-- Audits-und-Überprüfungen.sql (Regelmäßige Kontrolle der Maßnahmen, z. B. Sicherheitsprüfungen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Audits und Überprüfungen nur für große Unternehmen nötig?', 2, '[{"text": "Nein", "correct": true, "because": "Alle Organisationen profitieren"}, {"text": "Ja", "correct": false, "because": "Auch kleine Firmen brauchen Kontrolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Audits und Überprüfungen?', 3, '[{"text": "Sicherheitsmaßnahmen prüfen", "correct": true, "because": "Wirksamkeit sicherstellen"}, {"text": "Datenmenge maximieren", "correct": false, "because": "Nicht primär"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Sicherheit im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu Audits und Überprüfungen?', 5, '[{"text": "Sicherheitsprüfungen", "correct": true, "because": "Überprüft Maßnahmen"}, {"text": "Protokollanalysen", "correct": true, "because": "Identifiziert Schwächen"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Audits finden Schwachstellen. b) Sie sind nur einmalig nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Regelmäßigkeit erforderlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei Audits und Überprüfungen?', 4, '[{"text": "Sicherheitsrichtlinien", "correct": false, "because": "Prüfungsgrundlage"}, {"text": "Protokollierung", "correct": false, "because": "Nachverfolgbarkeit"}, {"text": "Visuelles Design", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Audits auch physische Sicherheitsmaßnahmen prüfen?', 2, '[{"text": "Ja", "correct": true, "because": "Umfassende Sicherheitskontrolle"}, {"text": "Nein", "correct": false, "because": "Nicht nur IT"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Mittel ist typisch für Audits?', 3, '[{"text": "Penetrationstest", "correct": true, "because": "Prüft Schwachstellen"}, {"text": "Hohe Serverleistung", "correct": false, "because": "Irrelevant"}, {"text": "Statische IPs", "correct": false, "because": "Kein Prüfungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden gehören zu Audits und Überprüfungen?', 5, '[{"text": "Log-Analyse", "correct": true, "because": "Erkennt Anomalien"}, {"text": "Compliance-Checks", "correct": true, "because": "Prüft Richtlinien"}, {"text": "Maximale Speichergröße", "correct": false, "because": "Nicht relevant"}, {"text": "Animationseffekte", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Audits verbessern Sicherheit. b) Sie sind nur für externe Prüfer. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch interne Audits möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Audits und Überprüfungen?', 4, '[{"text": "Prüfungsplan", "correct": false, "because": "Strukturiert Vorgehen"}, {"text": "Berichterstattung", "correct": false, "because": "Dokumentiert Ergebnisse"}, {"text": "Grafisches Design", "correct": true, "because": "Kein Sicherheitsaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Audits nur für IT-Systeme?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Prozesse und physische Sicherheit"}, {"text": "Ja", "correct": false, "because": "Umfassender Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bereiche prüfen Audits?', 4, '[{"text": "Zugriffskontrollen", "correct": true, "because": "Sichert Berechtigungen"}, {"text": "Netzwerksicherheit", "correct": true, "because": "Schützt Kommunikation"}, {"text": "Visuelles Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Audits nur einmalig sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Regelmäßige Prüfung nötig"}, {"text": "Ja", "correct": false, "because": "Kontinuierliche Kontrolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Audits?', 3, '[{"text": "Schwachstellenidentifikation", "correct": true, "because": "Risiken minimieren"}, {"text": "Schnelle Durchführung", "correct": false, "because": "Gründlichkeit zählt"}, {"text": "Schriftgröße", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Audits prüfen Sicherheitsmaßnahmen. b) Sie sind nur für Compliance.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Sicherheitsverbesserung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen unterstützen Audits?', 5, '[{"text": "Penetrationstests", "correct": true, "because": "Simuliert Angriffe"}, {"text": "Protokollüberprüfung", "correct": true, "because": "Analysiert Aktivitäten"}, {"text": "Maximale Speicherung", "correct": false, "because": "Nicht relevant"}, {"text": "Datenbankgröße", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Audits unwichtig?', 3, '[{"text": "Dokumentation", "correct": false, "because": "Ergebnisse festhalten"}, {"text": "Regelmäßigkeit", "correct": false, "because": "Kontinuierliche Kontrolle"}, {"text": "Animationseffekte", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Prüfen Audits auch Mitarbeiterverhalten?', 3, '[{"text": "Ja", "correct": true, "because": "Richtlinieneinhaltung testen"}, {"text": "Nein", "correct": false, "because": "Umfassender Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Audits rechtliche Anforderungen erfüllen?', 2, '[{"text": "Ja", "correct": true, "because": "Compliance oft Ziel"}, {"text": "Nein", "correct": false, "because": "Teil der Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Mittel wähle ich für Audits?', 4, '[{"text": "Sicherheitsprüfung", "correct": true, "because": "Überprüft Maßnahmen"}, {"text": "Zufällige Daten", "correct": false, "because": "Irrelevant"}, {"text": "Grafisches Design", "correct": false, "because": "Kein Schutzfokus"}]');

