
-- Software: Softwarearten - Spezialsoftware (Cloudlösungen SaaS)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Auswahl einer SaaS-Lösung für ein Unternehmen entscheidend?', 2, '[{"text": "Skalierbarkeit", "correct": true, "because": "Passt sich Wachstum an"}, {"text": "Farbe der Oberfläche", "correct": false, "because": "Kein funktionaler Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine SaaS-Lösung ohne Internetverbindung nutzbar?', 1, '[{"text": "Nein", "correct": true, "because": "SaaS basiert auf Cloud-Zugriff"}, {"text": "Ja", "correct": false, "because": "Internet ist zwingend erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind für eine SaaS-Lösung wichtig?', 5, '[{"text": "Automatische Updates", "correct": true, "because": "Hält Software aktuell"}, {"text": "Datensicherheit", "correct": true, "because": "Schützt Unternehmensdaten"}, {"text": "Gewicht des Servers", "correct": false, "because": "Irrelevant bei Cloud"}, {"text": "Zugriff von überall", "correct": true, "because": "Fördert Flexibilität"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen über SaaS-Lösungen richtig? a) Sie reduzieren lokale Hardwarekosten. b) Sie benötigen immer eine lokale Installation.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SaaS läuft in der Cloud"}, {"text": "Beides stimmt", "correct": false, "because": "Keine lokale Installation nötig"}, {"text": "Nur b) stimmt", "correct": false, "because": "Hardwarekosten sinken"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was würdest du bei der Bewertung einer SaaS-Lösung für ein Team ignorieren?', 2, '[{"text": "Kosten pro Nutzer", "correct": false, "because": "Wichtig für Budget"}, {"text": "Optisches Design", "correct": true, "because": "Kein Einfluss auf Funktion"}, {"text": "Verfügbarkeit", "correct": false, "because": "Entscheidend für Nutzung"}]');



-- Software: Softwarearten - Spezialsoftware (Cloudlösungen SaaS)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Auswahl einer SaaS-Lösung für ein Unternehmen entscheidend?', 2, '[{"text": "Skalierbarkeit", "correct": true, "because": "Passt sich Wachstum an"}, {"text": "Farbe der Benutzeroberfläche", "correct": false, "because": "Kein funktionaler Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine SaaS-Lösung ohne Internetverbindung nutzbar?', 1, '[{"text": "Nein", "correct": true, "because": "Cloud erfordert Online-Zugriff"}, {"text": "Ja", "correct": false, "because": "SaaS ist internetabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind für die Effektivität einer SaaS-Lösung wichtig?', 5, '[{"text": "Verfügbarkeit", "correct": true, "because": "Garantieren ständigen Zugriff"}, {"text": "Automatische Updates", "correct": true, "because": "Halten Software aktuell"}, {"text": "Lokale Speichergröße", "correct": false, "because": "Cloud-basiert"}, {"text": "Sicherheitsmaßnahmen", "correct": true, "because": "Schützen Daten"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen über SaaS-Lösungen richtig? a) Sie reduzieren lokale Hardwarekosten. b) Sie erfordern immer eigene Server.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SaaS nutzt Cloud-Server"}, {"text": "Beides stimmt", "correct": false, "because": "Eigene Server nicht nötig"}, {"text": "Nur b) stimmt", "correct": false, "because": "SaaS ist extern gehostet"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was würdest du bei der Bewertung einer SaaS-Lösung für ein Startup ignorieren?', 2, '[{"text": "Kostenstruktur", "correct": false, "because": "Wichtig für Budget"}, {"text": "Optisches Design", "correct": true, "because": "Kein Einfluss auf Funktion"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Entscheidend für Sicherheit"}]');



-- Software: Softwarearten - Spezialsoftware (Cloudlösungen SaaS)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Auswahl einer SaaS-Lösung für ein Unternehmen entscheidend?', 2, '[{"text": "Skalierbarkeit", "correct": true, "because": "Passt sich Wachstum an"}, {"text": "Farbe der Benutzeroberfläche", "correct": false, "because": "Kein funktionaler Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine SaaS-Lösung ohne Internetverbindung nutzbar?', 1, '[{"text": "Nein", "correct": true, "because": "Cloud erfordert Online-Zugriff"}, {"text": "Ja", "correct": false, "because": "SaaS ist internetabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind für eine SaaS-Lösung wichtig?', 5, '[{"text": "Verfügbarkeit", "correct": true, "because": "Gewährleistet ständigen Zugriff"}, {"text": "Automatische Updates", "correct": true, "because": "Hält Software aktuell"}, {"text": "Lokale Installationsgröße", "correct": false, "because": "SaaS ist cloudbasiert"}, {"text": "Datensicherheit", "correct": true, "because": "Schützt Unternehmensdaten"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen über SaaS-Lösungen richtig? a) Sie reduzieren Hardwarekosten. b) Sie erfordern lokale Server.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SaaS nutzt Cloud, keine Server"}, {"text": "Beides stimmt", "correct": false, "because": "Lokale Server nicht nötig"}, {"text": "Nur b) stimmt", "correct": false, "because": "Hardwarekosten sinken"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was würdest du bei der Bewertung einer SaaS-Lösung für ein kleines Team ignorieren?', 2, '[{"text": "Kosten pro Nutzer", "correct": false, "because": "Wichtig für Budget"}, {"text": "Optisches Design", "correct": true, "because": "Kein Einfluss auf Funktion"}, {"text": "Support-Verfügbarkeit", "correct": false, "because": "Entscheidend bei Problemen"}]');


