
-- Software: Softwarearten - Spezialsoftware (KI-Software)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist KI-Software immer für Datenanalyse geeignet?', 2, '[{"text": "Ja", "correct": true, "because": "Datenanalyse ist eine Kernstärke von KI"}, {"text": "Nein", "correct": false, "because": "Die meisten KI-Tools bieten dies an"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion einer KI-Software ist für die Automatisierung von Prozessen entscheidend?', 3, '[{"text": "Maschinelles Lernen", "correct": true, "because": "Ermöglicht selbstständige Optimierung"}, {"text": "Textverarbeitung", "correct": false, "because": "Nicht KI-spezifisch"}, {"text": "E-Mail-Integration", "correct": false, "because": "Sekundäre Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) KI-Software benötigt große Datenmengen zur Funktion. b) Sie ist nur für technische Unternehmen geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Daten sind essenziell für KI"}, {"text": "Beides stimmt", "correct": false, "because": "Auch andere Branchen nutzen KI"}, {"text": "Nur b) stimmt", "correct": false, "because": "Datenbedarf ist zentral"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal einer KI-Software solltest du für die Spracherkennung priorisieren?', 4, '[{"text": "Natürliche Sprachverarbeitung", "correct": true, "because": "Ermöglicht präzise Erkennung"}, {"text": "Design der Oberfläche", "correct": false, "because": "Kein Einfluss auf Funktion"}, {"text": "Installationsgröße", "correct": false, "because": "Technisch irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann KI-Software ohne Trainingsdaten effektiv arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Trainingsdaten sind für Lernprozesse nötig"}, {"text": "Ja", "correct": false, "because": "Ohne Daten keine Anpassung"}]');

-- Software: Softwarearten - Spezialsoftware (KI-Software)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist KI-Software immer für die Datenanalyse geeignet?', 2, '[{"text": "Ja", "correct": true, "because": "Datenanalyse ist eine Hauptanwendung"}, {"text": "Nein", "correct": false, "because": "KI ist oft dafür ausgelegt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion einer KI-Software ist für die Automatisierung von Prozessen entscheidend?', 3, '[{"text": "Maschinelles Lernen", "correct": true, "because": "Ermöglicht selbstständige Anpassung"}, {"text": "Textverarbeitung", "correct": false, "because": "Nicht KI-spezifisch"}, {"text": "E-Mail-Integration", "correct": false, "because": "Kein Kernmerkmal"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) KI-Software benötigt große Datenmengen zum Lernen. b) Sie ist nur für technische Unternehmen geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Daten sind essenziell für KI"}, {"text": "Beides stimmt", "correct": false, "because": "KI ist branchenübergreifend"}, {"text": "Nur b) stimmt", "correct": false, "because": "Datenbedarf ist zentral"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal einer KI-Software solltest du für die Spracherkennung priorisieren?', 4, '[{"text": "Natürliche Sprachverarbeitung", "correct": true, "because": "Ermöglicht präzise Erkennung"}, {"text": "Grafische Oberfläche", "correct": false, "because": "Sekundär zur Funktion"}, {"text": "Installationsgröße", "correct": false, "because": "Kein Einfluss auf Leistung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann KI-Software ohne Training effektiv arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Training ist für Funktionalität nötig"}, {"text": "Ja", "correct": false, "because": "Untrainierte KI ist ineffizient"}]');

-- Software: Softwarearten - Spezialsoftware (KI-Software)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist KI-Software immer für die Datenanalyse geeignet?', 2, '[{"text": "Ja", "correct": true, "because": "Datenanalyse ist eine Hauptanwendung von KI"}, {"text": "Nein", "correct": false, "because": "KI ist oft dafür ausgelegt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion einer KI-Software ist für die Automatisierung von Prozessen entscheidend?', 3, '[{"text": "Maschinelles Lernen", "correct": true, "because": "Ermöglicht selbstständige Anpassung"}, {"text": "Textverarbeitung", "correct": false, "because": "Nicht KI-spezifisch"}, {"text": "E-Mail-Integration", "correct": false, "because": "Kein Kernmerkmal"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) KI-Software benötigt große Datenmengen zur Funktion. b) Sie ist nur für technische Unternehmen geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "KI braucht Daten, ist aber branchenübergreifend"}, {"text": "Beides stimmt", "correct": false, "because": "Nicht nur technische Firmen"}, {"text": "Nur b) stimmt", "correct": false, "because": "Daten sind essenziell"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal einer KI-Software solltest du für die Spracherkennung priorisieren?', 4, '[{"text": "Natural Language Processing", "correct": true, "because": "Ermöglicht Sprachverarbeitung"}, {"text": "Design der Oberfläche", "correct": false, "because": "Kein Einfluss auf Funktion"}, {"text": "Speichergröße", "correct": false, "because": "Sekundär zur Technologie"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann KI-Software ohne Trainingsdaten effektiv arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Trainingsdaten sind essenziell"}, {"text": "Ja", "correct": false, "because": "Ohne Daten keine Lernbasis"}]');
