-- Arbeitsrecht Berufsbildung > Soziale gesellschaftliche Themen > Datenschutz > DSGVO Anforderungen
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen Fachinformatiker in einem IT-Betrieb die DSGVO-Anforderungen einhalten?', 2, '[{"text": "Ja", "correct": true, "because": "DSGVO gilt für alle, die personenbezogene Daten verarbeiten"}, {"text": "Nein", "correct": false, "because": "Gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine Einwilligung der Betroffenen laut DSGVO für die Verarbeitung personenbezogener Daten immer erforderlich?', 2, '[{"text": "Nein", "correct": true, "because": "Verarbeitung kann auch auf anderer Rechtsgrundlage basieren"}, {"text": "Ja", "correct": false, "because": "Nicht immer nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Verlangt die DSGVO von einem IT-Betrieb technische Schutzmaßnahmen für personenbezogene Daten?', 2, '[{"text": "Ja", "correct": true, "because": "Art. 32 DSGVO fordert technische und organisatorische Maßnahmen"}, {"text": "Nein", "correct": false, "because": "Schutzmaßnahmen sind Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Verstöße gegen DSGVO-Anforderungen in einem IT-Betrieb zu Bußgeldern führen?', 2, '[{"text": "Ja", "correct": true, "because": "DSGVO sieht Bußgelder bis 20 Mio. Euro vor"}, {"text": "Nein", "correct": false, "because": "Sanktionen möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Auszubildende in einem IT-Betrieb über die DSGVO-Anforderungen informiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Unterweisung ist Teil der Datenschutzpflicht"}, {"text": "Nein", "correct": false, "because": "Information ist erforderlich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Rechtsgrundlage ist für die Verarbeitung personenbezogener Daten gemäß DSGVO zwingend erforderlich?', 2, '[{"text": "Einwilligung oder gesetzliche Basis", "correct": true, "because": "Art. 6 DSGVO nennt Grundlagen"}, {"text": "Nur Einwilligung", "correct": false, "because": "Nicht ausschließlich"}, {"text": "Keine Grundlage nötig", "correct": false, "because": "Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Recht haben Betroffene gemäß DSGVO gegenüber einem IT-Betrieb?', 3, '[{"text": "Auskunftsrecht", "correct": true, "because": "Art. 15 DSGVO gibt Betroffenen Auskunft"}, {"text": "Recht auf längere Arbeitszeit", "correct": false, "because": "Kein DSGVO-Recht"}, {"text": "Recht auf Vergessenwerden", "correct": false, "because": "Auch richtig, aber nicht einzige Antwort"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme ist gemäß DSGVO zur Sicherung personenbezogener Daten in einem IT-Betrieb vorgeschrieben?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Technische Maßnahme nach Art. 32 DSGVO"}, {"text": "Öffentliche Speicherung", "correct": false, "because": "Verstößt gegen DSGVO"}, {"text": "Keine Sicherheitsvorkehrungen", "correct": false, "because": "Maßnahmen sind Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer muss gemäß DSGVO in einem IT-Betrieb einen Datenschutzbeauftragten benennen?', 2, '[{"text": "Unternehmen mit regelmäßiger Datenverarbeitung", "correct": true, "because": "Art. 37 DSGVO legt Kriterien"}, {"text": "Nur Auszubildende", "correct": false, "because": "Nicht deren Aufgabe"}, {"text": "Kunden", "correct": false, "because": "Kunden sind Betroffene"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflicht hat ein IT-Betrieb bei einem Datenleck gemäß DSGVO?', 3, '[{"text": "Meldung an die Aufsichtsbehörde", "correct": true, "because": "Art. 33 DSGVO fordert Meldung innerhalb 72 Stunden"}, {"text": "Ignorieren des Vorfalls", "correct": false, "because": "Verstoß gegen DSGVO"}, {"text": "Erhöhung der Arbeitszeit", "correct": false, "because": "Irrelevant"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Anforderungen stellt die DSGVO an einen IT-Betrieb?', 4, '[{"text": "Zweckbindung der Datenverarbeitung", "correct": true, "because": "Art. 5 DSGVO fordert Zweck"}, {"text": "Datensparsamkeit", "correct": true, "because": "Nur notwendige Daten erheben"}, {"text": "Unbegrenzte Datenspeicherung", "correct": false, "because": "Speicherbegrenzung vorgeschrieben"}, {"text": "Transparenz gegenüber Betroffenen", "correct": true, "because": "Art. 12 DSGVO fordert Information"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rechte haben Betroffene gemäß DSGVO gegenüber einem IT-Betrieb?', 3, '[{"text": "Auskunftsrecht", "correct": true, "because": "Art. 15 DSGVO"}, {"text": "Recht auf Löschung", "correct": true, "because": "Art. 17 DSGVO (Recht auf Vergessenwerden)"}, {"text": "Recht auf unbegrenzte Speicherung", "correct": false, "because": "Kein DSGVO-Recht"}, {"text": "Recht auf Datenübertragbarkeit", "correct": true, "because": "Art. 20 DSGVO"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche technischen Maßnahmen fordert die DSGVO von einem IT-Betrieb?', 4, '[{"text": "Verschlüsselung", "correct": true, "because": "Art. 32 DSGVO"}, {"text": "Zugangskontrollen", "correct": true, "because": "Schutz vor unbefugtem Zugriff"}, {"text": "Keine Sicherheitsvorkehrungen", "correct": false, "because": "Maßnahmen sind Pflicht"}, {"text": "Regelmäßige Sicherheitsüberprüfungen", "correct": true, "because": "Sicherstellung des Schutzniveaus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen drohen einem IT-Betrieb bei Verstößen gegen DSGVO-Anforderungen?', 3, '[{"text": "Hohe Bußgelder", "correct": true, "because": "Bis 20 Mio. Euro oder 4 % des Jahresumsatzes"}, {"text": "Imageschaden", "correct": true, "because": "Vertrauensverlust möglich"}, {"text": "Geringere Produktivität", "correct": false, "because": "Indirekt, nicht primär"}, {"text": "Verpflichtung zur Nachbesserung", "correct": true, "because": "Aufsichtsbehörde kann Maßnahmen anordnen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat ein IT-Betrieb gemäß DSGVO?', 3, '[{"text": "Dokumentation der Datenverarbeitung", "correct": true, "because": "Art. 30 DSGVO fordert Verzeichnis"}, {"text": "Meldung von Datenpannen", "correct": true, "because": "Art. 33 DSGVO"}, {"text": "Unbegrenzte Datenspeicherung", "correct": false, "because": "Speicherbegrenzung vorgeschrieben"}, {"text": "Benennung eines Datenschutzbeauftragten", "correct": true, "because": "Art. 37 DSGVO bei Bedarf"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die DSGVO verlangt technische Schutzmaßnahmen für Daten in einem IT-Betrieb. b) Eine Einwilligung ist immer für die Datenverarbeitung nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schutzmaßnahmen ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Betroffene haben ein Auskunftsrecht gemäß DSGVO. b) Ein IT-Betrieb muss Datenpannen melden.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Auskunftsrecht und Meldepflicht"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Verstöße gegen die DSGVO können Bußgelder nach sich ziehen. b) Die DSGVO gilt nur für große IT-Betriebe.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Bußgelder ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die DSGVO fordert Datensparsamkeit von einem IT-Betrieb. b) Auszubildende müssen über DSGVO-Anforderungen informiert werden.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Datensparsamkeit und Unterweisung"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein IT-Betrieb muss einen Datenschutzbeauftragten benennen, wenn regelmäßig Daten verarbeitet werden. b) Die DSGVO erlaubt unbegrenzte Datenspeicherung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Datenschutzbeauftragter ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

