-- Arbeitsrecht Berufsbildung > Soziale gesellschaftliche Themen > Datenschutz > Unternehmensrichtlinien
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen Unternehmensrichtlinien in einem IT-Betrieb die DSGVO berücksichtigen?', 2, '[{"text": "Ja", "correct": true, "because": "DSGVO ist für alle Unternehmen verbindlich"}, {"text": "Nein", "correct": false, "because": "Gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Unternehmensrichtlinien den Umgang mit personenbezogenen Daten für Fachinformatiker regeln?', 2, '[{"text": "Ja", "correct": true, "because": "Richtlinien legen interne Prozesse fest"}, {"text": "Nein", "correct": false, "because": "Regelung ist üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es erforderlich, dass Unternehmensrichtlinien in einem IT-Betrieb regelmäßig aktualisiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Änderungen in Gesetzen oder Technologien erfordern Anpassung"}, {"text": "Nein", "correct": false, "because": "Aktualisierung ist notwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Unternehmensrichtlinien die Verantwortlichkeiten für den Datenschutz in einem IT-Betrieb festlegen?', 2, '[{"text": "Ja", "correct": true, "because": "Richtlinien definieren Rollen und Pflichten"}, {"text": "Nein", "correct": false, "because": "Festlegung ist üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Unternehmensrichtlinien in einem IT-Betrieb Schulungen zum Datenschutz vorschreiben?', 2, '[{"text": "Ja", "correct": true, "because": "Schulungen sind Teil der DSGVO-Compliance"}, {"text": "Nein", "correct": false, "because": "Schulungen sind erforderlich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz bildet die Grundlage für Datenschutz-Unternehmensrichtlinien in einem IT-Betrieb?', 2, '[{"text": "Datenschutz-Grundverordnung (DSGVO)", "correct": true, "because": "DSGVO ist die EU-weite Grundlage"}, {"text": "ArbSchG", "correct": false, "because": "Regelt Arbeitsschutz"}, {"text": "BBiG", "correct": false, "because": "Regelt Ausbildung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptziel von Unternehmensrichtlinien zum Datenschutz in einem IT-Betrieb?', 3, '[{"text": "Sicherstellung der DSGVO-Compliance", "correct": true, "because": "Richtlinien gewährleisten Gesetzeskonformität"}, {"text": "Erhöhung der Arbeitszeit", "correct": false, "because": "Kein Ziel"}, {"text": "Reduktion der Produktivität", "correct": false, "because": "Nicht beabsichtigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme sollte in Unternehmensrichtlinien für Fachinformatiker festgelegt sein?', 3, '[{"text": "Sichere Datenverarbeitung", "correct": true, "because": "Schützt personenbezogene Daten"}, {"text": "Offene Datenfreigabe", "correct": false, "because": "Verstößt gegen DSGVO"}, {"text": "Keine Dokumentation", "correct": false, "because": "Dokumentation ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer ist typischerweise für die Einhaltung der Unternehmensrichtlinien zum Datenschutz in einem IT-Betrieb verantwortlich?', 2, '[{"text": "Datenschutzbeauftragter", "correct": true, "because": "DSGVO fordert Verantwortung"}, {"text": "Auszubildende", "correct": false, "because": "Nicht deren Aufgabe"}, {"text": "Kunden", "correct": false, "because": "Kunden sind Betroffene"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt sollte in Unternehmensrichtlinien für den Datenschutz in einem IT-Betrieb geregelt sein?', 3, '[{"text": "Verfahren bei Datenpannen", "correct": true, "because": "DSGVO Art. 33 fordert Meldepflicht"}, {"text": "Erhöhung der Arbeitsbelastung", "correct": false, "because": "Kein Ziel"}, {"text": "Ignorieren von Datenschutzverstößen", "correct": false, "because": "Verstoß gegen DSGVO"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente sollten Unternehmensrichtlinien zum Datenschutz in einem IT-Betrieb enthalten?', 4, '[{"text": "Regeln zur Datenverarbeitung", "correct": true, "because": "DSGVO fordert klare Prozesse"}, {"text": "Einwilligungsmanagement", "correct": true, "because": "Einwilligung ist Grundlage"}, {"text": "Keine Dokumentation", "correct": false, "because": "Dokumentation ist Pflicht"}, {"text": "Verfahren bei Datenpannen", "correct": true, "because": "Meldepflicht geregelt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Unternehmensrichtlinien zum Datenschutz einem IT-Betrieb?', 3, '[{"text": "Rechtssicherheit", "correct": true, "because": "Einhaltung der DSGVO"}, {"text": "Schutz vor Bußgeldern", "correct": true, "because": "Verstösse werden vermieden"}, {"text": "Geringere Sicherheit", "correct": false, "because": "Sicherheit wird erhöht"}, {"text": "Verbessertes Vertrauen der Kunden", "correct": true, "because": "Datenschutz stärkt Reputation"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile können Unternehmensrichtlinien zum Datenschutz für einen IT-Betrieb haben?', 4, '[{"text": "Verwaltungsaufwand", "correct": true, "because": "Dokumentation und Schulung nötig"}, {"text": "Kosten für Umsetzung", "correct": true, "because": "Investitionen erforderlich"}, {"text": "Weniger Datensicherheit", "correct": false, "because": "Sicherheit wird erhöht"}, {"text": "Zeitaufwand für Schulungen", "correct": true, "because": "Mitarbeiter müssen geschult werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche gesetzlichen Grundlagen beeinflussen Unternehmensrichtlinien zum Datenschutz in einem IT-Betrieb?', 3, '[{"text": "Datenschutz-Grundverordnung (DSGVO)", "correct": true, "because": "EU-weite Regelung"}, {"text": "Bundesdatenschutzgesetz (BDSG)", "correct": true, "because": "Nationale Ergänzung zur DSGVO"}, {"text": "ArbSchG", "correct": false, "because": "Regelt Arbeitsschutz"}, {"text": "Telemediengesetz (TMG)", "correct": true, "because": "Regelt digitale Dienste"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sollten Unternehmensrichtlinien für Fachinformatiker zum Datenschutz abdecken?', 3, '[{"text": "Zugriffsrechte auf Daten", "correct": true, "because": "Schützt vor unbefugtem Zugriff"}, {"text": "Verwendung von Passwörtern", "correct": true, "because": "Sichert Daten"}, {"text": "Keine Schulungspflicht", "correct": false, "because": "Schulung ist erforderlich"}, {"text": "Verhalten bei Datenpannen", "correct": true, "because": "Reaktion auf Vorfälle"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Unternehmensrichtlinien müssen die DSGVO berücksichtigen. b) Unternehmensrichtlinien sind freiwillig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DSGVO ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Unternehmensrichtlinien regeln den Umgang mit personenbezogenen Daten. b) Unternehmensrichtlinien müssen regelmäßig aktualisiert werden.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Regelung und Aktualisierung"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Unternehmensrichtlinien legen Verantwortlichkeiten für den Datenschutz fest. b) Unternehmensrichtlinien erhöhen die Arbeitsbelastung ohne Nutzen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verantwortlichkeiten ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Unternehmensrichtlinien schützen vor DSGVO-Bußgeldern. b) Unternehmensrichtlinien sind nur für große IT-Betriebe relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Bußgeldschutz ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Unternehmensrichtlinien schreiben Schulungen zum Datenschutz vor. b) Unternehmensrichtlinien haben keine Kosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schulungen ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

