-- Ja/Nein-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Wird die Gemeinkostenverteilung genutzt, um indirekte Kosten auf Produkte zu verteilen?', 2, '[{"text": "Ja", "correct": true, "because": "Hauptzweck der Gemeinkostenverteilung"}, {"text": "Nein", "correct": false, "because": "Verteilung ist zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Gemeinkosten ohne Verteilung direkt einem Produkt zugeordnet werden?', 2, '[{"text": "Ja", "correct": false, "because": "Gemeinkosten sind indirekt und benötigen Verteilung"}, {"text": "Nein", "correct": true, "because": "Direkte Zuordnung ist bei Einzelkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Gemeinkostenverteilung ein Teil der Leistungsrechnung?', 2, '[{"text": "Ja", "correct": true, "because": "Bestandteil der Kosten- und Leistungsrechnung"}, {"text": "Nein", "correct": false, "because": "Sie gehört dazu"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine ungenaue Gemeinkostenverteilung die Produktkalkulation verfälschen?', 2, '[{"text": "Ja", "correct": true, "because": "Ungenauigkeit führt zu falschen Kosten"}, {"text": "Nein", "correct": false, "because": "Verfälschung ist möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Gemeinkosten immer gleichmäßig auf alle Produkte verteilt werden?', 2, '[{"text": "Ja", "correct": false, "because": "Verteilung kann unterschiedlich erfolgen"}, {"text": "Nein", "correct": true, "because": "Flexible Methoden möglich"}]');

-- Single-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Gemeinkostenverteilung?', 2, '[{"text": "Zuordnung indirekter Kosten auf Kostenobjekte", "correct": true, "because": "Primäre Funktion"}, {"text": "Berechnung der Fixkosten", "correct": false, "because": "Zu eng gefasst"}, {"text": "Festlegung der Verkaufspreise", "correct": false, "because": "Folge, nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kostenart wird durch die Gemeinkostenverteilung aufgeteilt?', 3, '[{"text": "Indirekte Kosten", "correct": true, "because": "Gemeinkosten sind indirekt"}, {"text": "Direkte Einzelkosten", "correct": false, "because": "Bereits zugeordnet"}, {"text": "Variable Kosten", "correct": false, "because": "Nicht spezifisch genug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird häufig für die Gemeinkostenverteilung verwendet?', 2, '[{"text": "Zuschlagssätze", "correct": true, "because": "Übliche Praxis"}, {"text": "Direkte Abrechnung", "correct": false, "because": "Für Einzelkosten"}, {"text": "Pauschalbeträge", "correct": false, "because": "Weniger genau"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn Gemeinkosten nicht verteilt werden?', 3, '[{"text": "Produktkosten sind ungenau", "correct": true, "because": "Kosten bleiben unzugeteilt"}, {"text": "Einzelkosten steigen", "correct": false, "because": "Kein direkter Einfluss"}, {"text": "Fixkosten sinken", "correct": false, "because": "Keine Verbindung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Basis wird oft für die Gemeinkostenverteilung herangezogen?', 2, '[{"text": "Einzelkosten", "correct": true, "because": "Häufige Verteilungsgrundlage"}, {"text": "Umsatzerlöse", "correct": false, "because": "Weniger üblich"}, {"text": "Gewinne", "correct": false, "because": "Keine Basis"}]');

-- Multiple-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welche Kostenarten gehören zu den Gemeinkosten, die verteilt werden?', 4, '[{"text": "Fertigungs-Gemeinkosten", "correct": true, "because": "Typische Gemeinkosten"}, {"text": "Verwaltungs-Gemeinkosten", "correct": true, "because": "Ebenfalls verteilt"}, {"text": "Direkte Materialkosten", "correct": false, "because": "Einzelkosten"}, {"text": "Vertriebs-Gemeinkosten", "correct": true, "because": "Indirekte Kosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden können für die Gemeinkostenverteilung genutzt werden?', 3, '[{"text": "Zuschlagssätze", "correct": true, "because": "Häufige Methode"}, {"text": "Kostenstellenrechnung", "correct": true, "because": "Zwischenschritt"}, {"text": "Direkte Zuordnung", "correct": false, "because": "Für Einzelkosten"}, {"text": "Stufenleiterverfahren", "correct": true, "because": "Verfeinerte Verteilung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folgen kann eine fehlerhafte Gemeinkostenverteilung haben?', 4, '[{"text": "Verfälschte Produktkosten", "correct": true, "because": "Ungenauigkeit"}, {"text": "Über- oder Unterdeckung der Kosten", "correct": true, "because": "Falsche Zuordnung"}, {"text": "Senkung der Einzelkosten", "correct": false, "because": "Kein Effekt"}, {"text": "Beeinflussung der Preisgestaltung", "correct": true, "because": "Kostenbasis falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Gemeinkostenverteilung?', 3, '[{"text": "Genauere Produktkalkulation", "correct": true, "because": "Kosten werden zugeteilt"}, {"text": "Transparenz der Kostenstruktur", "correct": true, "because": "Klarheit"}, {"text": "Reduzierung der Gemeinkosten", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Bessere Entscheidungsgrundlage", "correct": true, "because": "Kostenverständnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sind bei der Gemeinkostenverteilung typisch?', 3, '[{"text": "Ermittlung der Gemeinkosten", "correct": true, "because": "Ausgangspunkt"}, {"text": "Festlegung der Verteilungsgrundlage", "correct": true, "because": "Z. B. Einzelkosten"}, {"text": "Festsetzung der Verkaufspreise", "correct": false, "because": "Folgeschritt"}, {"text": "Anwendung von Zuschlagssätzen", "correct": true, "because": "Verteilungsmethode"}]');

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Gemeinkostenverteilung verteilt indirekte Kosten. b) Sie betrifft nur direkte Kosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (indirekte Kosten)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Zuschlagssätze sind eine Methode der Gemeinkostenverteilung. b) Gemeinkosten werden nie verteilt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (Verteilung ist Zweck)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Fehlerhafte Verteilung verfälscht die Kalkulation. b) Gemeinkostenverteilung ist optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (wichtig für Genauigkeit)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Gemeinkostenverteilung verbessert die Kostentransparenz. b) Sie erfolgt immer gleichmäßig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (flexible Methoden)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Gemeinkostenverteilung ist Teil der Leistungsrechnung. b) Sie beeinflusst die Produktkosten.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "a) Leistungsrechnung, b) Produktkosten"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]');

