-- Arbeitsrecht Berufsbildung > Wirtschaftliche Zusammenhänge > Vor- Nachteile von Unternehmensformen > Haftungsbeschränkung bei GmbH
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Schützt die Haftungsbeschränkung einer IT-GmbH das Privatvermögen der Gesellschafter?', 2, '[{"text": "Ja", "correct": true, "because": "Die GmbH haftet nur mit dem Gesellschaftsvermögen"}, {"text": "Nein", "correct": false, "because": "Privatvermögen bleibt geschützt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Haftungsbeschränkung einer IT-GmbH ein Vorteil gegenüber einem Einzelunternehmen?', 2, '[{"text": "Ja", "correct": true, "because": "Einzelunternehmen haftet unbeschränkt"}, {"text": "Nein", "correct": false, "because": "Haftungsbeschränkung ist ein klarer Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Haftungsbeschränkung einer IT-GmbH bei grober Fahrlässigkeit der Geschäftsführung durchbrochen werden?', 2, '[{"text": "Ja", "correct": true, "because": "Bei grober Fahrlässigkeit kann persönliche Haftung entstehen"}, {"text": "Nein", "correct": false, "because": "Haftungsdurchgriff ist möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Erhöht die Haftungsbeschränkung einer IT-GmbH das Vertrauen von Gläubigern?', 2, '[{"text": "Nein", "correct": true, "because": "Gläubiger haben nur Zugriff auf Gesellschaftsvermögen"}, {"text": "Ja", "correct": false, "because": "Vertrauen kann sinken"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Haftungsbeschränkung einer IT-GmbH ein Nachteil für die Kapitalbeschaffung?', 2, '[{"text": "Nein", "correct": true, "because": "Haftungsbeschränkung ist ein Vorteil für Investoren"}, {"text": "Ja", "correct": false, "because": "Fördert Kapitalaufnahme"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Was bedeutet die Haftungsbeschränkung einer IT-GmbH?', 2, '[{"text": "Haftung nur mit Gesellschaftsvermögen", "correct": true, "because": "Privatvermögen bleibt geschützt"}, {"text": "Haftung mit Privatvermögen", "correct": false, "because": "Das gilt für Einzelunternehmen"}, {"text": "Keine Haftung", "correct": false, "because": "Haftung besteht, aber beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Vorteil bietet die Haftungsbeschränkung einer IT-GmbH gegenüber einer OHG?', 3, '[{"text": "Schutz des Privatvermögens", "correct": true, "because": "OHG haftet unbeschränkt"}, {"text": "Einfachere Gründung", "correct": false, "because": "OHG ist einfacher zu gründen"}, {"text": "Geringere Steuerlast", "correct": false, "because": "Steuern sind unabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'In welchem Fall kann die Haftungsbeschränkung einer IT-GmbH durchbrochen werden?', 3, '[{"text": "Bei grober Fahrlässigkeit der Geschäftsführung", "correct": true, "because": "Haftungsdurchgriff möglich"}, {"text": "Bei normaler Geschäftstätigkeit", "correct": false, "because": "Normale Tätigkeit schützt"}, {"text": "Bei hohem Umsatz", "correct": false, "because": "Umsatz irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz regelt die Haftungsbeschränkung einer IT-GmbH?', 2, '[{"text": "GmbH-Gesetz (GmbHG)", "correct": true, "because": "GmbHG regelt die GmbH"}, {"text": "HGB", "correct": false, "because": "HGB ergänzt, aber GmbHG ist spezifisch"}, {"text": "AktG", "correct": false, "because": "Gilt für AG"}]'),
('00000000-0000-0000-0000-000000000000', 'Warum ist die Haftungsbeschränkung für IT-Startups attraktiv?', 3, '[{"text": "Sie reduziert das persönliche Risiko", "correct": true, "because": "Privatvermögen bleibt geschützt"}, {"text": "Sie senkt die Gründungskosten", "correct": false, "because": "Kosten sind unabhängig"}, {"text": "Sie erhöht die Steuerlast", "correct": false, "because": "Steuerlast bleibt gleich"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Haftungsbeschränkung einer IT-GmbH?', 4, '[{"text": "Schutz des Privatvermögens", "correct": true, "because": "Haftung nur mit Gesellschaftsvermögen"}, {"text": "Erhöhtes Vertrauen von Investoren", "correct": true, "because": "Weniger Risiko für Gesellschafter"}, {"text": "Höhere Steuerlast", "correct": false, "because": "Steuerlast unabhängig"}, {"text": "Attraktivität für Startups", "correct": true, "because": "Risiko wird reduziert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile könnte die Haftungsbeschränkung einer IT-GmbH mit sich bringen?', 3, '[{"text": "Geringeres Vertrauen von Gläubigern", "correct": true, "because": "Nur Gesellschaftsvermögen greifbar"}, {"text": "Höhere Gründungskosten", "correct": true, "because": "Mindestkapital erforderlich"}, {"text": "Persönliche Haftung der Gesellschafter", "correct": false, "because": "Nicht bei GmbH"}, {"text": "Eingeschränkte Kapitalaufnahme", "correct": false, "because": "Kapitalaufnahme möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aussagen treffen auf die Haftungsbeschränkung einer IT-GmbH zu?', 4, '[{"text": "Schützt das Privatvermögen der Gesellschafter", "correct": true, "because": "Haftung nur mit Gesellschaftsvermögen"}, {"text": "Kann bei Missbrauch durchbrochen werden", "correct": true, "because": "Haftungsdurchgriff möglich"}, {"text": "Erhöht das Risiko für Gesellschafter", "correct": false, "because": "Risiko wird reduziert"}, {"text": "Vorteil gegenüber Einzelunternehmen", "correct": true, "because": "Einzelunternehmen haftet voll"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren könnten die Haftungsbeschränkung einer IT-GmbH beeinflussen?', 3, '[{"text": "Grobe Fahrlässigkeit der Geschäftsführung", "correct": true, "because": "Kann Haftungsdurchgriff auslösen"}, {"text": "Unterkapitalisierung der GmbH", "correct": true, "because": "Kann Haftungsdurchgriff begründen"}, {"text": "Hohe Umsätze", "correct": false, "because": "Umsatz ist irrelevant"}, {"text": "Missbrauch der Rechtsform", "correct": true, "because": "Kann persönliche Haftung auslösen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was unterscheidet die Haftungsbeschränkung der GmbH von der OHG für einen IT-Betrieb?', 3, '[{"text": "GmbH haftet nur mit Gesellschaftsvermögen", "correct": true, "because": "OHG haftet unbeschränkt"}, {"text": "OHG haftet mit Privatvermögen", "correct": true, "because": "OHG hat persönliche Haftung"}, {"text": "GmbH hat höhere Gründungskosten", "correct": true, "because": "Mindestkapital erforderlich"}, {"text": "OHG ist haftungsbeschränkt", "correct": false, "because": "OHG haftet unbeschränkt"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Haftungsbeschränkung der IT-GmbH schützt das Privatvermögen. b) Die Haftungsbeschränkung gilt auch bei grober Fahrlässigkeit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Privatvermögen ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Haftungsbeschränkung der IT-GmbH ist ein Vorteil gegenüber der OHG. b) Gläubiger haben Zugriff auf das Privatvermögen der Gesellschafter.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vorteil ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Haftungsbeschränkung kann bei Missbrauch durchbrochen werden. b) Die Haftungsbeschränkung senkt die Gründungskosten einer IT-GmbH.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Missbrauch ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Haftungsbeschränkung der IT-GmbH ist attraktiv für Investoren. b) Die Haftungsbeschränkung erhöht das Risiko für Gesellschafter.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Attraktivität ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Haftungsbeschränkung der IT-GmbH schützt vor persönlicher Haftung. b) Sie ist ein Nachteil für die Kapitalaufnahme.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schutz ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

