-- Arbeitsrecht Berufsbildung > Wirtschaftliche Zusammenhänge > Vor- Nachteile von Unternehmensformen > Persönliche Haftung bei OHG
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Haften die Gesellschafter einer IT-OHG persönlich mit ihrem Privatvermögen?', 2, '[{"text": "Ja", "correct": true, "because": "Die OHG hat unbeschränkte persönliche Haftung"}, {"text": "Nein", "correct": false, "because": "Persönliche Haftung ist ein Merkmal der OHG"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die persönliche Haftung bei einer IT-OHG auf das Gesellschaftsvermögen beschränkt?', 2, '[{"text": "Nein", "correct": true, "because": "Die Haftung erstreckt sich auf das Privatvermögen"}, {"text": "Ja", "correct": false, "because": "Haftung ist unbeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die persönliche Haftung einer IT-OHG durch Verträge ausgeschlossen werden?', 2, '[{"text": "Nein", "correct": true, "because": "Persönliche Haftung ist gesetzlich festgelegt"}, {"text": "Ja", "correct": false, "because": "Haftung kann nicht ausgeschlossen werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Besteht bei einer IT-OHG die Gefahr, dass private Schulden eines Gesellschafters die Firma belasten?', 2, '[{"text": "Nein", "correct": true, "because": "Private Schulden betreffen die OHG nicht direkt"}, {"text": "Ja", "correct": false, "because": "Haftung geht nur von Firma zu Gesellschafter"}]'),
('00000000-0000-0000-0000-000000000000', 'Erstreckt sich die persönliche Haftung einer IT-OHG auch auf zukünftige Schulden der Gesellschaft?', 2, '[{"text": "Ja", "correct": true, "because": "Haftung gilt für alle Schulden der OHG"}, {"text": "Nein", "correct": false, "because": "Haftung ist umfassend"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Was bedeutet die persönliche Haftung bei einer IT-OHG?', 2, '[{"text": "Gesellschafter haften mit ihrem Privatvermögen", "correct": true, "because": "Haftung ist unbeschränkt"}, {"text": "Haftung ist auf das Gesellschaftsvermögen begrenzt", "correct": false, "because": "Das gilt für GmbH"}, {"text": "Keine Haftung der Gesellschafter", "correct": false, "because": "Haftung besteht"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie weit reicht die persönliche Haftung einer IT-OHG?', 3, '[{"text": "Bis zum gesamten Privatvermögen der Gesellschafter", "correct": true, "because": "Unbeschränkte Haftung"}, {"text": "Nur bis zum eingebrachten Kapital", "correct": false, "because": "Keine Kapitalgrenze"}, {"text": "Nur bis zur Hälfte des Vermögens", "correct": false, "because": "Haftung ist vollständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Nachteil ergibt sich aus der persönlichen Haftung bei einer IT-OHG?', 3, '[{"text": "Hohes finanzielles Risiko für Gesellschafter", "correct": true, "because": "Privatvermögen gefährdet"}, {"text": "Eingeschränkte Kapitalbeschaffung", "correct": false, "because": "Das ist ein anderer Nachteil"}, {"text": "Geringe Flexibilität", "correct": false, "because": "Nicht direkt mit Haftung verbunden"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer haftet bei einer IT-OHG für Schulden der Gesellschaft?', 2, '[{"text": "Alle Gesellschafter gemeinsam", "correct": true, "because": "Gesamtschuldnerische Haftung"}, {"text": "Nur der Geschäftsführer", "correct": false, "because": "Kein Geschäftsführer bei OHG"}, {"text": "Die Gesellschaft allein", "correct": false, "because": "Gesellschafter haften persönlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz regelt die persönliche Haftung einer IT-OHG?', 3, '[{"text": "Handelsgesetzbuch (HGB)", "correct": true, "because": "HGB regelt die OHG-Haftung"}, {"text": "GmbHG", "correct": false, "because": "Gilt für GmbH"}, {"text": "AktG", "correct": false, "because": "Gilt für AG"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale beschreiben die persönliche Haftung bei einer IT-OHG?', 4, '[{"text": "Unbeschränkt", "correct": true, "because": "Haftung umfasst Privatvermögen"}, {"text": "Gesamtschuldnerisch", "correct": true, "because": "Alle Gesellschafter haften gemeinsam"}, {"text": "Beschränkt auf Gesellschaftsvermögen", "correct": false, "because": "Haftung ist unbeschränkt"}, {"text": "Gilt für alle Schulden der OHG", "correct": true, "because": "Umfassende Haftung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile ergeben sich aus der persönlichen Haftung einer IT-OHG?', 3, '[{"text": "Risiko für das Privatvermögen", "correct": true, "because": "Gesellschafter haften voll"}, {"text": "Hohe finanzielle Belastung bei Insolvenz", "correct": true, "because": "Privatvermögen betroffen"}, {"text": "Eingeschränkte Kapitalaufnahme", "correct": false, "because": "Nicht direkt mit Haftung verbunden"}, {"text": "Abhängigkeit von Mitgesellschaftern", "correct": true, "because": "Fehlentscheidungen treffen alle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Auswirkungen hat die persönliche Haftung einer IT-OHG auf die Gesellschafter?', 4, '[{"text": "Verlust des Privatvermögens möglich", "correct": true, "because": "Haftung ist unbeschränkt"}, {"text": "Gemeinsame Haftung für Schulden", "correct": true, "because": "Gesamtschuldnerisch"}, {"text": "Keine Haftung für Geschäftsschulden", "correct": false, "because": "Haftung besteht"}, {"text": "Persönliches Risiko bei Fehlentscheidungen", "correct": true, "because": "Alle haften für Fehler"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen die persönliche Haftung einer IT-OHG riskant?', 3, '[{"text": "Unbeschränkte Haftung", "correct": true, "because": "Privatvermögen gefährdet"}, {"text": "Gesamtschuldnerische Haftung", "correct": true, "because": "Alle Gesellschafter betroffen"}, {"text": "Mindestkapitalvorgabe", "correct": false, "because": "Keine Kapitalvorgabe bei OHG"}, {"text": "Geschäftliche Fehlentscheidungen", "correct": true, "because": "Fehler erhöhen Risiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Was unterscheidet die persönliche Haftung einer IT-OHG von der einer GmbH?', 3, '[{"text": "OHG haftet unbeschränkt", "correct": true, "because": "GmbH haftet beschränkt"}, {"text": "GmbH haftet nur mit Gesellschaftsvermögen", "correct": true, "because": "OHG mit Privatvermögen"}, {"text": "OHG haftet nur mit Gesellschaftsvermögen", "correct": false, "because": "OHG haftet unbeschränkt"}, {"text": "GmbH hat höheres Risiko", "correct": false, "because": "OHG hat höheres Risiko"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die persönliche Haftung einer IT-OHG erstreckt sich auf das Privatvermögen. b) Die Haftung ist auf das Gesellschaftsvermögen beschränkt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Privatvermögen ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Alle Gesellschafter einer IT-OHG haften gesamtschuldnerisch. b) Persönliche Haftung erhöht das finanzielle Risiko.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Gesamtschuldnerisch und Risiko sind Merkmale"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die persönliche Haftung einer IT-OHG gilt für alle Schulden. b) Die Haftung kann vertraglich ausgeschlossen werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Alle Schulden ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Persönliche Haftung macht die IT-OHG riskanter als die GmbH. b) Die OHG haftet nur mit dem Privatvermögen eines Gesellschafters.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Riskanter ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die persönliche Haftung einer IT-OHG betrifft alle Gesellschafter. b) Private Schulden eines Gesellschafters gefährden die OHG direkt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Alle haften, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

