INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Wirtschaftliche Aspekte > Kalkulation > Handelskalkulationen
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen bei Handelskalkulationen immer die Einkaufspreise berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Grundlage der Kalkulation"}, {"text": "Nein", "correct": false, "because": "Einkaufspreise sind essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Handelskalkulationen ohne Rücksicht auf Rabatte durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Rabatte beeinflussen den Netto-Einkaufspreis"}, {"text": "Ja", "correct": false, "because": "Rabatte sind relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist der Verkaufspreis in der Handelskalkulation unabhängig vom Gewinnzuschlag?', 2, '[{"text": "Nein", "correct": true, "because": "Gewinnzuschlag bestimmt den Verkaufspreis"}, {"text": "Ja", "correct": false, "because": "Zuschlag ist maßgeblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Handelskalkulationen ohne Berücksichtigung der Umsatzsteuer korrekt sein?', 2, '[{"text": "Nein", "correct": true, "because": "Umsatzsteuer ist gesetzlich vorgeschrieben"}, {"text": "Ja", "correct": false, "because": "Steuer ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Handelskalkulationen nur für große Unternehmen relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle Handelsunternehmen"}, {"text": "Ja", "correct": false, "because": "Universell anwendbar"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor ist die Basis der Handelskalkulation?', 3, '[{"text": "Einkaufspreis", "correct": true, "because": "Ausgangspunkt der Kalkulation"}, {"text": "Transportkosten", "correct": false, "because": "Zusatzkosten"}, {"text": "Design", "correct": false, "because": "Nicht kalkulationsrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Begriff beschreibt den Preis nach Abzug des Rabatts?', 2, '[{"text": "Netto-Einkaufspreis", "correct": true, "because": "Einkaufspreis abzüglich Rabatt"}, {"text": "Brutto-Verkaufspreis", "correct": false, "because": "Inklusive Steuer"}, {"text": "Listenpreis", "correct": false, "because": "Vor Rabatt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Zuschlag wird in der Handelskalkulation auf den Netto-Einkaufspreis addiert?', 2, '[{"text": "Gewinnzuschlag", "correct": true, "because": "Erhöht den Preis für Gewinn"}, {"text": "Rabatt", "correct": false, "because": "Reduziert den Preis"}, {"text": "Skonto", "correct": false, "because": "Zahlungsanreiz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Steuer wird in der Handelskalkulation zum Netto-Verkaufspreis hinzugefügt?', 3, '[{"text": "Umsatzsteuer", "correct": true, "because": "Gesetzlich vorgeschrieben"}, {"text": "Einkommenssteuer", "correct": false, "because": "Unternehmenssteuer"}, {"text": "Gewerbesteuer", "correct": false, "because": "Nicht verkaufsbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Handelskalkulation?', 2, '[{"text": "Festlegung des Verkaufspreises", "correct": true, "because": "Ziel ist der Endpreis"}, {"text": "Kostensenkung", "correct": false, "because": "Sekundär"}, {"text": "Lieferzeitoptimierung", "correct": false, "because": "Logistisch"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Handelskalkulation?', 4, '[{"text": "Einkaufspreis", "correct": true, "because": "Basis der Kalkulation"}, {"text": "Rabatt", "correct": true, "because": "Reduziert den Preis"}, {"text": "Gewinnzuschlag", "correct": true, "because": "Bestimmt den Gewinn"}, {"text": "Lieferzeit", "correct": false, "because": "Logistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen den Netto-Einkaufspreis?', 3, '[{"text": "Listenpreis", "correct": true, "because": "Ausgangswert"}, {"text": "Rabatt", "correct": true, "because": "Preisnachlass"}, {"text": "Skonto", "correct": true, "because": "Zahlungsanreiz"}, {"text": "Umsatzsteuer", "correct": false, "because": "Nach Netto"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Zuschläge werden in der Handelskalkulation berücksichtigt?', 3, '[{"text": "Gewinnzuschlag", "correct": true, "because": "Für den Gewinn"}, {"text": "Handlungskosten", "correct": true, "because": "Betriebskosten"}, {"text": "Umsatzsteuer", "correct": true, "because": "Gesetzliche Steuer"}, {"text": "Transportkosten", "correct": false, "because": "Optional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine genaue Handelskalkulation?', 4, '[{"text": "Preisgestaltung", "correct": true, "because": "Definiert Verkaufspreis"}, {"text": "Gewinnmaximierung", "correct": true, "because": "Optimiert Ertrag"}, {"text": "Transparenz", "correct": true, "because": "Klarheit über Kosten"}, {"text": "Schnelle Lieferung", "correct": false, "because": "Logistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können bei der Handelskalkulation auftreten?', 3, '[{"text": "Falsche Rabatte", "correct": true, "because": "Verfälscht Netto-Preis"}, {"text": "Unbekannte Umsatzsteuer", "correct": true, "because": "Führt zu Fehlern"}, {"text": "Fehlende Kosten", "correct": true, "because": "Unrealistischer Preis"}, {"text": "Lieferverzögerung", "correct": false, "because": "Logistisch"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Der Einkaufspreis ist die Basis der Handelskalkulation. b) Rabatte sind in der Kalkulation irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Einkaufspreis ja, Rabatte wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Gewinnzuschlag wird auf den Netto-Einkaufspreis addiert. b) Umsatzsteuer wird vor dem Gewinnzuschlag berechnet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zuschlag ja, Steuer danach"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Skonto reduziert den Netto-Einkaufspreis bei schneller Zahlung. b) Handelskalkulationen sind nur für große Unternehmen relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Skonto ja, Kalkulation allgemein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Der Verkaufspreis enthält die Umsatzsteuer. b) Handlungskosten sind in der Kalkulation optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Steuer ja, Handlungskosten wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Handelskalkulation dient der Preisgestaltung. b) Der Netto-Einkaufspreis bleibt ohne Rabatte gleich dem Listenpreis.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Preisgestaltung und Listenpreis korrekt"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides richtig"}]');

