-- questions.sql

-- Konstanten.sql (Unveränderliche Werte, Definition)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Können Konstanten im Programmverlauf geändert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Sie sind unveränderlich"}, {"text": "Ja", "correct": false, "because": "Widerspricht Definition"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer Konstante?', 3, '[{"text": "Feste Werte sichern", "correct": true, "because": "Verhindert Änderungen"}, {"text": "Dynamische Anpassung", "correct": false, "because": "Für Variablen"}, {"text": "UI-Design steuern", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften haben Konstanten?', 5, '[{"text": "Unveränderlich", "correct": true, "because": "Wert bleibt fest"}, {"text": "Global verfügbar", "correct": true, "because": "Oft programmweit nutzbar"}, {"text": "Dynamisch anpassbar", "correct": false, "because": "Widerspricht Definition"}, {"text": "Nur lokal gültig", "correct": false, "because": "Scope variiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Konstanten verbessern Lesbarkeit. b) Sie sind immer numerisch.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) kann auch String sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Definition einer Konstante?', 4, '[{"text": "Datentyp", "correct": false, "because": "Muss festgelegt sein"}, {"text": "Wertzuweisung", "correct": false, "because": "Definiert Konstante"}, {"text": "Farbcodierung", "correct": true, "because": "Kein Einfluss auf Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob jede Variable eine Konstante sein kann?', 2, '[{"text": "Nein", "correct": true, "because": "Variablen sind veränderlich"}, {"text": "Ja", "correct": false, "because": "Unterschied in Definition"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Syntax wähle ich für eine Konstante in Python?', 3, '[{"text": "const NAME = Wert", "correct": false, "because": "Falsche Syntax"}, {"text": "NAME = Wert", "correct": true, "because": "Konvention, Großbuchstaben"}, {"text": "let NAME = Wert", "correct": false, "because": "JavaScript-Syntax"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Konstanten im Code?', 5, '[{"text": "Lesbarkeit", "correct": true, "because": "Namen statt Werte"}, {"text": "Wartbarkeit", "correct": true, "because": "Zentrale Änderung"}, {"text": "Dynamische Anpassung", "correct": false, "because": "Nicht möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Konstanten sind optional. b) Sie verlangsamen den Code. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) hat keinen Einfluss"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um eine Konstante zu definieren?', 4, '[{"text": "Festen Wert", "correct": false, "because": "Kern der Konstante"}, {"text": "Eindeutigen Namen", "correct": false, "because": "Vermeidet Konflikte"}, {"text": "Datenbankzugriff", "correct": true, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Konstanten nur für Zahlen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Strings möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Regeln gelten für Konstanten?', 4, '[{"text": "Einmalige Zuweisung", "correct": true, "because": "Unveränderlich"}, {"text": "Bedeutungsvoller Name", "correct": true, "because": "Fördert Verständnis"}, {"text": "Mehrfache Änderung", "correct": false, "because": "Widerspricht Definition"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Konstanten die Performance steigern. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Primär für Lesbarkeit"}, {"text": "Ja", "correct": false, "because": "Kein direkter Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Nutzung von Konstanten?', 3, '[{"text": "Klarheit im Code", "correct": true, "because": "Erleichtert Verständnis"}, {"text": "Schnelle Änderung", "correct": false, "because": "Nicht möglich"}, {"text": "UI-Steuerung", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Konstanten reduzieren Fehler. b) Sie sind immer lokal.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) kann global sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einsatzbereiche haben Konstanten?', 5, '[{"text": "Feste Konfigurationswerte", "correct": true, "because": "Zentral definiert"}, {"text": "Mathematische Werte", "correct": true, "because": "Unveränderlich wie PI"}, {"text": "Dynamische Daten", "correct": false, "because": "Für Variablen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer Konstante unwichtig?', 3, '[{"text": "Name", "correct": false, "because": "Fördert Lesbarkeit"}, {"text": "Datentyp", "correct": false, "because": "Definiert Wert"}, {"text": "Farbschema", "correct": true, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Müssen Konstanten groß geschrieben sein?', 3, '[{"text": "Nein", "correct": true, "because": "Konvention, nicht Zwang"}, {"text": "Ja", "correct": false, "because": "Sprachabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Konstanten nur einmal definiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Einmalige Zuweisung"}, {"text": "Nein", "correct": false, "because": "Widerspricht Definition"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Praxis wähle ich für Konstante PI?', 4, '[{"text": "Als Konstante definieren", "correct": true, "because": "Fester Wert"}, {"text": "Als Variable nutzen", "correct": false, "because": "Änderung unlogisch"}, {"text": "In UI einbinden", "correct": false, "because": "Kein Bezug"}]');

