-- Netzwerkmodell.sql
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Erlaubt das Netzwerkmodell viele-zu-viele-Beziehungen?', 2, '[{"text": "Ja", "correct": true, "because": "Flexiblere Verknüpfungen"}, {"text": "Nein", "correct": false, "because": "Hauptmerkmal des Modells"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist für mich beim Netzwerkmodell entscheidend?', 3, '[{"text": "Verknüpfungsflexibilität", "correct": true, "because": "Erlaubt komplexe Beziehungen"}, {"text": "Schnelle Installation", "correct": false, "because": "Sekundär"}, {"text": "Minimale Speichergröße", "correct": false, "because": "Funktion wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat das Netzwerkmodell?', 5, '[{"text": "Viele-zu-viele-Beziehungen", "correct": true, "because": "Unterschied zur Hierarchie"}, {"text": "Graphenstruktur", "correct": true, "because": "Komplexe Verknüpfungen"}, {"text": "Ein Elternteil pro Kind", "correct": false, "because": "Hierarchisches Modell"}, {"text": "Flache Struktur", "correct": false, "because": "Relationaler Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Es unterstützt viele Eltern. b) Es ist immer baumartig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist hierarchisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich beim Netzwerkmodell?', 4, '[{"text": "Beziehungsverknüpfungen", "correct": false, "because": "Kern des Modells"}, {"text": "Flexibilität", "correct": false, "because": "Hauptvorteil"}, {"text": "Farbanpassung", "correct": true, "because": "Kein technischer Nutzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob das Netzwerkmodell einfacher als das relationale ist?', 2, '[{"text": "Nein", "correct": true, "because": "Komplexer durch Verknüpfungen"}, {"text": "Ja", "correct": false, "because": "Relational oft übersichtlicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Struktur wähle ich für das Netzwerkmodell?', 3, '[{"text": "Graph", "correct": true, "because": "Darstellt komplexe Beziehungen"}, {"text": "Baum", "correct": false, "because": "Hierarchisches Modell"}, {"text": "Tabelle", "correct": false, "because": "Relationaler Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet mir das Netzwerkmodell?', 5, '[{"text": "Komplexe Beziehungen", "correct": true, "because": "Viele-zu-viele möglich"}, {"text": "Flexible Navigation", "correct": true, "because": "Mehrere Pfade"}, {"text": "Einfache Struktur", "correct": false, "because": "Eher komplex"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Es erlaubt viele Eltern. b) Es ist für einfache Daten geeignet. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist eher komplex"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für das Netzwerkmodell?', 4, '[{"text": "Verknüpfungsstruktur", "correct": false, "because": "Kern des Modells"}, {"text": "Mehrere Beziehungen", "correct": false, "because": "Hauptmerkmal"}, {"text": "Flache Hierarchie", "correct": true, "because": "Hierarchisches Modell"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist das Netzwerkmodell für große Datenmengen ideal?', 2, '[{"text": "Ja", "correct": true, "because": "Flexibilität bei Komplexität"}, {"text": "Nein", "correct": false, "because": "Skaliert gut"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen das Netzwerkmodell effektiv?', 4, '[{"text": "Flexible Verknüpfungen", "correct": true, "because": "Unterstützt viele Beziehungen"}, {"text": "Effiziente Navigation", "correct": true, "because": "Mehrere Zugriffspfade"}, {"text": "Einfache Tabellen", "correct": false, "because": "Relationaler Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass das Netzwerkmodell wie eine Tabelle ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Graph statt flach"}, {"text": "Ja", "correct": false, "because": "Relationaler Irrtum"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich beim Netzwerkmodell?', 3, '[{"text": "Beziehungsmanagement", "correct": true, "because": "Kern der Flexibilität"}, {"text": "Schnelle Einrichtung", "correct": false, "because": "Struktur wichtiger"}, {"text": "Minimale Tiefe", "correct": false, "because": "Komplexität zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Es ist flexibler als hierarchisch. b) Es ist einfacher als relational.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist komplexer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Optionen verbessern das Netzwerkmodell?', 5, '[{"text": "Mehrere Verknüpfungen", "correct": true, "because": "Erhöht Flexibilität"}, {"text": "Pfadoptimierung", "correct": true, "because": "Schnellere Zugriffe"}, {"text": "Flache Struktur", "correct": false, "because": "Relationaler Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist beim Netzwerkmodell unwichtig?', 3, '[{"text": "Beziehungsstruktur", "correct": false, "because": "Kernfeature"}, {"text": "Graphenlogik", "correct": false, "because": "Definiert Modell"}, {"text": "Bildbearbeitung", "correct": true, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann das Netzwerkmodell hierarchisch sein?', 3, '[{"text": "Nein", "correct": true, "because": "Flexibler als Baum"}, {"text": "Ja", "correct": false, "because": "Unterschied zu Hierarchie"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob das Netzwerkmodell für einfache Daten geeignet ist?', 2, '[{"text": "Nein", "correct": true, "because": "Für Komplexität ausgelegt"}, {"text": "Ja", "correct": false, "because": "Eher komplex"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel passt zum Netzwerkmodell?', 4, '[{"text": "Lieferanten und Produkte", "correct": true, "because": "Viele-zu-viele-Beziehung"}, {"text": "Abteilungen und Mitarbeiter", "correct": false, "because": "Hierarchisch besser"}, {"text": "Einzelne Tabelle", "correct": false, "because": "Relationaler Ansatz"}]');

