INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 6 > Kommunikation > Organisation
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist eine gut organisierte Kommunikation immer notwendig, um IT-Projekte erfolgreich abzuschließen?', 2, '[{"text": "Ja", "correct": true, "because": "Klare Strukturen fördern Effizienz und Koordination"}, {"text": "Nein", "correct": false, "because": "Organisation ist entscheidend für den Erfolg"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine unorganisierte Kommunikation zu Missverständnissen in einem IT-Team führen?', 2, '[{"text": "Ja", "correct": true, "because": "Fehlende Struktur erhöht die Fehlerquote"}, {"text": "Nein", "correct": false, "because": "Unorganisation beeinträchtigt Klarheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle Kommunikationswege in einem IT-Projekt zentral dokumentiert sein, um organisiert zu sein?', 2, '[{"text": "Nein", "correct": true, "because": "Flexibilität ist möglich, aber Dokumentation hilft"}, {"text": "Ja", "correct": false, "because": "Zentralität ist nützlich, aber nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Kommunikations-Tools die Organisation in einem Team verbessern?', 2, '[{"text": "Ja", "correct": true, "because": "Tools wie Slack oder Jira strukturieren den Austausch"}, {"text": "Nein", "correct": false, "because": "Tools unterstützen die Organisation effektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Organisation der Kommunikation unabhängig von der Teamgröße?', 2, '[{"text": "Nein", "correct": true, "because": "Größere Teams erfordern mehr Struktur"}, {"text": "Ja", "correct": false, "because": "Teamgröße beeinflusst den Organisationsbedarf"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Tool wird häufig verwendet, um die Kommunikation in IT-Projekten zu organisieren?', 3, '[{"text": "Jira", "correct": true, "because": "Strukturiert Aufgaben und Kommunikation"}, {"text": "Paint", "correct": false, "because": "Für Grafiken, nicht Organisation"}, {"text": "Calculator", "correct": false, "because": "Keine Kommunikationsfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt ist für die Organisation der Kommunikation am wichtigsten?', 2, '[{"text": "Klare Verantwortlichkeiten", "correct": true, "because": "Definiert Ansprechpartner"}, {"text": "Maximale Meetingdauer", "correct": false, "because": "Weniger entscheidend"}, {"text": "Einheitliche Schriftart", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Organisation der Kommunikation in IT-Projekten?', 2, '[{"text": "Effiziente Zusammenarbeit", "correct": true, "because": "Optimiert Teamarbeit"}, {"text": "Reduktion der Teamgröße", "correct": false, "because": "Nicht relevant"}, {"text": "Vermeidung von Dokumentation", "correct": false, "because": "Gegenteil ist sinnvoll"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Fehler kann durch schlechte Organisation der Kommunikation entstehen?', 3, '[{"text": "Verzögerungen im Projekt", "correct": true, "because": "Unklarheiten bremsen Fortschritt"}, {"text": "Schnellere Entscheidungen", "correct": false, "because": "Unrealistisch"}, {"text": "Automatische Koordination", "correct": false, "because": "Nicht garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft, die Kommunikation in einem Team zu organisieren?', 2, '[{"text": "Regelmäßige Statusmeetings", "correct": true, "because": "Synchronisiert Team"}, {"text": "Einmalige E-Mail", "correct": false, "because": "Zu wenig Struktur"}, {"text": "Zufällige Nachrichten", "correct": false, "because": "Unorganisiert"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente tragen zur organisierten Kommunikation bei?', 4, '[{"text": "Definierte Kommunikationskanäle", "correct": true, "because": "Klarheit über Wege"}, {"text": "Zeitpläne für Meetings", "correct": true, "because": "Strukturiert Austausch"}, {"text": "Rollenverteilung", "correct": true, "because": "Verantwortlichkeiten klar"}, {"text": "Farbliche Gestaltung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Tools unterstützen die Organisation der Kommunikation?', 3, '[{"text": "Microsoft Teams", "correct": true, "because": "Zentraler Austausch"}, {"text": "Trello", "correct": true, "because": "Aufgabenorganisation"}, {"text": "Confluence", "correct": true, "because": "Dokumentation und Kommunikation"}, {"text": "Notepad", "correct": false, "because": "Keine Organisationsfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können durch unorganisierte Kommunikation entstehen?', 4, '[{"text": "Missverständnisse", "correct": true, "because": "Fehlende Klarheit"}, {"text": "Doppelarbeit", "correct": true, "because": "Keine Koordination"}, {"text": "Verzögerungen", "correct": true, "because": "Ineffizienter Ablauf"}, {"text": "Schnellere Prozesse", "correct": false, "because": "Gegenteil tritt ein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine organisierte Kommunikation?', 3, '[{"text": "Schnellere Entscheidungsfindung", "correct": true, "because": "Klarheit beschleunigt"}, {"text": "Bessere Teamkoordination", "correct": true, "because": "Struktur unterstützt"}, {"text": "Reduzierte Fehlerquote", "correct": true, "because": "Missverständnisse minimiert"}, {"text": "Weniger Dokumentation", "correct": false, "because": "Dokumentation bleibt wichtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen fördern die Organisation der Kommunikation?', 3, '[{"text": "Regelmäßige Updates", "correct": true, "because": "Hält Team informiert"}, {"text": "Klare Protokolle", "correct": true, "because": "Dokumentiert Absprachen"}, {"text": "Verantwortungsverteilung", "correct": true, "because": "Definiert Zuständigkeiten"}, {"text": "Zufällige Nachrichtenflut", "correct": false, "because": "Schadet Organisation"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Eine organisierte Kommunikation reduziert Missverständnisse. b) Kommunikation muss immer spontan erfolgen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Organisation ja, Spontaneität nicht nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Kommunikations-Tools wie Jira fördern die Organisation. b) Organisation der Kommunikation ist nur bei großen Teams relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tools ja, Organisation immer nützlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Klare Zeitpläne für Meetings verbessern die Organisation. b) Unorganisierte Kommunikation hat keinen Einfluss auf Projekte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeitpläne ja, Einfluss vorhanden"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Eine organisierte Kommunikation kann Verzögerungen vermeiden. b) Alle Teammitglieder müssen dieselben Tools nutzen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verzögerungen ja, Toolwahl flexibel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Protokolle von Absprachen unterstützen die Organisation. b) Organisation der Kommunikation ist nur bei technischen Problemen wichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Protokolle ja, Organisation immer relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

