INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Kundenbeziehungen > Kundengespräche > Durchführen
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann ein Kundengespräch erfolgreich durchgeführt werden, ohne auf die individuellen Bedürfnisse des Kunden einzugehen?', 2, '[{"text": "Nein", "correct": true, "because": "Kundenorientierung ist zentral für Erfolg"}, {"text": "Ja", "correct": false, "because": "Bedürfnisse ignorieren führt zu Misserfolg"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es während der Durchführung eines Kundengesprächs erlaubt, rechtliche Fragen komplett auszublenden?', 2, '[{"text": "Nein", "correct": true, "because": "Rechtliche Aspekte wie DSGVO müssen berücksichtigt werden"}, {"text": "Ja", "correct": false, "because": "Rechtliche Ignoranz ist riskant"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss während eines Kundengesprächs jede Aussage des Kunden sofort schriftlich protokolliert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Protokollierung kann später erfolgen, Fokus liegt auf Dialog"}, {"text": "Ja", "correct": false, "because": "Sofortige Protokollierung ist nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es bei der Durchführung eines Kundengesprächs essenziell, auf nonverbale Signale des Kunden zu achten?', 2, '[{"text": "Ja", "correct": true, "because": "Nonverbale Kommunikation zeigt Stimmung und Zustimmung"}, {"text": "Nein", "correct": false, "because": "Nonverbale Signale sind oft entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Kundengespräch ohne klare Zielvorgabe effektiv durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Ohne Ziel fehlt die Richtung und Struktur"}, {"text": "Ja", "correct": false, "because": "Zielosigkeit mindert Effektivität"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Technik ist während der Durchführung eines Kundengesprächs besonders wichtig, um Missverständnisse zu vermeiden?', 2, '[{"text": "Aktives Zuhören", "correct": true, "because": "Wiederholen und Nachfragen klärt Inhalte"}, {"text": "Schnelles Reden", "correct": false, "because": "Verwirrt eher"}, {"text": "Technische Fachbegriffe", "correct": false, "because": "Kann Kunden überfordern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Reaktion ist bei Einwänden des Kunden während eines Gesprächs am effektivsten?', 3, '[{"text": "Argumentativ entkräften", "correct": true, "because": "Zeigt Kompetenz und Lösungsorientierung"}, {"text": "Ignorieren", "correct": false, "because": "Weckt Misstrauen"}, {"text": "Sofort zustimmen", "correct": false, "because": "Wirkt unsicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt sollte bei der Durchführung eines Kundengesprächs Priorität haben?', 2, '[{"text": "Kundenbedürfnisse verstehen", "correct": true, "because": "Basis für maßgeschneiderte Lösungen"}, {"text": "Eigene Produkte präsentieren", "correct": false, "because": "Kundenfokus geht vor"}, {"text": "Zeitplan einhalten", "correct": false, "because": "Flexibilität ist wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist während eines Kundengesprächs entscheidend, um Vertrauen aufzubauen?', 2, '[{"text": "Transparenz", "correct": true, "because": "Offenheit schafft Glaubwürdigkeit"}, {"text": "Dominanz", "correct": false, "because": "Kann abschrecken"}, {"text": "Schnellsprache", "correct": false, "because": "Verwirrt eher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorgehensweise ist bei unklaren Kundenfragen während des Gesprächs am besten?', 2, '[{"text": "Nachfragen stellen", "correct": true, "because": "Klärt Unsicherheiten gezielt"}, {"text": "Vermutungen anstellen", "correct": false, "because": "Führt zu Missverständnissen"}, {"text": "Thema wechseln", "correct": false, "because": "Ignoriert Kundenbedarf"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente sind bei der Durchführung eines Kundengesprächs entscheidend?', 4, '[{"text": "Klarheit in der Kommunikation", "correct": true, "because": "Vermeidet Missverständnisse"}, {"text": "Flexibilität bei Anpassungen", "correct": true, "because": "Reagiert auf Kundenwünsche"}, {"text": "Empathie", "correct": true, "because": "Stärkt Beziehung"}, {"text": "Schnellschreiben", "correct": false, "because": "Nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Fehler sollten während eines Kundengesprächs vermieden werden?', 3, '[{"text": "Unterbrechungen des Kunden", "correct": true, "because": "Zeigt Respektlosigkeit"}, {"text": "Fehlende Rückfragen", "correct": true, "because": "Führt zu Unklarheiten"}, {"text": "Technischer Jargon ohne Erklärung", "correct": true, "because": "Verwirrt Laien"}, {"text": "Lautes Lachen", "correct": false, "because": "Kontextabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strategien fördern den Erfolg eines Kundengesprächs?', 4, '[{"text": "Zielgerichtete Fragen", "correct": true, "because": "Ermittelt Bedarf"}, {"text": "Positive Körpersprache", "correct": true, "because": "Signalisiert Offenheit"}, {"text": "Kundenlösungen vorschlagen", "correct": true, "because": "Zeigt Kompetenz"}, {"text": "Monologe halten", "correct": false, "because": "Hindert Dialog"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sollten während eines Kundengesprächs dokumentiert werden?', 3, '[{"text": "Kundenanforderungen", "correct": true, "because": "Basis für Planung"}, {"text": "Vereinbarungen", "correct": true, "because": "Verbindlichkeit schaffen"}, {"text": "Einwände des Kunden", "correct": true, "because": "Für Nachbearbeitung wichtig"}, {"text": "Wetterlage", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Fähigkeiten sind bei der Durchführung eines Kundengesprächs unerlässlich?', 3, '[{"text": "Argumentationsstärke", "correct": true, "because": "Überzeugt bei Einwänden"}, {"text": "Zuhörfähigkeit", "correct": true, "because": "Versteht Kunden"}, {"text": "Anpassungsfähigkeit", "correct": true, "because": "Reagiert auf Dynamik"}, {"text": "Programmierkenntnisse", "correct": false, "because": "Nicht primär relevant"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ein Kundengespräch sollte strikt einem Skript folgen. b) Kundenfragen sollten immer ernst genommen werden.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Skript ist starr, Fragen sind wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Empathie hat keinen Einfluss auf den Gesprächserfolg. b) Einwände des Kunden sollten begrüßt werden.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Empathie ist wichtig, Einwände sind Chancen"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Technische Details sollten im Kundengespräch immer im Vordergrund stehen. b) Nonverbale Signale können ignoriert werden.', 3, '[{"text": "Beides falsch", "correct": true, "because": "Kundenfokus geht vor, Signale sind relevant"}, {"text": "Beides stimmt", "correct": false, "because": "Beides ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Ein Kundengespräch kann ohne klare Kommunikation erfolgreich sein. b) Vereinbarungen sollten während des Gesprächs festgehalten werden.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Kommunikation ist essenziell, Vereinbarungen wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Flexibilität ist bei der Durchführung eines Kundengesprächs entscheidend. b) Der Kunde sollte das Gespräch dominieren.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Flexibilität ja, Dominanz ausbalancieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

