-- Phasen der Teamentwicklung (Forming, Storming, Norming, Performing).sql (Tuckman-Modell für Teamdynamik, z. B. Entwicklung von Zusammenarbeit)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist jedes Team sofort produktiv, wenn es startet?', 2, '[{"text": "Nein", "correct": true, "because": "Entwicklung braucht Zeit"}, {"text": "Ja", "correct": false, "because": "Phasen müssen durchlaufen werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phase kommt als erstes, wenn ein Team sich bildet?', 3, '[{"text": "Forming", "correct": true, "because": "Anfang der Orientierung"}, {"text": "Storming", "correct": false, "because": "Konflikte später"}, {"text": "Norming", "correct": false, "because": "Regeln später"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale zeigen, dass ein Team gut arbeitet?', 5, '[{"text": "Hohe Effizienz", "correct": true, "because": "Performing erreicht"}, {"text": "Selbstorganisation", "correct": true, "because": "Team ist eingespielt"}, {"text": "Häufige Streits", "correct": false, "because": "Frühere Phase"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Storming ist konfliktfrei. b) Norming bringt Regeln.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Storming hat Konflikte"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ein Team seine Arbeitsweise findet?', 4, '[{"text": "Persönliche Spannungen", "correct": true, "because": "Norming fokussiert Regeln"}, {"text": "Zielsetzung", "correct": false, "because": "Wichtig für Fokus"}, {"text": "Kommunikation", "correct": false, "because": "Schlüssel zum Erfolg"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Konflikte nur in einer Phase vorkommen?', 2, '[{"text": "Nein", "correct": true, "because": "Storming ist Hauptphase, aber nicht exklusiv"}, {"text": "Ja", "correct": false, "because": "Konflikte können wiederkehren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Verhalten sehe ich, wenn ein Team sich orientiert?', 3, '[{"text": "Vorsichtiges Abtasten", "correct": true, "because": "Typisch für Forming"}, {"text": "Offene Streits", "correct": false, "because": "Spätere Phase"}, {"text": "Klare Rollen", "correct": false, "because": "Erst in Norming"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften hat ein Team, das Höchstleistung bringt?', 5, '[{"text": "Vertrauen", "correct": true, "because": "Basis für Performing"}, {"text": "Flexibilität", "correct": true, "because": "Anpassungsfähig"}, {"text": "Unklarheit", "correct": false, "because": "Frühere Phase"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Forming ist produktiv. b) Storming schadet immer. Stimmt das?', 3, '[{"text": "Beides falsch", "correct": true, "because": "Forming ist langsam, Storming kann nützlich sein"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, wenn ein Team reibungslos läuft?', 4, '[{"text": "Ziele", "correct": false, "because": "Immer nötig"}, {"text": "Vertrauen", "correct": false, "because": "Kern von Performing"}, {"text": "Ständige Streits", "correct": true, "because": "Stört Effizienz"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Startet ein Team direkt mit klaren Regeln?', 2, '[{"text": "Nein", "correct": true, "because": "Regeln entstehen in Norming"}, {"text": "Ja", "correct": false, "because": "Forming ist unklar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phasen zeigen Fortschritt in der Zusammenarbeit?', 4, '[{"text": "Norming", "correct": true, "because": "Regeln entstehen"}, {"text": "Performing", "correct": true, "because": "Produktivität hoch"}, {"text": "Forming", "correct": false, "because": "Nur Anfang"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Teams ohne Konflikte schneller vorankommen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Konflikte können klären"}, {"text": "Ja", "correct": false, "because": "Storming ist normal"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ein Team sich neu formiert?', 3, '[{"text": "Kennenlernen", "correct": true, "because": "Forming braucht Vertrauen"}, {"text": "Sofortige Ergebnisse", "correct": false, "because": "Zu früh"}, {"text": "Regeldetails", "correct": false, "because": "Spätere Phase"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Performing ist stabil. b) Storming vermeidbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Storming oft unvermeidlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bringt es, wenn ein Team eingespielt ist?', 5, '[{"text": "Effiziente Arbeit", "correct": true, "because": "Performing erreicht"}, {"text": "Klare Rollen", "correct": true, "because": "Norming abgeschlossen"}, {"text": "Unklare Ziele", "correct": false, "because": "Frühere Phase"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ein Team gut läuft?', 3, '[{"text": "Kooperation", "correct": false, "because": "Kern von Performing"}, {"text": "Vertrauen", "correct": false, "because": "Basis für Erfolg"}, {"text": "Offene Streits", "correct": true, "because": "Stört Produktivität"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Konflikte ein Zeichen von Scheitern?', 3, '[{"text": "Nein", "correct": true, "because": "Normale Entwicklungsphase"}, {"text": "Ja", "correct": false, "because": "Storming ist produktiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob jedes Team alle Phasen durchläuft?', 2, '[{"text": "Nein", "correct": true, "because": "Kann variieren"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend linear"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich, wenn ein Team sich abstimmt?', 4, '[{"text": "Regeln schaffen", "correct": true, "because": "Norming stärken"}, {"text": "Sofortige Höchstleistung", "correct": false, "because": "Spätere Phase"}, {"text": "Konflikte forcieren", "correct": false, "because": "Falsche Richtung"}]');

