INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 6 > Planung > Ressourcen
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen Ressourcen in der Planungsphase eines IT-Systems immer exakt quantifiziert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Schätzungen sind oft ausreichend, Präzision kommt später"}, {"text": "Ja", "correct": false, "because": "Exakte Zahlen sind ideal, aber nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Können personelle Ressourcen in der Planung ohne Berücksichtigung von Qualifikationen zugeteilt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Möglich, aber riskant und ineffizient"}, {"text": "Nein", "correct": false, "because": "Qualifikationen sind entscheidend, aber nicht vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Verfügbarkeit von Hardware-Ressourcen in der Planungsphase irrelevant, wenn Software virtualisiert wird?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Virtualisierung benötigt physische Ressourcen"}, {"text": "Ja", "correct": false, "because": "Hardware bleibt grundlegend"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Ressourcenkonflikte in der Planungsphase vollständig ausgeschlossen werden?', 2, '[{"text": "Nein", "correct": true, "because": "Unvorhergesehene Änderungen sind möglich"}, {"text": "Ja", "correct": false, "because": "Absolute Sicherheit ist unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind finanzielle Ressourcen in der Planung wichtiger als zeitliche Ressourcen?', 2, '[{"text": "Nein", "correct": true, "because": "Beide sind interdependent und gleichwertig"}, {"text": "Ja", "correct": false, "because": "Zeit kann ebenso limitierend sein"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Ressource wird in der Planungsphase häufig unterschätzt?', 3, '[{"text": "Zeit", "correct": true, "because": "Projektlaufzeiten werden oft unrealistisch geplant"}, {"text": "Hardware", "correct": false, "because": "Leichter quantifizierbar"}, {"text": "Softwarelizenzen", "correct": false, "because": "Kosten meist bekannt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug wird typischerweise verwendet, um Ressourcen in der Planung zuzuweisen?', 2, '[{"text": "Projektmanagement-Software", "correct": true, "because": "Ermöglicht Zuordnung und Übersicht"}, {"text": "Textverarbeitung", "correct": false, "because": "Ungeeignet für komplexe Planung"}, {"text": "Tabellenkalkulation", "correct": false, "because": "Einfacher, aber weniger spezialisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Art von Ressource wird durch die Anzahl der verfügbaren Mitarbeiter definiert?', 2, '[{"text": "Personelle Ressource", "correct": true, "because": "Bezieht sich auf Arbeitskraft"}, {"text": "Materielle Ressource", "correct": false, "because": "Physische Güter"}, {"text": "Finanzielle Ressource", "correct": false, "because": "Geldmittel"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Ressourcenplanung?', 2, '[{"text": "Optimale Nutzung vorhandener Mittel", "correct": true, "because": "Effizienz und Kostenreduktion"}, {"text": "Maximierung der Projektlaufzeit", "correct": false, "because": "Gegenteil ist gewünscht"}, {"text": "Reduktion der Anforderungen", "correct": false, "because": "Unabhängig von Ressourcen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Risiko entsteht bei unzureichender Ressourcenplanung?', 3, '[{"text": "Projektverzögerung", "correct": true, "because": "Fehlende Ressourcen stoppen den Fortschritt"}, {"text": "Schnellere Umsetzung", "correct": false, "because": "Unrealistisch"}, {"text": "Geringere Qualität der Hardware", "correct": false, "because": "Nicht direkt verknüpft"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Ressourcenarten müssen in der Planung eines IT-Systems berücksichtigt werden?', 4, '[{"text": "Personelle Ressourcen", "correct": true, "because": "Mitarbeiter sind essenziell"}, {"text": "Finanzielle Ressourcen", "correct": true, "because": "Budget bestimmt Machbarkeit"}, {"text": "Zeitliche Ressourcen", "correct": true, "because": "Zeitrahmen entscheidend"}, {"text": "Kundenzufriedenheit", "correct": false, "because": "Ergebnis, keine Ressource"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Ressourcenzuweisung in der Planung?', 3, '[{"text": "Projektumfang", "correct": true, "because": "Definiert Ressourcenbedarf"}, {"text": "Verfügbarkeit", "correct": true, "because": "Limitierender Faktor"}, {"text": "Kompetenzen", "correct": true, "because": "Passende Skills nötig"}, {"text": "Wetterbedingungen", "correct": false, "because": "Irrelevant für IT-Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen kann eine Überlastung von Ressourcen haben?', 4, '[{"text": "Mitarbeiterüberlastung", "correct": true, "because": "Zu viele Aufgaben"}, {"text": "Kostensteigerung", "correct": true, "because": "Zusätzliche Ressourcen nötig"}, {"text": "Qualitätsverlust", "correct": true, "because": "Überforderung mindert Ergebnisse"}, {"text": "Kürzere Projektlaufzeit", "correct": false, "because": "Gegenteil tritt ein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden können zur Ressourcenplanung eingesetzt werden?', 3, '[{"text": "Ressourcen-Histogramm", "correct": true, "because": "Visualisiert Bedarf"}, {"text": "Kritischer Pfad", "correct": true, "because": "Zeigt zeitliche Abhängigkeiten"}, {"text": "Lastenausgleich", "correct": true, "because": "Optimierte Verteilung"}, {"text": "Zufallsauswahl", "correct": false, "because": "Unprofessionell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ressourcen können knapp werden, wenn die Planung fehlerhaft ist?', 3, '[{"text": "Budget", "correct": true, "because": "Überschreitung möglich"}, {"text": "Zeit", "correct": true, "because": "Verzögerungen entstehen"}, {"text": "Serverkapazität", "correct": true, "because": "Unterschätzung wahrscheinlich"}, {"text": "Kundendaten", "correct": false, "because": "Keine Ressource"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ressourcenplanung berücksichtigt die Verfügbarkeit von Mitarbeitern. b) Hardware-Ressourcen sind immer unbegrenzt verfügbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verfügbarkeit ja, Hardware begrenzt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Zeitliche Ressourcen werden durch Deadlines definiert. b) Ressourcenplanung ist nur in der Umsetzungsphase relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Deadlines ja, Planung vorher"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Ressourcenengpass kann durch Outsourcing gelöst werden. b) Finanzielle Ressourcen beeinflussen die Wahl der Hardware nicht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Outsourcing ja, Budget entscheidend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Ressourcen müssen den Anforderungen des Projekts entsprechen. b) Eine Überplanung von Ressourcen vermeidet jegliche Risiken.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Passung ja, Überplanung teuer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ressourcenplanung kann durch Software automatisiert werden. b) Personelle Ressourcen sind unabhängig von Projektzielen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Automatisierung ja, Ziele relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

