-- Schulungen anbieten.sql (Trainings für Nutzer oder Admins, z. B. zur Bedienung oder Verwaltung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kann ich Schulungen ohne Zielgruppe anbieten?', 2, '[{"text": "Nein", "correct": true, "because": "Zielgruppe definiert Inhalt"}, {"text": "Ja", "correct": false, "because": "Fehlende Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Schulungen?', 3, '[{"text": "Kompetenzförderung", "correct": true, "because": "Verbessert Nutzung"}, {"text": "Design", "correct": false, "because": "Anderer Fokus"}, {"text": "Performance", "correct": false, "because": "Indirekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einer guten Schulung?', 5, '[{"text": "Praxisbeispiele", "correct": true, "because": "Fördert Verständnis"}, {"text": "Interaktivität", "correct": true, "because": "Bindet Teilnehmer"}, {"text": "Hohe Auflösung", "correct": false, "because": "Irrelevant"}, {"text": "Lange Vorträge", "correct": false, "because": "Ermüdend"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Schulungen brauchen Planung. b) Nutzer verstehen alles intuitiv.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) oft unrealistisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei Schulungen?', 4, '[{"text": "Lernziele", "correct": false, "because": "Definiert Erfolg"}, {"text": "Teilnehmerbedarf", "correct": false, "because": "Passt Inhalt an"}, {"text": "Schriftfarbe", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Schulungen immer vor Ort sein müssen?', 2, '[{"text": "Nein", "correct": true, "because": "Online möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Format wähle ich für Admin-Schulungen?', 3, '[{"text": "Hands-on", "correct": true, "because": "Praxisnah für Admins"}, {"text": "Nur Theorie", "correct": false, "because": "Zu abstrakt"}, {"text": "E-Mail", "correct": false, "because": "Keine Interaktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen Schulungen effektiv?', 5, '[{"text": "Relevanz", "correct": true, "because": "Passt an Bedarf"}, {"text": "Feedback", "correct": true, "because": "Verbessert Lernen"}, {"text": "Hohe Kosten", "correct": false, "because": "Kein Qualitätsmerkmal"}, {"text": "Lange Dauer", "correct": false, "because": "Ermüdend"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Schulungen sind nur für Nutzer. b) Admins brauchen keine. Stimmt das?', 3, '[{"text": "Beides falsch", "correct": true, "because": "Beide profitieren"}, {"text": "Beides stimmt", "correct": false, "because": "Nicht exklusiv"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Nutzer-Schulungen?', 4, '[{"text": "Verständlichkeit", "correct": false, "because": "Kern der Schulung"}, {"text": "Beispiele", "correct": false, "because": "Veranschaulicht"}, {"text": "Kernel-Details", "correct": true, "because": "Zu technisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Schulungen ohne Materialien möglich?', 2, '[{"text": "Nein", "correct": true, "because": "Materialien unterstützen"}, {"text": "Ja", "correct": false, "because": "Weniger effektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Inhalte sind für Admins entscheidend?', 4, '[{"text": "Verwaltungstipps", "correct": true, "because": "Praxisrelevant"}, {"text": "Fehlerbehebung", "correct": true, "because": "Löst Probleme"}, {"text": "Marketing", "correct": false, "because": "Falscher Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Schulungen nur einmal nötig sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Updates erforderlich"}, {"text": "Ja", "correct": false, "because": "Wissen veraltet"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Schulungen?', 3, '[{"text": "Praxisnähe", "correct": true, "because": "Fördert Anwendung"}, {"text": "Schnelle Durchführung", "correct": false, "because": "Qualität zählt"}, {"text": "Theorie", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Schulungen brauchen Struktur. b) Online ist ineffektiv.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) kontextabhängig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten gute Schulungen?', 5, '[{"text": "Effizienz", "correct": true, "because": "Bessere Nutzung"}, {"text": "Fehlerreduktion", "correct": true, "because": "Klares Verständnis"}, {"text": "Hohe Kosten", "correct": false, "because": "Kein Vorteil"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Schulungen unwichtig?', 3, '[{"text": "Interaktion", "correct": false, "because": "Fördert Lernen"}, {"text": "Klarheit", "correct": false, "because": "Essenziell"}, {"text": "Raumdekor", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzen Schulungen die Dokumentation?', 3, '[{"text": "Nein", "correct": true, "because": "Ergänzen sich"}, {"text": "Ja", "correct": false, "because": "Doku bleibt nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Schulungen nur für Anfänger sind?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Profis profitieren"}, {"text": "Ja", "correct": false, "because": "Nicht exklusiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature ist für Schulungen entscheidend?', 4, '[{"text": "Anpassung", "correct": true, "because": "Passt an Zielgruppe"}, {"text": "Hohe Komplexität", "correct": false, "because": "Verwirrt"}, {"text": "Statische Inhalte", "correct": false, "because": "Wenig flexibel"}]');

