-- Support bei Softwareproblemen.sql (Hilfe bei Nutzeranfragen oder Fehlern, z. B. durch Ticketsysteme)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kann ich Support ohne Ticketsystem effektiv leisten?', 2, '[{"text": "Nein", "correct": true, "because": "Tickets organisieren Anfragen"}, {"text": "Ja", "correct": false, "because": "Ohne System chaotisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Support bei Softwareproblemen?', 3, '[{"text": "Nutzerhilfe", "correct": true, "because": "Löst Probleme"}, {"text": "Code-Optimierung", "correct": false, "because": "Anderer Fokus"}, {"text": "Design", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden helfen beim Support?', 5, '[{"text": "Ticketsysteme", "correct": true, "because": "Verfolgt Anfragen"}, {"text": "Fehlerprotokolle", "correct": true, "because": "Zeigt Ursachen"}, {"text": "Zufällige Antworten", "correct": false, "because": "Unzuverlässig"}, {"text": "Manuelle Suche", "correct": false, "because": "Ineffizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Support braucht Kommunikation. b) Ticketsysteme sind optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) erleichtert Organisation"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich beim Support?', 4, '[{"text": "Nutzeranfragen", "correct": false, "because": "Kern des Supports"}, {"text": "Fehlerdetails", "correct": false, "because": "Hilft bei Lösung"}, {"text": "Schriftfarbe", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Support immer technisch sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Bedienhilfe"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool nutze ich für ein Ticketsystem?', 3, '[{"text": "Jira", "correct": true, "because": "Verwaltet Anfragen"}, {"text": "Notepad", "correct": false, "because": "Unstrukturiert"}, {"text": "E-Mail allein", "correct": false, "because": "Chaotisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen Support effektiv?', 5, '[{"text": "Schnelle Reaktion", "correct": true, "because": "Zufriedenheit steigt"}, {"text": "Klare Lösungen", "correct": true, "because": "Hilft Nutzern"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Irrelevant"}, {"text": "Lange Wartezeiten", "correct": false, "because": "Frustriert"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Support ist nur für Fehler. b) Nutzerfragen sind unwichtig. Stimmt das?', 3, '[{"text": "Beides falsch", "correct": true, "because": "Auch Bedienung, Fragen zentral"}, {"text": "Beides stimmt", "correct": false, "because": "Nicht korrekt"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) unvollständig"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für den Support?', 4, '[{"text": "Fehlerprotokolle", "correct": false, "because": "Zeigt Ursachen"}, {"text": "Kommunikation", "correct": false, "because": "Verbindet mit Nutzern"}, {"text": "Teamfotos", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Support nur reaktiv?', 2, '[{"text": "Nein", "correct": true, "because": "Auch proaktiv möglich"}, {"text": "Ja", "correct": false, "because": "Nicht exklusiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Infos sind beim Support entscheidend?', 4, '[{"text": "Fehlerbeschreibung", "correct": true, "because": "Zeigt Problem"}, {"text": "Nutzerkontext", "correct": true, "because": "Klart Umgebung"}, {"text": "UI-Design", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Support ohne System auskommt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Systeme organisieren"}, {"text": "Ja", "correct": false, "because": "Chaos droht"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich beim Support?', 3, '[{"text": "Nutzerzufriedenheit", "correct": true, "because": "Fördert Vertrauen"}, {"text": "Schnelle Antworten", "correct": false, "because": "Qualität zählt"}, {"text": "Vermutungen", "correct": false, "because": "Unzuverlässig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ticketsysteme helfen beim Tracking. b) Support ist immer langsam.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) nicht zwangsläufig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet guter Support?', 5, '[{"text": "Nutzerbindung", "correct": true, "because": "Zufriedenheit steigt"}, {"text": "Fehlerreduktion", "correct": true, "because": "Probleme gelöst"}, {"text": "Hohe Kosten", "correct": false, "because": "Kein Vorteil"}, {"text": "Langsame Lösung", "correct": false, "because": "Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist beim Support unwichtig?', 3, '[{"text": "Reaktionszeit", "correct": false, "because": "Beeinflusst Zufriedenheit"}, {"text": "Fehlerdetails", "correct": false, "because": "Hilft bei Lösung"}, {"text": "Monitorgröße", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzt Support die Dokumentation?', 3, '[{"text": "Nein", "correct": true, "because": "Ergänzen sich"}, {"text": "Ja", "correct": false, "because": "Doku bleibt zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Support nur für Fehler ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Fragen"}, {"text": "Ja", "correct": false, "because": "Nicht exklusiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature ist für Support entscheidend?', 4, '[{"text": "Klare Kommunikation", "correct": true, "because": "Verständnis sichern"}, {"text": "Hohe Komplexität", "correct": false, "because": "Verwirrt"}, {"text": "Statische Antworten", "correct": false, "because": "Unflexibel"}]');

