-- TCL_Transaction_Control_Language.sql
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl speichert "INSERT INTO employees (id, name) VALUES (1, ''Anna'')" dauerhaft? "COMMIT"?', 2, '[{"text": "COMMIT", "correct": true, "because": "Bestätigt Transaktion"}, {"text": "ROLLBACK", "correct": false, "because": "Macht rückgängig"}, {"text": "SAVEPOINT", "correct": false, "because": "Nur Rückpunkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was bewirkt "ROLLBACK" nach "UPDATE orders SET total = 150 WHERE id = 10" ohne COMMIT?', 3, '[{"text": "Setzt total auf vorherigen Wert zurück", "correct": true, "because": "Nicht bestätigt"}, {"text": "Speichert total als 150", "correct": false, "because": "Kein COMMIT"}, {"text": "Löscht orders", "correct": false, "because": "Kein DDL"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl setzt einen Rückpunkt nach "DELETE FROM tasks WHERE id = 5"? "SAVEPOINT sp1"?', 4, '[{"text": "SAVEPOINT", "correct": true, "because": "Markiert Transaktionspunkt"}, {"text": "COMMIT", "correct": false, "because": "Speichert dauerhaft"}, {"text": "ROLLBACK", "correct": false, "because": "Setzt zurück"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert bei "ROLLBACK TO SAVEPOINT sp1" nach "INSERT INTO products (id, price) VALUES (101, 29.99); SAVEPOINT sp1; UPDATE products SET price = 39.99 WHERE id = 101"?', 5, '[{"text": "Stellt price auf 29.99 zurück", "correct": true, "because": "Zurück zu sp1"}, {"text": "Speichert price als 39.99", "correct": false, "because": "Kein COMMIT"}, {"text": "Löscht Datensatz 101", "correct": false, "because": "Kein DELETE"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl bestätigt "UPDATE employees SET salary = 60000 WHERE id = 10"? "COMMIT"?', 2, '[{"text": "COMMIT", "correct": true, "because": "Macht Änderung permanent"}, {"text": "ROLLBACK", "correct": false, "because": "Setzt zurück"}, {"text": "DROP", "correct": false, "because": "Kein TCL"}]'),
('00000000-0000-0000-0000-000000000000', 'Was bewirkt "ROLLBACK" nach "DELETE FROM orders WHERE id = 5" ohne COMMIT?', 3, '[{"text": "Stellt gelöschten Datensatz wieder her", "correct": true, "because": "Nicht bestätigt"}, {"text": "Löscht id 5 dauerhaft", "correct": false, "because": "Kein COMMIT"}, {"text": "Ändert orders", "correct": false, "because": "Kein UPDATE"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl speichert Änderungen nach "INSERT INTO tasks (id, task) VALUES (1, ''Plan''); UPDATE tasks SET task = ''Do'' WHERE id = 1"? "COMMIT"?', 4, '[{"text": "COMMIT", "correct": true, "because": "Speichert beide Änderungen"}, {"text": "SAVEPOINT", "correct": false, "because": "Nur Rückpunkt"}, {"text": "ROLLBACK", "correct": false, "because": "Setzt zurück"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert bei "SAVEPOINT sp2" nach "UPDATE products SET price = 50 WHERE id = 101"?', 2, '[{"text": "Setzt Rückpunkt nach Preisänderung", "correct": true, "because": "Markiert Transaktionspunkt"}, {"text": "Speichert Preisänderung", "correct": false, "because": "Kein COMMIT"}, {"text": "Löscht Preis", "correct": false, "because": "Kein DELETE"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl macht "DELETE FROM customers WHERE id = 3" rückgängig? "ROLLBACK" vor COMMIT?', 3, '[{"text": "ROLLBACK", "correct": true, "because": "Stellt vorigen Zustand her"}, {"text": "COMMIT", "correct": false, "because": "Speichert Löschung"}, {"text": "SAVEPOINT", "correct": false, "because": "Nur Rückpunkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was bewirkt "COMMIT" nach "INSERT INTO dept (id, name) VALUES (10, ''HR''); INSERT INTO dept (id, name) VALUES (11, ''IT'')"?', 4, '[{"text": "Speichert beide Abteilungen dauerhaft", "correct": true, "because": "Bestätigt Transaktion"}, {"text": "Setzt Änderungen zurück", "correct": false, "because": "Kein ROLLBACK"}, {"text": "Markiert Rückpunkt", "correct": false, "because": "Kein SAVEPOINT"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl setzt "UPDATE orders SET status = ''shipped'' WHERE id = 7" zurück? "ROLLBACK" vor COMMIT?', 2, '[{"text": "ROLLBACK", "correct": true, "because": "Macht Änderung rückgängig"}, {"text": "COMMIT", "correct": false, "because": "Speichert Änderung"}, {"text": "DROP", "correct": false, "because": "Kein TCL"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert bei "ROLLBACK TO SAVEPOINT sp1" nach "INSERT INTO sales (id, total) VALUES (1, 100); SAVEPOINT sp1; UPDATE sales SET total = 200 WHERE id = 1"?', 5, '[{"text": "Stellt total auf 100 zurück", "correct": true, "because": "Zurück zu sp1"}, {"text": "Speichert total als 200", "correct": false, "because": "Kein COMMIT"}, {"text": "Löscht sales", "correct": false, "because": "Kein DDL"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl speichert "DELETE FROM tasks WHERE id = 5" dauerhaft? "COMMIT"?', 3, '[{"text": "COMMIT", "correct": true, "because": "Macht Löschung permanent"}, {"text": "ROLLBACK", "correct": false, "because": "Stellt zurück"}, {"text": "SAVEPOINT", "correct": false, "because": "Nur Rückpunkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was bewirkt "SAVEPOINT sp3" nach "UPDATE employees SET dept_id = 2 WHERE id = 15"?', 2, '[{"text": "Markiert Rückpunkt nach Änderung", "correct": true, "because": "Für späteren Rollback"}, {"text": "Speichert dept_id Änderung", "correct": false, "because": "Kein COMMIT"}, {"text": "Löscht employees", "correct": false, "because": "Kein DELETE"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl macht "INSERT INTO products (id, price) VALUES (102, 49.99)" rückgängig? "ROLLBACK" vor COMMIT?', 3, '[{"text": "ROLLBACK", "correct": true, "because": "Entfernt unbestätigte Änderung"}, {"text": "COMMIT", "correct": false, "because": "Speichert Änderung"}, {"text": "TRUNCATE", "correct": false, "because": "Kein TCL"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert bei "COMMIT" nach "UPDATE orders SET total = total + 50 WHERE id = 8; DELETE FROM orders WHERE id = 9"?', 4, '[{"text": "Speichert Erhöhung und Löschung", "correct": true, "because": "Bestätigt beide"}, {"text": "Setzt Änderungen zurück", "correct": false, "because": "Kein ROLLBACK"}, {"text": "Markiert Rückpunkt", "correct": false, "because": "Kein SAVEPOINT"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl setzt "UPDATE customers SET status = ''active'' WHERE id = 4" zurück? "ROLLBACK TO SAVEPOINT sp1" nach "SAVEPOINT sp1"?', 5, '[{"text": "ROLLBACK TO SAVEPOINT sp1", "correct": true, "because": "Zurück vor Änderung"}, {"text": "COMMIT", "correct": false, "because": "Speichert Änderung"}, {"text": "SAVEPOINT sp2", "correct": false, "because": "Nur Rückpunkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was bewirkt "ROLLBACK" nach "INSERT INTO dept (id, name) VALUES (12, ''Sales'')" ohne vorherigen COMMIT?', 2, '[{"text": "Entfernt neuen Datensatz", "correct": true, "because": "Nicht bestätigt"}, {"text": "Speichert Sales-Abteilung", "correct": false, "because": "Kein COMMIT"}, {"text": "Ändert dept", "correct": false, "because": "Kein UPDATE"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl speichert "DELETE FROM employees WHERE dept_id = 3" dauerhaft? "COMMIT"?', 3, '[{"text": "COMMIT", "correct": true, "because": "Macht Löschung permanent"}, {"text": "ROLLBACK", "correct": false, "because": "Stellt zurück"}, {"text": "SAVEPOINT", "correct": false, "because": "Nur Rückpunkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert bei "ROLLBACK TO SAVEPOINT sp1" nach "INSERT INTO tasks (id, task) VALUES (2, ''Review''); SAVEPOINT sp1; DELETE FROM tasks WHERE id = 2"?', 4, '[{"text": "Stellt Review-Aufgabe wieder her", "correct": true, "because": "Zurück zu sp1"}, {"text": "Löscht Review dauerhaft", "correct": false, "because": "Kein COMMIT"}, {"text": "Ändert tasks", "correct": false, "because": "Kein UPDATE"}]');

