INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Trends > Beschaffen von Informationen über Auswirkungen auf das eigene Unternehmen, die Branche sowie die Gesellschaft
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Informationsbeschaffung über Trends nur für das eigene Unternehmen relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Branche und Gesellschaft sind betroffen"}, {"text": "Ja", "correct": false, "because": "Auswirkungen sind umfassender"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Informationsbeschaffung über Auswirkungen von Trends zwingend externe Quellen einbeziehen?', 2, '[{"text": "Ja", "correct": true, "because": "Externe Perspektiven sichern Objektivität"}, {"text": "Nein", "correct": false, "because": "Interne Daten allein sind unzureichend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Informationsbeschaffung über Trends ohne Berücksichtigung gesellschaftlicher Auswirkungen vollständig sein?', 2, '[{"text": "Nein", "correct": true, "because": "Gesellschaftliche Effekte sind integraler Bestandteil"}, {"text": "Ja", "correct": false, "because": "Gesellschaftliche Aspekte sind essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es ausreichend, Informationen über Trends nur einmalig zu beschaffen?', 2, '[{"text": "Nein", "correct": true, "because": "Trends entwickeln sich kontinuierlich"}, {"text": "Ja", "correct": false, "because": "Regelmäßigkeit ist erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Können interne Unternehmensdaten allein die Auswirkungen von Trends auf die Branche vollständig abbilden?', 2, '[{"text": "Nein", "correct": true, "because": "Branchenperspektive erfordert externe Daten"}, {"text": "Ja", "correct": false, "because": "Interne Sicht ist begrenzt"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Quelle ist für die Informationsbeschaffung über Trends am zuverlässigsten?', 2, '[{"text": "Fachstudien", "correct": true, "because": "Bieten fundierte Analysen"}, {"text": "Kundenumfragen", "correct": false, "because": "Subjektiv und begrenzt"}, {"text": "Interne Berichte", "correct": false, "because": "Fehlt externe Sicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Auswirkung von Trends sollte ein Unternehmen primär untersuchen?', 3, '[{"text": "Wettbewerbsposition", "correct": true, "because": "Entscheidend für Strategie"}, {"text": "Mitarbeiterzufriedenheit", "correct": false, "because": "Indirekt betroffen"}, {"text": "Produktionskosten", "correct": false, "because": "Sekundär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode ist am effektivsten, um Informationen über gesellschaftliche Auswirkungen von Trends zu beschaffen?', 2, '[{"text": "Sozialwissenschaftliche Studien", "correct": true, "because": "Analysieren gesellschaftliche Dynamiken"}, {"text": "Finanzberichte", "correct": false, "because": "Wirtschaftsfokus"}, {"text": "Produktfeedback", "correct": false, "because": "Kundenorientiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Informationsbeschaffung ist für die Branche am wichtigsten?', 2, '[{"text": "Wettbewerbsanalyse", "correct": true, "because": "Zeigt Marktpositionen"}, {"text": "Kundenpräferenzen", "correct": false, "because": "Kundenfokus"}, {"text": "Interne Prozesse", "correct": false, "because": "Unternehmensintern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Risiko entsteht, wenn Informationen über Trends nicht beschafft werden?', 2, '[{"text": "Strategische Fehlentscheidungen", "correct": true, "because": "Fehlende Daten führen zu Blindheit"}, {"text": "Geringere Produktivität", "correct": false, "because": "Indirekte Folge"}, {"text": "Technische Stagnation", "correct": false, "because": "Nicht primär"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Bereiche sollten bei der Informationsbeschaffung über Trends untersucht werden?', 4, '[{"text": "Unternehmensstrategie", "correct": true, "because": "Interne Anpassung nötig"}, {"text": "Branchenentwicklung", "correct": true, "because": "Wettbewerb beeinflusst"}, {"text": "Gesellschaftliche Veränderungen", "correct": true, "because": "Breiter Kontext"}, {"text": "Produktgestaltung", "correct": false, "because": "Folge, nicht Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Quellen sind für die Informationsbeschaffung über Trends geeignet?', 3, '[{"text": "Marktstudien", "correct": true, "because": "Analysieren Trends"}, {"text": "Fachzeitschriften", "correct": true, "because": "Aktuelle Entwicklungen"}, {"text": "Wettbewerberberichte", "correct": true, "because": "Vergleich möglich"}, {"text": "Mitarbeitermeinungen", "correct": false, "because": "Subjektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Auswirkungen auf das Unternehmen sollten bei der Informationsbeschaffung priorisiert werden?', 4, '[{"text": "Kostenstruktur", "correct": true, "because": "Effizienz betroffen"}, {"text": "Marktposition", "correct": true, "because": "Wettbewerbsfähigkeit"}, {"text": "Innovationsfähigkeit", "correct": true, "because": "Zukunftssicherung"}, {"text": "Mitarbeitermotivation", "correct": false, "because": "Indirekt relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden unterstützen die Informationsbeschaffung über Trends?', 3, '[{"text": "Datenanalyse", "correct": true, "because": "Erkennt Muster"}, {"text": "Experteninterviews", "correct": true, "because": "Liefert Einblicke"}, {"text": "Trendscouting", "correct": true, "because": "Proaktive Suche"}, {"text": "Produkttests", "correct": false, "because": "Reaktiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken entstehen bei unzureichender Informationsbeschaffung über Trends?', 3, '[{"text": "Wettbewerbsnachteile", "correct": true, "because": "Konkurrenz überholt"}, {"text": "Fehlende Anpassung", "correct": true, "because": "Markt wird verfehlt"}, {"text": "Reputationsverlust", "correct": true, "because": "Kunden erwarten Aktualität"}, {"text": "Geringere Produktionszeit", "correct": false, "because": "Keine Folge"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Informationsbeschaffung über Trends hilft bei der Strategieplanung. b) Sie ist nur für die Branche relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Strategie ja, auch Unternehmen und Gesellschaft"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Externe Studien sind für die Informationsbeschaffung essenziell. b) Gesellschaftliche Auswirkungen sind unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Studien ja, Gesellschaft relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Trendinformationen beeinflussen die Marktposition. b) Einmalige Beschaffung reicht für langfristige Planung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Markt ja, Kontinuität nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Wettbewerbsanalysen sind Teil der Informationsbeschaffung. b) Interne Daten reichen für Branchentrends aus.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Analysen ja, interne Daten unzureichend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Informationsbeschaffung schützt vor strategischen Fehlern. b) Sie ist nur für große Unternehmen nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schutz ja, gilt für alle"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

