INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Trends > Identifikation von Trends unter Berücksichtigung von Such- sowie Innovationsfeldern
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Identifikation von Trends ohne Berücksichtigung von Innovationsfeldern möglich?', 2, '[{"text": "Ja", "correct": true, "because": "Trends können auch ohne Innovationsfokus erkannt werden"}, {"text": "Nein", "correct": false, "because": "Innovationsfelder sind nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Suchfelder bei der Trendidentifikation immer technologische Entwicklungen umfassen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch soziale oder wirtschaftliche Aspekte zählen"}, {"text": "Ja", "correct": false, "because": "Suchfelder sind breiter gefasst"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Identifikation von Trends ohne externe Informationsquellen erfolgreich sein?', 2, '[{"text": "Nein", "correct": true, "because": "Externe Daten sind essenziell für Objektivität"}, {"text": "Ja", "correct": false, "because": "Interne Sicht ist begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Identifikation von Trends immer auf zukünftige Entwicklungen beschränkt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch aktuelle Muster werden erkannt"}, {"text": "Ja", "correct": false, "because": "Trends umfassen Gegenwart und Zukunft"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Innovationsfelder bei der Trendidentifikation zwingend branchenspezifisch sein?', 2, '[{"text": "Nein", "correct": true, "because": "Überbranchliche Innovationen sind relevant"}, {"text": "Ja", "correct": false, "because": "Breitere Felder können einfließen"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methode ist für die Identifikation von Trends am effektivsten?', 2, '[{"text": "Marktforschung", "correct": true, "because": "Liefert Daten und Prognosen"}, {"text": "Interne Brainstorming-Sitzungen", "correct": false, "because": "Subjektiv und begrenzt"}, {"text": "Zufällige Beobachtungen", "correct": false, "because": "Unstrukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Suchfeld ist bei der Trendidentifikation besonders relevant für IT-Systeme?', 3, '[{"text": "Technologische Innovationen", "correct": true, "because": "Direkter Einfluss auf IT"}, {"text": "Politische Entwicklungen", "correct": false, "because": "Indirekter Einfluss"}, {"text": "Kulturelle Veränderungen", "correct": false, "because": "Weniger spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Quelle sollte primär für die Trendidentifikation genutzt werden?', 2, '[{"text": "Fachpublikationen", "correct": true, "because": "Bieten fundierte Einblicke"}, {"text": "Kundensupport-Tickets", "correct": false, "because": "Reaktiv, nicht proaktiv"}, {"text": "Social-Media-Kommentare", "correct": false, "because": "Unstrukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Innovationsfeld prägt die Trendidentifikation in der IT am stärksten?', 2, '[{"text": "Künstliche Intelligenz", "correct": true, "because": "Breite Anwendung und Dynamik"}, {"text": "Hardware-Optimierung", "correct": false, "because": "Weniger dominant"}, {"text": "Netzwerksicherheit", "correct": false, "because": "Spezifischer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Fehler sollte bei der Trendidentifikation vermieden werden?', 2, '[{"text": "Ignorieren externer Daten", "correct": true, "because": "Führt zu Verzerrungen"}, {"text": "Fokus auf aktuelle Trends", "correct": false, "because": "Ist notwendig"}, {"text": "Nutzung von Analysetools", "correct": false, "because": "Ist hilfreich"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Suchfelder sind bei der Trendidentifikation relevant?', 4, '[{"text": "Technologische Entwicklungen", "correct": true, "because": "Kern der IT-Trends"}, {"text": "Wirtschaftliche Veränderungen", "correct": true, "because": "Beeinflussen Nachfrage"}, {"text": "Soziale Trends", "correct": true, "because": "Formen Nutzerverhalten"}, {"text": "Physische Geografie", "correct": false, "because": "Wenig Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Innovationsfelder sollten bei der Trendidentifikation berücksichtigt werden?', 3, '[{"text": "Künstliche Intelligenz", "correct": true, "because": "Prägt IT-Zukunft"}, {"text": "Cloud Computing", "correct": true, "because": "Verändert Infrastruktur"}, {"text": "Blockchain", "correct": true, "because": "Neue Anwendungen"}, {"text": "Manuelle Prozesse", "correct": false, "because": "Veraltet"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Quellen unterstützen die Identifikation von Trends?', 4, '[{"text": "Fachmessen", "correct": true, "because": "Zeigen Innovationen"}, {"text": "Wissenschaftliche Studien", "correct": true, "because": "Bieten Tiefe"}, {"text": "Branchenberichte", "correct": true, "because": "Geben Überblick"}, {"text": "Interne Memos", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Trendidentifikation?', 3, '[{"text": "Datenüberflutung", "correct": true, "because": "Viel Information erschwert Fokus"}, {"text": "Schnelle Veränderungen", "correct": true, "because": "Trends entwickeln sich rasant"}, {"text": "Fehlende Expertise", "correct": true, "because": "Erfordert Fachwissen"}, {"text": "Langsame Reaktion", "correct": false, "because": "Folge, nicht Ursache"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sind bei der Trendidentifikation essenziell?', 3, '[{"text": "Datensammlung", "correct": true, "because": "Grundlage der Analyse"}, {"text": "Bewertung von Relevanz", "correct": true, "because": "Filtert Wichtiges"}, {"text": "Prognose von Entwicklungen", "correct": true, "because": "Orientiert zukunftsgerichtet"}, {"text": "Produktfertigung", "correct": false, "because": "Folgeprozess"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Trendidentifikation erfordert externe Quellen. b) Sie beschränkt sich auf technologische Felder.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Quellen ja, Felder breiter"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Innovationsfelder wie KI sind bei der Trendidentifikation zentral. b) Soziale Trends sind irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "KI ja, soziale Trends auch wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Fachmessen helfen bei der Trendidentifikation. b) Interne Daten reichen für eine vollständige Analyse.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Fachmessen ja, interne Daten begrenzt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Trendidentifikation umfasst aktuelle und zukünftige Entwicklungen. b) Sie erfordert keine Analyse.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeitrahmen ja, Analyse nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Datenüberflutung ist eine Herausforderung bei der Trendidentifikation. b) Innovationsfelder müssen branchenspezifisch sein.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Überflutung ja, Felder flexibel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

