INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Trends > Nutzen geeigneter Informationsquellen, z.B. Fachmessen, Fachforen im Internet, um neue Trends sowie Einsatzgebiete wahrzunehmen
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Nutzung von Fachmessen und Fachforen zwingend erforderlich, um Trends und Einsatzgebiete zu erkennen?', 2, '[{"text": "Nein", "correct": true, "because": "Andere Quellen wie Studien oder Newsletter sind ebenfalls geeignet"}, {"text": "Ja", "correct": false, "because": "Nicht die einzige Option"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Fachmessen und Fachforen aktuelle Trends schneller aufzeigen als wissenschaftliche Publikationen?', 2, '[{"text": "Ja", "correct": true, "because": "Sie bieten oft direkte Einblicke in Echtzeit"}, {"text": "Nein", "correct": false, "because": "Aktualität ist ein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Teilnahme an Fachmessen und Fachforen ohne Kosten möglich?', 2, '[{"text": "Nein", "correct": true, "because": "Fachmessen haben oft Eintrittsgebühren, Foren können indirekte Kosten verursachen"}, {"text": "Ja", "correct": false, "because": "Kosten sind üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Fachmessen und Fachforen auch neue Einsatzgebiete für bestehende Technologien aufzeigen?', 2, '[{"text": "Ja", "correct": true, "because": "Diskussionen und Präsentationen zeigen neue Anwendungen"}, {"text": "Nein", "correct": false, "because": "Einsatzgebiete werden oft thematisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Fachmessen und Fachforen immer branchenspezifisch ausgerichtet?', 2, '[{"text": "Nein", "correct": true, "because": "Einige decken breitere oder übergreifende Themen ab"}, {"text": "Ja", "correct": false, "because": "Nicht immer spezifisch"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil von Fachmessen ist für die Trendwahrnehmung am bedeutendsten?', 2, '[{"text": "Direkter Kontakt zu Experten", "correct": true, "because": "Ermöglicht unmittelbare Einblicke"}, {"text": "Kostenlose Teilnahme", "correct": false, "because": "Selten der Fall"}, {"text": "Breite Öffentlichkeit", "correct": false, "because": "Fokus liegt auf Fachleuten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal von Fachforen im Internet unterstützt die Identifikation neuer Einsatzgebiete am besten?', 3, '[{"text": "Diskussionen von Nutzern", "correct": true, "because": "Vielfalt der Perspektiven"}, {"text": "Kostenfreier Zugang", "correct": false, "because": "Nicht primär relevant"}, {"text": "Offizielle Veröffentlichungen", "correct": false, "because": "Weniger dynamisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Informationsquelle ist auf Fachmessen am häufigsten verfügbar?', 2, '[{"text": "Produktvorstellungen", "correct": true, "because": "Hersteller präsentieren Innovationen"}, {"text": "Wissenschaftliche Vorträge", "correct": false, "because": "Weniger dominant"}, {"text": "Kundenbefragungen", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Nachteil von Fachmessen kann die Trendwahrnehmung erschweren?', 2, '[{"text": "Hohe Kosten", "correct": true, "because": "Begrenzt Zugang für kleinere Unternehmen"}, {"text": "Zu viele Besucher", "correct": false, "because": "Eher organisatorisch"}, {"text": "Mangelnde Aktualität", "correct": false, "because": "Nicht zutreffend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaft von Fachforen macht sie für die Trendwahrnehmung besonders nützlich?', 2, '[{"text": "Globale Reichweite", "correct": true, "because": "Ermöglicht weltweite Perspektiven"}, {"text": "Physische Präsenz", "correct": false, "because": "Nicht anwendbar"}, {"text": "Kostenintensität", "correct": false, "because": "Eher gering"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Fachmessen für die Trendwahrnehmung?', 4, '[{"text": "Live-Demonstrationen", "correct": true, "because": "Zeigen praktische Anwendungen"}, {"text": "Networking-Möglichkeiten", "correct": true, "because": "Fördern Austausch"}, {"text": "Aktuelle Markttrends", "correct": true, "because": "Direkt sichtbar"}, {"text": "Kostenlose Teilnahme", "correct": false, "because": "Selten der Fall"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale machen Fachforen im Internet nützlich für die Trendwahrnehmung?', 3, '[{"text": "Vielfalt der Meinungen", "correct": true, "because": "Breites Spektrum an Ideen"}, {"text": "Schnelle Updates", "correct": true, "because": "Aktuelle Diskussionen"}, {"text": "Zugang zu Experten", "correct": true, "because": "Fachleute beteiligt"}, {"text": "Physische Produktproben", "correct": false, "because": "Nicht möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Informationen können auf Fachmessen und Fachforen gewonnen werden?', 4, '[{"text": "Neue Technologien", "correct": true, "because": "Hauptfokus"}, {"text": "Einsatzgebiete", "correct": true, "because": "Praktische Anwendungen"}, {"text": "Markttrends", "correct": true, "because": "Wettbewerb sichtbar"}, {"text": "Mitarbeitergehälter", "correct": false, "because": "Nicht thematisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Nutzung von Fachmessen und Fachforen?', 3, '[{"text": "Kostenaufwand", "correct": true, "because": "Teilnahme oft teuer"}, {"text": "Informationsüberflutung", "correct": true, "because": "Viel Datenvolumen"}, {"text": "Zeitaufwand", "correct": true, "because": "Besuch oder Suche nötig"}, {"text": "Technische Stabilität", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen maximieren den Nutzen von Fachmessen und Fachforen?', 3, '[{"text": "Gezielte Auswahl", "correct": true, "because": "Relevanz erhöhen"}, {"text": "Aktive Teilnahme", "correct": true, "because": "Fördert Austausch"}, {"text": "Nachbereitung", "correct": true, "because": "Sichert Erkenntnisse"}, {"text": "Kostenreduktion", "correct": false, "because": "Nicht primär"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Fachmessen bieten Einblicke in neue Technologien. b) Sie sind die einzige Quelle für Trendwahrnehmung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Technologien ja, einzige Quelle nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Fachforen bieten globale Perspektiven auf Trends. b) Sie ersetzen Fachmessen vollständig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Global ja, Ersatz nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Fachmessen zeigen neue Einsatzgebiete. b) Sie sind immer kostenfrei zugänglich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Einsatzgebiete ja, kostenfrei nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Fachforen ermöglichen Diskussionen über Trends. b) Sie sind immer branchenspezifisch.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Diskussionen ja, nicht immer spezifisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Fachmessen fördern Networking für Trendwahrnehmung. b) Fachforen sind zeitlich begrenzt wie Messen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Networking ja, Foren dauerhaft"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

