INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Softwarearchitektur > Design Pattern > Model View Controller (MVC)
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist im MVC-Muster die View direkt mit dem Model verbunden?', 2, '[{"text": "Nein", "correct": true, "because": "Der Controller vermittelt zwischen Model und View"}, {"text": "Ja", "correct": false, "because": "Direkte Verbindung widerspricht MVC"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann das MVC-Muster in kleinen Anwendungen ohne Controller implementiert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Der Controller ist essenziell für die Steuerung"}, {"text": "Ja", "correct": false, "because": "Ohne Controller kein vollständiges MVC"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss das Model im MVC-Muster die Geschäftslogik enthalten?', 2, '[{"text": "Ja", "correct": true, "because": "Das Model repräsentiert Daten und Logik"}, {"text": "Nein", "correct": false, "because": "Logik ist Kern des Models"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die View im MVC-Muster Benutzereingaben direkt an das Model weiterleiten?', 2, '[{"text": "Nein", "correct": true, "because": "Eingaben gehen über den Controller"}, {"text": "Ja", "correct": false, "because": "Controller vermittelt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist das MVC-Muster nur für Webanwendungen geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Es kann auch in Desktop- oder anderen Anwendungen genutzt werden"}, {"text": "Ja", "correct": false, "because": "Anwendung ist breiter"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Komponente im MVC-Muster ist für die Benutzeroberfläche verantwortlich?', 2, '[{"text": "View", "correct": true, "because": "Die View zeigt die Daten an"}, {"text": "Model", "correct": false, "because": "Model enthält Daten und Logik"}, {"text": "Controller", "correct": false, "because": "Controller steuert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat der Controller im MVC-Muster primär?', 3, '[{"text": "Steuerung von Benutzereingaben", "correct": true, "because": "Er vermittelt zwischen View und Model"}, {"text": "Datenanzeige", "correct": false, "because": "Aufgabe der View"}, {"text": "Datenbankverwaltung", "correct": false, "because": "Aufgabe des Models"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil des MVC-Musters ist am bedeutendsten?', 2, '[{"text": "Trennung von Verantwortlichkeiten", "correct": true, "because": "Fördert Wartbarkeit und Testbarkeit"}, {"text": "Hohe Performance", "correct": false, "because": "Nicht primär"}, {"text": "Geringere Kosten", "correct": false, "because": "Nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt das Model im MVC-Muster?', 2, '[{"text": "Daten und Geschäftslogik verwalten", "correct": true, "because": "Es repräsentiert die Anwendungslogik"}, {"text": "Benutzerinteraktion steuern", "correct": false, "because": "Aufgabe des Controllers"}, {"text": "Daten anzeigen", "correct": false, "because": "Aufgabe der View"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Problem kann im MVC-Muster auftreten, wenn die Komponenten nicht klar getrennt sind?', 2, '[{"text": "Schwierige Wartung", "correct": true, "because": "Vermischung erschwert Änderungen"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Eher Verzögerung"}, {"text": "Geringere Sicherheit", "correct": false, "because": "Indirekte Folge"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zum MVC-Muster?', 4, '[{"text": "Model", "correct": true, "because": "Daten und Logik"}, {"text": "View", "correct": true, "because": "Benutzeroberfläche"}, {"text": "Controller", "correct": true, "because": "Steuerung"}, {"text": "Database", "correct": false, "because": "Kein direkter Bestandteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet das MVC-Muster?', 3, '[{"text": "Modularität", "correct": true, "because": "Trennung erleichtert Änderungen"}, {"text": "Testbarkeit", "correct": true, "because": "Komponenten separat testbar"}, {"text": "Wartbarkeit", "correct": true, "because": "Klare Struktur hilft"}, {"text": "Hohe Komplexität", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben kann der Controller im MVC-Muster übernehmen?', 4, '[{"text": "Verarbeitung von Eingaben", "correct": true, "because": "Steuert Benutzeraktionen"}, {"text": "Aktualisierung des Models", "correct": true, "because": "Leitet Änderungen weiter"}, {"text": "Steuerung der View", "correct": true, "because": "Bestimmt Anzeige"}, {"text": "Datenbankdesign", "correct": false, "because": "Aufgabe des Models"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es beim Einsatz des MVC-Musters?', 3, '[{"text": "Komplexität bei kleinen Projekten", "correct": true, "because": "Aufwand kann übermäßig sein"}, {"text": "Abhängigkeit zwischen Controller und Model", "correct": true, "because": "Kopplung möglich"}, {"text": "Koordination zwischen Komponenten", "correct": true, "because": "Kommunikation nötig"}, {"text": "Geringere Flexibilität", "correct": false, "because": "Eher flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien werden typischerweise im MVC-Muster eingesetzt?', 3, '[{"text": "HTML/CSS für die View", "correct": true, "because": "Web-Oberflächen"}, {"text": "Java für den Controller", "correct": true, "because": "Häufige Steuerlogik"}, {"text": "SQL für das Model", "correct": true, "because": "Datenverwaltung"}, {"text": "Assembly für Netzwerk", "correct": false, "because": "Nicht relevant"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die View im MVC-Muster zeigt die Benutzeroberfläche an. b) Sie aktualisiert direkt das Model.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Anzeige ja, Aktualisierung über Controller"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Controller steuert Benutzereingaben im MVC-Muster. b) Er ist für die Datenanzeige verantwortlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Steuerung ja, Anzeige nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Das Model enthält die Geschäftslogik im MVC-Muster. b) Es kann ohne Controller funktionieren.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Logik ja, Controller nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) MVC fördert die Trennung von Verantwortlichkeiten. b) Es ist nur für Webanwendungen geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Trennung ja, Anwendung breiter"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Koordination zwischen MVC-Komponenten kann komplex sein. b) Der Controller zeigt die Benutzeroberfläche an.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Koordination ja, Anzeige nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

