INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Design Pattern > Model-View-ViewModel (MVVM)
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist im MVVM-Muster die View direkt mit dem Model verbunden?', 2, '[{"text": "Nein", "correct": true, "because": "Das ViewModel vermittelt zwischen View und Model"}, {"text": "Ja", "correct": false, "because": "Direkte Verbindung widerspricht MVVM"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann das ViewModel im MVVM-Muster Daten direkt an die View binden?', 2, '[{"text": "Ja", "correct": true, "because": "Data Binding ist ein Kernmerkmal von MVVM"}, {"text": "Nein", "correct": false, "because": "Binding ist zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss das Model im MVVM-Muster die Benutzeroberflächenlogik enthalten?', 2, '[{"text": "Nein", "correct": true, "because": "Das Model enthält Geschäftslogik, nicht UI-Logik"}, {"text": "Ja", "correct": false, "because": "UI-Logik liegt im ViewModel"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die View im MVVM-Muster ohne ViewModel direkt auf das Model zugreifen?', 2, '[{"text": "Nein", "correct": true, "because": "Das ViewModel abstrahiert das Model für die View"}, {"text": "Ja", "correct": false, "because": "Direkter Zugriff widerspricht MVVM"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist das MVVM-Muster besonders geeignet für Anwendungen mit Data Binding?', 2, '[{"text": "Ja", "correct": true, "because": "Data Binding ist ein Hauptvorteil von MVVM"}, {"text": "Nein", "correct": false, "because": "Binding ist typisch"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Komponente im MVVM-Muster ist für die Vermittlung zwischen Model und View verantwortlich?', 2, '[{"text": "ViewModel", "correct": true, "because": "Es abstrahiert das Model für die View"}, {"text": "Model", "correct": false, "because": "Enthält Daten und Logik"}, {"text": "View", "correct": false, "because": "Zeigt nur die UI"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil des MVVM-Musters ist am bedeutendsten?', 3, '[{"text": "Trennung von UI und Logik", "correct": true, "because": "Fördert Testbarkeit und Wartbarkeit"}, {"text": "Hohe Performance", "correct": false, "because": "Nicht primär"}, {"text": "Geringere Komplexität", "correct": false, "because": "Komplexität kann steigen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie wird im MVVM-Muster häufig für die Datenbindung verwendet?', 2, '[{"text": "Data Binding Frameworks", "correct": true, "because": "Wie WPF oder Angular unterstützen Binding"}, {"text": "Direkte Methodenaufrufe", "correct": false, "because": "Nicht typisch"}, {"text": "SQL Queries", "correct": false, "because": "Datenbankbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat das Model im MVVM-Muster primär?', 2, '[{"text": "Geschäftslogik bereitstellen", "correct": true, "because": "Model enthält Daten und Logik"}, {"text": "Benutzeroberfläche anzeigen", "correct": false, "because": "Aufgabe der View"}, {"text": "Daten an View binden", "correct": false, "because": "Aufgabe des ViewModels"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Nachteil tritt beim MVVM-Muster am häufigsten auf?', 2, '[{"text": "Komplexität bei kleinen Projekten", "correct": true, "because": "Overhead durch ViewModel"}, {"text": "Geringe Testbarkeit", "correct": false, "because": "Testbarkeit ist Vorteil"}, {"text": "Hohe Latenz", "correct": false, "because": "Nicht typisch"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zum MVVM-Muster?', 4, '[{"text": "Model", "correct": true, "because": "Daten und Geschäftslogik"}, {"text": "View", "correct": true, "because": "Benutzeroberfläche"}, {"text": "ViewModel", "correct": true, "because": "Vermittler und Datenbinder"}, {"text": "Controller", "correct": false, "because": "Teil von MVC, nicht MVVM"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet das MVVM-Muster?', 3, '[{"text": "Testbarkeit", "correct": true, "because": "Logik im ViewModel ist testbar"}, {"text": "Wartbarkeit", "correct": true, "because": "Trennung erleichtert Änderungen"}, {"text": "Datenbindung", "correct": true, "because": "Automatische UI-Updates"}, {"text": "Hohe Komplexität", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben übernimmt das ViewModel im MVVM-Muster?', 4, '[{"text": "Daten für die View vorbereiten", "correct": true, "because": "Abstrahiert das Model"}, {"text": "Benutzereingaben verarbeiten", "correct": true, "because": "Reagiert auf Eingaben"}, {"text": "Datenbindung ermöglichen", "correct": true, "because": "Kernfunktion"}, {"text": "Datenbankzugriffe", "correct": false, "because": "Aufgabe des Models"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es beim MVVM-Muster?', 3, '[{"text": "Komplexität der Datenbindung", "correct": true, "because": "Kann schwer zu debuggen sein"}, {"text": "Erhöhter Entwicklungsaufwand", "correct": true, "because": "ViewModel benötigt Extraarbeit"}, {"text": "Abhängigkeit von Frameworks", "correct": true, "because": "Binding oft frameworkabhängig"}, {"text": "Geringere Flexibilität", "correct": false, "because": "Eher flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien unterstützen das MVVM-Muster häufig?', 3, '[{"text": "WPF", "correct": true, "because": "Starkes Data Binding"}, {"text": "Angular", "correct": true, "because": "Zwei-Wege-Binding"}, {"text": "Knockout.js", "correct": true, "because": "Unterstützt MVVM"}, {"text": "SOAP", "correct": false, "because": "Webservice-Protokoll"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Das ViewModel vermittelt zwischen View und Model. b) Die View greift direkt auf das Model zu.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "ViewModel ja, direkter Zugriff nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) MVVM nutzt Datenbindung für die View. b) Das Model enthält UI-Logik.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Datenbindung ja, UI-Logik nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) MVVM fördert die Testbarkeit der Logik. b) Es ist für Projekte ohne Binding ungeeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Testbarkeit ja, Binding nicht zwingend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Das ViewModel verarbeitet Benutzereingaben. b) MVVM ist ausschließlich für Webanwendungen geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Eingaben ja, Anwendung breiter"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Komplexität der Datenbindung ist eine Herausforderung bei MVVM. b) Das Model zeigt die Benutzeroberfläche an.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Komplexität ja, UI ist View"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

