-- Arbeitsrecht Berufsbildung > Berufsbildungsgesetz (BBiG) > Probezeitregelung
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Muss ein Ausbildungsvertrag für einen Fachinformatiker eine Probezeit enthalten?', 2, '[{"text": "Ja", "correct": true, "because": "§ 7 BBiG schreibt eine Probezeit vor"}, {"text": "Nein", "correct": false, "because": "Probezeit ist verpflichtend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Probezeit eines Fachinformatikers weniger als einen Monat betragen?', 2, '[{"text": "Nein", "correct": true, "because": "§ 7 BBiG legt mindestens einen Monat fest"}, {"text": "Ja", "correct": false, "because": "Mindestdauer ist vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Darf ein Betrieb einen Fachinformatiker während der Probezeit ohne Angabe von Gründen kündigen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 22 Abs. 1 BBiG erlaubt dies in der Probezeit"}, {"text": "Nein", "correct": false, "because": "Keine Begründung erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Probezeit eines Fachinformatikers länger als 4 Monate sein?', 2, '[{"text": "Nein", "correct": true, "because": "§ 7 BBiG begrenzt die Probezeit auf maximal 4 Monate"}, {"text": "Ja", "correct": false, "because": "Maximaldauer ist festgelegt"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Fachinformatiker während der Probezeit eine Vergütung erhalten?', 2, '[{"text": "Ja", "correct": true, "because": "§ 17 BBiG garantiert Vergütung ab Beginn"}, {"text": "Nein", "correct": false, "because": "Vergütung ist Pflicht"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Paragraph des BBiG regelt die Probezeit eines Fachinformatikers?', 2, '[{"text": "§ 7 BBiG", "correct": true, "because": "Legt die Probezeitregelung fest"}, {"text": "§ 13 BBiG", "correct": false, "because": "Bezieht sich auf Pflichten des Auszubildenden"}, {"text": "§ 22 BBiG", "correct": false, "because": "Regelt Kündigungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie lange beträgt die Mindestdauer der Probezeit für einen Fachinformatiker?', 2, '[{"text": "1 Monat", "correct": true, "because": "§ 7 BBiG legt dies als Mindestdauer fest"}, {"text": "2 Wochen", "correct": false, "because": "Zu kurz"}, {"text": "3 Monate", "correct": false, "because": "Nicht die Mindestdauer"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die maximale Dauer der Probezeit für einen Fachinformatiker?', 3, '[{"text": "4 Monate", "correct": true, "because": "§ 7 BBiG begrenzt die Probezeit auf maximal 4 Monate"}, {"text": "6 Monate", "correct": false, "because": "Zu lang"}, {"text": "2 Monate", "correct": false, "because": "Unter der Maximaldauer"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer bestimmt die genaue Dauer der Probezeit eines Fachinformatikers?', 2, '[{"text": "Betrieb und Auszubildender im Vertrag", "correct": true, "because": "§ 7 BBiG erlaubt Vereinbarung innerhalb der Grenzen"}, {"text": "Die IHK", "correct": false, "because": "IHK hat keine Festlegungsbefugnis"}, {"text": "Die Berufsschule", "correct": false, "because": "Schule ist nicht zuständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Fachinformatiker während der Probezeit gekündigt wird?', 3, '[{"text": "Die Kündigung wirkt mit 2 Wochen Frist", "correct": true, "because": "§ 22 Abs. 1 BBiG legt dies fest"}, {"text": "Die Kündigung ist unwirksam", "correct": false, "because": "Kündigung ist in Probezeit möglich"}, {"text": "Die Ausbildung wird verlängert", "correct": false, "because": "Nicht vorgeschrieben"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Regelungen gelten für die Probezeit eines Fachinformatikers gemäß § 7 BBiG?', 4, '[{"text": "Mindestdauer von 1 Monat", "correct": true, "because": "§ 7 BBiG legt dies fest"}, {"text": "Maximaldauer von 4 Monaten", "correct": true, "because": "§ 7 BBiG begrenzt die Dauer"}, {"text": "Verlängerung bis zu 6 Monaten", "correct": false, "because": "Nicht erlaubt"}, {"text": "Vereinbarung im Ausbildungsvertrag", "correct": true, "because": "Dauer wird vertraglich festgelegt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rechte hat ein Fachinformatiker während der Probezeit?', 3, '[{"text": "Anspruch auf Vergütung", "correct": true, "because": "§ 17 BBiG gilt ab Beginn"}, {"text": "Freistellung für Berufsschule", "correct": true, "because": "§ 15 BBiG schützt dies"}, {"text": "Besonderer Kündigungsschutz", "correct": false, "because": "Nicht in der Probezeit"}, {"text": "Schriftlicher Nachweis der Arbeitszeit", "correct": true, "because": "§ 2 NachwG gilt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gilt für die Kündigung eines Fachinformatikers während der Probezeit?', 4, '[{"text": "2 Wochen Kündigungsfrist", "correct": true, "because": "§ 22 Abs. 1 BBiG legt dies fest"}, {"text": "Keine Begründung erforderlich", "correct": true, "because": "Probezeit ohne Grund"}, {"text": "Schriftform ist optional", "correct": false, "because": "Schriftform ist Pflicht"}, {"text": "Beidseitiges Kündigungsrecht", "correct": true, "because": "Betrieb und Auszubildender dürfen kündigen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat ein Betrieb gegenüber einem Fachinformatiker während der Probezeit?', 3, '[{"text": "Vergütung zahlen", "correct": true, "because": "§ 17 BBiG verpflichtet dazu"}, {"text": "Gewissenhafte Ausbildung", "correct": true, "because": "§ 14 Abs. 1 BBiG gilt ab Beginn"}, {"text": "Keine Unterweisung bieten", "correct": false, "because": "Unterweisung ist Pflicht"}, {"text": "Arbeitsmittel bereitstellen", "correct": true, "because": "§ 14 Abs. 1 BBiG fordert dies"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte müssen im Ausbildungsvertrag zur Probezeit eines Fachinformatikers festgelegt werden?', 3, '[{"text": "Dauer der Probezeit", "correct": true, "because": "§ 7 BBiG verlangt dies"}, {"text": "Beginn der Probezeit", "correct": true, "because": "Teil der vertraglichen Festlegung"}, {"text": "Ende der Ausbildung", "correct": false, "because": "Nicht spezifisch für Probezeit"}, {"text": "Kündigungsfrist in der Probezeit", "correct": true, "because": "§ 22 Abs. 1 BBiG wird vertraglich geregelt"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Probezeit eines Fachinformatikers beträgt mindestens 1 Monat. b) Sie kann 6 Monate dauern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Mindestdauer 1 Monat, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Betrieb kann einen Fachinformatiker in der Probezeit mit 2 Wochen Frist kündigen. b) Eine Begründung ist in der Probezeit erforderlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "2 Wochen korrekt, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Probezeit eines Fachinformatikers ist maximal 4 Monate. b) Während der Probezeit gilt kein Kündigungsschutz.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "§ 7 und § 22 Abs. 1 BBiG bestätigen dies"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Ein Fachinformatiker kann in der Probezeit mit 2 Wochen Frist kündigen. b) Die Probezeit kann verlängert werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "2 Wochen korrekt, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Probezeit eines Fachinformatikers muss im Vertrag festgelegt werden. b) Während der Probezeit entfällt die Vergütung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vertraglich festgelegt, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');