-- # Lernfeld 5: Cyberphysische Systeme > ## Testgetriebene Entwicklung > - Tests > - Testprozess > - Testplanung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann die Testplanung in der testgetriebenen Entwicklung (TDD) vollständig vor der Implementierung abgeschlossen werden?', 2, '[{"text": "Nein", "correct": true, "because": "TDD erfordert iterative Tests parallel zur Entwicklung"}, {"text": "Ja", "correct": false, "because": "Tests entstehen mit dem Code"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Testplanung in TDD notwendig, um die Anforderungen der Software zu definieren?', 2, '[{"text": "Ja", "correct": true, "because": "Tests spiegeln Anforderungen wider"}, {"text": "Nein", "correct": false, "because": "Tests sind Anforderungsgrundlage"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Testfälle in der Testplanung ohne Kenntnis der Implementierungsdetails erstellt werden?', 2, '[{"text": "Ja", "correct": true, "because": "TDD fokussiert sich auf das Was, nicht das Wie"}, {"text": "Nein", "correct": false, "because": "Anforderungen reichen aus"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Testplanung in TDD alle möglichen Fehlerfälle vor der Entwicklung abdecken?', 2, '[{"text": "Nein", "correct": true, "because": "Iterative Anpassung der Tests ist üblich"}, {"text": "Ja", "correct": false, "because": "TDD ist dynamisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine unzureichende Testplanung in TDD die Softwarequalität negativ beeinflussen?', 2, '[{"text": "Ja", "correct": true, "because": "Unklare Tests führen zu unklarer Qualität"}, {"text": "Nein", "correct": false, "because": "Planung ist entscheidend"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Testplanung in der testgetriebenen Entwicklung?', 2, '[{"text": "Definition der Anforderungen durch Tests", "correct": true, "because": "Tests spezifizieren Verhalten"}, {"text": "Erstellung eines vollständigen Testberichts", "correct": false, "because": "Ergebnis, kein Ziel"}, {"text": "Optimierung der Laufzeit", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Testplanung in TDD im Vergleich zu traditionellen Methoden?', 3, '[{"text": "Sie treibt die Entwicklung voran", "correct": true, "because": "Tests vor Code"}, {"text": "Sie erfolgt nach der Implementierung", "correct": false, "because": "Traditioneller Ansatz"}, {"text": "Sie ist optional", "correct": false, "because": "TDD erfordert sie"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist in der Testplanung von TDD zentral?', 2, '[{"text": "Testfälle", "correct": true, "because": "Definieren erwartetes Verhalten"}, {"text": "Testdaten", "correct": false, "because": "Unterstützend, nicht zentral"}, {"text": "Testwerkzeuge", "correct": false, "because": "Hilfsmittel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird in der Testplanung von TDD typischerweise zuerst angewendet?', 2, '[{"text": "Schreiben eines fehlschlagenden Tests", "correct": true, "because": "TDD-Zyklus beginnt so"}, {"text": "Erstellen eines Testberichts", "correct": false, "because": "Späterer Schritt"}, {"text": "Debuggen des Codes", "correct": false, "because": "Nach Implementierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptmerkmal der Testplanung in TDD?', 2, '[{"text": "Iterative Erstellung", "correct": true, "because": "Tests wachsen mit dem Code"}, {"text": "Einmalige Definition", "correct": false, "because": "Nicht TDD-typisch"}, {"text": "Manuelle Überprüfung", "correct": false, "because": "Automatisierung üblich"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Schritte umfasst die Testplanung in der testgetriebenen Entwicklung?', 4, '[{"text": "Identifikation der Anforderungen", "correct": true, "because": "Tests basieren darauf"}, {"text": "Erstellung von Testfällen", "correct": true, "because": "Kern der Planung"}, {"text": "Manuelles Testen", "correct": false, "because": "Automatisierung bevorzugt"}, {"text": "Definition von Akzeptanzkriterien", "correct": true, "because": "Bestimmt Erfolg"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien leiten die Testplanung in TDD?', 3, '[{"text": "Test vor Code", "correct": true, "because": "Grundprinzip von TDD"}, {"text": "Minimale Implementierung", "correct": true, "because": "Nur nötiger Code"}, {"text": "Maximale Abdeckung von Anfang an", "correct": false, "because": "Iterativ, nicht maximal"}, {"text": "Kontinuierliches Refactoring", "correct": true, "because": "Verbessert Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Testplanung in TDD?', 3, '[{"text": "Klarheit über Anforderungen", "correct": true, "because": "Tests spezifizieren"}, {"text": "Frühe Fehlererkennung", "correct": true, "because": "Tests schlagen früh fehl"}, {"text": "Langsamere Entwicklung", "correct": false, "because": "Eher schneller durch Fokus"}, {"text": "Bessere Codequalität", "correct": true, "because": "Tests erzwingen Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Testplanung in TDD?', 4, '[{"text": "Hoher Anfangsinvest", "correct": true, "because": "Tests vor Code kosten Zeit"}, {"text": "Komplexität bei großen Systemen", "correct": true, "because": "Viele Tests nötig"}, {"text": "Einfache Implementierung", "correct": false, "because": "Eher komplexer"}, {"text": "Anpassung an Änderungen", "correct": true, "because": "Tests müssen mitangepasst werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente sollten in der Testplanung von TDD berücksichtigt werden?', 3, '[{"text": "Funktionale Anforderungen", "correct": true, "because": "Tests spezifizieren Funktionen"}, {"text": "Nicht-funktionale Anforderungen", "correct": true, "because": "Leistung kann getestet werden"}, {"text": "Hardwarekonfiguration", "correct": false, "because": "Nicht primär"}, {"text": "Abdeckungsgrad", "correct": true, "because": "Sichert Testqualität"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Testplanung in TDD erfolgt ausschließlich vor der Entwicklung. b) Tests in TDD definieren das Verhalten der Software.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Planung iterativ, Tests definieren"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Testplanung in TDD erfordert detaillierte Implementierungskenntnisse. b) Testfälle in TDD werden iterativ erstellt.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Keine Details nötig, iterativ korrekt"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Testplanung in TDD garantiert fehlerfreie Software. b) TDD-Tests dienen als Spezifikation.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Keine Garantie, Tests spezifizieren"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) In TDD wird die Testplanung einmalig vor Projektstart erstellt. b) Eine gute Testplanung in TDD reduziert Refactoring-Aufwand.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Planung iterativ, gute Tests helfen"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Testplanung in TDD fokussiert sich auf Anforderungen, nicht Implementierung. b) TDD erfordert keine Testplanung vorab.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Fokus auf Anforderungen, Planung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

