-- # Lernfeld 5: Cyberphysische Systeme > ## Testgetriebene Entwicklung > - Tests > - Testprozess > - Testergebnisauswertung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Testergebnisauswertung in der testgetriebenen Entwicklung (TDD) zwingend erforderlich, um den nächsten Entwicklungsschritt zu bestimmen?', 2, '[{"text": "Ja", "correct": true, "because": "Ergebnisse leiten Rot-Grün-Refaktor-Zyklus"}, {"text": "Nein", "correct": false, "because": "Auswertung ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine fehlerhafte Testergebnisauswertung in TDD zu einer falschen Implementierung führen?', 2, '[{"text": "Ja", "correct": true, "because": "Missverständnisse beeinflussen Code"}, {"text": "Nein", "correct": false, "because": "Auswertung steuert Entwicklung"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle Testergebnisse in TDD vor der Implementierung positiv sein?', 2, '[{"text": "Nein", "correct": true, "because": "Tests schlagen zunächst fehl"}, {"text": "Ja", "correct": false, "because": "Rot-Phase ist Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Testergebnisauswertung in TDD ohne Automatisierung effizient durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Manuelle Auswertung ist zeitaufwendig"}, {"text": "Ja", "correct": false, "because": "Automatisierung ist TDD-Kern"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Testergebnisauswertung in TDD unabhängig von den definierten Anforderungen?', 2, '[{"text": "Nein", "correct": true, "because": "Ergebnisse prüfen Anforderungserfüllung"}, {"text": "Ja", "correct": false, "because": "Anforderungen sind Grundlage"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Testergebnisauswertung in TDD?', 2, '[{"text": "Bestimmung des nächsten Entwicklungsschritts", "correct": true, "because": "Leitet Rot-Grün-Refaktor"}, {"text": "Erstellung eines Abschlussberichts", "correct": false, "because": "Nicht primär"}, {"text": "Optimierung der Laufzeit", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ergebnis in der Testergebnisauswertung zeigt an, dass der Code noch nicht korrekt ist?', 3, '[{"text": "Testfehlschlag", "correct": true, "because": "Rot-Phase signalisiert Fehler"}, {"text": "Test erfolgreich", "correct": false, "because": "Grün zeigt Korrektheit"}, {"text": "Test übersprungen", "correct": false, "because": "Keine Aussage"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug unterstützt die Testergebnisauswertung in TDD am effektivsten?', 2, '[{"text": "Test-Framework", "correct": true, "because": "Automatisiert Auswertung"}, {"text": "Texteditor", "correct": false, "because": "Kein Auswertungstool"}, {"text": "Debugger", "correct": false, "because": "Fehleranalyse, nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Schritt folgt in TDD direkt auf eine erfolgreiche Testergebnisauswertung?', 2, '[{"text": "Refactoring", "correct": true, "because": "Grün-Phase führt zu Verbesserung"}, {"text": "Neuer Testfall", "correct": false, "because": "Nach Refactoring"}, {"text": "Code-Dokumentation", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium ist bei der Testergebnisauswertung in TDD entscheidend?', 2, '[{"text": "Übereinstimmung mit Anforderungen", "correct": true, "because": "Tests prüfen Spezifikation"}, {"text": "Laufzeit des Tests", "correct": false, "because": "Sekundär"}, {"text": "Anzahl der Testfälle", "correct": false, "because": "Qualität über Quantität"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Ergebnisse können bei der Testergebnisauswertung in TDD auftreten?', 4, '[{"text": "Testfehlschlag", "correct": true, "because": "Rot-Phase"}, {"text": "Test erfolgreich", "correct": true, "because": "Grün-Phase"}, {"text": "Test nicht ausführbar", "correct": true, "because": "Fehler im Test möglich"}, {"text": "Keine Ergebnisse", "correct": false, "because": "Tests liefern immer Ergebnisse"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Testergebnisauswertung in TDD?', 3, '[{"text": "Qualität der Testfälle", "correct": true, "because": "Bestimmt Aussagekraft"}, {"text": "Anforderungsgenauigkeit", "correct": true, "because": "Tests basieren darauf"}, {"text": "Farbe des Testberichts", "correct": false, "because": "Irrelevant"}, {"text": "Implementierungsdetails", "correct": true, "because": "Beeinflussen Ergebnisse"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Testergebnisauswertung in TDD?', 3, '[{"text": "Frühe Fehlererkennung", "correct": true, "because": "Fehlschläge zeigen Probleme"}, {"text": "Richtung für Entwicklung", "correct": true, "because": "Leitet nächsten Schritt"}, {"text": "Langsamere Entwicklung", "correct": false, "because": "Eher schneller"}, {"text": "Validierung der Anforderungen", "correct": true, "because": "Tests bestätigen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Testergebnisauswertung in TDD?', 4, '[{"text": "Interpretation von Fehlschlägen", "correct": true, "because": "Ursachenanalyse nötig"}, {"text": "Zeitaufwand bei vielen Tests", "correct": true, "because": "Auswertung kann komplex sein"}, {"text": "Keine Automatisierung möglich", "correct": false, "because": "Automatisierung ist Standard"}, {"text": "Anpassung an Änderungen", "correct": true, "because": "Tests müssen aktuell bleiben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente werden bei der Testergebnisauswertung in TDD betrachtet?', 3, '[{"text": "Teststatus (Rot/Grün)", "correct": true, "because": "Zeigt Erfolg oder Fehlschlag"}, {"text": "Fehlermeldungen", "correct": true, "because": "Gibt Hinweise auf Probleme"}, {"text": "Code-Länge", "correct": false, "because": "Nicht relevant"}, {"text": "Abdeckungsgrad", "correct": true, "because": "Misst Testvollständigkeit"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Testergebnisauswertung in TDD erfolgt nur am Projektende. b) Ein fehlschlagender Test zeigt unvollständigen Code.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Auswertung kontinuierlich, Fehlschlag signalisiert"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Testergebnisse in TDD müssen immer positiv sein. b) Die Auswertung beeinflusst die Refactoring-Phase.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Tests schlagen fehl, Auswertung leitet"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Automatisierte Auswertung ist in TDD optional. b) Fehlermeldungen helfen bei der Fehlerbehebung.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Automatisierung zentral, Meldungen nützlich"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Testergebnisauswertung validiert die Anforderungen. b) TDD erfordert keine Testergebnisauswertung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Validierung durch Tests, Auswertung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein erfolgreicher Test in TDD zeigt vollständige Entwicklung. b) Die Testergebnisauswertung ist iterativ.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Erfolg nur Teil, Auswertung kontinuierlich"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

