-- questions.sql (Fähigkeiten zur Problemlösung, Eigeninitiative, Teamarbeit im IT-Kontext, z. B. praktische Anwendung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ich bei einem Netzwerkausfall immer den Chef fragen muss?', 2, '[{"text": "Nein", "correct": true, "because": "Eigeninitiative ist oft gefragt"}, {"text": "Ja", "correct": false, "because": "Selbstständigkeit zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Verhalten hilft mir, ein Softwareproblem schnell zu lösen?', 3, '[{"text": "Systematische Fehlersuche", "correct": true, "because": "Findet Ursache effizient"}, {"text": "Zufälliges Ausprobieren", "correct": false, "because": "Zeitverschwendung"}, {"text": "Ignorieren", "correct": false, "because": "Löst nichts"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Fähigkeiten sind bei einem IT-Projekt im Team wichtig?', 5, '[{"text": "Kommunikation", "correct": true, "because": "Koordiniert Aufgaben"}, {"text": "Problemlösung", "correct": true, "because": "Behebt Hindernisse"}, {"text": "Schnelles Tippen", "correct": false, "because": "Hilfreich, aber sekundär"}, {"text": "Kreatives Design", "correct": false, "because": "Nicht primär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eigenständigkeit ist bei Updates nötig. b) Teamarbeit ersetzt Fachwissen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Teamarbeit ergänzt Wissen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich eine Serverwartung plane?', 4, '[{"text": "Dokumentation", "correct": false, "because": "Hilft bei Problemlösung"}, {"text": "Zeitmanagement", "correct": false, "because": "Sichert Effizienz"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein Arbeitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ich bei jedem Problem den Support rufen soll. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Selbstständigkeit spart Zeit"}, {"text": "Ja", "correct": false, "because": "Nicht immer nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herangehensweise wähle ich, um ein neues Tool einzuführen?', 3, '[{"text": "Schulung organisieren", "correct": true, "because": "Fördert Teamkompetenz"}, {"text": "Ohne Plan starten", "correct": false, "because": "Führt zu Chaos"}, {"text": "Ausschließlich googlen", "correct": false, "because": "Unstrukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen mich im IT-Alltag effektiv?', 5, '[{"text": "Lernbereitschaft", "correct": true, "because": "Passt an neue Technik an"}, {"text": "Teamfähigkeit", "correct": true, "because": "Verbessert Zusammenarbeit"}, {"text": "Perfekte Rechtschreibung", "correct": false, "because": "Sekundär"}, {"text": "Schnelle Reaktion", "correct": false, "because": "Nur ein Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) Eigeninitiative Fehler verursacht und b) Teamarbeit immer langsamer ist. Stimmt das?', 3, '[{"text": "Beides falsch", "correct": true, "because": "Initiative löst Probleme, Teams können effizient sein"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beide falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um ein Backup-System zu optimieren?', 4, '[{"text": "Testläufe", "correct": false, "because": "Sichern Funktionalität"}, {"text": "Planung", "correct": false, "because": "Vermeidet Ausfälle"}, {"text": "Dekoration", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ich bei jedem Schritt nachfragen?', 2, '[{"text": "Nein", "correct": true, "because": "Selbstständigkeit wird erwartet"}, {"text": "Ja", "correct": false, "because": "Bremst Abläufe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen helfen bei einem Teamproblem?', 4, '[{"text": "Klare Absprachen", "correct": true, "because": "Vermeiden Missverständnisse"}, {"text": "Offene Kommunikation", "correct": true, "because": "Fördert Lösungen"}, {"text": "Schnelle Hardware", "correct": false, "because": "Kein Teamfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass selbstständiges Arbeiten immer riskant ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Mit Wissen sicher möglich"}, {"text": "Ja", "correct": false, "because": "Kompetenz reduziert Risiken"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ein Netzwerkproblem auftritt?', 3, '[{"text": "Fehlerlokalisierung", "correct": true, "because": "Erster Schritt zur Lösung"}, {"text": "Sofortiger Neustart", "correct": false, "because": "Kann Datenverlust riskieren"}, {"text": "Warten auf Hilfe", "correct": false, "because": "Verzögert Lösung"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Teamarbeit braucht Planung. b) Eigenständigkeit ist unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Eigenständigkeit ist essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herangehensweise wähle ich bei einem neuen IT-Projekt?', 4, '[{"text": "Ziele klären", "correct": true, "because": "Gibt Richtung vor"}, {"text": "Aufgaben verteilen", "correct": true, "because": "Fördert Teamarbeit"}, {"text": "Alles allein machen", "correct": false, "because": "Ineffizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ich bei jeder Aufgabe im Team helfen muss?', 2, '[{"text": "Nein", "correct": true, "because": "Eigenverantwortung zählt"}, {"text": "Ja", "correct": false, "because": "Bremst Teamdynamik"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gute Problemlösungsfähigkeit?', 5, '[{"text": "Schnelle Fehlerbehebung", "correct": true, "because": "Minimiert Ausfälle"}, {"text": "Eigenständige Lösungen", "correct": true, "because": "Reduziert Abhängigkeit"}, {"text": "Hohe Lautstärke", "correct": false, "because": "Irrelevant"}, {"text": "Bunte Dokumente", "correct": false, "because": "Kein Arbeitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Teamarbeit immer besser als allein arbeiten?', 3, '[{"text": "Nein", "correct": true, "because": "Abhängig von Aufgabe"}, {"text": "Ja", "correct": false, "because": "Solo effizient bei Spezialaufgaben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Verhalten wähle ich bei einem Konflikt im IT-Team?', 4, '[{"text": "Sachliche Diskussion", "correct": true, "because": "Fördert Lösungen"}, {"text": "Ignorieren", "correct": false, "because": "Verschärft Probleme"}, {"text": "Lautes Argumentieren", "correct": false, "because": "Stört Zusammenarbeit"}]');

