-- questions.sql (Rechtliche und wirtschaftliche Aspekte des Handelskaufs im IT-Kontext, z. B. Verträge, Lieferungen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Vertrag für IT-Hardware immer schriftlich sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "Mündlich auch möglich"}, {"text": "Ja", "correct": false, "because": "Formfreiheit gilt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend, wenn ich Server von einem Lieferanten kaufe?', 3, '[{"text": "Lieferbedingungen", "correct": true, "because": "Klären Transport und Risiko"}, {"text": "Farbe der Server", "correct": false, "because": "Irrelevant für Kauf"}, {"text": "Markenname", "correct": false, "because": "Nicht rechtlich bindend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten habe ich als Käufer bei einem IT-Liefervertrag?', 5, '[{"text": "Abnahme der Ware", "correct": true, "because": "Vertraglich vereinbart"}, {"text": "Zahlung des Kaufpreises", "correct": true, "because": "Grundpflicht im Handel"}, {"text": "Eigenes Marketing", "correct": false, "because": "Keine Käuferpflicht"}, {"text": "Lieferantenschulung", "correct": false, "because": "Nicht erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Gefahrübergang erfolgt bei Lieferung. b) Mängel müssen sofort gemeldet werden.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Gefahrübergang abhängig von Vereinbarung"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist kontextabhängig"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich Software von einem Anbieter kaufe?', 4, '[{"text": "Lizenzbedingungen", "correct": false, "because": "Bestimmen Nutzung"}, {"text": "Zahlungsfristen", "correct": false, "because": "Regeln Finanzfluss"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein Kaufaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Lieferant immer die Transportkosten trägt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Vereinbarung"}, {"text": "Ja", "correct": false, "because": "Kann Käuferpflicht sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Rügepflicht bei einem IT-Kauf?', 3, '[{"text": "Mängel schnell melden", "correct": true, "because": "Schützt Käuferrechte"}, {"text": "Preisnachlass sichern", "correct": false, "because": "Nicht primär"}, {"text": "Lieferung beschleunigen", "correct": false, "because": "Kein Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind bei einem Vertrag für IT-Dienstleistungen wichtig?', 5, '[{"text": "Leistungsbeschreibung", "correct": true, "because": "Klärt Umfang"}, {"text": "Zahlungsbedingungen", "correct": true, "because": "Regeln Finanzen"}, {"text": "Büroausstattung", "correct": false, "because": "Nicht vertragsrelevant"}, {"text": "Lieferantengröße", "correct": false, "because": "Kein rechtlicher Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) ein Kaufvertrag formfrei ist und b) Lieferzeiten immer verbindlich sind. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Lieferzeiten abhängig von Vereinbarung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen rechtssicheren IT-Kauf?', 4, '[{"text": "Kaufgegenstand", "correct": false, "because": "Definiert Ware"}, {"text": "Preisangabe", "correct": false, "because": "Regelt Zahlung"}, {"text": "Lieferantenhobby", "correct": true, "because": "Kein Vertragsbestandteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ich bei einem Kauf immer die Ware prüfen?', 2, '[{"text": "Ja", "correct": true, "because": "Sichert Mängelrüge"}, {"text": "Nein", "correct": false, "because": "Pflicht im Handel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rechte habe ich, wenn die gelieferte Hardware defekt ist?', 4, '[{"text": "Nacherfüllung", "correct": true, "because": "Reparatur oder Ersatz"}, {"text": "Rücktritt", "correct": true, "because": "Vertrag auflösbar"}, {"text": "Preisaufschlag", "correct": false, "because": "Kein Käuferrecht"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass der Käufer immer das Transportrisiko trägt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Incoterms"}, {"text": "Ja", "correct": false, "because": "Kann Lieferant übernehmen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit klaren Lieferbedingungen?', 3, '[{"text": "Risikoverteilung klären", "correct": true, "because": "Schützt beide Seiten"}, {"text": "Preis senken", "correct": false, "because": "Nicht primär"}, {"text": "Schnellere Lieferung", "correct": false, "because": "Kein direkter Zweck"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Gewährleistung ist Pflicht. b) Garantie ist gesetzlich vorgeschrieben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Garantie ist freiwillig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme wähle ich, wenn Software nicht wie vereinbart funktioniert?', 4, '[{"text": "Mängelrüge einlegen", "correct": true, "because": "Fordert Nacherfüllung"}, {"text": "Sofort zahlen", "correct": false, "because": "Ignoriert Mängel"}, {"text": "Lieferant wechseln", "correct": false, "because": "Keine Vertragslösung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Kaufvertrag ohne Preisangabe gültig ist?', 2, '[{"text": "Nein", "correct": true, "because": "Preis ist wesentlich"}, {"text": "Ja", "correct": false, "because": "Kaufvertrag braucht Preis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine schriftliche Bestellung?', 5, '[{"text": "Nachweisbarkeit", "correct": true, "because": "Klärt Streitfälle"}, {"text": "Rechtssicherheit", "correct": true, "because": "Bindet beide Seiten"}, {"text": "Schnellere Lieferung", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Höhere Kosten", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss der Lieferant immer die Versandkosten übernehmen?', 3, '[{"text": "Nein", "correct": true, "because": "Abhängig von Vereinbarung"}, {"text": "Ja", "correct": false, "because": "Kann Käuferpflicht sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Risiko trage ich, wenn ich keine Lieferfrist vereinbare?', 4, '[{"text": "Verzögerte Lieferung", "correct": true, "because": "Keine verbindliche Zeit"}, {"text": "Höhere Kosten", "correct": false, "because": "Nicht direkt"}, {"text": "Qualitätsverlust", "correct": false, "because": "Kein Zusammenhang"}]');

