-- # Lernfeld 5: Cyberphysische Systeme > ## Softwareplanung > - Modellierungssprachen

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann eine Modellierungssprache wie UML ohne technische Kenntnisse vollständig verstanden werden?', 2, '[{"text": "Nein", "correct": true, "because": "Technisches Verständnis ist für Details nötig"}, {"text": "Ja", "correct": false, "because": "Grundlagen sind komplex"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist UML die einzige Modellierungssprache, die in der Softwareplanung verwendet wird?', 2, '[{"text": "Nein", "correct": true, "because": "Andere wie BPMN oder SysML existieren"}, {"text": "Ja", "correct": false, "because": "Vielfalt an Sprachen verfügbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Modellierungssprachen die Kommunikation zwischen Entwicklern und Stakeholdern verbessern?', 2, '[{"text": "Ja", "correct": true, "because": "Visuelle Darstellung klärt Anforderungen"}, {"text": "Nein", "correct": false, "because": "Kommunikation wird erleichtert"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine Modellierungssprache zwingend erforderlich, um ein Softwaresystem zu entwerfen?', 2, '[{"text": "Nein", "correct": true, "because": "Entwurf kann auch textuell erfolgen"}, {"text": "Ja", "correct": false, "because": "Alternative Methoden möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine Modellierungssprache wie SysML auch Hardwarekomponenten beschreiben?', 2, '[{"text": "Ja", "correct": true, "because": "SysML ist für Systeme inklusive Hardware"}, {"text": "Nein", "correct": false, "because": "SysML ist dafür ausgelegt"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Modellierungssprache wird am häufigsten für die Softwareentwicklung verwendet?', 2, '[{"text": "UML", "correct": true, "because": "Standard in der Softwareplanung"}, {"text": "BPMN", "correct": false, "because": "Fokus auf Prozesse"}, {"text": "ERD", "correct": false, "because": "Datenbankmodellierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Diagramm in UML beschreibt den Ablauf von Aktivitäten?', 3, '[{"text": "Aktivitätsdiagramm", "correct": true, "because": "Zeigt Prozesse und Workflows"}, {"text": "Klassendiagramm", "correct": false, "because": "Statische Struktur"}, {"text": "Use-Case-Diagramm", "correct": false, "because": "Anwendungsfälle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Modellierungssprache eignet sich besonders für Geschäftsprozesse?', 2, '[{"text": "BPMN", "correct": true, "because": "Business Process Model and Notation"}, {"text": "UML", "correct": false, "because": "Allgemeiner Fokus"}, {"text": "SysML", "correct": false, "because": "Systemorientiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches UML-Diagramm zeigt die Interaktion zwischen Objekten über die Zeit?', 2, '[{"text": "Sequenzdiagramm", "correct": true, "because": "Zeigt Nachrichtenfolge"}, {"text": "Zustandsdiagramm", "correct": false, "because": "Zustandsänderungen"}, {"text": "Komponentendiagramm", "correct": false, "because": "Systemstruktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Sprache wird für die Modellierung komplexer cyberphysischer Systeme bevorzugt?', 2, '[{"text": "SysML", "correct": true, "because": "Erweitert UML für Systeme"}, {"text": "BPMN", "correct": false, "because": "Prozessorientiert"}, {"text": "DFD", "correct": false, "because": "Datenfluss, nicht System"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Diagramme gehören zu UML?', 4, '[{"text": "Klassendiagramm", "correct": true, "because": "Statische Struktur"}, {"text": "Sequenzdiagramm", "correct": true, "because": "Dynamisches Verhalten"}, {"text": "Entity-Relationship-Diagramm", "correct": false, "because": "Datenbankmodellierung"}, {"text": "Use-Case-Diagramm", "correct": true, "because": "Anwendungsfälle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Modellierungssprachen in der Softwareplanung?', 3, '[{"text": "Klarheit durch Visualisierung", "correct": true, "because": "Struktur wird sichtbar"}, {"text": "Verbesserte Kommunikation", "correct": true, "because": "Einheitliche Sprache"}, {"text": "Automatische Codegenerierung", "correct": true, "because": "Bei einigen Tools möglich"}, {"text": "Geringerer Planungsaufwand", "correct": false, "because": "Aufwand bleibt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Modellierungssprachen eignen sich für Systementwicklung?', 3, '[{"text": "UML", "correct": true, "because": "Breite Softwaremodellierung"}, {"text": "SysML", "correct": true, "because": "Cyberphysische Systeme"}, {"text": "HTML", "correct": false, "because": "Programmiersprache"}, {"text": "BPMN", "correct": true, "because": "Prozesse im System"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte können mit UML modelliert werden?', 4, '[{"text": "Statische Struktur", "correct": true, "because": "Klassendiagramme"}, {"text": "Dynamisches Verhalten", "correct": true, "because": "Sequenzdiagramme"}, {"text": "Geschäftsprozesse", "correct": true, "because": "Aktivitätsdiagramme"}, {"text": "Hardwarekonfiguration", "correct": false, "because": "SysML-Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Nutzung von Modellierungssprachen?', 3, '[{"text": "Hohe Lernkurve", "correct": true, "because": "Komplexität erfordert Training"}, {"text": "Abhängigkeit von Tools", "correct": true, "because": "Software oft nötig"}, {"text": "Einfache Anpassbarkeit", "correct": false, "because": "Anpassung kann schwierig sein"}, {"text": "Zeitaufwand", "correct": true, "because": "Detaillierung kostet Zeit"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) UML ist für die Modellierung von Geschäftsprozessen ungeeignet. b) SysML erweitert UML um Systemaspekte.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "UML kann Prozesse, SysML erweitert"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) BPMN fokussiert auf technische Softwareentwicklung. b) UML-Diagramme können dynamische Abläufe darstellen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "BPMN für Prozesse, UML dynamisch"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Modellierungssprachen sind immer toolabhängig. b) Ein Sequenzdiagramm zeigt zeitliche Abläufe.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Tools optional, Sequenz zeitlich"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) UML ist für Hardwaremodellierung optimiert. b) Modellierungssprachen verbessern die Planungsqualität.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "UML softwarezentriert, Planung profitiert"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) SysML kann Software und Hardware modellieren. b) BPMN ist für dynamische Softwareabläufe ungeeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SysML umfassend, BPMN für Prozesse"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

