-- Paketdiagramm.sql (Hilfreich für Modulstruktur, jedoch nicht relevant, z. B. Paketorganisation)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Paketdiagramm nur für große Softwareprojekte nützlich?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte profitieren von Struktur"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Paketdiagramm?', 3, '[{"text": "Modulstruktur zeigen", "correct": true, "because": "Organisiert Pakete"}, {"text": "Hardwarezuordnung", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Datenfluss", "correct": false, "because": "Datenflussdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem Paketdiagramm?', 5, '[{"text": "Pakete", "correct": true, "because": "Gruppieren Klassen"}, {"text": "Abhängigkeiten", "correct": true, "because": "Zeigen Beziehungen"}, {"text": "Farbanimation", "correct": false, "because": "Irrelevant"}, {"text": "Datenströme", "correct": false, "because": "Anderes Diagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Paketdiagramme sind Teil von UML. b) Sie zeigen Hardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware ist Verteilungsdiagramm"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Paketdiagramm?', 4, '[{"text": "Paketabhängigkeiten", "correct": false, "because": "Kern der Struktur"}, {"text": "Modulorganisation", "correct": false, "because": "Hauptzweck"}, {"text": "Hardwareknoten", "correct": true, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Paketdiagramm auch Klassen zeigt?', 2, '[{"text": "Ja", "correct": true, "because": "Klassen in Paketen möglich"}, {"text": "Nein", "correct": false, "because": "Nicht nur Paketebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich für ein Paketdiagramm?', 3, '[{"text": "Paket", "correct": true, "because": "Grundbaustein"}, {"text": "Knoten", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Datenfluss", "correct": false, "because": "Datenflussdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Informationen zeigt ein Paketdiagramm?', 5, '[{"text": "Modulstruktur", "correct": true, "because": "Organisiert Pakete"}, {"text": "Abhängigkeiten", "correct": true, "because": "Zeigt Beziehungen"}, {"text": "Hardwarestandorte", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Ablaufsequenzen", "correct": false, "because": "Sequenzdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Paketdiagramme helfen bei der Wartung. b) Sie zeigen Datenflüsse. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Datenflüsse nicht im Fokus"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Paketdiagramm?', 4, '[{"text": "Paketnamen", "correct": false, "because": "Identifizieren Pakete"}, {"text": "Abhängigkeitspfeile", "correct": false, "because": "Zeigen Beziehungen"}, {"text": "Netzwerkprotokolle", "correct": true, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Paketdiagramm nur für Entwickler?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Architekten nützlich"}, {"text": "Ja", "correct": false, "because": "Breitere Zielgruppe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beziehungen zeigt ein Paketdiagramm?', 4, '[{"text": "Abhängigkeiten", "correct": true, "because": "Zwischen Paketen"}, {"text": "Aggregation", "correct": true, "because": "Kann Paketstruktur zeigen"}, {"text": "Datenfluss", "correct": false, "because": "Datenflussdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Paketdiagramme überflüssig sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Hilfreich für Übersicht"}, {"text": "Ja", "correct": false, "because": "Struktur unterstützt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Paketdiagramm?', 3, '[{"text": "Klarheit der Struktur", "correct": true, "because": "Fördert Verständnis"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Qualität zählt"}, {"text": "Technische Details", "correct": false, "because": "Nicht im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Paketdiagramme zeigen Modulabhängigkeiten. b) Sie sind für Hardware wichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware ist Verteilungsdiagramm"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Paketdiagramm?', 5, '[{"text": "Modulübersicht", "correct": true, "because": "Klarheit über Struktur"}, {"text": "Wartungshilfe", "correct": true, "because": "Abhängigkeiten sichtbar"}, {"text": "Datenflussanalyse", "correct": false, "because": "Anderes Diagramm"}, {"text": "Hardwareplanung", "correct": false, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Paketdiagramm unwichtig?', 3, '[{"text": "Paketstruktur", "correct": false, "because": "Kern der Darstellung"}, {"text": "Abhängigkeiten", "correct": false, "because": "Zeigen Beziehungen"}, {"text": "Netzwerktopologie", "correct": true, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Zeigt ein Paketdiagramm auch Abläufe?', 3, '[{"text": "Nein", "correct": true, "because": "Statisch, nicht dynamisch"}, {"text": "Ja", "correct": false, "because": "Abläufe sind Sequenzdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Paketdiagramme für kleine Projekte nützlich sind?', 2, '[{"text": "Ja", "correct": true, "because": "Auch kleine Strukturen klären"}, {"text": "Nein", "correct": false, "because": "Skalierung unabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Symbol wähle ich für ein Paket im Paketdiagramm?', 4, '[{"text": "Rechteck mit Reiter", "correct": true, "because": "UML-Standard"}, {"text": "Pfeil", "correct": false, "because": "Nur Abhängigkeit"}, {"text": "Kreis", "correct": false, "because": "Andere Diagramme"}]');

