-- questions.sql

-- Testplan.sql (Testfälle, Durchführung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Testplan nur für große Projekte nötig?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte profitieren"}, {"text": "Ja", "correct": false, "because": "Universell nützlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Testplan?', 3, '[{"text": "Tests strukturiert durchführen", "correct": true, "because": "Sichert Systematik"}, {"text": "Code schneller schreiben", "correct": false, "because": "Kein direkter Zweck"}, {"text": "UI gestalten", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem Testplan?', 5, '[{"text": "Testfälle", "correct": true, "because": "Definieren Prüfungen"}, {"text": "Durchführungsplan", "correct": true, "because": "Legt Ablauf fest"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}, {"text": "Netzwerkprotokolle", "correct": false, "because": "Technischer Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Testfälle beschreiben Szenarien. b) Ein Testplan ist immer optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Plan oft essenziell"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Testplan?', 4, '[{"text": "Testziele", "correct": false, "because": "Definieren Zweck"}, {"text": "Durchführungsdetails", "correct": false, "because": "Strukturieren Tests"}, {"text": "Bildauflösung", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Testplan nur einmal erstellt wird?', 2, '[{"text": "Nein", "correct": true, "because": "Kann angepasst werden"}, {"text": "Ja", "correct": false, "because": "Iterativ nutzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich, um Tests zu spezifizieren?', 3, '[{"text": "Testfälle", "correct": true, "because": "Beschreiben Szenarien"}, {"text": "Farbanpassung", "correct": false, "because": "Nicht relevant"}, {"text": "Datenbankstruktur", "correct": false, "because": "Technischer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Testplan?', 5, '[{"text": "Systematik", "correct": true, "because": "Strukturiert Tests"}, {"text": "Nachvollziehbarkeit", "correct": true, "because": "Dokumentiert Ablauf"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Kein direkter Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Testplan spart Zeit. b) Er ist nur für Tester. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Auch Entwickler nutzen"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen Testplan?', 4, '[{"text": "Testziele", "correct": false, "because": "Legen Fokus fest"}, {"text": "Durchführungszeit", "correct": false, "because": "Plant Ablauf"}, {"text": "Grafikdesign", "correct": true, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Testplan immer detailliert?', 2, '[{"text": "Nein", "correct": true, "because": "Kann überblickend sein"}, {"text": "Ja", "correct": false, "because": "Flexibel gestaltbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte gehören zur Testplan-Durchführung?', 4, '[{"text": "Testfälle ausführen", "correct": true, "because": "Prüft Szenarien"}, {"text": "Ergebnisse dokumentieren", "correct": true, "because": "Sichert Nachweis"}, {"text": "Code neu schreiben", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Testplan nur für Software ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Hardware nutzbar"}, {"text": "Ja", "correct": false, "because": "Breiter einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich in einem Testplan?', 3, '[{"text": "Klare Testfälle", "correct": true, "because": "Sichert Prüfung"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Qualität zählt"}, {"text": "Serverkonfiguration", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Testplan definiert Abnahmekriterien. b) Er ist immer automatisiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Manuell möglich"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken gibt es ohne Testplan?', 5, '[{"text": "Unstrukturierte Tests", "correct": true, "because": "Fehlende Systematik"}, {"text": "Unklare Ergebnisse", "correct": true, "because": "Keine Dokumentation"}, {"text": "Schnellere Tests", "correct": false, "because": "Kein Risiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist im Testplan unwichtig?', 3, '[{"text": "Testabdeckung", "correct": false, "because": "Sichert Vollständigkeit"}, {"text": "Durchführungsreihenfolge", "correct": false, "because": "Strukturiert Ablauf"}, {"text": "Bildauflösung", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Testplan angepasst werden?', 3, '[{"text": "Ja", "correct": true, "because": "Flexibel bei Änderungen"}, {"text": "Nein", "correct": false, "because": "Anpassung üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Testplan nur für Tester ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Entwickler relevant"}, {"text": "Ja", "correct": false, "because": "Teamübergreifend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool wähle ich für Testplan-Erstellung?', 4, '[{"text": "Testmanagement-Software", "correct": true, "because": "Strukturiert Planung"}, {"text": "Grafikeditor", "correct": false, "because": "Kein Testzweck"}, {"text": "Debugger", "correct": false, "because": "Für Code-Analyse"}]');

