-- SaaS.sql (Cloud-basierte Softwarebereitstellung mit Abonnement-Modell)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass eine Cloud-Software immer lokal installiert wird?', 2, '[{"text": "Nein", "correct": true, "because": "Sie läuft auf Anbieterservern"}, {"text": "Ja", "correct": false, "because": "Kein lokaler Download nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Modell wird typischerweise für die Abrechnung verwendet?', 3, '[{"text": "Abonnement", "correct": true, "because": "Monatliche oder jährliche Zahlungen"}, {"text": "Einmalkauf", "correct": false, "because": "Selten bei Cloud-Software"}, {"text": "Kostenlos", "correct": false, "because": "Nur bei Freemium"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Cloud-basierte Lösung?', 5, '[{"text": "Skalierbarkeit", "correct": true, "because": "Ressourcen anpassbar"}, {"text": "Automatische Updates", "correct": true, "because": "Anbieter übernimmt Wartung"}, {"text": "Hoher Speicherbedarf lokal", "correct": false, "because": "Läuft in der Cloud"}, {"text": "Einmalige Lizenz", "correct": false, "because": "Nicht typisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Software läuft auf Anbieterservern. b) Nutzer besitzen die Software.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Nutzer mieten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Auswahl einer Cloud-Lösung?', 4, '[{"text": "Sicherheitsstandards", "correct": false, "because": "Schützen Daten"}, {"text": "Skalierbarkeit", "correct": false, "because": "Wichtig für Wachstum"}, {"text": "Anbieterlogo", "correct": true, "because": "Kein funktionaler Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Internetverbindung immer nötig ist?', 2, '[{"text": "Ja", "correct": true, "because": "Zugriff erfolgt online"}, {"text": "Nein", "correct": false, "because": "Nur bei Offline-Modi nicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll sichert die Datenübertragung?', 4, '[{"text": "HTTPS", "correct": true, "because": "Verschlüsselt Kommunikation"}, {"text": "FTP", "correct": false, "because": "Für Dateitransfer"}, {"text": "SMTP", "correct": false, "because": "Für E-Mails"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Cloud-Lösungen immer teurer als lokale Software sind. Stimmt das?', 3, '[{"

