-- SAN.sql (Netzwerk zur Bereitstellung zentraler Speicherressourcen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass ein Speichernetzwerk immer auf Fibre Channel basiert?', 2, '[{"text": "Nein", "correct": true, "because": "Auch iSCSI oder FCoE möglich"}, {"text": "Ja", "correct": false, "because": "Nicht ausschließlich Fibre Channel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wird häufig für schnelle Speicherzugriffe verwendet?', 3, '[{"text": "Fibre Channel", "correct": true, "because": "Hohe Geschwindigkeit für SAN"}, {"text": "FTP", "correct": false, "because": "Für Dateitransfer"}, {"text": "HTTP", "correct": false, "because": "Für Web"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind für ein Speichernetzwerk essenziell?', 5, '[{"text": "Speichergeräte", "correct": true, "because": "Speichern die Daten"}, {"text": "Switches", "correct": true, "because": "Verbinden Geräte"}, {"text": "Router", "correct": false, "because": "Für Netzwerk, nicht SAN"}, {"text": "Monitore", "correct": false, "because": "Nur für Anzeige"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Speichernetzwerk ermöglicht zentralen Zugriff. b) Es ist immer lokal begrenzt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, SAN kann verteilt sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung eines Speichernetwerks?', 4, '[{"text": "Bandbreite", "correct": false, "because": "Entscheidend für Leistung"}, {"text": "Redundanz", "correct": false, "because": "Sichert Verfügbarkeit"}, {"text": "Gerätedesign", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Speichernetzwerk ohne Switches funktioniert?', 2, '[{"text": "Nein", "correct": true, "because": "Switches verbinden Geräte"}, {"text": "Ja", "correct": false, "because": "Ohne Switches eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie ermöglicht blockbasierten Zugriff?', 4, '[{"text": "iSCSI", "correct": true, "because": "Nutzt IP-Netzwerke für SAN"}, {"text": "NFS", "correct": false, "because": "Dateibasiert"}, {"text": "SMB", "correct": false, "because": "Für Filesharing"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Speichernetzwerk langsamer als lokale Festplatten ist. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Hochleistungs-SAN oft schneller"}, {"text": "Ja", "correct": false, "because": "Abhängig von Konfiguration"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Speichernetzwerk dasselbe wie NAS?', 2, '[{"text": "Nein", "correct": true, "because": "SAN blockbasiert, NAS dateibasiert"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Technologien"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren verbessern die Leistung eines Speichernetwerks?', 5, '[{"text": "Hohe Bandbreite", "correct": true, "because": "Schnellere Datenübertragung"}, {"text": "Redundante Pfade", "correct": true, "because": "Sichern Zuverlässigkeit"}, {"text": "Gerätefarbe", "correct": false, "because": "Irrelevant"}, {"text": "Bildschirmauflösung", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Einrichtung eines Speichernetwerks?', 4, '[{"text": "Skalierbarkeit", "correct": true, "because": "Ermöglicht Wachstum"}, {"text": "Minimale Kosten", "correct": false, "because": "Leistung wichtiger"}, {"text": "Optisches Design", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Zoning verbessert die Sicherheit. b) Es verdoppelt die Bandbreite.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Zoning trennt Zugriffe"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Speichernetzwerk?', 3, '[{"text": "Speichergeräte", "correct": false, "because": "Kern des Systems"}, {"text": "Netzwerkadapter", "correct": false, "because": "Ermöglicht Verbindung"}, {"text": "Grafikkarte", "correct": true, "because": "Kein Speicherfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich die Sicherheit eines Speichernetwerks erhöhe?', 4, '[{"text": "Zoning und LUN-Masking einrichten", "correct": true, "because": "Begrenzt Zugriffe"}, {"text": "Alle Ports öffnen", "correct": false, "because": "Unsicher"}, {"text": "Standardpasswörter nutzen", "correct": false, "because": "Erhöht Risiken"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Speichernetzwerk immer teuer ist. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Kosteneffizient mit iSCSI"}, {"text": "Ja", "correct": false, "because": "Kosten variieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip hilft, Datenverluste zu vermeiden?', 4, '[{"text": "Redundanz", "correct": true, "because": "Sichert Verfügbarkeit"}, {"text": "Minimale Verbindung", "correct": false, "because": "Erhöht Risiken"}, {"text": "Hohe Latenz", "correct": false, "because": "Schadet Leistung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Speichernetzwerk ohne Switches funktionieren?', 2, '[{"text": "Ja", "correct": true, "because": "Direkte Verbindungen möglich"}, {"text": "Nein", "correct": false, "because": "Switches nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Speichernetzwerk?', 5, '[{"text": "Zentralisierte Verwaltung", "correct": true, "because": "Vereinfacht Zugriff"}, {"text": "Hohe Leistung", "correct": true, "because": "Schnelle Datenübertragung"}, {"text": "Kleinere Größe", "correct": false, "because": "Nicht primär"}, {"text": "Bessere Optik", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Verwaltung eines Speichernetwerks unwichtig?', 3, '[{"text": "Backup-Strategie", "correct": false, "because": "Schützt Daten"}, {"text": "Zugriffskontrollen", "correct": false, "because": "Sichern Sicherheit"}, {"text": "Gerätedekoration", "correct": true, "because": "Kein technischer Nutzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich ein Speichernetzwerk für ein Rechenzentrum einrichte?', 4, '[{"text": "Fibre Channel und Redundanz planen", "correct": true, "because": "Sichert Leistung und Sicherheit"}, {"text": "Nur lokale Festplatten", "correct": false, "because": "Eingeschränkt"}, {"text": "Ohne Switches", "correct": false, "because": "Begrenzt Skalierbarkeit"}]');

