-- Schadenskategorien.sql (Klassifizierung von Schäden in IT-Sicherheit und Risikomanagement)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Datenleck immer ein finanzieller Schaden?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Reputationsschaden möglich"}, {"text": "Ja", "correct": false, "because": "Nicht nur finanziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schadensart entsteht durch Ransomware?', 3, '[{"text": "Datenverlust", "correct": true, "because": "Dateien werden verschlüsselt"}, {"text": "Hardwaredefekt", "correct": false, "because": "Physikalischer Schaden"}, {"text": "Softwarefehler", "correct": false, "because": "Kein Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schäden können durch einen Cyberangriff entstehen?', 5, '[{"text": "Finanzielle Verluste", "correct": true, "because": "Durch Erpressung"}, {"text": "Reputationsschaden", "correct": true, "because": "Verlust von Vertrauen"}, {"text": "Höhere Bandbreite", "correct": false, "because": "Kein Schaden"}, {"text": "Bessere Software", "correct": false, "because": "Kein Schadensfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Datenverlust ist eine Schadensart. b) Mehr Sicherheit ist ein Schaden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Sicherheit ist positiv"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist kein typischer Schaden bei einem IT-Vorfall?', 4, '[{"text": "Verbesserte Software", "correct": true, "because": "Kein Schaden"}, {"text": "Datenverlust", "correct": false, "because": "Typischer Schaden"}, {"text": "Reputationsverlust", "correct": false, "because": "Häufiger Schaden"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein physischer Schaden ein IT-Schaden ist?', 2, '[{"text": "Ja", "correct": true, "because": "Hardware kann betroffen sein"}, {"text": "Nein", "correct": false, "because": "Physische Schäden zählen dazu"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Schaden entsteht durch einen Datenbankausfall?', 4, '[{"text": "Verfügbarkeitsverlust", "correct": true, "because": "Daten nicht zugänglich"}, {"text": "Bessere Performance", "correct": false, "because": "Kein Schaden"}, {"text": "Höhere Bandbreite", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Reputationsschaden nur kurzfristig ist. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Kann langfristige Folgen haben"}, {"text": "Ja", "correct": false, "because": "Vertrauensverlust dauert an"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein finanzieller Schaden immer direkt messbar?', 2, '[{"text": "Nein", "correct": true, "because": "Indirekte Kosten möglich"}, {"text": "Ja", "correct": false, "because": "Nicht immer sofort klar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schadensarten sind typisch für Phishing?', 5, '[{"text": "Datenklau", "correct": true, "because": "Sensible Daten gestohlen"}, {"text": "Finanzverlust", "correct": true, "because": "Durch Betrug"}, {"text": "Schnellere Systeme", "correct": false, "because": "Kein Schaden"}, {"text": "Bessere Software", "correct": false, "because": "Kein Schadensfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Analyse von Schäden?', 4, '[{"text": "Auswirkung bewerten", "correct": true, "because": "Bestimmt Schwere"}, {"text": "Farbschema wählen", "correct": false, "because": "Irrelevant"}, {"text": "Schnelle Lösung", "correct": false, "because": "Genauigkeit wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Verfügbarkeitsverlust ist ein Schaden. b) Höhere Sicherheit ist ein Schaden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Sicherheit ist positiv"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Schadensbewertung?', 3, '[{"text": "Schweregrad", "correct": false, "because": "Bestimmt Auswirkung"}, {"text": "Ursache", "correct": false, "because": "Hilft bei Prävention"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein Schadensfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich einen Schaden durch Malware erkenne?', 4, '[{"text": "Datenverlust oder Leistungsabfall prüfen", "correct": true, "because": "Typische Symptome"}, {"text": "Nur Farben checken", "correct": false, "because": "Irrelevant"}, {"text": "System ausschalten", "correct": false, "because": "Keine Erkennung"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Schaden immer vermeidbar ist. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Nicht alle Risiken eliminierbar"}, {"text": "Ja", "correct": false, "because": "Schäden oft unvermeidbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Schaden entsteht durch einen DDoS-Angriff?', 4, '[{"text": "Verfügbarkeitsverlust", "correct": true, "because": "Systeme überlastet"}, {"text": "Hardwaredefekt", "correct": false, "because": "Nicht typisch"}, {"text": "Bessere Performance", "correct": false, "because": "Kein Schaden"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Reputationsschaden finanziell messbar?', 2, '[{"text": "Ja", "correct": true, "because": "Durch Umsatzeinbußen"}, {"text": "Nein", "correct": false, "because": "Indirekt messbar"}]'),
('00000000-0000-0000-0000-0000-000000000000', 'Welche Kategorien sind bei einem Datenleck relevant?', 5, '[{"text": "Vertraulichkeitsverlust", "correct": true, "because": "Daten kompromittiert"}, {"text": "Rechtliche Konsequenzen", "correct": true, "because": "Bußgelder möglich"}, {"text": "Schnellere Systeme", "correct": false, "because": "Kein Schaden"}, {"text": "Bessere Software", "correct": false, "because": "Kein Schadensfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist kein Schaden durch einen IT-Vorfall?', 3, '[{"text": "Verbesserte Sicherheit", "correct": true, "because": "Positiver Effekt"}, {"text": "Datenverlust", "correct": false, "because": "Typischer Schaden"}, {"text": "Finanzverlust", "correct": false, "because": "Häufiger Schaden"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich Schäden bewerten will?', 4, '[{"text": "Finanzielle, operative, rechtliche Auswirkungen prüfen", "correct": true, "because": "Umfassende Analyse"}, {"text": "Nur Farben wählen", "correct": false, "because": "Irrelevant"}, {"text": "Problem ignorieren", "correct": false, "because": "Keine Lösung"}]');

