-- Schnittstellen.sql (Verbindungen zwischen Systemen, z. B. APIs, USB, Netzwerkprotokolle)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass jede Verbindung zwischen Systemen immer physische Kabel benötigt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch drahtlose Verbindungen wie APIs oder Wi-Fi"}, {"text": "Ja", "correct": false, "because": "Nicht auf Kabel beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wird häufig für Web-Verbindungen genutzt?', 3, '[{"text": "REST", "correct": true, "because": "Standard für API-Kommunikation"}, {"text": "FTP", "correct": false, "because": "Für Dateitransfer"}, {"text": "SMTP", "correct": false, "because": "Für E-Mails"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale machen eine Systemverbindung zuverlässig?', 5, '[{"text": "Standardisierung", "correct": true, "because": "Sichert Kompatibilität"}, {"text": "Fehlerkorrektur", "correct": true, "because": "Minimiert Datenverlust"}, {"text": "Farbcodierung", "correct": false, "because": "Nur visuelle Hilfe"}, {"text": "Gewicht des Geräts", "correct": false, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) USB ist eine universelle Hardware-Verbindung. b) Es ersetzt immer Wi-Fi.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Wi-Fi ist alternativ"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Entwicklung einer API?', 4, '[{"text": "Dokumentation", "correct": false, "because": "Sichert Nutzbarkeit"}, {"text": "Sicherheitsprotokolle", "correct": false, "because": "Schützen Daten"}, {"text": "Farbschema", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Verbindung immer bidirektional ist?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch unidirektional sein"}, {"text": "Ja", "correct": false, "because": "Nicht immer zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie ermöglicht Datenaustausch zwischen Webanwendungen?', 4, '[{"text": "REST API", "correct": true, "because": "Nutzt HTTP für Kommunikation"}, {"text": "VGA", "correct": false, "because": "Für Bildschirme"}, {"text": "SCSI", "correct": false, "because": "Für Speicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass alle Verbindungen standardisiert sein müssen. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Auch proprietäre Lösungen existieren"}, {"text": "Ja", "correct": false, "because": "Nicht immer erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist USB-C schneller als USB-A?', 2, '[{"text": "Ja", "correct": true, "because": "Unterstützt höhere Datenraten"}, {"text": "Nein", "correct": false, "because": "USB-C oft schneller"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Protokolle sind für Netzwerkverbindungen typisch?', 5, '[{"text": "HTTP", "correct": true, "because": "Für Webkommunikation"}, {"text": "TCP/IP", "correct": true, "because": "Basis für Internet"}, {"text": "VNC", "correct": false, "because": "Für Fernsteuerung"}, {"text": "MIDI", "correct": false, "because": "Für Audio"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Auswahl einer Hardware-Verbindung?', 4, '[{"text": "Kompatibilität", "correct": true, "because": "Sichert Funktion"}, {"text": "Kabellänge", "correct": false, "because": "Sekundär"}, {"text": "Verpackungsdesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) APIs ermöglichen Softwareintegration. b) Sie sind immer öffentlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, APIs können privat sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine effiziente API?', 3, '[{"text": "Dokumentation", "correct": false, "because": "Fördert Nutzung"}, {"text": "Authentifizierung", "correct": false, "because": "Sichert Zugriff"}, {"text": "UI-Design", "correct": true, "because": "Nur für Oberflächen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich eine API sichere?', 4, '[{"text": "Mit OAuth oder API-Keys", "correct": true, "because": "Kontrolliert Zugriff"}, {"text": "Ohne Authentifizierung", "correct": false, "because": "Unsicher"}, {"text": "Nur durch Passwörter", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Verbindungen immer synchron sind. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Auch asynchron möglich"}, {"text": "Ja", "correct": false, "because": "Nicht immer synchron"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll sichert Datenübertragung bei APIs?', 4, '[{"text": "HTTPS", "correct": true, "because": "Verschlüsselt Kommunikation"}, {"text": "FTP", "correct": false, "because": "Für Dateien"}, {"text": "SNMP", "correct": false, "because": "Für Netzwerkmanagement"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Thunderbolt mit USB-C kompatibel?', 2, '[{"text": "Ja", "correct": true, "because": "Nutzt gleichen Stecker"}, {"text": "Nein", "correct": false, "because": "Kompatibel mit USB-C"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine standardisierte Verbindung?', 5, '[{"text": "Interoperabilität", "correct": true, "because": "Ermöglicht Zusammenarbeit"}, {"text": "Breite Kompatibilität", "correct": true, "because": "Funktioniert mit vielen Geräten"}, {"text": "Einzigartiges Design", "correct": false, "because": "Kein Standardvorteil"}, {"text": "Hohe Kosten", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Wahl einer Verbindung unwichtig?', 3, '[{"text": "Datenrate", "correct": false, "because": "Bestimmt Leistung"}, {"text": "Sicherheit", "correct": false, "because": "Schützt Daten"}, {"text": "Steckerfarbe", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich eine API integriere?', 4, '[{"text": "Dokumentation prüfen, Authentifizierung einrichten", "correct": true, "because": "Sichert korrekte Nutzung"}, {"text": "Nur Endpunkt aufrufen", "correct": false, "because": "Fehlt Sicherheit"}, {"text": "Ohne Tests starten", "correct": false, "because": "Riskiert Fehler"}]');

