-- Schutzmaßnahmen_Clients.sql (IT-Sicherheitsmaßnahmen für Endgeräte wie PCs und Laptops)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass ein Virenscanner allein einen Client vollständig schützt?', 2, '[{"text": "Nein", "correct": true, "because": "Mehrschichtige Maßnahmen nötig"}, {"text": "Ja", "correct": false, "because": "Nicht gegen alle Bedrohungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie schützt Daten auf einem Laptop bei Diebstahl?', 3, '[{"text": "Festplattenverschlüsselung", "correct": true, "because": "Verhindert Fremdzugriff"}, {"text": "Firewall", "correct": false, "because": "Schützt Netzwerk"}, {"text": "Antivirus", "correct": false, "because": "Für Malware"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sichern einen Client effektiv?', 5, '[{"text": "Regelmäßige Updates", "correct": true, "because": "Schließen Sicherheitslücken"}, {"text": "Firewall", "correct": true, "because": "Blockiert Angriffe"}, {"text": "Bunte Icons", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Hohe Auflösung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Zwei-Faktor-Authentifizierung erhöht Sicherheit. b) Sie ersetzt Antivirensoftware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, ergänzt nur"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Absicherung eines Endgeräts?', 4, '[{"text": "Patch-Management", "correct": false, "because": "Schließt Lücken"}, {"text": "Antivirus-Software", "correct": false, "because": "Schützt vor Malware"}, {"text": "Bildschirmdesign", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob automatische Updates ausreichend sind?', 2, '[{"text": "Nein", "correct": true, "because": "Weitere Maßnahmen nötig"}, {"text": "Ja", "correct": false, "because": "Nicht allein ausreichend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme verhindert Phishing-Angriffe am besten?', 4, '[{"text": "Schulung der Nutzer", "correct": true, "because": "Erhöht Awareness"}, {"text": "Schnelle CPU", "correct": false, "because": "Kein Schutzfaktor"}, {"text": "Hohe Auflösung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Firewalls alle Bedrohungen stoppen. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Nur ein Teil der Lösung"}, {"text": "Ja", "correct": false, "because": "Begrenzt auf Netzwerk"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt ein Passwort-Manager vor Malware?', 2, '[{"text": "Nein", "correct": true, "because": "Nur für Zugangsdaten"}, {"text": "Ja", "correct": false, "because": "Kein Malwareschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien erhöhen die Client-Sicherheit?', 5, '[{"text": "Antivirus-Software", "correct": true, "because": "Erkennt Malware"}, {"text": "VPN", "correct": true, "because": "Sichert Verbindungen"}, {"text": "Grafikkarte", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Bildschirmschoner", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Absicherung eines mobilen Clients?', 4, '[{"text": "Festplattenverschlüsselung", "correct": true, "because": "Schützt bei Verlust"}, {"text": "Hohe Akkulaufzeit", "correct": false, "because": "Sekundär"}, {"text": "Leichtes Gewicht", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Backups schützen vor Ransomware. b) Sie verhindern Angriffe.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, nur Wiederherstellung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Client-Sicherheit?', 3, '[{"text": "Firewall", "correct": false, "because": "Blockiert Netzwerkangriffe"}, {"text": "Updates", "correct": false, "because": "Schließen Lücken"}, {"text": "Hintergrundbild", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich einen Client vor Datenlecks schütze?', 4, '[{"text": "Verschlüsselung und Zugriffskontrollen", "correct": true, "because": "Sichert Daten"}, {"text": "Nur Antivirus", "correct": false, "because": "Zu eingeschränkt"}, {"text": "Ohne Maßnahmen", "correct": false, "because": "Riskant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Makros in Office sicher sind. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Können Malware enthalten"}, {"text": "Ja", "correct": false, "because": "Häufig unsicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme schützt vor Zero-Day-Exploits?', 4, '[{"text": "Intrusion Detection", "correct": true, "because": "Erkennt Anomalien"}, {"text": "Bildschirmgröße", "correct": false, "because": "Irrelevant"}, {"text": "Hohe RAM-Kapazität", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein lokales Backup ausreichend?', 2, '[{"text": "Nein", "correct": true, "because": "Offsite-Backups nötig"}, {"text": "Ja", "correct": false, "because": "Risiko bei Diebstahl"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren minimieren Risiken bei Clients?', 5, '[{"text": "Schulungen", "correct": true, "because": "Reduzieren Fehler"}, {"text": "Updates", "correct": true, "because": "Schließen Lücken"}, {"text": "Schnelle CPU", "correct": false, "because": "Sekundär"}, {"text": "Bunte Tastatur", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Client-Absicherung unwichtig?', 3, '[{"text": "Antivirus", "correct": false, "because": "Schützt vor Malware"}, {"text": "Firewall", "correct": false, "because": "Blockiert Angriffe"}, {"text": "Bildschirmhelligkeit", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich einen Client sichere?', 4, '[{"text": "Updates, Firewall, Antivirus installieren", "correct": true, "because": "Umfassender Schutz"}, {"text": "Nur Passwort setzen", "correct": false, "because": "Zu eingeschränkt"}, {"text": "Ohne Maßnahmen", "correct": false, "because": "Unsicher"}]');

