-- Schutzmaßnahmen für Betriebssysteme.sql (Maßnahmen zum Schutz von Betriebssystemen vor Sicherheitsbedrohungen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass regelmäßige Updates eines Betriebssystems ausreichen, um es vollständig zu schützen?', 2, '[{"text": "Nein", "correct": true, "because": "Updates sind wichtig, aber weitere Maßnahmen nötig"}, {"text": "Ja", "correct": false, "because": "Mehrschichtiger Schutz erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme schützt ein Betriebssystem vor unbefugtem Zugriff?', 3, '[{"text": "Starke Passwörter", "correct": true, "because": "Verhindern unbefugtes Einloggen"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen erhöhen die Sicherheit eines Betriebssystems?', 5, '[{"text": "Regelmäßige Updates", "correct": true, "because": "Schließen Sicherheitslücken"}, {"text": "Firewall-Aktivierung", "correct": true, "because": "Blockiert Angriffe"}, {"text": "Verschlüsselung", "correct": true, "because": "Schützt Daten"}, {"text": "Bunte Oberfläche", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Firewall schützt vor Netzwerkangriffen. b) Sie ersetzt Antivirensoftware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Firewall und Antivirus ergänzen sich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Absicherung eines Betriebssystems?', 4, '[{"text": "Zugriffskontrollen", "correct": false, "because": "Schützen vor Missbrauch"}, {"text": "Updates", "correct": false, "because": "Schließen Lücken"}, {"text": "Bildschirmdesign", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Antivirensoftware alle Bedrohungen abdeckt?', 2, '[{"text": "Nein", "correct": true, "because": "Ergänzende Maßnahmen nötig"}, {"text": "Ja", "correct": false, "because": "Kein vollständiger Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip minimiert die Angriffsfläche eines Systems?', 4, '[{"text": "Härten", "correct": true, "because": "Entfernt unnötige Dienste"}, {"text": "Schnelle Installation", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Hohe Speichergröße", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Verschlüsselung allein ausreicht. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Teil eines Schutzkonzepts"}, {"text": "Ja", "correct": false, "because": "Kombination nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt ein Benutzerkonto ohne Admin-Rechte?', 2, '[{"text": "Ja", "correct": true, "because": "Einschränkt Schadsoftware"}, {"text": "Nein", "correct": false, "because": "Reduziert Risiken"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen schützen Daten auf einem Betriebssystem?', 5, '[{"text": "Verschlüsselung", "correct": true, "because": "Schützt Dateninhalt"}, {"text": "Zugriffskontrollen", "correct": true, "because": "Begrenzt Zugriff"}, {"text": "Hohe Auflösung", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Schnelle CPU", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Absicherung eines Servers?', 4, '[{"text": "Minimierung von Diensten", "correct": true, "because": "Reduziert Angriffsfläche"}, {"text": "Maximale Nutzerkonten", "correct": false, "because": "Erhöht Risiko"}, {"text": "Bunte Icons", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Backups schützen vor Datenverlust. b) Sie verhindern Angriffe.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Backups schützen nicht aktiv"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für den Schutz eines Betriebssystems?', 3, '[{"text": "Antivirensoftware", "correct": false, "because": "Erkennt Schadsoftware"}, {"text": "Updates", "correct": false, "because": "Schließen Lücken"}, {"text": "Dekoratives Design", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich die Angriffsfläche eines Systems reduziere?', 4, '[{"text": "Unnötige Software entfernen", "correct": true, "because": "Minimiert Schwachstellen"}, {"text": "Mehr Programme installieren", "correct": false, "because": "Erhöht Risiko"}, {"text": "Ohne Prüfung", "correct": false, "because": "Gefährlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Firewalls alle Angriffe stoppen. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Teil des Schutzes"}, {"text": "Ja", "correct": false, "because": "Kombination nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik schützt vor Malware-Installation?', 4, '[{"text": "Eingeschränkte Benutzerrechte", "correct": true, "because": "Begrenzt Schadsoftware"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Irrelevant"}, {"text": "Schnelle Updates", "correct": false, "because": "Nur Teilweise"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind automatische Updates sicher?', 2, '[{"text": "Ja", "correct": true, "because": "Schließen Lücken schnell"}, {"text": "Nein", "correct": false, "because": "Werden empfohlen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Zwei-Faktor-Authentifizierung?', 5, '[{"text": "Erhöhte Sicherheit", "correct": true, "because": "Zusätzliche Schutzschicht"}, {"text": "Schutz vor unbefugtem Zugriff", "correct": true, "because": "Schwieriger zu knacken"}, {"text": "Schnellere Anmeldung", "correct": false, "because": "Kein Sicherheitsvorteil"}, {"text": "Besseres Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Absicherung eines Systems unwichtig?', 3, '[{"text": "Passwortrichtlinien", "correct": false, "because": "Schützen Zugriff"}, {"text": "Firewall", "correct": false, "because": "Blockiert Angriffe"}, {"text": "Bildschirmauflösung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich ein Betriebssystem sichere?', 4, '[{"text": "Updates, Antivirus, Firewall einrichten", "correct": true, "because": "Umfassender Schutz"}, {"text": "Nur Antivirus installieren", "correct": false, "because": "Zu eingeschränkt"}, {"text": "Ohne Maßnahmen", "correct": false, "because": "Gefährlich"}]');

