-- Schutzmaßnahmen für Office-Produkte.sql (Maßnahmen zum Schutz von Microsoft Office-Produkten vor Sicherheitsbedrohungen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass das Deaktivieren von Makros in Office-Dokumenten alle Bedrohungen verhindert?', 2, '[{"text": "Nein", "correct": true, "because": "Weitere Maßnahmen wie Updates nötig"}, {"text": "Ja", "correct": false, "because": "Makros nur ein Angriffsweg"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einstellung schützt Office vor bösartigen Makros?', 3, '[{"text": "Makros nur aus vertrauenswürdigen Quellen zulassen", "correct": true, "because": "Reduziert Angriffsrisiko"}, {"text": "Alle Makros aktivieren", "correct": false, "because": "Erhöht Gefahr"}, {"text": "Makros ignorieren", "correct": false, "because": "Keine Sicherheitsmaßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sichern Office-Produkte ab?', 5, '[{"text": "Regelmäßige Updates", "correct": true, "because": "Schließen Sicherheitslücken"}, {"text": "Geschützte Ansicht aktivieren", "correct": true, "because": "Blockiert unsichere Inhalte"}, {"text": "Antivirensoftware", "correct": true, "because": "Erkennt Schadsoftware"}, {"text": "Farbcodierte Menüs", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Hohe Bildschirmauflösung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die geschützte Ansicht blockiert externe Inhalte. b) Sie ersetzt Antivirensoftware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Antivirus ergänzt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Absicherung von Office-Produkten?', 4, '[{"text": "Sicherheitsupdates", "correct": false, "because": "Schließen Schwachstellen"}, {"text": "Vertrauenswürdige Quellen", "correct": false, "because": "Reduzieren Risiken"}, {"text": "Symbolfarben", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob das Trust Center für Office-Sicherheit wichtig ist?', 2, '[{"text": "Ja", "correct": true, "because": "Steuert Sicherheitsoptionen"}, {"text": "Nein", "correct": false, "because": "Zentral für Konfiguration"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme schützt vor Phishing in Office-E-Mails?', 4, '[{"text": "Externe Inhalte blockieren", "correct": true, "because": "Verhindert schädliche Links"}, {"text": "E-Mails schneller laden", "correct": false, "because": "Kein Schutz"}, {"text": "Bilder immer anzeigen", "correct": false, "because": "Erhöht Risiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Office-Dateien nie Sicherheitsrisiken haben. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Makros und Links können gefährlich sein"}, {"text": "Ja", "correct": false, "because": "Häufige Angriffsvektoren"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die geschützte Ansicht standardmäßig aktiviert?', 2, '[{"text": "Ja", "correct": true, "because": "Für Dateien aus unsicheren Quellen"}, {"text": "Nein", "correct": false, "because": "Standard in Office"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einstellungen verbessern die Office-Sicherheit?', 5, '[{"text": "Makros deaktivieren", "correct": true, "because": "Verhindert Schadcode"}, {"text": "Meldungsleiste aktivieren", "correct": true, "because": "Warnt vor Risiken"}, {"text": "Hohe Schriftgröße", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Automatisches Speichern", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Absicherung von Office?', 4, '[{"text": "Regelmäßige Updates", "correct": true, "because": "Schließen Sicherheitslücken"}, {"text": "Schnelle Installation", "correct": false, "because": "Sekundär"}, {"text": "Benutzeroberfläche", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Das Trust Center steuert Sicherheitsoptionen. b) Es blockiert automatisch alle Makros.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Einstellung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Sicherheit von Office-Produkten?', 3, '[{"text": "Antivirensoftware", "correct": false, "because": "Ergänzt Schutz"}, {"text": "Sicherheitswarnungen", "correct": false, "because": "Informieren Nutzer"}, {"text": "Farbanpassung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich externe Inhalte in Office absichere?', 4, '[{"text": "Externe Inhalte im Trust Center blockieren", "correct": true, "because": "Verhindert Web-Beacons"}, {"text": "Alle Inhalte zulassen", "correct": false, "because": "Erhöht Risiko"}, {"text": "Inhalte ignorieren", "correct": false, "because": "Keine Maßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Sicherheitsupdates in Office optional sind. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Kritisch für Schutz"}, {"text": "Ja", "correct": false, "because": "Schließen Schwachstellen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature warnt vor unsicheren Inhalten?', 4, '[{"text": "Meldungsleiste", "correct": true, "because": "Zeigt Sicherheitsrisiken"}, {"text": "Autovervollständigung", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Formatvorlagen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt die geschützte Ansicht vor allen Angriffen?', 2, '[{"text": "Nein", "correct": true, "because": "Nur ein Schutzmechanismus"}, {"text": "Ja", "correct": false, "because": "Ergänzende Maßnahmen nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet das Deaktivieren von Makros?', 5, '[{"text": "Schutz vor Schadcode", "correct": true, "because": "Verhindert bösartige Skripte"}, {"text": "Weniger Warnungen", "correct": true, "because": "Reduziert Sicherheitsmeldungen"}, {"text": "Schnellere Dokumente", "correct": false, "because": "Kein Sicherheitsvorteil"}, {"text": "Bessere Formatierung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Office-Absicherung unwichtig?', 3, '[{"text": "Firewall", "correct": false, "because": "Schützt Netzwerk"}, {"text": "Sicherheitsrichtlinien", "correct": false, "because": "Steuern Schutz"}, {"text": "Menüanpassung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich Office sicher konfigurieren will?', 4, '[{"text": "Makros deaktivieren, Updates einrichten", "correct": true, "because": "Reduziert Risiken"}, {"text": "Alle Inhalte zulassen", "correct": false, "because": "Erhöht Gefahr"}, {"text": "Ohne Einstellungen", "correct": false, "because": "Unsicher"}]');

