-- Serverdienste.sql (Dienste wie Webserver, Datenbankserver, E-Mail-Server für Netzwerkfunktionen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass ein Webserver immer auch eine Datenbank benötigt?', 2, '[{"text": "Nein", "correct": true, "because": "Statische Inhalte ohne Datenbank möglich"}, {"text": "Ja", "correct": false, "because": "Nicht immer nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wird typischerweise für E-Mail-Server verwendet?', 3, '[{"text": "SMTP", "correct": true, "because": "Standard für E-Mail-Versand"}, {"text": "FTP", "correct": false, "because": "Für Dateitransfer"}, {"text": "HTTP", "correct": false, "because": "Für Web"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Dienste sind auf einem Server üblich?', 5, '[{"text": "Webserver", "correct": true, "because": "Bereitstellt Webseiten"}, {"text": "Datenbankserver", "correct": true, "because": "Verwaltet Daten"}, {"text": "DNS-Server", "correct": true, "because": "Löst Namen auf"}, {"text": "Grafikrendering", "correct": false, "because": "Für Workstations"}, {"text": "Bürodesign", "correct": false, "because": "Kein Serverdienst"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Apache ist ein Webserver. b) Es verwaltet auch E-Mails.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Apache nur für Web"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Konfiguration eines Servers?', 4, '[{"text": "Port-Einstellungen", "correct": false, "because": "Bestimmen Zugriff"}, {"text": "Sicherheitsrichtlinien", "correct": false, "because": "Schützen Dienst"}, {"text": "Serverfarbe", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein DNS-Server IP-Adressen zuordnet?', 2, '[{"text": "Ja", "correct": true, "because": "Löst Namen zu IPs auf"}, {"text": "Nein", "correct": false, "because": "Kernfunktion von DNS"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Dienst ermöglicht die Verwaltung von Datenbanken?', 4, '[{"text": "Datenbankserver", "correct": true, "because": "Speichert und verarbeitet Daten"}, {"text": "Webserver", "correct": false, "because": "Für Webseiten"}, {"text": "Mailserver", "correct": false, "because": "Für E-Mails"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein FTP-Server für Webseiten zuständig ist. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "FTP für Dateitransfer, nicht Web"}, {"text": "Ja", "correct": false, "because": "Webserver zuständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Läuft ein Webserver immer auf Port 80?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Port 443 für HTTPS"}, {"text": "Ja", "correct": false, "because": "Konfigurierbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Protokolle sind für Serverdienste typisch?', 5, '[{"text": "HTTP", "correct": true, "because": "Für Webserver"}, {"text": "IMAP", "correct": true, "because": "Für E-Mail-Abruf"}, {"text": "MIDI", "correct": false, "because": "Für Audio"}, {"text": "VGA", "correct": false, "because": "Für Bildschirme"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Einrichtung eines Servers?', 4, '[{"text": "Sicherheitskonfiguration", "correct": true, "because": "Schützt vor Angriffen"}, {"text": "Schnelle Installation", "correct": false, "because": "Sicherheit wichtiger"}, {"text": "Optisches Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) MySQL ist ein Datenbankserver. b) Es hostet auch Webseiten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Webserver separat"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen sicheren Serverdienst?', 3, '[{"text": "Firewall", "correct": false, "because": "Schützt Netzwerk"}, {"text": "Zugriffskontrollen", "correct": false, "because": "Begrenzen Zugriff"}, {"text": "Dekoratives Layout", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich einen E-Mail-Server absichere?', 4, '[{"text": "TLS aktivieren, Ports schützen", "correct": true, "because": "Sichert Kommunikation"}, {"text": "Alle Ports öffnen", "correct": false, "because": "Erhöht Risiko"}, {"text": "Ohne Verschlüsselung", "correct": false, "because": "Unsicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Datenbankserver immer lokal laufen muss. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Auch in Cloud möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Dienst löst Domänennamen in IP-Adressen auf?', 4, '[{"text": "DNS-Server", "correct": true, "because": "Kernfunktion von DNS"}, {"text": "Webserver", "correct": false, "because": "Bereitstellt Inhalte"}, {"text": "DHCP-Server", "correct": false, "because": "Vergibt IPs"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist NGINX ein Datenbankserver?', 2, '[{"text": "Nein", "correct": true, "because": "NGINX ist ein Webserver"}, {"text": "Ja", "correct": false, "because": "Falsche Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein gut konfigurierter Serverdienst?', 5, '[{"text": "Hohe Verfügbarkeit", "correct": true, "because": "Sichert Betrieb"}, {"text": "Sicherheit", "correct": true, "because": "Schützt Daten"}, {"text": "Bunte Oberfläche", "correct": false, "because": "Kein Vorteil"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Verwaltung eines Servers unwichtig?', 3, '[{"text": "Protokollierung", "correct": false, "because": "Hilft bei Fehlersuche"}, {"text": "Sicherheitsupdates", "correct": false, "because": "Schützen System"}, {"text": "Servergewicht", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich einen Webserver einrichte?', 4, '[{"text": "Ports konfigurieren, Firewall einrichten", "correct": true, "because": "Sichert Zugriff"}, {"text": "Nur Inhalte hochladen", "correct": false, "because": "Fehlt Sicherheit"}, {"text": "Ohne Konfiguration", "correct": false, "because": "Unsicher"}]');

