-- Sicherheitsleitlinie.sql (Richtlinien für IT-Sicherheit und Datenschutz in Organisationen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass eine Richtlinie für IT-Sicherheit immer nur technische Vorgaben enthält?', 2, '[{"text": "Nein", "correct": true, "because": "Auch organisatorische Maßnahmen"}, {"text": "Ja", "correct": false, "because": "Umfassender Ansatz nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt eine solche Richtlinie?', 3, '[{"text": "Risikominimierung", "correct": true, "because": "Schützt Systeme und Daten"}, {"text": "Farbcodierung", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Bürodesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bereiche deckt eine solche Richtlinie ab?', 5, '[{"text": "Zugriffskontrollen", "correct": true, "because": "Begrenzen Zugriff"}, {"text": "Schulungen", "correct": true, "because": "Erhöhen Bewusstsein"}, {"text": "Datenverschlüsselung", "correct": true, "because": "Schützt Vertraulichkeit"}, {"text": "Bunte Interfaces", "correct": false, "because": "Kosmetisch"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Richtlinie definiert Sicherheitsmaßnahmen. b) Sie wird einmal erstellt und nie geändert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Anpassung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Erstellung einer Sicherheitsrichtlinie?', 4, '[{"text": "Gesetzliche Vorgaben", "correct": false, "because": "Sichern Compliance"}, {"text": "Risikobewertung", "correct": false, "because": "Bestimmt Maßnahmen"}, {"text": "Firmenlogo", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Richtlinie nur für IT-Systeme gilt?', 2, '[{"text": "Nein", "correct": true, "because": "Umfasst auch Prozesse, Mitarbeiter"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme wird durch eine Richtlinie oft vorgeschrieben?', 4, '[{"text": "Passwortrichtlinien", "correct": true, "because": "Sichern Zugriff"}, {"text": "Schnelle Installation", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Richtlinie nur für große Unternehmen relevant ist. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Auch KMUs brauchen Sicherheit"}, {"text": "Ja", "correct": false, "because": "Universelle Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Wird eine Richtlinie nur einmal überprüft?', 2, '[{"text": "Nein", "correct": true, "because": "Regelmäßige Überprüfung nötig"}, {"text": "Ja", "correct": false, "because": "Anpassung erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Themen behandelt eine solche Richtlinie?', 5, '[{"text": "Datenklassifizierung", "correct": true, "because": "Schützt sensible Daten"}, {"text": "Notfallpläne", "correct": true, "because": "Sichern Wiederherstellung"}, {"text": "Schulungen", "correct": true, "because": "Fördern Compliance"}, {"text": "Bürofarben", "correct": false, "because": "Kosmetisch"}, {"text": "Möbeldesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Umsetzung einer Richtlinie?', 4, '[{"text": "Compliance", "correct": true, "because": "Sichert gesetzliche Vorgaben"}, {"text": "Schnelle Umsetzung", "correct": false, "because": "Genauigkeit wichtiger"}, {"text": "Visuelles Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Richtlinie schützt vor Datenlecks. b) Sie ersetzt technische Maßnahmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, ergänzt Maßnahmen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine Sicherheitsrichtlinie?', 3, '[{"text": "Verantwortlichkeiten", "correct": false, "because": "Definieren Zuständigkeiten"}, {"text": "Maßnahmenkatalog", "correct": false, "because": "Schützt Systeme"}, {"text": "Dekorative Diagramme", "correct": true, "because": "Nur visuelle Hilfe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich eine Richtlinie für Mitarbeiter erstelle?', 4, '[{"text": "Klare Regeln und Schulungen festlegen", "correct": true, "because": "Fördert Verständnis"}, {"text": "Nur technische Vorgaben machen", "correct": false, "because": "Zu eingeschränkt"}, {"text": "Ohne Kommunikation", "correct": false, "because": "Ineffektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Richtlinie automatisch alle Risiken eliminiert. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Minimiert, aber eliminiert nicht"}, {"text": "Ja", "correct": false, "because": "Risiken bleiben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip hilft, eine Richtlinie effektiv umzusetzen?', 4, '[{"text": "Regelmäßige Schulungen", "correct": true, "because": "Fördern Einhaltung"}, {"text": "Einmalige Regeln", "correct": false, "because": "Zu statisch"}, {"text": "Minimale Kontrollen", "correct": false, "because": "Ineffektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss eine Richtlinie gesetzlich vorgeschrieben sein?', 2, '[{"text": "Nein", "correct": true, "because": "Freiwillig, aber oft notwendig"}, {"text": "Ja", "correct": false, "because": "Kontextabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gut formulierte Richtlinie?', 5, '[{"text": "Klarheit für Mitarbeiter", "correct": true, "because": "Definiert Erwartungen"}, {"text": "Rechtliche Absicherung", "correct": true, "because": "Fördert Compliance"}, {"text": "Schnellere Prozesse", "correct": false, "because": "Nicht primär"}, {"text": "Bunte Visuals", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer Richtlinie unwichtig?', 3, '[{"text": "Verständlichkeit", "correct": false, "because": "Fördert Einhaltung"}, {"text": "Verantwortlichkeiten", "correct": false, "because": "Definieren Zuständigkeiten"}, {"text": "Präsentationsstil", "correct": true, "because": "Nur visuelle Hilfe"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich eine Richtlinie erstelle?', 4, '[{"text": "Risiken analysieren, Regeln klar definieren", "correct": true, "because": "Strukturierter Ansatz"}, {"text": "Nur technische Vorgaben setzen", "correct": false, "because": "Zu eingeschränkt"}, {"text": "Ohne Analyse starten", "correct": false, "because": "Ineffektiv"}]');

