-- Sicherheitsregeln.sql (Regeln zur Gewährleistung der IT-Sicherheit in Systemen und Organisationen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass IT-Sicherheitsvorgaben immer nur technische Aspekte abdecken?', 2, '[{"text": "Nein", "correct": true, "because": "Auch organisatorische Maßnahmen enthalten"}, {"text": "Ja", "correct": false, "because": "Umfassen beide Aspekte"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme ist typisch für IT-Sicherheitsvorgaben?', 3, '[{"text": "Passwortrichtlinien", "correct": true, "because": "Schützen Zugänge"}, {"text": "Farbcodierung", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte gehören zu solchen Vorgaben?', 5, '[{"text": "Zugriffskontrollen", "correct": true, "because": "Begrenzen Zugriff"}, {"text": "Schulungen", "correct": true, "because": "Erhöhen Bewusstsein"}, {"text": "Updates", "correct": true, "because": "Schließen Lücken"}, {"text": "Logo-Design", "correct": false, "because": "Kosmetisch"}, {"text": "Bildschirmgröße", "correct": false, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Regelmäßige Backups sind Teil der Vorgaben. b) Sie gelten nur für Server.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, gelten für alle Systeme"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Umsetzung solcher Vorgaben?', 4, '[{"text": "Zugriffsrechte", "correct": false, "because": "Sichern Systeme"}, {"text": "Schulungen", "correct": false, "because": "Fördern Compliance"}, {"text": "Firmenfarben", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob solche Vorgaben nur für Admins gelten?', 2, '[{"text": "Nein", "correct": true, "because": "Betreffen alle Nutzer"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Regel schützt vor unbefugtem Zugriff?', 4, '[{"text": "Zwei-Faktor-Authentifizierung", "correct": true, "because": "Erhöht Sicherheit"}, {"text": "Schnelle Logins", "correct": false, "because": "Kein Schutz"}, {"text": "Offene Ports", "correct": false, "because": "Erhöht Risiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass solche Vorgaben immer freiwillig sind. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Oft gesetzlich vorgeschrieben"}, {"text": "Ja", "correct": false, "because": "Verpflichtend in Firmen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Passwortrichtlinien Teil solcher Vorgaben?', 2, '[{"text": "Ja", "correct": true, "because": "Schützen Zugänge"}, {"text": "Nein", "correct": false, "because": "Standardmaßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sind in solchen Vorgaben typisch?', 5, '[{"text": "Firewall-Regeln", "correct": true, "because": "Schützen Netzwerk"}, {"text": "Protokollierung", "correct": true, "because": "Erkennt Vorfälle"}, {"text": "Verschlüsselung", "correct": true, "because": "Sichert Daten"}, {"text": "Bunte Symbole", "correct": false, "because": "Kosmetisch"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Umsetzung solcher Vorgaben?', 4, '[{"text": "Zugriffskontrollen", "correct": true, "because": "Schützen Systeme"}, {"text": "Schnelle Umsetzung", "correct": false, "because": "Genauigkeit wichtiger"}, {"text": "Visuelles Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Schulungen fördern Regelbewusstsein. b) Sie ersetzen technische Maßnahmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, ergänzen Maßnahmen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für solche Vorgaben?', 3, '[{"text": "Richtlinien", "correct": false, "because": "Definieren Regeln"}, {"text": "Überwachung", "correct": false, "because": "Sichert Einhaltung"}, {"text": "Dekoratives Layout", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich Phishing verhindere?', 4, '[{"text": "Schulungen und Filter einsetzen", "correct": true, "because": "Erhöhen Bewusstsein und Schutz"}, {"text": "Nur E-Mails öffnen", "correct": false, "because": "Erhöht Risiko"}, {"text": "Ohne Maßnahmen", "correct": false, "because": "Gefährlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass solche Vorgaben nur für große Firmen gelten. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Betreffen alle Organisationen"}, {"text": "Ja", "correct": false, "because": "Universelle Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip hilft, solche Vorgaben durchzusetzen?', 4, '[{"text": "Regelmäßige Audits", "correct": true, "because": "Überprüfen Einhaltung"}, {"text": "Keine Kontrollen", "correct": false, "because": "Riskiert Verstöße"}, {"text": "Zufällige Prüfungen", "correct": false, "because": "Weniger effektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind solche Vorgaben statisch?', 2, '[{"text": "Nein", "correct": true, "because": "Werden regelmäßig aktualisiert"}, {"text": "Ja", "correct": false, "because": "Anpassung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten solche Vorgaben?', 5, '[{"text": "Risikoreduktion", "correct": true, "because": "Minimieren Bedrohungen"}, {"text": "Rechtliche Compliance", "correct": true, "because": "Erfüllen Vorgaben"}, {"text": "Schnellere Prozesse", "correct": false, "because": "Kein Sicherheitsvorteil"}, {"text": "Bunte Visuals", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Erstellung solcher Vorgaben unwichtig?', 3, '[{"text": "Risikoanalyse", "correct": false, "because": "Definiert Bedarf"}, {"text": "Schulungen", "correct": false, "because": "Fördern Einhaltung"}, {"text": "Präsentationsstil", "correct": true, "because": "Kosmetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich solche Vorgaben einführe?', 4, '[{"text": "Risiken prüfen, Regeln definieren", "correct": true, "because": "Strukturierter Ansatz"}, {"text": "Nur Software installieren", "correct": false, "because": "Zu eingeschränkt"}, {"text": "Ohne Plan starten", "correct": false, "because": "Unstrukturiert"}]');

