INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > IT-Arbeitsplätze im Kontext > Komponentenhersteller
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind Komponentenhersteller für die Entwicklung moderner IT-Arbeitsplätze unerlässlich?', 2, '[{"text": "Ja", "correct": true, "because": "Liefern essenzielle Hardware wie CPUs und Speicher"}, {"text": "Nein", "correct": false, "because": "Komponenten sind grundlegend"}]'),
('00000000-0000-0000-0000-000000000000', 'Können IT-Arbeitsplätze ohne Produkte von Komponentenherstellern funktionieren?', 2, '[{"text": "Nein", "correct": true, "because": "Hardware ist für Betrieb notwendig"}, {"text": "Ja", "correct": false, "because": "Abhängigkeit von Komponenten"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Leistungsfähigkeit von IT-Arbeitsplätzen unabhängig von den Komponentenherstellern?', 2, '[{"text": "Nein", "correct": true, "because": "Qualität und Innovation der Komponenten beeinflussen Leistung"}, {"text": "Ja", "correct": false, "because": "Hersteller sind entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Produzieren Komponentenhersteller ausschließlich Hardware für IT-Arbeitsplätze?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Server, Mobilgeräte etc."}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Haben Trends wie Miniaturisierung die Rolle der Komponentenhersteller verändert?', 2, '[{"text": "Ja", "correct": true, "because": "Fokus auf kleinere, effizientere Teile"}, {"text": "Nein", "correct": false, "because": "Trends beeinflussen Entwicklung"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Komponentenhersteller ist bekannt für Prozessoren?', 3, '[{"text": "Intel", "correct": true, "because": "Führend bei CPUs"}, {"text": "Samsung", "correct": false, "because": "Mehr Displays und Speicher"}, {"text": "Seagate", "correct": false, "because": "Festplatten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponente ist für die Datenverarbeitung an IT-Arbeitsplätzen entscheidend?', 2, '[{"text": "CPU", "correct": true, "because": "Hauptverarbeitungseinheit"}, {"text": "Monitor", "correct": false, "because": "Ausgabe"}, {"text": "Tastatur", "correct": false, "because": "Eingabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Hersteller ist führend bei Grafikkarten?', 2, '[{"text": "NVIDIA", "correct": true, "because": "Marktführer bei GPUs"}, {"text": "Intel", "correct": false, "because": "Fokus auf CPUs"}, {"text": "Western Digital", "correct": false, "because": "Speicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielen Komponentenhersteller bei IT-Arbeitsplätzen?', 3, '[{"text": "Bereitstellung essentieller Hardware", "correct": true, "because": "Ohne Komponenten kein Betrieb"}, {"text": "Softwareentwicklung", "correct": false, "because": "Andere Branche"}, {"text": "Logistik", "correct": false, "because": "Transport"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptvorteil innovativer Komponentenhersteller?', 2, '[{"text": "Höhere Leistung", "correct": true, "because": "Verbessert Arbeitsplatz-Effizienz"}, {"text": "Geringere Kosten", "correct": false, "because": "Nicht primär"}, {"text": "Schnelle Lieferung", "correct": false, "because": "Logistisch"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten liefern Hersteller für IT-Arbeitsplätze?', 4, '[{"text": "Prozessoren", "correct": true, "because": "Für Verarbeitung"}, {"text": "Grafikkarten", "correct": true, "because": "Für visuelle Aufgaben"}, {"text": "Speichermodule", "correct": true, "because": "Für Datenhaltung"}, {"text": "Stühle", "correct": false, "because": "Möbel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Hersteller sind für IT-Komponenten bekannt?', 3, '[{"text": "Intel", "correct": true, "because": "Prozessoren"}, {"text": "AMD", "correct": true, "because": "Prozessoren und GPUs"}, {"text": "NVIDIA", "correct": true, "because": "Grafikkarten"}, {"text": "Toyota", "correct": false, "because": "Automobil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten moderne Komponentenhersteller?', 3, '[{"text": "Höhere Leistung", "correct": true, "because": "Verbesserte Technologie"}, {"text": "Energieeffizienz", "correct": true, "because": "Geringerer Verbrauch"}, {"text": "Skalierbarkeit", "correct": true, "because": "Anpassbar"}, {"text": "Geringere Größe", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es für Komponentenhersteller?', 4, '[{"text": "Technologische Innovation", "correct": true, "because": "Ständige Weiterentwicklung"}, {"text": "Kostenmanagement", "correct": true, "because": "Wettbewerbsdruck"}, {"text": "Lieferkettenprobleme", "correct": true, "because": "Materialknappheit"}, {"text": "Farbauswahl", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Trends beeinflussen die Arbeit von Komponentenherstellern?', 3, '[{"text": "Miniaturisierung", "correct": true, "because": "Kleinere Geräte"}, {"text": "Künstliche Intelligenz", "correct": true, "because": "Spezialisierte Chips"}, {"text": "Energieeffizienz", "correct": true, "because": "Nachhaltigkeit"}, {"text": "Lieferzeit", "correct": false, "because": "Logistisch"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Intel ist ein führender Prozessorhersteller. b) Komponentenhersteller sind für IT-Arbeitsplätze unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Intel ja, Hersteller essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) NVIDIA stellt Grafikkarten her. b) IT-Arbeitsplätze funktionieren ohne Komponenten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "NVIDIA ja, Komponenten nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Komponentenhersteller verbessern die Leistung von IT-Arbeitsplätzen. b) Sie produzieren nur für große Unternehmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Leistung ja, für alle Größen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Miniaturisierung ist ein Trend bei Komponentenherstellern. b) Ihre Produkte sind nur für Hardware relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Miniaturisierung ja, auch Softwareunterstützung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Energieeffizienz ist ein Ziel von Komponentenherstellern. b) Ihre Innovationen haben keinen Einfluss auf IT-Arbeitsplätze.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Effizienz ja, Einfluss groß"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

