-- Strategy-Pattern.sql (Algorithmische Flexibilität, z. B. austauschbare Verhalten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist das Strategy-Pattern nur für komplexe Algorithmen geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Auch einfache Verhalten austauschbar"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit dem Strategy-Pattern?', 3, '[{"text": "Algorithmische Flexibilität", "correct": true, "because": "Ermöglicht austauschbare Verhalten"}, {"text": "Datenmodellierung", "correct": false, "because": "Kein Datenfokus"}, {"text": "Hardwareintegration", "correct": false, "because": "Kein Hardwareaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zum Strategy-Pattern?', 5, '[{"text": "Strategie-Interface", "correct": true, "because": "Definiert Verhaltensmethoden"}, {"text": "Konkrete Strategien", "correct": true, "because": "Implementieren Varianten"}, {"text": "Datenfluss", "correct": false, "because": "Kein Pattern-Teil"}, {"text": "Farbcodierung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Strategy-Pattern ermöglicht Verhaltenswechsel zur Laufzeit. b) Es ist für statische Algorithmen gedacht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dynamisch, nicht statisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich beim Strategy-Pattern?', 4, '[{"text": "Strategieauswahl", "correct": false, "because": "Kern der Flexibilität"}, {"text": "Kontextklasse", "correct": false, "because": "Wendet Strategie an"}, {"text": "UI-Gestaltung", "correct": true, "because": "Kein Pattern-Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob das Strategy-Pattern auch ohne Interface funktioniert?', 2, '[{"text": "Ja", "correct": true, "because": "Abstrakte Klasse möglich"}, {"text": "Nein", "correct": false, "because": "Nicht zwingend Interface nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt der Kontext im Strategy-Pattern?', 3, '[{"text": "Strategieanwender", "correct": true, "because": "Nutzt ausgewählte Strategie"}, {"text": "Datenquelle", "correct": false, "because": "Kein Datenfokus"}, {"text": "UI-Steuerung", "correct": false, "because": "Nicht UI-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zum Strategy-Pattern?', 5, '[{"text": "Kontext", "correct": true, "because": "Hält Strategiereferenz"}, {"text": "Strategien", "correct": true, "because": "Implementieren Verhalten"}, {"text": "Datenfluss", "correct": false, "because": "Kein Pattern-Teil"}, {"text": "Farbcodierung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Strategy-Pattern fördert Austauschbarkeit. b) Es ist für feste Algorithmen gedacht. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Feste Algorithmen nicht flexibel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für das Strategy-Pattern?', 4, '[{"text": "Strategie-Interface", "correct": false, "because": "Definiert Verhalten"}, {"text": "Kontext", "correct": false, "because": "Wendet Strategie an"}, {"text": "3D-Grafiken", "correct": true, "because": "Kein Pattern-Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist das Strategy-Pattern nur für Laufzeitwechsel?', 2, '[{"text": "Nein", "correct": true, "because": "Auch statisch definierbar"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet das Strategy-Pattern?', 4, '[{"text": "Flexibilität", "correct": true, "because": "Verhalten austauschbar"}, {"text": "Wartbarkeit", "correct": true, "because": "Strategien getrennt"}, {"text": "Datenfluss", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass das Strategy-Pattern die Leistung senkt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Overhead meist minimal"}, {"text": "Ja", "correct": false, "because": "Abhängig von Implementierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich beim Strategy-Pattern?', 3, '[{"text": "Klarheit der Strategien", "correct": true, "because": "Fördert Verständnis"}, {"text": "Schnelle Ausführung", "correct": false, "because": "Flexibilität zählt mehr"}, {"text": "UI-Optik", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Strategy-Pattern nutzt Polymorphismus. b) Es ist für feste Algorithmen gedacht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Feste Algorithmen nicht flexibel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Szenarien profitieren vom Strategy-Pattern?', 5, '[{"text": "Sortieralgorithmen", "correct": true, "because": "Austauschbare Strategien"}, {"text": "Zahlungsverarbeitung", "correct": true, "because": "Verschiedene Methoden"}, {"text": "Datenkompression", "correct": false, "because": "Kein Verhaltensfokus"}, {"text": "UI-Animation", "correct": false, "because": "Kein UI-Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist beim Strategy-Pattern unwichtig?', 3, '[{"text": "Strategieauswahl", "correct": false, "because": "Kern der Flexibilität"}, {"text": "Polymorphismus", "correct": false, "because": "Ermöglicht Austausch"}, {"text": "Blinkende Anzeige", "correct": true, "because": "Kein Pattern-Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann das Strategy-Pattern mehrere Strategien gleichzeitig nutzen?', 3, '[{"text": "Nein", "correct": true, "because": "Eine Strategie pro Kontext"}, {"text": "Ja", "correct": false, "because": "Einzelstrategie im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob das Strategy-Pattern für Tests nützlich ist?', 2, '[{"text": "Ja", "correct": true, "because": "Strategien einzeln testbar"}, {"text": "Nein", "correct": false, "because": "Fördert Testbarkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich für eine Strategie?', 4, '[{"text": "Klasse", "correct": true, "because": "Implementiert Verhalten"}, {"text": "Datenfluss", "correct": false, "because": "Anderes Konzept"}, {"text": "UI-Komponente", "correct": false, "because": "Nicht UI-spezifisch"}]');

