-- DHCPFehlererkennung (Lease-Probleme, Serverausfall).sql
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein DHCP-Serverausfall der einzige Grund für Fehler?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Lease-Probleme möglich"}, {"text": "Ja", "correct": false, "because": "Mehrere Ursachen existieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Symptom zeigt einen DHCP-Serverausfall?', 3, '[{"text": "Keine IP-Zuweisung", "correct": true, "because": "Client erhält keine Antwort"}, {"text": "Hohe Latenz", "correct": false, "because": "Ping-spezifisch"}, {"text": "DNS-Fehler", "correct": false, "because": "Andere Ebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können DHCP-Fehler verursachen?', 5, '[{"text": "Abgelaufene Leases", "correct": true, "because": "IP wird freigegeben"}, {"text": "Serverausfall", "correct": true, "because": "Keine Antworten"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Nicht DHCP"}, {"text": "Paketkompression", "correct": false, "because": "Andere Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein abgelaufener Lease führt zu IP-Verlust. b) Serverausfall ist immer erkennbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ausfall kann versteckt sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der DHCP-Fehlererkennung?', 4, '[{"text": "Lease-Zeit", "correct": false, "because": "Zeigt Ablaufprobleme"}, {"text": "Serverantwort", "correct": false, "because": "Prüft Ausfall"}, {"text": "Webserver-Status", "correct": true, "because": "Nicht DHCP-relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Serverausfall sofort auffällt?', 2, '[{"text": "Nein", "correct": true, "because": "Lease kann noch aktiv sein"}, {"text": "Ja", "correct": false, "because": "Verzögerung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Fehler zeigt einen abgelaufenen Lease?', 3, '[{"text": "Keine IP nach Renewal", "correct": true, "because": "Client verliert Adresse"}, {"text": "Destination Unreachable", "correct": false, "because": "ICMPv6-Fehler"}, {"text": "Echo Reply ausbleibt", "correct": false, "because": "Ping-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anzeichen deuten auf DHCP-Fehler?', 5, '[{"text": "Keine DHCPOFFER-Antwort", "correct": true, "because": "Serverausfall"}, {"text": "IP-Konflikte", "correct": true, "because": "Lease-Problem"}, {"text": "Hohe Latenz", "correct": false, "because": "Netzwerkverzögerung"}, {"text": "DNS-Ausfall", "correct": false, "because": "Andere Ebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Serverausfall stoppt DHCP sofort. b) Lease-Probleme sind selten. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Lease-Probleme häufig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für DHCP-Fehlererkennung?', 4, '[{"text": "DHCP-Logs", "correct": false, "because": "Zeigen Probleme"}, {"text": "Client-Anfragen", "correct": false, "because": "Prüft Serverantwort"}, {"text": "HTTP-Status", "correct": true, "because": "Nicht DHCP-relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Führt ein Serverausfall immer zu IP-Verlust?', 2, '[{"text": "Nein", "correct": true, "because": "Lease bleibt aktiv"}, {"text": "Ja", "correct": false, "because": "Zeitabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool hilft, Serverausfälle zu erkennen?', 4, '[{"text": "dhclient", "correct": true, "because": "Zeigt fehlende Antwort"}, {"text": "traceroute", "correct": false, "because": "Pfadanalyse"}, {"text": "ipconfig", "correct": false, "because": "Nur Konfiguration"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Lease-Probleme nur bei IPv6 auftreten. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch IPv4 betroffen"}, {"text": "Ja", "correct": false, "because": "Protokollunabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei DHCP-Fehlererkennung?', 3, '[{"text": "Serverantwort", "correct": true, "because": "Zeigt Ausfall"}, {"text": "DNS-Einträge", "correct": false, "because": "Sekundär"}, {"text": "Bandbreite", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Kein DHCPOFFER zeigt Serverausfall. b) Lease-Probleme sind Hardware-bedingt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Lease auch Software"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet DHCP-Fehlererkennung?', 5, '[{"text": "Schnelle Problemlokalisierung", "correct": true, "because": "Server oder Lease"}, {"text": "Netzwerkstabilität", "correct": true, "because": "Fehler beheben"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Nicht DHCP"}, {"text": "Latenzreduktion", "correct": false, "because": "Andere Ebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei DHCP-Fehlererkennung unwichtig?', 3, '[{"text": "Lease-Dauer", "correct": false, "because": "Zeigt Ablauf"}, {"text": "Serververfügbarkeit", "correct": false, "because": "Kernproblem"}, {"text": "Web-UI", "correct": true, "because": "Nicht Netzwerk-relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein abgelaufener Lease Netzwerkzugriff verhindern?', 3, '[{"text": "Ja", "correct": true, "because": "IP wird ungültig"}, {"text": "Nein", "correct": false, "because": "Zugriff endet"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Serverausfall sofort IP-Verlust bedeutet?', 2, '[{"text": "Nein", "correct": true, "because": "Lease bleibt gültig"}, {"text": "Ja", "correct": false, "because": "Zeitabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Symptom zeigt einen DHCP-Fehler?', 4, '[{"text": "Keine IP nach Anfrage", "correct": true, "because": "Server antwortet nicht"}, {"text": "Hohe Ping-Zeit", "correct": false, "because": "Latenzproblem"}, {"text": "Router Advertisement", "correct": false, "because": "SLAAC-spezifisch"}]');

