INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Wirtschaftliche Aspekte > Beschaffungsmanagement > Quantitative Angebotsvergleiche
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen bei quantitativen Angebotsvergleichen immer alle Kostenfaktoren berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Vollständige Kosten sind Grundlage für Vergleich"}, {"text": "Nein", "correct": false, "because": "Kosten sind zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Können quantitative Angebotsvergleiche ohne Rücksicht auf Lieferzeiten durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Lieferzeiten beeinflussen Entscheidung"}, {"text": "Ja", "correct": false, "because": "Zeit ist relevanter Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Preisgestaltung der einzige Faktor bei quantitativen Angebotsvergleichen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Menge, Qualität und Zeit spielen eine Rolle"}, {"text": "Ja", "correct": false, "because": "Mehrdimensionaler Vergleich"}]'),
('00000000-0000-0000-0000-000000000000', 'Können quantitative Angebotsvergleiche ohne Dokumentation effizient sein?', 2, '[{"text": "Nein", "correct": true, "because": "Dokumentation sichert Nachvollziehbarkeit"}, {"text": "Ja", "correct": false, "because": "Ohne Dokumentation ineffizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind quantitative Angebotsvergleiche nur für große Beschaffungen relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle Beschaffungsgrößen"}, {"text": "Ja", "correct": false, "because": "Universell anwendbar"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor ist bei quantitativen Angebotsvergleichen am wichtigsten?', 3, '[{"text": "Gesamtpreis", "correct": true, "because": "Hauptkriterium für Wirtschaftlichkeit"}, {"text": "Lieferantengröße", "correct": false, "because": "Sekundär"}, {"text": "Farbauswahl", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium wird neben dem Preis häufig verglichen?', 2, '[{"text": "Lieferzeit", "correct": true, "because": "Beeinflusst Verfügbarkeit"}, {"text": "Verpackungsdesign", "correct": false, "because": "Nicht quantitativ"}, {"text": "Markenname", "correct": false, "because": "Qualitativ"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird oft für quantitative Angebotsvergleiche genutzt?', 2, '[{"text": "Tabellenvergleich", "correct": true, "because": "Übersichtliche Darstellung"}, {"text": "Farbabstimmung", "correct": false, "because": "Ästhetisch"}, {"text": "Intuitive Einschätzung", "correct": false, "because": "Nicht quantitativ"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt kann den Gesamtpreis in einem Angebot erhöhen?', 3, '[{"text": "Zusätzliche Transportkosten", "correct": true, "because": "Erhöht die Gesamtkosten"}, {"text": "Lieferantengröße", "correct": false, "because": "Indirekt"}, {"text": "Produktfarbe", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel quantitativer Angebotsvergleiche?', 2, '[{"text": "Kosteneffizienz", "correct": true, "because": "Optimiert Beschaffung"}, {"text": "Schnelle Entscheidung", "correct": false, "because": "Sekundär"}, {"text": "Markenwahl", "correct": false, "because": "Qualitativ"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren werden bei quantitativen Angebotsvergleichen berücksichtigt?', 4, '[{"text": "Preis", "correct": true, "because": "Hauptkriterium"}, {"text": "Lieferzeit", "correct": true, "because": "Beeinflusst Planung"}, {"text": "Menge", "correct": true, "because": "Bestimmt Bedarf"}, {"text": "Farbe", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kosten können in einem Angebot enthalten sein?', 3, '[{"text": "Einkaufspreis", "correct": true, "because": "Grundkosten"}, {"text": "Transportkosten", "correct": true, "because": "Zusatzkosten"}, {"text": "Zollgebühren", "correct": true, "because": "Bei Import"}, {"text": "Werbekosten", "correct": false, "because": "Nicht angebotsbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten quantitative Angebotsvergleiche?', 3, '[{"text": "Kosteneinsparung", "correct": true, "because": "Günstigstes Angebot"}, {"text": "Transparenz", "correct": true, "because": "Klarer Vergleich"}, {"text": "Effiziente Entscheidung", "correct": true, "because": "Datenbasiert"}, {"text": "Schnelle Lieferung", "correct": false, "because": "Abhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können bei quantitativen Angebotsvergleichen auftreten?', 4, '[{"text": "Unvollständige Daten", "correct": true, "because": "Verfälscht Vergleich"}, {"text": "Versteckte Kosten", "correct": true, "because": "Erhöht Gesamtpreis"}, {"text": "Unterschiedliche Lieferzeiten", "correct": true, "because": "Erschwert Entscheidung"}, {"text": "Lieferantengröße", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente sind für einen quantitativen Angebotsvergleich entscheidend?', 3, '[{"text": "Preis", "correct": true, "because": "Hauptkriterium"}, {"text": "Lieferzeit", "correct": true, "because": "Zeitlicher Faktor"}, {"text": "Menge", "correct": true, "because": "Bedarfsdeckung"}, {"text": "Produktfarbe", "correct": false, "because": "Ästhetisch"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Quantitative Angebotsvergleiche berücksichtigen den Preis. b) Lieferzeiten sind im Vergleich irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Preis ja, Lieferzeit wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Dokumentation ist für quantitative Angebotsvergleiche notwendig. b) Nur der Preis entscheidet über die Auswahl.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dokumentation ja, mehr Faktoren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Transportkosten können den Gesamtpreis beeinflussen. b) Quantitative Vergleiche sind nur für große Beschaffungen relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kosten ja, für alle Größen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Eine Tabellenvergleich hilft bei quantitativen Angebotsvergleichen. b) Versteckte Kosten sind im Vergleich unbedeutend.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tabellen ja, Kosten relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Quantitative Angebotsvergleiche fördern Kosteneffizienz. b) Die Menge ist ein entscheidender Vergleichsfaktor.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Effizienz und Menge korrekt"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides richtig"}]');

