-- Ja/Nein-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Muss ein Arbeitgeber den Auszubildenden Arbeitsmittel gemäß § 14 Abs. 1 BBiG bereitstellen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 14 Abs. 1 BBiG verpflichtet dazu"}, {"text": "Nein", "correct": false, "because": "Bereitstellung ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Auszubildende verpflichtet werden, ihre eigenen Arbeitsmittel mitzubringen?', 2, '[{"text": "Ja", "correct": false, "because": "§ 14 Abs. 1 BBiG legt die Pflicht beim Arbeitgeber"}, {"text": "Nein", "correct": true, "because": "Arbeitgeber muss bereitstellen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Arbeitsmittel wie Computer für Fachinformatiker vom Arbeitgeber bereitzustellen?', 2, '[{"text": "Ja", "correct": true, "because": "Notwendig für Ausbildung (§ 14 Abs. 1 BBiG)"}, {"text": "Nein", "correct": false, "because": "Bereitstellung ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss der Arbeitgeber die Arbeitsmittel auch warten?', 2, '[{"text": "Ja", "correct": true, "because": "Funktionsfähigkeit ist Teil der Bereitstellung"}, {"text": "Nein", "correct": false, "because": "Wartung ist impliziert"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Arbeitgeber die Kosten für Arbeitsmittel auf die Auszubildenden abwälzen?', 2, '[{"text": "Ja", "correct": false, "because": "§ 14 Abs. 1 BBiG verbietet dies"}, {"text": "Nein", "correct": true, "because": "Kosten trägt der Arbeitgeber"}]');

-- Single-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz verpflichtet den Arbeitgeber, Arbeitsmittel bereitzustellen?', 2, '[{"text": "BBiG § 14 Abs. 1", "correct": true, "because": "Regelt die Pflicht"}, {"text": "ArbSchG", "correct": false, "because": "Regelt Arbeitsschutz"}, {"text": "KSchG", "correct": false, "because": "Regelt Kündigungsschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was zählt zu den Arbeitsmitteln, die ein Arbeitgeber bereitstellen muss?', 3, '[{"text": "Werkzeuge und Geräte für die Ausbildung", "correct": true, "because": "§ 14 Abs. 1 BBiG umfasst dies"}, {"text": "Private Kleidung", "correct": false, "because": "Keine Arbeitsmittel"}, {"text": "Urlaubsgeld", "correct": false, "because": "Kein Arbeitsmittel"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer trägt die Kosten für die Bereitstellung der Arbeitsmittel?', 2, '[{"text": "Der Arbeitgeber", "correct": true, "because": "Pflicht gemäß § 14 Abs. 1 BBiG"}, {"text": "Die Auszubildenden", "correct": false, "because": "Nicht deren Pflicht"}, {"text": "Die Berufsschule", "correct": false, "because": "Keine Rolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz droht, wenn ein Arbeitgeber keine Arbeitsmittel bereitstellt?', 3, '[{"text": "Verstoß gegen das BBiG", "correct": true, "because": "Pflichtverletzung nach § 14 Abs. 1"}, {"text": "Höhere Vergütung", "correct": false, "because": "Keine Folge"}, {"text": "Kürzere Ausbildung", "correct": false, "because": "Kein Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Ziel der Bereitstellung von Arbeitsmitteln durch den Arbeitgeber?', 2, '[{"text": "Gewährleistung einer ordnungsgemäßen Ausbildung", "correct": true, "because": "§ 14 Abs. 1 BBiG dient diesem Zweck"}, {"text": "Kostensenkung für den Betrieb", "correct": false, "because": "Kein Ziel"}, {"text": "Vermeidung von Berufsschule", "correct": false, "because": "Kein Zusammenhang"}]');

-- Multiple-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welche Arbeitsmittel muss ein Arbeitgeber gemäß § 14 Abs. 1 BBiG bereitstellen?', 4, '[{"text": "Computer für Fachinformatiker", "correct": true, "because": "Notwendig für Ausbildung"}, {"text": "Schutzkleidung bei Bedarf", "correct": true, "because": "Arbeitsschutzrelevant"}, {"text": "Privates Handy", "correct": false, "because": "Kein Arbeitsmittel"}, {"text": "Softwarelizenzen", "correct": true, "because": "Teil der Ausbildung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten umfasst die Bereitstellung von Arbeitsmitteln?', 3, '[{"text": "Bereitstellung funktionsfähiger Geräte", "correct": true, "because": "§ 14 Abs. 1 BBiG"}, {"text": "Wartung der Arbeitsmittel", "correct": true, "because": "Impliziert durch Bereitstellung"}, {"text": "Kostenübernahme durch Auszubildende", "correct": false, "because": "Nicht erlaubt"}, {"text": "Anpassung an Ausbildungsbedarf", "correct": true, "because": "Zweck der Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen hat die Nichtbereitstellung von Arbeitsmitteln?', 4, '[{"text": "Verstoß gegen § 14 Abs. 1 BBiG", "correct": true, "because": "Pflichtverletzung"}, {"text": "Beeinträchtigung der Ausbildung", "correct": true, "because": "Fehlende Mittel schaden"}, {"text": "Höhere Vergütung", "correct": false, "because": "Keine Folge"}, {"text": "Mögliche Sanktionen durch Behörden", "correct": true, "because": "Gewerbeaufsicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche gesetzlichen Grundlagen regeln die Bereitstellung von Arbeitsmitteln?', 3, '[{"text": "§ 14 Abs. 1 BBiG", "correct": true, "because": "Kernvorschrift"}, {"text": "Arbeitsschutzgesetz (ArbSchG)", "correct": true, "because": "Ergänzt Sicherheit"}, {"text": "Kündigungsschutzgesetz (KSchG)", "correct": false, "because": "Kein Zusammenhang"}, {"text": "Jugendarbeitsschutzgesetz (JArbSchG)", "correct": true, "because": "Schutz junger Arbeitnehmer"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Pflicht des Arbeitgebers bei Arbeitsmitteln?', 3, '[{"text": "Kostenübernahme", "correct": true, "because": "§ 14 Abs. 1 BBiG"}, {"text": "Bereitstellung vor Ausbildungsbeginn", "correct": true, "because": "Notwendig für Start"}, {"text": "Auszubildende zahlen anteilig", "correct": false, "because": "Nicht erlaubt"}, {"text": "Sicherstellung der Funktionalität", "correct": true, "because": "Teil der Pflicht"}]');

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Der Arbeitgeber muss Arbeitsmittel bereitstellen. b) Auszubildende tragen die Kosten dafür.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) § 14 Abs. 1 BBiG, b) falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Arbeitsmittel müssen funktionsfähig sein. b) Der Arbeitgeber kann die Bereitstellung verweigern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (§ 14 Abs. 1 BBiG)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) § 14 Abs. 1 BBiG regelt die Bereitstellung von Arbeitsmitteln. b) Die Pflicht gilt nur für große Betriebe.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (gilt allgemein)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Arbeitsmittel dienen der Ausbildung. b) Die Berufsschule stellt sie bereit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (§ 14 Abs. 1 BBiG)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Nichtbereitstellung kann sanktioniert werden. b) Arbeitsmittel müssen den Ausbildungsanforderungen entsprechen.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "a) sanktionierbar, b) § 14 Abs. 1 BBiG"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]');

