-- Arbeitsrecht Berufsbildung > Pflichten von Arbeitgebern > Zeugnis ausstellen (§ 16 BBiG)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Muss ein Ausbildungsbetrieb einem Fachinformatiker bei Beendigung ein Zeugnis ausstellen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 16 BBiG verpflichtet den Betrieb dazu"}, {"text": "Nein", "correct": false, "because": "Zeugnis ist gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Betrieb das Zeugnis eines Fachinformatikers verweigern, wenn er die Ausbildung abbricht?', 2, '[{"text": "Nein", "correct": true, "because": "§ 16 BBiG gilt bei jeder Beendigung"}, {"text": "Ja", "correct": false, "because": "Zeugnis ist unabhängig vom Grund"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss das Zeugnis eines Fachinformatikers die Dauer der Ausbildung enthalten?', 2, '[{"text": "Ja", "correct": true, "because": "§ 16 BBiG fordert wesentliche Angaben"}, {"text": "Nein", "correct": false, "because": "Dauer ist Pflichtangabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Darf ein Ausbildungsbetrieb ein Zeugnis eines Fachinformatikers nur mündlich ausstellen?', 2, '[{"text": "Nein", "correct": true, "because": "§ 16 BBiG impliziert Schriftform"}, {"text": "Ja", "correct": false, "because": "Schriftform ist üblich und erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Fachinformatiker ein qualifiziertes Zeugnis mit Leistungsbeurteilung verlangen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 16 BBiG erlaubt dies auf Wunsch"}, {"text": "Nein", "correct": false, "because": "Qualifiziertes Zeugnis ist möglich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche gesetzliche Grundlage verpflichtet einen Betrieb, einem Fachinformatiker ein Zeugnis auszustellen?', 2, '[{"text": "§ 16 BBiG", "correct": true, "because": "Regelt die Zeugnispflicht"}, {"text": "§ 14 BBiG", "correct": false, "because": "Bezieht sich auf andere Pflichten"}, {"text": "§ 17 BBiG", "correct": false, "because": "Regelt die Vergütung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was muss ein Zeugnis für einen Fachinformatiker zwingend enthalten?', 3, '[{"text": "Dauer und Art der Ausbildung", "correct": true, "because": "§ 16 BBiG fordert wesentliche Angaben"}, {"text": "Nur die Unterschrift des Betriebs", "correct": false, "because": "Zu wenig Information"}, {"text": "Persönliche Hobbys", "correct": false, "because": "Nicht vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer ist verpflichtet, einem Fachinformatiker ein Zeugnis auszustellen?', 2, '[{"text": "Der Ausbildungsbetrieb", "correct": true, "because": "§ 16 BBiG legt dies fest"}, {"text": "Die IHK", "correct": false, "because": "IHK stellt Prüfungszeugnisse aus"}, {"text": "Die Berufsschule", "correct": false, "because": "Schule hat keine Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Betrieb einem Fachinformatiker kein Zeugnis ausstellt?', 3, '[{"text": "Der Auszubildende kann es einklagen", "correct": true, "because": "§ 16 BBiG ist einklagbar"}, {"text": "Die IHK übernimmt die Ausstellung", "correct": false, "because": "IHK ist nicht zuständig"}, {"text": "Der Anspruch verfällt", "correct": false, "because": "Recht bleibt bestehen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Art von Zeugnis kann ein Fachinformatiker auf Wunsch erhalten?', 3, '[{"text": "Ein qualifiziertes Zeugnis mit Leistungsbeurteilung", "correct": true, "because": "§ 16 BBiG erlaubt dies"}, {"text": "Ein Zeugnis ohne Angaben", "correct": false, "because": "Mindestangaben sind Pflicht"}, {"text": "Ein mündliches Zeugnis", "correct": false, "because": "Schriftform ist Standard"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Angaben muss ein Zeugnis für einen Fachinformatiker gemäß § 16 BBiG enthalten?', 4, '[{"text": "Dauer der Ausbildung", "correct": true, "because": "Wesentlich nach § 16 BBiG"}, {"text": "Art der Ausbildung", "correct": true, "because": "Pflichtangabe"}, {"text": "Private Interessen", "correct": false, "because": "Nicht relevant"}, {"text": "Berufsschulnoten", "correct": false, "because": "Nicht vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat ein Betrieb bei der Zeugnisausstellung für einen Fachinformatiker?', 3, '[{"text": "Zeugnis bei Beendigung ausstellen", "correct": true, "because": "§ 16 BBiG fordert dies"}, {"text": "Wahrheitsgemäße Angaben machen", "correct": true, "because": "Gesetzlich vorgeschrieben"}, {"text": "Nur mündlich ausstellen", "correct": false, "because": "Schriftform ist Standard"}, {"text": "Leistungsbeurteilung auf Wunsch", "correct": true, "because": "Möglich nach § 16 BBiG"}]'),
('00000000-0000-0000-0000-000000000000', 'Was darf ein Betrieb im Zeugnis eines Fachinformatikers nicht angeben?', 3, '[{"text": "Private Krankheitsdetails", "correct": true, "because": "Datenschutzrechtlich verboten"}, {"text": "Falsche Angaben", "correct": true, "because": "Zeugnis muss wahrheitsgemäß sein"}, {"text": "Dauer der Ausbildung", "correct": false, "because": "Pflichtangabe"}, {"text": "Leistungsbeurteilung", "correct": false, "because": "Auf Wunsch zulässig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen drohen einem Betrieb, der kein Zeugnis für einen Fachinformatiker ausstellt?', 4, '[{"text": "Klage des Auszubildenden", "correct": true, "because": "§ 16 BBiG ist einklagbar"}, {"text": "Verwarnung durch die IHK", "correct": true, "because": "IHK kann einschreiten"}, {"text": "Automatische Schließung", "correct": false, "because": "Nicht vorgesehen"}, {"text": "Schadensersatzforderungen", "correct": true, "because": "Bei Verletzung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'In welchen Fällen muss ein Betrieb einem Fachinformatiker ein Zeugnis ausstellen?', 3, '[{"text": "Bei regulärem Ausbildungsende", "correct": true, "because": "§ 16 BBiG gilt bei Beendigung"}, {"text": "Bei Kündigung durch den Betrieb", "correct": true, "because": "Unabhängig vom Grund"}, {"text": "Nur bei Bestehen der IHK-Prüfung", "correct": false, "because": "Nicht an Prüfung gebunden"}, {"text": "Bei Abbruch durch den Auszubildenden", "correct": true, "because": "Jede Beendigung zählt"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ein Betrieb muss einem Fachinformatiker ein Zeugnis ausstellen. b) Das Zeugnis muss nur die Unterschrift enthalten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeugnis Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Das Zeugnis eines Fachinformatikers muss die Ausbildungsdauer enthalten. b) Leistungsbeurteilung ist immer Pflicht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dauer Pflicht, Beurteilung optional"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Betrieb muss ein Zeugnis auch bei Kündigung ausstellen. b) Das Zeugnis darf mündlich sein.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kündigung zählt, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Ein Fachinformatiker kann ein qualifiziertes Zeugnis verlangen. b) Der Betrieb muss private Daten im Zeugnis angeben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Qualifiziertes Zeugnis möglich, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) § 16 BBiG verpflichtet den Betrieb zur Zeugnisausstellung. b) Ein Zeugnis ist nur bei erfolgreicher Ausbildung erforderlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeugnis Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

