-- Ja/Nein-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Darf ein Arbeitgeber gemäß § 14 Abs. 2 BBiG die Berufsschulzeugnisse eines Auszubildenden einsehen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 14 Abs. 2 BBiG gewährt das Einsichtsrecht"}, {"text": "Nein", "correct": false, "because": "Einsicht ist gesetzlich erlaubt"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Arbeitgeber die Zustimmung des Auszubildenden einholen, um Berufsschulzeugnisse einzusehen?', 2, '[{"text": "Ja", "correct": false, "because": "§ 14 Abs. 2 BBiG verlangt keine Zustimmung"}, {"text": "Nein", "correct": true, "because": "Recht ist uneingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Dient die Einsicht in Berufsschulzeugnisse der Überprüfung der Ausbildungsfortschritte?', 2, '[{"text": "Ja", "correct": true, "because": "Zweck ist die Kontrolle des Lernfortschritts"}, {"text": "Nein", "correct": false, "because": "Überprüfung ist Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Auszubildender dem Arbeitgeber die Berufsschulzeugnisse vorlegen?', 2, '[{"text": "Ja", "correct": true, "because": "Pflicht ergibt sich aus § 14 Abs. 2 BBiG"}, {"text": "Nein", "correct": false, "because": "Vorlage ist verpflichtend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Arbeitgeber die Einsicht in Berufsschulzeugnisse nutzen, um die Vergütung anzupassen?', 2, '[{"text": "Ja", "correct": false, "because": "Vergütung ist unabhängig geregelt (§ 17 BBiG)"}, {"text": "Nein", "correct": true, "because": "Keine Verbindung zur Vergütung"}]');

-- Single-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz regelt das Recht des Arbeitgebers auf Einsicht in Berufsschulzeugnisse?', 2, '[{"text": "§ 14 Abs. 2 BBiG", "correct": true, "because": "Regelt dieses Recht"}, {"text": "§ 13 BBiG", "correct": false, "because": "Regelt Pflichten der Auszubildenden"}, {"text": "ArbSchG", "correct": false, "because": "Regelt Arbeitsschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist der Hauptzweck der Einsicht in Berufsschulzeugnisse durch den Arbeitgeber?', 3, '[{"text": "Überprüfung der Ausbildungsfortschritte", "correct": true, "because": "Dient der Kontrolle"}, {"text": "Festlegung der Arbeitszeiten", "correct": false, "because": "Kein Zusammenhang"}, {"text": "Anpassung der Vergütung", "correct": false, "because": "Nicht zweckgebunden"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer hat gemäß § 14 Abs. 2 BBiG das Recht auf Einsicht in Berufsschulzeugnisse?', 2, '[{"text": "Der Arbeitgeber", "correct": true, "because": "Gesetzlich festgelegt"}, {"text": "Die Berufsschule", "correct": false, "because": "Keine Einsichtsbefugnis"}, {"text": "Die Eltern des Auszubildenden", "correct": false, "because": "Keine Rolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz kann ein Arbeitgeber ziehen, wenn die Berufsschulzeugnisse schlecht sind?', 3, '[{"text": "Zusätzliche Ausbildungsmaßnahmen anordnen", "correct": true, "because": "Förderung des Lernens möglich"}, {"text": "Sofortige Kündigung", "correct": false, "because": "Kündigung hat andere Voraussetzungen"}, {"text": "Vergütung kürzen", "correct": false, "because": "Nicht zulässig"}]'),
('00000000-0000-0000-0000-000000000000', 'In welchem Abschnitt des BBiG ist die Einsicht in Berufsschulzeugnisse geregelt?', 2, '[{"text": "§ 14 Abs. 2", "correct": true, "because": "Dort ist das Recht festgelegt"}, {"text": "§ 15 BBiG", "correct": false, "because": "Regelt Berufsschulbesuch"}, {"text": "§ 17 BBiG", "correct": false, "because": "Regelt Vergütung"}]');

-- Multiple-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welche Rechte hat ein Arbeitgeber in Bezug auf Berufsschulzeugnisse?', 4, '[{"text": "Einsicht verlangen", "correct": true, "because": "§ 14 Abs. 2 BBiG"}, {"text": "Vorlage einfordern", "correct": true, "because": "Pflicht des Auszubildenden"}, {"text": "Zeugnisse ändern", "correct": false, "because": "Keine Befugnis"}, {"text": "Noten überprüfen", "correct": true, "because": "Teil der Einsicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Zwecke verfolgt die Einsicht in Berufsschulzeugnisse?', 3, '[{"text": "Kontrolle der Lernfortschritte", "correct": true, "because": "Hauptzweck"}, {"text": "Förderung der Ausbildung", "correct": true, "because": "Maßnahmen möglich"}, {"text": "Festlegung der Urlaubszeiten", "correct": false, "because": "Kein Zusammenhang"}, {"text": "Bewertung der Leistung", "correct": true, "because": "Teil der Kontrolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten ergeben sich für den Auszubildenden aus dem Einsichtsrecht?', 4, '[{"text": "Vorlage der Zeugnisse", "correct": true, "because": "§ 14 Abs. 2 BBiG"}, {"text": "Verbesserung der Noten", "correct": false, "because": "Keine direkte Pflicht"}, {"text": "Mitteilung an den Arbeitgeber", "correct": true, "because": "Teil der Mitwirkung"}, {"text": "Kopien anfertigen", "correct": false, "because": "Nicht vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche gesetzlichen Grundlagen regeln das Einsichtsrecht in Berufsschulzeugnisse?', 3, '[{"text": "§ 14 Abs. 2 BBiG", "correct": true, "because": "Kernvorschrift"}, {"text": "Berufsbildungsgesetz (BBiG) allgemein", "correct": true, "because": "Rahmenrecht"}, {"text": "KSchG", "correct": false, "because": "Regelt Kündigungsschutz"}, {"text": "§ 15 BBiG", "correct": false, "because": "Regelt Berufsschulbesuch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen kann ein Arbeitgeber bei schlechten Zeugnissen ergreifen?', 3, '[{"text": "Zusätzliche Schulungen anordnen", "correct": true, "because": "Fördermaßnahme"}, {"text": "Nachhilfe organisieren", "correct": true, "because": "Unterstützung möglich"}, {"text": "Vergütung kürzen", "correct": false, "because": "Nicht zulässig"}, {"text": "Gespräch mit dem Auszubildenden führen", "correct": true, "because": "Klärung möglich"}]');

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Der Arbeitgeber darf Berufsschulzeugnisse einsehen. b) Der Auszubildende kann dies verweigern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) § 14 Abs. 2 BBiG, b) falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Einsicht dient der Kontrolle der Ausbildung. b) Der Arbeitgeber darf die Noten ändern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (keine Befugnis)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) § 14 Abs. 2 BBiG regelt das Einsichtsrecht. b) Es dient der Vergütungsanpassung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (kein Zusammenhang)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Der Auszubildende muss Zeugnisse vorlegen. b) Die Einsicht ist freiwillig für den Arbeitgeber.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) Pflicht, b) falsch (Recht des Arbeitgebers)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Schlechte Zeugnisse können Maßnahmen auslösen. b) Das Einsichtsrecht ist im BBiG geregelt.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "a) Maßnahmen möglich, b) § 14 Abs. 2 BBiG"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]');

