-- Leistungsangebot.sql (Dienstleistungen und Produkte, die ein IT-Unternehmen anbietet)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein IT-Leistungsangebot immer Hardware umfassen muss. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Software oder Dienstleistungen möglich"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich ein Leistungsangebot für IT-Kunden erstelle?', 3, '[{"text": "Kundenbedürfnisse", "correct": true, "because": "Steuert Angebot"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Qualität wichtiger"}, {"text": "Bunte Werbung", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören typischerweise zu einem IT-Leistungsangebot?', 5, '[{"text": "Support-Dienste", "correct": true, "because": "Wichtig für Kunden"}, {"text": "Softwarelösungen", "correct": true, "because": "Häufiger Bestandteil"}, {"text": "Büroausstattung", "correct": false, "because": "Kein IT-Fokus"}, {"text": "Marketingpläne", "correct": false, "because": "Nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Leistungsangebot muss flexibel sein. b) Es umfasst immer Hardwareverkauf.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware nicht zwingend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein Leistungsangebot für IT-Dienstleistungen plane?', 4, '[{"text": "Kundenanforderungen", "correct": false, "because": "Grundlage des Angebots"}, {"text": "Servicelevel", "correct": false, "because": "Definiert Qualität"}, {"text": "Bürodeko", "correct": true, "because": "Kein Leistungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Leistungsangebot immer standardisiert sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "Kann individuell angepasst werden"}, {"text": "Ja", "correct": false, "because": "Flexibilität möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem IT-Leistungsangebot?', 3, '[{"text": "Kundenzufriedenheit", "correct": true, "because": "Erfüllt Bedarf"}, {"text": "Schnellste Lieferung", "correct": false, "because": "Sekundär"}, {"text": "Weniger Angebot", "correct": false, "because": "Kein Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bestandteile sind für ein IT-Leistungsangebot entscheidend?', 5, '[{"text": "Technische Dienstleistungen", "correct": true, "because": "Kern der IT"}, {"text": "Supportverträge", "correct": true, "because": "Sichern Betrieb"}, {"text": "Bürogestaltung", "correct": false, "because": "Kein IT-Fokus"}, {"text": "Marketingtexte", "correct": false, "because": "Nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Leistungsangebot umfasst Support. b) Es ist immer kostenlos. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kostenlosigkeit unrealistisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein IT-Leistungsangebot?', 4, '[{"text": "Kundenanalyse", "correct": false, "because": "Definiert Bedarf"}, {"text": "Servicebeschreibung", "correct": false, "because": "Kern des Angebots"}, {"text": "Farbcodierung", "correct": true, "because": "Kein Leistungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ein Leistungsangebot immer Hardware enthalten?', 2, '[{"text": "Nein", "correct": true, "because": "Auch reine Dienstleistungen möglich"}, {"text": "Ja", "correct": false, "because": "Zu restriktiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein umfassendes IT-Leistungsangebot?', 4, '[{"text": "Kundenzufriedenheit", "correct": true, "because": "Erfüllt Bedarf"}, {"text": "Wettbewerbsvorteil", "correct": true, "because": "Hebt sich ab"}, {"text": "Hohe Kosten", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Leistungsangebot nur technische Dienste umfasst. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Beratung möglich"}, {"text": "Ja", "correct": false, "because": "Zu eng gefasst"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um ein Leistungsangebot für IT-Support zu erstellen?', 3, '[{"text": "Service-Level-Agreement", "correct": true, "because": "Definiert Leistung"}, {"text": "Teure Hardware", "correct": false, "because": "Nicht primär"}, {"text": "Bunte Flyer", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Leistungsangebot passt sich Kunden an. b) Es ist immer standardisiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kann individuell sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei einem IT-Leistungsangebot?', 5, '[{"text": "Kundenanforderungen", "correct": true, "because": "Definiert Umfang"}, {"text": "Kostenkalkulation", "correct": true, "because": "Sichert Rentabilität"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Firmenfarben", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich ein Leistungsangebot für IT-Dienste erstelle?', 3, '[{"text": "Leistungsbeschreibung", "correct": false, "because": "Kern des Angebots"}, {"text": "Kundensegmente", "correct": false, "because": "Richtet Angebot aus"}, {"text": "Dekoration", "correct": true, "because": "Kein Leistungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ein Leistungsangebot immer Produkte enthalten?', 3, '[{"text": "Nein", "correct": true, "because": "Auch reine Dienste möglich"}, {"text": "Ja", "correct": false, "because": "Zu restriktiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Leistungsangebot nur technische Lösungen bietet?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Beratung enthalten"}, {"text": "Ja", "correct": false, "because": "Zu eng gefasst"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für ein IT-Leistungsangebot?', 4, '[{"text": "Kundenorientierung", "correct": true, "because": "Passt an Bedarf an"}, {"text": "Schnellste Umsetzung", "correct": false, "because": "Qualität zählt"}, {"text": "Bunte Präsentation", "correct": false, "because": "Irrelevant"}]');

