-- Lenkungsausschuss.sql (Steuerungsgremium für IT-Projekte)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Lenkungsausschuss immer technische Experten sein müssen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Management vertreten"}, {"text": "Ja", "correct": false, "because": "Nicht nur Techniker"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich einen Lenkungsausschuss für ein IT-Projekt einrichte?', 3, '[{"text": "Projektsteuerung", "correct": true, "because": "Sichert Zielerreichung"}, {"text": "Schnelle Einrichtung", "correct": false, "because": "Kompetenz wichtiger"}, {"text": "Bürodesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben hat ein Lenkungsausschuss in einem IT-Projekt?', 5, '[{"text": "Entscheidungsfindung", "correct": true, "because": "Leitet Projekt"}, {"text": "Ressourcenzuweisung", "correct": true, "because": "Sichert Mittel"}, {"text": "Code schreiben", "correct": false, "because": "Technische Umsetzung"}, {"text": "Büroplanung", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Lenkungsausschuss überwacht den Projektfortschritt. b) Er führt die operative Arbeit aus.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Operative Arbeit separat"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich einen Lenkungsausschuss für ein IT-Projekt zusammenstelle?', 4, '[{"text": "Projektziele", "correct": false, "because": "Leiten Entscheidungen"}, {"text": "Stakeholder", "correct": false, "because": "Wichtig für Vertretung"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Steuerungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Lenkungsausschuss nur für große Projekte nötig ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für kleine Projekte nützlich"}, {"text": "Ja", "correct": false, "because": "Skalierbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Lenkungsausschuss?', 3, '[{"text": "Projekterfolg sichern", "correct": true, "because": "Überwacht und steuert"}, {"text": "Schnellste Umsetzung", "correct": false, "because": "Qualität zählt"}, {"text": "Weniger Kontrolle", "correct": false, "because": "Fördert Kontrolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rollen sind typisch für einen Lenkungsausschuss?', 5, '[{"text": "Projektleitung", "correct": true, "because": "Koordiniert Prozess"}, {"text": "Management", "correct": true, "because": "Stellt Ressourcen"}, {"text": "Programmierer", "correct": false, "because": "Operative Ebene"}, {"text": "Designer", "correct": false, "because": "Nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Lenkungsausschuss trifft strategische Entscheidungen. b) Er ist immer technisch fokussiert. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Technik nicht primär"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen Lenkungsausschuss?', 4, '[{"text": "Entscheidungsbefugnis", "correct": false, "because": "Kernaufgabe"}, {"text": "Projektübersicht", "correct": false, "because": "Basis für Steuerung"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein Steuerungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Lenkungsausschuss immer für jedes Projekt nötig?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Projektgröße"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Lenkungsausschuss?', 4, '[{"text": "Klare Entscheidungen", "correct": true, "because": "Vermeidet Stillstand"}, {"text": "Ressourcensteuerung", "correct": true, "because": "Sichert Mittel"}, {"text": "Schnellere Umsetzung", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Lenkungsausschuss nur technische Fragen klärt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch strategisch aktiv"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um einen Lenkungsausschuss für ein IT-Projekt effektiv zu machen?', 3, '[{"text": "Kompetente Mitglieder", "correct": true, "because": "Sichert Expertise"}, {"text": "Schnelle Meetings", "correct": false, "because": "Qualität wichtiger"}, {"text": "Bunte Präsentationen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Lenkungsausschuss überwacht Risiken. b) Er ersetzt das Projektteam.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Team bleibt operativ"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen einen Lenkungsausschuss effektiv?', 5, '[{"text": "Klare Verantwortlichkeiten", "correct": true, "because": "Sichert Struktur"}, {"text": "Regelmäßige Treffen", "correct": true, "because": "Hält Überblick"}, {"text": "Büroausstattung", "correct": false, "because": "Irrelevant"}, {"text": "Marketingziele", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich einen Lenkungsausschuss einrichte?', 3, '[{"text": "Projektziele", "correct": false, "because": "Leiten Entscheidungen"}, {"text": "Kompetenz", "correct": false, "because": "Sichert Erfolg"}, {"text": "Farbschema", "correct": true, "because": "Kein Steuerungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Lenkungsausschuss immer groß besetzt?', 3, '[{"text": "Nein", "correct": true, "because": "Kann klein und effizient sein"}, {"text": "Ja", "correct": false, "because": "Größe variabel"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Lenkungsausschuss technische Umsetzung plant?', 2, '[{"text": "Nein", "correct": true, "because": "Fokus auf Steuerung"}, {"text": "Ja", "correct": false, "because": "Operative Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für einen Lenkungsausschuss?', 4, '[{"text": "Entscheidungsbefugnis", "correct": true, "because": "Ermöglicht Steuerung"}, {"text": "Schnelle Einrichtung", "correct": false, "because": "Qualität zählt"}, {"text": "Bürodesign", "correct": false, "because": "Irrelevant"}]');

