-- Lohnsteuer.sql (Steuer auf Arbeitseinkommen und deren Bedeutung in der IT-Branche)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Lohnsteuer nur für IT-Mitarbeiter gilt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle Arbeitnehmer"}, {"text": "Ja", "correct": false, "because": "Nicht branchenspezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich Lohnsteuer in einer IT-Firma abrechne?', 3, '[{"text": "Korrekte Steuerklasse", "correct": true, "because": "Bestimmt Abzug"}, {"text": "Schnellste Abrechnung", "correct": false, "because": "Genauigkeit zählt"}, {"text": "Firmendesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Lohnsteuer für IT-Mitarbeiter?', 5, '[{"text": "Gehaltshöhe", "correct": true, "because": "Bestimmt Steuersatz"}, {"text": "Steuerklasse", "correct": true, "because": "Beeinflusst Abzug"}, {"text": "Bürogröße", "correct": false, "because": "Kein Faktor"}, {"text": "Hardwarekosten", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Lohnsteuer wird vom Arbeitgeber abgeführt. b) Sie ist immer gleich hoch.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Höhe variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich Lohnsteuer für IT-Mitarbeiter berechne?', 4, '[{"text": "Steuerfreibeträge", "correct": false, "because": "Beeinflussen Abzug"}, {"text": "Einkommenshöhe", "correct": false, "because": "Bestimmt Steuer"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Steuerfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Lohnsteuer nur für Festangestellte gilt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für andere Einkünfte"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich, wenn ich Lohnsteuer in einer IT-Firma korrekt abrechne?', 3, '[{"text": "Gesetzeskonformität", "correct": true, "because": "Vermeidet Strafen"}, {"text": "Schnellste Auszahlung", "correct": false, "because": "Genauigkeit wichtiger"}, {"text": "Weniger Steuer", "correct": false, "because": "Kein Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bestandteile sind bei der Lohnsteuerabrechnung in der IT entscheidend?', 5, '[{"text": "Bruttogehalt", "correct": true, "because": "Basis der Berechnung"}, {"text": "Steuerklasse", "correct": true, "because": "Bestimmt Abzug"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Hardwareausstattung", "correct": false, "because": "Kein Steuerfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Lohnsteuer wird monatlich abgeführt. b) Sie gilt nur für hohe Gehälter. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Gilt für alle Einkünfte"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Lohnsteuerabrechnung in einer IT-Firma?', 4, '[{"text": "Steuer-ID", "correct": false, "because": "Identifiziert Mitarbeiter"}, {"text": "Gehaltsdaten", "correct": false, "because": "Basis der Berechnung"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Steuerfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Wird Lohnsteuer direkt vom Mitarbeiter gezahlt?', 2, '[{"text": "Nein", "correct": true, "because": "Arbeitgeber führt ab"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine korrekte Lohnsteuerabrechnung?', 4, '[{"text": "Rechtssicherheit", "correct": true, "because": "Vermeidet Probleme"}, {"text": "Mitarbeiterzufriedenheit", "correct": true, "because": "Klare Abrechnung"}, {"text": "Schnellere Projekte", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Lohnsteuer nur für IT-Firmen relevant ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle Branchen"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um Lohnsteuer in einer IT-Firma korrekt zu berechnen?', 3, '[{"text": "Steuerprogramm", "correct": true, "because": "Automatisiert Berechnung"}, {"text": "Schnellste Software", "correct": false, "because": "Genauigkeit wichtiger"}, {"text": "Bunte Tabellen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Lohnsteuer hängt vom Einkommen ab. b) Sie wird jährlich abgeführt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Monatlich abgeführt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei der Lohnsteuer in einer IT-Firma?', 5, '[{"text": "Steuerfreibeträge", "correct": true, "because": "Beeinflussen Abzug"}, {"text": "Sozialabgaben", "correct": true, "because": "Teil der Abrechnung"}, {"text": "Büroausstattung", "correct": false, "because": "Irrelevant"}, {"text": "Firmenfarben", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich Lohnsteuer für IT-Mitarbeiter berechne?', 3, '[{"text": "Einkommenshöhe", "correct": false, "because": "Bestimmt Steuer"}, {"text": "Steuerklasse", "correct": false, "because": "Beeinflusst Abzug"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein Steuerfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Wird Lohnsteuer nur für Vollzeitkräfte erhoben?', 3, '[{"text": "Nein", "correct": true, "because": "Auch für Teilzeit"}, {"text": "Ja", "correct": false, "because": "Gilt für alle"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Lohnsteuer direkt ans Finanzamt geht?', 2, '[{"text": "Ja", "correct": true, "because": "Arbeitgeber führt ab"}, {"text": "Nein", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für die Lohnsteuerabrechnung?', 4, '[{"text": "Korrekte Daten", "correct": true, "because": "Sichert Genauigkeit"}, {"text": "Schnellste Auszahlung", "correct": false, "because": "Genauigkeit wichtiger"}, {"text": "Büroausstattung", "correct": false, "because": "Irrelevant"}]');


