-- Paketverlust (Ursachen, ICMPv6-Fehler).sql
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Paketverlust immer ein Hardwareproblem?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Software oder Netzwerk"}, {"text": "Ja", "correct": false, "because": "Mehrere Ursachen möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool zeigt Paketverlust an?', 3, '[{"text": "ping", "correct": true, "because": "Prozentualer Verlust"}, {"text": "ifconfig", "correct": false, "because": "Nur Konfiguration"}, {"text": "dhclient", "correct": false, "because": "Adresszuweisung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ursachen führen zu Paketverlust?', 5, '[{"text": "Netzwerküberlastung", "correct": true, "because": "Überfüllte Queues"}, {"text": "Fehlerhafte Hardware", "correct": true, "because": "Defekte Kabel oder Ports"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Fördert nicht Verlust"}, {"text": "DNS-Fehler", "correct": false, "because": "Andere Ebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) ICMPv6 meldet Paketverlust. b) Er ist immer vermeidbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verlust oft unvermeidbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Analyse von Paketverlust?', 4, '[{"text": "ICMPv6-Fehler", "correct": false, "because": "Zeigt Probleme"}, {"text": "Netzwerküberlastung", "correct": false, "because": "Häufige Ursache"}, {"text": "Webserver-Logs", "correct": true, "because": "Nicht Netzwerk-relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Paketverlust nur bei Multicast auftritt?', 2, '[{"text": "Nein", "correct": true, "because": "Betrifft alle Kommunikation"}, {"text": "Ja", "correct": false, "because": "Nicht Multicast-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher ICMPv6-Fehler zeigt Paketverlust an?', 3, '[{"text": "Destination Unreachable", "correct": true, "because": "Ziel nicht erreichbar"}, {"text": "Echo Reply", "correct": false, "because": "Erfolgreiche Antwort"}, {"text": "Router Advertisement", "correct": false, "because": "SLAAC-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche ICMPv6-Meldungen deuten auf Probleme hin?', 5, '[{"text": "Time Exceeded", "correct": true, "because": "Hop-Limit überschritten"}, {"text": "Destination Unreachable", "correct": true, "because": "Ziel nicht erreichbar"}, {"text": "Echo Request", "correct": false, "because": "Nur Anfrage"}, {"text": "Neighbor Solicitation", "correct": false, "because": "NDP-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Paketverlust wird durch ICMPv6 gemeldet. b) Er tritt nur bei IPv6 auf. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch bei IPv4 möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht zur Analyse von Paketverlust?', 4, '[{"text": "Ping-Ergebnisse", "correct": false, "because": "Zeigt Verlust"}, {"text": "ICMPv6-Meldungen", "correct": false, "because": "Gibt Hinweise"}, {"text": "DNS-Cache", "correct": true, "because": "Nicht Netzwerk-relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Paketverlust immer sichtbar?', 2, '[{"text": "Nein", "correct": true, "because": "Firewalls können verbergen"}, {"text": "Ja", "correct": false, "because": "Nicht immer nachweisbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ursache könnte ein Time Exceeded Fehler haben?', 4, '[{"text": "Routing-Schleife", "correct": true, "because": "Hop-Limit erreicht"}, {"text": "Echo Reply ausbleibt", "correct": false, "because": "Anderer Fehler"}, {"text": "DNS-Ausfall", "correct": false, "because": "Nicht ICMPv6"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Paketverlust nur durch Überlastung entsteht. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Hardware oder Config"}, {"text": "Ja", "correct": false, "because": "Mehrere Ursachen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Paketverlust-Analyse?', 3, '[{"text": "ICMPv6-Fehler", "correct": true, "because": "Gibt Hinweise"}, {"text": "Webserver-Status", "correct": false, "because": "Sekundär"}, {"text": "DNS-Einträge", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Paketverlust zeigt Netzwerkprobleme. b) ICMPv6 verhindert ihn.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "ICMPv6 meldet nur"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ICMPv6 bei Paketverlust?', 5, '[{"text": "Fehlerdiagnose", "correct": true, "because": "Meldet Probleme"}, {"text": "Ursachenlokalisierung", "correct": true, "because": "z. B. Time Exceeded"}, {"text": "Verlustvermeidung", "correct": false, "because": "Nur Meldung"}, {"text": "Datenkompression", "correct": false, "because": "Nicht ICMPv6"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Paketverlust unwichtig?', 3, '[{"text": "Netzwerküberlastung", "correct": false, "because": "Häufige Ursache"}, {"text": "ICMPv6-Meldungen", "correct": false, "because": "Diagnosehilfe"}, {"text": "Web-UI-Design", "correct": true, "because": "Nicht Netzwerk-relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann Paketverlust durch Firewalls versteckt werden?', 3, '[{"text": "Ja", "correct": true, "because": "Blockiert ICMPv6"}, {"text": "Nein", "correct": false, "because": "Häufiger Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Paketverlust Latenz erhöht?', 2, '[{"text": "Nein", "correct": true, "because": "Unabhängige Probleme"}, {"text": "Ja", "correct": false, "because": "Verwechselt Effekte"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Fehler zeigt, dass ein Ziel nicht erreichbar ist?', 4, '[{"text": "Destination Unreachable", "correct": true, "because": "ICMPv6-Meldung"}, {"text": "Echo Reply", "correct": false, "because": "Erfolgreiche Antwort"}, {"text": "Router Solicitation", "correct": false, "because": "NDP-spezifisch"}]');

