-- Projektmanagement: SMART-Prinzip - Attraktiv
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist "attraktiv" ein Kriterium des SMART-Prinzips?', 2, '[{"text": "Ja", "correct": true, "because": "Motivation ist Teil von SMART"}, {"text": "Nein", "correct": false, "because": "Es gehört dazu"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal beschreibt "attraktiv" im SMART-Prinzip?', 3, '[{"text": "Motivierend für Beteiligte", "correct": true, "because": "Fördert Engagement"}, {"text": "Uninteressant gestaltet", "correct": false, "because": "Widerspricht Attraktivität"}, {"text": "Ohne Zeitbezug", "correct": false, "because": "Anderes Kriterium"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Attraktive Ziele fördern Motivation. b) Attraktivität ist messbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist subjektiv, nicht messbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) trifft zu"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen ein Ziel attraktiv im SMART-Prinzip?', 4, '[{"text": "Persönlicher Nutzen", "correct": true, "because": "Steigert Motivation"}, {"text": "Langweilige Aufgaben", "correct": false, "because": "Senkt Attraktivität"}, {"text": "Erreichbare Herausforderung", "correct": true, "because": "Fördert Interesse"}, {"text": "Keine Belohnung", "correct": false, "because": "Verringert Anreiz"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Ziel ohne Attraktivität SMART sein?', 2, '[{"text": "Ja", "correct": true, "because": "Attraktivität ist subjektiv"}, {"text": "Nein", "correct": false, "because": "Andere Kriterien reichen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel ist nicht attraktiv im SMART-Prinzip?', 3, '[{"text": "Langweilige Routinearbeit", "correct": true, "because": "Fehlt Motivation"}, {"text": "Neue Software entwickeln", "correct": false, "because": "Kann ansprechend sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Attraktivität im SMART-Prinzip objektiv festgelegt?', 2, '[{"text": "Nein", "correct": true, "because": "Subjektiv vom Team abhängig"}, {"text": "Ja", "correct": false, "because": "Variiert individuell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt erhöht die Attraktivität eines Ziels?', 3, '[{"text": "Spannende Herausforderung", "correct": true, "because": "Fördert Engagement"}, {"text": "Monotone Aufgaben", "correct": false, "because": "Senkt Interesse"}, {"text": "Keine Anerkennung", "correct": false, "because": "Verringert Anreiz"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Attraktivität hängt vom Team ab. b) Attraktivität ist unwichtig im SMART-Prinzip.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Motivation zählt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was macht ein Ziel im SMART-Prinzip weniger attraktiv?', 3, '[{"text": "Fehlende Relevanz", "correct": true, "because": "Senkt Motivation"}, {"text": "Klarer Nutzen", "correct": false, "because": "Steigert Attraktivität"}, {"text": "Spannende Aufgabe", "correct": false, "because": "Fördert Interesse"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein technisches Ziel attraktiv sein?', 2, '[{"text": "Ja", "correct": true, "because": "Wenn es motiviert"}, {"text": "Nein", "correct": false, "because": "Hängt vom Kontext ab"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt ein attraktives SMART-Ziel?', 3, '[{"text": "Innovative App bis Q3 entwickeln", "correct": true, "because": "Spannend und klar"}, {"text": "Daten eintippen bis irgendwann", "correct": false, "because": "Langweilig und vage"}, {"text": "Server warten", "correct": false, "because": "Nicht motivierend"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Attraktivität im SMART-Prinzip immer notwendig?', 2, '[{"text": "Ja", "correct": true, "because": "Fördert Einsatz"}, {"text": "Nein", "correct": false, "because": "Es ist ein Kriterium"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente steigern die Attraktivität im SMART-Prinzip?', 4, '[{"text": "Sichtbare Erfolge", "correct": true, "because": "Motivieren Team"}, {"text": "Eintönige Arbeit", "correct": false, "because": "Senkt Interesse"}, {"text": "Kreativer Freiraum", "correct": true, "because": "Fördert Engagement"}, {"text": "Keine Rückmeldung", "correct": false, "because": "Demotiviert"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss Attraktivität im SMART-Prinzip für alle gleich sein?', 2, '[{"text": "Nein", "correct": true, "because": "Subjektiv unterschiedlich"}, {"text": "Ja", "correct": false, "because": "Individuell wahrgenommen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt Attraktivität im SMART-Prinzip?', 3, '[{"text": "Steigert Motivation", "correct": true, "because": "Fördert Einsatz"}, {"text": "Verlängert Zeit", "correct": false, "because": "Anderes Kriterium"}, {"text": "Erhöht Kosten", "correct": false, "because": "Unabhängig davon"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Ziel ohne Attraktivität motivieren?', 2, '[{"text": "Nein", "correct": true, "because": "Attraktivität treibt Einsatz"}, {"text": "Ja", "correct": false, "because": "Motivation leidet"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor mindert die Attraktivität eines Ziels?', 3, '[{"text": "Keine Relevanz für Team", "correct": true, "because": "Senkt Interesse"}, {"text": "Klarer Nutzen", "correct": false, "because": "Steigert Attraktivität"}, {"text": "Spannende Aufgabe", "correct": false, "because": "Fördert Motivation"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Attraktivität ist subjektiv. b) Attraktivität ist unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Motivation ist zentral"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Ziel der Attraktivität im SMART-Prinzip?', 3, '[{"text": "Team zum Handeln anregen", "correct": true, "because": "Fördert Engagement"}, {"text": "Zeit verlängern", "correct": false, "because": "Anderes Kriterium"}, {"text": "Kosten senken", "correct": false, "because": "Unabhängig davon"}]');

