-- Projektmanagement: SMART-Prinzip - Realistisch
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist "realistisch" ein Kriterium des SMART-Prinzips?', 2, '[{"text": "Ja", "correct": true, "because": "Teil der SMART-Definition"}, {"text": "Nein", "correct": false, "because": "Es gehört dazu"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal beschreibt "realistisch" im SMART-Prinzip?', 3, '[{"text": "Machbarkeit des Ziels", "correct": true, "because": "Realistisch heißt umsetzbar"}, {"text": "Unendliche Ressourcen", "correct": false, "because": "Nicht realistisch"}, {"text": "Keine Zeitvorgabe", "correct": false, "because": "Anderes Kriterium"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Realistische Ziele sind erreichbar. b) Realistisch bedeutet unmöglich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) widerspricht der Definition"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) trifft zu"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen ein Ziel realistisch?', 4, '[{"text": "Verfügbare Ressourcen", "correct": true, "because": "Bestimmen Machbarkeit"}, {"text": "Unendliche Zeit", "correct": false, "because": "Nicht realistisch"}, {"text": "Teamkapazität", "correct": true, "because": "Beeinflusst Umsetzung"}, {"text": "Klar definierte Schritte", "correct": true, "because": "Fördern Erreichbarkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Ziel ohne realistische Basis SMART sein?', 2, '[{"text": "Nein", "correct": true, "because": "Realistisch ist zwingend"}, {"text": "Ja", "correct": false, "because": "Widerspricht SMART"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel ist nicht realistisch?', 3, '[{"text": "App in einem Tag entwickeln", "correct": true, "because": "Zu wenig Zeit"}, {"text": "Server in einer Woche einrichten", "correct": false, "because": "Machbar mit Ressourcen"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist ein realistisches Ziel immer leicht zu erreichen?', 2, '[{"text": "Nein", "correct": true, "because": "Kann herausfordernd bleiben"}, {"text": "Ja", "correct": false, "because": "Realistisch heißt nicht einfach"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor gefährdet die Realistischkeit eines Ziels?', 3, '[{"text": "Unzureichende Ressourcen", "correct": true, "because": "Machen Umsetzung schwer"}, {"text": "Klares Team", "correct": false, "because": "Fördert Realismus"}, {"text": "Gute Planung", "correct": false, "because": "Unterstützt Machbarkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Realistische Ziele berücksichtigen Zeit. b) Realistisch ignoriert Teamkapazität.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Kapazität zählt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was macht "Server bis morgen installieren" unrealistisch?', 3, '[{"text": "Zu kurze Zeit", "correct": true, "because": "Nicht machbar in einem Tag"}, {"text": "Zu viele Ressourcen", "correct": false, "because": "Problem ist Zeit"}, {"text": "Keine Spezifikation", "correct": false, "because": "Anderes Kriterium"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Ziel mit unbegrenzten Ressourcen realistisch sein?', 2, '[{"text": "Nein", "correct": true, "because": "Ressourcen sind immer begrenzt"}, {"text": "Ja", "correct": false, "because": "Unrealistische Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel ist realistisch im SMART-Prinzip?', 3, '[{"text": "Datenbank in 2 Wochen optimieren", "correct": true, "because": "Machbar mit Planung"}, {"text": "Betriebssystem in 1 Stunde entwickeln", "correct": false, "because": "Unrealistisch kurz"}, {"text": "Team in 1 Tag verdoppeln", "correct": false, "because": "Zu schnell"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein realistisches Ziel immer sofort umsetzbar sein?', 2, '[{"text": "Nein", "correct": true, "because": "Kann zeitlich geplant sein"}, {"text": "Ja", "correct": false, "because": "Realismus erlaubt Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente fördern die Realistischkeit eines Ziels?', 4, '[{"text": "Einschätzung der Zeit", "correct": true, "because": "Macht Planung möglich"}, {"text": "Unendliches Budget", "correct": false, "because": "Nicht realistisch"}, {"text": "Verfügbare Expertise", "correct": true, "because": "Sichert Umsetzung"}, {"text": "Klarer Plan", "correct": true, "because": "Fördert Machbarkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist "realistisch" dasselbe wie "einfach"?', 2, '[{"text": "Nein", "correct": true, "because": "Realistisch kann herausfordernd sein"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Begriffe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt macht ein Ziel unrealistisch?', 3, '[{"text": "Fehlende Fachkenntnisse", "correct": true, "because": "Verhindern Umsetzung"}, {"text": "Klares Budget", "correct": false, "because": "Fördert Realismus"}, {"text": "Definierte Schritte", "correct": false, "because": "Unterstützen Realität"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Ziel realistisch sein, wenn Ressourcen fehlen?', 2, '[{"text": "Nein", "correct": true, "because": "Ressourcen sind entscheidend"}, {"text": "Ja", "correct": false, "because": "Fehlende Mittel machen es schwer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt "realistisch" im SMART-Prinzip?', 3, '[{"text": "Sichert Erreichbarkeit", "correct": true, "because": "Verhindert Überforderung"}, {"text": "Ignoriert Zeit", "correct": false, "because": "Zeit ist Teil davon"}, {"text": "Macht Ziele vage", "correct": false, "because": "Fördert Klarheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Realistische Ziele berücksichtigen Kapazitäten. b) Realistisch bedeutet ohne Planung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Planung hilft"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Ziel nicht realistisch ist?', 3, '[{"text": "Motivation sinkt", "correct": true, "because": "Unrealistische Ziele frustrieren"}, {"text": "Team wird effizienter", "correct": false, "because": "Eher Gegenteil"}, {"text": "Projekt wird einfacher", "correct": false, "because": "Komplexität bleibt"}]');

