INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Kundenbeziehungen > AGB-Gesetz
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen Allgemeine Geschäftsbedingungen (AGB) nach dem AGB-Gesetz immer schriftlich vorliegen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch elektronische Form ist zulässig (§ 305 BGB)"}, {"text": "Ja", "correct": false, "because": "Schriftform ist nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine Klausel in den AGB nach dem AGB-Gesetz wirksam sein, wenn sie den Kunden unangemessen benachteiligt?', 2, '[{"text": "Nein", "correct": true, "because": "§ 307 BGB verbietet unangemessene Benachteiligung"}, {"text": "Ja", "correct": false, "because": "Unwirksam bei Benachteiligung"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es nach dem AGB-Gesetz erlaubt, Kundenrechte wie das Widerrufsrecht per AGB auszuschließen?', 2, '[{"text": "Nein", "correct": true, "because": "Gesetzliche Rechte dürfen nicht entzogen werden (§ 306 BGB)"}, {"text": "Ja", "correct": false, "because": "Widerrufsrecht ist zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen AGB nach dem AGB-Gesetz dem Kunden vor Vertragsschluss ausdrücklich zur Kenntnis gebracht werden?', 2, '[{"text": "Ja", "correct": true, "because": "Einbeziehung erfordert Kenntnisnahme (§ 305 Abs. 2 BGB)"}, {"text": "Nein", "correct": false, "because": "Ohne Kenntnisnahme keine Einbindung"}]'),
('00000000-0000-0000-0000-000000000000', 'Können AGB nach dem AGB-Gesetz auch dann gelten, wenn sie intransparent oder unverständlich formuliert sind?', 2, '[{"text": "Nein", "correct": true, "because": "Unklare Klauseln sind unwirksam (§ 307 Abs. 1 BGB)"}, {"text": "Ja", "correct": false, "because": "Transparenz ist Pflicht"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche gesetzliche Grundlage regelt die Wirksamkeit von AGB im Verhältnis zu Kunden?', 2, '[{"text": "BGB (§§ 305 ff.)", "correct": true, "because": "Regelt Einbeziehung und Inhaltskontrolle"}, {"text": "UWG", "correct": false, "because": "Fokussiert Wettbewerb"}, {"text": "DSGVO", "correct": false, "because": "Datenschutz, nicht AGB"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Klausel in AGB wäre nach dem AGB-Gesetz unwirksam?', 3, '[{"text": "Haftungsausschluss für grobe Fahrlässigkeit", "correct": true, "because": "Verstößt gegen § 309 Nr. 7 BGB"}, {"text": "Zahlungsfrist von 30 Tagen", "correct": false, "because": "Angemessen und üblich"}, {"text": "Lieferzeitangabe ca. 2 Wochen", "correct": false, "because": "Keine Benachteiligung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die wichtigste Anforderung des AGB-Gesetzes an die Formulierung von Klauseln?', 2, '[{"text": "Klarheit und Verständlichkeit", "correct": true, "because": "§ 307 Abs. 1 BGB fordert Transparenz"}, {"text": "Technische Präzision", "correct": false, "because": "Wichtig, aber nicht primär"}, {"text": "Kürze der Formulierungen", "correct": false, "because": "Kein Hauptkriterium"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz tritt ein, wenn eine AGB-Klausel gegen das AGB-Gesetz verstößt?', 2, '[{"text": "Sie ist nichtig", "correct": true, "because": "§ 306 BGB erklärt sie für unwirksam"}, {"text": "Sie wird automatisch angepasst", "correct": false, "because": "Keine automatische Korrektur"}, {"text": "Sie bleibt gültig mit Einschränkung", "correct": false, "because": "Nichtigkeit ist Folge"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme muss ein Unternehmen ergreifen, um AGB nach dem AGB-Gesetz wirksam einzubinden?', 2, '[{"text": "Kunden auf AGB hinweisen", "correct": true, "because": "§ 305 Abs. 2 BGB verlangt Kenntnisnahme"}, {"text": "AGB im Kleingedruckten verstecken", "correct": false, "because": "Verstößt gegen Transparenz"}, {"text": "AGB nur intern speichern", "correct": false, "because": "Keine Einbindung beim Kunden"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Anforderungen stellt das AGB-Gesetz an wirksame AGB?', 4, '[{"text": "Einbeziehung vor Vertragsschluss", "correct": true, "because": "§ 305 Abs. 2 BGB"}, {"text": "Klarheit der Formulierungen", "correct": true, "because": "§ 307 Abs. 1 BGB"}, {"text": "Keine unangemessene Benachteiligung", "correct": true, "because": "§ 307 BGB"}, {"text": "Verwendung technischer Fachsprache", "correct": false, "because": "Kann Unklarheit erzeugen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Klauseln sind nach dem AGB-Gesetz verboten?', 3, '[{"text": "Ausschluss der Haftung bei Vorsatz", "correct": true, "because": "§ 309 Nr. 7 BGB"}, {"text": "Verpflichtung zu Schadensersatz bei Vertragsbruch", "correct": true, "because": "Unangemessen (§ 309 Nr. 5 BGB)"}, {"text": "Änderungsvorbehalt bei Preisänderungen", "correct": true, "because": "Kann unzulässig sein (§ 308 Nr. 4 BGB)"}, {"text": "Lieferung innerhalb von 14 Tagen", "correct": false, "because": "Angemessen und üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folgen hat eine Verletzung des AGB-Gesetzes?', 4, '[{"text": "Nichtigkeit der Klausel", "correct": true, "because": "§ 306 BGB"}, {"text": "Schadensersatzansprüche des Kunden", "correct": true, "because": "Bei Täuschung möglich"}, {"text": "Wettbewerbsrechtliche Abmahnung", "correct": true, "because": "UWG kann greifen"}, {"text": "Automatische Vertragsverlängerung", "correct": false, "because": "Keine direkte Folge"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rechte des Kunden dürfen durch AGB nicht eingeschränkt werden?', 3, '[{"text": "Widerrufsrecht", "correct": true, "because": "Gesetzlich zwingend (§ 355 BGB)"}, {"text": "Gewährleistungsansprüche", "correct": true, "because": "§ 309 Nr. 8 BGB schützt"}, {"text": "Recht auf Schadensersatz bei Vorsatz", "correct": true, "because": "§ 309 Nr. 7 BGB"}, {"text": "Recht auf Rabatt", "correct": false, "because": "Kein gesetzliches Recht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sichern die Einhaltung des AGB-Gesetzes?', 3, '[{"text": "Hinweis auf AGB vor Vertragsabschluss", "correct": true, "because": "§ 305 Abs. 2 BGB"}, {"text": "Regelmäßige rechtliche Prüfung der AGB", "correct": true, "because": "Vermeidet Verstöße"}, {"text": "Verständliche Sprache", "correct": true, "because": "§ 307 Abs. 1 BGB"}, {"text": "Versteckte Klauseln einfügen", "correct": false, "because": "Verstößt gegen Transparenz"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) AGB müssen dem Kunden vor Vertragsschluss zugänglich sein. b) Unklare Klauseln sind automatisch gültig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zugänglichkeit ja (§ 305 BGB), Unklarheit nein (§ 307 BGB)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Das AGB-Gesetz verbietet Haftungsausschlüsse bei grober Fahrlässigkeit. b) AGB können gesetzliche Rechte uneingeschränkt ändern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "§ 309 Nr. 7 BGB ja, gesetzliche Rechte nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) AGB sind unwirksam, wenn sie den Kunden unangemessen benachteiligen. b) Das AGB-Gesetz gilt nur für Verbraucher.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "§ 307 BGB ja, gilt auch für Unternehmer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Versteckte Klauseln in AGB sind zulässig. b) AGB müssen klar und verständlich sein.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Versteckt nein, Klarheit ja (§ 307 BGB)"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Das AGB-Gesetz schützt gesetzliche Kundenrechte. b) AGB können ohne Hinweis einbezogen werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schutz ja (§ 306 BGB), Hinweis nötig (§ 305 BGB)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

