INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Kundenbeziehungen > Berücksichtigung der geltenden Compliance-Regelungen
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen Compliance-Regelungen in Kundenbeziehungen auch dann beachtet werden, wenn keine gesetzlichen Sanktionen drohen?', 2, '[{"text": "Ja", "correct": true, "because": "Compliance umfasst auch interne und ethische Standards"}, {"text": "Nein", "correct": false, "because": "Gesetzliche Sanktionen sind nicht allein maßgeblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Einhaltung von Compliance-Regelungen in Kundenbeziehungen ausschließlich Sache der Rechtsabteilung?', 2, '[{"text": "Nein", "correct": true, "because": "Alle Mitarbeiter sind verantwortlich"}, {"text": "Ja", "correct": false, "because": "Compliance ist unternehmensweit relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Unternehmen Compliance-Regelungen in Kundenbeziehungen ignorieren, wenn der Kunde dies akzeptiert?', 2, '[{"text": "Nein", "correct": true, "because": "Compliance ist nicht verhandelbar, sondern verpflichtend"}, {"text": "Ja", "correct": false, "because": "Kundenwunsch hebt Vorschriften nicht auf"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Compliance-Regelungen in Kundenbeziehungen nur auf finanzielle Transaktionen beschränkt?', 2, '[{"text": "Nein", "correct": true, "because": "Sie umfassen auch Datenschutz, Ethik und mehr"}, {"text": "Ja", "correct": false, "because": "Compliance ist breiter gefasst"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Einhaltung von Compliance-Regelungen in Kundenbeziehungen regelmäßig überprüft werden?', 2, '[{"text": "Ja", "correct": true, "because": "Regelmäßige Audits sichern Konformität"}, {"text": "Nein", "correct": false, "because": "Einmalige Umsetzung reicht nicht"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgen Compliance-Regelungen in Kundenbeziehungen primär?', 2, '[{"text": "Risikominimierung", "correct": true, "because": "Schutz vor Verstößen und Reputationsverlust"}, {"text": "Umsatzsteigerung", "correct": false, "because": "Indirekt, nicht primär"}, {"text": "Kundengewinnung", "correct": false, "because": "Nebenprodukt, nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme ist entscheidend, um Compliance-Regelungen in Kundenbeziehungen sicherzustellen?', 3, '[{"text": "Schulung der Mitarbeiter", "correct": true, "because": "Wissen sichert Umsetzung"}, {"text": "Preissenkung für Kunden", "correct": false, "because": "Kein Compliance-Bezug"}, {"text": "Marketingkampagnen", "correct": false, "because": "Nicht regelrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorschrift ist in Kundenbeziehungen ein zentraler Bestandteil der Compliance?', 2, '[{"text": "DSGVO", "correct": true, "because": "Regelt Umgang mit Kundendaten"}, {"text": "UWG", "correct": false, "because": "Wettbewerbsfokus"}, {"text": "HGB", "correct": false, "because": "Buchhaltungsbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die größte Konsequenz bei Nichtbeachtung von Compliance-Regelungen in Kundenbeziehungen?', 2, '[{"text": "Reputationsschaden", "correct": true, "because": "Vertrauensverlust wirkt langfristig"}, {"text": "Geringere Produktivität", "correct": false, "because": "Indirekt betroffen"}, {"text": "Technische Probleme", "correct": false, "because": "Kein direkter Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element der Compliance-Regelungen schützt Kunden direkt?', 2, '[{"text": "Datenschutzvorgaben", "correct": true, "because": "Sichert personenbezogene Daten"}, {"text": "Anti-Korruptionsrichtlinien", "correct": false, "because": "Schützt eher Unternehmen"}, {"text": "Wettbewerbsregeln", "correct": false, "because": "Indirekter Kundenschutz"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Bereiche decken Compliance-Regelungen in Kundenbeziehungen ab?', 4, '[{"text": "Datenschutz", "correct": true, "because": "DSGVO ist maßgeblich"}, {"text": "Korruptionsprävention", "correct": true, "because": "Verhindert unethisches Verhalten"}, {"text": "Wettbewerbsrecht", "correct": true, "because": "UWG schützt Fairness"}, {"text": "Produktentwicklung", "correct": false, "because": "Kein Compliance-Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen fördern die Einhaltung von Compliance-Regelungen in Kundenbeziehungen?', 3, '[{"text": "Regelmäßige Audits", "correct": true, "because": "Überprüfen Konformität"}, {"text": "Schulungen für Mitarbeiter", "correct": true, "because": "Sensibilisieren für Regeln"}, {"text": "Transparente Kommunikation", "correct": true, "because": "Vertrauen schaffen"}, {"text": "Rabattaktionen", "correct": false, "because": "Kein Compliance-Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken entstehen durch Verstöße gegen Compliance-Regelungen in Kundenbeziehungen?', 4, '[{"text": "Bußgelder", "correct": true, "because": "Gesetzliche Sanktionen möglich"}, {"text": "Vertrauensverlust", "correct": true, "because": "Kunden ziehen sich zurück"}, {"text": "Rechtliche Streitigkeiten", "correct": true, "because": "Klagen drohen"}, {"text": "Technische Ausfälle", "correct": false, "because": "Kein direkter Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Gesetze sind für Compliance-Regelungen in Kundenbeziehungen relevant?', 3, '[{"text": "DSGVO", "correct": true, "because": "Datenschutz für Kunden"}, {"text": "UWG", "correct": true, "because": "Regelt Wettbewerbsverhalten"}, {"text": "StGB", "correct": true, "because": "Anti-Korruption und Betrug"}, {"text": "EStG", "correct": false, "because": "Steuerrecht, kein Kundenfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Abteilungen sind für die Umsetzung von Compliance-Regelungen in Kundenbeziehungen verantwortlich?', 3, '[{"text": "Vertrieb", "correct": true, "because": "Direkter Kundenkontakt"}, {"text": "Rechtsabteilung", "correct": true, "because": "Prüft Regelkonformität"}, {"text": "Management", "correct": true, "because": "Setzt Richtlinien"}, {"text": "Produktion", "correct": false, "because": "Kein direkter Kundenbezug"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Compliance-Regelungen schützen Kunden vor Datenmissbrauch. b) Sie sind nur für Großunternehmen relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Datenschutz ja, gilt für alle Unternehmen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die DSGVO ist eine zentrale Compliance-Regelung in Kundenbeziehungen. b) Audits sind optional und nicht erforderlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DSGVO ja, Audits wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Compliance-Regelungen verhindern Korruption in Kundenbeziehungen. b) Sie können durch Kundenvereinbarungen aufgehoben werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Korruption ja, Vereinbarungen nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Verstöße gegen Compliance-Regelungen können Bußgelder nach sich ziehen. b) Sie betreffen nur den Vertrieb.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Bußgelder ja, alle Abteilungen betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Schulungen fördern die Einhaltung von Compliance-Regelungen. b) Compliance hat keinen Einfluss auf die Kundenbindung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schulungen ja, Vertrauen stärkt Bindung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

