INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Kundenbeziehungen > Dokumentation sowie Verwaltung von Kundenbeziehungen („Customer Relationship Management“)
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Dokumentation von Kundenbeziehungen in einem CRM-System gesetzlich vorgeschrieben?', 2, '[{"text": "Nein", "correct": true, "because": "Es gibt keine allgemeine Pflicht, aber DSGVO kann Anforderungen stellen"}, {"text": "Ja", "correct": false, "because": "CRM-Nutzung ist betriebliche Entscheidung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Verwaltung von Kundenbeziehungen ohne ein CRM-System effektiv sein?', 2, '[{"text": "Ja", "correct": true, "because": "Manuelle Methoden sind möglich, aber weniger effizient"}, {"text": "Nein", "correct": false, "because": "CRM ist hilfreich, aber nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle Kundendaten in einem CRM-System zentral gespeichert werden, um den Datenschutz zu gewährleisten?', 2, '[{"text": "Nein", "correct": true, "because": "Datenschutz hängt von Prozessen ab, nicht nur vom CRM"}, {"text": "Ja", "correct": false, "because": "Zentralisierung ist keine Garantie"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Dokumentation von Kundeninteraktionen in einem CRM-System nur für den Vertrieb relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Support und Management profitieren"}, {"text": "Ja", "correct": false, "because": "Mehrere Abteilungen nutzen CRM"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein CRM-System automatisch alle rechtlichen Anforderungen an die Kundenbeziehungen erfüllen?', 2, '[{"text": "Nein", "correct": true, "because": "Rechtliche Compliance erfordert menschliche Überprüfung"}, {"text": "Ja", "correct": false, "because": "Automatisierung deckt nicht alles ab"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Funktion eines CRM-Systems ist für die Dokumentation von Kundenbeziehungen am wichtigsten?', 2, '[{"text": "Kundenhistorie speichern", "correct": true, "because": "Bietet vollständigen Überblick"}, {"text": "Automatisierte Werbung", "correct": false, "because": "Marketing, nicht Dokumentation"}, {"text": "Rechnungsstellung", "correct": false, "because": "Finanzfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Verwaltung von Kundenbeziehungen wird durch ein CRM-System primär verbessert?', 3, '[{"text": "Datenkonsistenz", "correct": true, "because": "Zentralisierung reduziert Fehler"}, {"text": "Produktentwicklung", "correct": false, "because": "Technischer Bereich"}, {"text": "Mitarbeitermotivation", "correct": false, "because": "Indirekt betroffen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Art von Daten sollte in einem CRM-System besonders sorgfältig dokumentiert werden?', 2, '[{"text": "Personenbezogene Daten", "correct": true, "because": "DSGVO verlangt Schutz"}, {"text": "Produktpreise", "correct": false, "because": "Wichtig, aber nicht primär"}, {"text": "Interne Notizen", "correct": false, "because": "Sekundär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Dokumentation von Kundenbeziehungen in einem CRM-System?', 2, '[{"text": "Nachverfolgbarkeit sichern", "correct": true, "because": "Ermöglicht Kontinuität"}, {"text": "Kosten senken", "correct": false, "because": "Indirekter Effekt"}, {"text": "Vertrieb steigern", "correct": false, "because": "Folge, nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Risiko wird durch eine unzureichende Verwaltung von Kundenbeziehungen in einem CRM-System erhöht?', 2, '[{"text": "Datenschutzverletzungen", "correct": true, "because": "Fehlende Struktur gefährdet Daten"}, {"text": "Technische Ausfälle", "correct": false, "because": "Nicht direkt verknüpft"}, {"text": "Kundengewinnung", "correct": false, "because": "Eher Verlust"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Daten sollten in einem CRM-System dokumentiert werden?', 4, '[{"text": "Kundenkontaktdaten", "correct": true, "because": "Grundlage für Kommunikation"}, {"text": "Interaktionshistorie", "correct": true, "because": "Zeigt Verlauf"}, {"text": "Vertragsdetails", "correct": true, "because": "Rechtlich relevant"}, {"text": "Mitarbeitergehälter", "correct": false, "because": "Kein Kundenbezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Verwaltung von Kundenbeziehungen mit einem CRM-System?', 3, '[{"text": "Zentralisierte Daten", "correct": true, "because": "Vereinfacht Zugriff"}, {"text": "Automatisierte Prozesse", "correct": true, "because": "Spart Zeit"}, {"text": "Verbesserte Kundenanalyse", "correct": true, "because": "Liefert Insights"}, {"text": "Geringere Produktionskosten", "correct": false, "because": "Kein direkter Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen können bei der Dokumentation in einem CRM-System auftreten?', 4, '[{"text": "Datenqualität", "correct": true, "because": "Ungenaue Eingaben schaden"}, {"text": "Datenschutz", "correct": true, "because": "DSGVO muss eingehalten werden"}, {"text": "Nutzerakzeptanz", "correct": true, "because": "Mitarbeiter müssen System nutzen"}, {"text": "Hardwarekosten", "correct": false, "because": "Indirekt, nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Abteilungen profitieren von der Verwaltung von Kundenbeziehungen in einem CRM-System?', 3, '[{"text": "Vertrieb", "correct": true, "because": "Optimiert Verkaufsprozesse"}, {"text": "Kundensupport", "correct": true, "because": "Schneller Zugriff auf Historie"}, {"text": "Marketing", "correct": true, "because": "Zielgerichtete Kampagnen"}, {"text": "Produktion", "correct": false, "because": "Kein direkter Kundenfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche rechtlichen Anforderungen müssen bei der Dokumentation in einem CRM-System beachtet werden?', 3, '[{"text": "Einwilligung zur Datenverarbeitung", "correct": true, "because": "DSGVO Art. 6"}, {"text": "Datenminimierung", "correct": true, "because": "Nur notwendige Daten speichern"}, {"text": "Löschfristen", "correct": true, "because": "Speicherbegrenzung erforderlich"}, {"text": "Produktzertifizierung", "correct": false, "because": "Kein Datenschutzbezug"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ein CRM-System verbessert die Nachverfolgbarkeit von Kundenbeziehungen. b) Es ist für kleine Unternehmen überflüssig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nachverfolgbarkeit ja, auch kleine Firmen profitieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Dokumentation in einem CRM-System muss DSGVO-konform sein. b) Alle Kundendaten dürfen unbegrenzt gespeichert werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DSGVO ja, Speicherbegrenzung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein CRM-System kann die Kundenanalyse automatisieren. b) Es ersetzt die persönliche Kundeninteraktion.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Analyse ja, Interaktion bleibt wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Verwaltung in einem CRM-System erhöht die Datenkonsistenz. b) Es ist nur für den Kundensupport relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Konsistenz ja, mehrere Abteilungen betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein CRM-System unterstützt die Einhaltung von Löschfristen. b) Die Dokumentation darin ist nur für den Vertrieb nützlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Löschfristen ja, Nutzen breiter"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

