-- Bereitstellungsstrategien (Cloud, Container, Server).sql (Methoden zur Auslieferung, z. B. AWS, Docker, On-Premise)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist eine Cloud-Bereitstellung immer teurer als On-Premise?', 2, '[{"text": "Nein", "correct": true, "because": "Skalierung kann Kosten senken"}, {"text": "Ja", "correct": false, "because": "Abhängig von Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strategie wähle ich für maximale Flexibilität?', 3, '[{"text": "Container", "correct": true, "because": "Portabel und skalierbar"}, {"text": "On-Premise", "correct": false, "because": "Hardwaregebunden"}, {"text": "Cloud", "correct": false, "because": "Anbieterabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Container-Bereitstellung?', 5, '[{"text": "Portabilität", "correct": true, "because": "Läuft überall gleich"}, {"text": "Isolation", "correct": true, "because": "Prozesse getrennt"}, {"text": "Hohe Latenz", "correct": false, "because": "Kein Vorteil"}, {"text": "Einfache Hardware", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) AWS ist nur für große Firmen. b) Docker spart Ressourcen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "AWS auch für Kleine"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl einer Cloud-Strategie?', 4, '[{"text": "Skalierbarkeit", "correct": false, "because": "Kernvorteil Cloud"}, {"text": "Kostenmodelle", "correct": false, "because": "Entscheidend"}, {"text": "Betriebssystem", "correct": true, "because": "Abstrahiert in Cloud"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Container immer virtualisierte Server brauchen?', 2, '[{"text": "Nein", "correct": true, "because": "Laufen auf Host-OS"}, {"text": "Ja", "correct": false, "because": "Keine VM nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool nutze ich für Container-Orchestrierung?', 3, '[{"text": "Kubernetes", "correct": true, "because": "Standard für Verwaltung"}, {"text": "AWS EC2", "correct": false, "because": "Cloud-Instanz"}, {"text": "Docker allein", "correct": false, "because": "Keine Orchestrierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen eine Cloud-Strategie effektiv?', 5, '[{"text": "Automatische Skalierung", "correct": true, "because": "Passt sich Last an"}, {"text": "Pay-per-Use", "correct": true, "because": "Kosteneffizient"}, {"text": "Hohe Taktfrequenz", "correct": false, "because": "Hardware-spezifisch"}, {"text": "Statische IPs", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) On-Premise ist sicherer. b) Cloud ist immer verfügbar. Stimmt das?', 3, '[{"text": "Beides falsch", "correct": true, "because": "Sicherheit und Verfügbarkeit kontextabhängig"}, {"text": "Beides stimmt", "correct": false, "because": "Nicht absolut"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) nicht immer"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) nicht garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine Container-Strategie?', 4, '[{"text": "Docker", "correct": false, "because": "Kern der Container"}, {"text": "Orchestrierung", "correct": false, "because": "Wichtig bei Skalierung"}, {"text": "Physische Server", "correct": true, "because": "Abstrahiert durch Host"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist On-Premise immer langsamer als Cloud?', 2, '[{"text": "Nein", "correct": true, "because": "Hängt von Hardware ab"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind bei AWS entscheidend?', 4, '[{"text": "EC2", "correct": true, "because": "Virtuelle Server"}, {"text": "S3", "correct": true, "because": "Speicherlösung"}, {"text": "BIOS", "correct": false, "because": "Hardware-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Container nur für Microservices sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Monolithen nutzbar"}, {"text": "Ja", "correct": false, "because": "Nicht exklusiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einer On-Premise-Strategie?', 3, '[{"text": "Hardware-Kontrolle", "correct": true, "because": "Volle Autonomie"}, {"text": "Schnelle Skalierung", "correct": false, "because": "Cloud-Vorteil"}, {"text": "Pay-per-Use", "correct": false, "because": "Cloud-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Cloud spart Wartung. b) Container brauchen keine VMs.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Cloud abstrahiert, Container auf Host"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) auch korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) auch korrekt"}, {"text": "Beides falsch", "correct": false, "because": "Beide richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat eine Cloud-Strategie?', 5, '[{"text": "Vendor Lock-in", "correct": true, "because": "Abhängigkeit vom Anbieter"}, {"text": "Datenkontrolle", "correct": true, "because": "Weniger direkter Zugriff"}, {"text": "Hohe Leistung", "correct": false, "because": "Kein Nachteil"}, {"text": "Einfache Wartung", "correct": false, "because": "Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer Container-Strategie unwichtig?', 3, '[{"text": "Isolation", "correct": false, "because": "Kernvorteil"}, {"text": "Portabilität", "correct": false, "because": "Hauptmerkmal"}, {"text": "Monitorgröße", "correct": true, "because": "Hardware-irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Bietet Cloud immer bessere Sicherheit?', 3, '[{"text": "Nein", "correct": true, "because": "Hängt von Konfiguration ab"}, {"text": "Ja", "correct": false, "because": "Nicht garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob On-Premise für kleine Teams geeignet ist?', 2, '[{"text": "Ja", "correct": true, "because": "Kontrolle bei kleinem Umfang"}, {"text": "Nein", "correct": false, "because": "Nicht exklusiv groß"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature ist für eine hybride Strategie entscheidend?', 4, '[{"text": "Interoperabilität", "correct": true, "because": "Cloud und On-Premise verbinden"}, {"text": "Hohe Taktfrequenz", "correct": false, "because": "Hardware-spezifisch"}, {"text": "Statische IPs", "correct": false, "because": "Nicht primär"}]');

