-- Software übergeben (Installation, Schulung).sql (Übergabe an Kunden inkl. Setup und Training, z. B. Live-Schaltung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Software-Übergabe ohne Schulung komplett?', 2, '[{"text": "Nein", "correct": true, "because": "Schulung sichert Nutzung"}, {"text": "Ja", "correct": false, "because": "Training essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Schritt priorisiere ich bei der Software-Übergabe?', 3, '[{"text": "Installation", "correct": true, "because": "Grundlage für Betrieb"}, {"text": "Dokumentation", "correct": false, "because": "Folgt Installation"}, {"text": "Feedback", "correct": false, "because": "Später relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Software-Übergabe?', 5, '[{"text": "Installation", "correct": true, "because": "Setup erforderlich"}, {"text": "Schulung", "correct": true, "because": "Nutzerkompetenz"}, {"text": "Hardware-Tuning", "correct": false, "because": "Nicht primär"}, {"text": "Marketing", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Installation reicht für Übergabe. b) Schulung ist optional.', 3, '[{"text": "Beides falsch", "correct": true, "because": "Schulung essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "Nicht ausreichend"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Software-Übergabe?', 4, '[{"text": "Schulungsplan", "correct": false, "because": "Wissenstransfer nötig"}, {"text": "Installationsskript", "correct": false, "because": "Setup-Grundlage"}, {"text": "Farbschema", "correct": true, "because": "Irrelevant für Übergabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Live-Schaltung ohne Test möglich ist?', 2, '[{"text": "Nein", "correct": true, "because": "Tests sichern Stabilität"}, {"text": "Ja", "correct": false, "because": "Risiko steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer Schulung bei Übergabe?', 3, '[{"text": "Nutzerkompetenz", "correct": true, "because": "Effektive Nutzung"}, {"text": "Kostensenkung", "correct": false, "because": "Nicht primär"}, {"text": "Schnellere Installation", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sichern eine erfolgreiche Übergabe?', 5, '[{"text": "Detaillierte Schulung", "correct": true, "because": "Fördert Verständnis"}, {"text": "Getestete Installation", "correct": true, "because": "Verhindert Fehler"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nicht zwingend"}, {"text": "Manuelle Updates", "correct": false, "because": "Nicht essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Übergabe ist nur Installation. b) Schulung verlängert den Prozess. Stimmt das?', 3, '[{"text": "Beides falsch", "correct": true, "because": "Schulung essenziell, kein Verzug"}, {"text": "Beides stimmt", "correct": false, "because": "Nicht korrekt"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) unvollständig"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) kontextabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht direkt für die Übergabe?', 4, '[{"text": "Installationsanleitung", "correct": false, "because": "Setup-Grundlage"}, {"text": "Schulungsmaterial", "correct": false, "because": "Wissenstransfer"}, {"text": "Design-Spezifikation", "correct": true, "because": "Entwicklungsspezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Übergabe ohne Dokumentation sinnvoll?', 2, '[{"text": "Nein", "correct": true, "because": "Doku unterstützt Nutzung"}, {"text": "Ja", "correct": false, "because": "Fehlende Orientierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind bei der Installation entscheidend?', 4, '[{"text": "Abhängigkeiten", "correct": true, "because": "Sichern Funktion"}, {"text": "Konfigurationsdateien", "correct": true, "because": "Passen System an"}, {"text": "UI-Design", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Schulung nur für Anfänger ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Profis profitieren"}, {"text": "Ja", "correct": false, "because": "Nicht exklusiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einer Live-Schaltung?', 3, '[{"text": "Stabilitätstest", "correct": true, "because": "Verhindert Ausfälle"}, {"text": "Schnelle Übergabe", "correct": false, "because": "Qualität zählt"}, {"text": "Minimales Training", "correct": false, "because": "Wissen nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Installation muss automatisiert sein. b) Schulung braucht Praxis.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Automatisierung optional"}, {"text": "Beides stimmt", "correct": false, "because": "a) nicht zwingend"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken gibt es bei der Übergabe?', 5, '[{"text": "Fehlende Schulung", "correct": true, "because": "Nutzerfehler möglich"}, {"text": "Ungetestete Installation", "correct": true, "because": "Instabilität"}, {"text": "Hohe Leistung", "correct": false, "because": "Kein Risiko"}, {"text": "Schnelle Lieferung", "correct": false, "because": "Nicht per se riskant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Schulung unwichtig?', 3, '[{"text": "Praxisbeispiele", "correct": false, "because": "Fördern Verständnis"}, {"text": "Klarheit", "correct": false, "because": "Essenziell"}, {"text": "Monitorauflösung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Reicht eine Übergabe ohne Feedback?', 3, '[{"text": "Nein", "correct": true, "because": "Feedback verbessert"}, {"text": "Ja", "correct": false, "because": "Optimierung fehlt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Installation ohne Abhängigkeiten läuft?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängigkeiten nötig"}, {"text": "Ja", "correct": false, "because": "Fehler wahrscheinlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist für die Übergabe entscheidend?', 4, '[{"text": "Kommunikation", "correct": true, "because": "Kunde einbinden"}, {"text": "Hohe Taktfrequenz", "correct": false, "because": "Hardware-spezifisch"}, {"text": "Statische IPs", "correct": false, "because": "Nicht primär"}]');

