-- Intrusion-Detection-Systeme.sql (Erkennung von Angriffen, z. B. IDS/IPS)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Intrusion-Detection-Systeme nur für externe Angriffe gedacht?', 2, '[{"text": "Nein", "correct": true, "because": "Auch interne Bedrohungen erkennbar"}, {"text": "Ja", "correct": false, "because": "Umfassender Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem IDS?', 3, '[{"text": "Angriffserkennung", "correct": true, "because": "Identifiziert Bedrohungen"}, {"text": "Datenmenge maximieren", "correct": false, "because": "Nicht primär"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Sicherheit im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktionen bieten IDS/IPS?', 5, '[{"text": "Überwachung", "correct": true, "because": "Erkennt Anomalien"}, {"text": "Blockierung", "correct": true, "because": "IPS verhindert Angriffe"}, {"text": "Datenbankdesign", "correct": false, "because": "Nicht relevant"}, {"text": "Visuelle Gestaltung", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein IDS erkennt Angriffe. b) Ein IPS blockiert sie automatisch.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "IDS erkennt, IPS blockiert"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "Beide sind richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der IDS/IPS-Konfiguration?', 4, '[{"text": "Signaturdatenbank", "correct": false, "because": "Erkennt bekannte Angriffe"}, {"text": "Überwachungsregeln", "correct": false, "because": "Definiert Schutz"}, {"text": "Farbschema", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein IDS auch interne Netzwerke überwacht?', 2, '[{"text": "Ja", "correct": true, "because": "Host- und Netzwerk-IDS möglich"}, {"text": "Nein", "correct": false, "because": "Umfassende Überwachung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches System erkennt Angriffe in Echtzeit?', 3, '[{"text": "IPS", "correct": true, "because": "Aktive Erkennung und Reaktion"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Irrelevant"}, {"text": "Statische IPs", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ansätze nutzen IDS/IPS?', 5, '[{"text": "Signaturbasiert", "correct": true, "because": "Erkennt bekannte Muster"}, {"text": "Anomaliebasiert", "correct": true, "because": "Erkennt Abweichungen"}, {"text": "Maximale Speicherung", "correct": false, "because": "Nicht vorgeschrieben"}, {"text": "Animationseffekte", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein IDS warnt vor Angriffen. b) Es blockiert sie immer. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Blockieren ist IPS-Funktion"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein IDS/IPS?', 4, '[{"text": "Regelmäßige Updates", "correct": false, "because": "Wichtig für neuen Schutz"}, {"text": "Alarmierung", "correct": false, "because": "Informiert über Bedrohungen"}, {"text": "Grafikdesign", "correct": true, "because": "Kein Sicherheitsaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erkennt ein IDS nur bekannte Angriffe?', 2, '[{"text": "Nein", "correct": true, "because": "Anomalieerkennung für neue Bedrohungen"}, {"text": "Ja", "correct": false, "because": "Erweiterte Funktionen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Systeme schützen Netzwerke?', 4, '[{"text": "Netzwerk-IDS", "correct": true, "because": "Überwacht Datenverkehr"}, {"text": "Host-IDS", "correct": true, "because": "Überwacht Geräte"}, {"text": "Visuelles Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein IPS alle Angriffe stoppt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Begrenzte Wirksamkeit"}, {"text": "Ja", "correct": false, "because": "Nicht vollständig abgedeckt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem IDS/IPS?', 3, '[{"text": "Echtzeitüberwachung", "correct": true, "because": "Frühwarnsystem"}, {"text": "Schnelle Datenverarbeitung", "correct": false, "because": "Sekundär"}, {"text": "Schriftarten", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) IDS protokolliert Angriffe. b) IPS ist nur für große Netzwerke.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "IPS für alle Netzwerke"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Techniken verwenden IDS/IPS?', 5, '[{"text": "Paketanalyse", "correct": true, "because": "Prüft Datenverkehr"}, {"text": "Verhaltensüberwachung", "correct": true, "because": "Erkennt Anomalien"}, {"text": "Maximale Speicherung", "correct": false, "because": "Nicht vorgeschrieben"}, {"text": "Datenbankdesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem IDS/IPS unwichtig?', 3, '[{"text": "Signaturupdates", "correct": false, "because": "Wichtig für Erkennung"}, {"text": "Protokollierung", "correct": false, "because": "Nachverfolgbarkeit"}, {"text": "Animationseffekte", "correct": true, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt ein IDS aktiv vor Angriffen?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Erkennung, keine Abwehr"}, {"text": "Ja", "correct": false, "because": "IPS übernimmt Abwehr"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein IPS auch interne Angriffe blockiert?', 2, '[{"text": "Ja", "correct": true, "because": "Je nach Konfiguration möglich"}, {"text": "Nein", "correct": false, "because": "Nicht nur extern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches System wähle ich für aktive Abwehr?', 4, '[{"text": "IPS", "correct": true, "because": "Blockiert Angriffe direkt"}, {"text": "Hohe Latenz", "correct": false, "because": "Kein Schutz"}, {"text": "Großer Speicher", "correct": false, "because": "Irrelevant"}]');

