-- Public-Key-Infrastruktur.sql (PKI, Zertifikate für sichere Kommunikation, z. B. SSL/TLS)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist eine PKI nur für Websites relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für E-Mails, VPNs und mehr"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer PKI?', 3, '[{"text": "Sichere Kommunikation", "correct": true, "because": "Schützt Datenübertragung"}, {"text": "Datenmenge maximieren", "correct": false, "because": "Nicht primär"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Sicherheit im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zur PKI?', 5, '[{"text": "Zertifikate", "correct": true, "because": "Bestätigen Identität"}, {"text": "Zertifizierungsstelle", "correct": true, "because": "Stellt Zertifikate aus"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Schutzfaktor"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) PKI nutzt asymmetrische Verschlüsselung. b) Sie ist nur für SSL/TLS nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch für andere Zwecke"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der PKI-Umsetzung?', 4, '[{"text": "Zertifikatsverwaltung", "correct": false, "because": "Kern der PKI"}, {"text": "Schlüsselpaare", "correct": false, "because": "Basis der Verschlüsselung"}, {"text": "Visuelles Design", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob PKI auch Authentizität sicherstellt?', 2, '[{"text": "Ja", "correct": true, "because": "Zertifikate bestätigen Identität"}, {"text": "Nein", "correct": false, "because": "Teil der Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist zentral für PKI?', 3, '[{"text": "Zertifizierungsstelle", "correct": true, "because": "Vertrauensanker"}, {"text": "Hohe Serverleistung", "correct": false, "because": "Irrelevant"}, {"text": "Statische IPs", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien nutzt PKI?', 5, '[{"text": "SSL/TLS", "correct": true, "because": "Sichert Webkommunikation"}, {"text": "S/MIME", "correct": true, "because": "Verschlüsselt E-Mails"}, {"text": "Maximale Speichergröße", "correct": false, "because": "Nicht relevant"}, {"text": "Animationseffekte", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) PKI schützt Datenübertragung. b) Sie ist ohne Zertifikate möglich. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zertifikate sind essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine PKI?', 4, '[{"text": "Public Keys", "correct": false, "because": "Teil der Verschlüsselung"}, {"text": "Zertifikatsstelle", "correct": false, "because": "Vertrauensbasis"}, {"text": "Grafisches Design", "correct": true, "because": "Kein Sicherheitsaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist PKI nur für Verschlüsselung?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Authentizität und Integrität"}, {"text": "Ja", "correct": false, "because": "Mehrere Funktionen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rollen spielen Zertifikate in der PKI?', 4, '[{"text": "Identitätsnachweis", "correct": true, "because": "Bestätigt Echtheit"}, {"text": "Schlüsselverteilung", "correct": true, "because": "Ermöglicht Verschlüsselung"}, {"text": "Datenbankgröße", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass PKI immer teuer ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten variieren je nach Umsetzung"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einer PKI?', 3, '[{"text": "Zertifikatsvertrauen", "correct": true, "because": "Basis der Sicherheit"}, {"text": "Schnelle Datenübertragung", "correct": false, "because": "Sekundär"}, {"text": "Visuelle Gestaltung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) PKI nutzt Public und Private Keys. b) Sie ist nur für große Firmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Gilt für alle Größen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben hat eine Zertifizierungsstelle in der PKI?', 5, '[{"text": "Zertifikate ausstellen", "correct": true, "because": "Bestätigt Identität"}, {"text": "Widerrufslisten führen", "correct": true, "because": "Ungültige Zertifikate"}, {"text": "Maximale Speicherung", "correct": false, "because": "Nicht vorgeschrieben"}, {"text": "Datenbankdesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der PKI unwichtig?', 3, '[{"text": "Schlüsselverwaltung", "correct": false, "because": "Kern der Sicherheit"}, {"text": "Zertifikatsprüfung", "correct": false, "because": "Vertrauen sicherstellen"}, {"text": "Schriftarten", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt PKI auch vor Datenmanipulation?', 3, '[{"text": "Ja", "correct": true, "because": "Signaturen sichern Integrität"}, {"text": "Nein", "correct": false, "because": "Mehr als nur Verschlüsselung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob PKI regelmäßig aktualisiert werden muss?', 2, '[{"text": "Ja", "correct": true, "because": "Zertifikate laufen ab"}, {"text": "Nein", "correct": false, "because": "Erneuerung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich für sichere PKI-Kommunikation?', 4, '[{"text": "SSL-Zertifikat", "correct": true, "because": "Sichert Webverbindungen"}, {"text": "Zufällige Daten", "correct": false, "because": "Irrelevant"}, {"text": "Grafisches Design", "correct": false, "because": "Kein Schutzfokus"}]');

