-- Technik: Installation - Betriebssystem
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Installation eines Betriebssystems ein wichtiger Schritt für einen Computer?', 2, '[{"text": "Ja", "correct": true, "because": "Grundlage für Nutzung"}, {"text": "Nein", "correct": false, "because": "Es ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt die Installation eines Betriebssystems?', 3, '[{"text": "Betriebsbereitschaft des Systems herstellen", "correct": true, "because": "Ermöglicht Nutzung"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Andere Funktion"}, {"text": "Netzwerk konfigurieren", "correct": false, "because": "Nachgelagerter Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Betriebssystem wird auf eine Festplatte installiert. b) Es wird immer automatisch installiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, manuell möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte gehören zur Installation eines Betriebssystems?', 4, '[{"text": "Bootmedium erstellen", "correct": true, "because": "Startet Installation"}, {"text": "Unklare Anweisungen", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Partitionierung", "correct": true, "because": "Festplatte vorbereiten"}, {"text": "Treiber installieren", "correct": true, "because": "Hardwareunterstützung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Computer ohne Betriebssystem vollständig genutzt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Software fehlt"}, {"text": "Ja", "correct": false, "because": "Nur Grundfunktionen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt das Bootmedium bei der Installation?', 3, '[{"text": "Startet den Installationsprozess", "correct": true, "because": "Lädt Installationsdaten"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Andere Funktion"}, {"text": "Netzwerk verbinden", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Installation eines Betriebssystems nur für neue Computer relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Updates oder Neuinstallation"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat die Partitionierung?', 3, '[{"text": "Festplatte in Abschnitte teilen", "correct": true, "because": "Vorbereitung Installation"}, {"text": "Treiber konfigurieren", "correct": false, "because": "Späterer Schritt"}, {"text": "Netzwerk einrichten", "correct": false, "because": "Nach Installation"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Bootmedium kann eine CD sein. b) Die Installation erfordert keine Hardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Hardware nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Betriebssystem-Installation?', 3, '[{"text": "Computer nicht nutzbar", "correct": true, "because": "Keine Softwarebasis"}, {"text": "Automatische Nutzung", "correct": false, "because": "Unsinn"}, {"text": "Netzwerk direkt verfügbar", "correct": false, "because": "OS nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Betriebssystem ohne Bootmedium installiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Netzwerkinstallation möglich"}, {"text": "Nein", "correct": false, "because": "Flexibilität gegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt einen Installationsschritt?', 3, '[{"text": "Windows-ISO auf USB schreiben", "correct": true, "because": "Konkret und real"}, {"text": "Irgendwas installieren", "correct": false, "because": "Zu vage"}, {"text": "Treiber überspringen", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Installation eines Betriebssystems nur für Windows relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Linux, macOS"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Voraussetzungen sind für die Installation nötig?', 4, '[{"text": "Kompatible Hardware", "correct": true, "because": "Systemanforderungen"}, {"text": "Unklare Schritte", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Installationsmedium", "correct": true, "because": "Liefert OS"}, {"text": "Stromversorgung", "correct": true, "because": "Betrieb nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Installation dokumentiert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Optional, aber hilfreich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt das BIOS bei der Installation?', 3, '[{"text": "Startet das Bootmedium", "correct": true, "because": "Initialisiert System"}, {"text": "Netzwerk konfigurieren", "correct": false, "because": "OS-Aufgabe"}, {"text": "Treiber laden", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Betriebssystem ohne Festplatte installiert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Speicherort nötig"}, {"text": "Ja", "correct": false, "because": "Unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor beeinflusst die Installation?', 3, '[{"text": "Hardwarekompatibilität", "correct": true, "because": "Bestimmt Erfolg"}, {"text": "Monitorgröße", "correct": false, "because": "Irrelevant"}, {"text": "Tastaturlayout", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Installation erfordert einen Product Key. b) Sie ist immer automatisiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, manuell möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen der Betriebssystem-Installation?', 3, '[{"text": "Funktionsfähigkeit des Computers", "correct": true, "because": "Ermöglicht Nutzung"}, {"text": "Maximale Unklarheit", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Softwarebasis", "correct": false, "because": "Fördert Betrieb"}]');

