INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Softwarearchitektur > 3-Schichten-Modell (3-Tier)
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist das 3-Schichten-Modell immer physisch auf drei separate Server aufgeteilt?', 2, '[{"text": "Nein", "correct": true, "because": "Die Schichten können logisch sein und auf einem Server laufen"}, {"text": "Ja", "correct": false, "because": "Physische Trennung ist nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Präsentationsschicht im 3-Schichten-Modell direkt auf die Datenschicht zugreifen?', 2, '[{"text": "Nein", "correct": true, "because": "Die Logikschicht vermittelt zwischen Präsentation und Daten"}, {"text": "Ja", "correct": false, "because": "Direkter Zugriff widerspricht dem Modell"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist das 3-Schichten-Modell flexibel genug, um in kleinen Anwendungen verwendet zu werden?', 2, '[{"text": "Ja", "correct": true, "because": "Es ist anpassbar auch für kleinere Projekte"}, {"text": "Nein", "correct": false, "because": "Flexibilität ist gegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle drei Schichten im 3-Schichten-Modell immer unterschiedliche Programmiersprachen verwenden?', 2, '[{"text": "Nein", "correct": true, "because": "Die Wahl der Sprache ist unabhängig vom Modell"}, {"text": "Ja", "correct": false, "because": "Keine solche Anforderung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Logikschicht im 3-Schichten-Modell Geschäftslogik und Datenbankzugriffe kombinieren?', 2, '[{"text": "Ja", "correct": true, "because": "Logikschicht kann beide Aufgaben übernehmen"}, {"text": "Nein", "correct": false, "because": "Kombination ist möglich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Schicht im 3-Schichten-Modell ist für die Benutzerinteraktion verantwortlich?', 2, '[{"text": "Präsentationsschicht", "correct": true, "because": "Sie stellt die Benutzeroberfläche bereit"}, {"text": "Logikschicht", "correct": false, "because": "Verarbeitet Logik"}, {"text": "Datenschicht", "correct": false, "because": "Speichert Daten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat die Logikschicht im 3-Schichten-Modell primär?', 3, '[{"text": "Verarbeitung der Geschäftslogik", "correct": true, "because": "Sie enthält die Anwendungslogik"}, {"text": "Datenbankverwaltung", "correct": false, "because": "Aufgabe der Datenschicht"}, {"text": "Anzeige von Daten", "correct": false, "because": "Präsentationsschicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil des 3-Schichten-Modells ist am bedeutendsten?', 2, '[{"text": "Trennung von Verantwortlichkeiten", "correct": true, "because": "Fördert Wartbarkeit und Modularität"}, {"text": "Hohe Performance", "correct": false, "because": "Nicht primär"}, {"text": "Geringere Kosten", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schicht im 3-Schichten-Modell interagiert direkt mit der Datenbank?', 2, '[{"text": "Datenschicht", "correct": true, "because": "Sie verwaltet Datenbankzugriffe"}, {"text": "Präsentationsschicht", "correct": false, "because": "Nur Benutzerinteraktion"}, {"text": "Logikschicht", "correct": false, "because": "Vermittelt, greift nicht direkt zu"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Problem kann beim 3-Schichten-Modell auftreten, wenn die Schichten nicht klar getrennt sind?', 2, '[{"text": "Schwierige Wartung", "correct": true, "because": "Vermischung erschwert Änderungen"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Eher Verzögerung"}, {"text": "Geringere Sicherheit", "correct": false, "because": "Indirekte Folge"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Schichten gehören zum 3-Schichten-Modell?', 4, '[{"text": "Präsentationsschicht", "correct": true, "because": "Benutzeroberfläche"}, {"text": "Logikschicht", "correct": true, "because": "Geschäftslogik"}, {"text": "Datenschicht", "correct": true, "because": "Datenverwaltung"}, {"text": "Netzwerkschicht", "correct": false, "because": "Kein Teil des Modells"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet das 3-Schichten-Modell?', 3, '[{"text": "Modularität", "correct": true, "because": "Trennung erleichtert Änderungen"}, {"text": "Wartbarkeit", "correct": true, "because": "Klare Struktur hilft"}, {"text": "Skalierbarkeit", "correct": true, "because": "Schichten können separat skaliert werden"}, {"text": "Maximale Komplexität", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben können der Logikschicht im 3-Schichten-Modell zugeordnet werden?', 4, '[{"text": "Verarbeitung von Geschäftsregeln", "correct": true, "because": "Kernaufgabe"}, {"text": "Datenvalidierung", "correct": true, "because": "Sichert Datenintegrität"}, {"text": "Anwendungslogik", "correct": true, "because": "Hauptfunktion"}, {"text": "Benutzeroberflächen-Design", "correct": false, "because": "Präsentationsschicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es beim Einsatz des 3-Schichten-Modells?', 3, '[{"text": "Kommunikationsoverhead", "correct": true, "because": "Schichten erhöhen Latenz"}, {"text": "Komplexität bei kleinen Projekten", "correct": true, "because": "Aufwand kann übermäßig sein"}, {"text": "Abhängigkeit zwischen Schichten", "correct": true, "because": "Kopplung möglich"}, {"text": "Geringere Flexibilität", "correct": false, "because": "Eher flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien werden typischerweise im 3-Schichten-Modell eingesetzt?', 3, '[{"text": "HTML/CSS für Präsentation", "correct": true, "because": "Web-Oberflächen"}, {"text": "Java für Logik", "correct": true, "because": "Häufige Anwendungslogik"}, {"text": "SQL für Daten", "correct": true, "because": "Datenbankzugriff"}, {"text": "Assembly für Netzwerk", "correct": false, "because": "Kein Teil des Modells"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Präsentationsschicht im 3-Schichten-Modell zeigt die Benutzeroberfläche an. b) Sie greift direkt auf die Datenbank zu.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Anzeige ja, direkter Zugriff nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Logikschicht enthält die Geschäftslogik. b) Das 3-Schichten-Modell erfordert physische Trennung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Logik ja, physische Trennung nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Datenschicht verwaltet Datenbankzugriffe. b) Sie ist für die Benutzerinteraktion zuständig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Daten ja, Interaktion nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Das 3-Schichten-Modell fördert Modularität. b) Es ist nur für große Anwendungen geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Modularität ja, Größe flexibel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Kommunikationsoverhead ist eine Herausforderung im 3-Schichten-Modell. b) Alle Schichten müssen unterschiedliche Sprachen nutzen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Overhead ja, Sprachen flexibel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

