INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Trends > Maßnahmen zur aktiven Information durch Newsfeeds oder Newsletter einleiten
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Einleitung von Newsfeeds oder Newslettern zwingend erforderlich, um über Trends informiert zu bleiben?', 2, '[{"text": "Nein", "correct": true, "because": "Andere Quellen wie Fachmessen oder Studien sind ebenfalls effektiv"}, {"text": "Ja", "correct": false, "because": "Nicht die einzige Methode"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Newsfeeds oder Newsletter allein alle relevanten Trends eines Unternehmens abdecken?', 2, '[{"text": "Nein", "correct": true, "because": "Sie bieten nur einen Ausschnitt und erfordern Ergänzung"}, {"text": "Ja", "correct": false, "because": "Begrenzte Reichweite und Tiefe"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Nutzung von Newsfeeds oder Newslettern eine proaktive Maßnahme zur Trendinformation?', 2, '[{"text": "Ja", "correct": true, "because": "Sie liefern regelmäßig aktuelle Informationen"}, {"text": "Nein", "correct": false, "because": "Proaktivität ist gegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Newsfeeds oder Newsletter immer branchenspezifisch sein, um nützlich zu sein?', 2, '[{"text": "Nein", "correct": true, "because": "Allgemeine Trends können ebenfalls Einfluss haben"}, {"text": "Ja", "correct": false, "because": "Breitere Perspektiven sind wertvoll"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Informationsbeschaffung durch Newsfeeds oder Newsletter Datenschutzrisiken bergen?', 2, '[{"text": "Ja", "correct": true, "because": "Abonnements erfordern oft persönliche Daten"}, {"text": "Nein", "correct": false, "because": "Risiken sind vorhanden"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil von Newsfeeds oder Newslettern ist für die Trendinformation am bedeutendsten?', 2, '[{"text": "Regelmäßige Updates", "correct": true, "because": "Halten stets aktuell"}, {"text": "Kosteneffizienz", "correct": false, "because": "Sekundär relevant"}, {"text": "Interaktivität", "correct": false, "because": "Weniger zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Quelle ist für die Einleitung von Newsfeeds oder Newslettern am häufigsten genutzt?', 3, '[{"text": "Fachmedien", "correct": true, "because": "Bieten spezifische und verlässliche Inhalte"}, {"text": "Soziale Medien", "correct": false, "because": "Ungefiltert und volatil"}, {"text": "Interne Berichte", "correct": false, "because": "Begrenzt auf Unternehmen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Risiko ist bei der Nutzung von Newsfeeds oder Newslettern am kritischsten?', 2, '[{"text": "Informationsüberflutung", "correct": true, "because": "Kann Fokus erschweren"}, {"text": "Technische Ausfälle", "correct": false, "because": "Weniger häufig"}, {"text": "Kostensteigerung", "correct": false, "because": "Meist gering"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme optimiert die Informationsbeschaffung durch Newsfeeds oder Newsletter?', 2, '[{"text": "Filterung nach Relevanz", "correct": true, "because": "Reduziert Überfluss"}, {"text": "Häufigere Veröffentlichung", "correct": false, "because": "Kann überfordern"}, {"text": "Automatische Übersetzung", "correct": false, "because": "Sekundär nützlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt sollte bei der Auswahl von Newsfeeds oder Newslettern primär beachtet werden?', 2, '[{"text": "Verlässlichkeit der Quelle", "correct": true, "because": "Sichert Qualität der Information"}, {"text": "Kostenfreiheit", "correct": false, "because": "Qualität überwiegt"}, {"text": "Visuelle Gestaltung", "correct": false, "because": "Weniger entscheidend"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Newsfeeds oder Newsletter für die Trendinformation?', 4, '[{"text": "Aktuelle Informationen", "correct": true, "because": "Regelmäßige Updates"}, {"text": "Zugang zu Expertenwissen", "correct": true, "because": "Fachquellen nutzbar"}, {"text": "Automatische Zustellung", "correct": true, "because": "Reduziert Aufwand"}, {"text": "Hohe Druckqualität", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Quellen sind für Newsfeeds oder Newsletter zur Trendinformation geeignet?', 3, '[{"text": "Branchenverbände", "correct": true, "because": "Spezifisches Wissen"}, {"text": "Fachzeitschriften", "correct": true, "because": "Tiefgehende Analysen"}, {"text": "Technologieblogs", "correct": true, "because": "Aktuelle Trends"}, {"text": "Private Tagebücher", "correct": false, "because": "Unprofessionell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen können bei der Nutzung von Newsfeeds oder Newslettern auftreten?', 4, '[{"text": "Informationsüberflutung", "correct": true, "because": "Zu viele Daten"}, {"text": "Fehlende Relevanz", "correct": true, "because": "Nicht immer passend"}, {"text": "Datenschutzrisiken", "correct": true, "because": "Persönliche Daten nötig"}, {"text": "Hohe Druckkosten", "correct": false, "because": "Digital, nicht physisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren sollten bei der Auswahl von Newsfeeds oder Newslettern berücksichtigt werden?', 3, '[{"text": "Aktualität", "correct": true, "because": "Trends sind zeitkritisch"}, {"text": "Glaubwürdigkeit", "correct": true, "because": "Verlässlichkeit entscheidend"}, {"text": "Spezialisierung", "correct": true, "because": "Relevanz für Branche"}, {"text": "Farbschema", "correct": false, "because": "Ästhetik sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen verbessern die Effektivität von Newsfeeds oder Newslettern?', 3, '[{"text": "Personalisierung", "correct": true, "because": "Erhöht Relevanz"}, {"text": "Regelmäßige Analyse", "correct": true, "because": "Optimiert Nutzung"}, {"text": "Kuratierte Inhalte", "correct": true, "because": "Filtert Wichtiges"}, {"text": "Höhere Lautstärke", "correct": false, "because": "Nicht anwendbar"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Newsfeeds oder Newsletter bieten aktuelle Trendinformationen. b) Sie sind die einzige Informationsquelle für Trends.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Aktuell ja, einzige Quelle nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Newsfeeds oder Newsletter können Datenschutzrisiken bergen. b) Sie sind immer kostenfrei verfügbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Risiken ja, kostenfrei nicht immer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Nutzung von Newsfeeds oder Newslettern ist proaktiv. b) Sie ersetzen vollständig andere Informationsquellen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Proaktiv ja, Ersatz nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Newsfeeds oder Newsletter sollten glaubwürdig sein. b) Ihre Relevanz ist für alle Branchen gleich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Glaubwürdigkeit ja, Relevanz variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Personalisierung verbessert Newsfeeds oder Newsletter. b) Sie sind unabhängig von externen Quellen nutzbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Personalisierung ja, externe Quellen nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

