INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Konfiguration eines Access Points notwendig, um ein WLAN einzurichten?', 2, '[{"text": "Ja", "correct": true, "because": "Ein Access Point ist zentral für die WLAN-Verbindung"}, {"text": "Nein", "correct": false, "because": "Konfiguration ist erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein WLAN-Netzwerk immer mit einer Verschlüsselung gesichert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Verschlüsselung schützt vor unbefugtem Zugriff"}, {"text": "Nein", "correct": false, "because": "Sicherheit ist Best Practice"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein WLAN-Netzwerk ohne SSID eingerichtet werden?', 2, '[{"text": "Nein", "correct": true, "because": "Die SSID identifiziert das Netzwerk"}, {"text": "Ja", "correct": false, "because": "SSID ist zwingend erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Verwendet die WLAN-Einrichtung den IEEE 802.11-Standard?', 2, '[{"text": "Ja", "correct": true, "because": "IEEE 802.11 ist die Basis für WLAN"}, {"text": "Nein", "correct": false, "because": "802.11 ist der Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es möglich, ein WLAN-Netzwerk ohne Passwort zu konfigurieren?', 2, '[{"text": "Ja", "correct": true, "because": "Technisch möglich, aber unsicher"}, {"text": "Nein", "correct": false, "because": "Passwort ist optional"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Frequenz wird von modernen WLAN-Netzwerken am häufigsten genutzt?', 2, '[{"text": "5 GHz", "correct": true, "because": "5 GHz bietet höhere Geschwindigkeit und weniger Störungen"}, {"text": "2,4 GHz", "correct": false, "because": "Älter, mehr Störungen"}, {"text": "60 GHz", "correct": false, "because": "Nur bei speziellen Standards wie 802.11ad"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Sicherheitsstandard ist für die WLAN-Einrichtung aktuell empfohlen?', 3, '[{"text": "WPA3", "correct": true, "because": "WPA3 ist der neueste und sicherste Standard"}, {"text": "WPA2", "correct": false, "because": "Noch sicher, aber älter"}, {"text": "WEP", "correct": false, "because": "Veraltet und unsicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponente ist für die WLAN-Einrichtung zentral?', 2, '[{"text": "Access Point", "correct": true, "because": "Verbindet Geräte drahtlos"}, {"text": "Switch", "correct": false, "because": "Für kabelgebundene Netzwerke"}, {"text": "Router", "correct": false, "because": "Router ergänzt, ist aber nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher WLAN-Standard unterstützt Wi-Fi 6?', 2, '[{"text": "802.11ax", "correct": true, "because": "802.11ax ist Wi-Fi 6"}, {"text": "802.11n", "correct": false, "because": "Wi-Fi 4"}, {"text": "802.11ac", "correct": false, "because": "Wi-Fi 5"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist der Zweck der SSID bei der WLAN-Einrichtung?', 2, '[{"text": "Netzwerk identifizieren", "correct": true, "because": "SSID ist der Netzwerkname"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Das macht WPA"}, {"text": "IP-Adressen vergeben", "correct": false, "because": "Das macht DHCP"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Frequenzbänder können bei der WLAN-Einrichtung genutzt werden?', 4, '[{"text": "2,4 GHz", "correct": true, "because": "Weit verbreitet, größere Reichweite"}, {"text": "5 GHz", "correct": true, "because": "Schneller, weniger Störungen"}, {"text": "60 GHz", "correct": true, "because": "Für 802.11ad/ay, sehr schnell"}, {"text": "10 GHz", "correct": false, "because": "Nicht für WLAN"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Sicherheitsmaßnahmen sollten bei der WLAN-Einrichtung konfiguriert werden?', 3, '[{"text": "WPA3-Verschlüsselung", "correct": true, "because": "Höchste Sicherheit"}, {"text": "Starkes Passwort", "correct": true, "because": "Schützt vor Zugriff"}, {"text": "SSID ausblenden", "correct": true, "because": "Erschwert Auffinden"}, {"text": "WEP-Verschlüsselung", "correct": false, "because": "Unsicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind für die WLAN-Einrichtung erforderlich?', 4, '[{"text": "Access Point", "correct": true, "because": "Zentrale Verbindungseinheit"}, {"text": "WLAN-Adapter", "correct": true, "because": "Für Client-Geräte"}, {"text": "Router", "correct": true, "because": "Verbindet WLAN mit Internet"}, {"text": "Koaxialkabel", "correct": false, "because": "Nicht für WLAN"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die WLAN-Leistung bei der Einrichtung?', 3, '[{"text": "Frequenzband", "correct": true, "because": "2,4 GHz vs. 5 GHz"}, {"text": "Kanalwahl", "correct": true, "because": "Vermeidet Überlappung"}, {"text": "Reichweite", "correct": true, "because": "Signalstärke nimmt ab"}, {"text": "Kabellänge", "correct": false, "because": "Nicht relevant für WLAN"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die WLAN-Einrichtung?', 3, '[{"text": "Mobilität", "correct": true, "because": "Keine Kabel nötig"}, {"text": "Einfache Erweiterung", "correct": true, "because": "Neue Geräte leicht hinzufügbar"}, {"text": "Hohe Kosten", "correct": false, "because": "Kosten sind oft niedrig"}, {"text": "Flexibilität", "correct": true, "because": "Anpassbar an Bedarf"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die WLAN-Einrichtung basiert auf IEEE 802.11. b) WPA2 ist unsicherer als WEP.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "802.11 ja, WPA2 sicherer als WEP"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die SSID muss bei der WLAN-Einrichtung festgelegt werden. b) 5 GHz hat eine größere Reichweite als 2,4 GHz.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SSID ja, 5 GHz geringere Reichweite"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) WPA3 ist der aktuellste Sicherheitsstandard. b) Ein Access Point ist für jedes WLAN zwingend erforderlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "WPA3 ja, Ad-hoc-Modus möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Kanalwahl beeinflusst die WLAN-Leistung. b) Ein Passwort ist bei der WLAN-Einrichtung optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kanalwahl ja, Passwort empfohlen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch (Sicherheit)"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) 802.11ax bietet höhere Geschwindigkeiten als 802.11ac. b) Die SSID dient der Datenverschlüsselung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "802.11ax ja, SSID identifiziert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

