-- IT-Sicherheit und Datenschutz: Technische Maßnahmen - Virenschutz
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Virenschutz eine technische Maßnahme zur IT-Sicherheit?', 2, '[{"text": "Ja", "correct": true, "because": "Schützt vor Schadsoftware"}, {"text": "Nein", "correct": false, "because": "Er ist zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt Virenschutz?', 3, '[{"text": "Erkennung und Entfernung von Schadsoftware", "correct": true, "because": "Sichert Systeme"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Andere Maßnahme"}, {"text": "Netzwerk trennen", "correct": false, "because": "Keine Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Virenschutz schützt vor Malware. b) Er ist nur für Netzwerke relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, auch lokal"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktionen hat ein Virenschutz?', 4, '[{"text": "Virenscans", "correct": true, "because": "Erkennt Schadsoftware"}, {"text": "Unklare Prozesse", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Echtzeitschutz", "correct": true, "because": "Überwacht laufend"}, {"text": "Quarantäne", "correct": true, "because": "Isoliert Bedrohungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein System ohne Virenschutz sicher sein?', 2, '[{"text": "Nein", "correct": true, "because": "Malware-Risiko"}, {"text": "Ja", "correct": false, "because": "Unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt Virenschutz im Datenschutz?', 3, '[{"text": "Schützt sensible Daten vor Malware", "correct": true, "because": "Sichert Integrität"}, {"text": "Datenverfügbarkeit", "correct": false, "because": "Anderes Schutzziel"}, {"text": "Identität prüfen", "correct": false, "because": "Authentifizierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Virenschutz nur für Endgeräte relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Server"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat der Echtzeitschutz?', 3, '[{"text": "Kontinuierliche Überwachung auf Malware", "correct": true, "because": "Sofortige Erkennung"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Andere Maßnahme"}, {"text": "Netzwerk trennen", "correct": false, "because": "Keine Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Virenschutz benötigt regelmäßige Updates. b) Er schützt vor allen Bedrohungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, nicht vollständig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Virenschutz?', 3, '[{"text": "Systeme anfällig für Malware", "correct": true, "because": "Kein Schutz"}, {"text": "Daten schneller übertragen", "correct": false, "because": "Unsinn"}, {"text": "Systeme sicherer", "correct": false, "because": "Gegenteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Virenschutz ohne Updates wirksam sein?', 2, '[{"text": "Nein", "correct": true, "because": "Neue Bedrohungen unerkannt"}, {"text": "Ja", "correct": false, "because": "Ineffektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine Virenschutzfunktion?', 3, '[{"text": "Scan auf Trojaner", "correct": true, "because": "Konkret und real"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Andere Maßnahme"}, {"text": "Netzwerk trennen", "correct": false, "because": "Andere Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Virenschutz nur für Windows-Systeme relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Linux, macOS"}, {"text": "Ja", "correct": false, "because": "Breite Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat ein guter Virenschutz?', 4, '[{"text": "Regelmäßige Updates", "correct": true, "because": "Aktuelle Bedrohungen"}, {"text": "Unklare Scans", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Echtzeitschutz", "correct": true, "because": "Sofortige Reaktion"}, {"text": "Heuristische Analyse", "correct": true, "because": "Erkennt neue Malware"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss Virenschutz ständig laufen?', 2, '[{"text": "Ja", "correct": true, "because": "Echtzeitschutz nötig"}, {"text": "Nein", "correct": false, "because": "Ineffektiv ohne"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Quarantäne?', 3, '[{"text": "Isoliert erkannte Bedrohungen", "correct": true, "because": "Verhindert Schaden"}, {"text": "Daten löschen", "correct": false, "because": "Optionale Folge"}, {"text": "Identität prüfen", "correct": false, "because": "Authentifizierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Virenschutz ohne Internet arbeiten?', 2, '[{"text": "Ja", "correct": true, "because": "Lokale Scans möglich"}, {"text": "Nein", "correct": false, "because": "Updates fehlen langfristig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor gefährdet den Virenschutz?', 3, '[{"text": "Veraltete Signaturen", "correct": true, "because": "Neue Malware unerkannt"}, {"text": "Schnelles Netzwerk", "correct": false, "because": "Irrelevant"}, {"text": "Gute Passwörter", "correct": false, "because": "Unterstützt Sicherheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Virenschutz schützt vor Ransomware. b) Er ist nur für Server relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, auch Endgeräte"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen von Virenschutz?', 3, '[{"text": "Schutz vor Schadsoftware", "correct": true, "because": "Sichert Daten"}, {"text": "Maximale Infektion", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Datensicherheit", "correct": false, "because": "Fördert Schutz"}]');

