-- Technik: Hardware - Geräteklassen - Desktops
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Gehören Desktops zu den Geräteklassen der Hardware?', 2, '[{"text": "Ja", "correct": true, "because": "Sind stationäre Computer"}, {"text": "Nein", "correct": false, "because": "Sie sind zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptmerkmal charakterisiert einen Desktop?', 3, '[{"text": "Stationäre Nutzung", "correct": true, "because": "Nicht mobil"}, {"text": "Hohe Mobilität", "correct": false, "because": "Laptop-Merkmal"}, {"text": "Nur Serverfunktion", "correct": false, "because": "Andere Klasse"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Desktops bestehen aus separaten Komponenten. b) Sie sind immer tragbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, nicht mobil"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören typischerweise zu einem Desktop?', 4, '[{"text": "Monitor", "correct": true, "because": "Darstellung"}, {"text": "Unklare Teile", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Systemeinheit", "correct": true, "because": "Hauptgehäuse"}, {"text": "Tastatur", "correct": true, "because": "Eingabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Desktop ohne Monitor betrieben werden?', 2, '[{"text": "Ja", "correct": true, "because": "Nur Systemeinheit nötig"}, {"text": "Nein", "correct": false, "because": "Flexibilität möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt ein Desktop in der IT?', 3, '[{"text": "Arbeitsplatzrechner für Nutzer", "correct": true, "because": "Fördert Produktivität"}, {"text": "Nur Serverfunktion", "correct": false, "because": "Andere Geräteklasse"}, {"text": "Mobile Datenspeicherung", "correct": false, "because": "Laptop-Merkmal"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Desktops nur für private Nutzung geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Auch in Unternehmen genutzt"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaft unterscheidet Desktops von Laptops?', 3, '[{"text": "Stationäre Bauweise", "correct": true, "because": "Nicht tragbar"}, {"text": "Integrierter Akku", "correct": false, "because": "Laptop-Merkmal"}, {"text": "Geringere Leistung", "correct": false, "because": "Oft leistungsstärker"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Desktops sind modular erweiterbar. b) Sie haben immer einen Akku.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, kein Akku"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Systemeinheit bei einem Desktop?', 3, '[{"text": "Desktop funktioniert nicht", "correct": true, "because": "Kernkomponente fehlt"}, {"text": "Monitor arbeitet allein", "correct": false, "because": "Unmöglich"}, {"text": "Leistung steigt", "correct": false, "because": "Unsinn"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Desktop als Server genutzt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Mit passender Hardware"}, {"text": "Nein", "correct": false, "because": "Flexibilität möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine Desktop-Komponente?', 3, '[{"text": "Grafikkarte in Systemeinheit", "correct": true, "because": "Konkret und real"}, {"text": "Irgendwas anschließen", "correct": false, "because": "Zu vage"}, {"text": "Team soll etwas nutzen", "correct": false, "because": "Keine Komponente"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Desktops nur für Einzelnutzer gedacht?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Mehrnutzer möglich"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat ein typischer Desktop?', 4, '[{"text": "Hohe Leistung", "correct": true, "because": "Für komplexe Aufgaben"}, {"text": "Kleine Größe", "correct": false, "because": "Eher größer"}, {"text": "Erweiterbarkeit", "correct": true, "because": "Modular aufgebaut"}, {"text": "Externer Stromanschluss", "correct": true, "because": "Kein Akku"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Desktop immer einen Monitor haben?', 2, '[{"text": "Nein", "correct": true, "because": "Optional anschließbar"}, {"text": "Ja", "correct": false, "because": "Flexibilität möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Systemeinheit?', 3, '[{"text": "Hauptverarbeitung des Desktops", "correct": true, "because": "Enthält CPU"}, {"text": "Nur Bildschirmdarstellung", "correct": false, "because": "Monitoraufgabe"}, {"text": "Mobile Stromversorgung", "correct": false, "because": "Laptop-Merkmal"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Desktop ohne Tastatur betrieben werden?', 2, '[{"text": "Ja", "correct": true, "because": "Alternative Eingaben möglich"}, {"text": "Nein", "correct": false, "because": "Flexibilität gegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor beeinflusst die Leistung eines Desktops?', 3, '[{"text": "Prozessorleistung", "correct": true, "because": "Kernkomponente"}, {"text": "Monitorgröße", "correct": false, "because": "Kein Leistungsfaktor"}, {"text": "Tastaturlayout", "correct": false, "because": "Nur Eingabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Desktops sind für Büroarbeit geeignet. b) Sie sind immer teurer als Laptops.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, variabel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen von Desktops?', 3, '[{"text": "Hohe Anpassungsfähigkeit", "correct": true, "because": "Fördert Flexibilität"}, {"text": "Maximale Mobilität", "correct": false, "because": "Laptop-Merkmal"}, {"text": "Keine Erweiterung", "correct": false, "because": "Modular möglich"}]');

