-- Datenflussdiagramm.sql (Wichtig für Datenfluss und Prozessmodellierung, auch als DFD bekannt, z. B. Datenströme zwischen Prozessen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Datenflussdiagramm nur für Softwareentwicklung geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Geschäftsprozesse nützlich"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Datenflussdiagramm?', 3, '[{"text": "Datenfluss visualisieren", "correct": true, "because": "Zeigt Datenströme zwischen Prozessen"}, {"text": "Hardwarezuordnung", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Code-Optimierung", "correct": false, "because": "Kein Programmierfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem Datenflussdiagramm?', 5, '[{"text": "Prozesse", "correct": true, "because": "Datenverarbeitungsschritte"}, {"text": "Datenströme", "correct": true, "because": "Zeigen Datenbewegung"}, {"text": "Farbanimation", "correct": false, "because": "Irrelevant"}, {"text": "Hardwareknoten", "correct": false, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Datenflussdiagramme zeigen Prozesse. b) Sie ersetzen ERM-Diagramme.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "ERM für Datenstruktur"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Datenflussdiagramm?', 4, '[{"text": "Datenströme", "correct": false, "because": "Kern des Diagramms"}, {"text": "Prozesse", "correct": false, "because": "Zeigen Datenverarbeitung"}, {"text": "UI-Design", "correct": true, "because": "Kein Datenflussaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Datenflussdiagramm auch Hardware zeigt?', 2, '[{"text": "Nein", "correct": true, "because": "Fokus auf Daten, nicht Hardware"}, {"text": "Ja", "correct": false, "because": "Verteilungsdiagramm-Thema"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Symbol wähle ich für einen Prozess im Datenflussdiagramm?', 3, '[{"text": "Kreis", "correct": true, "because": "DFD-Standard für Prozesse"}, {"text": "Pfeil", "correct": false, "because": "Datenstrom"}, {"text": "Rechteck", "correct": false, "because": "Datenspeicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zu einem Datenflussdiagramm?', 5, '[{"text": "Externe Entitäten", "correct": true, "because": "Datenquellen/-senken"}, {"text": "Datenspeicher", "correct": true, "because": "Speichern Daten"}, {"text": "Schnittstellen", "correct": false, "because": "Komponentendiagramm"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Datenflussdiagramme zeigen Datenbewegung. b) Sie sind für Hardwareplanung wichtig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware ist Verteilungsdiagramm"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Datenflussdiagramm?', 4, '[{"text": "Prozesse", "correct": false, "because": "Verarbeiten Daten"}, {"text": "Datenströme", "correct": false, "because": "Zeigen Datenfluss"}, {"text": "Netzwerkknoten", "correct": true, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Datenflussdiagramm nur für Software?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Geschäftsprozesse"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beziehungen nutze ich im Datenflussdiagramm?', 4, '[{"text": "Datenströme", "correct": true, "because": "Verbinden Prozesse"}, {"text": "Externe Entitäten", "correct": true, "because": "Datenquellen/-senken"}, {"text": "Abhängigkeiten", "correct": false, "because": "Komponentendiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Datenflussdiagramme nur Datenstruktur zeigen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Fokus auf Datenfluss"}, {"text": "Ja", "correct": false, "because": "ERM-Thema"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Datenflussdiagramm?', 3, '[{"text": "Klarheit des Datenflusses", "correct": true, "because": "Fördert Verständnis"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Qualität zählt"}, {"text": "Visuelle Effekte", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) DFDs zeigen Prozessinteraktionen. b) Sie ersetzen Zustandsdiagramme.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zustände sind anders"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Datenflussdiagramm?', 5, '[{"text": "Datenübersicht", "correct": true, "because": "Klarheit über Datenbewegung"}, {"text": "Prozessverständnis", "correct": true, "because": "Interaktionen sichtbar"}, {"text": "Hardwareplanung", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Code-Details", "correct": false, "because": "Nicht im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist im Datenflussdiagramm unwichtig?', 3, '[{"text": "Datenströme", "correct": false, "because": "Kern der Darstellung"}, {"text": "Datenspeicher", "correct": false, "because": "Zeigen Datenhaltung"}, {"text": "Blinkende Icons", "correct": true, "because": "Kein Datenflussaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Zeigt ein Datenflussdiagramm auch Hardware?', 3, '[{"text": "Nein", "correct": true, "because": "Fokus auf Datenfluss"}, {"text": "Ja", "correct": false, "because": "Hardware in Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob DFDs für Tests nützlich sind?', 2, '[{"text": "Ja", "correct": true, "because": "Definieren Datenflusstests"}, {"text": "Nein", "correct": false, "because": "Testfälle ableitbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Symbol wähle ich für einen Datenspeicher?', 4, '[{"text": "Zwei parallele Linien", "correct": true, "because": "DFD-Standard"}, {"text": "Pfeil", "correct": false, "because": "Datenstrom"}, {"text": "Kreis", "correct": false, "because": "Prozess"}]');

