-- Nassi-Shneiderman-Diagramm.sql (Zentral für strukturierte Programmabläufe, z. B. blockbasierte Darstellung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Nassi-Shneiderman-Diagramm nur für komplexe Programme sinnvoll?', 2, '[{"text": "Nein", "correct": true, "because": "Auch einfache Abläufe klar darstellbar"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Nassi-Shneiderman-Diagramm?', 3, '[{"text": "Strukturierte Ablaufvisualisierung", "correct": true, "because": "Blockbasierte Darstellung"}, {"text": "Datenmodellierung", "correct": false, "because": "ERM-Thema"}, {"text": "Hardwareplanung", "correct": false, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem Nassi-Shneiderman-Diagramm?', 5, '[{"text": "Prozessblöcke", "correct": true, "because": "Zeigen Ablaufsequenzen"}, {"text": "Entscheidungen", "correct": true, "because": "Steuern Verzweigungen"}, {"text": "Farbanimation", "correct": false, "because": "Irrelevant"}, {"text": "Komponenten", "correct": false, "because": "Komponentendiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Nassi-Shneiderman zeigt Abläufe blockweise. b) Es ersetzt Programmablaufpläne.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Alternative, kein Ersatz"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Nassi-Shneiderman-Diagramm?', 4, '[{"text": "Prozessschritte", "correct": false, "because": "Kern der Darstellung"}, {"text": "Verzweigungen", "correct": false, "because": "Entscheidungen zeigen"}, {"text": "UI-Design", "correct": true, "because": "Kein Ablauffaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Nassi-Shneiderman-Diagramm auch Schleifen darstellt?', 2, '[{"text": "Ja", "correct": true, "because": "Blockweise Wiederholungen"}, {"text": "Nein", "correct": false, "because": "Schleifen sind enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Symbol wähle ich für eine Entscheidung?', 3, '[{"text": "Dreieck im Block", "correct": true, "because": "Standard für Verzweigungen"}, {"text": "Rechteck", "correct": false, "because": "Nur Prozessschritt"}, {"text": "Pfeil", "correct": false, "because": "Nur Verbindung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten verbessern ein Nassi-Shneiderman-Diagramm?', 5, '[{"text": "Prozessblöcke", "correct": true, "because": "Zeigen Schritte"}, {"text": "Schleifenblöcke", "correct": true, "because": "Wiederholungen klar"}, {"text": "Datenfluss", "correct": false, "because": "Datenflussdiagramm"}, {"text": "Farbcodierung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Nassi-Shneiderman ist für strukturierte Abläufe. b) Es zeigt Hardwarezuordnung. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware ist Verteilungsdiagramm"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Nassi-Shneiderman-Diagramm?', 4, '[{"text": "Entscheidungen", "correct": false, "because": "Steuern Ablauf"}, {"text": "Prozessblöcke", "correct": false, "because": "Grundlage der Darstellung"}, {"text": "Netzwerkknoten", "correct": true, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Nassi-Shneiderman-Diagramm nur für Software?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Geschäftsprozesse"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strukturen zeigt ein Nassi-Shneiderman-Diagramm?', 4, '[{"text": "Schleifen", "correct": true, "because": "Wiederholungen darstellen"}, {"text": "Bedingungen", "correct": true, "because": "Entscheidungen zeigen"}, {"text": "Datenfluss", "correct": false, "because": "Datenflussdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Nassi-Shneiderman-Diagramme veraltet sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Immer noch nützlich"}, {"text": "Ja", "correct": false, "because": "Strukturierte Darstellung aktuell"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Nassi-Shneiderman-Diagramm?', 3, '[{"text": "Klarheit der Struktur", "correct": true, "because": "Fördert Verständnis"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Qualität zählt"}, {"text": "Visuelle Effekte", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Nassi-Shneiderman zeigt Abläufe blockweise. b) Es ist für Hardwareplanung wichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware ist Verteilungsdiagramm"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Nassi-Shneiderman-Diagramm?', 5, '[{"text": "Übersichtliche Struktur", "correct": true, "because": "Blockweise klar"}, {"text": "Einfache Lesbarkeit", "correct": true, "because": "Logik verständlich"}, {"text": "Hardwarezuordnung", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Datenfluss", "correct": false, "because": "Datenflussdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Nassi-Shneiderman-Diagramm unwichtig?', 3, '[{"text": "Ablaufblöcke", "correct": false, "because": "Kern der Darstellung"}, {"text": "Entscheidungen", "correct": false, "because": "Steuern Logik"}, {"text": "3D-Grafiken", "correct": true, "because": "Kein Ablauffaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Nassi-Shneiderman-Diagramm Schleifen darstellen?', 3, '[{"text": "Ja", "correct": true, "because": "Blockweise Wiederholungen"}, {"text": "Nein", "correct": false, "because": "Schleifen sind enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Nassi-Shneiderman-Diagramm für Tests nützlich ist?', 2, '[{"text": "Ja", "correct": true, "because": "Testfälle ableitbar"}, {"text": "Nein", "correct": false, "because": "Ablauf hilft bei Tests"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Symbol wähle ich für einen Prozessschritt?', 4, '[{"text": "Rechteck", "correct": true, "because": "Standard für Aktionen"}, {"text": "Pfeil", "correct": false, "because": "Nur Verbindung"}, {"text": "Raute", "correct": false, "because": "Entscheidungen"}]');

