-- # Lernfeld 5: Cyberphysische Systeme > ## IT-Sicherheit > - Sicherheit > - + Datenlöschung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann eine einfache Dateilöschung im Betriebssystem garantieren, dass Daten unwiederbringlich entfernt sind?', 2, '[{"text": "Nein", "correct": true, "because": "Daten bleiben auf Speichermedien bis zur Überschreibung"}, {"text": "Ja", "correct": false, "because": "Wiederherstellung ist möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die physische Zerstörung eines Speichermediums die einzige Methode, um Datenlöschung sicherzustellen?', 2, '[{"text": "Nein", "correct": true, "because": "Sicheres Überschreiben ist eine Alternative"}, {"text": "Ja", "correct": false, "because": "Softwarelösungen existieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Daten nach einer sicheren Löschung mit mehrfachem Überschreiben noch mit forensischen Tools wiederhergestellt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Mehrfaches Überschreiben macht Wiederherstellung praktisch unmöglich"}, {"text": "Ja", "correct": false, "because": "Forensik scheitert bei korrekter Methode"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Daten auf SSDs genauso einfach sicher zu löschen wie auf HDDs?', 2, '[{"text": "Nein", "correct": true, "because": "SSDs nutzen Wear-Leveling, was Löschung erschwert"}, {"text": "Ja", "correct": false, "because": "Technologische Unterschiede bestehen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine unsachgemäße Datenlöschung rechtliche Konsequenzen nach DSGVO nach sich ziehen?', 2, '[{"text": "Ja", "correct": true, "because": "Datenschutzverletzungen sind strafbar"}, {"text": "Nein", "correct": false, "because": "DSGVO fordert sichere Löschung"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird typischerweise für die sichere Datenlöschung auf Festplatten empfohlen?', 2, '[{"text": "Mehrfaches Überschreiben", "correct": true, "because": "Überschreiben verhindert Wiederherstellung"}, {"text": "Formatierung", "correct": false, "because": "Daten bleiben wiederherstellbar"}, {"text": "Papierkorb leeren", "correct": false, "because": "Nur Verzeichnis gelöscht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Standard definiert eine sichere Datenlöschung durch mehrfaches Überschreiben?', 3, '[{"text": "DoD 5220.22-M", "correct": true, "because": "US-Standard mit mehreren Durchläufen"}, {"text": "ISO 27001", "correct": false, "because": "Allgemeiner Sicherheitsstandard"}, {"text": "GDPR", "correct": false, "because": "Reguliert Datenschutz, nicht Methoden"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die größte Herausforderung bei der Datenlöschung auf SSDs?', 2, '[{"text": "Wear-Leveling", "correct": true, "because": "Verteilt Daten unvorhersehbar"}, {"text": "Hohe Schreibgeschwindigkeit", "correct": false, "because": "Irrelevant für Löschung"}, {"text": "Kleine Speichergröße", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik ist für die sichere Löschung verschlüsselter Daten am effizientesten?', 2, '[{"text": "Schlüsselvernichtung", "correct": true, "because": "Ohne Schlüssel sind Daten unlesbar"}, {"text": "Physische Zerstörung", "correct": false, "because": "Aufwendiger"}, {"text": "Einfaches Überschreiben", "correct": false, "because": "Nicht nötig bei Verschlüsselung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme ist bei der Datenlöschung auf Cloud-Speichern am kritischsten?', 2, '[{"text": "Bestätigung des Anbieters", "correct": true, "because": "Cloud-Daten außerhalb direkter Kontrolle"}, {"text": "Lokales Überschreiben", "correct": false, "because": "Unwirksam in Cloud"}, {"text": "Dateikomprimierung", "correct": false, "because": "Irrelevant"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methoden gelten als sicher für die Datenlöschung auf magnetischen Medien?', 4, '[{"text": "Mehrfaches Überschreiben", "correct": true, "because": "Verhindert Wiederherstellung"}, {"text": "Degaussing", "correct": true, "because": "Entmagnetisiert Medium"}, {"text": "Einfache Formatierung", "correct": false, "because": "Daten bleiben lesbar"}, {"text": "Physische Zerstörung", "correct": true, "because": "Macht Zugriff unmöglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren erschweren die sichere Datenlöschung auf SSDs?', 3, '[{"text": "Wear-Leveling", "correct": true, "because": "Verteilt Daten unkontrolliert"}, {"text": "TRIM-Befehl", "correct": true, "because": "Markiert Daten nur als gelöscht"}, {"text": "Hohe Kapazität", "correct": false, "because": "Größe unerheblich"}, {"text": "Controller-Logik", "correct": true, "because": "Versteckt Datenreste"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken bestehen bei unsachgemäßer Datenlöschung?', 3, '[{"text": "Datenwiederherstellung", "correct": true, "because": "Daten bleiben zugänglich"}, {"text": "Rechtliche Verstöße", "correct": true, "because": "Verletzung von Datenschutzgesetzen"}, {"text": "Systemabsturz", "correct": false, "because": "Nicht direkt verknüpft"}, {"text": "Identitätsdiebstahl", "correct": true, "because": "Persönliche Daten gefährdet"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Techniken sind für die Datenlöschung in der Cloud relevant?', 4, '[{"text": "Schlüsselvernichtung", "correct": true, "because": "Macht Daten unlesbar"}, {"text": "Vertragsvereinbarungen", "correct": true, "because": "Anbieter muss Löschung garantieren"}, {"text": "Lokale Formatierung", "correct": false, "because": "Keine Kontrolle über Cloud"}, {"text": "Sichere API-Aufrufe", "correct": true, "because": "Löschung programmgesteuert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Standards oder Vorschriften beeinflussen die Anforderungen an Datenlöschung?', 3, '[{"text": "DSGVO", "correct": true, "because": "Fordert sichere Datenvernichtung"}, {"text": "NIST 800-88", "correct": true, "because": "Richtlinien für Medienbereinigung"}, {"text": "ISO 9001", "correct": false, "because": "Qualitätsmanagement, nicht Löschung"}, {"text": "Gutmann-Methode", "correct": true, "because": "Definiert Überschreibungsverfahren"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Einfaches Löschen im Dateiexplorer entspricht sicherer Datenlöschung. b) Degaussing ist auf SSDs anwendbar.', 3, '[{"text": "Beides falsch", "correct": true, "because": "Löschen unsicher, Degaussing nur magnetisch"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beides falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Mehrfaches Überschreiben ist auf SSDs weniger effektiv als auf HDDs. b) Schlüsselvernichtung macht verschlüsselte Daten unwiederbringlich.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "SSDs komplexer, Schlüsselverlust wirksam"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Datenlöschung in der Cloud erfordert physischen Zugriff. b) Unsachgemäße Löschung kann gegen Datenschutzgesetze verstoßen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Cloud virtuell, Verstöße möglich"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Forensische Tools können nach sicherer Löschung immer Daten wiederherstellen. b) Physische Zerstörung ist die einzige Methode für SSDs.', 3, '[{"text": "Beides falsch", "correct": true, "because": "Sichere Löschung wirksam, Alternativen für SSDs"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beides falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Gutmann-Methode überschreibt Daten 35 Mal. b) Sichere Datenlöschung ist optional unter der DSGVO.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Gutmann 35 Durchläufe, DSGVO fordert Löschung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

