-- # Lernfeld 5: Cyberphysische Systeme > ## IT-Sicherheit > - Sicherheit > - + Verschlüsselung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann Verschlüsselung allein einen Schutz vor Datenmanipulation während der Übertragung garantieren?', 2, '[{"text": "Nein", "correct": true, "because": "Integrität erfordert zusätzliche Mechanismen wie Hashing"}, {"text": "Ja", "correct": false, "because": "Verschlüsselung schützt nur Vertraulichkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist symmetrische Verschlüsselung immer schneller als asymmetrische Verschlüsselung bei gleicher Schlüssellänge?', 2, '[{"text": "Ja", "correct": true, "because": "Symmetrisch nutzt weniger komplexe Algorithmen"}, {"text": "Nein", "correct": false, "because": "Symmetrisch ist effizienter"}]'),
('00000000-0000-0000-0000-000000000000', 'Können verschlüsselte Daten ohne den richtigen Schlüssel jemals inhaltlich analysiert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Ohne Schlüssel bleibt Inhalt unzugänglich"}, {"text": "Ja", "correct": false, "because": "Analyse ohne Schlüssel unmöglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine Verschlüsselung mit einem 128-Bit-Schlüssel immer sicherer als eine mit einem 64-Bit-Schlüssel?', 2, '[{"text": "Ja", "correct": true, "because": "Längere Schlüssel erhöhen Brute-Force-Aufwand"}, {"text": "Nein", "correct": false, "because": "Schlüssellänge entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine perfekte Verschlüsselung durch quantenbasierte Angriffe kompromittiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Quantencomputer brechen bestimmte Algorithmen"}, {"text": "Nein", "correct": false, "because": "Quantenangriffe sind real"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Algorithmus wird typischerweise für symmetrische Verschlüsselung in modernen Systemen verwendet?', 2, '[{"text": "AES", "correct": true, "because": "Advanced Encryption Standard ist Standard"}, {"text": "RSA", "correct": false, "because": "Asymmetrisch"}, {"text": "MD5", "correct": false, "because": "Hashing, nicht Verschlüsselung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist der Hauptvorteil der asymmetrischen Verschlüsselung gegenüber der symmetrischen?', 3, '[{"text": "Sichere Schlüsselaustausch ohne vorherigen Kontakt", "correct": true, "because": "Public-Key löst Schlüsselaustauschproblem"}, {"text": "Höhere Geschwindigkeit", "correct": false, "because": "Asymmetrisch ist langsamer"}, {"text": "Einfachere Implementierung", "correct": false, "because": "Komplexer als symmetrisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Verschlüsselungstechnik wird primär für die Sicherung von HTTPS-Verbindungen eingesetzt?', 2, '[{"text": "TLS", "correct": true, "because": "Transport Layer Security ist Standard"}, {"text": "DES", "correct": false, "because": "Veraltet und unsicher"}, {"text": "SHA", "correct": false, "because": "Hashing, nicht Verschlüsselung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor bestimmt die Sicherheit einer Verschlüsselung am stärksten?', 2, '[{"text": "Schlüssellänge", "correct": true, "because": "Längere Schlüssel erhöhen Aufwand"}, {"text": "Datenmenge", "correct": false, "because": "Irrelevant für Sicherheit"}, {"text": "Übertragungsgeschwindigkeit", "correct": false, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schwäche weist die Verschlüsselung mit einem öffentlichen Schlüssel auf?', 2, '[{"text": "Abhängigkeit von der Sicherheit des privaten Schlüssels", "correct": true, "because": "Privater Schlüssel ist kritisch"}, {"text": "Langsame Entschlüsselung", "correct": false, "because": "Sekundär"}, {"text": "Unfähigkeit, große Daten zu verschlüsseln", "correct": false, "because": "Hybrid möglich"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind für eine sichere Verschlüsselung essenziell?', 4, '[{"text": "Starke Schlüssellänge", "correct": true, "because": "Erhöht Brute-Force-Aufwand"}, {"text": "Zufälligkeit des Schlüssels", "correct": true, "because": "Vermeidet Vorhersagbarkeit"}, {"text": "Hohe Komprimierung", "correct": false, "because": "Irrelevant für Sicherheit"}, {"text": "Widerstand gegen Kryptoanalyse", "correct": true, "because": "Schützt vor Angriffen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Algorithmen werden häufig für asymmetrische Verschlüsselung verwendet?', 3, '[{"text": "RSA", "correct": true, "because": "Standard für Public-Key"}, {"text": "ECC", "correct": true, "because": "Elliptische Kurven effizient"}, {"text": "AES", "correct": false, "because": "Symmetrisch"}, {"text": "Diffie-Hellman", "correct": true, "because": "Schlüsselaustausch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bedrohungen kann Verschlüsselung nicht direkt abwehren?', 3, '[{"text": "Phishing-Angriffe", "correct": true, "because": "Zielt auf Nutzer, nicht Daten"}, {"text": "Man-in-the-Middle ohne Zertifikatsprüfung", "correct": true, "because": "Schwache Authentifizierung"}, {"text": "Brute-Force-Angriffe", "correct": false, "because": "Starke Schlüssel widerstehen"}, {"text": "Social Engineering", "correct": true, "because": "Umgeht Technik"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die hybride Verschlüsselung?', 4, '[{"text": "Kombiniert Geschwindigkeit der symmetrischen Verschlüsselung", "correct": true, "because": "Effizient für große Daten"}, {"text": "Sicherer Schlüsselaustausch durch asymmetrische Verschlüsselung", "correct": true, "because": "Löst Austauschproblem"}, {"text": "Eliminiert alle Schwächen", "correct": false, "because": "Schwächen bleiben"}, {"text": "Optimal für kleine Datenmengen", "correct": true, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren könnten die Sicherheit einer Verschlüsselung gefährden?', 3, '[{"text": "Schwache Schlüsselgenerierung", "correct": true, "because": "Vorhersagbare Schlüssel unsicher"}, {"text": "Veraltete Algorithmen", "correct": true, "because": "Leichter zu brechen"}, {"text": "Hohe Übertragungsgeschwindigkeit", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Kompromittierter privater Schlüssel", "correct": true, "because": "Kern der Sicherheit"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Symmetrische Verschlüsselung eignet sich besser für große Datenmengen als asymmetrische. b) Asymmetrische Verschlüsselung benötigt keinen Schlüsselaustausch.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Symmetrisch effizienter, Austausch nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Verschlüsselung schützt Daten vor unbefugtem Zugriff, nicht vor Verlust. b) Ein 256-Bit-Schlüssel ist immer unknackbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schutz begrenzt, 256-Bit nicht absolut"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) TLS verwendet ausschließlich symmetrische Verschlüsselung. b) Quantencomputer bedrohen aktuelle Verschlüsselungsstandards.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "TLS hybrid, Quanten sind Bedrohung"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Sicherheit der Verschlüsselung hängt nur vom Algorithmus ab. b) Ein kompromittierter Schlüssel macht die Verschlüsselung nutzlos.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Algorithmus nicht allein, Schlüssel kritisch"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Verschlüsselung kann Datenintegrität ohne Hashing gewährleisten. b) AES ist für symmetrische und asymmetrische Verschlüsselung geeignet.', 3, '[{"text": "Beides falsch", "correct": true, "because": "Integrität braucht Hash, AES nur symmetrisch"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beides falsch"}]');

