INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Hardware > Auswahl und Komponenten > Drucker Funktion, Einsatz, Varianten > Etikettendrucker
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Können Etikettendrucker unabhängig von den Etikettenmaterialien ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Drucker müssen mit Etikettengröße und -typ kompatibel sein"}, {"text": "Ja", "correct": false, "because": "Material bestimmt Einsatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen bei der Auswahl eines Etikettendruckers immer die Druckauflösungsanforderungen berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Auflösung entscheidet über Lesbarkeit"}, {"text": "Nein", "correct": false, "because": "Anforderungen sind entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Druckgeschwindigkeit eines Etikettendruckers für alle Anwendungen irrelevant?', 2, '[{"text": "Nein", "correct": true, "because": "Geschwindigkeit wichtig bei hohem Volumen"}, {"text": "Ja", "correct": false, "because": "Effizienz hängt davon ab"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Etikettendrucker ohne Rücksicht auf die Softwarekompatibilität ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Software muss Designs unterstützen"}, {"text": "Ja", "correct": false, "because": "Kompatibilität ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Etikettendrucker mit Thermotransfertechnologie immer teurer als Direktthermodrucker?', 2, '[{"text": "Ja", "correct": true, "because": "Thermotransfer benötigt zusätzliche Bänder"}, {"text": "Nein", "correct": false, "because": "Preisunterschied ist üblich"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor ist bei der Auswahl eines Etikettendruckers am wichtigsten?', 3, '[{"text": "Nutzungsanforderungen", "correct": true, "because": "Bestimmen Auflösung und Typ"}, {"text": "Marke", "correct": false, "because": "Sekundär"}, {"text": "Farbe", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schnittstelle wird für moderne Etikettendrucker am häufigsten verwendet?', 2, '[{"text": "USB", "correct": true, "because": "Universeller Standard"}, {"text": "Parallelport", "correct": false, "because": "Veraltet"}, {"text": "Serial", "correct": false, "because": "Weniger gebräuchlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie eignet sich am besten für langlebige Etiketten?', 2, '[{"text": "Thermotransfer", "correct": true, "because": "Haltbarer durch Farbband"}, {"text": "Direktthermo", "correct": false, "because": "Weniger langlebig"}, {"text": "Tintenstrahl", "correct": false, "because": "Weniger spezialisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einheit misst die Druckauflösung eines Etikettendruckers?', 3, '[{"text": "DPI", "correct": true, "because": "Dots per Inch gibt Detailgenauigkeit an"}, {"text": "PPM", "correct": false, "because": "Pages per Minute, für Geschwindigkeit"}, {"text": "GB", "correct": false, "because": "Speichergröße"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptvorteil von Netzwerk-Etikettendruckern?', 2, '[{"text": "Gemeinsame Nutzung", "correct": true, "because": "Mehrere Nutzer können zugreifen"}, {"text": "Geringere Kosten", "correct": false, "because": "Oft teurer"}, {"text": "Kleinere Größe", "correct": false, "because": "Nicht zwangsläufig"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte beeinflussen die Auswahl eines Etikettendruckers?', 4, '[{"text": "Etikettengröße", "correct": true, "because": "Bestimmt Druckbereich"}, {"text": "Druckauflösung", "correct": true, "because": "Beeinflusst Lesbarkeit"}, {"text": "Druckgeschwindigkeit", "correct": true, "because": "Wichtig für Volumen"}, {"text": "Gewicht des Druckers", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Thermotransfertechnologie?', 3, '[{"text": "Langlebige Etiketten", "correct": true, "because": "Widerstandsfähig gegen Umwelt"}, {"text": "Hohe Druckqualität", "correct": true, "because": "Präzise und klar"}, {"text": "Vielseitigkeit", "correct": true, "because": "Verschiedene Materialien möglich"}, {"text": "Geringere Kosten", "correct": false, "because": "Teurer als Direktthermo"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können bei der Auswahl eines Etikettendruckers auftreten?', 3, '[{"text": "Inkompatibilität mit Etiketten", "correct": true, "because": "Falsche Größe oder Material"}, {"text": "Unzureichende Auflösung", "correct": true, "because": "Unleserliche Etiketten"}, {"text": "Langsame Druckgeschwindigkeit", "correct": true, "because": "Ineffizient bei Volumen"}, {"text": "Falsche Farbe", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen profitieren von Etikettendruckern?', 4, '[{"text": "Logistik", "correct": true, "because": "Versandetiketten"}, {"text": "Einzelhandel", "correct": true, "because": "Preisschilder"}, {"text": "Produktion", "correct": true, "because": "Seriennummern"}, {"text": "Fotodruck", "correct": false, "because": "Andere Druckertypen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schnittstellen können Etikettendrucker unterstützen?', 3, '[{"text": "USB", "correct": true, "because": "Standardverbindung"}, {"text": "Ethernet", "correct": true, "because": "Für Netzwerkzugriff"}, {"text": "Bluetooth", "correct": true, "because": "Drahtlose Option"}, {"text": "HDMI", "correct": false, "because": "Für Video, nicht Drucker"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Thermotransferdrucker verwenden Farbbänder. b) Direktthermodrucker sind für dauerhafte Etiketten besser geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Farbbänder ja, Direktthermo weniger haltbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) DPI misst die Druckauflösung bei Etikettendruckern. b) Geschwindigkeit ist bei Einzelhandelsanwendungen irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DPI ja, Geschwindigkeit oft wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Etikettendrucker müssen mit der Software kompatibel sein. b) Alle Etikettendrucker unterstützen Farbdruck.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Software ja, Farbdruck nicht immer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Netzwerk-Etikettendrucker ermöglichen gemeinsame Nutzung. b) Thermotransfer ist schneller als Direktthermo.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Netzwerk ja, Geschwindigkeit ähnlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Etikettendrucker sind für Logistik essenziell. b) Auflösung ist bei Barcode-Etiketten unerheblich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Logistik ja, Auflösung für Barcodes wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

