INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Hardware > Auswahl und Komponenten > Drucker Funktion, Einsatz, Varianten > Matrixdrucker (Nadel- o. Punktmatrixdrucker)
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Können Matrixdrucker unabhängig vom Papiertyp ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Benötigen oft Durchschlagpapier"}, {"text": "Ja", "correct": false, "because": "Papierart ist entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen bei der Auswahl eines Matrixdruckers immer die Lautstärkeanforderungen berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Nadelmatrixdrucker sind oft laut"}, {"text": "Nein", "correct": false, "because": "Lautstärke ist relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Druckgeschwindigkeit eines Matrixdruckers für alle Anwendungen entscheidend?', 2, '[{"text": "Nein", "correct": true, "because": "Wichtiger bei hohem Volumen, weniger bei Qualität"}, {"text": "Ja", "correct": false, "because": "Geschwindigkeit nicht immer primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Matrixdrucker ohne Rücksicht auf die Verbrauchsmaterialien ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Farbbänder oder Nadeln müssen kompatibel sein"}, {"text": "Ja", "correct": false, "because": "Verbrauchsmaterialien sind essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Matrixdrucker immer langsamer als moderne Tintenstrahldrucker?', 2, '[{"text": "Ja", "correct": true, "because": "Mechanische Technik ist langsamer"}, {"text": "Nein", "correct": false, "because": "Geschwindigkeit ist typischerweise geringer"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor ist bei der Auswahl eines Matrixdruckers am wichtigsten?', 3, '[{"text": "Anwendungsanforderungen", "correct": true, "because": "Bestimmen Papier und Einsatz"}, {"text": "Marke", "correct": false, "because": "Sekundär"}, {"text": "Farbe", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie wird bei Matrixdruckern verwendet?', 2, '[{"text": "Nadelmatrix", "correct": true, "because": "Nadeln schlagen auf Farbband"}, {"text": "Laser", "correct": false, "because": "Andere Technologie"}, {"text": "Tintenstrahl", "correct": false, "because": "Nicht mechanisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Verbrauchsmaterial ist für Matrixdrucker essenziell?', 2, '[{"text": "Farbband", "correct": true, "because": "Überträgt Tinte aufs Papier"}, {"text": "Toner", "correct": false, "because": "Für Laserdrucker"}, {"text": "Tintenpatrone", "correct": false, "because": "Für Tintenstrahldrucker"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendung ist typisch für Matrixdrucker?', 3, '[{"text": "Durchschlagdruck", "correct": true, "because": "Für mehrlagiges Papier geeignet"}, {"text": "Fotodruck", "correct": false, "because": "Falsche Technologie"}, {"text": "Etikettendruck", "correct": false, "because": "Andere Drucker besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptvorteil von Matrixdruckern?', 2, '[{"text": "Durchschlagfähigkeit", "correct": true, "because": "Mehrere Kopien gleichzeitig"}, {"text": "Hohe Druckqualität", "correct": false, "because": "Eher gering"}, {"text": "Schnelle Druckzeit", "correct": false, "because": "Langsamer als moderne Drucker"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte beeinflussen die Auswahl eines Matrixdruckers?', 4, '[{"text": "Papierkompatibilität", "correct": true, "because": "Durchschlagpapier nötig"}, {"text": "Lautstärke", "correct": true, "because": "Lärm kann störend sein"}, {"text": "Verbrauchsmaterialien", "correct": true, "because": "Farbbänder erforderlich"}, {"text": "Gewicht des Druckers", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Matrixdrucker?', 3, '[{"text": "Durchschlagfähigkeit", "correct": true, "because": "Mehrere Kopien"}, {"text": "Geringe Betriebskosten", "correct": true, "because": "Einfache Materialien"}, {"text": "Robustheit", "correct": true, "because": "Langlebige Mechanik"}, {"text": "Hohe Auflösung", "correct": false, "because": "Eher gering"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile haben Matrixdrucker?', 3, '[{"text": "Hohe Lautstärke", "correct": true, "because": "Mechanischer Betrieb"}, {"text": "Langsame Druckgeschwindigkeit", "correct": true, "because": "Im Vergleich zu Laser"}, {"text": "Geringe Druckqualität", "correct": true, "because": "Nur Text geeignet"}, {"text": "Hohe Anschaffungskosten", "correct": false, "because": "Eher günstig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schnittstellen können Matrixdrucker unterstützen?', 4, '[{"text": "USB", "correct": true, "because": "Moderne Modelle"}, {"text": "Parallelport", "correct": true, "because": "Ältere Standards"}, {"text": "Serial", "correct": true, "because": "Frühere Verbindung"}, {"text": "HDMI", "correct": false, "because": "Für Video, nicht Drucker"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen sind typisch für Matrixdrucker?', 3, '[{"text": "Rechnungsdruck", "correct": true, "because": "Durchschlag für Kopien"}, {"text": "Logistikdokumente", "correct": true, "because": "Mehrlagiges Papier"}, {"text": "Formulardruck", "correct": true, "because": "Einfacher Textdruck"}, {"text": "Fotodruck", "correct": false, "because": "Nicht geeignet"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Matrixdrucker verwenden Nadeln für den Druck. b) Sie sind für hochauflösende Grafiken geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nadeln ja, Grafiken nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Matrixdrucker benötigen Farbbänder. b) Sie sind leiser als Tintenstrahldrucker.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Farbbänder ja, lauter als Tintenstrahl"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Matrixdrucker können Durchschlagpapier bedrucken. b) Ihre Druckgeschwindigkeit ist höher als die von Laserdruckern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Durchschlag ja, langsamer als Laser"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Matrixdrucker sind robust und langlebig. b) Sie eignen sich für den Fotodruck.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Robust ja, Fotodruck nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Matrixdrucker sind für Logistikdokumente geeignet. b) Sie haben geringere Betriebskosten als Laserdrucker.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Logistik ja, Betriebskosten niedriger"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides richtig"}]');

