INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Hardware > Auswahl und Komponenten > Drucker Funktion, Einsatz, Varianten > Plotter
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Können Plotter unabhängig von den Druckformaten ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Plotter müssen mit den benötigten Großformaten kompatibel sein"}, {"text": "Ja", "correct": false, "because": "Format ist entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen bei der Auswahl eines Plotters immer die Anforderungen an die Druckqualität berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Qualität entscheidet über Detailgenauigkeit"}, {"text": "Nein", "correct": false, "because": "Anforderungen sind zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Druckgeschwindigkeit eines Plotters für alle Anwendungen irrelevant?', 2, '[{"text": "Nein", "correct": true, "because": "Geschwindigkeit wichtig bei hohem Volumen"}, {"text": "Ja", "correct": false, "because": "Effizienz hängt davon ab"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Plotter ohne Rücksicht auf die Softwarekompatibilität ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Software steuert Druckprozess"}, {"text": "Ja", "correct": false, "because": "Kompatibilität ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Plotter immer teurer als Standarddrucker?', 2, '[{"text": "Ja", "correct": true, "because": "Spezialisierte Technik erhöht Kosten"}, {"text": "Nein", "correct": false, "because": "Preisunterschied ist üblich"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor ist bei der Auswahl eines Plotters am wichtigsten?', 3, '[{"text": "Druckanforderungen", "correct": true, "because": "Bestimmen Format und Qualität"}, {"text": "Marke", "correct": false, "because": "Sekundär"}, {"text": "Farbe", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie wird bei den meisten modernen Plottern verwendet?', 2, '[{"text": "Tintenstrahl", "correct": true, "because": "Hohe Präzision und Farbqualität"}, {"text": "Nadelmatrix", "correct": false, "because": "Veraltet"}, {"text": "Laser", "correct": false, "because": "Weniger üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Verbrauchsmaterial ist für Plotter typisch?', 2, '[{"text": "Tintenpatronen", "correct": true, "because": "Für Tintenstrahl-Plotter"}, {"text": "Toner", "correct": false, "because": "Für Laserdrucker"}, {"text": "Farbbänder", "correct": false, "because": "Für Matrixdrucker"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendung ist typisch für Plotter?', 3, '[{"text": "Technische Zeichnungen", "correct": true, "because": "Großformat und Präzision nötig"}, {"text": "Fotodruck", "correct": false, "because": "Andere Drucker besser"}, {"text": "Durchschlagdruck", "correct": false, "because": "Falsche Technologie"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptvorteil von Plottern?', 2, '[{"text": "Großformatdruck", "correct": true, "because": "Für Pläne und Poster geeignet"}, {"text": "Geringe Kosten", "correct": false, "because": "Oft teurer"}, {"text": "Hohe Geschwindigkeit", "correct": false, "because": "Qualität über Geschwindigkeit"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte beeinflussen die Auswahl eines Plotters?', 4, '[{"text": "Druckformat", "correct": true, "because": "Bestimmt maximale Größe"}, {"text": "Druckqualität", "correct": true, "because": "Beeinflusst Detailgenauigkeit"}, {"text": "Softwarekompatibilität", "correct": true, "because": "Für CAD-Programme nötig"}, {"text": "Gewicht des Plotters", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Plotter?', 3, '[{"text": "Hohe Präzision", "correct": true, "because": "Für technische Zeichnungen"}, {"text": "Großformatfähigkeit", "correct": true, "because": "Bis zu A0 und größer"}, {"text": "Farbdruck", "correct": true, "because": "Für Pläne und Designs"}, {"text": "Geringer Stromverbrauch", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können bei der Auswahl eines Plotters auftreten?', 3, '[{"text": "Inkompatibilität mit Software", "correct": true, "because": "Falsche Programme"}, {"text": "Unzureichendes Format", "correct": true, "because": "Zu kleines Druckfeld"}, {"text": "Hohe Kosten", "correct": true, "because": "Teurer als Standarddrucker"}, {"text": "Falsche Farbe", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schnittstellen können Plotter unterstützen?', 4, '[{"text": "USB", "correct": true, "because": "Standardverbindung"}, {"text": "Ethernet", "correct": true, "because": "Für Netzwerk"}, {"text": "Wi-Fi", "correct": true, "because": "Drahtlose Option"}, {"text": "HDMI", "correct": false, "because": "Für Video, nicht Drucker"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen profitieren von Plottern?', 3, '[{"text": "Architekturpläne", "correct": true, "because": "Großformat und Präzision"}, {"text": "Technische Zeichnungen", "correct": true, "because": "Detaillierte Darstellung"}, {"text": "Posterdruck", "correct": true, "because": "Große, farbige Ausgabe"}, {"text": "Textdokumente", "correct": false, "because": "Standarddrucker besser"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Plotter verwenden meist Tintenstrahltechnologie. b) Sie sind für kleine Formate optimiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tintenstrahl ja, Großformat primär"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Plotter bieten hohe Druckqualität für Pläne. b) Ihre Geschwindigkeit übertrifft die von Laserdruckern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Qualität ja, Geschwindigkeit geringer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Plotter sind für technische Zeichnungen geeignet. b) Sie benötigen keine spezielle Software.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeichnungen ja, Software nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Plotter unterstützen Großformatdruck bis A0. b) Sie sind günstiger als Tintenstrahldrucker.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Großformat ja, teurer als Tintenstrahl"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Plotter benötigen Tintenpatronen. b) Druckqualität ist bei technischen Zeichnungen unerheblich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tinten ja, Qualität wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

