INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 6 > Umsetzung > Installation
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist eine Installation eines IT-Systems ohne vorherige Hardwareprüfung möglich?', 2, '[{"text": "Ja", "correct": true, "because": "Technisch möglich, aber fehleranfällig"}, {"text": "Nein", "correct": false, "because": "Prüfung ist empfohlen, aber nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Installationsschritte immer in einer festgelegten Reihenfolge durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig vom System, aber Flexibilität ist oft möglich"}, {"text": "Ja", "correct": false, "because": "Reihenfolge ist ideal, aber nicht immer zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine Installation vollständig automatisiert ohne menschliches Eingreifen erfolgen?', 2, '[{"text": "Ja", "correct": true, "because": "Mit Skripten oder Tools möglich"}, {"text": "Nein", "correct": false, "because": "Automatisierung ist machbar, aber nicht immer vollständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es erforderlich, während der Installation eines Systems regelmäßig Backups zu erstellen?', 2, '[{"text": "Nein", "correct": true, "because": "Sinnvoll, aber nicht zwingend vorgeschrieben"}, {"text": "Ja", "correct": false, "because": "Backups sind Best Practice, aber nicht Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Abhängigkeiten zwischen Softwarekomponenten die Installation eines Systems verhindern?', 2, '[{"text": "Ja", "correct": true, "because": "Fehlende Abhängigkeiten blockieren oft den Prozess"}, {"text": "Nein", "correct": false, "because": "Abhängigkeiten sind kritisch"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme sollte vor der Installation eines Betriebssystems zwingend durchgeführt werden?', 3, '[{"text": "Kompatibilitätsprüfung der Hardware", "correct": true, "because": "Verhindert Installationsfehler"}, {"text": "Erstellung eines Benutzerhandbuchs", "correct": false, "because": "Spätere Phase"}, {"text": "Festlegen der IP-Adresse", "correct": false, "because": "Erst bei Konfiguration relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Medium wird häufig für die Installation eines Serversystems verwendet?', 2, '[{"text": "Bootfähiges USB-Laufwerk", "correct": true, "because": "Flexibel und weit verbreitet"}, {"text": "Papieranleitung", "correct": false, "because": "Kein Installationsmedium"}, {"text": "Cloud-Backup", "correct": false, "because": "Für Wiederherstellung, nicht Installation"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist der erste Schritt bei der Installation einer Software auf einem bestehenden System?', 2, '[{"text": "Überprüfung der Systemanforderungen", "correct": true, "because": "Stellt Kompatibilität sicher"}, {"text": "Deinstallation alter Versionen", "correct": false, "because": "Nur bei Bedarf"}, {"text": "Neustart des Systems", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Fehler tritt häufig auf, wenn Treiber während der Installation fehlen?', 2, '[{"text": "Hardware wird nicht erkannt", "correct": true, "because": "Treiber sind essenziell für Funktion"}, {"text": "System läuft schneller", "correct": false, "because": "Fehlende Treiber verlangsamen"}, {"text": "Installation wird abgebrochen", "correct": false, "because": "Nicht immer der Fall"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool wird oft verwendet, um eine automatisierte Installation über mehrere Systeme hinweg durchzuführen?', 3, '[{"text": "Image-Deployment-Software", "correct": true, "because": "Ermöglicht konsistente Installation"}, {"text": "Texteditor", "correct": false, "because": "Nicht für Installation geeignet"}, {"text": "Monitoring-Tool", "correct": false, "because": "Für Analyse, nicht Installation"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Vorbereitungen sind vor einer Systeminstallation notwendig?', 4, '[{"text": "Sicherung vorhandener Daten", "correct": true, "because": "Schutz vor Datenverlust"}, {"text": "Überprüfung der Stromversorgung", "correct": true, "because": "Stabilität gewährleisten"}, {"text": "Beschaffung kompatibler Hardware", "correct": true, "because": "Voraussetzung für Funktion"}, {"text": "Erstellung eines Marketingplans", "correct": false, "because": "Irrelevant für Installation"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können während einer Installation auftreten?', 3, '[{"text": "Inkompatible Treiber", "correct": true, "because": "Verhindert Hardwareerkennung"}, {"text": "Fehlende Berechtigungen", "correct": true, "because": "Blockiert Zugriff"}, {"text": "Korrupte Installationsdateien", "correct": true, "because": "Führt zu Abbruch"}, {"text": "Zu schnelle Internetverbindung", "correct": false, "because": "Kein Installationsproblem"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten müssen bei der Installation eines Betriebssystems berücksichtigt werden?', 4, '[{"text": "Partitionierung der Festplatte", "correct": true, "because": "Speicherzuweisung"}, {"text": "Auswahl des Dateisystems", "correct": true, "because": "Definiert Datenstruktur"}, {"text": "Installation von Treibern", "correct": true, "because": "Für Hardwarefunktion"}, {"text": "Farbe des Gehäuses", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte gehören typischerweise zur Installation einer Serversoftware?', 3, '[{"text": "Download der Installationsdatei", "correct": true, "because": "Erster Zugriff"}, {"text": "Anpassung der Konfigurationsdateien", "correct": true, "because": "Für spezifische Anforderungen"}, {"text": "Test der Funktionalität", "correct": true, "because": "Überprüft Erfolg"}, {"text": "Erstellung eines Logos", "correct": false, "because": "Nicht technisch relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ressourcen werden für eine erfolgreiche Installation benötigt?', 3, '[{"text": "Installationsmedium", "correct": true, "because": "Enthält Software"}, {"text": "Dokumentation", "correct": true, "because": "Leitet Prozess"}, {"text": "Ausreichende Hardwareleistung", "correct": true, "because": "Erfüllt Anforderungen"}, {"text": "Kundensupport-Team", "correct": false, "because": "Nur bei Problemen"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Eine Installation kann durch fehlende Administratorrechte scheitern. b) Jede Installation erfordert eine Internetverbindung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Rechte ja, Internet nicht immer nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Installationsanleitung ist optional bei Standardsoftware. b) Hardwaretreiber müssen immer manuell installiert werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Anleitung optional, Treiber oft automatisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine Installation kann durch inkompatible Hardware abgebrochen werden. b) Ein Rollback ist bei jeder Installation möglich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Inkompatibilität ja, Rollback nicht garantiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Bei der Installation eines Serversystems ist die Netzwerkverbindung optional. b) Eine Protokollierung der Installation ist sinnvoll.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Netzwerk oft nötig, Protokoll hilfreich"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine automatisierte Installation spart Zeit im Vergleich zur manuellen Installation. b) Fehler bei der Installation können nur durch Hardwareprobleme entstehen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Automatisierung effizient, Fehler vielfältig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

