INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 6 > Umsetzung > Konfiguration
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Muss die Konfiguration eines IT-Systems immer manuell durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Automatisierte Tools wie Skripte können genutzt werden"}, {"text": "Ja", "correct": false, "because": "Manuelle Konfiguration ist nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine fehlerhafte Konfiguration die Sicherheit eines Systems gefährden?', 2, '[{"text": "Ja", "correct": true, "because": "Falsche Einstellungen öffnen Schwachstellen"}, {"text": "Nein", "correct": false, "because": "Sicherheit hängt stark von Konfiguration ab"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es möglich, eine Konfiguration ohne vorherige Planung erfolgreich umzusetzen?', 2, '[{"text": "Ja", "correct": true, "because": "Technisch machbar, aber ineffizient und riskant"}, {"text": "Nein", "correct": false, "because": "Planung ist empfohlen, aber nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Standardkonfigurationen von Systemen immer für den produktiven Einsatz geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Standards sind oft unsicher oder unoptimiert"}, {"text": "Ja", "correct": false, "because": "Anpassung an spezifische Anforderungen nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Konfigurationsänderungen während des Betriebs eines Systems ohne Auswirkungen bleiben?', 2, '[{"text": "Nein", "correct": true, "because": "Änderungen beeinflussen Funktionalität oder Stabilität"}, {"text": "Ja", "correct": false, "because": "Auswirkungen sind nahezu unvermeidbar"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Tool wird häufig zur Automatisierung der Konfiguration von Servern verwendet?', 3, '[{"text": "Ansible", "correct": true, "because": "Bekannt für Konfigurationsmanagement"}, {"text": "Photoshop", "correct": false, "because": "Für Bildbearbeitung, nicht Konfiguration"}, {"text": "Wireshark", "correct": false, "because": "Für Netzwerkanalyse, nicht Konfiguration"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Konfiguration ist entscheidend, um Netzwerkzugriffe zu kontrollieren?', 2, '[{"text": "Firewall-Regeln", "correct": true, "because": "Steuern den Datenverkehr"}, {"text": "Farbschema der GUI", "correct": false, "because": "Irrelevant für Zugriff"}, {"text": "Prozessor-Taktfrequenz", "correct": false, "because": "Leistungsaspekt, nicht Zugriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Konfiguration eines Betriebssystems während der Umsetzung?', 2, '[{"text": "Optimierung für spezifische Anforderungen", "correct": true, "because": "Anpassung an Nutzungszweck"}, {"text": "Maximierung der Installationszeit", "correct": false, "because": "Effizienz ist Ziel"}, {"text": "Entfernung aller Standardeinstellungen", "correct": false, "because": "Nicht immer nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Fehler tritt oft bei der Konfiguration von Software auf?', 3, '[{"text": "Inkompatible Parameter", "correct": true, "because": "Falsche Werte führen zu Fehlfunktionen"}, {"text": "Zu schnelle Installation", "correct": false, "because": "Geschwindigkeit ist kein Fehler"}, {"text": "Zu geringe Bildschirmhelligkeit", "correct": false, "because": "Irrelevant für Software"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Datei wird typischerweise zur Konfiguration eines Webservers wie Apache bearbeitet?', 2, '[{"text": "httpd.conf", "correct": true, "because": "Hauptkonfigurationsdatei von Apache"}, {"text": "index.html", "correct": false, "because": "Inhaltsdatei, keine Konfiguration"}, {"text": "boot.ini", "correct": false, "because": "Für Windows-Boot, nicht Webserver"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente müssen bei der Konfiguration eines Netzwerks berücksichtigt werden?', 4, '[{"text": "IP-Adressen", "correct": true, "because": "Für Kommunikation essenziell"}, {"text": "Subnetzmasken", "correct": true, "because": "Definiert Netzwerkgrenzen"}, {"text": "Gateway-Adresse", "correct": true, "because": "Für externe Verbindungen"}, {"text": "Betriebssystemfarbe", "correct": false, "because": "Irrelevant für Netzwerk"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken können durch eine unsachgemäße Konfiguration entstehen?', 3, '[{"text": "Datenverlust", "correct": true, "because": "Fehlkonfiguration kann Daten gefährden"}, {"text": "Sicherheitslücken", "correct": true, "because": "Offene Ports oder schwache Passwörter"}, {"text": "Systemabstürze", "correct": true, "because": "Inkompatible Einstellungen"}, {"text": "Schnellere Performance", "correct": false, "because": "Unwahrscheinlich bei Fehlern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sind bei der Konfiguration einer Datenbank typischerweise erforderlich?', 4, '[{"text": "Benutzerrechte festlegen", "correct": true, "because": "Sichert Zugriff"}, {"text": "Speicherorte definieren", "correct": true, "because": "Für Datenverwaltung"}, {"text": "Performance-Optimierung", "correct": true, "because": "Für Effizienz"}, {"text": "Installation eines Grafikeditors", "correct": false, "because": "Unnötig für Datenbank"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Konfiguration eines Servers?', 3, '[{"text": "Anwendungsanforderungen", "correct": true, "because": "Bestimmen Ressourcennutzung"}, {"text": "Hardwarekapazität", "correct": true, "because": "Begrenzt Möglichkeiten"}, {"text": "Sicherheitsrichtlinien", "correct": true, "because": "Schützen System"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant für Server"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden können zur Dokumentation einer Konfiguration genutzt werden?', 3, '[{"text": "Konfigurationsdateien", "correct": true, "because": "Enthalten Einstellungen"}, {"text": "Kommentare in Skripten", "correct": true, "because": "Erklären Änderungen"}, {"text": "Versionsverwaltung", "correct": true, "because": "Verfolgt Anpassungen"}, {"text": "Fotos vom Bildschirm", "correct": false, "because": "Unpraktisch und ungenau"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Eine Konfiguration kann rückgängig gemacht werden, wenn sie dokumentiert ist. b) Standardeinstellungen sind immer sicher.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dokumentation hilft, Standards oft unsicher"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Konfiguration eines Systems beeinflusst dessen Performance. b) Konfiguration ist nur bei der Installation relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Performance ja, Konfiguration auch später"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Automatisierte Konfiguration reduziert menschliche Fehler. b) Jede Konfiguration erfordert einen Neustart des Systems.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Automatisierung ja, Neustart nicht immer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Konfigurationsmanagement-Tools können mehrere Systeme gleichzeitig verwalten. b) Eine einmalige Konfiguration reicht für den gesamten Lebenszyklus eines Systems.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tools ja, Anpassungen nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine falsche Konfiguration kann zu einem Totalausfall führen. b) Die Konfiguration eines Systems ist unabhängig von seinen Anforderungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ausfall ja, Anforderungen relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

