-- Netzteil.sql (Stromversorgungseinheit für IT-Systeme)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Netzteil immer für alle Systeme geeignet ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Leistung"}, {"text": "Ja", "correct": false, "because": "Zu vereinfacht"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich ein Netzteil für ein IT-System auswähle?', 3, '[{"text": "Leistungskapazität", "correct": true, "because": "Sichert Versorgung"}, {"text": "Schnellste Installation", "correct": false, "because": "Leistung zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat ein Netzteil in IT-Systemen?', 5, '[{"text": "Wattzahl", "correct": true, "because": "Bestimmt Leistung"}, {"text": "Effizienzrating", "correct": true, "because": "Beeinflusst Verbrauch"}, {"text": "Büromöbel", "correct": false, "because": "Kein Merkmal"}, {"text": "Farbanalyse", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Netzteil wandelt Wechselstrom in Gleichstrom um. b) Es ist immer modular.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht immer modular"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein Netzteil für ein IT-System auswähle?', 4, '[{"text": "Wattzahl", "correct": false, "because": "Bestimmt Leistung"}, {"text": "Effizienz", "correct": false, "because": "Beeinflusst Verbrauch"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Netzteil immer modular sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "Auch nicht-modular möglich"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Netzteil in einem IT-System?', 3, '[{"text": "Stabile Stromversorgung", "correct": true, "because": "Sichert Betrieb"}, {"text": "Schnellste Montage", "correct": false, "because": "Stabilität wichtiger"}, {"text": "Weniger Watt", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind bei einem Netzteil entscheidend?', 5, '[{"text": "Leistungskapazität", "correct": true, "because": "Versorgt Komponenten"}, {"text": "Effizienzrating", "correct": true, "because": "Reduziert Verbrauch"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Netzteil hat oft ein 80-Plus-Rating. b) Es ist immer für Server geeignet. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht immer Server-tauglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um ein Netzteil für ein IT-System auszuwählen?', 4, '[{"text": "Komponentenbedarf", "correct": false, "because": "Bestimmt Wattzahl"}, {"text": "Effizienzrating", "correct": false, "because": "Beeinflusst Verbrauch"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Netzteil immer für alle Spannungen geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Modell"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein hochwertiges Netzteil?', 4, '[{"text": "Stabilität", "correct": true, "because": "Sichert Betrieb"}, {"text": "Energieeffizienz", "correct": true, "because": "Reduziert Kosten"}, {"text": "Schnellere Installation", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Netzteil nur für PCs geeignet ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Server, Geräte"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um ein Netzteil für ein IT-System auszuwählen?', 3, '[{"text": "Wattzahl", "correct": true, "because": "Sichert Versorgung"}, {"text": "Günstigster Preis", "correct": false, "because": "Qualität wichtiger"}, {"text": "Bunte Optik", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Netzteil kann modular sein. b) Es ist immer ineffizient.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Effizienz variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei einem Netzteil?', 5, '[{"text": "Leistungskapazität", "correct": true, "because": "Sichert Versorgung"}, {"text": "Kabelmanagement", "correct": true, "because": "Erleichtert Installation"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich ein Netzteil für ein IT-System auswähle?', 3, '[{"text": "Effizienzrating", "correct": false, "because": "Reduziert Verbrauch"}, {"text": "Kompatibilität", "correct": false, "because": "Sichert Funktion"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Netzteil ohne ausreichende Wattzahl ein System betreiben?', 3, '[{"text": "Nein", "correct": true, "because": "Riskiert Ausfälle"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Netzteil immer einen Lüfter benötigt?', 2, '[{"text": "Nein", "correct": true, "because": "Fannless-Modelle möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für ein Netzteil?', 4, '[{"text": "Stabile Stromversorgung", "correct": true, "because": "Sichert Betrieb"}, {"text": "Schnellste Montage", "correct": false, "because": "Leistung zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');


