-- Nodes.sql (Netzwerkknoten in einem IT-Netzwerk)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Nodes in einem Netzwerk immer physische Geräte sein müssen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch virtuelle Nodes möglich"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich Nodes für ein IT-Netzwerk auswähle?', 3, '[{"text": "Funktionalität", "correct": true, "because": "Bestimmt Rolle im Netzwerk"}, {"text": "Schnellste Installation", "correct": false, "because": "Leistung zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Arten von Nodes gibt es in einem Netzwerk?', 5, '[{"text": "Router", "correct": true, "because": "Leitet Daten zwischen Netzwerken"}, {"text": "Endgeräte", "correct": true, "because": "Senden/Empfangen Daten"}, {"text": "Büromöbel", "correct": false, "because": "Kein Node"}, {"text": "Farbanalyse", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Node kann Daten weiterleiten. b) Jeder Node ist immer ein Router.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht alle Nodes sind Router"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich Nodes für ein IT-Netzwerk plane?', 4, '[{"text": "Datenrate", "correct": false, "because": "Bestimmt Leistung"}, {"text": "Netzwerkrolle", "correct": false, "because": "Definiert Funktion"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Node immer ein physisches Gerät ist?', 2, '[{"text": "Nein", "correct": true, "because": "Virtuelle Nodes möglich"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Nodes in einem Netzwerk?', 3, '[{"text": "Datenkommunikation", "correct": true, "because": "Ermöglicht Übertragung"}, {"text": "Schnellste Installation", "correct": false, "because": "Funktion zählt"}, {"text": "Weniger Nodes", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind bei Nodes entscheidend?', 5, '[{"text": "Verbindungsfähigkeit", "correct": true, "because": "Ermöglicht Kommunikation"}, {"text": "Datenverarbeitung", "correct": true, "because": "Verarbeitet Daten"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Switch ist ein Node. b) Alle Nodes sind Endgeräte. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht alle sind Endgeräte"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Nodes in einem Netzwerk effektiv einzusetzen?', 4, '[{"text": "Netzwerkprotokolle", "correct": false, "because": "Ermöglichen Kommunikation"}, {"text": "Anschlüsse", "correct": false, "because": "Verbinden Geräte"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind alle Nodes Endgeräte?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Router, Switches"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Nodes in einem Netzwerk?', 4, '[{"text": "Datenübertragung", "correct": true, "because": "Ermöglichen Kommunikation"}, {"text": "Netzwerkflexibilität", "correct": true, "because": "Unterschiedliche Rollen"}, {"text": "Schnellere Installation", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Nodes nur für große Netzwerke relevant sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Netzwerke"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um Nodes für ein IT-Netzwerk auszuwählen?', 3, '[{"text": "Netzwerkrolle", "correct": true, "because": "Bestimmt Funktion"}, {"text": "Günstigster Preis", "correct": false, "because": "Leistung wichtiger"}, {"text": "Bunte Optik", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Node kann ein Server sein. b) Alle Nodes haben eine MAC-Adresse.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht alle haben MAC"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei Nodes?', 5, '[{"text": "Datenrate", "correct": true, "because": "Beeinflusst Leistung"}, {"text": "Verbindungstyp", "correct": true, "because": "Bestimmt Einsatz"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich Nodes für ein Netzwerk auswähle?', 3, '[{"text": "Bandbreite", "correct": false, "because": "Bestimmt Leistung"}, {"text": "Kompatibilität", "correct": false, "because": "Sichert Funktion"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind alle Nodes mit einer MAC-Adresse ausgestattet?', 3, '[{"text": "Nein", "correct": true, "because": "Nicht alle haben MAC"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Nodes nur Daten empfangen können?', 2, '[{"text": "Nein", "correct": true, "because": "Auch senden, weiterleiten"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für Nodes?', 4, '[{"text": "Kommunikationsfähigkeit", "correct": true, "because": "Ermöglicht Netzwerk"}, {"text": "Schnellste Installation", "correct": false, "because": "Funktion zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');


