-- Nutzwertanalyse.sql (Methode zur Bewertung von Alternativen anhand gewichteter Kriterien)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass die Nutzwertanalyse immer nur quantitative Kriterien berücksichtigt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch qualitative Kriterien"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich eine Nutzwertanalyse für ein IT-Projekt durchführe?', 3, '[{"text": "Kriteriengewichtung", "correct": true, "because": "Bestimmt Einfluss"}, {"text": "Schnellste Durchführung", "correct": false, "because": "Genauigkeit zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Nutzwertanalyse?', 5, '[{"text": "Bewertungskriterien", "correct": true, "because": "Grundlage der Bewertung"}, {"text": "Gewichtungsfaktoren", "correct": true, "because": "Bestimmen Priorität"}, {"text": "Büromöbel", "correct": false, "because": "Kein Faktor"}, {"text": "Farbskala", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Nutzwertanalyse bewertet Alternativen. b) Sie ist immer objektiv.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Subjektive Gewichtung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich eine Nutzwertanalyse in einem IT-Projekt durchführe?', 4, '[{"text": "Kriterienauswahl", "correct": false, "because": "Bestimmt Bewertung"}, {"text": "Alternativen", "correct": false, "because": "Grundlage der Analyse"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Nutzwertanalyse nur für IT-Projekte geeignet ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch andere Bereiche"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit der Nutzwertanalyse?', 3, '[{"text": "Beste Alternative finden", "correct": true, "because": "Optimiert Entscheidung"}, {"text": "Schnellste Lösung", "correct": false, "because": "Qualität zählt"}, {"text": "Weniger Kriterien", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte gehören zur Nutzwertanalyse?', 5, '[{"text": "Kriterien festlegen", "correct": true, "because": "Grundlage der Bewertung"}, {"text": "Gewichtung bestimmen", "correct": true, "because": "Priorisiert Kriterien"}, {"text": "Bürogröße messen", "correct": false, "because": "Irrelevant"}, {"text": "Farbskala wählen", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Die Nutzwertanalyse verwendet Gewichtungsfaktoren. b) Sie ist immer zeitaufwendig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeitaufwand variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um eine Nutzwertanalyse durchzuführen?', 4, '[{"text": "Bewertungsskala", "correct": false, "because": "Misst Kriterien"}, {"text": "Alternativen", "correct": false, "because": "Grundlage der Analyse"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Nutzwertanalyse immer objektiv?', 2, '[{"text": "Nein", "correct": true, "because": "Subjektive Gewichtung"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Nutzwertanalyse?', 4, '[{"text": "Transparente Entscheidung", "correct": true, "because": "Nachvollziehbar"}, {"text": "Berücksichtigt Qualitatives", "correct": true, "because": "Flexibel"}, {"text": "Schnellere Projekte", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass die Nutzwertanalyse nur für große Projekte geeignet ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um eine Nutzwertanalyse effektiv durchzuführen?', 3, '[{"text": "Relevante Kriterien", "correct": true, "because": "Sichern Genauigkeit"}, {"text": "Schnellste Methode", "correct": false, "because": "Qualität wichtiger"}, {"text": "Bunte Diagramme", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Nutzwertanalyse ist flexibel einsetzbar. b) Sie entfernt immer alle Unsicherheiten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Subjektivität bleibt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei der Nutzwertanalyse?', 5, '[{"text": "Kriteriengewichtung", "correct": true, "because": "Bestimmt Einfluss"}, {"text": "Alternativenbewertung", "correct": true, "because": "Vergleicht Optionen"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich eine Nutzwertanalyse durchführe?', 3, '[{"text": "Bewertungsskala", "correct": false, "because": "Misst Kriterien"}, {"text": "Kriterienauswahl", "correct": false, "because": "Grundlage der Analyse"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Nutzwertanalyse immer zeitaufwendig?', 3, '[{"text": "Nein", "correct": true, "because": "Abhängig vom Umfang"}, {"text": "Ja", "correct": false, "because": "Kann effizient sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Nutzwertanalyse nur quantitative Daten benötigt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch qualitativ"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für die Nutzwertanalyse?', 4, '[{"text": "Gewichtete Kriterien", "correct": true, "because": "Bestimmen Ergebnis"}, {"text": "Schnellste Durchführung", "correct": false, "because": "Qualität zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');

