-- Effizienz bewerten.sql (Laufzeit- und Speicherbedarf der Datenstrukturen analysieren)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Laufzeit einer Suche in einer LinkedList immer O(n)?', 2, '[{"text": "Ja", "correct": true, "because": "Lineares Durchsuchen nötig"}, {"text": "Nein", "correct": false, "because": "Keine direkten Zugriffe möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Struktur hat die beste Laufzeit für zufällige Zugriffe?', 3, '[{"text": "Array", "correct": true, "because": "O(1) durch Index"}, {"text": "HashMap", "correct": false, "because": "O(1) nur bei Schlüsseln"}, {"text": "Baum", "correct": false, "because": "O(log n) im Durchschnitt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen den Speicherbedarf einer HashMap?', 5, '[{"text": "Anzahl der Elemente", "correct": true, "because": "Direkt proportional zur Größe"}, {"text": "Lastfaktor", "correct": true, "because": "Bestimmt Array-Größe"}, {"text": "Sortierreihenfolge", "correct": false, "because": "HashMap sortiert nicht"}, {"text": "Zugriffshäufigkeit", "correct": false, "because": "Irrelevant für Speicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Stack hat O(1) für Push. b) Eine Queue hat O(n) für Enqueue.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Queue ist O(1) bei richtiger Implementierung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Laufzeitanalyse einer Baumstruktur?', 4, '[{"text": "Höhe des Baums", "correct": false, "because": "Bestimmt O(log n)"}, {"text": "Ausbalancierung", "correct": false, "because": "Beeinflusst Effizienz"}, {"text": "Speicherort", "correct": true, "because": "Irrelevant für Laufzeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine ArrayList mehr Speicher als ein Array braucht?', 2, '[{"text": "Ja", "correct": true, "because": "Overhead durch Objekte"}, {"text": "Nein", "correct": false, "because": "ArrayList hat zusätzliche Metadaten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Operation hat bei einem ausbalancierten Baum die schlechteste Laufzeit?', 3, '[{"text": "Suche", "correct": true, "because": "O(log n) ist typisch"}, {"text": "Einfügen", "correct": false, "because": "Auch O(log n)"}, {"text": "Wurzelzugriff", "correct": false, "because": "O(1) möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strukturen haben O(1) für Hinzufügen?', 5, '[{"text": "Stack", "correct": true, "because": "Push ist O(1)"}, {"text": "Queue", "correct": true, "because": "Enqueue ist O(1)"}, {"text": "Baum", "correct": false, "because": "O(log n) wegen Balance"}, {"text": "ArrayList", "correct": false, "because": "O(n) bei vollem Array"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) HashMap hat O(1) Suche. b) Kollisionen machen sie langsamer. Stimmt das?', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Kollisionen erhöhen Laufzeit"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "Beide sind richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Speicheranalyse einer Liste unwichtig?', 4, '[{"text": "Elementanzahl", "correct": false, "because": "Direkt relevant"}, {"text": "Referenzgröße", "correct": false, "because": "Bestimmt Speicher pro Knoten"}, {"text": "Sortieralgorithmus", "correct": true, "because": "Beeinflusst nur Laufzeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Hat ein Array O(1) für alle Operationen?', 2, '[{"text": "Nein", "correct": true, "because": "Einfügen ist O(n)"}, {"text": "Ja", "correct": false, "because": "Nur Zugriff ist O(1)"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strukturen haben den geringsten Speicherbedarf?', 4, '[{"text": "Array", "correct": true, "because": "Kein Overhead"}, {"text": "LinkedList", "correct": false, "because": "Zeiger pro Element"}, {"text": "HashSet", "correct": false, "because": "Zusätzliche Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Bäume immer effizienter als Listen sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig vom Szenario"}, {"text": "Ja", "correct": false, "because": "Listen können bei Zugriffen besser sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer Queue die teuerste Operation?', 3, '[{"text": "Suche", "correct": true, "because": "O(n) da keine direkten Zugriffe"}, {"text": "Enqueue", "correct": false, "because": "O(1) bei guter Implementierung"}, {"text": "Dequeue", "correct": false, "because": "O(1) ebenfalls"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) HashSet hat O(1) für Contains. b) TreeSet hat O(1) für Contains.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "TreeSet ist O(log n)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strukturen skalieren schlecht bei großen Datenmengen?', 5, '[{"text": "LinkedList", "correct": true, "because": "O(n) für Zugriffe"}, {"text": "Array", "correct": true, "because": "O(n) für Verschiebung"}, {"text": "HashMap", "correct": false, "because": "O(1) bleibt stabil"}, {"text": "B-Baum", "correct": false, "because": "O(log n) skaliert gut"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Effizienz einer Stack-Implementierung?', 3, '[{"text": "Push-Laufzeit", "correct": false, "because": "Kernoperation"}, {"text": "Pop-Laufzeit", "correct": false, "because": "Ebenfalls zentral"}, {"text": "Sortierfähigkeit", "correct": true, "because": "Stack sortiert nicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal mit der Laufzeit? Ist Einfügen in eine HashMap immer O(1)?', 3, '[{"text": "Nein", "correct": true, "because": "Kollisionen können O(n) machen"}, {"text": "Ja", "correct": false, "because": "Nur im Idealfall O(1)"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Array mehr Speicher als eine HashMap braucht?', 2, '[{"text": "Nein", "correct": true, "because": "HashMap hat Overhead"}, {"text": "Ja", "correct": false, "because": "Array ist kompakter"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Struktur hat die beste Laufzeit für sortierte Daten?', 4, '[{"text": "Baum", "correct": true, "because": "O(log n) für Operationen"}, {"text": "ArrayList", "correct": false, "because": "O(n log n) für Sortierung"}, {"text": "Queue", "correct": false, "because": "Keine Sortierung"}]');

