INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > IT-Sicherheit > Kundenberatung IT-Sicherheit
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Kundenberatung zu IT-Sicherheit notwendig, um Kunden über Bedrohungen wie Phishing aufzuklären?', 2, '[{"text": "Ja", "correct": true, "because": "Beratung sensibilisiert Kunden für Risiken"}, {"text": "Nein", "correct": false, "because": "Ohne Beratung fehlt oft das Bewusstsein"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine Kundenberatung zu IT-Sicherheit ohne technisches Fachwissen erfolgreich sein?', 2, '[{"text": "Nein", "correct": true, "because": "Fachwissen ist essenziell für fundierte Beratung"}, {"text": "Ja", "correct": false, "because": "Ohne Expertise wird die Beratung ungenau"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Kundenberatung zu IT-Sicherheit immer individuelle Lösungen vorschlagen?', 2, '[{"text": "Ja", "correct": true, "because": "Maßgeschneiderte Lösungen sind effektiver"}, {"text": "Nein", "correct": false, "because": "Standardlösungen sind oft unzureichend"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Kunden durch Beratung zu IT-Sicherheit vor allen Bedrohungen geschützt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Beratung reduziert Risiken, aber kein absoluter Schutz"}, {"text": "Ja", "correct": false, "because": "Kompletter Schutz ist unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Kundenberatung zu IT-Sicherheit auch für kleine Unternehmen relevant?', 2, '[{"text": "Ja", "correct": true, "because": "Alle Unternehmen sind potenziellen Bedrohungen ausgesetzt"}, {"text": "Nein", "correct": false, "because": "Größe spielt keine Rolle bei Sicherheitsrisiken"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Kundenberatung zu IT-Sicherheit primär?', 2, '[{"text": "Risikoreduktion", "correct": true, "because": "Minimiert Bedrohungen durch Aufklärung"}, {"text": "Softwareverkauf", "correct": false, "because": "Sekundär"}, {"text": "Kostensteigerung", "correct": false, "because": "Kein Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt ist bei der Kundenberatung zu IT-Sicherheit am wichtigsten?', 3, '[{"text": "Verständliche Kommunikation", "correct": true, "because": "Kunden müssen Risiken verstehen"}, {"text": "Technische Details", "correct": false, "because": "Wichtig, aber nicht primär"}, {"text": "Schnelle Durchführung", "correct": false, "because": "Qualität über Geschwindigkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme sollte in der Kundenberatung zu IT-Sicherheit am häufigsten empfohlen werden?', 2, '[{"text": "Regelmäßige Schulungen", "correct": true, "because": "Sensibilisiert Mitarbeiter"}, {"text": "Neue Hardware", "correct": false, "because": "Nicht immer nötig"}, {"text": "Komplexe Passwörter", "correct": false, "because": "Teilmaßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Risiko wird durch Kundenberatung zu IT-Sicherheit am ehesten minimiert?', 2, '[{"text": "Phishing-Angriffe", "correct": true, "because": "Aufklärung reduziert Anfälligkeit"}, {"text": "Hardware-Ausfall", "correct": false, "because": "Nicht direkt beeinflussbar"}, {"text": "Softwarefehler", "correct": false, "because": "Technisches Problem"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie sollte in der Kundenberatung oft empfohlen werden?', 2, '[{"text": "Multi-Faktor-Authentifizierung", "correct": true, "because": "Erhöht Sicherheit effektiv"}, {"text": "Texteditor", "correct": false, "because": "Kein Sicherheitswerkzeug"}, {"text": "Router", "correct": false, "because": "Nur Netzwerkschutz"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Themen sollten in der Kundenberatung zu IT-Sicherheit behandelt werden?', 4, '[{"text": "Phishing-Prävention", "correct": true, "because": "Häufige Bedrohung"}, {"text": "Passwortmanagement", "correct": true, "because": "Grundlage der Sicherheit"}, {"text": "Datensicherung", "correct": true, "because": "Schutz vor Verlust"}, {"text": "Hardware-Wartung", "correct": false, "because": "Weniger sicherheitsrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sollten in der Kundenberatung empfohlen werden?', 3, '[{"text": "Regelmäßige Updates", "correct": true, "because": "Schließt Sicherheitslücken"}, {"text": "Mitarbeiterschulung", "correct": true, "because": "Reduziert menschliche Fehler"}, {"text": "Verschlüsselung", "correct": true, "because": "Schützt Daten"}, {"text": "Schnellere Internetverbindung", "correct": false, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bedrohungen sollten in der Kundenberatung angesprochen werden?', 4, '[{"text": "Ransomware", "correct": true, "because": "Hoher Schaden möglich"}, {"text": "Phishing", "correct": true, "because": "Häufig und gefährlich"}, {"text": "Datendiebstahl", "correct": true, "because": "Vertraulichkeit gefährdet"}, {"text": "Langsame Server", "correct": false, "because": "Kein Sicherheitsrisiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Kundenberatung zu IT-Sicherheit?', 3, '[{"text": "Risikobewusstsein", "correct": true, "because": "Kunden erkennen Gefahren"}, {"text": "Verbesserte Sicherheit", "correct": true, "because": "Maßnahmen umgesetzt"}, {"text": "Kundenzufriedenheit", "correct": true, "because": "Vertrauen steigt"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien sollten in der Kundenberatung vorgeschlagen werden?', 3, '[{"text": "Firewall", "correct": true, "because": "Schützt Netzwerke"}, {"text": "Antivirus-Software", "correct": true, "because": "Erkennt Malware"}, {"text": "VPN", "correct": true, "because": "Sichert Verbindungen"}, {"text": "Textverarbeitung", "correct": false, "because": "Kein Sicherheitswerkzeug"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Kundenberatung zu IT-Sicherheit sensibilisiert für Phishing. b) Sie ist nur für große Unternehmen relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Sensibilisierung ja, alle betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Technisches Fachwissen ist für IT-Sicherheitsberatung essenziell. b) Kundenberatung schützt vor allen Bedrohungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Fachwissen ja, absoluter Schutz nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Schulungen sind eine empfohlene Maßnahme in der IT-Sicherheitsberatung. b) Standardlösungen reichen immer aus.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schulungen ja, Standardlösungen oft nicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Kundenberatung reduziert Sicherheitsrisiken. b) Sie ist ohne technische Lösungen wirkungslos.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Risiken ja, Aufklärung allein hilft"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Multi-Faktor-Authentifizierung ist eine sinnvolle Empfehlung. b) Kundenberatung ist nur für Softwareentwicklung relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "MFA ja, Beratung allgemein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

