INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Hardware > Auswahl und Komponenten > Hardware zur Barrierefreiheit
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann Hardware zur Barrierefreiheit unabhängig von den spezifischen Bedürfnissen der Nutzer ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Bedürfnisse bestimmen die geeignete Hardware"}, {"text": "Ja", "correct": false, "because": "Ohne Anpassung ineffektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen bei der Hardware-Konfiguration zur Barrierefreiheit gesetzliche Vorgaben berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Vorschriften wie Barrierefreiheitsgesetze gelten"}, {"text": "Nein", "correct": false, "because": "Gesetzliche Anforderungen sind relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Hardware zur Barrierefreiheit nur für Menschen mit Sehbehinderungen relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Umfasst auch Hör-, Bewegungs- und andere Einschränkungen"}, {"text": "Ja", "correct": false, "because": "Vielfalt der Bedürfnisse"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Standardgeräte ohne Anpassung als Hardware zur Barrierefreiheit genutzt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Spezielle Anpassungen oft nötig"}, {"text": "Ja", "correct": false, "because": "Standardgeräte fehlen oft Funktionen"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Hardware zur Barrierefreiheit immer teurer als Standardhardware?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten variieren je nach Lösung"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig teurer"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor ist bei der Auswahl von Hardware zur Barrierefreiheit am wichtigsten?', 3, '[{"text": "Individuelle Nutzerbedürfnisse", "correct": true, "because": "Bestimmen geeignete Lösungen"}, {"text": "Kosten", "correct": false, "because": "Sekundär"}, {"text": "Marke", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Hardware wird häufig für Sehbehinderte eingesetzt?', 2, '[{"text": "Braillezeile", "correct": true, "because": "Ermöglicht taktile Ausgabe"}, {"text": "Lautsprecher", "correct": false, "because": "Für Hörbehinderte"}, {"text": "Joystick", "correct": false, "because": "Für Mobilitätseinschränkungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion erfüllt eine adaptive Tastatur?', 2, '[{"text": "Erleichtert Eingabe für Motorikprobleme", "correct": true, "because": "Große Tasten oder Anpassungen"}, {"text": "Verbessert Druckqualität", "correct": false, "because": "Nicht relevant"}, {"text": "Erhöht Netzwerkgeschwindigkeit", "correct": false, "because": "Falscher Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gerät unterstützt Hörbehinderte bei der Nutzung eines Computers?', 3, '[{"text": "Visuelles Signalgerät", "correct": true, "because": "Zeigt Töne visuell an"}, {"text": "Spracherkennungssoftware", "correct": false, "because": "Für Sehbehinderte"}, {"text": "Trackball", "correct": false, "because": "Für Mobilitätseinschränkungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptvorteil von Hardware zur Barrierefreiheit?', 2, '[{"text": "Erhöhte Zugänglichkeit", "correct": true, "because": "Ermöglicht Nutzung für alle"}, {"text": "Geringere Kosten", "correct": false, "because": "Nicht primär"}, {"text": "Schnellere Verarbeitung", "correct": false, "because": "Nicht Hauptziel"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte beeinflussen die Auswahl von Hardware zur Barrierefreiheit?', 4, '[{"text": "Art der Behinderung", "correct": true, "because": "Bestimmt Gerätetyp"}, {"text": "Kompatibilität mit System", "correct": true, "because": "Muss integrierbar sein"}, {"text": "Benutzerfreundlichkeit", "correct": true, "because": "Erleichtert Nutzung"}, {"text": "Farbe des Geräts", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Hardware kann zur Barrierefreiheit beitragen?', 3, '[{"text": "Braillezeile", "correct": true, "because": "Für Sehbehinderte"}, {"text": "Adaptive Tastatur", "correct": true, "because": "Für Motorikprobleme"}, {"text": "Sprachausgabe", "correct": true, "because": "Für Sehbehinderte"}, {"text": "Standardmaus", "correct": false, "because": "Keine spezielle Anpassung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können bei der Auswahl von Hardware zur Barrierefreiheit auftreten?', 3, '[{"text": "Inkompatibilität mit Software", "correct": true, "because": "Einschränkt Funktion"}, {"text": "Hohe Kosten", "correct": true, "because": "Spezialisierte Geräte teuer"}, {"text": "Fehlende Anpassung", "correct": true, "because": "Passt nicht zu Bedürfnissen"}, {"text": "Geringe Lautstärke", "correct": false, "because": "Nicht primär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche gesetzlichen Anforderungen können die Hardware-Konfiguration beeinflussen?', 4, '[{"text": "Barrierefreiheitsgesetze", "correct": true, "because": "Vorgaben für Zugang"}, {"text": "Arbeitsschutzvorschriften", "correct": true, "because": "Sicherheit am Arbeitsplatz"}, {"text": "Datenschutz", "correct": true, "because": "Schutz sensibler Daten"}, {"text": "Verbrauchssteuer", "correct": false, "because": "Nicht direkt relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen profitieren von Hardware zur Barrierefreiheit?', 3, '[{"text": "Bildung", "correct": true, "because": "Inklusiver Unterricht"}, {"text": "Arbeitsplatz", "correct": true, "because": "Ermöglicht Teilhabe"}, {"text": "Alltagsnutzung", "correct": true, "because": "Unterstützt Selbstständigkeit"}, {"text": "Hochgeschwindigkeitsdruck", "correct": false, "because": "Nicht primär relevant"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Hardware zur Barrierefreiheit muss an Nutzerbedürfnisse angepasst sein. b) Sie ist nur für Sehbehinderungen nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Anpassung ja, nicht nur Sehbehinderung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Braillezeilen unterstützen Sehbehinderte. b) Adaptive Hardware ist immer teurer als Standardhardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Braille ja, Kosten variieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Hardware zur Barrierefreiheit verbessert die Zugänglichkeit. b) Sie erfordert keine Softwareunterstützung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zugänglichkeit ja, Software oft nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Gesetzliche Vorgaben können die Hardwarewahl beeinflussen. b) Barrierefreiheit ist nur für öffentliche Einrichtungen relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vorgaben ja, nicht nur öffentlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Adaptive Tastaturen unterstützen Menschen mit Motorikproblemen. b) Hardware zur Barrierefreiheit ist immer eigenständig nutzbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Motorik ja, oft systemabhängig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

