-- Asymmetrische-Verschlüsselung.sql (Public und Private Key, z. B. RSA, sicherer Schlüsselaustausch)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist asymmetrische Verschlüsselung nur für kleine Datenmengen geeignet?', 2, '[{"text": "Ja", "correct": true, "because": "Langsamer, oft für Schlüssel verwendet"}, {"text": "Nein", "correct": false, "because": "Weniger effizient bei großen Daten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit asymmetrischer Verschlüsselung?', 3, '[{"text": "Sicherer Schlüsselaustausch", "correct": true, "because": "Public und Private Keys schützen"}, {"text": "Datenmenge maximieren", "correct": false, "because": "Nicht primär"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Sicherheit im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften hat asymmetrische Verschlüsselung?', 5, '[{"text": "Zwei Schlüssel", "correct": true, "because": "Public und Private Key"}, {"text": "Hohe Sicherheit", "correct": true, "because": "Schwierig zu knacken"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) RSA ist asymmetrisch. b) Sie nutzt einen Schlüssel.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "RSA nutzt zwei Schlüssel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei asymmetrischer Verschlüsselung?', 4, '[{"text": "Schlüsselpaar-Management", "correct": false, "because": "Kritisch für Sicherheit"}, {"text": "Algorithmuswahl", "correct": false, "because": "Bestimmt Schutz"}, {"text": "Visuelles Design", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob asymmetrische Verschlüsselung langsamer als symmetrische ist?', 2, '[{"text": "Ja", "correct": true, "because": "Höherer Rechenaufwand"}, {"text": "Nein", "correct": false, "because": "Weniger effizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Algorithmus ist typisch für asymmetrische Verschlüsselung?', 3, '[{"text": "RSA", "correct": true, "because": "Weit verbreitet und sicher"}, {"text": "AES", "correct": false, "because": "Symmetrisch"}, {"text": "SHA-256", "correct": false, "because": "Hashfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen nutzt asymmetrische Verschlüsselung?', 5, '[{"text": "Schlüsselaustausch", "correct": true, "because": "Sichert symmetrische Schlüssel"}, {"text": "Digitale Signaturen", "correct": true, "because": "Bestätigt Authentizität"}, {"text": "Maximale Speichergröße", "correct": false, "because": "Nicht relevant"}, {"text": "Animationseffekte", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Asymmetrische Verschlüsselung schützt Schlüsselaustausch. b) Sie ist schneller als symmetrische.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Langsamer als symmetrisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für asymmetrische Verschlüsselung?', 4, '[{"text": "Public Key", "correct": false, "because": "Für Verschlüsselung nötig"}, {"text": "Private Key", "correct": false, "because": "Für Entschlüsselung nötig"}, {"text": "Grafisches Design", "correct": true, "because": "Kein Sicherheitsaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist RSA symmetrisch?', 2, '[{"text": "Nein", "correct": true, "because": "Asymmetrisch mit zwei Schlüsseln"}, {"text": "Ja", "correct": false, "because": "Falsche Zuordnung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet asymmetrische Verschlüsselung?', 4, '[{"text": "Sicherer Schlüsselaustausch", "correct": true, "because": "Ohne geheime Übertragung"}, {"text": "Authentizität", "correct": true, "because": "Durch Signaturen"}, {"text": "Hohe Taktfrequenz", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass asymmetrische Verschlüsselung für große Dateien ideal ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Langsam, meist für Schlüssel"}, {"text": "Ja", "correct": false, "because": "Symmetrisch effizienter"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei asymmetrischer Verschlüsselung?', 3, '[{"text": "Schlüsselpaar-Sicherheit", "correct": true, "because": "Schützt den Private Key"}, {"text": "Schnelle Übertragung", "correct": false, "because": "Sekundär"}, {"text": "Visuelles Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Asymmetrische Verschlüsselung nutzt zwei Schlüssel. b) Sie ist für alle Daten geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht ideal für große Daten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Algorithmen sind typisch für asymmetrische Verschlüsselung?', 5, '[{"text": "RSA", "correct": true, "because": "Standardalgorithmus"}, {"text": "ECC", "correct": true, "because": "Effizienter bei kleinerer Schlüssellänge"}, {"text": "AES", "correct": false, "because": "Symmetrisch"}, {"text": "SHA-256", "correct": false, "because": "Hashfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei asymmetrischer Verschlüsselung unwichtig?', 3, '[{"text": "Schlüsselverwaltung", "correct": false, "because": "Kern der Sicherheit"}, {"text": "Public-Key-Verteilung", "correct": false, "because": "Notwendig für Austausch"}, {"text": "Schriftgröße", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt asymmetrische Verschlüsselung auch Integrität?', 3, '[{"text": "Ja", "correct": true, "because": "Mit Signaturen möglich"}, {"text": "Nein", "correct": false, "because": "Erweiterte Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob asymmetrische Verschlüsselung für Schlüsselaustausch genutzt wird?', 2, '[{"text": "Ja", "correct": true, "because": "Hauptanwendung"}, {"text": "Nein", "correct": false, "because": "Standardnutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich für asymmetrische Verschlüsselung?', 4, '[{"text": "Public-Private-Key-Paar", "correct": true, "because": "Kern der Technologie"}, {"text": "Zufällige Daten", "correct": false, "because": "Irrelevant"}, {"text": "Grafisches Design", "correct": false, "because": "Kein Schutzfokus"}]');

