-- Arbeitsrecht Berufsbildung > Soziale gesellschaftliche Themen > Nachhaltigkeit > Emissionsreduktion
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann ein IT-Betrieb durch energieeffiziente Hardware die CO₂-Emissionen reduzieren?', 2, '[{"text": "Ja", "correct": true, "because": "Geringerer Energieverbrauch senkt Emissionen"}, {"text": "Nein", "correct": false, "because": "Effizienz wirkt emissionsmindernd"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Emissionsreduktion in einem IT-Betrieb gesetzlich vorgeschrieben?', 2, '[{"text": "Nein", "correct": true, "because": "Keine direkte Pflicht, aber freiwillige Standards existieren"}, {"text": "Ja", "correct": false, "because": "Keine allgemeine gesetzliche Vorschrift"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Fachinformatiker durch Homeoffice die Emissionen eines IT-Betriebs senken?', 2, '[{"text": "Ja", "correct": true, "because": "Weniger Pendeln reduziert CO₂"}, {"text": "Nein", "correct": false, "because": "Homeoffice wirkt emissionsmindernd"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein IT-Betrieb erneuerbare Energien nutzen, um Emissionen zu reduzieren?', 2, '[{"text": "Nein", "correct": true, "because": "Freiwillig, aber effektiv"}, {"text": "Ja", "correct": false, "because": "Keine Pflicht, nur Option"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Emissionsreduktion in einem IT-Betrieb die Betriebskosten langfristig senken?', 2, '[{"text": "Ja", "correct": true, "because": "Energieeffizienz spart Kosten"}, {"text": "Nein", "correct": false, "because": "Langfristige Einsparungen möglich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme trägt in einem IT-Betrieb zur Emissionsreduktion bei?', 2, '[{"text": "Nutzung erneuerbarer Energien", "correct": true, "because": "Reduziert CO₂ durch fossile Brennstoffe"}, {"text": "Erhöhter Energieverbrauch", "correct": false, "because": "Erhöht Emissionen"}, {"text": "Weniger Hardware", "correct": false, "because": "Nicht primär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptziel der Emissionsreduktion in einem IT-Betrieb?', 3, '[{"text": "Verringerung des CO₂-Fußabdrucks", "correct": true, "because": "Nachhaltigkeit zielt auf Klimaschutz"}, {"text": "Erhöhung der Betriebskosten", "correct": false, "because": "Kein Ziel"}, {"text": "Reduktion der Produktivität", "correct": false, "because": "Nicht beabsichtigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie unterstützt die Emissionsreduktion in einem IT-Betrieb?', 3, '[{"text": "Energieeffiziente Server", "correct": true, "because": "Senkt Stromverbrauch und CO₂"}, {"text": "Alte Hardware", "correct": false, "because": "Erhöht Energieverbrauch"}, {"text": "Manuelle Prozesse", "correct": false, "because": "Kein Einfluss auf Emissionen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer ist in einem IT-Betrieb für die Umsetzung von Emissionsreduktionsmaßnahmen verantwortlich?', 2, '[{"text": "Das Management", "correct": true, "because": "Entscheidet über Strategien und Ressourcen"}, {"text": "Die Auszubildenden", "correct": false, "because": "Nicht deren Aufgabe"}, {"text": "Die Kunden", "correct": false, "because": "Keine Rolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil ergibt sich durch Emissionsreduktion für einen IT-Betrieb?', 3, '[{"text": "Verbessertes Unternehmensimage", "correct": true, "because": "Nachhaltigkeit stärkt Reputation"}, {"text": "Höhere Energiekosten", "correct": false, "because": "Kosten sinken oft"}, {"text": "Geringere Produktivität", "correct": false, "because": "Produktivität bleibt"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen tragen zur Emissionsreduktion in einem IT-Betrieb bei?', 4, '[{"text": "Energieeffiziente Hardware", "correct": true, "because": "Senkt Stromverbrauch"}, {"text": "Nutzung erneuerbarer Energien", "correct": true, "because": "Reduziert CO₂"}, {"text": "Erhöhter Energieverbrauch", "correct": false, "because": "Erhöht Emissionen"}, {"text": "Homeoffice-Optionen", "correct": true, "because": "Weniger Pendeln"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Emissionsreduktion einem IT-Betrieb?', 3, '[{"text": "Kostensenkung langfristig", "correct": true, "because": "Energieeffizienz spart Geld"}, {"text": "Verbessertes Image", "correct": true, "because": "Nachhaltigkeit stärkt Reputation"}, {"text": "Höhere Emissionen", "correct": false, "because": "Kein Vorteil"}, {"text": "Kundenzufriedenheit", "correct": true, "because": "Umweltbewusstsein wird geschätzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile können durch Emissionsreduktion in einem IT-Betrieb entstehen?', 4, '[{"text": "Kurzfristige Investitionskosten", "correct": true, "because": "Neue Hardware kostet Geld"}, {"text": "Komplexere Prozesse", "correct": true, "because": "Umstellung kann Aufwand erfordern"}, {"text": "Geringere Energieeffizienz", "correct": false, "because": "Effizienz steigt"}, {"text": "Zeitaufwand für Umsetzung", "correct": true, "because": "Planung benötigt Zeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien unterstützen die Emissionsreduktion in einem IT-Betrieb?', 3, '[{"text": "Cloud Computing mit grüner Energie", "correct": true, "because": "Reduziert lokalen Energieverbrauch"}, {"text": "Energieeffiziente Server", "correct": true, "because": "Senkt CO₂-Ausstoß"}, {"text": "Alte, ineffiziente Geräte", "correct": false, "because": "Erhöht Emissionen"}, {"text": "Virtualisierung", "correct": true, "because": "Optimiert Ressourcennutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Emissionsreduktion in einem IT-Betrieb?', 3, '[{"text": "Energieverbrauch der Hardware", "correct": true, "because": "Hauptquelle für Emissionen"}, {"text": "Pendeln der Mitarbeiter", "correct": true, "because": "Beeinflusst CO₂-Fußabdruck"}, {"text": "Produktivität der Mitarbeiter", "correct": false, "because": "Kein direkter Einfluss"}, {"text": "Nutzung erneuerbarer Energien", "correct": true, "because": "Reduziert Emissionen"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Emissionsreduktion kann durch energieeffiziente Hardware erreicht werden. b) Sie ist in einem IT-Betrieb gesetzlich vorgeschrieben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Homeoffice reduziert Emissionen in einem IT-Betrieb. b) Emissionsreduktion kann Betriebskosten langfristig senken.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Homeoffice und Kostensenkung"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Erneuerbare Energien tragen zur Emissionsreduktion bei. b) Emissionsreduktion erhöht kurzfristig die Kosten.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Energien und Kosten"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Emissionsreduktion verbessert das Image eines IT-Betriebs. b) Fachinformatiker haben keinen Einfluss darauf.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Image ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Cloud Computing mit grüner Energie reduziert Emissionen. b) Emissionsreduktion ist nur für große IT-Betriebe relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Cloud ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

