-- # Lernfeld 5: Cyberphysische Systeme > ## Testgetriebene Entwicklung > - Best Practices > - Klare Testbenennung, Einzelverantwortlichkeit von Tests, Vermeidung von Abhängigkeiten zwischen Tests

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist eine klare Testbenennung in TDD notwendig, um die Lesbarkeit und Verständlichkeit der Tests zu gewährleisten?', 2, '[{"text": "Ja", "correct": true, "because": "Klarheit verbessert Verständnis"}, {"text": "Nein", "correct": false, "because": "Lesbarkeit ist zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Einzelverantwortlichkeit von Tests in TDD die Fehlersuche erschweren?', 2, '[{"text": "Nein", "correct": true, "because": "Isolierte Tests vereinfachen Fehlersuche"}, {"text": "Ja", "correct": false, "because": "Einzelverantwortung hilft"}]'),
('00000000-0000-0000-0000-000000000000', 'Vermeidet die Praxis, Abhängigkeiten zwischen Tests in TDD zu verhindern, potenzielle Testfehler?', 2, '[{"text": "Ja", "correct": true, "because": "Unabhängigkeit reduziert Fehlerquellen"}, {"text": "Nein", "correct": false, "because": "Abhängigkeiten riskant"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle Tests in TDD immer eine klare Benennung haben, um funktional zu sein?', 2, '[{"text": "Nein", "correct": true, "because": "Funktion unabhängig, Verständnis verbessert"}, {"text": "Ja", "correct": false, "because": "Klarheit ist Best Practice"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Abhängigkeiten zwischen Tests in TDD die Wartbarkeit der Test-Suite negativ beeinflussen?', 2, '[{"text": "Ja", "correct": true, "because": "Abhängigkeiten erschweren Änderungen"}, {"text": "Nein", "correct": false, "because": "Wartbarkeit leidet"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt eine klare Testbenennung in TDD?', 2, '[{"text": "Verbesserung der Lesbarkeit", "correct": true, "because": "Klarheit für Entwickler"}, {"text": "Schnellere Testausführung", "correct": false, "because": "Nicht primär"}, {"text": "Reduzierung der Testanzahl", "correct": false, "because": "Unbeeinflusst"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil ergibt sich aus der Einzelverantwortlichkeit von Tests in TDD?', 3, '[{"text": "Einfachere Fehlersuche", "correct": true, "because": "Isolierte Tests zeigen Fehler klar"}, {"text": "Komplexere Tests", "correct": false, "because": "Eher vereinfacht"}, {"text": "Weniger Testaufwand", "correct": false, "because": "Aufwand unbeeinflusst"}]'),
('00000000-0000-0000-0000-000000000000', 'Warum wird die Vermeidung von Abhängigkeiten zwischen Tests in TDD empfohlen?', 2, '[{"text": "Erhöhte Unabhängigkeit", "correct": true, "because": "Tests laufen isoliert"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Nicht primär"}, {"text": "Weniger Tests", "correct": false, "because": "Anzahl unbeeinflusst"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der klaren Testbenennung hilft bei der Wartung?', 2, '[{"text": "Selbsterklärende Namen", "correct": true, "because": "Vereinfacht Verständnis"}, {"text": "Kürzere Namen", "correct": false, "because": "Klarheit über Kürze"}, {"text": "Technische Details", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Best Practice in TDD erleichtert die Fehlersuche am meisten?', 2, '[{"text": "Einzelverantwortlichkeit", "correct": true, "because": "Isolierte Tests helfen"}, {"text": "Komplexe Testnamen", "correct": false, "because": "Eher hinderlich"}, {"text": "Testabhängigkeiten", "correct": false, "because": "Erschwert Fehlersuche"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine klare Testbenennung in TDD?', 4, '[{"text": "Besseres Verständnis", "correct": true, "because": "Tests leicht lesbar"}, {"text": "Schnellere Fehlersuche", "correct": true, "because": "Klarheit hilft"}, {"text": "Langsamere Tests", "correct": false, "because": "Unbeeinflusst"}, {"text": "Einfachere Wartung", "correct": true, "because": "Verständnis erleichtert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte fördert die Einzelverantwortlichkeit von Tests in TDD?', 3, '[{"text": "Isolation", "correct": true, "because": "Tests unabhängig"}, {"text": "Klarheit der Fehlerquelle", "correct": true, "because": "Fehler leicht lokalisierbar"}, {"text": "Komplexere Tests", "correct": false, "because": "Eher vereinfacht"}, {"text": "Verbesserte Testbarkeit", "correct": true, "because": "Einzelne Funktionen prüfbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Gründe unterstützen die Vermeidung von Abhängigkeiten zwischen Tests in TDD?', 3, '[{"text": "Erhöhte Zuverlässigkeit", "correct": true, "because": "Tests unabhängig ausführbar"}, {"text": "Einfachere Wartung", "correct": true, "because": "Änderungen isoliert"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Nicht primär"}, {"text": "Robustheit der Test-Suite", "correct": true, "because": "Weniger Fehlerquellen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Best Practices tragen zur Testqualität in TDD bei?', 4, '[{"text": "Klare Testbenennung", "correct": true, "because": "Fördert Verständnis"}, {"text": "Einzelverantwortlichkeit", "correct": true, "because": "Isoliert Fehler"}, {"text": "Abhängige Tests", "correct": false, "because": "Eher schädlich"}, {"text": "Unabhängigkeit der Tests", "correct": true, "because": "Sichert Robustheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen können diese Best Practices in TDD vermeiden?', 3, '[{"text": "Unklare Testzwecke", "correct": true, "because": "Klare Namen helfen"}, {"text": "Schwierige Fehlersuche", "correct": true, "because": "Einzelverantwortung vereinfacht"}, {"text": "Hohe Testanzahl", "correct": false, "because": "Unbeeinflusst"}, {"text": "Testinstabilität", "correct": true, "because": "Unabhängigkeit reduziert Risiken"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Klare Testbenennung verbessert die Wartbarkeit. b) Einzelverantwortlichkeit erhöht die Testkomplexität.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wartbarkeit ja, Komplexität nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Abhängigkeiten zwischen Tests erhöhen die Zuverlässigkeit. b) Klare Testbenennung erleichtert die Fehlersuche.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Abhängigkeiten schaden, Klarheit hilft"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Einzelverantwortlichkeit isoliert Tests in TDD. b) Testabhängigkeiten sind eine Best Practice.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Isolation ja, Abhängigkeiten nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Klare Testbenennung ist in TDD optional. b) Vermeidung von Testabhängigkeiten verbessert die Robustheit.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Klarheit empfohlen, Robustheit steigt"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Einzelverantwortlichkeit vereinfacht die Wartung. b) Klare Testbenennung ist nur für große Projekte relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wartung ja, Klarheit immer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

