-- # Lernfeld 5: Cyberphysische Systeme > ## Testgetriebene Entwicklung > - Herausforderungen > - Lernkurve, Zeitaufwand für Testentwicklung, Testwartung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Lernkurve für TDD eine Herausforderung für Entwickler ohne Test-Erfahrung?', 2, '[{"text": "Ja", "correct": true, "because": "TDD erfordert neues Mindset"}, {"text": "Nein", "correct": false, "because": "Lernaufwand real"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann der Zeitaufwand für die Testentwicklung in TDD die Entwicklungsgeschwindigkeit langfristig erhöhen?', 2, '[{"text": "Ja", "correct": true, "because": "Tests reduzieren Nacharbeit"}, {"text": "Nein", "correct": false, "because": "Langfristige Effizienz"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Testwartung in TDD nur bei großen Projekten eine Herausforderung?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte betroffen"}, {"text": "Ja", "correct": false, "because": "Wartung universell"}]'),
('00000000-0000-0000-0000-000000000000', 'Können eine steile Lernkurve und hoher Zeitaufwand den Einsatz von TDD verhindern?', 2, '[{"text": "Ja", "correct": true, "because": "Hürden können abschrecken"}, {"text": "Nein", "correct": false, "because": "Überwindbar, aber real"}]'),
('00000000-0000-0000-0000-000000000000', 'Erfordert die Testwartung in TDD ständige Anpassung bei Änderungen im Code?', 2, '[{"text": "Ja", "correct": true, "because": "Tests müssen aktuell bleiben"}, {"text": "Nein", "correct": false, "because": "Wartung nötig"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Lernkurve stellt die größte Herausforderung in TDD dar?', 2, '[{"text": "Verständnis für Tests vor Code", "correct": true, "because": "Neues Mindset nötig"}, {"text": "Code-Komplexität", "correct": false, "because": "Sekundär"}, {"text": "Dokumentation", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die Hauptursache für den hohen Zeitaufwand der Testentwicklung in TDD?', 3, '[{"text": "Erstellen von Tests vor der Implementierung", "correct": true, "because": "Initialer Aufwand"}, {"text": "Manuelle Testausführung", "correct": false, "because": "Automatisiert"}, {"text": "Fehlende Werkzeuge", "correct": false, "because": "Werkzeuge vorhanden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor macht die Testwartung in TDD besonders aufwendig?', 2, '[{"text": "Änderungen im Code", "correct": true, "because": "Tests müssen angepasst werden"}, {"text": "Hohe Testanzahl", "correct": false, "because": "Sekundär"}, {"text": "Keine Automatisierung", "correct": false, "because": "Automatisierung üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie kann die Lernkurve für TDD reduziert werden?', 2, '[{"text": "Training und Praxis", "correct": true, "because": "Erfahrung verringert Hürden"}, {"text": "Weniger Tests", "correct": false, "because": "Nicht TDD-konform"}, {"text": "Komplexere Tools", "correct": false, "because": "Erhöht Lernaufwand"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme minimiert den Zeitaufwand für Testentwicklung in TDD?', 2, '[{"text": "Wiederverwendbare Testfixtures", "correct": true, "because": "Reduziert Aufwand"}, {"text": "Manuelle Tests", "correct": false, "because": "Ineffizient"}, {"text": "Weniger Refactoring", "correct": false, "because": "Nicht zielführend"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren tragen zur Lernkurve in TDD bei?', 4, '[{"text": "Tests vor Code schreiben", "correct": true, "because": "Neues Konzept"}, {"text": "Verständnis von Test-Frameworks", "correct": true, "because": "Technisches Wissen nötig"}, {"text": "Keine Vorkenntnisse nötig", "correct": false, "because": "Wissen hilfreich"}, {"text": "Refactoring-Praktiken", "correct": true, "because": "Strukturverständnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente erhöhen den Zeitaufwand für Testentwicklung in TDD?', 3, '[{"text": "Tests vor Implementierung", "correct": true, "because": "Initialer Aufwand"}, {"text": "Detaillierte Testfälle", "correct": true, "because": "Spezifikation nötig"}, {"text": "Automatisierte Ausführung", "correct": false, "because": "Spart Zeit"}, {"text": "Testabdeckung erhöhen", "correct": true, "because": "Mehr Tests nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Testwartung in TDD?', 3, '[{"text": "Code-Änderungen", "correct": true, "because": "Tests müssen angepasst werden"}, {"text": "Unklare Anforderungen", "correct": true, "because": "Tests schwer aktuell"}, {"text": "Keine Automatisierung", "correct": false, "because": "Automatisierung üblich"}, {"text": "Hohe Testanzahl", "correct": true, "because": "Wartungsaufwand steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie kann die Lernkurve in TDD überwunden werden?', 4, '[{"text": "Schulungen", "correct": true, "because": "Wissen aufbauen"}, {"text": "Praxisprojekte", "correct": true, "because": "Erfahrung sammeln"}, {"text": "Komplexere Tools", "correct": false, "because": "Erhöht Aufwand"}, {"text": "Pair Programming", "correct": true, "because": "Wissen teilen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen reduzieren den Aufwand für Testwartung in TDD?', 3, '[{"text": "Modulare Tests", "correct": true, "because": "Einfacher anpassbar"}, {"text": "Klare Anforderungen", "correct": true, "because": "Weniger Änderungen"}, {"text": "Weniger Refactoring", "correct": false, "because": "Nicht zielführend"}, {"text": "Wiederverwendbare Fixtures", "correct": true, "because": "Vereinfacht Wartung"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Lernkurve in TDD betrifft nur Anfänger. b) Zeitaufwand für Testentwicklung ist eine TDD-Herausforderung.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Lernkurve allgemein, Zeitaufwand real"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Testwartung in TDD ist bei Änderungen nötig. b) Die Lernkurve in TDD ist unbedeutend.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wartung real, Lernkurve signifikant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Zeitaufwand für Testentwicklung in TDD kann langfristig sinken. b) Testwartung ist in TDD optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Effizienz steigt, Wartung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Lernkurve in TDD kann durch Praxis reduziert werden. b) Zeitaufwand für Testentwicklung ist in TDD vermeidbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Praxis hilft, Zeitaufwand real"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Testwartung in TDD erhöht den Aufwand bei Änderungen. b) Die Lernkurve in TDD betrifft nur große Teams.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wartung real, Lernkurve allgemein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

