-- questions.sql (Cache-Themenbereich für Fachinformatiker, IHK-Ausbildung)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist der Cache immer schneller als der Arbeitsspeicher?', 2, '[{"text": "Ja", "correct": true, "because": "Näher an der CPU, geringere Latenz"}, {"text": "Nein", "correct": false, "because": "Nur in Ausnahmen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt der Cache bei der CPU-Leistung?', 3, '[{"text": "Verkürzt Zugriffszeiten", "correct": true, "because": "Daten schneller verfügbar"}, {"text": "Erhöht Taktfrequenz", "correct": false, "because": "Unabhängig davon"}, {"text": "Reduziert Stromverbrauch", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ebenen gehören typischerweise zum Cache?', 4, '[{"text": "L1", "correct": true, "because": "Schnellster Cache"}, {"text": "L2", "correct": true, "because": "Größer als L1"}, {"text": "RAM", "correct": false, "because": "Hauptspeicher"}, {"text": "SSD", "correct": false, "because": "Sekundärspeicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) L1-Cache ist kleiner als L2. b) L3 ist immer auf der CPU.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "L3 kann extern sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht immer wahr"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl eines Prozessors, wenn ich nur auf Cache achte?', 4, '[{"text": "Taktfrequenz", "correct": true, "because": "Auch entscheidend für Leistung"}, {"text": "Cache-Größe", "correct": false, "because": "Direkt relevant"}, {"text": "Kernanzahl", "correct": false, "because": "Wichtig für Multitasking"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob mehr Cache immer besser ist?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig vom Workload"}, {"text": "Ja", "correct": false, "because": "Nicht universell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaft macht den Cache so schnell?', 3, '[{"text": "Nähe zur CPU", "correct": true, "because": "Geringe Latenz"}, {"text": "Große Kapazität", "correct": false, "because": "Gegenteil ist wahr"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Cache-Leistung?', 5, '[{"text": "Hit-Rate", "correct": true, "because": "Effektivität der Vorhersage"}, {"text": "Latenz", "correct": true, "because": "Zugriffsgeschwindigkeit"}, {"text": "Taktfrequenz", "correct": false, "because": "CPU-spezifisch"}, {"text": "Festplattenzugriff", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Cache ist flüchtig. b) Er speichert nur Programmcode. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Daten werden gecacht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist für die Cache-Funktion unwichtig?', 4, '[{"text": "Zugriffszeit", "correct": false, "because": "Entscheidend für Geschwindigkeit"}, {"text": "Größe", "correct": false, "because": "Beeinflusst Kapazität"}, {"text": "Betriebssystem", "correct": true, "because": "Hardwareabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist der Cache Teil des RAM?', 2, '[{"text": "Nein", "correct": true, "because": "Separater Speicher"}, {"text": "Ja", "correct": false, "because": "Verwechselbar, aber falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Daten speichert der Cache typischerweise?', 4, '[{"text": "Häufig genutzte Daten", "correct": true, "because": "Optimiert Zugriff"}, {"text": "Befehle der CPU", "correct": true, "because": "Schnelle Ausführung"}, {"text": "Komplette Programme", "correct": false, "because": "Zu groß"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein größerer Cache immer die Leistung steigert. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Abhängig von Anwendung"}, {"text": "Ja", "correct": false, "because": "Nicht immer linear"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Cache-System?', 3, '[{"text": "Schnelligkeit", "correct": true, "because": "Primäres Ziel"}, {"text": "Kapazität", "correct": false, "because": "Wichtig, aber sekundär"}, {"text": "Kosten", "correct": false, "because": "Nicht technisch entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Cache ist SRAM. b) RAM ist immer DRAM.', 4, '[{"text": "Nur a) stimmt", "correct": true, "because": "RAM kann auch SRAM sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht immer wahr"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein großer Cache?', 5, '[{"text": "Höhere Hit-Rate", "correct": true, "because": "Mehr Daten verfügbar"}, {"text": "Weniger Hauptspeicherzugriffe", "correct": true, "because": "Schnellerer Zugriff"}, {"text": "Höhere Taktfrequenz", "correct": false, "because": "Unabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Cache-Größe irrelevant?', 3, '[{"text": "Workload", "correct": false, "because": "Beeinflusst Effizienz"}, {"text": "Latenz", "correct": false, "because": "Entscheidend für Leistung"}, {"text": "Monitorauflösung", "correct": true, "because": "Kein Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Wird der Cache bei einem Stromausfall gelöscht?', 2, '[{"text": "Ja", "correct": true, "because": "Flüchtiger Speicher"}, {"text": "Nein", "correct": false, "because": "Nicht persistent"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob der Cache auch auf SSDs genutzt wird?', 3, '[{"text": "Ja", "correct": true, "because": "Zwischenspeicher möglich"}, {"text": "Nein", "correct": false, "because": "Nicht ausschließlich CPU"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip nutzt der Cache für Effizienz?', 4, '[{"text": "Lokalität", "correct": true, "because": "Räumliche und zeitliche Nähe"}, {"text": "Multithreading", "correct": false, "because": "CPU-spezifisch"}, {"text": "Kompression", "correct": false, "because": "Nicht anwendbar"}]');

