-- questions.sql (Colocation, relevant für Serverhousing und IT-Infrastruktur)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Colocation nur für große Unternehmen sinnvoll?', 2, '[{"text": "Nein", "correct": true, "because": "Auch KMUs nutzen es"}, {"text": "Ja", "correct": false, "because": "Skalierbar für alle Größen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Vorteil bietet mir das Housing meiner Server?', 3, '[{"text": "Hohe Verfügbarkeit", "correct": true, "because": "Rechenzentrum-Infrastruktur"}, {"text": "Kostenlose Wartung", "correct": false, "because": "Wartung bleibt meine Aufgabe"}, {"text": "Schnellere Software", "correct": false, "because": "Hardware-fokussiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zu einem Colocation-Angebot?', 5, '[{"text": "Stromversorgung", "correct": true, "because": "Essenziell für Betrieb"}, {"text": "Kühlung", "correct": true, "because": "Schützt Hardware"}, {"text": "Softwarelizenzen", "correct": false, "because": "Nicht enthalten"}, {"text": "Programmierung", "correct": false, "because": "Eigene Verantwortung"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Colocation spart Platz im Büro. b) Ich verliere die Kontrolle über meine Hardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kontrolle bleibt bei mir"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl eines Anbieters?', 4, '[{"text": "Netzwerkverfügbarkeit", "correct": false, "because": "Kritisch für Zugriff"}, {"text": "Kühlung", "correct": false, "because": "Schützt die Hardware"}, {"text": "Firmenfarben", "correct": true, "because": "Irrelevant für Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ich bei Colocation die Hardware warten muss?', 2, '[{"text": "Ja", "correct": true, "because": "Wartung bleibt meine Aufgabe"}, {"text": "Nein", "correct": false, "because": "Anbieter kümmert sich nur um Infrastruktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Faktor priorisiere ich bei der Anbieterwahl?', 3, '[{"text": "Redundante Stromversorgung", "correct": true, "because": "Sichert Betrieb"}, {"text": "Kostenlose Updates", "correct": false, "because": "Nicht enthalten"}, {"text": "Schönes Gebäude", "correct": false, "because": "Kein technischer Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bringt mir das Serverhousing?', 5, '[{"text": "Bessere Kühlung", "correct": true, "because": "Professionelle Systeme"}, {"text": "Schnelle Internetanbindung", "correct": true, "because": "Rechenzentrum-Qualität"}, {"text": "Kostenlose Software", "correct": false, "because": "Nicht inbegriffen"}, {"text": "Automatische Backups", "correct": false, "because": "Eigene Verantwortung"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Colocation reduziert meine Betriebskosten. b) Ich muss alles selbst konfigurieren. Stimmt das?', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Kostensenkung und Eigenverantwortung"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "Beide sind richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht vom Anbieter?', 4, '[{"text": "Strom", "correct": false, "because": "Kern des Angebots"}, {"text": "Sicherheit", "correct": false, "because": "Schützt meine Hardware"}, {"text": "Betriebssystem", "correct": true, "because": "Eigene Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Colocation dasselbe wie Cloud-Hosting?', 2, '[{"text": "Nein", "correct": true, "because": "Eigene Hardware vs. virtuelle Ressourcen"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Ansätze"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen einen Standort attraktiv?', 4, '[{"text": "Hohe Bandbreite", "correct": true, "because": "Schneller Datentransfer"}, {"text": "Physische Sicherheit", "correct": true, "because": "Schützt vor Zugriff"}, {"text": "Günstige Miete", "correct": false, "because": "Qualität zählt mehr"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ich bei Colocation keine Internetverbindung brauche. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Netzwerk ist essenziell"}, {"text": "Ja", "correct": false, "because": "Ohne Zugriff nutzlos"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Planung?', 3, '[{"text": "Redundanz", "correct": true, "because": "Minimiert Ausfälle"}, {"text": "Niedrige Latenz", "correct": false, "because": "Wichtig, aber sekundär"}, {"text": "Farbliche Gestaltung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Colocation bietet Klimatisierung. b) Ich muss die Software warten.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Infrastruktur vs. Eigenverantwortung"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "Beide sind richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kosten spare ich durch Serverhousing?', 5, '[{"text": "Kühlkosten", "correct": true, "because": "Rechenzentrum übernimmt"}, {"text": "Stromkosten", "correct": true, "because": "Inklusive im Service"}, {"text": "Hardwarekosten", "correct": false, "because": "Bleiben meine Last"}, {"text": "Lizenzkosten", "correct": false, "because": "Unabhängig davon"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Anbieter unwichtig?', 3, '[{"text": "Stromversorgung", "correct": false, "because": "Kern des Betriebs"}, {"text": "Kühlung", "correct": false, "because": "Schützt Hardware"}, {"text": "Kaffeemaschine", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Übernimmt der Anbieter meine Backups?', 3, '[{"text": "Nein", "correct": true, "because": "Eigene Verantwortung"}, {"text": "Ja", "correct": false, "because": "Nur Infrastruktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Colocation auch für virtuelle Server geht?', 2, '[{"text": "Nein", "correct": true, "because": "Physische Hardware nötig"}, {"text": "Ja", "correct": false, "because": "Cloud ist anders"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Aspekt überprüfe ich zuerst beim Anbieter?', 4, '[{"text": "SLA-Verfügbarkeit", "correct": true, "because": "Garantierte Betriebszeit"}, {"text": "Standortdesign", "correct": false, "because": "Ästhetik unwichtig"}, {"text": "Mitarbeiterzahl", "correct": false, "because": "Kein direkter Einfluss"}]');

