-- questions.sql (Container, relevant für Virtualisierung und Softwarebereitstellung)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Container dasselbe wie eine virtuelle Maschine?', 2, '[{"text": "Nein", "correct": true, "because": "Container teilen den Kernel, VMs nicht"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Technologien"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Zweck verfolge ich mit Containern?', 3, '[{"text": "Konsistente Bereitstellung", "correct": true, "because": "Umgebungen bleiben gleich"}, {"text": "Hardware-Optimierung", "correct": false, "because": "Nicht primär"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Kein Sicherheitsfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zu einem Container?', 5, '[{"text": "Anwendungscode", "correct": true, "because": "Kern der Ausführung"}, {"text": "Bibliotheken", "correct": true, "because": "Abhängigkeiten enthalten"}, {"text": "Eigenes Betriebssystem", "correct": false, "because": "Nutzt Host-Kernel"}, {"text": "Grafikschnittstelle", "correct": false, "because": "Nicht enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Container sind leichtgewichtig. b) Sie benötigen Hypervisoren.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Keine Hypervisoren nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Container-Nutzung?', 4, '[{"text": "Abhängigkeiten", "correct": false, "because": "Müssen enthalten sein"}, {"text": "Orchestrierung", "correct": false, "because": "Wichtig bei Skalierung"}, {"text": "Monitorauflösung", "correct": true, "because": "Irrelevant für Container"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Container eigene Kernel haben?', 2, '[{"text": "Nein", "correct": true, "because": "Nutzen den Host-Kernel"}, {"text": "Ja", "correct": false, "because": "Unterschied zu VMs"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool nutze ich typischerweise dafür?', 3, '[{"text": "Docker", "correct": true, "because": "Standard für Container"}, {"text": "VMware", "correct": false, "because": "Für VMs, nicht Container"}, {"text": "Apache", "correct": false, "because": "Webserver, kein Container-Tool"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Container?', 5, '[{"text": "Portabilität", "correct": true, "because": "Übertragbar zwischen Systemen"}, {"text": "Schneller Start", "correct": true, "because": "Kein OS-Boot nötig"}, {"text": "Hohe Grafikleistung", "correct": false, "because": "Nicht relevant"}, {"text": "Eingebaute Sicherheit", "correct": false, "because": "Muss separat konfiguriert werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Container sind schneller als VMs. b) Sie sind immer sicherer. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Sicherheit nicht garantiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen Container?', 4, '[{"text": "Runtime", "correct": false, "because": "Zum Ausführen nötig"}, {"text": "Image", "correct": false, "because": "Grundlage des Containers"}, {"text": "Dedizierte Festplatte", "correct": true, "because": "Nutzt Host-Ressourcen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Container plattformabhängig?', 2, '[{"text": "Nein", "correct": true, "because": "Laufen auf kompatiblen Hosts"}, {"text": "Ja", "correct": false, "because": "Hohe Portabilität"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben erledige ich mit Containern?', 4, '[{"text": "Anwendungsdeployment", "correct": true, "because": "Konsistente Umgebung"}, {"text": "Microservices", "correct": true, "because": "Unabhängige Dienste"}, {"text": "Hardware-Reparatur", "correct": false, "because": "Kein physischer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Container keine Netzwerke brauchen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kommunikation oft nötig"}, {"text": "Ja", "correct": false, "because": "Netzwerkfähigkeit vorhanden"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Nutzung?', 3, '[{"text": "Isolation", "correct": true, "because": "Sichert Abgrenzung"}, {"text": "Maximale CPU", "correct": false, "because": "Nicht primär"}, {"text": "Schnelle Installation", "correct": false, "because": "Konfiguration wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Container sind skalierbar. b) Sie ersetzen Betriebssysteme.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien unterstützen Container?', 5, '[{"text": "Docker", "correct": true, "because": "Verwaltet Container"}, {"text": "Kubernetes", "correct": true, "because": "Orchestriert sie"}, {"text": "Photoshop", "correct": false, "because": "Kein Zusammenhang"}, {"text": "Excel", "correct": false, "because": "Kein Container-Tool"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Verwaltung unwichtig?', 3, '[{"text": "Ressourcenzuweisung", "correct": false, "because": "Sichert Leistung"}, {"text": "Netzwerkkonfiguration", "correct": false, "because": "Wichtig für Kommunikation"}, {"text": "Bildschirmgröße", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzen Container virtuelle Maschinen komplett?', 3, '[{"text": "Nein", "correct": true, "because": "Verschiedene Anwendungsfälle"}, {"text": "Ja", "correct": false, "because": "VMs bleiben relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Container für kleine Projekte geeignet sind?', 2, '[{"text": "Ja", "correct": true, "because": "Flexibel einsetzbar"}, {"text": "Nein", "correct": false, "because": "Auch für kleine Umgebungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature ist für Container entscheidend?', 4, '[{"text": "Namespacing", "correct": true, "because": "Isoliert Prozesse"}, {"text": "Hohe Taktfrequenz", "correct": false, "because": "Hardware-Faktor"}, {"text": "Grafiktreiber", "correct": false, "because": "Nicht relevant"}]');

