-- questions.sql (CPU, relevant für Kernkomponenten und Hardware)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die CPU dasselbe wie der Arbeitsspeicher?', 2, '[{"text": "Nein", "correct": true, "because": "CPU rechnet, RAM speichert"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Funktionen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe übernimmt die CPU primär?', 3, '[{"text": "Befehle ausführen", "correct": true, "because": "Kern der Verarbeitung"}, {"text": "Daten speichern", "correct": false, "because": "Aufgabe des RAM"}, {"text": "Grafik rendern", "correct": false, "because": "GPU-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zur CPU?', 5, '[{"text": "Rechenwerk", "correct": true, "because": "Führt Berechnungen durch"}, {"text": "Steuerwerk", "correct": true, "because": "Koordiniert Abläufe"}, {"text": "Festplatte", "correct": false, "because": "Externer Speicher"}, {"text": "Grafikeinheit", "correct": false, "because": "Optional, nicht Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die CPU hat mehrere Kerne. b) Sie arbeitet ohne Taktgeber.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Taktgeber ist essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der CPU-Auswahl?', 4, '[{"text": "Taktfrequenz", "correct": false, "because": "Beeinflusst Leistung"}, {"text": "Sockeltyp", "correct": false, "because": "Muss zum Mainboard passen"}, {"text": "Gehäusefarbe", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die CPU auch Grafik berechnet?', 2, '[{"text": "Ja", "correct": true, "because": "Bei integrierter GPU"}, {"text": "Nein", "correct": false, "because": "Möglich mit iGPU"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Faktor priorisiere ich für hohe Leistung?', 3, '[{"text": "Kernanzahl", "correct": true, "because": "Mehr Kerne, mehr Parallelität"}, {"text": "Geringer Preis", "correct": false, "because": "Leistung zählt"}, {"text": "Kleine Größe", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen eine CPU effizient?', 5, '[{"text": "Hohe Taktfrequenz", "correct": true, "because": "Schnellere Verarbeitung"}, {"text": "Großer Cache", "correct": true, "because": "Schneller Datenzugriff"}, {"text": "Hohe Lautstärke", "correct": false, "because": "Irrelevant"}, {"text": "Schönes Design", "correct": false, "because": "Kein Leistungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Mehr Kerne sind immer besser. b) Die CPU kühlt sich selbst. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kühlung extern nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht direkt für die CPU?', 4, '[{"text": "Kühler", "correct": false, "because": "Verhindert Überhitzung"}, {"text": "Mainboard", "correct": false, "because": "Sockel nötig"}, {"text": "Externer Akku", "correct": true, "because": "Für Laptops, nicht Desktop"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Taktfrequenz der einzige Leistungsfaktor?', 2, '[{"text": "Nein", "correct": true, "because": "Kerne und Cache zählen auch"}, {"text": "Ja", "correct": false, "because": "Nur ein Teil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben übernimmt die CPU?', 4, '[{"text": "Befehlsverarbeitung", "correct": true, "because": "Kernaufgabe"}, {"text": "Datenflusssteuerung", "correct": true, "because": "Koordiniert Prozesse"}, {"text": "Dauerhafte Speicherung", "correct": false, "because": "Festplattenaufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine CPU ohne Cache nicht läuft. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Cache optimiert, ist aber optional"}, {"text": "Ja", "correct": false, "because": "Funktioniert auch ohne"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich für Gaming?', 3, '[{"text": "Hohe Single-Core-Leistung", "correct": true, "because": "Spiele nutzen oft einen Kern"}, {"text": "Maximaler Speicher", "correct": false, "because": "RAM-spezifisch"}, {"text": "Geringer Stromverbrauch", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die CPU hat einen Cache. b) Sie ist immer schneller als die GPU.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "GPU kann spezialisierter sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Leistung?', 5, '[{"text": "Taktfrequenz", "correct": true, "because": "Bestimmt Geschwindigkeit"}, {"text": "Kernanzahl", "correct": true, "because": "Ermöglicht Parallelität"}, {"text": "Bildschirmgröße", "correct": false, "because": "Kein Einfluss"}, {"text": "Tastaturlayout", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Auswahl unwichtig?', 3, '[{"text": "Kernanzahl", "correct": false, "because": "Beeinflusst Leistung"}, {"text": "TDP", "correct": false, "because": "Wärme und Strom relevant"}, {"text": "Verpackungsdesign", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Arbeitet die CPU ohne RAM?', 3, '[{"text": "Nein", "correct": true, "because": "RAM für Datenzugriff nötig"}, {"text": "Ja", "correct": false, "because": "Abhängig vom Speicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine CPU übertaktet werden kann?', 2, '[{"text": "Ja", "correct": true, "because": "Mit Vorsicht möglich"}, {"text": "Nein", "correct": false, "because": "Häufige Praxis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt der Cache?', 4, '[{"text": "Schneller Datenzugriff", "correct": true, "because": "Reduziert Wartezeiten"}, {"text": "Dauerhafte Speicherung", "correct": false, "because": "Nicht persistent"}, {"text": "Grafikverarbeitung", "correct": false, "because": "GPU-spezifisch"}]');

