-- questions.sql (Externe Datenträger - Speichermedien, z. B. für Systemintegration und Datenmanagement)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind externe Datenträger nur für Backups gedacht?', 2, '[{"text": "No", "correct": true, "because": "Also data transfer"}, {"text": "Yes", "correct": false, "because": "Multiple uses"}]'),
('00000000-0000-0000-0000-000000000000', 'What is the primary purpose of external storage devices?', 3, '[{"text": "Store and transfer data", "correct": true, "because": "Portable storage"}, {"text": "Run applications", "correct": false, "because": "Not primary"}, {"text": "Secure networks", "correct": false, "because": "Different focus"}]'),
('00000000-0000-0000-0000-000000000000', 'Which examples are external storage devices?', 5, '[{"text": "USB drives", "correct": true, "because": "Portable storage"}, {"text": "External HDDs", "correct": true, "because": "High capacity"}, {"text": "RAM", "correct": false, "because": "Internal memory"}]'),
('00000000-0000-0000-0000-000000000000', 'Are these statements correct? a) External storage devices are portable. b) They replace internal drives.', 3, '[{"text": "Only a) is correct", "correct": true, "because": "Supplement, not replace"}, {"text": "Both are correct", "correct": false, "because": "b) is false"}, {"text": "Only b) is correct", "correct": false, "because": "a) is true"}, {"text": "Both are false", "correct": false, "because": "a) is true"}]'),
('00000000-0000-0000-0000-000000000000', 'What do I ignore with external storage devices?', 4, '[{"text": "Capacity", "correct": false, "because": "Key factor"}, {"text": "Data security", "correct": false, "because": "Important concern"}, {"text": "Paper size", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Can you recall if external storage devices always need a USB connection?', 2, '[{"text": "No", "correct": true, "because": "Also Thunderbolt, eSATA"}, {"text": "Yes", "correct": false, "because": "Multiple interfaces"}]'),
('00000000-0000-0000-0000-000000000000', 'Which interface is commonly used for external storage devices?', 3, '[{"text": "USB", "correct": true, "because": "Widely supported"}, {"text": "HDMI", "correct": false, "because": "Video output"}, {"text": "Ethernet", "correct": false, "because": "Networking"}]'),
('00000000-0000-0000-0000-000000000000', 'What benefits do external storage devices offer?', 5, '[{"text": "Portability", "correct": true, "because": "Easy transport"}, {"text": "Additional storage", "correct": true, "because": "Expand capacity"}, {"text": "Increased CPU speed", "correct": false, "because": "Not performance-related"}]'),
('00000000-0000-0000-0000-000000000000', 'I’ve heard: a) External storage devices can store backups. b) They’re only for large files. Is that true?', 3, '[{"text": "Only a) is correct", "correct": true, "because": "Any file size"}, {"text": "Both are correct", "correct": false, "because": "b) is false"}, {"text": "Only b) is correct", "correct": false, "because": "a) is true"}, {"text": "Both are false", "correct": false, "because": "a) is true"}]'),
('00000000-0000-0000-0000-000000000000', 'What don’t I need for external storage devices?', 4, '[{"text": "Storage capacity", "correct": false, "because": "Core feature"}, {"text": "Interface compatibility", "correct": false, "because": "Connection needed"}, {"text": "Paper manuals", "correct": true, "because": "Digital sufficient"}]'),
('00000000-0000-0000-0000-000000000000', 'How was it again? Are external storage devices always removable?', 2, '[{"text": "Yes", "correct": true, "because": "Designed for portability"}, {"text": "No", "correct": false, "because": "Typically removable"}]'),
('00000000-0000-0000-0000-000000000000', 'Which devices commonly use external storage?', 4, '[{"text": "Computers", "correct": true, "because": "Data transfer"}, {"text": "Smartphones", "correct": true, "because": "Expanded storage"}, {"text": "Paper printers", "correct": false, "because": "Not typical"}]'),
('00000000-0000-0000-0000-000000000000', 'I’ve heard that external storage devices are only for personal use. Is that true?', 2, '[{"text": "No", "correct": true, "because": "Also business use"}, {"text": "Yes", "correct": false, "because": "Wide application"}]'),
('00000000-0000-0000-0000-000000000000', 'What do I prioritize with external storage devices?', 3, '[{"text": "Capacity", "correct": true, "because": "Storage needs"}, {"text": "Color", "correct": false, "because": "Irrelevant"}, {"text": "Speed", "correct": false, "because": "Secondary"}]'),
('00000000-0000-0000-0000-000000000000', 'Are these statements correct? a) External storage devices can be encrypted. b) They’re only for temporary data.', 3, '[{"text": "Only a) is correct", "correct": true, "because": "Permanent use possible"}, {"text": "Both are correct", "correct": false, "because": "b) is false"}, {"text": "Only b) is correct", "correct": false, "because": "a) is true"}, {"text": "Both are false", "correct": false, "because": "a) is true"}]'),
('00000000-0000-0000-0000-000000000000', 'What risks are associated with external storage devices?', 5, '[{"text": "Data loss", "correct": true, "because": "Physical damage"}, {"text": "Security breaches", "correct": true, "because": "Unauthorized access"}, {"text": "Paper jams", "correct": false, "because": "Not physical"}]'),
('00000000-0000-0000-0000-000000000000', 'What’s unimportant for external storage devices?', 3, '[{"text": "Transfer speed", "correct": false, "because": "Performance factor"}, {"text": "Durability", "correct": false, "because": "Reliability"}, {"text": "Print quality", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'How was it again? Can external storage devices be used for OS installation?', 3, '[{"text": "Yes", "correct": true, "because": "Bootable drives"}, {"text": "No", "correct": false, "because": "Possible with setup"}]'),
('00000000-0000-0000-0000-000000000000', 'Can you recall if external storage devices always need power?', 2, '[{"text": "No", "correct": true, "because": "USB-powered options"}, {"text": "Yes", "correct": false, "because": "Not always external power"}]'),
('00000000-0000-0000-0000-000000000000', 'What’s central to external storage devices?', 4, '[{"text": "Portability", "correct": true, "because": "Core feature"}, {"text": "High processing power", "correct": false, "because": "Not needed"}, {"text": "Paper records", "correct": false, "because": "Irrelevant"}]');

