-- questions.sql (Externes Rechenzentrum - Ausgelagerte IT-Infrastruktur, z. B. für Systemintegration)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein externes Rechenzentrum dasselbe wie ein internes Rechenzentrum?', 2, '[{"text": "Nein", "correct": true, "because": "Drittanbieter vs. Eigenbetrieb"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Betreiber"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt ein externes Rechenzentrum?', 3, '[{"text": "Bereitstellung von IT-Ressourcen", "correct": true, "because": "Outsourcing"}, {"text": "Daten lokal speichern", "correct": false, "because": "Extern"}, {"text": "Hardware verkaufen", "correct": false, "because": "Dienstleistung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zu einem externen Rechenzentrum?', 5, '[{"text": "Server", "correct": true, "because": "Rechenleistung"}, {"text": "Netzwerk", "correct": true, "because": "Konnektivität"}, {"text": "Papierdokumente", "correct": false, "because": "Digital"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein externes Rechenzentrum wird von Drittanbietern betrieben. b) Es ist immer teurer als interne Lösungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kosten variabel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem externen Rechenzentrum?', 4, '[{"text": "Datensicherheit", "correct": false, "because": "Kritisch"}, {"text": "Servicevertrag", "correct": false, "because": "Regelt Nutzung"}, {"text": "Papierformat", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein externes Rechenzentrum immer Cloud-basiert ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch dedizierte Server"}, {"text": "Ja", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Anbieter ist typisch für externe Rechenzentren?', 3, '[{"text": "AWS", "correct": true, "because": "Amazon Web Services"}, {"text": "Apache", "correct": false, "because": "Webserver"}, {"text": "MySQL", "correct": false, "because": "Datenbank"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein externes Rechenzentrum?', 5, '[{"text": "Skalierbarkeit", "correct": true, "because": "Flexibel anpassbar"}, {"text": "Kosteneinsparung", "correct": true, "because": "Kein Eigenbau"}, {"text": "Papierproduktion", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein externes Rechenzentrum reduziert Verwaltungsaufwand. b) Es ist immer unsicher. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Sicherheit abhängig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein externes Rechenzentrum?', 4, '[{"text": "Internetverbindung", "correct": false, "because": "Zugriff nötig"}, {"text": "Servicevertrag", "correct": false, "because": "Regelt Nutzung"}, {"text": "Eigenes Servergebäude", "correct": true, "because": "Extern"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein externes Rechenzentrum immer teurer als ein internes?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten variabel"}, {"text": "Ja", "correct": false, "because": "Oft günstiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Dienstleistungen bietet ein externes Rechenzentrum?', 4, '[{"text": "Hosting", "correct": true, "because": "Serverbereitstellung"}, {"text": "Backup", "correct": true, "because": "Datensicherung"}, {"text": "Papierarchivierung", "correct": false, "because": "Digital"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein externes Rechenzentrum keine Wartung braucht. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Anbieter wartet"}, {"text": "Ja", "correct": false, "because": "Wartung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem externen Rechenzentrum?', 3, '[{"text": "Datensicherheit", "correct": true, "because": "Schutz wichtig"}, {"text": "Papierdokumente", "correct": false, "because": "Irrelevant"}, {"text": "Schnelligkeit", "correct": false, "because": "Sicherheit zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein externes Rechenzentrum bietet Skalierbarkeit. b) Es erfordert immer eigene Hardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware extern"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien nutzt ein externes Rechenzentrum?', 5, '[{"text": "Cloud-Computing", "correct": true, "because": "Virtuelle Ressourcen"}, {"text": "Virtualisierung", "correct": true, "because": "Effiziente Nutzung"}, {"text": "Papierfax", "correct": false, "because": "Analog"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem externen Rechenzentrum unwichtig?', 3, '[{"text": "SLA", "correct": false, "because": "Service Level Agreement"}, {"text": "Datensicherheit", "correct": false, "because": "Kritisch"}, {"text": "Schriftart", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein externes Rechenzentrum lokal betrieben werden?', 3, '[{"text": "Nein", "correct": true, "because": "Extern ausgelagert"}, {"text": "Ja", "correct": false, "because": "Drittanbieter"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein externes Rechenzentrum Kostenvorteile bietet?', 2, '[{"text": "Ja", "correct": true, "because": "Kein Eigenbau"}, {"text": "Nein", "correct": false, "because": "Oft günstiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist für ein externes Rechenzentrum zentral?', 4, '[{"text": "Drittanbieter-Management", "correct": true, "because": "Extern betrieben"}, {"text": "Eigenes Servergebäude", "correct": false, "because": "Nicht extern"}, {"text": "Papierdokumente", "correct": false, "because": "Irrelevant"}]');

