-- questions.sql (Nachhaltige IT-Lösungen, z. B. Energieeffizienz, Ressourcenschonung, umweltfreundliche Technologien)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Server mit hoher Leistung immer weniger effizient ist?', 2, '[{"text": "Nein", "correct": true, "because": "Effizienz hängt von Design ab"}, {"text": "Ja", "correct": false, "because": "Moderne CPUs können effizient sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme reduziert den Stromverbrauch eines Rechenzentrums am besten?', 3, '[{"text": "Virtualisierung", "correct": true, "because": "Konsolidiert Serverlast"}, {"text": "Größere Festplatten", "correct": false, "because": "Kein direkter Einfluss"}, {"text": "Höhere Taktfrequenz", "correct": false, "because": "Erhöht Verbrauch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren fördern eine nachhaltige IT-Umgebung?', 5, '[{"text": "Energieeffiziente Hardware", "correct": true, "because": "Senkt Stromverbrauch"}, {"text": "Wärmerückgewinnung", "correct": true, "because": "Nutzt Abwärme sinnvoll"}, {"text": "Höhere Serveranzahl", "correct": false, "because": "Erhöht Verbrauch"}, {"text": "Farbiges Gehäuse", "correct": false, "because": "Kein Umweltfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Cloud-Computing spart immer Energie. b) SSDs sind effizienter als HDDs.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Cloud hängt von Nutzung ab"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist kontextabhängig"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein nachhaltiges IT-System plane?', 4, '[{"text": "Energieverbrauch", "correct": false, "because": "Kern der Nachhaltigkeit"}, {"text": "Lebenszyklus von Geräten", "correct": false, "because": "Wichtig für Recycling"}, {"text": "Bildschirmdesign", "correct": true, "because": "Kein Umweltfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass alte Hardware immer ineffizient ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Effizienz hängt von Nutzung ab"}, {"text": "Ja", "correct": false, "because": "Optimierte Nutzung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie wähle ich, um den Stromverbrauch von PCs zu senken?', 3, '[{"text": "Energiesparmodi", "correct": true, "because": "Reduzieren Leerlaufverbrauch"}, {"text": "Größere Netzteile", "correct": false, "because": "Können Verbrauch erhöhen"}, {"text": "Schnellere CPUs", "correct": false, "because": "Meist höherer Verbrauch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte machen eine nachhaltige Serverumgebung aus?', 5, '[{"text": "Hohe Virtualisierungsrate", "correct": true, "because": "Optimiert Ressourcennutzung"}, {"text": "Kühlung mit Außenluft", "correct": true, "because": "Senkt Energiebedarf"}, {"text": "Maximale CPU-Last", "correct": false, "because": "Erhöht Verbrauch"}, {"text": "Bunte Beleuchtung", "correct": false, "because": "Kein Nachhaltigkeitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) LED-Monitore weniger Strom verbrauchen und b) größere Monitore immer nachhaltiger sind. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Größere Monitore verbrauchen oft mehr"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine umweltfreundliche IT-Lösung?', 4, '[{"text": "Energieeffiziente Netzteile", "correct": false, "because": "Senken Verbrauch"}, {"text": "Recyclingkonzepte", "correct": false, "because": "Fördern Wiederverwertung"}, {"text": "Hochglanzgehäuse", "correct": true, "because": "Kein Umweltvorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Spart Thin-Client-Computing immer Energie?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Einsatzszenario"}, {"text": "Ja", "correct": false, "because": "Nicht universell effizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen fördern die Nachhaltigkeit von IT-Systemen?', 4, '[{"text": "Serverkonsolidierung", "correct": true, "because": "Reduziert Hardwarebedarf"}, {"text": "Energieüberwachung", "correct": true, "because": "Optimiert Verbrauch"}, {"text": "Schnellere Netzwerke", "correct": false, "because": "Kein primärer Umweltfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass nachhaltige IT immer teurer ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Langfristig oft kostensparend"}, {"text": "Ja", "correct": false, "because": "Effizienz senkt Betriebskosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer energieeffizienten Netzwerkkonfiguration?', 3, '[{"text": "Reduzierter Stromverbrauch", "correct": true, "because": "Senkt Betriebskosten"}, {"text": "Höhere Bandbreite", "correct": false, "because": "Nicht primäres Ziel"}, {"text": "Schnellere Installation", "correct": false, "because": "Kein Umweltfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Energiesparende Prozessoren senken die Leistung. b) Virtualisierung spart Ressourcen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Moderne CPUs sind leistungsstark"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein nachhaltiges Rechenzentrum?', 5, '[{"text": "Niedrigerer Stromverbrauch", "correct": true, "because": "Senkt Kosten und Emissionen"}, {"text": "Längere Gerätelebensdauer", "correct": true, "because": "Optimiert Nutzung"}, {"text": "Höhere Latenz", "correct": false, "because": "Kein Vorteil"}, {"text": "Größere Baufläche", "correct": false, "because": "Erhöht Ressourcenbedarf"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Auswahl nachhaltiger Hardware unwichtig?', 3, '[{"text": "Energieeffizienzklasse", "correct": false, "because": "Zeigt Verbrauch"}, {"text": "Recyclingfähigkeit", "correct": false, "because": "Fördert Wiederverwertung"}, {"text": "Markenlogo", "correct": true, "because": "Kein Umweltfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht Cloud-Computing immer die Nachhaltigkeit?', 3, '[{"text": "Nein", "correct": true, "because": "Abhängig von Anbieter und Nutzung"}, {"text": "Ja", "correct": false, "because": "Nicht automatisch effizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Recycling von IT-Geräten gesetzlich vorgeschrieben ist?', 2, '[{"text": "Ja", "correct": true, "because": "Reguliert durch WEEE-Richtlinie"}, {"text": "Nein", "correct": false, "because": "Vorgaben in vielen Ländern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strategie wähle ich, um den Papierverbrauch in der IT zu reduzieren?', 4, '[{"text": "Digitalisierung von Prozessen", "correct": true, "because": "Vermeidet Ausdrucke"}, {"text": "Schnellere Drucker", "correct": false, "because": "Erhöht Verbrauch"}, {"text": "Größere Monitore", "correct": false, "because": "Kein direkter Einfluss"}]');

