-- questions.sql (Betriebswirtschaftliche Klassifikation von Gütern, z. B. Hardware, Software, Dienstleistungen in IT)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Softwarelizenz zu den Sachgütern zählt?', 2, '[{"text": "Nein", "correct": true, "because": "Immaterielles Gut"}, {"text": "Ja", "correct": false, "because": "Nicht physisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gut beschreibt am besten eine Wartung durch einen IT-Dienstleister?', 3, '[{"text": "Dienstleistung", "correct": true, "because": "Arbeitsleistung ohne physisches Produkt"}, {"text": "Sachgut", "correct": false, "because": "Nicht materiell"}, {"text": "Investitionsgut", "correct": false, "because": "Keine langfristige Anschaffung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Güter sind für ein IT-Projekt typisch?', 5, '[{"text": "Hardware", "correct": true, "because": "Physische Komponenten wie Server"}, {"text": "Software", "correct": true, "because": "Immaterielle Programme"}, {"text": "Büromöbel", "correct": false, "because": "Nicht projektspezifisch"}, {"text": "Kaffee", "correct": false, "because": "Kein IT-Gut"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Server ist ein Investitionsgut. b) Ein USB-Stick ist ein Verbrauchsgut.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "USB-Sticks sind langlebig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein IT-System beschaffe?', 4, '[{"text": "Lizenzkosten", "correct": false, "because": "Teil der Softwaregüter"}, {"text": "Wartungsverträge", "correct": false, "because": "Dienstleistungsgüter"}, {"text": "Bürofarbe", "correct": true, "because": "Kein Gut"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Cloud-Dienste Sachgüter sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Cloud ist eine Dienstleistung"}, {"text": "Ja", "correct": false, "because": "Nicht physisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gut beschreibt eine Festplatte am besten?', 3, '[{"text": "Investitionsgut", "correct": true, "because": "Langfristig genutzt"}, {"text": "Verbrauchsgut", "correct": false, "because": "Nicht schnell verbraucht"}, {"text": "Dienstleistung", "correct": false, "because": "Physisches Produkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Güter fallen bei einer Netzwerkinstallation an?', 5, '[{"text": "Kabel", "correct": true, "because": "Physisches Sachgut"}, {"text": "Konfigurationsdienst", "correct": true, "because": "Arbeitsleistung"}, {"text": "Mitarbeiterverpflegung", "correct": false, "because": "Kein Installationsgut"}, {"text": "Büroflächen", "correct": false, "because": "Nicht direkt relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) Druckerpatronen Verbrauchsgüter sind und b) ein Monitor ein Dienstleistungsgut ist. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Monitor ist Sachgut"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Einrichtung eines Servers?', 4, '[{"text": "Betriebssystem", "correct": false, "because": "Immaterielles Gut"}, {"text": "Hardware", "correct": false, "because": "Physisches Sachgut"}, {"text": "Wandfarbe", "correct": true, "because": "Kein IT-Gut"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein IT-Training ein Sachgut?', 2, '[{"text": "Nein", "correct": true, "because": "Es ist eine Dienstleistung"}, {"text": "Ja", "correct": false, "because": "Nicht physisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Wahl von Gütern in einem IT-Projekt?', 4, '[{"text": "Lebensdauer", "correct": true, "because": "Unterscheidet Investitionsgüter"}, {"text": "Kosten", "correct": true, "because": "Bestimmen Budget"}, {"text": "Bürodesign", "correct": false, "because": "Kein direkter Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass alle IT-Güter physisch sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Software und Dienstleistungen immateriell"}, {"text": "Ja", "correct": false, "because": "Viele Güter nicht physisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich, wenn ich Investitionsgüter für ein Rechenzentrum wähle?', 3, '[{"text": "Langfristige Nutzung", "correct": true, "because": "Hohe Lebensdauer zählt"}, {"text": "Schneller Verbrauch", "correct": false, "because": "Nicht für Investitionsgüter"}, {"text": "Einmalige Nutzung", "correct": false, "because": "Gegenteil von Investition"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Router ist ein Investitionsgut. b) Ein Backup-Service ist ein Sachgut.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Backup ist Dienstleistung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Nutzung von Dienstleistungsgütern in der IT?', 5, '[{"text": "Flexibilität", "correct": true, "because": "Anpassung an Bedarf"}, {"text": "Kein Eigenbesitz", "correct": true, "because": "Senkt Investitionskosten"}, {"text": "Physische Lagerung", "correct": false, "because": "Nicht relevant"}, {"text": "Hohe Verbrauchskosten", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Beschaffung von IT-Gütern unwichtig?', 3, '[{"text": "Nutzungsdauer", "correct": false, "because": "Beeinflusst Kosten"}, {"text": "Wartungsaufwand", "correct": false, "because": "Wichtig für Betrieb"}, {"text": "Verpackungsdesign", "correct": true, "because": "Kein funktionaler Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Zählt eine Datenbanksoftware zu den Sachgütern?', 2, '[{"text": "Nein", "correct": true, "because": "Immaterielles Gut"}, {"text": "Ja", "correct": false, "because": "Nicht physisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Verbrauchsgüter langfristig genutzt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Schnell verbraucht"}, {"text": "Ja", "correct": false, "because": "Für Investitionsgüter typisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gut wähle ich für kurzfristige Nutzung in einem Projekt?', 3, '[{"text": "Verbrauchsgut", "correct": true, "because": "Schnell aufgebraucht"}, {"text": "Investitionsgut", "correct": false, "because": "Langfristig genutzt"}, {"text": "Dienstleistung", "correct": false, "because": "Arbeitsleistung"}]');


