-- Sequenzdiagramm.sql (Essenziell für Abläufe und Interaktionen, z. B. Nachrichtenfluss zwischen Objekten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Sequenzdiagramm nur für komplexe Systeme sinnvoll?', 2, '[{"text": "Nein", "correct": true, "because": "Auch einfache Abläufe klärbar"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Sequenzdiagramm?', 3, '[{"text": "Interaktionen darstellen", "correct": true, "because": "Zeigt Nachrichtenfluss"}, {"text": "Hardwarezuordnung", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Datenkompression", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem Sequenzdiagramm?', 5, '[{"text": "Objekte", "correct": true, "because": "Akteure der Interaktion"}, {"text": "Nachrichten", "correct": true, "because": "Zeigen Kommunikation"}, {"text": "Farbanimation", "correct": false, "because": "Irrelevant"}, {"text": "Hardwareknoten", "correct": false, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Sequenzdiagramme zeigen Zeitabläufe. b) Sie ersetzen Use-Cases.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Use-Cases sind Anforderungen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Sequenzdiagramm?', 4, '[{"text": "Nachrichtenfluss", "correct": false, "because": "Kern des Diagramms"}, {"text": "Lebenslinien", "correct": false, "because": "Zeigen Objektaktivität"}, {"text": "UI-Design", "correct": true, "because": "Kein Ablaufaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Sequenzdiagramm auch Hardware zeigt?', 2, '[{"text": "Nein", "correct": true, "because": "Fokus auf Software-Interaktion"}, {"text": "Ja", "correct": false, "because": "Hardware in anderen Diagrammen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beziehung wähle ich für einen Methodenaufruf?', 3, '[{"text": "Synchrone Nachricht", "correct": true, "because": "Wartet auf Antwort"}, {"text": "Assoziation", "correct": false, "because": "Use-Case-Thema"}, {"text": "Abhängigkeit", "correct": false, "because": "Paketdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten verbessern ein Sequenzdiagramm?', 5, '[{"text": "Lebenslinien", "correct": true, "because": "Zeigen Objektzeit"}, {"text": "Rückrufe", "correct": true, "because": "Antworten darstellen"}, {"text": "Datenfluss", "correct": false, "because": "Datenflussdiagramm"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Sequenzdiagramme zeigen Abläufe. b) Sie sind für Hardware wichtig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hardware nicht im Fokus"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Sequenzdiagramm?', 4, '[{"text": "Objekte", "correct": false, "because": "Interaktionspartner"}, {"text": "Nachrichten", "correct": false, "because": "Zeigen Kommunikation"}, {"text": "Hardwareknoten", "correct": true, "because": "Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Sequenzdiagramme statisch?', 2, '[{"text": "Nein", "correct": true, "because": "Zeigen dynamische Abläufe"}, {"text": "Ja", "correct": false, "because": "Nicht statisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachrichtenarten nutze ich im Sequenzdiagramm?', 4, '[{"text": "Synchrone", "correct": true, "because": "Wartet auf Antwort"}, {"text": "Asynchrone", "correct": true, "because": "Ohne Wartezeit"}, {"text": "Aggregation", "correct": false, "because": "Klassendiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Sequenzdiagramme nur für Entwickler sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Stakeholder nützlich"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Sequenzdiagramm?', 3, '[{"text": "Zeitliche Klarheit", "correct": true, "because": "Ablauf verständlich machen"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Genauigkeit zählt"}, {"text": "Visuelle Effekte", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Sequenzdiagramme zeigen Objektinteraktionen. b) Sie sind für statische Struktur.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Statisch ist Klassendiagramm"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Sequenzdiagramm?', 5, '[{"text": "Ablaufverständnis", "correct": true, "because": "Zeigt Interaktionen klar"}, {"text": "Kommunikationsübersicht", "correct": true, "because": "Nachrichtenfluss sichtbar"}, {"text": "Hardwarezuordnung", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Datenkompression", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist im Sequenzdiagramm unwichtig?', 3, '[{"text": "Zeitachse", "correct": false, "because": "Kern der Darstellung"}, {"text": "Objektinteraktion", "correct": false, "because": "Hauptzweck"}, {"text": "3D-Grafiken", "correct": true, "because": "Kein Ablauffaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Sequenzdiagramm auch Hardware zeigen?', 3, '[{"text": "Nein", "correct": true, "because": "Fokus auf Software-Abläufe"}, {"text": "Ja", "correct": false, "because": "Hardware in Verteilungsdiagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Sequenzdiagramme für Tests nützlich sind?', 2, '[{"text": "Ja", "correct": true, "because": "Definieren Testabläufe"}, {"text": "Nein", "correct": false, "because": "Testfälle ableitbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich für einen Methodenaufruf im Sequenzdiagramm?', 4, '[{"text": "Synchrone Nachricht", "correct": true, "because": "Wartet auf Rückgabe"}, {"text": "Hardwareknoten", "correct": false, "because": "Verteilungsdiagramm"}, {"text": "Datenfluss", "correct": false, "because": "Datenflussdiagramm"}]');

