-- Use-Case-Diagramm.sql (Zentral für Anforderungen und Benutzerinteraktionen, z. B. Akteure und Szenarien)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Use-Case-Diagramm nur für Endnutzer relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Entwickler und Systeme als Akteure"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Use-Case-Diagramm?', 3, '[{"text": "Anforderungen visualisieren", "correct": true, "because": "Zeigt Interaktionen klar"}, {"text": "Code implementieren", "correct": false, "because": "Kein Programmierfokus"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem Use-Case-Diagramm?', 5, '[{"text": "Akteure", "correct": true, "because": "Stellen Nutzer oder Systeme dar"}, {"text": "Use-Cases", "correct": true, "because": "Beschreiben Funktionen"}, {"text": "Farbcodierung", "correct": false, "because": "Irrelevant"}, {"text": "Datenfluss", "correct": false, "because": "Anderes Diagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Akteure sind immer menschlich. b) Use-Cases zeigen Funktionen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Akteure können Systeme sein"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Use-Case-Diagramm?', 4, '[{"text": "Akteur-Interaktionen", "correct": false, "because": "Kern des Diagramms"}, {"text": "Szenarien", "correct": false, "because": "Beschreiben Use-Cases"}, {"text": "Grafikdesign", "correct": true, "because": "Fokus auf Funktion, nicht Optik"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Use-Case-Diagramm technische Details zeigt?', 2, '[{"text": "Nein", "correct": true, "because": "Fokus auf Anforderungen"}, {"text": "Ja", "correct": false, "because": "Abstrakt, nicht technisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beziehung nutze ich zwischen Akteuren und Use-Cases?', 3, '[{"text": "Assoziation", "correct": true, "because": "Zeigt Interaktion"}, {"text": "Vererbung", "correct": false, "because": "Für Klassen, nicht Use-Cases"}, {"text": "Aggregation", "correct": false, "because": "Falsche Beziehung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten verbessern ein Use-Case-Diagramm?', 5, '[{"text": "Include", "correct": true, "because": "Wiederverwendung von Use-Cases"}, {"text": "Extend", "correct": true, "because": "Optionale Erweiterungen"}, {"text": "Datenfluss", "correct": false, "because": "Anderes Diagramm"}, {"text": "Farbanimation", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Use-Case-Diagramme sind für Stakeholder wichtig. b) Sie zeigen Abläufe im Detail. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Abläufe in anderen Diagrammen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Use-Case-Diagramm?', 4, '[{"text": "Akteure", "correct": false, "because": "Zeigen Interaktionspartner"}, {"text": "Use-Cases", "correct": false, "because": "Kern der Anforderungen"}, {"text": "Code-Snippets", "correct": true, "because": "Kein technischer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Use-Case-Diagramm nur für Softwareentwicklung?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Prozesse oder Systeme"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beziehungen nutze ich in einem Use-Case-Diagramm?', 4, '[{"text": "Include", "correct": true, "because": "Bindet Use-Cases ein"}, {"text": "Extend", "correct": true, "because": "Erweitert optional"}, {"text": "Sequenz", "correct": false, "because": "Anderes Diagramm"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Use-Case-Diagramme technische Implementierung zeigen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Fokus auf Anforderungen"}, {"text": "Ja", "correct": false, "because": "Abstrakt, nicht technisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Use-Case-Diagramm?', 3, '[{"text": "Klarheit der Anforderungen", "correct": true, "because": "Fördert Verständnis"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Qualität zählt"}, {"text": "Visuelle Effekte", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Use-Cases beschreiben Szenarien. b) Akteure sind nur intern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Akteure auch extern"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Use-Case-Diagramm?', 5, '[{"text": "Klarheit für Stakeholder", "correct": true, "because": "Verständnis fördern"}, {"text": "Anforderungsübersicht", "correct": true, "because": "Zeigt Funktionen"}, {"text": "Datenflussdetails", "correct": false, "because": "Anderes Diagramm"}, {"text": "Technische Spezifikation", "correct": false, "because": "Nicht im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Use-Case-Diagramm unwichtig?', 3, '[{"text": "Interaktionen", "correct": false, "because": "Kern der Darstellung"}, {"text": "Systemgrenze", "correct": false, "because": "Definiert Umfang"}, {"text": "3D-Animation", "correct": true, "because": "Kein funktionaler Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Zeigt ein Use-Case-Diagramm Abläufe?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Anforderungen, keine Schritte"}, {"text": "Ja", "correct": false, "because": "Abläufe in anderen Diagrammen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Use-Case-Diagramm auch für Tests nützlich ist?', 2, '[{"text": "Ja", "correct": true, "because": "Definiert Testfälle"}, {"text": "Nein", "correct": false, "because": "Basis für Testszenarien"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich für ein Use-Case-Diagramm?', 4, '[{"text": "Akteure", "correct": true, "because": "Zeigen Interaktionspartner"}, {"text": "Datenfluss", "correct": false, "because": "Anderes Diagramm"}, {"text": "Code-Beispiele", "correct": false, "because": "Kein technischer Fokus"}]');

