-- Arbeitsrecht Berufsbildung > Soziale gesellschaftliche Themen > Arbeitsschutz > Arbeitsplatzgestaltung
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Muss ein IT-Betrieb bei der Arbeitsplatzgestaltung ergonomische Aspekte berücksichtigen?', 2, '[{"text": "Ja", "correct": true, "because": "Ergonomie ist gemäß ArbSchG und Bildschirmarbeitsverordnung vorgeschrieben"}, {"text": "Nein", "correct": false, "because": "Ergonomie ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine schlechte Arbeitsplatzgestaltung in einem IT-Betrieb gesundheitliche Probleme wie Rückenschmerzen verursachen?', 2, '[{"text": "Ja", "correct": true, "because": "Ungeeignete Möbel oder Haltung schaden der Gesundheit"}, {"text": "Nein", "correct": false, "because": "Gesundheitsrisiken sind bekannt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Beleuchtung ein relevanter Faktor bei der Arbeitsplatzgestaltung in einem IT-Betrieb?', 2, '[{"text": "Ja", "correct": true, "because": "Gute Beleuchtung schützt die Augen gemäß BildschArbV"}, {"text": "Nein", "correct": false, "because": "Beleuchtung ist vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen bei der Arbeitsplatzgestaltung in einem IT-Betrieb Fluchtwege berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Fluchtwege sind Teil der Sicherheitsvorschriften"}, {"text": "Nein", "correct": false, "because": "Sicherheit ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein IT-Betrieb die Arbeitsplatzgestaltung frei gestalten, ohne gesetzliche Vorgaben?', 2, '[{"text": "Nein", "correct": true, "because": "ArbSchG und BildschArbV setzen Vorgaben"}, {"text": "Ja", "correct": false, "because": "Gesetzliche Regeln sind bindend"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz regelt die Arbeitsplatzgestaltung in einem IT-Betrieb?', 2, '[{"text": "Arbeitsschutzgesetz (ArbSchG)", "correct": true, "because": "ArbSchG ist die Grundlage für Arbeitsschutz"}, {"text": "BBiG", "correct": false, "because": "Regelt Ausbildung"}, {"text": "HGB", "correct": false, "because": "Regelt Handel"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Arbeitsplatzgestaltung in einem IT-Betrieb?', 3, '[{"text": "Sicherstellung von Gesundheit und Sicherheit", "correct": true, "because": "ArbSchG § 3 fordert Schutz"}, {"text": "Maximierung der Kosten", "correct": false, "because": "Kosten nicht primär"}, {"text": "Verringerung der Produktivität", "correct": false, "because": "Produktivität soll steigen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Arbeitsplatzgestaltung ist für Fachinformatiker besonders wichtig?', 3, '[{"text": "Ergonomische Bildschirmarbeitsplätze", "correct": true, "because": "Fachinformatiker arbeiten viel am Bildschirm"}, {"text": "Hohe Decken", "correct": false, "because": "Weniger relevant"}, {"text": "Manuelle Werkzeuge", "correct": false, "because": "Nicht primär für IT"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer ist für die Arbeitsplatzgestaltung in einem IT-Betrieb verantwortlich?', 2, '[{"text": "Der Arbeitgeber", "correct": true, "because": "ArbSchG § 3 legt Verantwortung beim Arbeitgeber"}, {"text": "Die Auszubildenden", "correct": false, "because": "Nicht deren Pflicht"}, {"text": "Die IHK", "correct": false, "because": "IHK überwacht, gestaltet nicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor der Arbeitsplatzgestaltung kann die Gesundheit eines Fachinformatikers beeinträchtigen?', 3, '[{"text": "Schlechte Beleuchtung", "correct": true, "because": "Belastet Augen bei Bildschirmarbeit"}, {"text": "Hohe Lautstärke", "correct": false, "because": "Weniger relevant für IT"}, {"text": "Gute Belüftung", "correct": false, "because": "Fördert Gesundheit"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte müssen bei der Arbeitsplatzgestaltung in einem IT-Betrieb berücksichtigt werden?', 4, '[{"text": "Ergonomische Möbel", "correct": true, "because": "Schützt vor Haltungsschäden"}, {"text": "Ausreichende Beleuchtung", "correct": true, "because": "Schützt Augen"}, {"text": "Hohe Temperaturen", "correct": false, "because": "Ungünstig für Gesundheit"}, {"text": "Fluchtwege", "correct": true, "because": "Sicherheitsvorschrift"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gute Arbeitsplatzgestaltung einem IT-Betrieb?', 3, '[{"text": "Weniger Krankheitsfälle", "correct": true, "because": "Gesundheit wird gefördert"}, {"text": "Höhere Produktivität", "correct": true, "because": "Angenehme Umgebung steigert Leistung"}, {"text": "Höhere Kosten", "correct": false, "because": "Kosten können sinken"}, {"text": "Bessere Arbeitsbedingungen", "correct": true, "because": "Ergonomie verbessert Umfeld"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken entstehen durch eine schlechte Arbeitsplatzgestaltung in einem IT-Betrieb?', 4, '[{"text": "Rückenschmerzen", "correct": true, "because": "Ungeeignete Möbel"}, {"text": "Augenbelastung", "correct": true, "because": "Schlechte Beleuchtung"}, {"text": "Geringere Effizienz", "correct": true, "because": "Unwohlsein mindert Leistung"}, {"text": "Hohe Luftfeuchtigkeit", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche gesetzlichen Grundlagen regeln die Arbeitsplatzgestaltung in einem IT-Betrieb?', 3, '[{"text": "Arbeitsschutzgesetz (ArbSchG)", "correct": true, "because": "Grundlage für Sicherheit"}, {"text": "Bildschirmarbeitsverordnung (BildschArbV)", "correct": true, "because": "Spezifisch für Bildschirmarbeit"}, {"text": "BBiG", "correct": false, "because": "Regelt Ausbildung"}, {"text": "Arbeitsstättenverordnung (ArbStättV)", "correct": true, "because": "Regelt Arbeitsstätten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was unterscheidet die Arbeitsplatzgestaltung für Fachinformatiker von anderen Berufen?', 3, '[{"text": "Fokus auf Bildschirmarbeit", "correct": true, "because": "IT spezifisch"}, {"text": "Ergonomische Anforderungen", "correct": true, "because": "Haltungsschäden vermeiden"}, {"text": "Hoher Lärmpegel", "correct": false, "because": "Weniger relevant"}, {"text": "Spezifische Beleuchtung", "correct": true, "because": "Augenschutz bei Bildschirmen"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Arbeitsplatzgestaltung in einem IT-Betrieb muss ergonomisch sein. b) Beleuchtung ist für Fachinformatiker irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ergonomie ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine gute Arbeitsplatzgestaltung fördert die Produktivität eines IT-Betriebs. b) Fluchtwege sind Teil der Sicherheitsvorschriften.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Produktivität und Sicherheit"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Schlechte Arbeitsplatzgestaltung kann Rückenschmerzen verursachen. b) Der Arbeitgeber ist nicht für die Gestaltung verantwortlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Rückenschmerzen ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die BildschArbV regelt die Arbeitsplatzgestaltung für Fachinformatiker. b) Eine gute Gestaltung erhöht Krankheitsfälle.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "BildschArbV ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Arbeitsplatzgestaltung muss Fluchtwege berücksichtigen. b) Ergonomie ist für IT-Arbeitsplätze unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Fluchtwege ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

