-- Arbeitsrecht Berufsbildung > Soziale gesellschaftliche Themen > Arbeitsschutz > Sicherheitsvorschriften
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen Sicherheitsvorschriften bei einem IT-Betrieb den Schutz vor Bildschirmarbeit berücksichtigen?', 2, '[{"text": "Ja", "correct": true, "because": "Bildschirmarbeit erfordert ergonomische Vorschriften"}, {"text": "Nein", "correct": false, "because": "Schutz ist gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Sicherheitsvorschriften für Fachinformatiker im Umgang mit elektrischen Geräten relevant?', 2, '[{"text": "Ja", "correct": true, "because": "Elektrische Sicherheit ist Pflicht"}, {"text": "Nein", "correct": false, "because": "Elektrische Geräte sind Teil der Arbeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Sicherheitsvorschriften einem IT-Betrieb helfen, Arbeitsunfälle zu vermeiden?', 2, '[{"text": "Ja", "correct": true, "because": "Vorschriften minimieren Risiken"}, {"text": "Nein", "correct": false, "because": "Unfallprävention ist ein Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Sicherheitsvorschriften bei einem IT-Betrieb regelmäßig überprüft werden?', 2, '[{"text": "Ja", "correct": true, "because": "Regelmäßige Überprüfung ist gesetzlich vorgeschrieben"}, {"text": "Nein", "correct": false, "because": "Überprüfung ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Sicherheitsvorschriften für Homeoffice-Arbeitsplätze eines Fachinformatikers irrelevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Homeoffice unterliegt Arbeitsschutz"}, {"text": "Ja", "correct": false, "because": "Vorschriften gelten auch dort"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Sicherheitsvorschrift ist für Fachinformatiker an Bildschirmarbeitsplätzen besonders wichtig?', 2, '[{"text": "Ergonomische Gestaltung", "correct": true, "because": "Schützt vor Haltungsschäden"}, {"text": "Feuerlöscherpflicht", "correct": false, "because": "Weniger spezifisch"}, {"text": "Lärmschutz", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz regelt die Sicherheitsvorschriften für Fachinformatiker im Arbeitsschutz?', 3, '[{"text": "Arbeitsschutzgesetz (ArbSchG)", "correct": true, "because": "ArbSchG ist die Grundlage"}, {"text": "BBiG", "correct": false, "because": "Regelt Ausbildung"}, {"text": "GmbHG", "correct": false, "because": "Regelt GmbH"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Sicherheitsvorschriften schützt Fachinformatiker bei der Arbeit mit Servern?', 3, '[{"text": "Elektrische Sicherheit", "correct": true, "because": "Verhindert Stromunfälle"}, {"text": "Brandschutz", "correct": false, "because": "Wichtig, aber weniger spezifisch"}, {"text": "Lichtverhältnisse", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Ziel der Sicherheitsvorschriften für einen IT-Betrieb?', 2, '[{"text": "Schutz der Gesundheit der Mitarbeiter", "correct": true, "because": "Primäres Ziel des Arbeitsschutzes"}, {"text": "Erhöhung der Kosten", "correct": false, "because": "Kein Ziel"}, {"text": "Reduktion der Produktivität", "correct": false, "because": "Nicht beabsichtigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Nachteil kann durch Sicherheitsvorschriften für einen IT-Betrieb entstehen?', 3, '[{"text": "Erhöhter Verwaltungsaufwand", "correct": true, "because": "Umsetzung und Kontrolle kosten Zeit"}, {"text": "Geringere Qualität", "correct": false, "because": "Qualität nicht betroffen"}, {"text": "Weniger Innovation", "correct": false, "because": "Innovation unabhängig"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Sicherheitsvorschriften sind für Fachinformatiker in einem IT-Betrieb relevant?', 4, '[{"text": "Ergonomische Arbeitsplätze", "correct": true, "because": "Schützt vor Haltungsschäden"}, {"text": "Elektrische Sicherheit", "correct": true, "because": "Verhindert Stromunfälle"}, {"text": "Keine Pausenregelung", "correct": false, "because": "Pausen sind vorgeschrieben"}, {"text": "Datensicherheit", "correct": true, "because": "Schützt vor Datenverlust"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Sicherheitsvorschriften einem IT-Betrieb?', 3, '[{"text": "Reduzierung von Arbeitsunfällen", "correct": true, "because": "Vorschriften minimieren Risiken"}, {"text": "Schutz der Mitarbeitergesundheit", "correct": true, "because": "Primäres Ziel"}, {"text": "Höhere Kosten", "correct": false, "because": "Kein Vorteil"}, {"text": "Erhöhte Produktivität", "correct": true, "because": "Gesunde Mitarbeiter sind produktiver"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile können Sicherheitsvorschriften für einen IT-Betrieb mit sich bringen?', 4, '[{"text": "Erhöhter Verwaltungsaufwand", "correct": true, "because": "Kontrolle und Dokumentation nötig"}, {"text": "Kosten für Umsetzung", "correct": true, "because": "Investitionen erforderlich"}, {"text": "Geringere Arbeitsbelastung", "correct": false, "because": "Belastung kann gleich bleiben"}, {"text": "Einschränkung der Flexibilität", "correct": true, "because": "Vorgaben können Flexibilität reduzieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bereiche decken Sicherheitsvorschriften für Fachinformatiker ab?', 3, '[{"text": "Bildschirmarbeitsplätze", "correct": true, "because": "Ergonomie ist vorgeschrieben"}, {"text": "Elektrische Geräte", "correct": true, "because": "Stromschutz ist Pflicht"}, {"text": "Kundenservice", "correct": false, "because": "Kein direkter Sicherheitsbereich"}, {"text": "Brandschutz", "correct": true, "because": "Allgemeine Sicherheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Was unterscheidet Sicherheitsvorschriften für einen IT-Betrieb von anderen Branchen?', 3, '[{"text": "Fokus auf Bildschirmarbeit", "correct": true, "because": "IT-spezifisch"}, {"text": "Elektrische Sicherheit bei Servern", "correct": true, "because": "IT-Geräte betont"}, {"text": "Keine ergonomischen Vorgaben", "correct": false, "because": "Ergonomie ist relevant"}, {"text": "Datensicherheit als Zusatz", "correct": true, "because": "IT-spezifisches Risiko"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Sicherheitsvorschriften schützen die Gesundheit von Fachinformatikern. b) Sicherheitsvorschriften sind für Homeoffice irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Gesundheit ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Sicherheitsvorschriften reduzieren Arbeitsunfälle in einem IT-Betrieb. b) Sicherheitsvorschriften erhöhen den Verwaltungsaufwand.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Unfälle sinken, Aufwand steigt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Sicherheitsvorschriften betreffen ergonomische Arbeitsplätze für Fachinformatiker. b) Sicherheitsvorschriften sind nur für physische Gefahren relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ergonomie ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Sicherheitsvorschriften erhöhen die Produktivität eines IT-Betriebs. b) Sicherheitsvorschriften haben keine Kosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Produktivität ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Sicherheitsvorschriften sind im ArbSchG geregelt. b) Sicherheitsvorschriften betreffen nur große IT-Betriebe.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "ArbSchG ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

