-- Verschlüsselungsverfahren (AES).sql (z. B. AES für symmetrische Verschlüsselung, Datensicherheit)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist AES immer symmetrisch?', 2, '[{"text": "Ja", "correct": true, "because": "Ein Schlüssel für Ver-/Entschlüsselung"}, {"text": "Nein", "correct": false, "because": "Keine asymmetrische Variante"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit AES in meinem Projekt?', 3, '[{"text": "Datensicherheit", "correct": true, "because": "Schützt vor unbefugtem Zugriff"}, {"text": "Datenkompression", "correct": false, "because": "Keine Kompressionsfunktion"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Sicherheit im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen AES sicher?', 5, '[{"text": "Schlüsselgröße", "correct": true, "because": "128, 192 oder 256 Bit"}, {"text": "Rundenstruktur", "correct": true, "because": "Mehrere Verschlüsselungsrunden"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Farbkodierung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) AES-256 ist sicherer als AES-128. b) Es ist für Passwörter ideal.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Passwörter brauchen Hashing"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Nutzung von AES?', 4, '[{"text": "Schlüsselmanagement", "correct": false, "because": "Kern der Sicherheit"}, {"text": "Blockgröße", "correct": false, "because": "128 Bit entscheidend"}, {"text": "Anzeigefarbe", "correct": true, "because": "Kein Sicherheitsaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob AES auch Integrität schützt?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Vertraulichkeit, nicht Integrität"}, {"text": "Ja", "correct": false, "because": "Hashing oder MAC nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Modus wähle ich für AES bei großen Dateien?', 3, '[{"text": "CBC", "correct": true, "because": "Sicher mit Initialisierungsvektor"}, {"text": "ECB", "correct": false, "because": "Unsicher bei Mustern"}, {"text": "XOR", "correct": false, "because": "Kein AES-Modus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen AES effektiv?', 5, '[{"text": "Schlüsselstärke", "correct": true, "because": "Schwieriger zu knacken"}, {"text": "Substitution-Permutation", "correct": true, "because": "Verwirrt und streut Daten"}, {"text": "Hohe Taktfrequenz", "correct": false, "because": "Hardware-aspekt"}, {"text": "Grafische Ausgabe", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) AES ist schneller als RSA. b) Es ist für Schlüsselaustausch ideal. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schlüsselaustausch ist asymmetrisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für AES?', 4, '[{"text": "Initialisierungsvektor", "correct": false, "because": "Wichtig für sichere Modi"}, {"text": "Schlüssel", "correct": false, "because": "Grundlage der Verschlüsselung"}, {"text": "Touchscreen-Optimierung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist AES-128 unsicher?', 2, '[{"text": "Nein", "correct": true, "because": "Noch sicher, aber 256 stärker"}, {"text": "Ja", "correct": false, "because": "Weit verbreitet akzeptiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Modi sind für AES sicher?', 4, '[{"text": "CBC", "correct": true, "because": "Initialisierungsvektor erhöht Sicherheit"}, {"text": "GCM", "correct": true, "because": "Integrität und Authentizität"}, {"text": "ECB", "correct": false, "because": "Muster sichtbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass AES für kleine Daten übertrieben ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Sicherheit unabhängig von Größe"}, {"text": "Ja", "correct": false, "because": "Effizient auch bei kleinen Daten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei AES für Datensicherheit?', 3, '[{"text": "Schlüsselgröße", "correct": true, "because": "Bestimmt Brute-Force-Schwierigkeit"}, {"text": "Schnelle Berechnung", "correct": false, "because": "Sicherheit vor Geschwindigkeit"}, {"text": "Einfache Syntax", "correct": false, "because": "Implementierungsdetail"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) AES nutzt einen Schlüssel. b) Es ist für Netzwerke ungeeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Netzwerke nutzen AES oft"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen profitieren von AES?', 5, '[{"text": "Dateiverschlüsselung", "correct": true, "because": "Sichert lokale Daten"}, {"text": "VPNs", "correct": true, "because": "Sichert Übertragung"}, {"text": "Datenkompression", "correct": false, "because": "Keine Kompressionsfunktion"}, {"text": "Netzwerkoptimierung", "correct": false, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei AES unwichtig?', 3, '[{"text": "Blockchiffrierung", "correct": false, "because": "Kern der Methode"}, {"text": "Schlüsselrotation", "correct": false, "because": "Erhöht Sicherheit"}, {"text": "Blinkende Anzeige", "correct": true, "because": "Kein Sicherheitsaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann AES ohne IV sicher sein?', 3, '[{"text": "Nein", "correct": true, "because": "IV verhindert Muster in Modi wie CBC"}, {"text": "Ja", "correct": false, "because": "Sicherheit leidet ohne IV"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob AES für Passwörter allein geeignet ist?', 2, '[{"text": "Nein", "correct": true, "because": "Hashing mit Salt besser"}, {"text": "Ja", "correct": false, "because": "AES ist für Daten, nicht Passwörter"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen AES-Modus wähle ich für Authentizität?', 4, '[{"text": "GCM", "correct": true, "because": "Kombiniert Verschlüsselung und Integrität"}, {"text": "ECB", "correct": false, "because": "Keine Authentizität"}, {"text": "CTR", "correct": false, "because": "Nur Verschlüsselung"}]');

