-- questions.sql (Auswirkungen auf IT, z. B. internationale Zusammenarbeit, Datenschutz, globale Netzwerke)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob internationale Teams immer dieselben Tools nutzen müssen?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Projekt und Region"}, {"text": "Ja", "correct": false, "because": "Flexibilität ist üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend, wenn ich Daten über Ländergrenzen hinweg übertrage?', 3, '[{"text": "Datenschutzvorschriften", "correct": true, "because": "Regeln wie DSGVO beachten"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nur technischer Aspekt"}, {"text": "Lokale Software", "correct": false, "because": "Nicht primär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren sind bei der Zusammenarbeit in globalen IT-Projekten wichtig?', 5, '[{"text": "Zeitzonenmanagement", "correct": true, "because": "Koordiniert Meetings"}, {"text": "Kulturelle Sensibilität", "correct": true, "because": "Fördert Teamarbeit"}, {"text": "Einheitliche Hardware", "correct": false, "because": "Nicht zwingend"}, {"text": "Gleiche Büroausstattung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) DSGVO gilt nur in Europa. b) Internationale Projekte brauchen immer Übersetzer.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Übersetzer nicht immer nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich eine Cloud-Lösung für ein globales Team wähle?', 4, '[{"text": "Datenspeicherort", "correct": false, "because": "Relevant für Compliance"}, {"text": "Zugriffskontrollen", "correct": false, "because": "Schützen Daten"}, {"text": "Farbe der Benutzeroberfläche", "correct": true, "because": "Kein funktionaler Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass alle Länder dieselben Datenschutzregeln haben. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Regeln variieren stark"}, {"text": "Ja", "correct": false, "because": "Länder haben eigene Gesetze"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wähle ich für sicheren Datenaustausch zwischen Ländern?', 3, '[{"text": "TLS", "correct": true, "because": "Sichert Übertragungen"}, {"text": "FTP", "correct": false, "because": "Unsicher ohne Verschlüsselung"}, {"text": "HTTP", "correct": false, "because": "Keine Verschlüsselung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind bei der Verwaltung eines globalen Netzwerks relevant?', 5, '[{"text": "Latenzoptimierung", "correct": true, "because": "Verbessert Zugriffszeiten"}, {"text": "Regionale Compliance", "correct": true, "because": "Erfüllt gesetzliche Vorgaben"}, {"text": "Einheitliche Gerätemarken", "correct": false, "because": "Nicht notwendig"}, {"text": "Identische Bürozeiten", "correct": false, "because": "Unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) Cloud-Dienste immer global verfügbar sind und b) lokale Server sicherer sind. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Sicherheit hängt von Konfiguration ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein internationales IT-Projekt?', 4, '[{"text": "Kommunikationsplattform", "correct": false, "because": "Koordiniert Teams"}, {"text": "Verschlüsselte Verbindungen", "correct": false, "because": "Schützen Daten"}, {"text": "Einheitliche Kaffeemaschinen", "correct": true, "because": "Kein Projektfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein VPN für globale Teams immer notwendig?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Sicherheitsanforderungen"}, {"text": "Ja", "correct": false, "because": "Nicht immer erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren fördern die Zusammenarbeit in einem verteilten Team?', 4, '[{"text": "Klar definierte Prozesse", "correct": true, "because": "Vermeiden Missverständnisse"}, {"text": "Gemeinsame Tools", "correct": true, "because": "Erleichtern Koordination"}, {"text": "Gleiche Urlaubszeiten", "correct": false, "because": "Nicht praktikabel"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass internationale Standards die IT-Sicherheit garantieren. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Standards müssen implementiert werden"}, {"text": "Ja", "correct": false, "because": "Keine automatische Sicherheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer globalen Backup-Strategie?', 3, '[{"text": "Datenverfügbarkeit", "correct": true, "because": "Sichert Zugriff weltweit"}, {"text": "Einheitliches Design", "correct": false, "because": "Kein Backup-Ziel"}, {"text": "Schnellere Hardware", "correct": false, "because": "Nicht primär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Zeitzonen erschweren Projekte. b) Alle Länder nutzen dieselbe Cloud.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Cloud-Nutzung variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine globale IT-Infrastruktur?', 5, '[{"text": "Skalierbarkeit", "correct": true, "because": "Passt sich wachsenden Anforderungen an"}, {"text": "Redundanz", "correct": true, "because": "Erhöht Ausfallsicherheit"}, {"text": "Einheitliche Softwareversionen", "correct": false, "because": "Nicht zwingend"}, {"text": "Gleiche Arbeitszeiten", "correct": false, "because": "Unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Wahl eines globalen Kommunikationssystems unwichtig?', 3, '[{"text": "Zuverlässigkeit", "correct": false, "because": "Sichert Verbindung"}, {"text": "Verschlüsselung", "correct": false, "because": "Schützt Daten"}, {"text": "Farbe der Oberfläche", "correct": true, "because": "Kein funktionaler Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht eine globale IT-Strategie immer die Kosten?', 2, '[{"text": "Nein", "correct": true, "because": "Effizienz kann Kosten senken"}, {"text": "Ja", "correct": false, "because": "Abhängig von Umsetzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob internationale Softwarelizenzen immer gleich sind?', 3, '[{"text": "Nein", "correct": true, "because": "Variieren je nach Land"}, {"text": "Ja", "correct": false, "because": "Regionale Unterschiede existieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme wähle ich, um globale Datenflüsse zu sichern?', 4, '[{"text": "Ende-zu-Ende-Verschlüsselung", "correct": true, "because": "Schützt Daten während Übertragung"}, {"text": "Schnelle Server", "correct": false, "because": "Nur Leistungsfaktor"}, {"text": "Einheitliche Passwörter", "correct": false, "because": "Erhöht Risiko"}]');

