-- questions.sql (Datenmodellierung und Abfragen mit vernetzten Daten, z. B. Beziehungen, Knoten, Kanten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Beziehungen in vernetzten Daten immer bidirektional sind?', 2, '[{"text": "Nein", "correct": true, "because": "Können gerichtet oder ungerichtet sein"}, {"text": "Ja", "correct": false, "because": "Richtung ist flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend, um Verbindungen zwischen Datenpunkten zu modellieren?', 3, '[{"text": "Kanten", "correct": true, "because": "Repräsentieren Beziehungen"}, {"text": "Tabellen", "correct": false, "because": "Typisch für relationale Systeme"}, {"text": "Spalten", "correct": false, "because": "Nicht für Verbindungen relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Szenarien profitieren besonders von vernetzten Datenstrukturen?', 5, '[{"text": "Soziale Netzwerke", "correct": true, "because": "Beziehungen zwischen Nutzern"}, {"text": "Empfehlungssysteme", "correct": true, "because": "Verknüpfen Präferenzen"}, {"text": "Einfache Tabellenkalkulation", "correct": false, "because": "Keine komplexen Verbindungen"}, {"text": "Statische Berichte", "correct": false, "because": "Wenig Beziehungslogik"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Knoten speichern Entitäten. b) Kanten definieren immer Hierarchien.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kanten können beliebige Beziehungen darstellen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein System für komplexe Beziehungen entwerfe?', 4, '[{"text": "Kantenattribute", "correct": false, "because": "Beschreiben Beziehungsdetails"}, {"text": "Knotentypen", "correct": false, "because": "Definieren Entitäten"}, {"text": "Farbschema", "correct": true, "because": "Irrelevant für Datenstruktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass vernetzte Daten immer schneller als relationale Tabellen sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Anwendungsfall"}, {"text": "Ja", "correct": false, "because": "Tabellen besser bei einfachen Abfragen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Abfragesprache ist typisch für vernetzte Daten?', 3, '[{"text": "Cypher", "correct": true, "because": "Optimiert für Beziehungen"}, {"text": "SQL", "correct": false, "because": "Für relationale Datenbanken"}, {"text": "Python", "correct": false, "because": "Programmiersprache"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen vernetzte Datenstrukturen flexibel?', 5, '[{"text": "Dynamische Beziehungen", "correct": true, "because": "Ermöglichen Änderungen"}, {"text": "Attributierte Kanten", "correct": true, "because": "Speichern Zusatzinformationen"}, {"text": "Feste Schemata", "correct": false, "because": "Weniger flexibel"}, {"text": "Statische Tabellen", "correct": false, "because": "Nicht beziehungsorientiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) vernetzte Daten schemalos sind und b) sie immer für große Datenmengen geeignet sind. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Skalierung hängt von System ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Beziehungen zwischen Datenpunkten zu analysieren?', 4, '[{"text": "Knotenidentifikatoren", "correct": false, "because": "Markieren Entitäten"}, {"text": "Kantenrichtung", "correct": false, "because": "Definiert Beziehungslogik"}, {"text": "Bildschirmauflösung", "correct": true, "because": "Kein Datenfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind vernetzte Daten immer hierarchisch organisiert?', 2, '[{"text": "Nein", "correct": true, "because": "Können beliebige Strukturen bilden"}, {"text": "Ja", "correct": false, "because": "Flexibel, nicht nur hierarchisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Speicherung von Beziehungen in einem Netzwerk?', 4, '[{"text": "Effiziente Traversierung", "correct": true, "because": "Schnelle Beziehungsabfragen"}, {"text": "Intuitive Modellierung", "correct": true, "because": "Spiegelt reale Verbindungen"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Nicht primär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass vernetzte Daten nur für soziale Netzwerke nützlich sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Logistik, Fraud usw."}, {"text": "Ja", "correct": false, "because": "Vielseitig einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich, wenn ich Daten mit vielen Verknüpfungen speichere?', 3, '[{"text": "Schnelle Beziehungsabfragen", "correct": true, "because": "Optimiert für Verbindungen"}, {"text": "Maximale Speichergröße", "correct": false, "because": "Nicht primär relevant"}, {"text": "Einfache Tabellenstruktur", "correct": false, "because": "Nicht beziehungsorientiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Traversierung ist schneller als Joins. b) Vernetzte Daten brauchen immer mehr Speicher.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Speicherbedarf ist kontextabhängig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik wähle ich, um Pfade zwischen Datenpunkten zu finden?', 4, '[{"text": "Tiefensuche", "correct": true, "because": "Effizient für Beziehungen"}, {"text": "Lineare Suche", "correct": false, "because": "Nicht für Netzwerke geeignet"}, {"text": "Sortieralgorithmus", "correct": false, "because": "Anderer Zweck"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob vernetzte Daten immer strukturierte Daten voraussetzen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch unstrukturierte Daten möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen ein System für vernetzte Daten effektiv?', 5, '[{"text": "Schnelle Traversierung", "correct": true, "because": "Optimiert Beziehungsabfragen"}, {"text": "Flexible Schemata", "correct": true, "because": "Ermöglicht Anpassungen"}, {"text": "Hohe Bildschirmauflösung", "correct": false, "because": "Kein Datenfaktor"}, {"text": "Feste Tabellenstruktur", "correct": false, "because": "Weniger flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind alle vernetzten Systeme automatisch skalierbar?', 3, '[{"text": "Nein", "correct": true, "because": "Abhängig von Implementierung"}, {"text": "Ja", "correct": false, "because": "Skalierung erfordert Optimierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt am besten zu vernetzten Daten?', 4, '[{"text": "Analyse von Lieferketten", "correct": true, "because": "Komplexe Beziehungen"}, {"text": "Einfache Inventarliste", "correct": false, "because": "Lineare Daten"}, {"text": "Statische Dokumente", "correct": false, "because": "Keine Beziehungslogik"}]');

