INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist eine Internetverbindung notwendig, um Cloud-Dienste für die Client-Integration zu nutzen?', 2, '[{"text": "Ja", "correct": true, "because": "Cloud-Dienste sind online-basierte Services"}, {"text": "Nein", "correct": false, "because": "Internet ist zwingend erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Cloud-Dienste die lokale Speicherung auf einem Client ersetzen?', 2, '[{"text": "Ja", "correct": true, "because": "Cloud-Speicher wie OneDrive kann lokal ersetzen"}, {"text": "Nein", "correct": false, "because": "Cloud bietet Alternative zur lokalen Speicherung"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Sicherheitsmaßnahmen bei der Nutzung von Cloud-Diensten berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Datenschutz und Authentifizierung sind essenziell"}, {"text": "Nein", "correct": false, "because": "Sicherheit ist unerlässlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Client ohne spezielle Software Cloud-Dienste nutzen?', 2, '[{"text": "Ja", "correct": true, "because": "Webbrowser reicht oft aus"}, {"text": "Nein", "correct": false, "because": "Software ist nicht immer nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Cloud-Dienste immer schneller als lokale Lösungen?', 2, '[{"text": "Nein", "correct": true, "because": "Geschwindigkeit hängt von Internetverbindung ab"}, {"text": "Ja", "correct": false, "because": "Lokale Lösungen können schneller sein"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Cloud-Diensttyp wird häufig für die Speicherung von Dateien genutzt?', 2, '[{"text": "Storage as a Service", "correct": true, "because": "z. B. Google Drive oder Dropbox"}, {"text": "Infrastructure as a Service", "correct": false, "because": "IaaS ist für virtuelle Maschinen"}, {"text": "Platform as a Service", "correct": false, "because": "PaaS ist für Entwicklung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wird üblicherweise für den Zugriff auf Cloud-Dienste über einen Webbrowser verwendet?', 3, '[{"text": "HTTPS", "correct": true, "because": "Sichere Kommunikation über Web"}, {"text": "FTP", "correct": false, "because": "Weniger üblich für Cloud"}, {"text": "ICMP", "correct": false, "because": "Nur für Diagnosen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein wesentlicher Vorteil der Nutzung von Cloud-Diensten für Clients?', 2, '[{"text": "Skalierbarkeit", "correct": true, "because": "Ressourcen können flexibel angepasst werden"}, {"text": "Hohe Latenz", "correct": false, "because": "Latenz ist ein Nachteil"}, {"text": "Komplexe Installation", "correct": false, "because": "Cloud vereinfacht Installation"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anforderung muss vor der Cloud-Integration eines Clients geprüft werden?', 2, '[{"text": "Internetbandbreite", "correct": true, "because": "Bestimmt Zugriffsgeschwindigkeit"}, {"text": "Bildschirmgröße", "correct": false, "because": "Irrelevant für Cloud"}, {"text": "Prozessorleistung", "correct": false, "because": "Weniger entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Sicherheitsmechanismus ist für den Cloud-Zugriff unerlässlich?', 2, '[{"text": "Authentifizierung", "correct": true, "because": "Schützt vor unbefugtem Zugriff"}, {"text": "Firewall", "correct": false, "because": "Wichtig, aber nicht spezifisch"}, {"text": "Antivirus", "correct": false, "because": "Ergänzend, nicht primär"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Cloud-Dienste könnten für die Client-Integration genutzt werden?', 4, '[{"text": "Speicherdienste (z. B. OneDrive)", "correct": true, "because": "Für Dateizugriff"}, {"text": "Anwendungsdienste (z. B. Office 365)", "correct": true, "because": "Für Software"}, {"text": "Virtuelle Maschinen (z. B. AWS EC2)", "correct": true, "because": "Für virtuelle Clients"}, {"text": "Lokale Datenbanken", "correct": false, "because": "Nicht Cloud-basiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche technischen Anforderungen müssen für die Nutzung von Cloud-Diensten geprüft werden?', 3, '[{"text": "Internetgeschwindigkeit", "correct": true, "because": "Beeinflusst Zugriff"}, {"text": "Betriebssystemkompatibilität", "correct": true, "because": "Muss mit Cloud kompatibel sein"}, {"text": "Netzwerkprotokolle", "correct": true, "because": "z. B. HTTPS"}, {"text": "Bildschirmhelligkeit", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Sicherheitsmaßnahmen sind bei der Cloud-Integration wichtig?', 4, '[{"text": "Verschlüsselung", "correct": true, "because": "Schützt Daten"}, {"text": "Zwei-Faktor-Authentifizierung", "correct": true, "because": "Erhöht Sicherheit"}, {"text": "Regelmäßige Updates", "correct": true, "because": "Schließt Sicherheitslücken"}, {"text": "Lokale Passwörter", "correct": false, "because": "Cloud-spezifisch nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Nutzung von Cloud-Diensten für Clients?', 3, '[{"text": "Zugriff von überall", "correct": true, "because": "Cloud ist ortsunabhängig"}, {"text": "Geringere Hardwareanforderungen", "correct": true, "because": "Verarbeitung in der Cloud"}, {"text": "Hohe Anfangskosten", "correct": false, "because": "Kosten sind meist niedriger"}, {"text": "Einfache Skalierung", "correct": true, "because": "Ressourcen flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sollten bei der Auswahl eines Cloud-Dienstes untersucht werden?', 3, '[{"text": "Verfügbarkeit", "correct": true, "because": "Uptime ist entscheidend"}, {"text": "Kosten", "correct": true, "because": "Budgetrelevant"}, {"text": "Datenschutz", "correct": true, "because": "z. B. DSGVO-Konformität"}, {"text": "Farbe der Benutzeroberfläche", "correct": false, "because": "Irrelevant"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Cloud-Dienste erfordern eine Internetverbindung. b) Lokale Software ist immer notwendig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Internet ja, Software optional"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) HTTPS wird für sicheren Cloud-Zugriff genutzt. b) Cloud-Dienste sind immer kostenlos.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "HTTPS ja, kostenlos nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Cloud-Dienste bieten Skalierbarkeit. b) Sicherheitsmaßnahmen sind unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Skalierbarkeit ja, Sicherheit wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Zwei-Faktor-Authentifizierung erhöht die Cloud-Sicherheit. b) Bandbreite ist für Cloud-Zugriff irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "2FA ja, Bandbreite wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Cloud-Dienste ermöglichen ortsunabhängigen Zugriff. b) Cloud-Dienste erfordern immer eine lokale Installation.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ortsunabhängig ja, Installation optional"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

