
-- Netzwerktechnik: Netzwerkkomponenten (Router)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Router immer für die Internetverbindung notwendig?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch lokal Netzwerke verbinden"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend für LAN"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion eines Routers ist für die Verbindung zwischen Netzwerken entscheidend?', 3, '[{"text": "Routing", "correct": true, "because": "Leitet Daten zwischen Netzwerken"}, {"text": "Switching", "correct": false, "because": "Für lokale Verbindungen"}, {"text": "Design des Gehäuses", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Router kann mehrere Subnetze verwalten. b) Ein Router ist nur für WLAN nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Router verwaltet Subnetze"}, {"text": "Beides stimmt", "correct": false, "because": "Router auch für Kabel"}, {"text": "Nur b) stimmt", "correct": false, "because": "WLAN ist optional"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal eines Routers solltest du für ein großes Büro priorisieren?', 4, '[{"text": "Bandbreitenmanagement", "correct": true, "because": "Optimiert Datenverkehr"}, {"text": "Anzahl der LEDs", "correct": false, "because": "Nur Statusanzeige"}, {"text": "Farbe des Geräts", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Router ohne WAN-Port ein lokales Netzwerk betreiben?', 2, '[{"text": "Ja", "correct": true, "because": "LAN-Ports reichen für lokales Netz"}, {"text": "Nein", "correct": false, "because": "WAN nicht zwingend nötig"}]');

-- Netzwerktechnik: Netzwerkkomponenten (Router)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Router immer für die Internetverbindung notwendig?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch lokale Netzwerke verbinden"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend für LAN"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion eines Routers ist für die Verbindung zwischen Netzwerken entscheidend?', 3, '[{"text": "Routing", "correct": true, "because": "Leitet Daten zwischen Netzwerken"}, {"text": "Switching", "correct": false, "because": "Für lokale Verbindungen"}, {"text": "Signalverstärkung", "correct": false, "because": "Nicht primäre Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Router kann auch als WLAN-Access-Point dienen. b) Ein Router arbeitet nur auf Schicht 1 des OSI-Modells.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Router haben oft WLAN-Funktion"}, {"text": "Beides stimmt", "correct": false, "because": "Router auf Schicht 3"}, {"text": "Nur b) stimmt", "correct": false, "because": "Schicht 1 ist falsch"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal eines Routers solltest du für ein großes Unternehmen priorisieren?', 4, '[{"text": "Hohe Routing-Kapazität", "correct": true, "because": "Bewältigt viele Verbindungen"}, {"text": "Anzahl der LEDs", "correct": false, "because": "Nur Statusanzeige"}, {"text": "Farbe des Gehäuses", "correct": false, "because": "Kein Einfluss auf Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Router ohne WAN-Port ein lokales Netzwerk verwalten?', 2, '[{"text": "Ja", "correct": true, "because": "WAN ist für Internet, nicht LAN"}, {"text": "Nein", "correct": false, "because": "Lokales Netzwerk unabhängig"}]');

-- Netzwerktechnik: Netzwerkkomponenten (Router)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Router immer notwendig, um zwei Netzwerke zu verbinden?', 2, '[{"text": "Ja", "correct": true, "because": "Router leiten Daten zwischen Netzwerken"}, {"text": "Nein", "correct": false, "because": "Router sind dafür essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion eines Routers ist für die Netzwerktrennung entscheidend?', 3, '[{"text": "NAT (Network Address Translation)", "correct": true, "because": "Trennt lokale von öffentlichen Netzen"}, {"text": "Switching", "correct": false, "because": "Für lokale Verbindungen"}, {"text": "Design des Gehäuses", "correct": false, "because": "Kein Einfluss auf Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Router kann DHCP bereitstellen. b) Ein Router ist nur für kabelgebundene Netzwerke geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Router bieten oft DHCP"}, {"text": "Beides stimmt", "correct": false, "because": "Router auch für WLAN"}, {"text": "Nur b) stimmt", "correct": false, "because": "DHCP ist üblich"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal eines Routers solltest du für ein Heimnetzwerk priorisieren?', 4, '[{"text": "WLAN-Reichweite", "correct": true, "because": "Wichtig für drahtlose Geräte"}, {"text": "Anzahl der LEDs", "correct": false, "because": "Nur Statusanzeige"}, {"text": "Farbe des Geräts", "correct": false, "because": "Kein Einfluss auf Leistung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Router ohne Internetverbindung ein lokales Netzwerk betreiben?', 2, '[{"text": "Ja", "correct": true, "because": "Lokale Kommunikation möglich"}, {"text": "Nein", "correct": false, "because": "Internet nicht zwingend nötig"}]');
