-- questions.sql (Adressierungsarten: Methoden zur Speicherzuweisung in der Informatik)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die direkte Adressierung immer die schnellste Methode?', 2, '[{"text": "Ja", "correct": true, "because": "Kein zusätzlicher Zugriff nötig"}, {"text": "Nein", "correct": false, "because": "Kontextabhängig, aber meist schnell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Adressierungsart nutze ich für einen festen Speicherort?', 3, '[{"text": "Direkte Adressierung", "correct": true, "because": "Gibt Adresse direkt an"}, {"text": "Indirekte Adressierung", "correct": false, "because": "Nutzt Zwischenschritt"}, {"text": "Indexierte Adressierung", "correct": false, "because": "Dynamische Verschiebung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Adressierungsarten sind flexibel?', 5, '[{"text": "Indirekte Adressierung", "correct": true, "because": "Zeiger auf Adresse"}, {"text": "Indexierte Adressierung", "correct": true, "because": "Offset-basierte Anpassung"}, {"text": "Direkte Adressierung", "correct": false, "because": "Statisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Indirekte Adressierung braucht einen Zeiger. b) Direkte Adressierung ist dynamisch.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Direkte Adressierung ist fest"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl der Adressierungsart?', 4, '[{"text": "Prozessorgeschwindigkeit", "correct": false, "because": "Beeinflusst Effizienz"}, {"text": "Speicherzugriff", "correct": false, "because": "Kern der Methode"}, {"text": "Programmiersprache", "correct": true, "because": "Höhere Ebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die indexierte Adressierung einen Offset nutzt?', 2, '[{"text": "Ja", "correct": true, "because": "Basisadresse plus Verschiebung"}, {"text": "Nein", "correct": false, "because": "Offset ist Kern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode ist für Arrays ideal?', 3, '[{"text": "Indexierte Adressierung", "correct": true, "because": "Effizienter Elementzugriff"}, {"text": "Direkte Adressierung", "correct": false, "because": "Zu statisch"}, {"text": "Indirekte Adressierung", "correct": false, "because": "Komplexer"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur indirekten Adressierung?', 5, '[{"text": "Zeiger", "correct": true, "because": "Verweist auf Adresse"}, {"text": "Zusätzlicher Speicherzugriff", "correct": true, "because": "Indirektion erfordert"}, {"text": "Feste Adresse", "correct": false, "because": "Nicht statisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Direkte Adressierung ist einfach. b) Sie ist immer effizienter als indirekte. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Effizienz hängt vom Einsatz ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Adressierungsart unwichtig?', 4, '[{"text": "Speicherzugriffszeit", "correct": false, "because": "Beeinflusst Performance"}, {"text": "Adressformat", "correct": false, "because": "Definiert Zugriff"}, {"text": "Betriebssystem", "correct": true, "because": "Hardwareebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die direkte Adressierung flexibel?', 2, '[{"text": "Nein", "correct": true, "because": "Feste Adresse vorgegeben"}, {"text": "Ja", "correct": false, "because": "Nicht dynamisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile hat die indirekte Adressierung?', 4, '[{"text": "Flexibilität", "correct": true, "because": "Dynamische Zuweisung"}, {"text": "Zeigerunterstützung", "correct": true, "because": "Ermöglicht Verweise"}, {"text": "Minimale Zugriffszeit", "correct": false, "because": "Langsamer durch Indirektion"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass indexierte Adressierung nur für Arrays ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für andere Strukturen"}, {"text": "Ja", "correct": false, "because": "Vielseitig einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Wahl der Adressierungsart?', 3, '[{"text": "Effizienz", "correct": true, "because": "Optimiert Zugriff"}, {"text": "Speichergröße", "correct": false, "because": "Sekundär"}, {"text": "Programmieraufwand", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Indirekte Adressierung ist komplexer. b) Direkte Adressierung nutzt Zeiger.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Direkte Adressierung ohne Zeiger"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat die indirekte Adressierung?', 5, '[{"text": "Höherer Zeitaufwand", "correct": true, "because": "Zusätzlicher Zugriff"}, {"text": "Komplexität", "correct": true, "because": "Schwerer zu verwalten"}, {"text": "Geringere Flexibilität", "correct": false, "because": "Ist flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der direkten Adressierung unwichtig?', 3, '[{"text": "Speicheradresse", "correct": false, "because": "Kern der Methode"}, {"text": "Zugriffsgeschwindigkeit", "correct": false, "because": "Entscheidend"}, {"text": "Offset-Wert", "correct": true, "because": "Für indexierte Adressierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Nutzt die indexierte Adressierung eine Basisadresse?', 3, '[{"text": "Ja", "correct": true, "because": "Basis plus Offset"}, {"text": "Nein", "correct": false, "because": "Kernprinzip"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die direkte Adressierung für Schleifen geeignet ist?', 2, '[{"text": "Nein", "correct": true, "because": "Zu statisch"}, {"text": "Ja", "correct": false, "because": "Indexierte besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Adressierungsart wähle ich für dynamische Daten?', 4, '[{"text": "Indirekte Adressierung", "correct": true, "because": "Zeiger erlauben Flexibilität"}, {"text": "Direkte Adressierung", "correct": false, "because": "Statisch"}, {"text": "Immediate Adressierung", "correct": false, "because": "Wert, nicht Adresse"}]');

