-- questions.sql (All-Flash- und Hybrid-Flash-Storage: Speicherlösungen)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist All-Flash-Storage immer schneller als Hybrid-Flash?', 2, '[{"text": "Ja", "correct": true, "because": "Nur SSDs ohne HDDs"}, {"text": "Nein", "correct": false, "because": "Kontextabhängig, aber meist ja"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie nutzt Hybrid-Flash-Storage?', 3, '[{"text": "Kombination aus SSD und HDD", "correct": true, "because": "Bietet Balance aus Geschwindigkeit und Kapazität"}, {"text": "Nur SSDs", "correct": false, "because": "Das wäre All-Flash"}, {"text": "Nur HDDs", "correct": false, "because": "Fehlt die Flash-Komponente"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet All-Flash-Storage?', 5, '[{"text": "Höhere Geschwindigkeit", "correct": true, "because": "SSDs ohne mechanische Teile"}, {"text": "Geringerer Stromverbrauch", "correct": true, "because": "Effizienter als HDDs"}, {"text": "Größere Kapazität", "correct": false, "because": "HDDs bieten mehr Platz"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Hybrid-Flash ist kostengünstiger als All-Flash. b) All-Flash hat keine Tiering-Optionen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "All-Flash kann Tiering nutzen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl zwischen All-Flash und Hybrid-Flash?', 4, '[{"text": "Leistungsanforderungen", "correct": false, "because": "Entscheidend für Auswahl"}, {"text": "Budget", "correct": false, "because": "Kosten sind zentral"}, {"text": "Betriebssystem", "correct": true, "because": "Wenig Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Hybrid-Flash Tiering nutzt?', 2, '[{"text": "Ja", "correct": true, "because": "Daten zwischen SSD und HDD verschieben"}, {"text": "Nein", "correct": false, "because": "Tiering ist typisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Lösung wähle ich für maximale Performance?', 3, '[{"text": "All-Flash", "correct": true, "because": "Höchste IOPS und geringste Latenz"}, {"text": "Hybrid-Flash", "correct": false, "because": "Kompromisslösung"}, {"text": "HDD-only", "correct": false, "because": "Langsamer"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zu Hybrid-Flash-Storage?', 5, '[{"text": "SSDs für heiße Daten", "correct": true, "because": "Schneller Zugriff"}, {"text": "HDDs für kalte Daten", "correct": true, "because": "Kostengünstige Kapazität"}, {"text": "Nur NVMe", "correct": false, "because": "Nicht ausschließlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) All-Flash ist teurer als Hybrid. b) Hybrid hat keine SSDs. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hybrid nutzt SSDs"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei All-Flash unwichtig?', 4, '[{"text": "Latenzzeit", "correct": false, "because": "Kernvorteil"}, {"text": "Datenreduktion", "correct": false, "because": "Optimiert Kapazität"}, {"text": "Plattenrotation", "correct": true, "because": "Keine HDDs"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Hybrid-Flash für Big Data geeignet?', 2, '[{"text": "Ja", "correct": true, "because": "Kombiniert Kapazität und Geschwindigkeit"}, {"text": "Nein", "correct": false, "because": "Abhängig, aber oft passend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat Hybrid-Flash?', 4, '[{"text": "Komplexeres Management", "correct": true, "because": "Tiering erforderlich"}, {"text": "Höhere Latenz als All-Flash", "correct": true, "because": "HDD-Komponente"}, {"text": "Geringere Kosten", "correct": false, "because": "Vorteil, kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass All-Flash keine Kapazität bietet. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kapazität mit Deduplizierung hoch"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Wahl von All-Flash?', 3, '[{"text": "Performance", "correct": true, "because": "Hauptvorteil von SSDs"}, {"text": "Kapazität", "correct": false, "because": "Sekundär"}, {"text": "Einfachheit", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Hybrid-Flash nutzt Caching. b) All-Flash ist langsamer.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "All-Flash ist schneller"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile hat Hybrid-Flash?', 5, '[{"text": "Kosteneffizienz", "correct": true, "because": "Kombiniert HDD-Preis mit SSD-Speed"}, {"text": "Hohe Kapazität", "correct": true, "because": "HDDs bieten Platz"}, {"text": "Maximale IOPS", "correct": false, "because": "All-Flash überlegen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Hybrid-Flash unwichtig?', 3, '[{"text": "Tiering-Strategie", "correct": false, "because": "Entscheidend für Effizienz"}, {"text": "SSD-Anteil", "correct": false, "because": "Beeinflusst Performance"}, {"text": "Firmenlogo", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann All-Flash deduplizieren?', 3, '[{"text": "Ja", "correct": true, "because": "Häufig integriert"}, {"text": "Nein", "correct": false, "because": "Falsch, oft vorhanden"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Hybrid-Flash für Backups passt?', 2, '[{"text": "Ja", "correct": true, "because": "Kapazität und Kosten ideal"}, {"text": "Nein", "correct": false, "because": "Abhängig, aber oft geeignet"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Lösung wähle ich für gemischte Workloads?', 4, '[{"text": "Hybrid-Flash", "correct": true, "because": "Flexibel für heiße und kalte Daten"}, {"text": "All-Flash", "correct": false, "because": "Teurer bei hoher Kapazität"}, {"text": "HDD-only", "correct": false, "because": "Zu langsam"}]');

