-- questions.sql (Anwenderprogramme: Software für Endnutzer)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Anwenderprogramme immer für technische Nutzer gedacht?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Laien"}, {"text": "Ja", "correct": false, "because": "Breite Zielgruppe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Anwenderprogrammen?', 3, '[{"text": "Unterstützung bei Aufgaben", "correct": true, "because": "Erleichtert Arbeit"}, {"text": "Datenbankverwaltung", "correct": false, "because": "Spezifischer Zweck"}, {"text": "Hardwaresteuerung", "correct": false, "because": "Andere Ebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beispiele gehören zu Anwenderprogrammen?', 5, '[{"text": "Textverarbeitung", "correct": true, "because": "Für Endnutzer"}, {"text": "Tabellenkalkulation", "correct": true, "because": "Breite Anwendung"}, {"text": "Betriebssystem", "correct": false, "because": "Systemsoftware"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Anwenderprogramme sind benutzerfreundlich. b) Sie erfordern Programmierkenntnisse.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Keine Programmierung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Auswahl von Anwenderprogrammen?', 4, '[{"text": "Benutzerfreundlichkeit", "correct": false, "because": "Kernkriterium"}, {"text": "Funktionsumfang", "correct": false, "because": "Entscheidend für Nutzen"}, {"text": "Programmiereranzahl", "correct": true, "because": "Irrelevant für Nutzer"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Anwenderprogramme plattformabhängig sind?', 2, '[{"text": "Ja", "correct": true, "because": "Oft systemspezifisch"}, {"text": "Nein", "correct": false, "because": "Abhängig vom Programm"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Software ist ein Anwenderprogramm?', 3, '[{"text": "Microsoft Word", "correct": true, "because": "Für Endnutzer"}, {"text": "Linux Kernel", "correct": false, "because": "Systemsoftware"}, {"text": "Apache Server", "correct": false, "because": "Serversoftware"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zu den Merkmalen von Anwenderprogrammen?', 5, '[{"text": "Grafische Oberfläche", "correct": true, "because": "Benutzerfreundlich"}, {"text": "Direkte Nutzung", "correct": true, "because": "Keine Programmierung"}, {"text": "Low-Level-Steuerung", "correct": false, "because": "Systemebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Anwenderprogramme sind für Endnutzer. b) Sie sind immer kostenlos. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kosten variieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Anwenderprogrammen unwichtig?', 4, '[{"text": "Usability", "correct": false, "because": "Kernmerkmal"}, {"text": "Funktionalität", "correct": false, "because": "Definiert Nutzen"}, {"text": "Quellcode", "correct": true, "because": "Für Nutzer irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Anwenderprogramme systemnah?', 2, '[{"text": "Nein", "correct": true, "because": "Nutzerorientiert"}, {"text": "Ja", "correct": false, "because": "Abstraktionsschicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Anwenderprogramme?', 4, '[{"text": "Einfache Bedienung", "correct": true, "because": "Für Laien geeignet"}, {"text": "Effizienzsteigerung", "correct": true, "because": "Optimiert Aufgaben"}, {"text": "Hardwaresteuerung", "correct": false, "because": "Systemsoftware"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Anwenderprogramme nur für Büros sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Breite Einsatzbereiche"}, {"text": "Ja", "correct": false, "because": "Nicht eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Anwenderprogrammen?', 3, '[{"text": "Benutzerfreundlichkeit", "correct": true, "because": "Hauptfokus"}, {"text": "Technische Details", "correct": false, "because": "Sekundär"}, {"text": "Entwicklungskosten", "correct": false, "because": "Nutzerperspektive"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Anwenderprogramme haben oft GUIs. b) Sie sind immer plattformunabhängig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Plattformabhängig möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile haben Anwenderprogramme?', 5, '[{"text": "Begrenzte Anpassbarkeit", "correct": true, "because": "Für Laien standardisiert"}, {"text": "Kosten bei Lizenzen", "correct": true, "because": "Oft kommerziell"}, {"text": "Hohe Flexibilität", "correct": false, "because": "Eher eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Anwenderprogrammen unwichtig?', 3, '[{"text": "Bedienoberfläche", "correct": false, "because": "Kernmerkmal"}, {"text": "Nutzerunterstützung", "correct": false, "because": "Erleichtert Nutzung"}, {"text": "Assembly-Code", "correct": true, "because": "Nutzerunsichtbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Müssen Anwenderprogramme updatesicher sein?', 3, '[{"text": "Ja", "correct": true, "because": "Sicherheit und Funktion"}, {"text": "Nein", "correct": false, "because": "Wichtig für Nutzer"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Anwenderprogramme Open Source sein können?', 2, '[{"text": "Ja", "correct": true, "because": "Beispiele wie LibreOffice"}, {"text": "Nein", "correct": false, "because": "Nicht ausgeschlossen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Programm wähle ich für alltägliche Aufgaben?', 4, '[{"text": "Excel", "correct": true, "because": "Anwenderprogramm"}, {"text": "Windows Kernel", "correct": false, "because": "Systemsoftware"}, {"text": "MySQL", "correct": false, "because": "Datenbanksoftware"}]');

