-- questions.sql (Arithmetische Operatoren: Mathematische Operationen in Programmierung und Datenbanken)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind arithmetische Operatoren nur in Programmiersprachen verfügbar?', 2, '[{"text": "Nein", "correct": true, "because": "Auch in Datenbanken wie SQL nutzbar"}, {"text": "Ja", "correct": false, "because": "Nicht exklusiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit arithmetischen Operatoren?', 3, '[{"text": "Mathematische Berechnungen", "correct": true, "because": "Ermöglicht Addition, Subtraktion etc."}, {"text": "Textverarbeitung", "correct": false, "because": "Anderer Bereich"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Operatoren gehören zu den arithmetischen Operatoren?', 5, '[{"text": "Addition (+)", "correct": true, "because": "Grundoperation"}, {"text": "Multiplikation (*)", "correct": true, "because": "Grundoperation"}, {"text": "Vergleich (==)", "correct": false, "because": "Logischer Operator"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Modulo-Operator (%) ist ein arithmetischer Operator. b) Er wird nur für Ganzzahlen verwendet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch für Gleitkommazahlen möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Verwendung arithmetischer Operatoren?', 4, '[{"text": "Datentypen", "correct": false, "because": "Entscheidend für Ergebnisse"}, {"text": "Reihenfolge", "correct": false, "because": "Operatorenpriorität wichtig"}, {"text": "Schriftart", "correct": true, "because": "Irrelevant für Berechnung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob der Divisionsoperator (/) Ganzzahlen immer abrundet?', 2, '[{"text": "Nein", "correct": true, "because": "Ergebnis kann Gleitkomma sein"}, {"text": "Ja", "correct": false, "because": "Abhängig von Sprache"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Operator berechnet den Rest einer Division?', 3, '[{"text": "Modulo (%)", "correct": true, "because": "Restwertoperator"}, {"text": "Division (/)", "correct": false, "because": "Quotient"}, {"text": "Subtraktion (-)", "correct": false, "because": "Differenz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Arbeit mit arithmetischen Operatoren?', 5, '[{"text": "Operatorenpriorität", "correct": true, "because": "Bestimmt Reihenfolge"}, {"text": "Datentypkonvertierung", "correct": true, "because": "Vermeidet Fehler"}, {"text": "Textformatierung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Arithmetische Operatoren sind universell in Programmiersprachen. b) Sie funktionieren nur mit Zahlen. Stimmt das?', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Nur numerische Werte"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) auch korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) auch korrekt"}, {"text": "Beides falsch", "correct": false, "because": "Beide richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei arithmetischen Operatoren unwichtig?', 4, '[{"text": "Rechenregeln", "correct": false, "because": "Bestimmen Ergebnis"}, {"text": "Datentypen", "correct": false, "because": "Beeinflussen Operation"}, {"text": "Codekommentare", "correct": true, "because": "Keine Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann der Subtraktionsoperator (-) auch für Zeitberechnungen genutzt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Zeitdifferenzen möglich"}, {"text": "Nein", "correct": false, "because": "Nicht ausgeschlossen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bringen arithmetische Operatoren?', 4, '[{"text": "Schnelle Berechnungen", "correct": true, "because": "Effiziente Operationen"}, {"text": "Einfache Implementierung", "correct": true, "because": "Grundfunktionen"}, {"text": "Textverarbeitung", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass arithmetische Operatoren immer exakte Ergebnisse liefern. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Gleitkommaungenauigkeit möglich"}, {"text": "Ja", "correct": false, "because": "Abhängig von Datentyp"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei arithmetischen Operatoren?', 3, '[{"text": "Korrektheit", "correct": true, "because": "Sichert Ergebnisse"}, {"text": "Schnelligkeit", "correct": false, "because": "Sekundär"}, {"text": "Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Multiplikationsoperator (*) hat Vorrang vor Addition (+). b) Operatoren arbeiten mit Zeichenketten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeichenketten nicht direkt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile haben arithmetische Operatoren?', 5, '[{"text": "Rundungsfehler", "correct": true, "because": "Bei Gleitkommazahlen"}, {"text": "Überlauf", "correct": true, "because": "Bei großen Werten"}, {"text": "Hohe Lesbarkeit", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei arithmetischen Operatoren unwichtig?', 3, '[{"text": "Priorität", "correct": false, "because": "Beeinflusst Reihenfolge"}, {"text": "Datentyp", "correct": false, "because": "Entscheidet Ergebnis"}, {"text": "Variablenname", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann der Additionsoperator (+) auch für Strings genutzt werden?', 3, '[{"text": "Ja", "correct": true, "because": "Konkatenation in manchen Sprachen"}, {"text": "Nein", "correct": false, "because": "Nicht rein arithmetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob der Modulo-Operator (%) negative Zahlen verarbeiten kann?', 2, '[{"text": "Ja", "correct": true, "because": "Abhängig von Sprache"}, {"text": "Nein", "correct": false, "because": "Möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Operator wähle ich für eine ganzzahlige Division?', 4, '[{"text": "Modulo (%)", "correct": true, "because": "Restwert"}, {"text": "Division (/)", "correct": false, "because": "Quotient"}, {"text": "Addition (+)", "correct": false, "because": "Summierung"}]');

