-- questions.sql (Ausbildungsvertrag: Vertrag zwischen Auszubildendem und Ausbildendem)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Ausbildungsvertrag immer schriftlich erforderlich?', 2, '[{"text": "Ja", "correct": true, "because": "Gesetzlich vorgeschrieben"}, {"text": "Nein", "correct": false, "because": "Schriftform Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Ausbildungsvertrag?', 3, '[{"text": "Rechte und Pflichten festlegen", "correct": true, "because": "Regelt Ausbildungsverhältnis"}, {"text": "Kosten senken", "correct": false, "because": "Indirekt"}, {"text": "Produktivität steigern", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem Ausbildungsvertrag?', 5, '[{"text": "Ausbildungsdauer", "correct": true, "because": "Festgelegte Zeit"}, {"text": "Vergütung", "correct": true, "because": "Entlohnung geregelt"}, {"text": "Marketingplan", "correct": false, "because": "Kein Vertragsbestandteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Ausbildungsvertrag ist rechtlich bindend. b) Er muss mündlich abgeschlossen werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schriftform erforderlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Ausbildungsvertrag?', 4, '[{"text": "Ausbildungsbeginn", "correct": false, "because": "Pflichtangabe"}, {"text": "Probezeit", "correct": false, "because": "Gesetzlich vorgeschrieben"}, {"text": "Büroverschönerung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Ausbildungsvertrag eine Probezeit enthält?', 2, '[{"text": "Ja", "correct": true, "because": "Gesetzlich vorgesehen"}, {"text": "Nein", "correct": false, "because": "Teil des Vertrags"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Angabe ist im Ausbildungsvertrag Pflicht?', 3, '[{"text": "Beruf", "correct": true, "because": "Definiert Ausbildung"}, {"text": "Hobbys", "correct": false, "because": "Nicht relevant"}, {"text": "Lieblingsfarbe", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zu einem Ausbildungsvertrag?', 5, '[{"text": "Ausbildungsvergütung", "correct": true, "because": "Pflichtangabe"}, {"text": "Kündigungsfristen", "correct": true, "because": "Rechtlich geregelt"}, {"text": "Produktwerbung", "correct": false, "because": "Kein Vertragsbestandteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Ausbildungsvertrag regelt die Arbeitszeit. b) Er ist optional. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Pflicht für Ausbildung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist im Ausbildungsvertrag unwichtig?', 4, '[{"text": "Ausbildungsinhalt", "correct": false, "because": "Pflichtangabe"}, {"text": "Vergütung", "correct": false, "because": "Gesetzlich vorgeschrieben"}, {"text": "Bürodesign", "correct": true, "because": "Kein Vertragsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ein Ausbildungsvertrag bei der Kammer eingereicht werden?', 2, '[{"text": "Ja", "correct": true, "because": "Pflicht in Deutschland"}, {"text": "Nein", "correct": false, "because": "Gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Ausbildungsvertrag?', 4, '[{"text": "Rechtssicherheit", "correct": true, "because": "Klarheit für beide Seiten"}, {"text": "Verbindlichkeit", "correct": true, "because": "Bindet Parteien"}, {"text": "Schnellere Prozesse", "correct": false, "because": "Kein direkter Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Ausbildungsvertrag nur für den Auszubildenden wichtig ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Ausbildenden relevant"}, {"text": "Ja", "correct": false, "because": "Beidseitige Verpflichtung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich im Ausbildungsvertrag?', 3, '[{"text": "Ausbildungsbedingungen", "correct": true, "because": "Kern des Vertrags"}, {"text": "Kosten", "correct": false, "because": "Sekundär"}, {"text": "Ästhetik", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Ausbildungsvertrag legt die Vergütung fest. b) Er ist nur für die Probezeit bindend.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Gilt für gesamte Dauer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat ein fehlender Ausbildungsvertrag?', 5, '[{"text": "Rechtsunsicherheit", "correct": true, "because": "Keine klare Regelung"}, {"text": "Keine Vergütungssicherheit", "correct": true, "because": "Entlohnung unklar"}, {"text": "Schnellere Ausbildung", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist im Ausbildungsvertrag unwichtig?', 3, '[{"text": "Ausbildungsdauer", "correct": false, "because": "Pflichtangabe"}, {"text": "Arbeitszeit", "correct": false, "because": "Regelungsbestandteil"}, {"text": "Mitarbeiternamen", "correct": true, "because": "Kein Vertragsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Ausbildungsvertrag geändert werden?', 3, '[{"text": "Ja", "correct": true, "because": "Mit Zustimmung beider Seiten"}, {"text": "Nein", "correct": false, "because": "Flexibel anpassbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Ausbildungsvertrag die Ausbildungsstätte nennt?', 2, '[{"text": "Ja", "correct": true, "because": "Pflichtangabe"}, {"text": "Nein", "correct": false, "because": "Teil des Vertrags"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Angabe wähle ich für den Ausbildungsvertrag?', 4, '[{"text": "Ausbildungsberuf", "correct": true, "because": "Definiert Ausbildung"}, {"text": "Hobbys", "correct": false, "because": "Irrelevant"}, {"text": "Lieblingsfarbe", "correct": false, "because": "Kein Bezug"}]');

