-- Lernfeld:1 > Das Unternehmen und die eigene Rolle im Betrieb beschreiben > Rechtliches > Duales System > Aufbau
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Binärfragen (8 Stück, 40%)
('00000000-0000-0000-0000-000000000000', 'Kann das duale System ohne Berufsschule funktionieren?', 2, '[{"text": "Nein", "correct": true, "because": "Berufsschule ist Pflichtbestandteil"}, {"text": "Ja", "correct": false, "because": "Dualität erfordert beide Orte"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Betrieb im dualen System immer dabei sein?', 2, '[{"text": "Ja", "correct": true, "because": "Praxisort essenziell"}, {"text": "Nein", "correct": false, "because": "Betrieb zwingend erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die IHK ein Teil des dualen Systems?', 2, '[{"text": "Ja", "correct": true, "because": "Überwacht und prüft"}, {"text": "Nein", "correct": false, "because": "Zentrale Rolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Könnte das duale System nur Theorie umfassen?', 2, '[{"text": "Nein", "correct": true, "because": "Praxis und Theorie kombiniert"}, {"text": "Ja", "correct": false, "because": "Dualität fehlt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sag mir nochmal: Gehört die Berufsschule zum Aufbau des dualen Systems?', 2, '[{"text": "Ja", "correct": true, "because": "Theorieunterricht Pflicht"}, {"text": "Nein", "correct": false, "because": "Unverzichtbarer Teil"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann das duale System ohne Vertrag existieren?', 2, '[{"text": "Nein", "correct": true, "because": "Vertrag Grundlage"}, {"text": "Ja", "correct": false, "because": "Gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist der Betriebsrat ein fester Bestandteil des dualen Systems?', 2, '[{"text": "Nein", "correct": true, "because": "Optional je Betrieb"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Könnte die Jugendvertretung zum dualen System gehören?', 2, '[{"text": "Ja", "correct": true, "because": "Unterstützt Azubis"}, {"text": "Nein", "correct": false, "because": "Optionale Ergänzung"}]'),
-- Single-Choice-Fragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Was ist der Kern des dualen Systems?', 2, '[{"text": "Betrieb und Berufsschule", "correct": true, "because": "Dualität definiert"}, {"text": "Nur Betrieb", "correct": false, "because": "Schule fehlt"}, {"text": "Nur Theorie", "correct": false, "because": "Praxis fehlt"}]'),
('00000000-0000-0000-0000-000000000000', 'Meine Chefin sagt, das duale System hat viele Partner. Wer gehört dazu?', 3, '[{"text": "Betrieb, Schule, IHK", "correct": true, "because": "Hauptakteure"}, {"text": "Nur Betrieb", "correct": false, "because": "Zu wenig"}, {"text": "Nur Schule", "correct": false, "because": "Praxis fehlt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die IHK im dualen System?', 2, '[{"text": "Prüfungen organisieren", "correct": true, "because": "Kernaufgabe"}, {"text": "Vertrag schreiben", "correct": false, "because": "Betriebssache"}, {"text": "Unterricht geben", "correct": false, "because": "Schulaufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Der Abteilungsleiter fragt, was das duale System ausmacht. Was sage ich?', 3, '[{"text": "Praxis und Theorie kombiniert", "correct": true, "because": "Grundprinzip"}, {"text": "Nur Praxis", "correct": false, "because": "Theorie fehlt"}, {"text": "Nur Vertrag", "correct": false, "because": "Zu eng"}]'),
-- Multiple-Choice-Fragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zum Aufbau des dualen Systems?', 4, '[{"text": "Betrieb", "correct": true, "because": "Praxisort"}, {"text": "Berufsschule", "correct": true, "because": "Theorieort"}, {"text": "IHK", "correct": true, "because": "Prüfungsorgan"}, {"text": "Universität", "correct": false, "because": "Kein Teil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was macht das duale System aus?', 3, '[{"text": "Ausbildungsvertrag", "correct": true, "because": "Rechtliche Basis"}, {"text": "Praxis im Betrieb", "correct": true, "because": "Lernort"}, {"text": "Theorie in der Schule", "correct": true, "because": "Lernort"}, {"text": "Urlaubsplanung", "correct": false, "because": "Kein Bestandteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Wir diskutieren über das duale System. Welche Akteure sind beteiligt?', 3, '[{"text": "Betrieb", "correct": true, "because": "Praxis"}, {"text": "Berufsschule", "correct": true, "because": "Theorie"}, {"text": "IHK", "correct": true, "because": "Prüfungen"}, {"text": "Kunden", "correct": false, "because": "Keine Rolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Institutionen unterstützen das duale System?', 4, '[{"text": "Berufsschule", "correct": true, "because": "Theorie"}, {"text": "Betrieb", "correct": true, "because": "Praxis"}, {"text": "IHK", "correct": true, "because": "Überwachung"}, {"text": "Supermarkt", "correct": false, "because": "Kein Bezug"}]'),
-- Kombinationsfragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Das duale System braucht Betrieb und Schule. b) Die IHK ist optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Betrieb/Schule ja, IHK Pflicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Vertrag ist Teil des dualen Systems. b) Es funktioniert ohne Berufsschule.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vertrag ja, Schule nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die IHK überwacht das duale System. b) Der Betriebsrat ist immer dabei.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "IHK ja, Betriebsrat nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Das duale System kombiniert Praxis und Theorie. b) Es braucht keine Prüfungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kombination ja, Prüfungen ja"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

