-- Parallelisierung.sql (Gleichzeitige Ausführung von Prozessen in IT-Systemen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die gleichzeitige Verarbeitung immer schneller als sequentielle?', 2, '[{"text": "Nein", "correct": true, "because": "Overhead kann Leistung beeinträchtigen"}, {"text": "Ja", "correct": false, "because": "Nicht immer effizienter"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptziel, wenn ich Aufgaben gleichzeitig ausführe?', 3, '[{"text": "Leistungssteigerung", "correct": true, "because": "Nutzt mehrere Kerne"}, {"text": "Minimale Rechenleistung", "correct": false, "because": "Gegenteil des Ziels"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Automatisierung bevorzugt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Techniken unterstützen gleichzeitige Verarbeitung?', 5, '[{"text": "Multithreading", "correct": true, "because": "Teilt Aufgaben in Threads"}, {"text": "Prozessparallelsierung", "correct": true, "because": "Nutzt mehrere Prozesse"}, {"text": "Einfache Schleifen", "correct": false, "because": "Sequentielle Ausführung"}, {"text": "Manuelle Eingaben", "correct": false, "because": "Keine Parallelität"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Parallelisierung benötigt mehrere Kerne. b) Sie eliminiert Latenz komplett.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) reduziert, aber eliminiert nicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung gleichzeitiger Verarbeitung?', 4, '[{"text": "Synchronisation", "correct": false, "because": "Vermeidet Konflikte"}, {"text": "Ressourcennutzung", "correct": false, "because": "Bestimmt Effizienz"}, {"text": "Farbschema", "correct": true, "because": "Irrelevant für Prozesse"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob gleichzeitige Verarbeitung immer Threads benötigt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Prozesse oder GPUs möglich"}, {"text": "Ja", "correct": false, "because": "Threads sind optional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Konzept ist für gleichzeitige Verarbeitung entscheidend?', 3, '[{"text": "Aufgabenteilung", "correct": true, "because": "Ermöglicht parallele Ausführung"}, {"text": "Einzelausführung", "correct": false, "because": "Sequentielle Methode"}, {"text": "Manuelle Zuweisung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei gleichzeitiger Verarbeitung?', 5, '[{"text": "Synchronisationsprobleme", "correct": true, "because": "Können Datenkonflikte verursachen"}, {"text": "Ressourcenkonkurrenz", "correct": true, "because": "Beeinträchtigt Leistung"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nicht primär relevant"}, {"text": "Einfache Schleifen", "correct": false, "because": "Keine Herausforderung"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Parallelisierung verbessert Rechenleistung. b) Sie ist immer einfach umzusetzen. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) kann komplex sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für gleichzeitige Verarbeitung?', 4, '[{"text": "Synchronisationsmechanismen", "correct": false, "because": "Verhindern Konflikte"}, {"text": "Skalierbare Architektur", "correct": false, "because": "Fördert Effizienz"}, {"text": "Grafische Oberfläche", "correct": true, "because": "Kein Parallelisierungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist gleichzeitige Verarbeitung nur für große Systeme?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für kleinere Anwendungen nützlich"}, {"text": "Ja", "correct": false, "because": "Breit anwendbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen profitieren von gleichzeitiger Verarbeitung?', 4, '[{"text": "Datenanalyse", "correct": true, "because": "Verarbeitet große Mengen parallel"}, {"text": "Bildverarbeitung", "correct": true, "because": "Nutzt mehrere Kerne"}, {"text": "Einfache Eingaben", "correct": false, "because": "Sequentielle Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass gleichzeitige Verarbeitung immer fehlerfrei ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Fehler durch Konflikte möglich"}, {"text": "Ja", "correct": false, "because": "Fehleranfällig ohne Synchronisation"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Implementierung gleichzeitiger Verarbeitung?', 3, '[{"text": "Korrekte Synchronisation", "correct": true, "because": "Vermeidet Datenfehler"}, {"text": "Maximale Komplexität", "correct": false, "because": "Vermeidbar"}, {"text": "Manuelle Aufteilung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Multithreading ist eine Form der Parallelisierung. b) Es funktioniert nur mit GPUs.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist nicht exklusiv"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Mechanismen unterstützen gleichzeitige Verarbeitung?', 5, '[{"text": "Mutexes", "correct": true, "because": "Sichern kritische Abschnitte"}, {"text": "Semaphoren", "correct": true, "because": "Kontrollieren Zugriff"}, {"text": "Statische Variablen", "correct": false, "because": "Keine Synchronisation"}, {"text": "Einfache Schleifen", "correct": false, "because": "Sequentielle Logik"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei gleichzeitiger Verarbeitung unwichtig?', 3, '[{"text": "Thread-Sicherheit", "correct": false, "because": "Sichert Datenintegrität"}, {"text": "Skalierbarkeit", "correct": false, "because": "Fördert Effizienz"}, {"text": "Bildbearbeitung", "correct": true, "because": "Kein Parallelisierungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob gleichzeitige Verarbeitung für Echtzeitanwendungen geeignet ist?', 2, '[{"text": "Ja", "correct": true, "because": "Verbessert Reaktionszeiten"}, {"text": "Nein", "correct": false, "because": "Echtzeit möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Verursacht gleichzeitige Verarbeitung immer Overhead?', 3, '[{"text": "Ja", "correct": true, "because": "Synchronisation kostet Ressourcen"}, {"text": "Nein", "correct": false, "because": "Overhead oft vorhanden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu gleichzeitiger Verarbeitung?', 4, '[{"text": "Verarbeitung großer Datenmengen", "correct": true, "because": "Nutzt mehrere Kerne"}, {"text": "Einfache Textausgabe", "correct": false, "because": "Sequentielle Aufgabe"}, {"text": "Manuelle Eingabe", "correct": false, "because": "Keine Parallelität"}]');

