-- Primärschlüssel.sql (Eindeutige Identifikatoren in Datenbanken)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kann eine Tabelle mehrere Primärschlüssel haben?', 2, '[{"text": "Nein", "correct": true, "because": "Nur ein Primärschlüssel pro Tabelle erlaubt"}, {"text": "Ja", "correct": false, "because": "Mehrere Schlüssel wären Fremdschlüssel"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel eines Primärschlüssels?', 3, '[{"text": "Eindeutige Identifikation", "correct": true, "because": "Jeder Datensatz eindeutig"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Nicht Aufgabe des Schlüssels"}, {"text": "Manuelle Zuordnung", "correct": false, "because": "Automatisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften muss ein Primärschlüssel erfüllen?', 5, '[{"text": "Eindeutigkeit", "correct": true, "because": "Keine Duplikate erlaubt"}, {"text": "Not-Null", "correct": true, "because": "Kein Wert darf fehlen"}, {"text": "Änderbarkeit", "correct": false, "because": "Soll stabil bleiben"}, {"text": "Mehrere Werte", "correct": false, "because": "Einzelwert pro Datensatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Primärschlüssel kann aus mehreren Spalten bestehen. b) Er darf NULL-Werte enthalten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, NULL verboten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Auswahl eines Primärschlüssels?', 4, '[{"text": "Eindeutigkeit", "correct": false, "because": "Kernanforderung"}, {"text": "Stabilität", "correct": false, "because": "Soll unveränderlich sein"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Schlüssel"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Primärschlüssel geändert werden darf?', 2, '[{"text": "Nein", "correct": true, "because": "Änderungen gefährden Integrität"}, {"text": "Ja", "correct": false, "because": "Stabilität erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt ein Primärschlüssel in Beziehungen?', 3, '[{"text": "Verknüpfung", "correct": true, "because": "Verbindet Tabellen über Fremdschlüssel"}, {"text": "Datenkompression", "correct": false, "because": "Nicht seine Funktion"}, {"text": "Manuelle Zuordnung", "correct": false, "because": "Automatisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Primärschlüssel?', 5, '[{"text": "Datenintegrität", "correct": true, "because": "Verhindert Duplikate"}, {"text": "Schnelle Abfragen", "correct": true, "because": "Index verbessert Zugriff"}, {"text": "Variable Werte", "correct": false, "because": "Müssen stabil sein"}, {"text": "Grafische Darstellung", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Primärschlüssel sind oft Auto-Increment-Werte. b) Sie müssen immer numerisch sein. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) auch Text möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen Primärschlüssel?', 4, '[{"text": "Eindeutigkeit", "correct": false, "because": "Kernanforderung"}, {"text": "Indexierung", "correct": false, "because": "Verbessert Leistung"}, {"text": "Änderbare Werte", "correct": true, "because": "Soll stabil bleiben"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Primärschlüssel ein Fremdschlüssel sein?', 2, '[{"text": "Ja", "correct": true, "because": "In Beziehungen möglich"}, {"text": "Nein", "correct": false, "because": "Funktion kombinierbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Datentypen eignen sich für Primärschlüssel?', 4, '[{"text": "Integer", "correct": true, "because": "Effizient und eindeutig"}, {"text": "UUID", "correct": true, "because": "Global eindeutig"}, {"text": "Variable Texte", "correct": false, "because": "Weniger stabil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Primärschlüssel immer automatisch generiert werden. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Manuelle Werte möglich"}, {"text": "Ja", "correct": false, "because": "Flexibilität gegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Wahl eines Primärschlüssels?', 3, '[{"text": "Eindeutigkeit", "correct": true, "because": "Verhindert Duplikate"}, {"text": "Hohe Länge", "correct": false, "because": "Effizienz wichtiger"}, {"text": "Manuelle Eingabe", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Primärschlüssel unterstützen Beziehungen. b) Sie sind nur für numerische Werte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) auch Text möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können ohne Primärschlüssel entstehen?', 5, '[{"text": "Doppelte Datensätze", "correct": true, "because": "Keine Eindeutigkeit"}, {"text": "Langsame Abfragen", "correct": true, "because": "Fehlender Index"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Netzwerkproblem"}, {"text": "Grafische Darstellung", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Primärschlüssel unwichtig?', 3, '[{"text": "Stabilität", "correct": false, "because": "Sichert Integrität"}, {"text": "Eindeutigkeit", "correct": false, "because": "Kernmerkmal"}, {"text": "Bildschirmauflösung", "correct": true, "because": "Kein Datenbankfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Primärschlüssel automatisch indiziert wird?', 2, '[{"text": "Ja", "correct": true, "because": "Verbessert Abfragen"}, {"text": "Nein", "correct": false, "because": "Index Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ein Primärschlüssel ein einzelnes Attribut sein?', 3, '[{"text": "Nein", "correct": true, "because": "Kombinierte Schlüssel möglich"}, {"text": "Ja", "correct": false, "because": "Mehrere Spalten erlaubt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einem Primärschlüssel?', 4, '[{"text": "Identifikation von Kunden", "correct": true, "because": "Eindeutige Kundennummer"}, {"text": "Musikwiedergabe", "correct": false, "because": "Andere Domäne"}, {"text": "Netzwerkkonfiguration", "correct": false, "because": "Technische Aufgabe"}]');

