-- Arbeitsrecht Berufsbildung > Wirtschaftliche Zusammenhänge > Wirtschaftliche Trends > Automatisierung
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Steigert die Automatisierung die Produktivität eines IT-Betriebs?', 2, '[{"text": "Ja", "correct": true, "because": "Automatisierung optimiert Prozesse"}, {"text": "Nein", "correct": false, "because": "Produktivität wird erhöht"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Automatisierung in einem IT-Betrieb Arbeitskosten senken?', 2, '[{"text": "Ja", "correct": true, "because": "Weniger manuelle Arbeit reduziert Kosten"}, {"text": "Nein", "correct": false, "because": "Kostensenkung ist ein Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Erhöht die Automatisierung den Bedarf an qualifizierten IT-Fachkräften?', 2, '[{"text": "Ja", "correct": true, "because": "Automatisierung erfordert technisches Know-how"}, {"text": "Nein", "correct": false, "because": "Fachkräftebedarf steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Führt die Automatisierung in einem IT-Betrieb zu einem Verlust von Arbeitsplätzen?', 2, '[{"text": "Ja", "correct": true, "because": "Manuelle Tätigkeiten werden ersetzt"}, {"text": "Nein", "correct": false, "because": "Arbeitsplatzverlust ist möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Automatisierung die Qualität von IT-Dienstleistungen verbessern?', 2, '[{"text": "Ja", "correct": true, "because": "Automatisierung reduziert Fehler"}, {"text": "Nein", "correct": false, "because": "Qualität kann steigen"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Effekt der Automatisierung ist für einen IT-Betrieb am bedeutendsten?', 2, '[{"text": "Erhöhte Effizienz", "correct": true, "because": "Automatisierung optimiert Prozesse"}, {"text": "Höhere Fehlerquote", "correct": false, "because": "Fehlerquote sinkt"}, {"text": "Geringere Produktivität", "correct": false, "because": "Produktivität steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil ergibt sich durch Automatisierung für einen IT-Betrieb?', 3, '[{"text": "Kostensenkung", "correct": true, "because": "Weniger Arbeitsaufwand reduziert Kosten"}, {"text": "Erhöhte Arbeitsplatzsicherheit", "correct": false, "because": "Arbeitsplätze können wegfallen"}, {"text": "Komplexere Prozesse", "correct": false, "because": "Prozesse werden vereinfacht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Nachteil kann durch Automatisierung in einem IT-Betrieb entstehen?', 3, '[{"text": "Verlust von Arbeitsplätzen", "correct": true, "because": "Manuelle Jobs werden ersetzt"}, {"text": "Geringere Qualität", "correct": false, "because": "Qualität kann steigen"}, {"text": "Niedrigere Kosten", "correct": false, "because": "Kosten sind ein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie treibt die Automatisierung in einem IT-Betrieb voran?', 2, '[{"text": "Künstliche Intelligenz", "correct": true, "because": "KI automatisiert komplexe Aufgaben"}, {"text": "Manuelle Eingaben", "correct": false, "because": "Keine Automatisierungstechnologie"}, {"text": "Papierbasierte Prozesse", "correct": false, "because": "Verhindert Automatisierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderung bringt die Automatisierung für einen IT-Betrieb?', 3, '[{"text": "Hohe Anfangsinvestitionen", "correct": true, "because": "Technologie kostet initial viel"}, {"text": "Geringerer Fachkräftebedarf", "correct": false, "because": "Fachkräftebedarf steigt"}, {"text": "Langsamere Prozesse", "correct": false, "because": "Prozesse werden schneller"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Automatisierung einem IT-Betrieb?', 4, '[{"text": "Erhöhte Effizienz", "correct": true, "because": "Prozesse werden optimiert"}, {"text": "Kostensenkung", "correct": true, "because": "Weniger Arbeitsaufwand"}, {"text": "Geringere Qualität", "correct": false, "because": "Qualität kann steigen"}, {"text": "Schnellere Prozesse", "correct": true, "because": "Automatisierung beschleunigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile bringt die Automatisierung einem IT-Betrieb?', 3, '[{"text": "Hohe Anfangsinvestitionen", "correct": true, "because": "Technologie kostet initial viel"}, {"text": "Verlust von Arbeitsplätzen", "correct": true, "because": "Manuelle Jobs weg"}, {"text": "Geringere Produktivität", "correct": false, "because": "Produktivität steigt"}, {"text": "Erhöhter Wartungsaufwand", "correct": true, "because": "Systeme benötigen Pflege"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Effekte hat die Automatisierung auf die Arbeitsweise eines IT-Betriebs?', 4, '[{"text": "Reduzierte Fehlerquote", "correct": true, "because": "Automatisierung minimiert Fehler"}, {"text": "Erhöhter Bedarf an IT-Fachkräften", "correct": true, "because": "Technik erfordert Expertise"}, {"text": "Langsamere Prozesse", "correct": false, "because": "Prozesse werden schneller"}, {"text": "Kostensenkung durch Effizienz", "correct": true, "because": "Effizienz senkt Kosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien fördern die Automatisierung in einem IT-Betrieb?', 3, '[{"text": "Künstliche Intelligenz", "correct": true, "because": "KI automatisiert Aufgaben"}, {"text": "Robotertechnik", "correct": true, "because": "Roboter übernehmen physische Aufgaben"}, {"text": "Manuelle Prozesse", "correct": false, "because": "Keine Automatisierung"}, {"text": "Cloud Computing", "correct": true, "because": "Cloud erleichtert Automatisierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was unterscheidet die Automatisierungseffekte in einem IT-Betrieb von denen in einem Produktionsbetrieb?', 3, '[{"text": "IT nutzt Softwarelösungen stärker", "correct": true, "because": "Software ist zentral"}, {"text": "Produktion nutzt mehr physische Roboter", "correct": true, "because": "Physische Automatisierung"}, {"text": "IT hat geringere Kosten", "correct": false, "because": "Kosten variieren"}, {"text": "IT hat höheren Fachkräftebedarf", "correct": true, "because": "Technisches Know-how nötig"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Automatisierung steigert die Produktivität eines IT-Betriebs. b) Automatisierung erhöht die Fehlerquote.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Produktivität ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Automatisierung senkt die Kosten eines IT-Betriebs. b) Automatisierung erhöht den Bedarf an IT-Fachkräften.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Kostensenkung und Fachkräftebedarf"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Automatisierung kann Arbeitsplätze in einem IT-Betrieb ersetzen. b) Automatisierung führt zu geringerer Qualität.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Arbeitsplätze ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Automatisierung erfordert hohe Anfangsinvestitionen in einem IT-Betrieb. b) Automatisierung verbessert die Qualität von Dienstleistungen.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "Investitionen und Qualität stimmen"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Automatisierung nutzt KI zur Prozessoptimierung in einem IT-Betrieb. b) Automatisierung hat keine Nachteile für einen IT-Betrieb.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "KI ja, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

