-- Arbeitsrecht Berufsbildung > Betriebswirtschaftliche Grundlagen > Kostenrechnung > Fixkosten
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind Mietkosten für ein Büro in einem IT-Betrieb Fixkosten?', 2, '[{"text": "Ja", "correct": true, "because": "Mietkosten bleiben unabhängig von der Produktion konstant"}, {"text": "Nein", "correct": false, "because": "Mietkosten sind typische Fixkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Fixkosten in einem IT-Betrieb je nach Projektanzahl variieren?', 2, '[{"text": "Nein", "correct": true, "because": "Fixkosten sind unabhängig von der Produktionsmenge"}, {"text": "Ja", "correct": false, "because": "Fixkosten ändern sich nicht mit der Projektanzahl"}]'),
('00000000-0000-0000-0000-000000000000', 'Zählen die Gehälter eines fest angestellten Fachinformatikers zu den Fixkosten?', 2, '[{"text": "Ja", "correct": true, "because": "Feste Gehälter sind unabhängig von der Projektanzahl konstant"}, {"text": "Nein", "correct": false, "because": "Feste Gehälter sind Fixkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Abschreibungen auf Server in einem IT-Betrieb Fixkosten?', 2, '[{"text": "Ja", "correct": true, "because": "Abschreibungen sind feste, planmäßige Kosten"}, {"text": "Nein", "correct": false, "because": "Abschreibungen sind Fixkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Fixkosten eines IT-Betriebs im Laufe der Zeit steigen?', 2, '[{"text": "Ja", "correct": true, "because": "Fixkosten wie Miete können durch Vertragsänderungen steigen"}, {"text": "Nein", "correct": false, "because": "Fixkosten können sich über die Zeit ändern"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Kosten sind typische Fixkosten in einem IT-Betrieb?', 2, '[{"text": "Mietkosten für Büroräume", "correct": true, "because": "Mietkosten sind konstant"}, {"text": "Kosten für Projektmaterial", "correct": false, "because": "Das sind variable Kosten"}, {"text": "Stromkosten für Projekte", "correct": false, "because": "Das sind variable Kosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie werden Fixkosten in einem IT-Betrieb charakterisiert?', 3, '[{"text": "Sie bleiben unabhängig von der Produktionsmenge konstant", "correct": true, "because": "Definition von Fixkosten"}, {"text": "Sie variieren mit der Projektanzahl", "correct": false, "because": "Das sind variable Kosten"}, {"text": "Sie sind nur kurzfristig konstant", "correct": false, "because": "Fixkosten sind langfristig konstant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kostenart gehört nicht zu den Fixkosten eines IT-Betriebs?', 3, '[{"text": "Kosten für Projektmaterial", "correct": true, "because": "Das sind variable Kosten"}, {"text": "Abschreibungen auf Server", "correct": false, "because": "Fixkosten"}, {"text": "Mietkosten für Büroräume", "correct": false, "because": "Fixkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aussage beschreibt Fixkosten in einem IT-Betrieb am besten?', 2, '[{"text": "Kosten, die unabhängig von der Produktion anfallen", "correct": true, "because": "Definition von Fixkosten"}, {"text": "Kosten, die nur bei Projekten entstehen", "correct": false, "because": "Das sind variable Kosten"}, {"text": "Kosten, die direkt verteilt werden", "correct": false, "because": "Das sind Einzelkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein IT-Betrieb die Fixkosten nicht deckt?', 3, '[{"text": "Der Betrieb macht Verluste", "correct": true, "because": "Fixkosten müssen gedeckt werden"}, {"text": "Die Fixkosten verschwinden", "correct": false, "because": "Kosten bleiben bestehen"}, {"text": "Die Projekte werden profitabler", "correct": false, "because": "Umsatz deckt Fixkosten nicht"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Kosten sind Beispiele für Fixkosten in einem IT-Betrieb?', 4, '[{"text": "Mietkosten für Büroräume", "correct": true, "because": "Konstant unabhängig von Produktion"}, {"text": "Abschreibungen auf Server", "correct": true, "because": "Planmäßige feste Kosten"}, {"text": "Kosten für Projektmaterial", "correct": false, "because": "Variable Kosten"}, {"text": "Gehälter fest angestellter Mitarbeiter", "correct": true, "because": "Konstant unabhängig von Projekten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale haben Fixkosten in einem IT-Betrieb?', 3, '[{"text": "Unabhängig von der Produktionsmenge", "correct": true, "because": "Definition von Fixkosten"}, {"text": "Konstant über einen bestimmten Zeitraum", "correct": true, "because": "Fixkosten ändern sich nicht kurzfristig"}, {"text": "Variieren mit der Projektanzahl", "correct": false, "because": "Das sind variable Kosten"}, {"text": "Können langfristig steigen", "correct": true, "because": "Beispiel Mietsteigerung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kostenarten gehören nicht zu den Fixkosten eines IT-Betriebs?', 3, '[{"text": "Kosten für Projekt-Hardware", "correct": true, "because": "Variable Kosten"}, {"text": "Stromkosten für Server", "correct": true, "because": "Variable Kosten"}, {"text": "Mietkosten für Serverräume", "correct": false, "because": "Fixkosten"}, {"text": "Gehälter der Verwaltung", "correct": false, "because": "Fixkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aussagen treffen auf Fixkosten eines IT-Betriebs zu?', 4, '[{"text": "Sie fallen unabhängig von Projekten an", "correct": true, "because": "Definition von Fixkosten"}, {"text": "Sie können Mietkosten umfassen", "correct": true, "because": "Miete ist Fixkosten"}, {"text": "Sie variieren mit der Produktion", "correct": false, "because": "Das sind variable Kosten"}, {"text": "Sie umfassen Abschreibungen", "correct": true, "because": "Abschreibungen sind Fixkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was unterscheidet Fixkosten von variablen Kosten in einem IT-Betrieb?', 3, '[{"text": "Fixkosten sind unabhängig von der Produktion", "correct": true, "because": "Definition von Fixkosten"}, {"text": "Variable Kosten ändern sich mit der Produktion", "correct": true, "because": "Definition von variablen Kosten"}, {"text": "Fixkosten sind immer projektbezogen", "correct": false, "because": "Fixkosten sind nicht projektbezogen"}, {"text": "Variable Kosten sind konstant", "correct": false, "because": "Variable Kosten variieren"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Mietkosten sind Fixkosten eines IT-Betriebs. b) Kosten für Projektmaterial sind Fixkosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Mietkosten ja, Projektmaterial nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Fixkosten bleiben konstant unabhängig von Projekten. b) Gehälter für Projektteams sind Fixkosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Fixkosten konstant, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Abschreibungen auf Server sind Fixkosten. b) Stromkosten für Projekte sind Fixkosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Abschreibungen ja, Stromkosten nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Fixkosten können langfristig steigen. b) Sie sind immer projektabhängig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Langfristig steigen möglich, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Feste Gehälter sind Fixkosten in einem IT-Betrieb. b) Fixkosten variieren mit der Produktionsmenge.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Gehälter Fixkosten, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');