-- Ja/Nein-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Werden Zuschlagssätze in der Kostenrechnung verwendet, um Gemeinkosten auf Einzelkosten zu verteilen?', 2, '[{"text": "Ja", "correct": true, "because": "Zuschlagssätze dienen der Verteilung von Gemeinkosten"}, {"text": "Nein", "correct": false, "because": "Verteilung ist Zweck der Zuschlagssätze"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Zuschlagssätze in einem IT-Betrieb auch für Materialkosten verwendet werden?', 2, '[{"text": "Ja", "correct": true, "because": "Materialgemeinkosten können zugeschlagen werden"}, {"text": "Nein", "correct": false, "because": "Materialkosten können einbezogen werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Zuschlagssätze immer in Prozent angegeben werden?', 2, '[{"text": "Ja", "correct": true, "because": "Übliche Praxis in der Kostenrechnung"}, {"text": "Nein", "correct": false, "because": "Prozent ist Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein zu hoher Zuschlagssatz die Wettbewerbsfähigkeit eines Unternehmens beeinträchtigen?', 2, '[{"text": "Ja", "correct": true, "because": "Höhere Kosten können Preise erhöhen"}, {"text": "Nein", "correct": false, "because": "Wettbewerbsfähigkeit wird beeinflusst"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Zuschlagssätze in der Kostenrechnung fix und unveränderlich?', 2, '[{"text": "Ja", "correct": false, "because": "Sie können angepasst werden"}, {"text": "Nein", "correct": true, "because": "Flexibilität ist gegeben"}]');

-- Single-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was ist die Hauptfunktion von Zuschlagssätzen in der Kostenrechnung?', 2, '[{"text": "Verteilung von Gemeinkosten", "correct": true, "because": "Primäre Aufgabe"}, {"text": "Berechnung der Fixkosten", "correct": false, "because": "Zu spezifisch"}, {"text": "Festlegung der Verkaufspreise", "correct": false, "because": "Indirekte Folge"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kostenart wird typischerweise mit Zuschlagssätzen auf Einzelkosten verteilt?', 3, '[{"text": "Gemeinkosten", "correct": true, "because": "Zuschlagssätze dienen dazu"}, {"text": "Variable Kosten", "correct": false, "because": "Direkt zurechenbar"}, {"text": "Einzelkosten", "correct": false, "because": "Bereits direkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie wird ein Zuschlagssatz üblicherweise angegeben?', 2, '[{"text": "In Prozent", "correct": true, "because": "Standard in der Kostenrechnung"}, {"text": "In Euro", "correct": false, "because": "Nicht üblich"}, {"text": "In Stunden", "correct": false, "because": "Falsche Einheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Zuschlagssatz zu niedrig angesetzt wird?', 3, '[{"text": "Gemeinkosten werden nicht vollständig gedeckt", "correct": true, "because": "Unterdeckung entsteht"}, {"text": "Einzelkosten steigen", "correct": false, "because": "Kein direkter Einfluss"}, {"text": "Fixkosten sinken", "correct": false, "because": "Keine Verbindung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Basis wird oft für die Berechnung eines Zuschlagssatzes herangezogen?', 2, '[{"text": "Einzelkosten", "correct": true, "because": "Gemeinkosten werden darauf verteilt"}, {"text": "Gesamtkosten", "correct": false, "because": "Zu allgemein"}, {"text": "Umsatz", "correct": false, "because": "Nicht üblich"}]');

-- Multiple-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welche Kostenarten können mit Zuschlagssätzen verteilt werden?', 4, '[{"text": "Fertigungs-Gemeinkosten", "correct": true, "because": "Typische Anwendung"}, {"text": "Material-Gemeinkosten", "correct": true, "because": "Ebenfalls verteilbar"}, {"text": "Einzelkosten", "correct": false, "because": "Direkt zurechenbar"}, {"text": "Verwaltungs-Gemeinkosten", "correct": true, "because": "Auch diese werden zugeschlagen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Höhe eines Zuschlagssatzes?', 3, '[{"text": "Höhe der Gemeinkosten", "correct": true, "because": "Direkter Einfluss"}, {"text": "Einzelkostenbasis", "correct": true, "because": "Verteilungsgrundlage"}, {"text": "Wettbewerbsfähigkeit", "correct": false, "because": "Indirekter Effekt"}, {"text": "Betriebsgröße", "correct": true, "because": "Kann Kostenstruktur beeinflussen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folgen kann ein falsch angesetzter Zuschlagssatz haben?', 4, '[{"text": "Überdeckung der Gemeinkosten", "correct": true, "because": "Bei zu hohem Satz"}, {"text": "Unterdeckung der Gemeinkosten", "correct": true, "because": "Bei zu niedrigem Satz"}, {"text": "Senkung der Einzelkosten", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Verfälschte Produktkalkulation", "correct": true, "because": "Kosten werden falsch zugeteilt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Nutzung von Zuschlagssätzen?', 3, '[{"text": "Einfache Verteilung von Gemeinkosten", "correct": true, "because": "Praktikabel"}, {"text": "Genauere Kostenzuordnung", "correct": true, "because": "Verteilt indirekte Kosten"}, {"text": "Senkung der Fixkosten", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Transparenz in der Kalkulation", "correct": true, "because": "Klarheit über Kosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sind bei der Berechnung eines Zuschlagssatzes nötig?', 3, '[{"text": "Ermittlung der Gemeinkosten", "correct": true, "because": "Ausgangspunkt"}, {"text": "Festlegung der Bezugsgröße", "correct": true, "because": "Einzelkosten als Basis"}, {"text": "Berechnung der Verkaufspreise", "correct": false, "because": "Folgeschritt"}, {"text": "Prozentuale Verteilung", "correct": true, "because": "Ergebnis der Berechnung"}]');

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Zuschlagssätze verteilen Gemeinkosten auf Einzelkosten. b) Sie werden nie in Prozent angegeben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (Prozent üblich)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Zu hohe Zuschlagssätze erhöhen die Produktkosten. b) Zuschlagssätze betreffen nur Fixkosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (auch variable Kosten)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Zuschlagssätze können angepasst werden. b) Sie dienen nur der Materialkostenverteilung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (Gemeinkosten)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Zuschlagssätze verbessern die Kostenkalkulation. b) Sie sind unabhängig von der Einzelkostenbasis.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (Basis erforderlich)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Falsche Zuschlagssätze verfälschen die Kalkulation. b) Sie sind ein Werkzeug der Kostenrechnung.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "a) Verfälschung möglich, b) Kostenrechnung"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]');

