INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist ein SOA-Eintrag zwingend erforderlich, um eine DNS-Zone einzurichten?', 2, '[{"text": "Ja", "correct": true, "because": "Start of Authority definiert die Zone"}, {"text": "Nein", "correct": false, "because": "SOA ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein DNS-Server sowohl autoritative als auch rekursive Namensauflösung durchführen?', 2, '[{"text": "Ja", "correct": true, "because": "Server kann beide Rollen übernehmen"}, {"text": "Nein", "correct": false, "because": "Kombination ist möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Zoneneinträge regelmäßig aktualisiert werden, um gültig zu bleiben?', 2, '[{"text": "Nein", "correct": true, "because": "Nur bei Änderungen nötig, TTL regelt Gültigkeit"}, {"text": "Ja", "correct": false, "because": "Keine ständige Aktualisierung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein CNAME-Eintrag auf eine Adresse außerhalb der eigenen Zone verweisen?', 2, '[{"text": "Ja", "correct": true, "because": "CNAME kann auf externe Domains zeigen"}, {"text": "Nein", "correct": false, "because": "Externe Verweise sind erlaubt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Namensauflösung eines DNS-Servers auf UDP-Port 53 beschränkt?', 2, '[{"text": "Nein", "correct": true, "because": "TCP wird für größere Antworten genutzt"}, {"text": "Ja", "correct": false, "because": "TCP ist ebenfalls möglich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Zoneneintrag ist für die Reverse-Namensauflösung (IP zu Name) zuständig?', 2, '[{"text": "PTR", "correct": true, "because": "Pointer-Eintrag für Reverse-DNS"}, {"text": "A", "correct": false, "because": "Für IPv4-Namensauflösung"}, {"text": "MX", "correct": false, "because": "Für Mailserver"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Schritt ist der erste bei der rekursiven Namensauflösung eines DNS-Servers?', 3, '[{"text": "Prüfung des lokalen Caches", "correct": true, "because": "Cache wird zuerst abgefragt"}, {"text": "Anfrage an Root-Server", "correct": false, "because": "Erst nach Cache-Miss"}, {"text": "Direkte Antwort an Client", "correct": false, "because": "Nur bei Cache-Treffer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Eintrag definiert den primären Nameserver einer Zone?', 2, '[{"text": "NS", "correct": true, "because": "Nameserver-Eintrag zeigt zuständigen Server"}, {"text": "SOA", "correct": false, "because": "Definiert Zone, nicht primär"}, {"text": "A", "correct": false, "because": "Für IP-Adressen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche TTL-Einstellung ist typisch für einen Zoneneintrag, der selten geändert wird?', 2, '[{"text": "86400 Sekunden (1 Tag)", "correct": true, "because": "Geeignet für stabile Einträge"}, {"text": "300 Sekunden (5 Minuten)", "correct": false, "because": "Für häufige Änderungen"}, {"text": "60 Sekunden (1 Minute)", "correct": false, "because": "Zu kurz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher DNS-Eintrag wird verwendet, um mehrere Mailserver mit Priorität zu definieren?', 2, '[{"text": "MX", "correct": true, "because": "Mail Exchange mit Prioritätswert"}, {"text": "CNAME", "correct": false, "because": "Für Aliase"}, {"text": "AAAA", "correct": false, "because": "Für IPv6-Adressen"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Zoneneinträge sind für die Namensauflösung eines Web-Servers erforderlich?', 4, '[{"text": "A", "correct": true, "because": "Für IPv4-Adresse"}, {"text": "AAAA", "correct": true, "because": "Für IPv6-Adresse"}, {"text": "NS", "correct": true, "because": "Nameserver der Zone"}, {"text": "TXT", "correct": false, "because": "Für Textinformationen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind bei der rekursiven Namensauflösung beteiligt?', 3, '[{"text": "Lokaler Resolver", "correct": true, "because": "Startet die Abfrage"}, {"text": "Root-Server", "correct": true, "because": "Erste Stufe bei unbekannten Domains"}, {"text": "TLD-Server", "correct": true, "because": "Top-Level-Domain-Server"}, {"text": "DHCP-Server", "correct": false, "because": "Für IP-Vergabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einträge könnten in einer Zone für ein Unternehmensnetzwerk vorkommen?', 4, '[{"text": "A (IPv4-Adresse)", "correct": true, "because": "Für Server"}, {"text": "MX (Mailserver)", "correct": true, "because": "Für E-Mail"}, {"text": "CNAME (Alias)", "correct": true, "because": "Für Subdomains"}, {"text": "DHCP (Adresszuweisung)", "correct": false, "because": "Kein DNS-Eintrag"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine korrekt konfigurierte Namensauflösung?', 3, '[{"text": "Schneller Zugriff auf Ressourcen", "correct": true, "because": "Effiziente Auflösung"}, {"text": "Verbesserte Sicherheit", "correct": true, "because": "DNSSEC möglich"}, {"text": "Reduzierte Bandbreitennutzung", "correct": true, "because": "Caching"}, {"text": "Erhöhte Hardwarekosten", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einstellungen sollten bei Zoneneinträgen geprüft werden?', 3, '[{"text": "TTL-Wert", "correct": true, "because": "Beeinflusst Gültigkeit"}, {"text": "Nameserver (NS)", "correct": true, "because": "Definiert Zuständigkeit"}, {"text": "IP-Adresse (A/AAAA)", "correct": true, "because": "Für Auflösung"}, {"text": "Router-Gateway", "correct": false, "because": "Nicht Teil der Zone"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ein PTR-Eintrag ist für Reverse-DNS nötig. b) Ein SOA-Eintrag ist optional für eine Zone.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "PTR ja, SOA zwingend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein CNAME kann auf eine externe Domain verweisen. b) Die Namensauflösung ist immer auf UDP beschränkt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "CNAME ja, TCP auch möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein MX-Eintrag definiert Mailserver mit Priorität. b) Ein A-Eintrag ist für IPv6-Adressen gedacht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "MX ja, A für IPv4"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) NS-Einträge sind für die Namensauflösung einer Zone essenziell. b) Zoneneinträge verlieren automatisch ihre Gültigkeit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "NS ja, Gültigkeit via TTL"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein DNS-Server prüft zuerst den Cache bei der Namensauflösung. b) Ein TTL von 86400 Sekunden ist für häufige Änderungen geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Cache ja, 86400 für stabile Einträge"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

