INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist DHCPv6 notwendig, um IPv6-Adressen in einem Netzwerk zuzuweisen?', 2, '[{"text": "Nein", "correct": true, "because": "SLAAC kann auch Adressen zuweisen"}, {"text": "Ja", "correct": false, "because": "DHCPv6 ist optional"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann DHCPv6 zusätzliche Informationen wie DNS-Server-Adressen bereitstellen?', 2, '[{"text": "Ja", "correct": true, "because": "DHCPv6 liefert DNS- und andere Optionen"}, {"text": "Nein", "correct": false, "because": "DNS-Zuweisung ist möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein DHCPv6-Server im selben Subnetz wie die Clients sein?', 2, '[{"text": "Nein", "correct": true, "because": "Relay Agents können Anfragen weiterleiten"}, {"text": "Ja", "correct": false, "because": "Relay Agents ermöglichen Flexibilität"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist DHCPv6 stateful, im Gegensatz zu SLAAC?', 2, '[{"text": "Ja", "correct": true, "because": "DHCPv6 speichert Zustände, SLAAC nicht"}, {"text": "Nein", "correct": false, "because": "Stateful ist Hauptmerkmal"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann DHCPv6 mit SLAAC in einem Netzwerk kombiniert werden?', 2, '[{"text": "Ja", "correct": true, "because": "SLAAC für Adressen, DHCPv6 für Optionen"}, {"text": "Nein", "correct": false, "because": "Kombination ist üblich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Port wird von DHCPv6-Clients verwendet, um Anfragen an den Server zu senden?', 2, '[{"text": "546", "correct": true, "because": "UDP-Port 546 ist für DHCPv6-Clients"}, {"text": "547", "correct": false, "because": "Port 547 ist für Server"}, {"text": "67", "correct": false, "because": "Für IPv4-DHCP"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist der Hauptvorteil von DHCPv6 gegenüber SLAAC bei der IPv6-Adresszuweisung?', 3, '[{"text": "Zentrale Verwaltung", "correct": true, "because": "DHCPv6 ermöglicht Kontrolle"}, {"text": "Schnellere Zuweisung", "correct": false, "because": "SLAAC ist schneller"}, {"text": "Einfachere Einrichtung", "correct": false, "because": "SLAAC ist einfacher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Adresse wird von DHCPv6-Servern verwendet, um Anfragen von Relay Agents zu empfangen?', 2, '[{"text": "FF02::1:2", "correct": true, "because": "Link-Local Multicast für DHCPv6"}, {"text": "FF00::1", "correct": false, "because": "Allgemeiner Multicast"}, {"text": "FE80::1", "correct": false, "because": "Link-Local Unicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Information wird von DHCPv6 nicht bereitgestellt, im Gegensatz zu IPv4-DHCP?', 2, '[{"text": "Standard-Gateway", "correct": true, "because": "Gateway via Router Advertisement"}, {"text": "DNS-Server", "correct": false, "because": "DHCPv6 liefert DNS"}, {"text": "Subnetzmaske", "correct": false, "because": "Präfixlänge ersetzt Maske"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Schritt ist bei der DHCPv6-Einrichtung entscheidend, um Adressen zuzuweisen?', 2, '[{"text": "Adresspool definieren", "correct": true, "because": "Legt verfügbare Adressen fest"}, {"text": "Kanalwahl", "correct": false, "because": "Für WLAN, nicht DHCPv6"}, {"text": "VLAN konfigurieren", "correct": false, "because": "Switch-Funktion"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Informationen kann ein DHCPv6-Server bereitstellen?', 4, '[{"text": "IPv6-Adressen", "correct": true, "because": "Hauptfunktion"}, {"text": "DNS-Server-Adressen", "correct": true, "because": "Zusätzliche Option"}, {"text": "Netzwerkpräfix", "correct": true, "because": "Definiert Subnetz"}, {"text": "MAC-Adressen", "correct": false, "because": "Client-seitig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sind bei der Einrichtung eines DHCPv6-Servers erforderlich?', 3, '[{"text": "Adresspool festlegen", "correct": true, "because": "Definiert verfügbare Adressen"}, {"text": "Server aktivieren", "correct": true, "because": "Startet DHCPv6-Dienst"}, {"text": "Relay Agent konfigurieren", "correct": true, "because": "Für andere Subnetze"}, {"text": "Kanalwahl festlegen", "correct": false, "because": "Für WLAN"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Unterschiede gibt es zwischen DHCPv6 und IPv4-DHCP?', 4, '[{"text": "128-Bit-Adressen", "correct": true, "because": "IPv6-Adressen"}, {"text": "Kein Standard-Gateway", "correct": true, "because": "Via RA geliefert"}, {"text": "UDP-Ports 546/547", "correct": true, "because": "Anders als 67/68"}, {"text": "Schnellere Zuweisung", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet DHCPv6 bei der Netzwerkeinrichtung?', 3, '[{"text": "Zentrale Adressverwaltung", "correct": true, "because": "Stateful Kontrolle"}, {"text": "DNS-Konfiguration", "correct": true, "because": "Liefert DNS-Server"}, {"text": "Automatische Subnetztrennung", "correct": false, "because": "Nicht Funktion von DHCPv6"}, {"text": "Erweiterte Optionen", "correct": true, "because": "z. B. NTP"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind bei der DHCPv6-Einrichtung beteiligt?', 3, '[{"text": "DHCPv6-Server", "correct": true, "because": "Vergibt Adressen"}, {"text": "DHCPv6-Client", "correct": true, "because": "Empfängt Konfiguration"}, {"text": "Relay Agent", "correct": true, "because": "Leitet Anfragen"}, {"text": "Koaxialkabel", "correct": false, "because": "Nicht relevant"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) DHCPv6 kann DNS-Server-Adressen zuweisen. b) DHCPv6 ist für alle IPv6-Netzwerke zwingend erforderlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DNS ja, SLAAC Alternative"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) DHCPv6 verwendet UDP-Port 547 für Server. b) DHCPv6 liefert Standard-Gateway-Adressen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Port 547 ja, Gateway via RA"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) DHCPv6 ist stateful und speichert Zuweisungen. b) SLAAC und DHCPv6 sind identisch.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Stateful ja, SLAAC stateless"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Ein DHCPv6-Relay Agent ermöglicht die Nutzung über Subnetze hinweg. b) DHCPv6-Adresspools müssen manuell definiert werden.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Relay ja, Pool-Definition nötig"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) DHCPv6 kann mit SLAAC kombiniert werden. b) DHCPv6 verwendet dieselben Ports wie IPv4-DHCP.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kombination ja, Ports 546/547 vs. 67/68"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

