-- Softwarekomponenten dokumentieren.sql (Beschreibung der Systemteile, z. B. Architekturübersicht)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist eine Dokumentation von Softwarekomponenten ohne Architekturübersicht vollständig?', 2, '[{"text": "Nein", "correct": true, "because": "Übersicht gibt Kontext"}, {"text": "Ja", "correct": false, "because": "Fehlende Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit der Dokumentation von Softwarekomponenten?', 3, '[{"text": "Wartbarkeit", "correct": true, "because": "Erleichtert Änderungen"}, {"text": "Performance", "correct": false, "because": "Kein direkter Einfluss"}, {"text": "Marketing", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Dokumentation von Softwarekomponenten?', 5, '[{"text": "Architekturübersicht", "correct": true, "because": "Zeigt Struktur"}, {"text": "Komponentenbeschreibung", "correct": true, "because": "Erklärt Funktion"}, {"text": "UI-Design", "correct": false, "because": "Nicht primär"}, {"text": "Hardware-Details", "correct": false, "because": "Kontextabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Komponentendokumentation braucht Abhängigkeiten. b) Sie ist nur für Entwickler.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) auch für Architekten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Dokumentation von Softwarekomponenten?', 4, '[{"text": "Komponenteninteraktion", "correct": false, "because": "Zeigt Zusammenspiel"}, {"text": "Zweck", "correct": false, "because": "Erklärt Nutzen"}, {"text": "Farbschema", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Komponentendokumentation immer detailliert sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "Übersicht kann reichen"}, {"text": "Ja", "correct": false, "because": "Abhängig vom Zweck"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool nutze ich für eine Architekturübersicht?', 3, '[{"text": "UML-Diagramme", "correct": true, "because": "Standard für Struktur"}, {"text": "Word", "correct": false, "because": "Unstrukturiert"}, {"text": "Notepad", "correct": false, "because": "Keine Visualisierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen eine Komponentendokumentation effektiv?', 5, '[{"text": "Klarheit", "correct": true, "because": "Fördert Verständnis"}, {"text": "Abhängigkeiten", "correct": true, "because": "Zeigt Zusammenhänge"}, {"text": "Lange Texte", "correct": false, "because": "Ermüdend"}, {"text": "Hohe Auflösung", "correct": false, "because": "Bildspezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Dokumentation ist nur für große Systeme. b) Kleine Projekte brauchen sie nicht. Stimmt das?', 3, '[{"text": "Beides falsch", "correct": true, "because": "Alle profitieren"}, {"text": "Beides stimmt", "correct": false, "because": "Nicht exklusiv"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Komponentendokumentation?', 4, '[{"text": "Funktionsbeschreibung", "correct": false, "because": "Erklärt Rolle"}, {"text": "Interaktionen", "correct": false, "because": "Zeigt Zusammenspiel"}, {"text": "Monitorgröße", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Komponentendokumentation nur für Wartung?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Entwicklung"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Details sind in einer Architekturübersicht entscheidend?', 4, '[{"text": "Komponenten", "correct": true, "because": "Bausteine des Systems"}, {"text": "Verbindungen", "correct": true, "because": "Zeigt Interaktion"}, {"text": "Code-Zeilen", "correct": false, "because": "Zu spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Dokumentation nur einmal erstellt wird. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Updates nötig"}, {"text": "Ja", "correct": false, "because": "Systeme ändern sich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Komponentendokumentation?', 3, '[{"text": "Struktur", "correct": true, "because": "Gibt Übersicht"}, {"text": "Technische Tiefe", "correct": false, "because": "Nicht immer nötig"}, {"text": "Schnelle Fertigstellung", "correct": false, "because": "Qualität zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Dokumentation braucht Diagramm. b) Text reicht aus.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) oft unzureichend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist schwach"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gute Komponentendokumentation?', 5, '[{"text": "Einfachere Wartung", "correct": true, "because": "Klarheit hilft"}, {"text": "Bessere Zusammenarbeit", "correct": true, "because": "Teamverständnis"}, {"text": "Hohe Kosten", "correct": false, "because": "Kein Vorteil"}, {"text": "Schnelle Entwicklung", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Dokumentation unwichtig?', 3, '[{"text": "Komponentenrolle", "correct": false, "because": "Erklärt Zweck"}, {"text": "Abhängigkeiten", "correct": false, "because": "Zeigt Zusammenhänge"}, {"text": "Schriftfarbe", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzt Dokumentation den Code?', 3, '[{"text": "Nein", "correct": true, "because": "Ergänzt ihn"}, {"text": "Ja", "correct": false, "because": "Code bleibt zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Dokumentation nur für große Teams ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Teams profitieren"}, {"text": "Ja", "correct": false, "because": "Nicht exklusiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature ist für die Dokumentation entscheidend?', 4, '[{"text": "Übersichtlichkeit", "correct": true, "because": "Fördert Verständnis"}, {"text": "Code-Details", "correct": false, "because": "Zu spezifisch"}, {"text": "Statische Daten", "correct": false, "because": "Nicht primär"}]');

