-- Desktopvirtualisierung.sql (VDI, Remote-Desktops)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist VDI dasselbe wie Remote-Desktop?', 2, '[{"text": "Nein", "correct": true, "because": "VDI nutzt VMs, Remote-Desktop oft nicht"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Technologien"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Lösung wähle ich für zentrale Verwaltung?', 3, '[{"text": "VDI", "correct": true, "because": "Zentralisierte Desktops"}, {"text": "Lokale PCs", "correct": false, "because": "Dezentralisiert"}, {"text": "Manuelle Konfiguration", "correct": false, "because": "Zu aufwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen Remote-Desktops für mobile Nutzer geeignet?', 5, '[{"text": "Zugriff von überall", "correct": true, "because": "Netzwerkabhängig"}, {"text": "Geringe Client-Anforderungen", "correct": true, "because": "Server übernimmt Arbeit"}, {"text": "Hohe lokale Leistung", "correct": false, "because": "Nicht nötig"}, {"text": "Kostenfreiheit", "correct": false, "because": "Infrastruktur kostet"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) VDI braucht einen Hypervisor. b) Remote-Desktops sind immer sicher.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Sicherheit hängt ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung von VDI?', 4, '[{"text": "Serverkapazität", "correct": false, "because": "Entscheidend für VMs"}, {"text": "Netzwerkbandbreite", "correct": false, "because": "Wichtig für Zugriff"}, {"text": "Lokale GPU-Leistung", "correct": true, "because": "Serverseitig relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Remote-Desktops ohne Internet laufen?', 2, '[{"text": "Ja", "correct": true, "because": "Lokales Netzwerk reicht"}, {"text": "Nein", "correct": false, "because": "Internet nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature priorisiere ich für VDI in einem Unternehmen?', 3, '[{"text": "Zentrale Verwaltung", "correct": true, "because": "Effizienz und Kontrolle"}, {"text": "Hohe Latenz", "correct": false, "because": "Nicht gewünscht"}, {"text": "Lokale Installation", "correct": false, "because": "Serverbasiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Remote-Desktop?', 5, '[{"text": "Flexibler Zugriff", "correct": true, "because": "Von jedem Gerät möglich"}, {"text": "Geringere Client-Kosten", "correct": true, "because": "Wenig Hardware nötig"}, {"text": "Hohe lokale Leistung", "correct": false, "because": "Serverabhängig"}, {"text": "Einfache Einrichtung", "correct": false, "because": "Komplexe Infrastruktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) VDI ist ressourcenintensiv. b) Remote-Desktops brauchen keine Server. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Server nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Remote-Desktops in einem kleinen Büro?', 4, '[{"text": "Netzwerkverbindung", "correct": false, "because": "Grundvoraussetzung"}, {"text": "Serverinfrastruktur", "correct": false, "because": "Hostet Desktops"}, {"text": "High-End-Workstations", "correct": true, "because": "Clients minimal"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist VDI für Gaming geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Hohe Latenz problematisch"}, {"text": "Ja", "correct": false, "because": "Nicht optimal"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren sind für VDI in einer Schule wichtig?', 4, '[{"text": "Zentrale Updates", "correct": true, "because": "Einheitliche Software"}, {"text": "Skalierbarkeit", "correct": true, "because": "Viele Nutzer"}, {"text": "Lokale Speicherkapazität", "correct": false, "because": "Serverbasiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Remote-Desktops immer langsam sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Hängt von Netzwerk ab"}, {"text": "Ja", "correct": false, "because": "Kann schnell sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich für Remote-Desktops in einem Callcenter?', 3, '[{"text": "Niedrige Latenz", "correct": true, "because": "Echtzeitkommunikation"}, {"text": "Hohe lokale CPU", "correct": false, "because": "Serverseitig"}, {"text": "Maximale Kosten", "correct": false, "because": "Effizienz zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) VDI braucht starke Server. b) Remote-Desktops sind nur für Windows.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, plattformübergreifend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat VDI?', 5, '[{"text": "Hohe Serverkosten", "correct": true, "because": "Starke Hardware nötig"}, {"text": "Netzwerkabhängigkeit", "correct": true, "because": "Ohne Netz nutzlos"}, {"text": "Geringere Latenz", "correct": false, "because": "Nicht garantiert"}, {"text": "Einfache Verwaltung", "correct": false, "because": "Komplexer"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Remote-Desktops für Heimarbeit unwichtig?', 3, '[{"text": "Sicherheitsprotokolle", "correct": false, "because": "Datenschutz nötig"}, {"text": "Netzwerkstabilität", "correct": false, "because": "Zuverlässigkeit wichtig"}, {"text": "Lokale GPU", "correct": true, "because": "Server übernimmt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht VDI die Sicherheit automatisch?', 3, '[{"text": "Nein", "correct": true, "because": "Hängt von Konfiguration ab"}, {"text": "Ja", "correct": false, "because": "Nicht inhärent sicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Remote-Desktops für CAD sinnvoll sind?', 2, '[{"text": "Nein", "correct": true, "because": "Hohe Grafikanforderungen"}, {"text": "Ja", "correct": false, "because": "Latenz problematisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Lösung wähle ich für flexible Arbeitsplätze?', 4, '[{"text": "VDI", "correct": true, "because": "Zentral und skalierbar"}, {"text": "Lokale Workstations", "correct": false, "because": "Weniger flexibel"}, {"text": "Manuelle Updates", "correct": false, "because": "Zu aufwendig"}]');

