-- Pfad: Anwendersupport/IT Sicherheit/Social Engineering

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann Social Engineering im Anwendersupport durch Täuschung sensible Daten erlangen?', 2, '[{"text": "Ja", "correct": true, "because": "Manipulation der Nutzer"}, {"text": "Nein", "correct": false, "because": "Hauptmethode"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Social Engineering im Anwendersupport eine rein technische Bedrohung?', 2, '[{"text": "Nein", "correct": true, "because": "Psychologische Taktiken"}, {"text": "Ja", "correct": false, "because": "Menschlicher Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Schulungen im Anwendersupport Social Engineering vorbeugen?', 2, '[{"text": "Ja", "correct": true, "because": "Sensibilisierung hilft"}, {"text": "Nein", "correct": false, "because": "Präventionsmaßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Phishing eine Form von Social Engineering im Anwendersupport?', 2, '[{"text": "Ja", "correct": true, "because": "Täuschung per E-Mail"}, {"text": "Nein", "correct": false, "because": "Klassisches Beispiel"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Social Engineering im Anwendersupport unbefugte Zugriffe ermöglichen?', 2, '[{"text": "Ja", "correct": true, "because": "Daten durch Manipulation"}, {"text": "Nein", "correct": false, "because": "Häufige Folge"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methode ist ein Beispiel für Social Engineering im Anwendersupport?', 2, '[{"text": "Phishing", "correct": true, "because": "Täuschung der Nutzer"}, {"text": "DDoS-Angriff", "correct": false, "because": "Technischer Angriff"}, {"text": "SQL-Injection", "correct": false, "because": "Datenbankangriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel von Social Engineering im Anwendersupport?', 3, '[{"text": "Datenbeschaffung", "correct": true, "because": "Sensible Informationen"}, {"text": "Systemüberlastung", "correct": false, "because": "Technisches Ziel"}, {"text": "Hardwarezerstörung", "correct": false, "because": "Physisches Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme schützt im Anwendersupport am besten vor Social Engineering?', 2, '[{"text": "Mitarbeiterschulung", "correct": true, "because": "Bewusstsein schaffen"}, {"text": "Firewall", "correct": false, "because": "Technischer Schutz"}, {"text": "Antivirus", "correct": false, "because": "Malwareschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Taktik nutzt Social Engineering im Anwendersupport häufig?', 2, '[{"text": "Vertrauen ausnutzen", "correct": true, "because": "Psychologische Manipulation"}, {"text": "Codeverschlüsselung", "correct": false, "because": "Technische Methode"}, {"text": "Datenkompression", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folge hat Social Engineering im Anwendersupport?', 2, '[{"text": "Identitätsdiebstahl", "correct": true, "because": "Missbrauch von Daten"}, {"text": "Systemabsturz", "correct": false, "because": "Technisches Problem"}, {"text": "Datenkorruption", "correct": false, "because": "Integritätsproblem"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Techniken gehören zu Social Engineering im Anwendersupport?', 3, '[{"text": "Phishing", "correct": true, "because": "Täuschende E-Mails"}, {"text": "Pretexting", "correct": true, "because": "Falsche Identität"}, {"text": "Baiting", "correct": true, "because": "Köder nutzen"}, {"text": "SQL-Injection", "correct": false, "because": "Technischer Angriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folgen kann Social Engineering im Anwendersupport haben?', 4, '[{"text": "Datenverlust", "correct": true, "because": "Sensible Daten entwendet"}, {"text": "Unbefugter Zugriff", "correct": true, "because": "Systemeingang"}, {"text": "Vertrauensverlust", "correct": true, "because": "Reputation geschädigt"}, {"text": "Hardwareausfall", "correct": false, "because": "Technisches Problem"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schutzmaßnahmen helfen gegen Social Engineering im Anwendersupport?', 3, '[{"text": "Schulungen", "correct": true, "because": "Sensibilisierung"}, {"text": "Zwei-Faktor-Authentifizierung", "correct": true, "because": "Zusätzliche Sicherheit"}, {"text": "Richtlinien", "correct": true, "because": "Verhaltensvorgaben"}, {"text": "Serverwartung", "correct": false, "because": "Technische Maßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Angriffsvektoren nutzt Social Engineering im Anwendersupport?', 4, '[{"text": "E-Mails", "correct": true, "because": "Phishing-Angriffe"}, {"text": "Telefonanrufe", "correct": true, "because": "Vishing"}, {"text": "USB-Sticks", "correct": true, "because": "Baiting"}, {"text": "Systemupdates", "correct": false, "because": "Technische Maßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schwächen nutzt Social Engineering im Anwendersupport aus?', 3, '[{"text": "Vertrauen", "correct": true, "because": "Menschliche Naivität"}, {"text": "Unwissenheit", "correct": true, "because": "Fehlendes Bewusstsein"}, {"text": "Neugier", "correct": true, "because": "Köder locken"}, {"text": "Hardwareleistung", "correct": false, "because": "Technischer Aspekt"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Phishing ist eine Form von Social Engineering im Anwendersupport. b) Social Engineering ist nur ein Softwareproblem.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Phishing ja, menschlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Social Engineering nutzt psychologische Manipulation im Anwendersupport. b) Technische Schutzmaßnahmen reichen zur Abwehr aus.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Manipulation ja, Schulung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Schulungen können Social Engineering im Anwendersupport vorbeugen. b) Social Engineering betrifft nur technische Systeme.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schulung ja, menschlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Social Engineering kann Identitätsdiebstahl im Anwendersupport verursachen. b) Firewall schützt vollständig vor Social Engineering.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Identität ja, Firewall unzureichend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Pretexting ist eine Technik von Social Engineering im Anwendersupport. b) Social Engineering ist immer leicht erkennbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Pretexting ja, oft subtil"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

