-- questions.sql (Fat Clients - Leistungsstarke lokale Computer, z. B. für Systemintegration)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Fat Client dasselbe wie ein Thin Client?', 2, '[{"text": "Nein", "correct": true, "because": "Lokale vs. Server-Verarbeitung"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Konzepte"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt ein Fat Client?', 3, '[{"text": "Lokale Datenverarbeitung", "correct": true, "because": "Selbstständige Leistung"}, {"text": "Nur Serverzugriff", "correct": false, "because": "Thin Client"}, {"text": "Netzwerksicherheit", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat ein Fat Client?', 5, '[{"text": "Hohe Rechenleistung", "correct": true, "because": "Lokale Verarbeitung"}, {"text": "Großer Speicher", "correct": true, "because": "Daten lokal"}, {"text": "Minimale Hardware", "correct": false, "because": "Thin Client"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Fat Clients führen Aufgaben lokal aus. b) Sie sind komplett serverabhängig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wenig Serverabhängigkeit"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Fat Client?', 4, '[{"text": "Rechenleistung", "correct": false, "because": "Kernmerkmal"}, {"text": "Softwareinstallation", "correct": false, "because": "Lokal nötig"}, {"text": "Papierformat", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Fat Client immer eine Netzwerkverbindung braucht?', 2, '[{"text": "Nein", "correct": true, "because": "Kann offline arbeiten"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Hardware ist für einen Fat Client typisch?', 3, '[{"text": "Leistungsstarke CPU", "correct": true, "because": "Lokale Verarbeitung"}, {"text": "Minimaler RAM", "correct": false, "because": "Hoher Bedarf"}, {"text": "Papierdrucker", "correct": false, "because": "Keine Hardware"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Fat Client?', 5, '[{"text": "Hohe Leistung", "correct": true, "because": "Lokale Ressourcen"}, {"text": "Offline-Funktionalität", "correct": true, "because": "Unabhängigkeit"}, {"text": "Geringer Speicherbedarf", "correct": false, "because": "Hoher Bedarf"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Fat Clients sind leistungsstark. b) Sie sind immer serverabhängig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wenig Servernutzung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen Fat Client?', 4, '[{"text": "Leistungsstarke Hardware", "correct": false, "because": "Lokale Verarbeitung"}, {"text": "Software", "correct": false, "because": "Lokal installiert"}, {"text": "Externer Server", "correct": true, "because": "Unabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Fat Client immer teurer als ein Thin Client?', 2, '[{"text": "Ja", "correct": true, "because": "Mehr Hardware nötig"}, {"text": "Nein", "correct": false, "because": "Kosten variabel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen sind typisch für Fat Clients?', 4, '[{"text": "Grafikdesign", "correct": true, "because": "Hohe Leistung"}, {"text": "Spiele", "correct": true, "because": "Lokale Verarbeitung"}, {"text": "Terminaldienste", "correct": false, "because": "Thin Client"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Fat Clients keine Netzwerkverbindung brauchen. Stimmt das?', 2, '[{"text": "Ja", "correct": true, "because": "Kann offline laufen"}, {"text": "Nein", "correct": false, "because": "Optional"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Fat Client?', 3, '[{"text": "Lokale Leistung", "correct": true, "because": "Kernmerkmal"}, {"text": "Papierdokumente", "correct": false, "because": "Irrelevant"}, {"text": "Serverzugriff", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Fat Clients haben hohe Hardwareanforderungen. b) Sie sind für zentrale Verwaltung optimiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Thin Client zentral"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat ein Fat Client?', 5, '[{"text": "Hohe Kosten", "correct": true, "because": "Hardwareaufwand"}, {"text": "Komplexe Verwaltung", "correct": true, "because": "Lokale Updates"}, {"text": "Geringe Leistung", "correct": false, "because": "Hohe Leistung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Fat Client unwichtig?', 3, '[{"text": "Prozessorleistung", "correct": false, "because": "Kernmerkmal"}, {"text": "Speicher", "correct": false, "because": "Daten lokal"}, {"text": "Schriftart", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Fat Client als Thin Client genutzt werden?', 3, '[{"text": "Ja", "correct": true, "because": "Mit Software anpassbar"}, {"text": "Nein", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Fat Client Updates lokal benötigt?', 2, '[{"text": "Ja", "correct": true, "because": "Lokale Software"}, {"text": "Nein", "correct": false, "because": "Nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist für einen Fat Client zentral?', 4, '[{"text": "Lokale Verarbeitung", "correct": true, "because": "Kernprinzip"}, {"text": "Zentraler Server", "correct": false, "because": "Thin Client"}, {"text": "Papierdokumente", "correct": false, "because": "Irrelevant"}]');

