-- Sicherheitstest.sql (Penetrationstests, Schwachstellen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Penetrationstests immer illegal?', 2, '[{"text": "Nein", "correct": true, "because": "Legal mit Zustimmung"}, {"text": "Ja", "correct": false, "because": "Nur ohne Erlaubnis illegal"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wähle ich, um Schwachstellen aktiv auszunutzen?', 3, '[{"text": "Penetrationstest", "correct": true, "because": "Simuliert Angriffe"}, {"text": "Schwachstellenscan", "correct": false, "because": "Nur Erkennung"}, {"text": "Manuelle Prüfung", "correct": false, "because": "Weniger systematisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen einen Penetrationstest effektiv?', 5, '[{"text": "Realistische Angriffe", "correct": true, "because": "Simuliert echte Bedrohungen"}, {"text": "Detaillierte Berichte", "correct": true, "because": "Dokumentiert Schwachstellen"}, {"text": "Geringer Aufwand", "correct": false, "because": "Gründlichkeit zählt"}, {"text": "Einfache Tools", "correct": false, "because": "Komplexe Angriffe nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Schwachstellenscans finden alle Probleme. b) Penetrationstests simulieren Hacker.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "a) ist falsch, Scans nicht umfassend"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung eines Sicherheitstests?', 4, '[{"text": "Systemumgebung", "correct": false, "because": "Muss berücksichtigt werden"}, {"text": "Angriffsvektoren", "correct": false, "because": "Kern der Tests"}, {"text": "Farbschema der Tools", "correct": true, "because": "Technisch irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Schwachstellenscans aktiv ausnutzen?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Erkennung, kein Exploit"}, {"text": "Ja", "correct": false, "because": "Das machen Pentests"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel priorisiere ich bei einem Penetrationstest?', 3, '[{"text": "Schwachstellen aufdecken", "correct": true, "because": "Sicherheitslücken finden"}, {"text": "System abstürzen", "correct": false, "because": "Nicht das Ziel"}, {"text": "Einfache Durchführung", "correct": false, "because": "Effektivität zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Schwachstellenscan?', 5, '[{"text": "Schnelle Erkennung", "correct": true, "because": "Automatisierte Analyse"}, {"text": "Geringer Aufwand", "correct": true, "because": "Weniger manuelle Arbeit"}, {"text": "Volle Ausnutzung", "correct": false, "because": "Nur Erkennung"}, {"text": "Hohe Kosten", "correct": false, "because": "Oft kostengünstig"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Penetrationstests sind invasiv. b) Schwachstellenscans beheben Probleme. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Scans beheben nicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen Penetrationstest?', 4, '[{"text": "Testumgebung", "correct": false, "because": "Schützt Produktion"}, {"text": "Angriffstools", "correct": false, "because": "Nötig für Simulation"}, {"text": "Grafische Oberfläche", "correct": true, "because": "Technik im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Schwachstellenscans ausreichend für Sicherheit?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Erkennung, kein Test"}, {"text": "Ja", "correct": false, "because": "Pentests ergänzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren sind für einen Penetrationstest entscheidend?', 4, '[{"text": "Erlaubnis", "correct": true, "because": "Legalität sicherstellen"}, {"text": "Angriffsszenarien", "correct": true, "because": "Realistische Simulation"}, {"text": "Minimale Kosten", "correct": false, "because": "Qualität zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Penetrationstests nur für große Firmen sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine profitieren"}, {"text": "Ja", "correct": false, "because": "Nicht firmengrößenabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Schwachstellenscan?', 3, '[{"text": "Umfassende Erkennung", "correct": true, "because": "Alle Lücken finden"}, {"text": "Schnelle Ausführung", "correct": false, "because": "Gründlichkeit wichtiger"}, {"text": "Manuelle Eingriffe", "correct": false, "because": "Automatisierung zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Penetrationstests brauchen Expertise. b) Schwachstellenscans sind invasiv.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Scans nicht invasiv"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat ein Penetrationstest?', 5, '[{"text": "Hoher Aufwand", "correct": true, "because": "Zeit- und ressourcenintensiv"}, {"text": "Risiko für Systeme", "correct": true, "because": "Kann Störungen verursachen"}, {"text": "Geringe Kosten", "correct": false, "because": "Teuer durch Expertise"}, {"text": "Einfache Analyse", "correct": false, "because": "Komplexe Auswertung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Sicherheitstest für eine Web-App unwichtig?', 3, '[{"text": "Netzwerkschwachstellen", "correct": false, "because": "Relevant für Zugriff"}, {"text": "Angriffsvektoren", "correct": false, "because": "Wichtig für Simulation"}, {"text": "Lokale Grafikleistung", "correct": true, "because": "Irrelevant für Web"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Finden Schwachstellenscans alle Exploits?', 3, '[{"text": "Nein", "correct": true, "because": "Nur bekannte Lücken, keine Tests"}, {"text": "Ja", "correct": false, "because": "Begrenzt auf Datenbank"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Penetrationstests automatisch laufen?', 2, '[{"text": "Nein", "correct": true, "because": "Manuelle Expertise nötig"}, {"text": "Ja", "correct": false, "because": "Teilweise automatisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Test wähle ich für eine umfassende Sicherheitsprüfung?', 4, '[{"text": "Penetrationstest", "correct": true, "because": "Simuliert reale Angriffe"}, {"text": "Schwachstellenscan", "correct": false, "because": "Nur Erkennung"}, {"text": "Visuelle Inspektion", "correct": false, "because": "Zu oberflächlich"}]');

