@startuml
entity "payments" {
  * payer_id : uuid pk
  --
  * paypal_payment_id : uuid
  --
  * payer_email : text
  --
  * payer_status : text
  --
  * profile_status : text
  --
  * product_id : text
  --
  * created_at : timestamptz
  --
  * updated_at : timestamptz
}

entity "room" {
  * product_id : text pk
  --
  * unlocked_levels : json String Array
  --
  * visible_levels : json String Array
}

entity "acceskey" {
  * key_id : uuid autoincrement
  --
  * paypal_payment_id : uuid FK Referes to payments.paypal_payment_id
  --
  * product_id : text FK Referes to room.product_id
}

entity "player" {
  * id : uuid FK Referes to acceskey.key_id
  --
  * cores : jsonb
  /'
  [
  {
    "richtige_essenzen": [
      {
        "essence_fk": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
        "richtige_fragen": [
          "a1b2c3d4-e5f6-47g8-h9i0-j1k2l3m4n5o6",
          "123e4567-e89b-12d3-a456-426614174000"
        ],
        "falsche_fragen": [
          "550e8400-e29b-41d4-a716-446655440000",
          "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
        ]
      }
    ],
    "falsche_essenzen": [
      {
        "essence_fk": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
        "richtige_fragen": [
          "a1b2c3d4-e5f6-47g8-h9i0-j1k2l3m4n5o6",
          "123e4567-e89b-12d3-a456-426614174000"
        ],
        "falsche_fragen": [
          "550e8400-e29b-41d4-a716-446655440000",
          "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
        ]
      }
    ]
  },
  {
    "richtige_essenzen": [
      {
        "essence_fk": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
        "richtige_fragen": [
          "a1b2c3d4-e5f6-47g8-h9i0-j1k2l3m4n5o6",
          "123e4567-e89b-12d3-a456-426614174000"
        ],
        "falsche_fragen": [
          "550e8400-e29b-41d4-a716-446655440000",
          "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
        ]
      }
    ],
    "falsche_essenzen": [
      {
        "essence_fk": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
        "richtige_fragen": [
          "a1b2c3d4-e5f6-47g8-h9i0-j1k2l3m4n5o6",
          "123e4567-e89b-12d3-a456-426614174000"
        ],
        "falsche_fragen": [
          "550e8400-e29b-41d4-a716-446655440000",
          "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
        ]
      }
    ]
  }
  ]
  '/
}

' Fremdschlüssel-Beziehungen mit unterschiedlichen Pfeilen
acceskey -down-> payments : paypal_payment_id
player -down-> acceskey : key_id

' product_id-Vorgang mit einheitlicher Verbindung
payments *-- room : product_id
payments *-- acceskey : product_id
room *-- acceskey : product_id

@enduml