-- Planung: Erstellen des Projektstrukturplans
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Gehört das Erstellen des Projektstrukturplans zur Planungsphase?', 2, '[{"text": "Ja", "correct": true, "because": "Organisiert das Projekt früh"}, {"text": "Nein", "correct": false, "because": "Es ist Teil der Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel des Projektstrukturplans (PSP)?', 3, '[{"text": "Projekt in Teilaufgaben gliedern", "correct": true, "because": "Schafft Übersicht"}, {"text": "Team direkt motivieren", "correct": false, "because": "Anderer Fokus"}, {"text": "Kosten sofort festlegen", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der PSP definiert Arbeitspakete. b) Er wird erst in der Durchführung erstellt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Planung entscheidend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bestandteile hat ein PSP?', 4, '[{"text": "Projektphasen", "correct": true, "because": "Strukturieren Ablauf"}, {"text": "Vage Beschreibungen", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Teilprojekte", "correct": true, "because": "Zwischenebenen"}, {"text": "Arbeitspakete", "correct": true, "because": "Kleinste Einheiten"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist ein PSP für die Planung eines Projekts zwingend?', 2, '[{"text": "Ja", "correct": true, "because": "Gibt Struktur"}, {"text": "Nein", "correct": false, "because": "Ohne fehlt Übersicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher PSP ist schlecht aufgebaut?', 3, '[{"text": "Irgendwas planen", "correct": true, "because": "Zu ungenau"}, {"text": "1.1.2 App-Modul entwickeln", "correct": false, "because": "Klar strukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Gilt der PSP nur für komplexe Projekte?', 2, '[{"text": "Nein", "correct": true, "because": "Auch einfache Projekte brauchen ihn"}, {"text": "Ja", "correct": false, "because": "Universelle Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik hilft beim Erstellen eines PSP?', 3, '[{"text": "Bottom-Up-Ansatz", "correct": true, "because": "Von Details zu Ganzem"}, {"text": "Keine Ordnung", "correct": false, "because": "Fehlt Systematik"}, {"text": "Spontane Liste", "correct": false, "because": "Unübersichtlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der PSP zeigt Hierarchien. b) Er ist nur für Zeitplanung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, umfassender"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist eine Folge, wenn der PSP fehlt?', 3, '[{"text": "Unstrukturierte Aufgaben", "correct": true, "because": "Fehlende Gliederung"}, {"text": "Schnellere Umsetzung", "correct": false, "because": "Eher Chaos"}, {"text": "Kostenreduktion", "correct": false, "because": "Können steigen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann der PSP während der Durchführung geändert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Anpassung möglich"}, {"text": "Nein", "correct": false, "because": "Flexibilität nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt einen guten PSP-Eintrag?', 3, '[{"text": "2.1.3 Testphase abschließen", "correct": true, "because": "Klar und nummeriert"}, {"text": "Irgendwas testen", "correct": false, "because": "Zu vage"}, {"text": "Team soll etwas tun", "correct": false, "because": "Nicht strukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist der PSP nur für den Projektleiter wichtig?', 2, '[{"text": "Nein", "correct": true, "because": "Team braucht Struktur"}, {"text": "Ja", "correct": false, "because": "Projektweite Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften hat ein PSP?', 4, '[{"text": "Logische Gliederung", "correct": true, "because": "Fördert Übersicht"}, {"text": "Zufällige Reihenfolge", "correct": false, "because": "Widerspricht Struktur"}, {"text": "Kodierungssystem", "correct": true, "because": "Nummeriert Ebenen"}, {"text": "Klar definierte Aufgaben", "correct": true, "because": "Spezifiziert Arbeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss der PSP schriftlich festgehalten werden?', 2, '[{"text": "Ja", "correct": true, "because": "Dokumentation essenziell"}, {"text": "Nein", "correct": false, "because": "Nachvollziehbarkeit fehlt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Nutzen hat der PSP?', 3, '[{"text": "Koordination der Aufgaben", "correct": true, "because": "Fördert Ablauf"}, {"text": "Zeit verlängern", "correct": false, "because": "Kein Ziel"}, {"text": "Technische Lösung finden", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein PSP ohne Arbeitspakete erstellt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Kernbestandteil fehlt"}, {"text": "Ja", "correct": false, "because": "Unvollständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor kompliziert das Erstellen eines PSP?', 3, '[{"text": "Unklare Projektziele", "correct": true, "because": "Verhindern Struktur"}, {"text": "Gute Datenbasis", "correct": false, "because": "Fördert Erstellung"}, {"text": "Klarer Umfang", "correct": false, "because": "Unterstützt Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der PSP unterstützt Ressourcenplanung. b) Er ist nur für IT-Projekte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, breit anwendbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Vorteil des PSP?', 3, '[{"text": "Transparente Projektstruktur", "correct": true, "because": "Fördert Verständnis"}, {"text": "Maximale Unklarheit", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Planung", "correct": false, "because": "Fördert Ordnung"}]');

