-- Planung: Erstellen des Zeitplans
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist das Erstellen des Zeitplans Teil der Planungsphase?', 2, '[{"text": "Ja", "correct": true, "because": "Definiert zeitlichen Ablauf"}, {"text": "Nein", "correct": false, "because": "Es gehört zur Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel hat das Erstellen des Zeitplans?', 3, '[{"text": "Zeitliche Strukturierung des Projekts", "correct": true, "because": "Legt Ablauf fest"}, {"text": "Kosten sofort senken", "correct": false, "because": "Kein primäres Ziel"}, {"text": "Team motivieren", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der Zeitplan enthält Meilensteine. b) Er wird erst in der Durchführung erstellt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Planung ist entscheidend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zum Erstellen eines Zeitplans?', 4, '[{"text": "Start- und Endtermine", "correct": true, "because": "Definieren Dauer"}, {"text": "Unklare Schätzungen", "correct": false, "because": "Fehlt Präzision"}, {"text": "Meilensteine", "correct": true, "because": "Markieren Fortschritt"}, {"text": "Abhängigkeiten", "correct": true, "because": "Zeigen Reihenfolge"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Projekt ohne Zeitplan effektiv geplant werden?', 2, '[{"text": "Nein", "correct": true, "because": "Zeitliche Orientierung fehlt"}, {"text": "Ja", "correct": false, "because": "Risiko von Verzögerungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug hilft beim Erstellen eines Zeitplans?', 3, '[{"text": "Gantt-Diagramm", "correct": true, "because": "Visualisiert Ablauf"}, {"text": "Keine Struktur", "correct": false, "because": "Fehlt Übersicht"}, {"text": "Zufällige Notizen", "correct": false, "because": "Ungeeignet"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist ein Zeitplan nur für große Projekte relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte brauchen ihn"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt ist beim Erstellen eines Zeitplans zentral?', 3, '[{"text": "Realistische Zeitabschätzung", "correct": true, "because": "Sichert Machbarkeit"}, {"text": "Teamgröße allein", "correct": false, "because": "Nicht primär"}, {"text": "Kostenübersicht", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der Zeitplan zeigt Abhängigkeiten. b) Er ist immer unveränderlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Anpassung möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Zeitplan?', 3, '[{"text": "Verzögerungen drohen", "correct": true, "because": "Keine Zeitkontrolle"}, {"text": "Projekt wird effizienter", "correct": false, "because": "Eher Chaos"}, {"text": "Kosten sinken", "correct": false, "because": "Können steigen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Zeitplan während des Projekts geändert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Flexibilität nötig"}, {"text": "Nein", "correct": false, "because": "Anpassung üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt einen guten Zeitplan?', 3, '[{"text": "App-Entwicklung: 1.6.–30.6.", "correct": true, "because": "Klar definiert"}, {"text": "Irgendwann fertig sein", "correct": false, "because": "Zu vage"}, {"text": "Team soll schneller arbeiten", "correct": false, "because": "Kein Zeitrahmen"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist der Zeitplan nur für den Projektleiter wichtig?', 2, '[{"text": "Nein", "correct": true, "because": "Team braucht Orientierung"}, {"text": "Ja", "correct": false, "because": "Projektweite Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen das Erstellen eines Zeitplans?', 4, '[{"text": "Arbeitspakete", "correct": true, "because": "Definieren Aufgaben"}, {"text": "Unklare Ziele", "correct": false, "because": "Erschweren Planung"}, {"text": "Ressourcenverfügbarkeit", "correct": true, "because": "Bestimmen Dauer"}, {"text": "Projektumfang", "correct": true, "because": "Setzt Rahmen"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Zeitplan dokumentiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Nachvollziehbarkeit wichtig"}, {"text": "Nein", "correct": false, "because": "Dokumentation hilft"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt der Zeitplan?', 3, '[{"text": "Koordination des Projekts", "correct": true, "because": "Steuert Ablauf"}, {"text": "Kosten direkt senken", "correct": false, "because": "Unabhängig davon"}, {"text": "Technische Lösung finden", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Zeitplan ohne Arbeitspakete erstellt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Aufgabenbasis fehlt"}, {"text": "Ja", "correct": false, "because": "Unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor erschwert das Erstellen eines Zeitplans?', 3, '[{"text": "Unrealistische Schätzungen", "correct": true, "because": "Verzerren Plan"}, {"text": "Klarer Umfang", "correct": false, "because": "Fördert Planung"}, {"text": "Gute Ressourcen", "correct": false, "because": "Unterstützt Ablauf"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der Zeitplan hilft bei der Ressourcenplanung. b) Er ist nur für technische Projekte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, breit anwendbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen des Zeitplans?', 3, '[{"text": "Pünktliche Fertigstellung fördern", "correct": true, "because": "Steuert Zeit"}, {"text": "Maximale Unklarheit", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Koordination", "correct": false, "because": "Fördert Ordnung"}]');

