
-- Softwareentwicklung: Grundlagen - UML (Use Case)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Use Case immer eine vollständige Implementierung?', 2, '[{"text": "Nein", "correct": true, "because": "Es beschreibt nur Anforderungen"}, {"text": "Ja", "correct": false, "because": "Kein Code, nur Szenario"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element eines Use-Case-Diagramms repräsentiert den Benutzer?', 3, '[{"text": "Aktor", "correct": true, "because": "Stellt Benutzer oder Systeme dar"}, {"text": "Use Case", "correct": false, "because": "Beschreibt Funktion"}, {"text": "Assoziation", "correct": false, "because": "Verbindungslinie"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Use Case beschreibt eine Interaktion zwischen Aktor und System. b) Ein Use Case enthält technische Details der Implementierung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Use Cases sind funktional, nicht technisch"}, {"text": "Beides stimmt", "correct": false, "because": "Keine Implementierungsdetails"}, {"text": "Nur b) stimmt", "correct": false, "because": "Interaktion ist zentral"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Symbol solltest du im Use-Case-Diagramm für eine Funktion priorisieren?', 4, '[{"text": "Oval", "correct": true, "because": "Repräsentiert einen Use Case"}, {"text": "Pfeil", "correct": false, "because": "Zeigt Beziehungen"}, {"text": "Rechteck", "correct": false, "because": "Für Systemgrenzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Use-Case-Diagramm mehrere Akteure enthalten?', 2, '[{"text": "Ja", "correct": true, "because": "Verschiedene Benutzer möglich"}, {"text": "Nein", "correct": false, "because": "Nicht auf einen beschränkt"}]');

-- Softwareentwicklung: Grundlagen - UML (Use Case)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Use Case immer eine vollständige Implementierung?', 2, '[{"text": "Nein", "correct": true, "because": "Es beschreibt nur Anforderungen, kein Code"}, {"text": "Ja", "correct": false, "because": "Use Cases sind keine Implementierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element eines Use-Case-Diagramms repräsentiert den Benutzer?', 3, '[{"text": "Aktor", "correct": true, "because": "Stellt Benutzer oder externe Systeme dar"}, {"text": "Use Case", "correct": false, "because": "Beschreibt eine Funktion"}, {"text": "Klasse", "correct": false, "because": "Gehört zu Klassendiagrammen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Use Case beschreibt eine Interaktion mit dem System. b) Jeder Use Case hat genau einen Aktor.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Interaktion ist zentral, mehrere Aktoren möglich"}, {"text": "Beides stimmt", "correct": false, "because": "Mehrere Aktoren erlaubt"}, {"text": "Nur b) stimmt", "correct": false, "because": "Interaktion ist Kern"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beziehung in einem Use-Case-Diagramm zeigt eine optionale Erweiterung?', 4, '[{"text": "Extend", "correct": true, "because": "Zeigt optionale Use Cases"}, {"text": "Include", "correct": false, "because": "Zeigt zwingende Einbindung"}, {"text": "Association", "correct": false, "because": "Verbindet Aktor mit Use Case"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Use Case ohne Aktor definiert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Ein Aktor löst den Use Case aus"}, {"text": "Ja", "correct": false, "because": "Aktor ist essenziell"}]');

-- Softwareentwicklung: Grundlagen - UML (Use Case)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Use Case immer eine vollständige Implementierung?', 2, '[{"text": "Nein", "correct": true, "because": "Es beschreibt nur Anforderungen, kein Code"}, {"text": "Ja", "correct": false, "because": "Use Cases sind keine Implementierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element eines Use-Case-Diagramms repräsentiert den Benutzer?', 3, '[{"text": "Aktor", "correct": true, "because": "Stellt Benutzer oder externe Systeme dar"}, {"text": "Use Case", "correct": false, "because": "Beschreibt eine Funktion"}, {"text": "Klasse", "correct": false, "because": "Gehört zu Klassendiagrammen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Use Case beschreibt eine Interaktion mit dem System. b) Jeder Use Case hat genau einen Aktor.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Interaktion ist zentral, mehrere Aktoren möglich"}, {"text": "Beides stimmt", "correct": false, "because": "Mehrere Aktoren erlaubt"}, {"text": "Nur b) stimmt", "correct": false, "because": "Interaktion ist Kern"}, {"text": "Beides falsch", "correct": false, "because": "Aussage a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beziehung in einem Use-Case-Diagramm zeigt eine optionale Erweiterung?', 4, '[{"text": "Extend", "correct": true, "because": "Zeigt optionale Use Cases"}, {"text": "Include", "correct": false, "because": "Zeigt zwingende Einbindung"}, {"text": "Association", "correct": false, "because": "Nur Verbindung zwischen Aktor und Use Case"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Use-Case-Diagramm ohne Systemgrenze erstellt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Grenze ist optional"}, {"text": "Nein", "correct": false, "because": "Nicht zwingend erforderlich"}]');
