-- questions.sql (Physische Datenorganisation in Datenbanken, z. B. Speicherstrukturen, Zugriffsmethoden)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Datenbank immer physisch sichtbar organisiert ist?', 2, '[{"text": "Nein", "correct": true, "because": "Abstraktion über physischer Ebene"}, {"text": "Ja", "correct": false, "because": "Nutzer sieht logisches Schema"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element definiert, wie Daten physisch gespeichert werden?', 3, '[{"text": "Speicherstruktur", "correct": true, "because": "Legt Organisation fest"}, {"text": "SQL-Abfrage", "correct": false, "because": "Nur Zugriff"}, {"text": "Benutzeroberfläche", "correct": false, "because": "Kein Speicherfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte gehören zur physischen Datenorganisation?', 5, '[{"text": "Indizes", "correct": true, "because": "Beschleunigen Zugriff"}, {"text": "Dateistrukturen", "correct": true, "because": "Definieren Speicher"}, {"text": "Partitionierung", "correct": true, "because": "Teilt Daten auf"}, {"text": "Farbcodierung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Es beschreibt die physische Speicherung. b) Es ist für Nutzer sichtbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist logisches Schema"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich die Datenorganisation plane?', 4, '[{"text": "Indizes", "correct": false, "because": "Optimieren Zugriff"}, {"text": "Speicherformat", "correct": false, "because": "Definiert Struktur"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass die physische Ebene immer gleich ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig vom DBMS"}, {"text": "Ja", "correct": false, "because": "Variiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik wähle ich, um den Zugriff auf Daten zu beschleunigen?', 3, '[{"text": "B-Baum-Index", "correct": true, "because": "Effiziente Suche"}, {"text": "SQL-View", "correct": false, "because": "Logische Ebene"}, {"text": "Backup", "correct": false, "because": "Wiederherstellung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gut geplante Datenorganisation?', 5, '[{"text": "Schneller Zugriff", "correct": true, "because": "Optimierte Strukturen"}, {"text": "Effiziente Speicherung", "correct": true, "because": "Nutzt Ressourcen"}, {"text": "Hohe Leistung", "correct": true, "because": "Reduziert Latenz"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) Indizes die physische Ebene betreffen und b) sie für Nutzer sichtbar sind. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist logische Ebene"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um die physische Speicherung zu definieren?', 4, '[{"text": "Dateistrukturen", "correct": false, "because": "Organisieren Daten"}, {"text": "Zugriffsmethoden", "correct": false, "because": "Bestimmen Zugriff"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die physische Ebene für Nutzer relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Abstraktion durch DBMS"}, {"text": "Ja", "correct": false, "because": "Logisches Schema zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Datenorganisation?', 4, '[{"text": "Speichertechnologie", "correct": true, "because": "z. B. SSD vs. HDD"}, {"text": "Indexstrategie", "correct": true, "because": "Beschleunigt Zugriff"}, {"text": "Farbcodierung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass die physische Ebene immer gleich bleibt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von DBMS"}, {"text": "Ja", "correct": false, "because": "Variabel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer physischen Struktur?', 3, '[{"text": "Leistungsoptimierung", "correct": true, "because": "Schneller Zugriff"}, {"text": "Nutzeransicht", "correct": false, "because": "Logisches Schema"}, {"text": "Datenkompression", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Partitionierung teilt Daten physisch. b) Sie ist für Nutzer sichtbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist logische Ebene"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt ein Index?', 4, '[{"text": "Zugriff beschleunigen", "correct": true, "because": "Optimiert Suche"}, {"text": "Daten anzeigen", "correct": false, "because": "Logische Ebene"}, {"text": "Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die physische Ebene die Datengröße beeinflusst?', 2, '[{"text": "Ja", "correct": true, "because": "Durch Speicherstrukturen"}, {"text": "Nein", "correct": false, "because": "Einfluss vorhanden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine optimierte Datenorganisation?', 5, '[{"text": "Schnelle Abfragen", "correct": true, "because": "Indizes helfen"}, {"text": "Geringerer Speicherbedarf", "correct": true, "because": "Effiziente Strukturen"}, {"text": "Hohe Leistung", "correct": true, "because": "Optimiert Zugriff"}, {"text": "Farbanpassung", "correct": false, "because": "Kein Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die physische Ebene für SQL-Abfragen relevant?', 3, '[{"text": "Nein", "correct": true, "because": "SQL ist logisch"}, {"text": "Ja", "correct": false, "because": "DBMS abstrahiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur physischen Datenorganisation?', 4, '[{"text": "Index für schnelle Suche", "correct": true, "because": "Physische Optimierung"}, {"text": "SQL-Abfrage schreiben", "correct": false, "because": "Logische Ebene"}, {"text": "Daten anzeigen", "correct": false, "because": "Nutzeransicht"}]');

