-- questions.sql (Netzwerkkonfiguration, z. B. IP-Adressen, Subnetze, Tools wie ipconfig/ip)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Netzwerkeinstellung immer manuell sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "DHCP automatisiert"}, {"text": "Ja", "correct": false, "because": "Automatisierung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl zeigt dir unter Windows die aktuellen Netzwerkeinstellungen?', 3, '[{"text": "ipconfig", "correct": true, "because": "Zeigt IP-Adressen"}, {"text": "netstat", "correct": false, "because": "Verbindungen"}, {"text": "ping", "correct": false, "because": "Nur Erreichbarkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einer Netzwerkeinstellung?', 5, '[{"text": "IP-Adresse", "correct": true, "because": "Identifiziert Gerät"}, {"text": "Subnetzmaske", "correct": true, "because": "Definiert Netzwerk"}, {"text": "Gateway", "correct": true, "because": "Leitet Daten"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Subnetzmaske teilt Netzwerke. b) DHCP ist immer statisch.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DHCP ist dynamisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein Netzwerk einrichte?', 4, '[{"text": "IP-Adresse", "correct": false, "because": "Identifiziert Geräte"}, {"text": "Gateway", "correct": false, "because": "Leitet Daten"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Adresse immer fest vergeben wird. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "DHCP vergibt dynamisch"}, {"text": "Ja", "correct": false, "because": "Flexibel einstellbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Befehl unter Linux zeigt die aktuellen Adressen?', 3, '[{"text": "ip addr show", "correct": true, "because": "Listet IP-Adressen"}, {"text": "ifconfig", "correct": false, "because": "Älteres Tool"}, {"text": "route", "correct": false, "because": "Nur Routing"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine dynamische Adressvergabe?', 5, '[{"text": "Einfache Verwaltung", "correct": true, "because": "Automatisiert"}, {"text": "Flexibilität", "correct": true, "because": "Ändert sich bei Bedarf"}, {"text": "Weniger Konflikte", "correct": true, "because": "Vermeidet Doppelvergabe"}, {"text": "Hohe Latenz", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) ipconfig unter Windows Adressen zeigt und b) es nur IPv4 unterstützt. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch IPv6 sichtbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um eine Netzwerkeinstellung zu ändern?', 4, '[{"text": "IP-Adresse", "correct": false, "because": "Identifiziert Gerät"}, {"text": "Subnetzmaske", "correct": false, "because": "Definiert Netzwerk"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss eine Adresse immer statisch sein?', 2, '[{"text": "Nein", "correct": true, "because": "Dynamisch möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel einstellbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Techniken nutze ich für die Netzwerkeinstellung?', 4, '[{"text": "DHCP", "correct": true, "because": "Automatische Vergabe"}, {"text": "Statische Zuweisung", "correct": true, "because": "Manuelle Konfiguration"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Netzwerkeinstellung nur lokal funktioniert. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch extern gültig"}, {"text": "Ja", "correct": false, "because": "Global nutzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer Netzwerkeinstellung?', 3, '[{"text": "Kommunikation ermöglichen", "correct": true, "because": "Verbindet Geräte"}, {"text": "Datenkompression", "correct": false, "because": "Anderer Zweck"}, {"text": "Designverbesserung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Subnetzmaske trennt Netzwerke. b) Ein Gateway ist optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Gateway oft nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt das Gateway?', 4, '[{"text": "Daten weiterleiten", "correct": true, "because": "Verbindet Netzwerke"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Anderer Zweck"}, {"text": "Design anpassen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Adresse immer IPv4 sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "IPv6 möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen eine Netzwerkeinstellung nützlich?', 5, '[{"text": "IP-Adresse", "correct": true, "because": "Identifiziert Geräte"}, {"text": "Subnetzmaske", "correct": true, "because": "Trennt Netzwerke"}, {"text": "Gateway", "correct": true, "because": "Leitet Daten"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist `ipconfig /release` unter Windows zum Anzeigen da?', 3, '[{"text": "Nein", "correct": true, "because": "Gibt Adresse frei"}, {"text": "Ja", "correct": false, "because": "Nur Anzeige mit /all"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einer Netzwerkeinstellung?', 4, '[{"text": "IP-Adresse einem Server zuweisen", "correct": true, "because": "Typische Anwendung"}, {"text": "Webseitenlayout erstellen", "correct": false, "because": "Anderer Zweck"}, {"text": "Daten komprimieren", "correct": false, "because": "Sekundär"}]');

