-- questions.sql (Softwarequalitätsmodell, z. B. Funktionalität, Zuverlässigkeit, Effizienz in IT)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Qualitätsmodell immer nur Funktionalität bewertet?', 2, '[{"text": "Nein", "correct": true, "because": "Mehrere Kriterien"}, {"text": "Ja", "correct": false, "because": "Umfassend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium prüft, ob eine Software ihre Aufgaben erfüllt?', 3, '[{"text": "Funktionalität", "correct": true, "because": "Zweck erfüllen"}, {"text": "Effizienz", "correct": false, "because": "Ressourcennutzung"}, {"text": "Wartbarkeit", "correct": false, "because": "Änderbarkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale gehören zu einem Softwarequalitätsstandard?', 5, '[{"text": "Zuverlässigkeit", "correct": true, "because": "Fehlerresistenz"}, {"text": "Benutzbarkeit", "correct": true, "because": "Nutzerfreundlichkeit"}, {"text": "Effizienz", "correct": true, "because": "Ressourcennutzung"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Effizienz misst Ressourcennutzung. b) Funktionalität ist optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Funktionalität ist Kern"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich Softwarequalität bewerte?', 4, '[{"text": "Zuverlässigkeit", "correct": false, "because": "Wichtig für Stabilität"}, {"text": "Wartbarkeit", "correct": false, "because": "Änderbarkeit entscheidend"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Software immer perfekt sein muss. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Qualität hat Kriterien"}, {"text": "Ja", "correct": false, "because": "Relativ bewertet"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal prüft die Nutzerfreundlichkeit einer Software?', 3, '[{"text": "Benutzbarkeit", "correct": true, "because": "Einfache Bedienung"}, {"text": "Portabilität", "correct": false, "because": "Systemwechsel"}, {"text": "Funktionalität", "correct": false, "because": "Zweck"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kriterien machen eine Software hochwertig?', 5, '[{"text": "Funktionalität", "correct": true, "because": "Erfüllt Anforderungen"}, {"text": "Wartbarkeit", "correct": true, "because": "Leicht anpassbar"}, {"text": "Portabilität", "correct": true, "because": "Systemunabhängig"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) Zuverlässigkeit Fehlerresistenz misst und b) Effizienz unwichtig ist. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Effizienz zählt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Softwarequalität zu bewerten?', 4, '[{"text": "Testkriterien", "correct": false, "because": "Bewertungsgrundlage"}, {"text": "Anforderungen", "correct": false, "because": "Vergleichspunkt"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Portabilität für die Bedienung wichtig?', 2, '[{"text": "Nein", "correct": true, "because": "Systemwechsel, nicht Bedienung"}, {"text": "Ja", "correct": false, "because": "Benutzbarkeit zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale helfen bei der Wartung?', 4, '[{"text": "Wartbarkeit", "correct": true, "because": "Änderbarkeit"}, {"text": "Portabilität", "correct": true, "because": "Systemwechsel erleichtert"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Software nur funktional sein muss. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Mehrere Kriterien"}, {"text": "Ja", "correct": false, "because": "Umfassend bewertet"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Qualitätsstandard?', 3, '[{"text": "Software verbessern", "correct": true, "because": "Kriterien prüfen"}, {"text": "Daten komprimieren", "correct": false, "because": "Anderer Zweck"}, {"text": "Design verbessern", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Benutzbarkeit misst Nutzerfreundlichkeit. b) Zuverlässigkeit ist optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zuverlässigkeit essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt Effizienz?', 4, '[{"text": "Ressourcennutzung", "correct": true, "because": "Optimiert Leistung"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Anderer Zweck"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Funktionalität die Bedienung prüft?', 2, '[{"text": "Nein", "correct": true, "because": "Das ist Benutzbarkeit"}, {"text": "Ja", "correct": false, "because": "Zweck, nicht Bedienung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen eine Software hochwertig?', 5, '[{"text": "Funktionalität", "correct": true, "because": "Erfüllt Zweck"}, {"text": "Effizienz", "correct": true, "because": "Optimiert Ressourcen"}, {"text": "Benutzbarkeit", "correct": true, "because": "Nutzerfreundlich"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Wartbarkeit für die Laufzeit wichtig?', 3, '[{"text": "Nein", "correct": true, "because": "Änderbarkeit, nicht Laufzeit"}, {"text": "Ja", "correct": false, "because": "Effizienz zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einem Qualitätsmerkmal?', 4, '[{"text": "Software einfach anpassen", "correct": true, "because": "Wartbarkeit"}, {"text": "Webseitenlayout erstellen", "correct": false, "because": "Designfokus"}, {"text": "Datenkompression", "correct": false, "because": "Anderer Zweck"}]');


