-- questions.sql (Schutz von Systemen, Bedrohungen, Sicherheitsmaßnahmen in IT)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Passwort immer ausreicht, um ein System zu schützen?', 2, '[{"text": "Nein", "correct": true, "because": "Mehrfaktor stärker"}, {"text": "Ja", "correct": false, "because": "Kann geknackt werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme verhindert unbefugten Zugriff auf Daten?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Macht Daten unlesbar"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nur Leistung"}, {"text": "Schnelle Hardware", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden helfen, ein System abzusichern?', 5, '[{"text": "Firewall", "correct": true, "because": "Blockiert Angriffe"}, {"text": "Antivirus", "correct": true, "because": "Erkennt Malware"}, {"text": "Updates", "correct": true, "because": "Schließt Lücken"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Phishing zielt auf Nutzerdaten. b) Updates sind optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Updates essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein Netzwerk absichere?', 4, '[{"text": "Verschlüsselung", "correct": false, "because": "Schützt Daten"}, {"text": "Zugriffskontrollen", "correct": false, "because": "Begrenzt Zugang"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Firewall alle Angriffe stoppt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Nur ein Teil des Schutzes"}, {"text": "Ja", "correct": false, "because": "Begrenzt wirksam"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool erkennt ungewöhnliche Aktivitäten im Netzwerk?', 3, '[{"text": "IDS", "correct": true, "because": "Intrusion Detection System"}, {"text": "Router", "correct": false, "because": "Nur Weiterleitung"}, {"text": "Texteditor", "correct": false, "because": "Kein Sicherheitswerkzeug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen ein System sicherer?', 5, '[{"text": "Starke Passwörter", "correct": true, "because": "Erschweren Zugriff"}, {"text": "Backups", "correct": true, "because": "Schützen vor Verlust"}, {"text": "Verschlüsselung", "correct": true, "because": "Sichert Daten"}, {"text": "Hohe Auflösung", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) 2FA die Sicherheit erhöht und b) offene WLANs sicher sind. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Offene WLANs unsicher"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Daten vor Verlust zu schützen?', 4, '[{"text": "Regelmäßige Backups", "correct": false, "because": "Wiederherstellung"}, {"text": "Verschlüsselung", "correct": false, "because": "Schützt Vertraulichkeit"}, {"text": "Schnelle Festplatte", "correct": true, "because": "Nur Leistung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein VPN immer sicher?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Konfiguration"}, {"text": "Ja", "correct": false, "because": "Schwachstellen möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen helfen gegen Social Engineering?', 4, '[{"text": "Schulungen", "correct": true, "because": "Sensibilisieren Nutzer"}, {"text": "Richtlinien", "correct": true, "because": "Definieren Verhalten"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Sicherheitslücken selten sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Häufig und gefährlich"}, {"text": "Ja", "correct": false, "because": "Updates nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer Firewall?', 3, '[{"text": "Unbefugten Zugriff blockieren", "correct": true, "because": "Filtert Verkehr"}, {"text": "Daten komprimieren", "correct": false, "because": "Nicht Aufgabe"}, {"text": "Netzwerk beschleunigen", "correct": false, "because": "Kein Leistungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Backups schützen vor Ransomware. b) Antivirus stoppt alles.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Antivirus nicht 100%"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik sichert Daten bei der Übertragung?', 4, '[{"text": "TLS", "correct": true, "because": "Verschlüsselt Kommunikation"}, {"text": "FTP", "correct": false, "because": "Unsicher"}, {"text": "HTTP", "correct": false, "because": "Klartext"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein starkes Passwort allein genug ist?', 2, '[{"text": "Nein", "correct": true, "because": "2FA stärker"}, {"text": "Ja", "correct": false, "because": "Kann geknackt werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein IDS?', 5, '[{"text": "Bedrohungserkennung", "correct": true, "because": "Warnt bei Angriffen"}, {"text": "Protokollierung", "correct": true, "because": "Dokumentiert Ereignisse"}, {"text": "Datenkompression", "correct": false, "because": "Nicht enthalten"}, {"text": "Schnelle Hardware", "correct": false, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt ein Backup vor allen Bedrohungen?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Datenverlust"}, {"text": "Ja", "correct": false, "because": "Kein Echtzeitschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario zeigt einen typischen Angriff?', 4, '[{"text": "Phishing-Mail", "correct": true, "because": "Zielt auf Nutzer"}, {"text": "Software-Update", "correct": false, "because": "Kein Angriff"}, {"text": "Netzwerkscan", "correct": false, "because": "Nur Prüfung"}]');

