-- questions.sql (Peripheriegeräte, Netzwerkzubehör, Speichermedien in IT, z. B. Mäuse, Router, USB-Sticks)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob jedes Gerät einen USB-Anschluss braucht?', 2, '[{"text": "Nein", "correct": true, "because": "Andere Schnittstellen möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Teil hilft mir, Daten zwischen zwei Computern zu übertragen?', 3, '[{"text": "USB-Stick", "correct": true, "because": "Einfacher Datenträger"}, {"text": "Maus", "correct": false, "because": "Nur Eingabe"}, {"text": "Monitor", "correct": false, "because": "Nur Anzeige"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Geräte erweitern die Funktionen eines PCs?', 5, '[{"text": "Tastatur", "correct": true, "because": "Eingabe ermöglichen"}, {"text": "Externer Speicher", "correct": true, "because": "Erweitert Kapazität"}, {"text": "Netzwerkadapter", "correct": true, "because": "Verbindet Netzwerke"}, {"text": "Bürostuhl", "correct": false, "because": "Kein IT-Teil"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Router verbindet Netzwerke. b) Eine Maus speichert Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Maus ist Eingabegerät"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich meinen PC aufrüste?', 4, '[{"text": "Speicherkapazität", "correct": false, "because": "Wichtig für Leistung"}, {"text": "Anschlüsse", "correct": false, "because": "Für Kompatibilität"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass jedes Gerät einen Monitor braucht. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Server ohne möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Teil verbindet meinen PC mit einem WLAN?', 3, '[{"text": "Netzwerkadapter", "correct": true, "because": "Ermöglicht WLAN-Zugang"}, {"text": "USB-Stick", "correct": false, "because": "Nur Speicher"}, {"text": "Tastatur", "correct": false, "because": "Nur Eingabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktionen bieten externe Geräte?', 5, '[{"text": "Daten speichern", "correct": true, "because": "z. B. Festplatten"}, {"text": "Eingaben tätigen", "correct": true, "because": "z. B. Maus"}, {"text": "Netzwerke verbinden", "correct": true, "because": "z. B. Router"}, {"text": "Farben anpassen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) ein Switch Daten weiterleitet und b) ein Drucker speichert. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Drucker druckt nur"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um meinen PC zu erweitern?', 4, '[{"text": "Externer Speicher", "correct": false, "because": "Erhöht Kapazität"}, {"text": "Netzwerkkabel", "correct": false, "because": "Für Verbindung"}, {"text": "Bürodeko", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Router für jedes Netzwerk nötig?', 2, '[{"text": "Nein", "correct": true, "because": "Switch reicht lokal"}, {"text": "Ja", "correct": false, "because": "Kontextabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Geräte verbessern die Netzwerkverbindung?', 4, '[{"text": "Router", "correct": true, "because": "Verbindet Netzwerke"}, {"text": "Switch", "correct": true, "because": "Erweitert Anschlüsse"}, {"text": "Monitor", "correct": false, "because": "Nur Anzeige"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Tastatur immer kabelgebunden ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kabellos möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem externen Speicher?', 3, '[{"text": "Daten sichern", "correct": true, "because": "Erweitert Speicher"}, {"text": "Eingaben tätigen", "correct": false, "because": "Anderer Zweck"}, {"text": "Farben anpassen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein USB-Hub erweitert Anschlüsse. b) Ein Switch speichert Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Switch leitet nur"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt ein Drucker im Büro?', 4, '[{"text": "Dokumente ausgeben", "correct": true, "because": "Druckt physisch"}, {"text": "Netzwerke verbinden", "correct": false, "because": "Router-Aufgabe"}, {"text": "Daten speichern", "correct": false, "because": "Speichergerät"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Monitor für jeden PC nötig ist?', 2, '[{"text": "Nein", "correct": true, "because": "Remote möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Netzwerkadapter?', 5, '[{"text": "WLAN-Zugang", "correct": true, "because": "Verbindet drahtlos"}, {"text": "Erhöhte Mobilität", "correct": true, "because": "Kein Kabel nötig"}, {"text": "Einfache Installation", "correct": true, "because": "Plug-and-Play"}, {"text": "Daten speichern", "correct": false, "because": "Keine Speicherfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein USB-Stick nur für Speicherung?', 3, '[{"text": "Ja", "correct": true, "because": "Primär Speicher"}, {"text": "Nein", "correct": false, "because": "Hauptzweck Speicherung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einem externen Gerät?', 4, '[{"text": "Daten auf USB-Stick sichern", "correct": true, "because": "Typische Nutzung"}, {"text": "Webdesign erstellen", "correct": false, "because": "Softwareaufgabe"}, {"text": "Daten komprimieren", "correct": false, "because": "Anderer Zweck"}]');

