-- Arbeitsrecht Berufsbildung > Berufsbildungsgesetz (BBiG) > Rechte Pflichten Definition
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Hat ein Fachinformatiker das Recht auf eine angemessene Ausbildung gemäß BBiG?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG definiert dieses Recht"}, {"text": "Nein", "correct": false, "because": "Recht ist gesetzlich verankert"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Fachinformatiker die Anweisungen des Arbeitgebers befolgen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG definiert dies als Pflicht"}, {"text": "Nein", "correct": false, "because": "Befolgung ist vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist ein Ausbildungsbetrieb verpflichtet, einem Fachinformatiker eine Vergütung zu zahlen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 17 BBiG legt diese Pflicht fest"}, {"text": "Nein", "correct": false, "because": "Vergütung ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Fachinformatiker verlangen, dass der Betrieb ihn für Berufsschulprüfungen freistellt?', 2, '[{"text": "Ja", "correct": true, "because": "§ 15 BBiG definiert dieses Recht"}, {"text": "Nein", "correct": false, "because": "Freistellung ist gesetzlich garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Ausbildungsbetrieb die Arbeitsleistung eines Fachinformatikers kontrollieren dürfen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 14 Abs. 2 BBiG definiert dieses Recht"}, {"text": "Nein", "correct": false, "because": "Kontrolle ist erlaubt"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Paragraph des BBiG definiert die Pflichten eines Fachinformatikers?', 2, '[{"text": "§ 13 BBiG", "correct": true, "because": "Legt Pflichten wie Lernpflichten fest"}, {"text": "§ 14 BBiG", "correct": false, "because": "Bezieht sich auf Arbeitgeberpflichten"}, {"text": "§ 16 BBiG", "correct": false, "because": "Regelt das Zeugnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Recht hat ein Fachinformatiker gemäß BBiG?', 3, '[{"text": "Anspruch auf Ausbildungsvergütung", "correct": true, "because": "§ 17 BBiG definiert dieses Recht"}, {"text": "Feste Arbeitszeiten nach Wahl", "correct": false, "because": "Arbeitszeiten werden vom Betrieb festgelegt"}, {"text": "Ablehnung aller Anweisungen", "correct": false, "because": "Pflicht zur Befolgung besteht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflicht hat ein Ausbildungsbetrieb gegenüber einem Fachinformatiker?', 3, '[{"text": "Gewissenhafte Ausbildung durchführen", "correct": true, "because": "§ 14 Abs. 1 BBiG fordert dies"}, {"text": "Nur einfache Aufgaben zuteilen", "correct": false, "because": "Nicht gewissenhaft"}, {"text": "Keine Unterweisung bieten", "correct": false, "because": "Unterweisung ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer definiert die Rechte und Pflichten eines Fachinformatikers im BBiG?', 2, '[{"text": "Das Berufsbildungsgesetz", "correct": true, "because": "BBiG legt Rechte und Pflichten fest"}, {"text": "Die IHK", "correct": false, "because": "IHK überwacht nur"}, {"text": "Die Berufsschule", "correct": false, "because": "Schule ergänzt die Ausbildung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Betrieb seine Pflichten gegenüber einem Fachinformatiker nicht erfüllt?', 3, '[{"text": "Die IHK kann einschreiten", "correct": true, "because": "IHK überwacht die Einhaltung des BBiG"}, {"text": "Der Auszubildende übernimmt die Pflichten", "correct": false, "because": "Nicht seine Aufgabe"}, {"text": "Keine Konsequenzen", "correct": false, "because": "Verstoß hat Folgen"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Rechte hat ein Fachinformatiker gemäß BBiG?', 4, '[{"text": "Anspruch auf angemessene Ausbildung", "correct": true, "because": "§ 13 BBiG definiert dies"}, {"text": "Anspruch auf Vergütung", "correct": true, "because": "§ 17 BBiG garantiert dies"}, {"text": "Feste Arbeitszeiten nach Wahl", "correct": false, "because": "Arbeitszeiten vom Betrieb festgelegt"}, {"text": "Freistellung für Prüfungen", "correct": true, "because": "§ 15 BBiG schützt dies"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat ein Fachinformatiker gemäß BBiG?', 3, '[{"text": "Lernpflichten erfüllen", "correct": true, "because": "§ 13 BBiG fordert dies"}, {"text": "Arbeitszeit einhalten", "correct": true, "because": "§ 13 BBiG definiert dies"}, {"text": "Selbstständig den Betrieb leiten", "correct": false, "because": "Nicht vorgeschrieben"}, {"text": "Verschwiegenheit über Betriebsgeheimnisse", "correct": true, "because": "§ 13 BBiG legt dies fest"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat ein Ausbildungsbetrieb gegenüber einem Fachinformatiker?', 4, '[{"text": "Gewissenhafte Ausbildung", "correct": true, "because": "§ 14 Abs. 1 BBiG fordert dies"}, {"text": "Vergütung zahlen", "correct": true, "because": "§ 17 BBiG definiert dies"}, {"text": "Nur einfache Aufgaben zuteilen", "correct": false, "because": "Nicht gewissenhaft"}, {"text": "Zeugnis ausstellen", "correct": true, "because": "§ 16 BBiG verpflichtet dazu"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rechte hat ein Ausbildungsbetrieb gegenüber einem Fachinformatiker?', 3, '[{"text": "Weisungsrecht", "correct": true, "because": "§ 14 Abs. 2 BBiG definiert dies"}, {"text": "Kontrolle der Arbeitsleistung", "correct": true, "because": "§ 14 Abs. 2 BBiG erlaubt dies"}, {"text": "Vergütung kürzen bei Fehlern", "correct": false, "because": "§ 17 BBiG schützt die Vergütung"}, {"text": "Kündigung unter Vorschriften", "correct": true, "because": "§ 22 BBiG regelt dies"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Fachinformatiker seine Pflichten gemäß BBiG nicht erfüllt?', 3, '[{"text": "Abmahnung durch den Betrieb", "correct": true, "because": "Reaktion auf Pflichtverletzung"}, {"text": "Kündigung bei schwerem Verstoß", "correct": true, "because": "§ 22 BBiG erlaubt dies"}, {"text": "Automatische Beförderung", "correct": false, "because": "Nicht logisch"}, {"text": "Verwarnung durch die IHK", "correct": true, "because": "IHK kann eingreifen"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ein Fachinformatiker hat das Recht auf Vergütung. b) Der Betrieb hat keine Pflichten gegenüber dem Auszubildenden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vergütung ist Recht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Betrieb muss einen Fachinformatiker gewissenhaft ausbilden. b) Der Fachinformatiker hat keine Lernpflichten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ausbildung Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Fachinformatiker muss Betriebseigentum schonen. b) Der Betrieb hat kein Weisungsrecht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schonung Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Der Betrieb muss ein Zeugnis ausstellen. b) Ein Fachinformatiker hat kein Recht auf Freistellung für Prüfungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeugnis Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Fachinformatiker muss Arbeitszeit einhalten. b) Der Betrieb hat keine Pflicht zur Vergütung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Arbeitszeit Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

