-- Qualitätsmanagement.sql (Maßnahmen zur Sicherstellung von Prozess- und Produktqualität)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Stimmt es, dass ich bei der Qualitätskontrolle nur Endprodukte prüfe?', 2, '[{"text": "Nein", "correct": true, "because": "Prozesse werden auch geprüft"}, {"text": "Ja", "correct": false, "because": "Umfassender Ansatz nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug nutze ich, um Prozessabweichungen zu visualisieren?', 3, '[{"text": "Regelkarte", "correct": true, "because": "Zeigt Schwankungen klar"}, {"text": "Gantt-Diagramm", "correct": false, "because": "Für Zeitplanung"}, {"text": "ER-Diagramm", "correct": false, "because": "Für Datenmodelle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sichern die Softwarequalität?', 5, '[{"text": "Code-Reviews", "correct": true, "because": "Findet Fehler früh"}, {"text": "Automatisierte Tests", "correct": true, "because": "Sichert Funktionalität"}, {"text": "Hohe Rechenleistung", "correct": false, "because": "Kein Qualitätsfaktor"}, {"text": "Schnelle Deployment-Zyklen", "correct": false, "because": "Risiko für Fehler"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) ISO 9001 fordert kontinuierliche Verbesserung. b) Sie garantiert fehlerfreie Produkte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "ISO 9001 sichert Prozesse, nicht Perfektion"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl eines Qualitätsstandards?', 4, '[{"text": "Branchenanforderungen", "correct": false, "because": "maßgeblich für Relevanz"}, {"text": "Zertifizierungskosten", "correct": false, "because": "wichtig für Budget"}, {"text": "Marketingkampagnen", "correct": true, "because": "kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Pareto-Diagramm Fehlerursachen priorisiert?', 2, '[{"text": "Ja", "correct": true, "because": "Zeigt 80/20-Regel"}, {"text": "Nein", "correct": false, "because": "Hauptzweck ist Priorisierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip ist für nachhaltige Prozessverbesserung entscheidend?', 4, '[{"text": "PDCA-Zyklus", "correct": true, "because": "Strukturiert Planung und Kontrolle"}, {"text": "Hohe Automatisierung", "correct": false, "because": "Werkzeug, kein Prinzip"}, {"text": "Maximale Dokumentation", "correct": false, "because": "Hilfreich, aber sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Qualitätsmanagement nur für Produktion relevant ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Dienstleistungen und IT"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Audit nur eine Fehlerfindung?', 3, '[{"text": "Nein", "correct": true, "because": "Auch Verbesserungspotenziale erkennen"}, {"text": "Ja", "correct": false, "because": "Umfassender Zweck"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen ein Testprotokoll effektiv?', 5, '[{"text": "Klar definierte Kriterien", "correct": true, "because": "Sichert Vergleichbarkeit"}, {"text": "Nachvollziehbare Ergebnisse", "correct": true, "because": "Ermöglicht Analyse"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Genauigkeit zählt"}, {"text": "Minimale Dokumentation", "correct": false, "because": "Details sind nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wenn ich ein System auf Qualität prüfe, was ist primär?', 4, '[{"text": "Erfüllung der Anforderungen", "correct": true, "because": "Kern der Qualitätssicherung"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Sekundär zur Korrektheit"}, {"text": "Geringer Speicherbedarf", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Qualitätsziele müssen messbar sein. b) Sie ändern sich nie. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ziele müssen anpassbar bleiben"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich bei einer Ursachenanalyse vorgehe?', 4, '[{"text": "Ishikawa-Diagramm nutzen", "correct": true, "because": "Strukturiert Ursachen"}, {"text": "Nur Logs prüfen", "correct": false, "because": "Zu eingeschränkt"}, {"text": "Zufallstests", "correct": false, "because": "Unsystematisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Einführung eines neuen Standards unwichtig?', 3, '[{"text": "Schulung der Mitarbeiter", "correct": false, "because": "Sichert Umsetzung"}, {"text": "Anpassung der Prozesse", "correct": false, "because": "Kern der Einführung"}, {"text": "Farbcodierung der Dokumente", "correct": true, "because": "Kein funktionaler Nutzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Stimmt es, dass ich bei der Qualitätssicherung nur auf Softwarefehler achte?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Prozesse und Usability"}, {"text": "Ja", "correct": false, "because": "Breiterer Fokus nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft mir, Prozesse langfristig zu optimieren?', 4, '[{"text": "Kontinuierliche Verbesserung", "correct": true, "because": "Fördert nachhaltige Anpassung"}, {"text": "Einmalige Überprüfung", "correct": false, "because": "Zu statisch"}, {"text": "Maximale Standardisierung", "correct": false, "because": "Einschränkt Flexibilität"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Fehlermanagement-System trackt Bugs. b) Es ersetzt Tests.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tests sind weiter nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Qualitätssicherung nur für Kunden relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch interne Prozesse profitieren"}, {"text": "Ja", "correct": false, "because": "Breitere Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte prüfe ich bei einer Softwarequalitätskontrolle?', 5, '[{"text": "Funktionalität", "correct": true, "because": "Erfüllt Anforderungen"}, {"text": "Wartbarkeit", "correct": true, "because": "Ermöglicht Updates"}, {"text": "Farbschema", "correct": false, "because": "Ästhetik, kein Kern"}, {"text": "Installationszeit", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Qualitätsmanagement immer teuer ist. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Langfristig kostensparend"}, {"text": "Ja", "correct": false, "because": "Kosteneffizienz möglich"}]');

