-- Meilenstein.sql (Wichtige Etappen oder Kontrollpunkte in IT-Projekten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Meilensteine in IT-Projekten immer am Projektende liegen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Verteilt über Projektlaufzeit"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich Meilensteine für ein IT-Projekt definiere?', 3, '[{"text": "Klar definierte Ziele", "correct": true, "because": "Sichern Fortschritt"}, {"text": "Schnellste Festlegung", "correct": false, "because": "Planung zählt"}, {"text": "Bürodesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale haben Meilensteine in IT-Projekten?', 5, '[{"text": "Klar definiert", "correct": true, "because": "Markieren Etappen"}, {"text": "Messbar", "correct": true, "because": "Überprüfen Fortschritt"}, {"text": "Büromöbel", "correct": false, "because": "Kein Merkmal"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Meilensteine dienen der Projektkontrolle. b) Sie sind immer unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wichtig für Kontrolle"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich Meilensteine für ein IT-Projekt festlege?', 4, '[{"text": "Projektziele", "correct": false, "because": "Bestimmen Meilensteine"}, {"text": "Zeitplan", "correct": false, "because": "Koordiniert Etappen"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Projektfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Meilensteine in IT-Projekten immer zeitlich fixiert sind?', 2, '[{"text": "Ja", "correct": true, "because": "Markieren Deadlines"}, {"text": "Nein", "correct": false, "because": "Grundprinzip"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Meilensteinen in einem IT-Projekt?', 3, '[{"text": "Fortschrittskontrolle", "correct": true, "because": "Überprüft Status"}, {"text": "Schnellste Fertigstellung", "correct": false, "because": "Planung wichtiger"}, {"text": "Weniger Kontrolle", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bestandteile sind bei Meilensteinen in IT-Projekten entscheidend?', 5, '[{"text": "Ergebnisse", "correct": true, "because": "Definieren Erfolg"}, {"text": "Termine", "correct": true, "because": "Markieren Zeitpunkte"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbanalyse", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Meilensteine helfen Projekte zu steuern. b) Sie sind immer optional. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht optional"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Meilensteine in einem IT-Projekt zu definieren?', 4, '[{"text": "Projektplan", "correct": false, "because": "Grundlage für Etappen"}, {"text": "Kriterien", "correct": false, "because": "Definieren Erfolg"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Projektfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Meilensteine in IT-Projekten immer flexibel?', 2, '[{"text": "Nein", "correct": true, "because": "Oft festgelegt"}, {"text": "Ja", "correct": false, "because": "Zu ungenau"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Meilensteine in IT-Projekten?', 4, '[{"text": "Transparenz", "correct": true, "because": "Zeigen Fortschritt"}, {"text": "Motivation", "correct": true, "because": "Markieren Erfolge"}, {"text": "Schnellere Projekte", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Meilensteine nur für große IT-Projekte wichtig sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um Meilensteine in einem IT-Projekt effektiv zu setzen?', 3, '[{"text": "Klar definierte Ziele", "correct": true, "because": "Markieren Etappen"}, {"text": "Günstigste Tools", "correct": false, "because": "Effektivität wichtiger"}, {"text": "Bunte Diagramme", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Meilensteine können Risiken reduzieren. b) Sie sind immer unwichtig für IT-Projekte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wichtig für Kontrolle"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei Meilensteinen in IT-Projekten?', 5, '[{"text": "Zeitplan", "correct": true, "because": "Koordiniert Etappen"}, {"text": "Ergebnisse", "correct": true, "because": "Definieren Erfolg"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich Meilensteine für ein IT-Projekt festlege?', 3, '[{"text": "Projektphasen", "correct": false, "because": "Strukturieren Meilensteine"}, {"text": "Kriterien", "correct": false, "because": "Messen Fortschritt"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Projektfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Meilensteine in IT-Projekten immer flexibel?', 3, '[{"text": "Nein", "correct": true, "because": "Oft festgelegt"}, {"text": "Ja", "correct": false, "because": "Zu ungenau"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Meilensteine nur für IT-Projekte relevant sind?', 2, '[{"text": "Nein", "correct": true, "because": "Auch andere Bereiche"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für Meilensteine in IT-Projekten?', 4, '[{"text": "Definierte Ziele", "correct": true, "because": "Markieren Fortschritt"}, {"text": "Schnellste Umsetzung", "correct": false, "because": "Planung zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');

