-- MS_Access.sql (Relationale Datenbankanwendung von Microsoft)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass MS Access immer nur für kleine Datenbanken geeignet ist. Stimmt das?', 2, '[{"text": "Ja", "correct": true, "because": "Begrenzt für große Datenmengen"}, {"text": "Nein", "correct": false, "because": "Primär für kleine bis mittlere"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich MS Access für ein IT-Projekt nutze?', 3, '[{"text": "Datenbankdesign", "correct": true, "because": "Sichert Struktur"}, {"text": "Schnellste Installation", "correct": false, "because": "Planung zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktionen bietet MS Access?', 5, '[{"text": "Tabellenverwaltung", "correct": true, "because": "Speichert Daten"}, {"text": "Abfragen", "correct": true, "because": "Filtert Daten"}, {"text": "Büroplanung", "correct": false, "because": "Kein Feature"}, {"text": "Farbanalyse", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) MS Access unterstützt SQL-Abfragen. b) Es ist immer serverbasiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Lokal nutzbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich MS Access für ein Projekt einsetze?', 4, '[{"text": "Datenintegrität", "correct": false, "because": "Sichert Konsistenz"}, {"text": "Benutzerfreundlichkeit", "correct": false, "because": "Wichtiges Feature"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Datenbankfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob MS Access nur für Einzelnutzer geeignet ist?', 2, '[{"text": "Nein", "correct": true, "because": "Mehrere Nutzer möglich"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit MS Access in einem IT-Projekt?', 3, '[{"text": "Datenverwaltung", "correct": true, "because": "Organisiert Informationen"}, {"text": "Schnellste Installation", "correct": false, "because": "Funktion zählt"}, {"text": "Weniger Daten", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bestandteile sind bei MS Access entscheidend?', 5, '[{"text": "Tabellen", "correct": true, "because": "Speichern Daten"}, {"text": "Formulare", "correct": true, "because": "Eingabe erleichtern"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) MS Access kann Berichte erstellen. b) Es ist immer für große Datenbanken geeignet. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Begrenzt für große Daten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um MS Access effektiv zu nutzen?', 4, '[{"text": "Tabellenstruktur", "correct": false, "because": "Sichert Daten"}, {"text": "Abfragen", "correct": false, "because": "Filtert Informationen"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Datenbankfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist MS Access immer serverbasiert?', 2, '[{"text": "Nein", "correct": true, "because": "Auch lokal nutzbar"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet MS Access in der IT?', 4, '[{"text": "Benutzerfreundlichkeit", "correct": true, "because": "Einfache Bedienung"}, {"text": "Schnelle Entwicklung", "correct": true, "because": "Rascher Einsatz"}, {"text": "Schnellere Projekte", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass MS Access nur für kleine Unternehmen geeignet ist. Stimmt das?', 2, '[{"text": "Ja", "correct": true, "because": "Begrenzt für große Datenmengen"}, {"text": "Nein", "correct": false, "because": "Primär für kleine bis mittlere"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um MS Access für ein Projekt effektiv zu nutzen?', 3, '[{"text": "Datenbankdesign", "correct": true, "because": "Sichert Struktur"}, {"text": "Günstigste Lizenz", "correct": false, "because": "Funktion wichtiger"}, {"text": "Bunte Oberfläche", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) MS Access unterstützt Beziehungen zwischen Tabellen. b) Es ist immer für Großunternehmen geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Begrenzt für große Daten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei MS Access?', 5, '[{"text": "Datenintegrität", "correct": true, "because": "Sichert Konsistenz"}, {"text": "Benutzerzugriff", "correct": true, "because": "Regelt Nutzung"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich MS Access für ein Projekt einsetze?', 3, '[{"text": "Tabellenbeziehungen", "correct": false, "because": "Sichern Struktur"}, {"text": "Datenbankgröße", "correct": false, "because": "Bestimmt Einsatz"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Datenbankfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann MS Access mit anderen Datenbanken verbunden werden?', 3, '[{"text": "Ja", "correct": true, "because": "Via ODBC möglich"}, {"text": "Nein", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob MS Access nur für Einzelnutzer gedacht ist?', 2, '[{"text": "Nein", "correct": true, "because": "Mehrere Nutzer möglich"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für MS Access?', 4, '[{"text": "Tabellenstruktur", "correct": true, "because": "Sichert Datenverwaltung"}, {"text": "Schnellste Installation", "correct": false, "because": "Funktion zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');

