-- Mängelanzeige.sql (Meldung von Fehlern oder Problemen in IT-Systemen oder Projekten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Mängelanzeige immer schriftlich erfolgen muss. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch mündlich möglich"}, {"text": "Ja", "correct": false, "because": "Form variiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich eine Mängelanzeige für ein IT-System erstelle?', 3, '[{"text": "Genauigkeit der Beschreibung", "correct": true, "because": "Sichert Verständnis"}, {"text": "Schnellste Meldung", "correct": false, "because": "Details wichtiger"}, {"text": "Farbliche Gestaltung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einer Mängelanzeige in der IT?', 5, '[{"text": "Fehlerbeschreibung", "correct": true, "because": "Erklärt Problem"}, {"text": "Zeitpunkt", "correct": true, "because": "Hilft bei Analyse"}, {"text": "Büroausstattung", "correct": false, "because": "Kein Faktor"}, {"text": "Marketingplan", "correct": false, "because": "Nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Mängelanzeige dient der Problemlösung. b) Sie ist immer rechtlich bindend.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht immer bindend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich eine Mängelanzeige für ein IT-Projekt erstelle?', 4, '[{"text": "Fehlerursache", "correct": false, "because": "Hilft bei Lösung"}, {"text": "Auswirkung", "correct": false, "because": "Zeigt Dringlichkeit"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein Mängelfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Mängelanzeige immer vom Kunden kommt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch intern möglich"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer Mängelanzeige in der IT?', 3, '[{"text": "Problemlösung", "correct": true, "because": "Behebt Fehler"}, {"text": "Schnellste Meldung", "correct": false, "because": "Genauigkeit wichtiger"}, {"text": "Weniger Dokumentation", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bestandteile sind bei einer Mängelanzeige entscheidend?', 5, '[{"text": "Problemdetails", "correct": true, "because": "Beschreibt Fehler"}, {"text": "Dringlichkeit", "correct": true, "because": "Priorisiert Bearbeitung"}, {"text": "Büromöbel", "correct": false, "because": "Irrelevant"}, {"text": "Werbestrategie", "correct": false, "because": "Kein Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Eine Mängelanzeige verbessert die Qualität. b) Sie ist immer negativ. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht nur negativ"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine Mängelanzeige in der IT?', 4, '[{"text": "Fehlerbeschreibung", "correct": false, "because": "Kernbestandteil"}, {"text": "Zeitangabe", "correct": false, "because": "Hilft bei Analyse"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Mängelfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist eine Mängelanzeige immer Teil eines Vertrags?', 2, '[{"text": "Nein", "correct": true, "because": "Auch informell möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Mängelanzeige?', 4, '[{"text": "Fehlerbehebung", "correct": true, "because": "Löst Probleme"}, {"text": "Qualitätssteigerung", "correct": true, "because": "Verbessert System"}, {"text": "Schnellere Projekte", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Mängelanzeige nur für Hardware gilt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Software betroffen"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um eine Mängelanzeige für ein IT-System effektiv zu machen?', 3, '[{"text": "Detaillierte Angaben", "correct": true, "because": "Fördert Lösung"}, {"text": "Schnellste Meldung", "correct": false, "because": "Details wichtiger"}, {"text": "Bunte Formulare", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Mängelanzeige kann Prozesse verbessern. b) Sie ist immer unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht unwichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei einer Mängelanzeige?', 5, '[{"text": "Fehlerbeschreibung", "correct": true, "because": "Erklärt Problem"}, {"text": "Zeitpunkt", "correct": true, "because": "Hilft bei Analyse"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Firmenfarben", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich eine Mängelanzeige erstelle?', 3, '[{"text": "Auswirkungen", "correct": false, "because": "Zeigt Dringlichkeit"}, {"text": "Fehlerursache", "correct": false, "because": "Hilft bei Lösung"}, {"text": "Dekoratives Layout", "correct": true, "because": "Kein Mängelfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist eine Mängelanzeige nur für Kunden relevant?', 3, '[{"text": "Nein", "correct": true, "because": "Auch intern nützlich"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Mängelanzeige immer schriftlich sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "Auch mündlich möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für eine Mängelanzeige?', 4, '[{"text": "Präzise Fehlerbeschreibung", "correct": true, "because": "Sichert Verständnis"}, {"text": "Schnellste Meldung", "correct": false, "because": "Details wichtiger"}, {"text": "Büroausstattung", "correct": false, "because": "Irrelevant"}]');


