-- questions.sql (Energieeffizienz - Optimierung des Energieverbrauchs in IT-Systemen, z. B. für Systemintegration)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Energieeffizienz nur für Serverräume relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Workstations, Geräte"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt Energieeffizienz in IT-Systemen?', 3, '[{"text": "Energieverbrauch reduzieren", "correct": true, "because": "Kosten und Umwelt"}, {"text": "Leistung maximieren", "correct": false, "because": "Sekundär"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Anderes Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen fördern die Energieeffizienz?', 5, '[{"text": "Virtualisierung", "correct": true, "because": "Weniger physische Server"}, {"text": "Energieeffiziente Hardware", "correct": true, "because": "Geringerer Verbrauch"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Ineffizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Energieeffizienz senkt Betriebskosten. b) Sie erhöht den Energieverbrauch.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verbrauch sinkt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Energieeffizienz?', 4, '[{"text": "Stromverbrauch", "correct": false, "because": "Kernfaktor"}, {"text": "Hardwareauslastung", "correct": false, "because": "Effizienz beeinflusst"}, {"text": "Papierfarbe", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Energieeffizienz nur Hardware betrifft?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Software"}, {"text": "Ja", "correct": false, "because": "Systemweit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie steigert die Energieeffizienz?', 3, '[{"text": "Power Management", "correct": true, "because": "Verbrauch steuern"}, {"text": "Manuelle Abschaltung", "correct": false, "because": "Ineffizient"}, {"text": "Papierdokumentation", "correct": false, "because": "Nicht technisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Energieeffizienz?', 5, '[{"text": "Kostensenkung", "correct": true, "because": "Weniger Strom"}, {"text": "Umweltschutz", "correct": true, "because": "CO2-Reduktion"}, {"text": "Höhere Leistung", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Energieeffizienz spart Ressourcen. b) Sie ist nur für neue Systeme relevant. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch alte Systeme"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Energieeffizienz?', 4, '[{"text": "Effiziente Hardware", "correct": false, "because": "Verbrauch senken"}, {"text": "Software-Optimierung", "correct": false, "because": "Prozesse verbessern"}, {"text": "Papierhandbücher", "correct": true, "because": "Digital ausreichend"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Energieeffizienz nur für Serverräume?', 2, '[{"text": "Nein", "correct": true, "because": "Auch PCs, Geräte"}, {"text": "Ja", "correct": false, "because": "Systemweit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Energieeffizienz?', 4, '[{"text": "Hardware-Design", "correct": true, "because": "Energieverbrauch"}, {"text": "Software-Algorithmen", "correct": true, "because": "Prozesseffizienz"}, {"text": "Monitorgröße", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Energieeffizienz die Leistung senkt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Leistung optimierbar"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Energieeffizienz?', 3, '[{"text": "Niedriger Verbrauch", "correct": true, "because": "Kernziel"}, {"text": "Maximale Leistung", "correct": false, "because": "Sekundär"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Energieeffizienz reduziert Stromkosten. b) Sie erfordert immer neue Hardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Software optimierbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ansätze fördern Energieeffizienz?', 5, '[{"text": "Sleep-Modi", "correct": true, "because": "Verbrauch senken"}, {"text": "Effiziente Kühlung", "correct": true, "because": "Energie sparen"}, {"text": "Manuelle Abschaltung", "correct": false, "because": "Ineffizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Energieeffizienz unwichtig?', 3, '[{"text": "Stromverbrauch", "correct": false, "because": "Kernfaktor"}, {"text": "Optimierung", "correct": false, "because": "Zentral"}, {"text": "Schriftart", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann Energieeffizienz die Umwelt schonen?', 3, '[{"text": "Ja", "correct": true, "because": "Weniger CO2"}, {"text": "Nein", "correct": false, "because": "Umweltvorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Energieeffizienz nur neue Systeme betrifft?', 2, '[{"text": "Nein", "correct": true, "because": "Auch alte Systeme"}, {"text": "Ja", "correct": false, "because": "Breit anwendbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist für Energieeffizienz zentral?', 4, '[{"text": "Optimierter Energieverbrauch", "correct": true, "because": "Kernprinzip"}, {"text": "Manuelle Prozesse", "correct": false, "because": "Ineffizient"}, {"text": "Papierdokumente", "correct": false, "because": "Irrelevant"}]');

