-- questions.sql (Beschaffungsplanung: Planung von IT-Ressourcen für Fachinformatiker)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was versteht ein Fachinformatiker unter Beschaffungsplanung?', 2, '[{"text": "Planung von IT-Ressourcen", "correct": true, "because": "Hardware und Software beschaffen"}, {"text": "Marketingplanung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit der Beschaffungsplanung?', 3, '[{"text": "Bedarfsgerechte Versorgung", "correct": true, "because": "Ressourcen bereitstellen"}, {"text": "Systemgeschwindigkeit erhöhen", "correct": false, "because": "Indirekt"}, {"text": "Design optimieren", "correct": false, "because": "Kein primäres Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Beschaffungsplanung?', 5, '[{"text": "Bedarfsermittlung", "correct": true, "because": "Was wird benötigt"}, {"text": "Budgetplanung", "correct": true, "because": "Kosten berücksichtigen"}, {"text": "Büroverschönerung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Beschaffungsplanung berücksichtigt den Bedarf. b) Sie ist nur für Hardware nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Software betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Beschaffungsplanung?', 4, '[{"text": "Kostenrahmen", "correct": false, "because": "Budget entscheidend"}, {"text": "Lieferzeiten", "correct": false, "because": "Zeitplan wichtig"}, {"text": "Farbe der Hardware", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Beschaffungsplanung den Bedarf analysiert?', 2, '[{"text": "Ja", "correct": true, "because": "Grundlage der Planung"}, {"text": "Nein", "correct": false, "because": "Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wähle ich für die Beschaffungsplanung?', 3, '[{"text": "Bedarfsanalyse", "correct": true, "because": "Ermittelt Anforderungen"}, {"text": "Marketingkampagne", "correct": false, "because": "Kein Bezug"}, {"text": "Hardwaretest", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Beschaffungsplanung eines Fachinformatikers?', 5, '[{"text": "Angebotsvergleich", "correct": true, "because": "Preise prüfen"}, {"text": "Lieferantenbewertung", "correct": true, "because": "Zuverlässigkeit"}, {"text": "Büroverschönerung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Beschaffungsplanung optimiert Ressourcen. b) Sie ist nur für große Firmen nötig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch kleine Firmen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Beschaffungsplanung unwichtig?', 4, '[{"text": "Budget", "correct": false, "because": "Kostenplanung"}, {"text": "Lieferzeit", "correct": false, "because": "Zeitmanagement"}, {"text": "Farbe der Geräte", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss die Beschaffungsplanung dokumentiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Nachvollziehbarkeit"}, {"text": "Nein", "correct": false, "because": "Empfohlen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gute Beschaffungsplanung?', 4, '[{"text": "Kosteneffizienz", "correct": true, "because": "Optimale Ressourcen"}, {"text": "Rechtzeitige Verfügbarkeit", "correct": true, "because": "Keine Verzögerungen"}, {"text": "Schnellere Systeme", "correct": false, "because": "Kein Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Beschaffungsplanung nur für Hardware ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Software"}, {"text": "Ja", "correct": false, "because": "Umfassender"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Beschaffungsplanung?', 3, '[{"text": "Bedarf", "correct": true, "because": "Grundlage"}, {"text": "Ästhetik", "correct": false, "because": "Sekundär"}, {"text": "Marketing", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Beschaffungsplanung umfasst Budgetplanung. b) Sie ist nur für Neugeräte relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Ersatzteile"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat eine schlechte Beschaffungsplanung?', 5, '[{"text": "Verzögerungen", "correct": true, "because": "Ressourcen fehlen"}, {"text": "Höhere Kosten", "correct": true, "because": "Fehlkauf"}, {"text": "Schnellere Lieferung", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Fachinformatiker bei der Beschaffungsplanung?', 3, '[{"text": "Bedarf ermitteln", "correct": true, "because": "Planung"}, {"text": "Büro reinigen", "correct": false, "because": "Kein Bezug"}, {"text": "Marketing betreiben", "correct": false, "because": "Andere Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Beschaffungsplanung digital erfolgen?', 2, '[{"text": "Ja", "correct": true, "because": "Softwaretools"}, {"text": "Nein", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool könnte ein Fachinformatiker für die Beschaffungsplanung nutzen?', 4, '[{"text": "SAP", "correct": true, "because": "ERP-System"}, {"text": "Photoshop", "correct": false, "because": "Grafiktool"}, {"text": "Excel", "correct": false, "because": "Eingeschränkt"}]');