-- questions.sql (Bildwiederholfrequenz: Frequenz der Bildaktualisierung am Bildschirm)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was versteht ein Fachinformatiker unter Bildwiederholfrequenz?', 2, '[{"text": "Anzahl der Bildaktualisierungen pro Sekunde", "correct": true, "because": "Misst Refresh-Rate"}, {"text": "Auflösung eines Bildschirms", "correct": false, "because": "Anderes Konzept"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer hohen Bildwiederholfrequenz?', 3, '[{"text": "Flüssigere Darstellung", "correct": true, "because": "Verbessert Nutzererfahrung"}, {"text": "Kosten senken", "correct": false, "because": "Indirekt"}, {"text": "Speicherplatz sparen", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einheit wird für die Bildwiederholfrequenz verwendet?', 5, '[{"text": "Hertz (Hz)", "correct": true, "because": "Frequenzmaß"}, {"text": "Pixel", "correct": false, "because": "Auflösung"}, {"text": "Byte", "correct": false, "because": "Speichergröße"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine höhere Bildwiederholfrequenz reduziert Flimmern. b) Sie ist nur für Spiele relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Büroarbeit betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Bildwiederholfrequenz?', 4, '[{"text": "Monitorunterstützung", "correct": false, "because": "Hardware entscheidend"}, {"text": "Grafikkartenleistung", "correct": false, "because": "Beeinflusst Frequenz"}, {"text": "Büroverschönerung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Bildwiederholfrequenz die Augenbelastung beeinflusst?', 2, '[{"text": "Ja", "correct": true, "because": "Weniger Flimmern"}, {"text": "Nein", "correct": false, "because": "Ergonomisch relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bildwiederholfrequenz ist Standard für moderne Monitore?', 3, '[{"text": "60 Hz", "correct": true, "because": "Häufigster Wert"}, {"text": "30 Hz", "correct": false, "because": "Zu niedrig"}, {"text": "10 Hz", "correct": false, "because": "Unpraktisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Optimierung der Bildwiederholfrequenz?', 5, '[{"text": "Grafikkarteneinstellungen", "correct": true, "because": "Steuert Frequenz"}, {"text": "Monitorunterstützung", "correct": true, "because": "Hardwareanforderung"}, {"text": "Bürogestaltung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Eine hohe Bildwiederholfrequenz verbessert die Darstellung. b) Sie ist nur für Gamer wichtig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Büroarbeit"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Bildwiederholfrequenz unwichtig?', 4, '[{"text": "Bildschirmgröße", "correct": false, "because": "Beeinflusst Wahrnehmung"}, {"text": "Grafikkartenleistung", "correct": false, "because": "Entscheidend"}, {"text": "Farbe des Monitors", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss die Bildwiederholfrequenz mit der Grafikkarte übereinstimmen?', 2, '[{"text": "Ja", "correct": true, "because": "Kompatibilität nötig"}, {"text": "Nein", "correct": false, "because": "Abhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine hohe Bildwiederholfrequenz?', 4, '[{"text": "Flüssige Animationen", "correct": true, "because": "Bessere Darstellung"}, {"text": "Weniger Augenbelastung", "correct": true, "because": "Reduziert Flimmern"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Bildwiederholfrequenz von 144 Hz nur für Spiele ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für andere Anwendungen"}, {"text": "Ja", "correct": false, "because": "Breiter Nutzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Bildwiederholfrequenz?', 3, '[{"text": "Nutzerkomfort", "correct": true, "because": "Ergonomie"}, {"text": "Kosten", "correct": false, "because": "Sekundär"}, {"text": "Ästhetik", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Bildwiederholfrequenz von 60 Hz ist Standard. b) Sie beeinflusst nur die Hardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Nutzererfahrung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat eine niedrige Bildwiederholfrequenz?', 5, '[{"text": "Flimmern", "correct": true, "because": "Augenbelastung"}, {"text": "Ruckelige Darstellung", "correct": true, "because": "Weniger flüssig"}, {"text": "Schnellere Reaktion", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Fachinformatiker bei der Bildwiederholfrequenz?', 3, '[{"text": "Optimale Einstellung", "correct": true, "because": "Nutzerkomfort"}, {"text": "Büro reinigen", "correct": false, "because": "Kein Bezug"}, {"text": "Marketing betreiben", "correct": false, "because": "Andere Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Bildwiederholfrequenz angepasst werden?', 2, '[{"text": "Ja", "correct": true, "because": "Einstellbar"}, {"text": "Nein", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool könnte ein Fachinformatiker zur Anpassung nutzen?', 4, '[{"text": "Grafikkarten-Treiber", "correct": true, "because": "z.B. NVIDIA Control Panel"}, {"text": "Photoshop", "correct": false, "because": "Grafiktool"}, {"text": "Excel", "correct": false, "because": "Tabellenkalkulation"}]');

