-- questions.sql (Blacklisting: Sicherheitsmaßnahme zum Sperren unerwünschter Elemente)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was versteht ein Fachinformatiker unter Blacklisting?', 2, '[{"text": "Sperren bekannter unerwünschter Elemente", "correct": true, "because": "Blockiert Bedrohungen"}, {"text": "Freigabe zugelassener Elemente", "correct": false, "because": "Whitelisting"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Blacklisting?', 3, '[{"text": "Sicherheit erhöhen", "correct": true, "because": "Bedrohungen abwehren"}, {"text": "Kosten senken", "correct": false, "because": "Indirekt"}, {"text": "Systemleistung steigern", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente können auf einer Blacklist stehen?', 5, '[{"text": "IP-Adressen", "correct": true, "because": "Netzwerksicherheit"}, {"text": "Benutzernamen", "correct": true, "because": "Zugriffskontrolle"}, {"text": "Dateien", "correct": true, "because": "Malware-Schutz"}, {"text": "Farbcodes", "correct": false, "because": "Kein Sicherheitsbezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Blacklisting blockiert bekannte Bedrohungen. b) Es erlaubt alles außer den gelisteten Elementen.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Definition von Blacklisting"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) auch korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) auch korrekt"}, {"text": "Beides falsch", "correct": false, "because": "Beide richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich beim Blacklisting?', 4, '[{"text": "Liste der Bedrohungen", "correct": false, "because": "Grundlage"}, {"text": "Aktualität der Liste", "correct": false, "because": "Schutz erhöhen"}, {"text": "Büroverschönerung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Blacklisting in Firewalls genutzt wird?', 2, '[{"text": "Ja", "correct": true, "because": "IP-Sperrung"}, {"text": "Nein", "correct": false, "because": "Häufig genutzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool könnte Blacklisting für IP-Adressen umsetzen?', 3, '[{"text": "iptables", "correct": true, "because": "Firewall-Regeln"}, {"text": "Photoshop", "correct": false, "because": "Grafiktool"}, {"text": "Excel", "correct": false, "because": "Tabellenkalkulation"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Umsetzung von Blacklisting?', 5, '[{"text": "Liste erstellen", "correct": true, "because": "Bedrohungen definieren"}, {"text": "Regeln anwenden", "correct": true, "because": "Sperrung umsetzen"}, {"text": "Farbcodierung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Blacklisting schützt vor bekannten Bedrohungen. b) Es blockiert automatisch alle neuen Bedrohungen. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nur bekannte"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist beim Blacklisting unwichtig?', 4, '[{"text": "Aktualität", "correct": false, "because": "Schutz aktuell halten"}, {"text": "Sperrregeln", "correct": false, "because": "Umsetzung nötig"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss eine Blacklist regelmäßig aktualisiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Neue Bedrohungen"}, {"text": "Nein", "correct": false, "because": "Empfohlen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Blacklisting?', 4, '[{"text": "Schutz vor bekannten Bedrohungen", "correct": true, "because": "Sperrt Zugriffe"}, {"text": "Einfache Umsetzung", "correct": true, "because": "Liste-basierend"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Blacklisting sicherer als Whitelisting ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Whitelisting restriktiver"}, {"text": "Ja", "correct": false, "because": "Abhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich beim Blacklisting?', 3, '[{"text": "Aktualität der Liste", "correct": true, "because": "Schutz gewährleisten"}, {"text": "Kosten", "correct": false, "because": "Sekundär"}, {"text": "Ästhetik", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Blacklisting blockiert bekannte IPs. b) Es schützt vor allen Bedrohungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nur bekannte"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat Blacklisting?', 5, '[{"text": "Keine neuen Bedrohungen", "correct": true, "because": "Nur bekannte gesperrt"}, {"text": "Wartungsaufwand", "correct": true, "because": "Liste aktualisieren"}, {"text": "Schnellere Prozesse", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Fachinformatiker beim Blacklisting?', 3, '[{"text": "Blacklist pflegen", "correct": true, "because": "Sicherheit gewährleisten"}, {"text": "Büro reinigen", "correct": false, "because": "Kein Bezug"}, {"text": "Marketing betreiben", "correct": false, "because": "Andere Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Blacklisting automatisiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "z.B. mit IDS"}, {"text": "Nein", "correct": false, "because": "Automatisierbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool könnte ein Fachinformatiker für Blacklisting nutzen?', 4, '[{"text": "Fail2Ban", "correct": true, "because": "Automatische Sperrung"}, {"text": "Photoshop", "correct": false, "because": "Grafiktool"}, {"text": "Excel", "correct": false, "because": "Tabellenkalkulation"}]');

