-- questions.sql (Businessplan: Strategisches Dokument für Geschäftsplanung)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was versteht ein Fachinformatiker unter einem Businessplan?', 2, '[{"text": "Strategisches Dokument für Geschäftsplanung", "correct": true, "because": "Ziele und Finanzen"}, {"text": "Technisches Handbuch", "correct": false, "because": "Kein IT-Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Businessplan?', 3, '[{"text": "Unternehmensziele und Finanzierung planen", "correct": true, "because": "Langfristige Strategie"}, {"text": "Software entwickeln", "correct": false, "because": "Kein technisches Ziel"}, {"text": "Design verbessern", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem Businessplan?', 5, '[{"text": "Geschäftsidee", "correct": true, "because": "Grundlage"}, {"text": "Finanzplan", "correct": true, "because": "Kosten und Einnahmen"}, {"text": "Marktanalyse", "correct": true, "because": "Wettbewerb"}, {"text": "Farbcodierung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Businessplan enthält eine Marktanalyse. b) Er ist nur für IT-Projekte relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Alle Branchen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Businessplan?', 4, '[{"text": "Finanzplanung", "correct": false, "because": "Kernbestandteil"}, {"text": "Marktanalyse", "correct": false, "because": "Wettbewerb verstehen"}, {"text": "Büroverschönerung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Businessplan einen Finanzplan enthält?', 2, '[{"text": "Ja", "correct": true, "because": "Kosten und Einnahmen"}, {"text": "Nein", "correct": false, "because": "Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Teil eines Businessplans ist für Investoren am wichtigsten?', 3, '[{"text": "Finanzplan", "correct": true, "because": "Rendite und Risiko"}, {"text": "Teamvorstellung", "correct": false, "because": "Sekundär"}, {"text": "Farbschema", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Erstellung eines Businessplans?', 5, '[{"text": "Zieldefinition", "correct": true, "because": "Geschäftsziele"}, {"text": "Wettbewerbsanalyse", "correct": true, "because": "Markt verstehen"}, {"text": "Finanzprognosen", "correct": true, "because": "Einnahmen planen"}, {"text": "Bürogestaltung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Businessplan hilft bei der Finanzierung. b) Er ist nur für Start-ups nötig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch bestehende Firmen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Businessplan unwichtig?', 4, '[{"text": "Zielsetzung", "correct": false, "because": "Kern"}, {"text": "Finanzplanung", "correct": false, "because": "Entscheidend"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ein Businessplan eine Marktanalyse enthalten?', 2, '[{"text": "Ja", "correct": true, "because": "Wettbewerb bewerten"}, {"text": "Nein", "correct": false, "because": "Empfohlen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Businessplan für Fachinformatiker?', 4, '[{"text": "Projektfinanzierung sichern", "correct": true, "because": "Investoren überzeugen"}, {"text": "Strategische Planung", "correct": true, "because": "Ziele definieren"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Businessplan nur für große Projekte ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte"}, {"text": "Ja", "correct": false, "because": "Universell"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Businessplan?', 3, '[{"text": "Finanzplan", "correct": true, "because": "Überlebensfähigkeit"}, {"text": "Ästhetik", "correct": false, "because": "Sekundär"}, {"text": "Kosten", "correct": false, "because": "Teil des Plans"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Businessplan enthält eine Geschäftsidee. b) Er ist nur für IT-Projekte nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Alle Branchen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat ein fehlender Businessplan?', 5, '[{"text": "Fehlende Finanzierung", "correct": true, "because": "Investoren überzeugen"}, {"text": "Unklare Ziele", "correct": true, "because": "Keine Strategie"}, {"text": "Schnellere Umsetzung", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Fachinformatiker bei einem Businessplan?', 3, '[{"text": "Technische Machbarkeit prüfen", "correct": true, "because": "IT-Aspekte"}, {"text": "Büro reinigen", "correct": false, "because": "Kein Bezug"}, {"text": "Marketing betreiben", "correct": false, "because": "Andere Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Businessplan IT-Projekte umfassen?', 2, '[{"text": "Ja", "correct": true, "because": "z.B. Softwareentwicklung"}, {"text": "Nein", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool könnte ein Fachinformatiker für einen Businessplan nutzen?', 4, '[{"text": "Excel", "correct": true, "because": "Finanzkalkulation"}, {"text": "Photoshop", "correct": false, "because": "Grafiktool"}, {"text": "Notepad", "correct": false, "because": "Texteditor"}]');

