-- Skripte zur Prozessautomatisierung erstellen.sql (z. B. Bash- oder Python-Skripte für wiederkehrende Aufgaben)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Bash-Skript immer schneller als ein Python-Skript?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Aufgabe und Implementierung"}, {"text": "Ja", "correct": false, "because": "Python kann optimiert schneller sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Automatisierungsskript?', 3, '[{"text": "Zeitersparnis", "correct": true, "because": "Wiederkehrende Aufgaben automatisieren"}, {"text": "Datenkompression", "correct": false, "because": "Nicht primär"}, {"text": "Grafische Ausgabe", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einem guten Automatisierungsskript?', 5, '[{"text": "Fehlerbehandlung", "correct": true, "because": "Sichert Robustheit"}, {"text": "Modularität", "correct": true, "because": "Erleichtert Wartung"}, {"text": "Hohe Auflösung", "correct": false, "because": "Irrelevant"}, {"text": "Farbige Logs", "correct": false, "because": "Nice-to-have"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Bash ist für Systemaufgaben ideal. b) Python ist nur für Datenanalyse.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Python ist vielseitig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Automatisierungsskript?', 4, '[{"text": "Ausführungslogik", "correct": false, "because": "Kern der Automatisierung"}, {"text": "Fehlerausgabe", "correct": false, "because": "Wichtig für Diagnose"}, {"text": "Grafisches Design", "correct": true, "because": "Kein Skriptfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Bash-Skripte auch ohne Shell laufen?', 2, '[{"text": "Nein", "correct": true, "because": "Shell-Umgebung nötig"}, {"text": "Ja", "correct": false, "because": "Shell ist Basis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Sprache wähle ich für ein plattformübergreifendes Skript?', 3, '[{"text": "Python", "correct": true, "because": "Hohe Portabilität"}, {"text": "Bash", "correct": false, "because": "Unix-spezifisch"}, {"text": "Batch", "correct": false, "because": "Windows-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben automatisierst du mit Bash oder Python?', 5, '[{"text": "Dateibereinigung", "correct": true, "because": "Wiederkehrende Aufgabe"}, {"text": "Systemüberwachung", "correct": true, "because": "Regelmäßige Checks"}, {"text": "Datenbankdesign", "correct": false, "because": "Kein Automatisierungsfokus"}, {"text": "UI-Tests", "correct": false, "because": "Andere Tools besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Bash ist schneller bei Systemaufrufen. b) Python ist immer komplexer. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Python kann einfach sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Automatisierungsskript?', 4, '[{"text": "Logikfluss", "correct": false, "because": "Kern der Ausführung"}, {"text": "Fehlerprüfung", "correct": false, "because": "Sichert Stabilität"}, {"text": "Touch-Optimierung", "correct": true, "because": "Kein UI-Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Python-Skripte immer plattformunabhängig?', 2, '[{"text": "Ja", "correct": true, "because": "Mit Anpassung portabel"}, {"text": "Nein", "correct": false, "because": "OS-spezifische Aufrufe möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Features verbessern ein Bash-Skript?', 4, '[{"text": "Variablen", "correct": true, "because": "Flexibilität erhöhen"}, {"text": "Bedingungen", "correct": true, "because": "Logik steuern"}, {"text": "3D-Grafiken", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Automatisierungsskripte immer fehleranfällig sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Mit Tests robust"}, {"text": "Ja", "correct": false, "because": "Fehler vermeidbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Skript für wiederkehrende Aufgaben?', 3, '[{"text": "Wartbarkeit", "correct": true, "because": "Langfristige Nutzung"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Qualität zählt"}, {"text": "Maximale Größe", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Bash ist für Serveraufgaben geeignet. b) Python braucht immer eine GUI.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Python CLI-fähig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Automatisierungsskripte?', 5, '[{"text": "Konsistenz", "correct": true, "because": "Gleiche Ausführung"}, {"text": "Zeitersparnis", "correct": true, "because": "Manuelle Arbeit reduziert"}, {"text": "Hohe Auflösung", "correct": false, "because": "Kein Vorteil"}, {"text": "Grafische Reports", "correct": false, "because": "Nicht Kernvorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Python-Skript unwichtig?', 3, '[{"text": "Lesbarkeit", "correct": false, "because": "Fördert Wartung"}, {"text": "Fehlerbehandlung", "correct": false, "because": "Sichert Robustheit"}, {"text": "Blinkende Anzeige", "correct": true, "because": "Kein Skriptfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Bash-Skript komplexe Logik umsetzen?', 3, '[{"text": "Ja", "correct": true, "because": "Mit Schleifen und Bedingungen"}, {"text": "Nein", "correct": false, "because": "Nicht auf einfache Aufgaben beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Python-Skripte auch Systembefehle ausführen können?', 2, '[{"text": "Ja", "correct": true, "because": "Mit os oder subprocess"}, {"text": "Nein", "correct": false, "because": "Funktionalität vorhanden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool wähle ich für ein Skript zur Log-Rotation?', 4, '[{"text": "Bash", "correct": true, "because": "Einfach für Systemaufgaben"}, {"text": "HTML", "correct": false, "because": "Kein Skripttool"}, {"text": "CSS", "correct": false, "because": "Nur Styling"}]');

