-- Projektstruktur im Unternehmen präsentieren.sql (Rollen und Verantwortlichkeiten im Team oder Unternehmen definieren)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Projektstruktur nur für große Unternehmen wichtig?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Teams brauchen Klarheit"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit der Präsentation einer Projektstruktur?', 3, '[{"text": "Rollen und Verantwortlichkeiten definieren", "correct": true, "because": "Klarheit im Team schaffen"}, {"text": "Datenmenge maximieren", "correct": false, "because": "Nicht primär"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Organisation im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Projektstruktur?', 5, '[{"text": "Rollenbeschreibungen", "correct": true, "because": "Definiert Aufgaben"}, {"text": "Verantwortlichkeitsmatrix", "correct": true, "because": "Zeigt Zuständigkeiten"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Organisationsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Projektstruktur verbessert die Zusammenarbeit. b) Sie ist nur für Projektleiter nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Alle Teammitglieder profitieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Projektstruktur?', 4, '[{"text": "Rollenzuweisung", "correct": false, "because": "Kern der Struktur"}, {"text": "Verantwortlichkeiten", "correct": false, "because": "Definiert Aufgaben"}, {"text": "Visuelles Design", "correct": true, "because": "Kein Organisationsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Projektstruktur auch externe Partner einbezieht?', 2, '[{"text": "Ja", "correct": true, "because": "Kann Kooperationen abdecken"}, {"text": "Nein", "correct": false, "because": "Flexibel erweiterbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist typisch für eine Projektstruktur?', 3, '[{"text": "Organigramm", "correct": true, "because": "Visualisiert Hierarchie"}, {"text": "Hohe Serverleistung", "correct": false, "because": "Irrelevant"}, {"text": "Statische IPs", "correct": false, "because": "Kein Organisationsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden gehören zur Präsentation einer Projektstruktur?', 5, '[{"text": "RACI-Matrix", "correct": true, "because": "Definiert Verantwortlichkeiten"}, {"text": "Teamrollen", "correct": true, "because": "Klärt Aufgaben"}, {"text": "Maximale Speichergröße", "correct": false, "because": "Nicht relevant"}, {"text": "Animationseffekte", "correct": false, "because": "Kein Organisationsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Eine Projektstruktur fördert Effizienz. b) Sie ist nur für komplexe Projekte nötig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch einfache Projekte profitieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine Projektstruktur?', 4, '[{"text": "Rollenbeschreibungen", "correct": false, "because": "Definiert Verantwortlichkeiten"}, {"text": "Kommunikationswege", "correct": false, "because": "Koordination sicherstellen"}, {"text": "Grafisches Design", "correct": true, "because": "Kein Organisationsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist eine Projektstruktur nur für interne Teams?', 2, '[{"text": "Nein", "correct": true, "because": "Auch externe Partner einbeziehbar"}, {"text": "Ja", "correct": false, "because": "Flexibel anwendbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Tools unterstützen die Projektstruktur?', 4, '[{"text": "Organigramme", "correct": true, "because": "Visualisiert Struktur"}, {"text": "RACI-Diagramme", "correct": true, "because": "Klärt Verantwortlichkeiten"}, {"text": "Visuelles Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Projektstruktur nur für Projektstart nötig ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Durchgehend wichtig"}, {"text": "Ja", "correct": false, "because": "Kontinuierliche Orientierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einer Projektstruktur?', 3, '[{"text": "Klarheit der Rollen", "correct": true, "because": "Fördert Zusammenarbeit"}, {"text": "Schnelle Umsetzung", "correct": false, "because": "Gründlichkeit zählt"}, {"text": "Schriftgröße", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Projektstruktur klärt Verantwortlichkeiten. b) Sie ist nur für Führungskräfte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Alle Teammitglieder betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Projektstruktur?', 5, '[{"text": "Effiziente Zusammenarbeit", "correct": true, "because": "Klarheit fördern"}, {"text": "Reduzierte Missverständnisse", "correct": true, "because": "Rollen definiert"}, {"text": "Maximale Speichergröße", "correct": false, "because": "Nicht relevant"}, {"text": "Animationseffekte", "correct": false, "because": "Kein Organisationsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer Projektstruktur unwichtig?', 3, '[{"text": "Rollenzuweisung", "correct": false, "because": "Kern der Struktur"}, {"text": "Verantwortlichkeitsmatrix", "correct": false, "because": "Klärt Zuständigkeiten"}, {"text": "Schriftgröße", "correct": true, "because": "Kein Organisationsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist eine Projektstruktur nur für komplexe Projekte?', 3, '[{"text": "Nein", "correct": true, "because": "Auch einfache Projekte profitieren"}, {"text": "Ja", "correct": false, "because": "Universell nützlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Projektstruktur regelmäßig angepasst werden sollte?', 2, '[{"text": "Ja", "correct": true, "because": "Änderungen im Team oder Projekt"}, {"text": "Nein", "correct": false, "because": "Flexibilität nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich für eine Projektstruktur?', 4, '[{"text": "RACI-Matrix", "correct": true, "because": "Klärt Verantwortlichkeiten"}, {"text": "Zufällige Daten", "correct": false, "because": "Irrelevant"}, {"text": "Grafisches Design", "correct": false, "because": "Kein Organisationsfokus"}]');

