-- Pfad: Anwendersupport/Schutzbedarfsfeststellung/Elemente Schutzbedarfsfeststellung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind Schutzziele ein Element der Schutzbedarfsfeststellung im Anwendersupport?', 2, '[{"text": "Ja", "correct": true, "because": "Grundlage der Bewertung"}, {"text": "Nein", "correct": false, "because": "Kernbestandteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Bezieht die Schutzbedarfsfeststellung im Anwendersupport Schadensszenarien ein?', 2, '[{"text": "Ja", "correct": true, "because": "Potenzielle Schäden bewerten"}, {"text": "Nein", "correct": false, "because": "Wichtiges Element"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Risikobewertung ein Element der Schutzbedarfsfeststellung im Anwendersupport?', 2, '[{"text": "Ja", "correct": true, "because": "Gefahren einschätzen"}, {"text": "Nein", "correct": false, "because": "Teil des Prozesses"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Schutzbedarfsfeststellung im Anwendersupport ohne Systemanalyse erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Systeme müssen erfasst werden"}, {"text": "Ja", "correct": false, "because": "Erfassung essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Maßnahmen ein direktes Element der Schutzbedarfsfeststellung im Anwendersupport?', 2, '[{"text": "Nein", "correct": true, "because": "Folgen der Feststellung"}, {"text": "Ja", "correct": false, "because": "Späterer Schritt"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Element der Schutzbedarfsfeststellung im Anwendersupport definiert den Schutzbedarf?', 2, '[{"text": "Schutzziele", "correct": true, "because": "Vertraulichkeit, Integrität, Verfügbarkeit"}, {"text": "Gefährdungen", "correct": false, "because": "Risiken"}, {"text": "Maßnahmen", "correct": false, "because": "Umsetzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element der Schutzbedarfsfeststellung im Anwendersupport bewertet potenzielle Schäden?', 3, '[{"text": "Schadensszenarien", "correct": true, "because": "Auswirkungen einschätzen"}, {"text": "Systemanalyse", "correct": false, "because": "Erfassung"}, {"text": "Risikoanalyse", "correct": false, "because": "Gefahrenbewertung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element der Schutzbedarfsfeststellung im Anwendersupport identifiziert Bedrohungen?', 2, '[{"text": "Gefährdungen", "correct": true, "because": "Risiken erkennen"}, {"text": "Schutzziele", "correct": false, "because": "Schutzdefinition"}, {"text": "Systemstruktur", "correct": false, "because": "Erfassung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element der Schutzbedarfsfeststellung im Anwendersupport erfasst die Systeme?', 2, '[{"text": "Systemanalyse", "correct": true, "because": "Komponenten identifizieren"}, {"text": "Schadensszenarien", "correct": false, "because": "Schadensbewertung"}, {"text": "Maßnahmenplan", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element der Schutzbedarfsfeststellung im Anwendersupport priorisiert Risiken?', 2, '[{"text": "Risikoanalyse", "correct": true, "because": "Gefahren bewerten"}, {"text": "Schutzziele", "correct": false, "because": "Schutzdefinition"}, {"text": "Gefährdungskatalog", "correct": false, "because": "Risikoliste"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Schutzbedarfsfeststellung im Anwendersupport?', 3, '[{"text": "Schutzziele", "correct": true, "because": "Schutzbedarf definieren"}, {"text": "Gefährdungen", "correct": true, "because": "Risiken identifizieren"}, {"text": "Schadensszenarien", "correct": true, "because": "Schäden bewerten"}, {"text": "Hardwarewartung", "correct": false, "because": "Technische Maßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente der Schutzbedarfsfeststellung im Anwendersupport analysieren Risiken?', 4, '[{"text": "Gefährdungen", "correct": true, "because": "Bedrohungen erkennen"}, {"text": "Schadensszenarien", "correct": true, "because": "Schadensauswirkungen"}, {"text": "Risikoanalyse", "correct": true, "because": "Risiken bewerten"}, {"text": "Systemupdates", "correct": false, "because": "Technische Maßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schutzziele werden in der Schutzbedarfsfeststellung im Anwendersupport betrachtet?', 3, '[{"text": "Vertraulichkeit", "correct": true, "because": "Datenschutz"}, {"text": "Integrität", "correct": true, "because": "Datenkorrektheit"}, {"text": "Verfügbarkeit", "correct": true, "because": "Systemzugriff"}, {"text": "Kosteneffizienz", "correct": false, "because": "Kein Schutzziele"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente der Schutzbedarfsfeststellung im Anwendersupport sind für die Analyse essenziell?', 4, '[{"text": "Systemanalyse", "correct": true, "because": "Systeme erfassen"}, {"text": "Schutzziele", "correct": true, "because": "Schutz definieren"}, {"text": "Gefährdungen", "correct": true, "because": "Risiken identifizieren"}, {"text": "Maßnahmenkatalog", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente der Schutzbedarfsfeststellung im Anwendersupport bewerten Auswirkungen?', 3, '[{"text": "Schadensszenarien", "correct": true, "because": "Schadenspotenzial"}, {"text": "Risikoanalyse", "correct": true, "because": "Risikobewertung"}, {"text": "Schutzziele", "correct": true, "because": "Schutzbedarf festlegen"}, {"text": "Schulungen", "correct": false, "because": "Präventionsmaßnahme"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Schutzziele sind ein Element der Schutzbedarfsfeststellung im Anwendersupport. b) Maßnahmen werden direkt festgelegt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schutzziele ja, Maßnahmen später"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Schadensszenarien sind ein Element der Schutzbedarfsfeststellung. b) Systemanalyse ist optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Szenarien ja, Analyse Pflicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Gefährdungen sind ein Element der Schutzbedarfsfeststellung im Anwendersupport. b) Risikoanalyse ist kein Bestandteil.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Gefährdungen ja, Risikoanalyse dabei"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Systemanalyse ist ein Element der Schutzbedarfsfeststellung im Anwendersupport. b) Schadensszenarien betreffen nur Hardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Analyse ja, auch Software"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Risikoanalyse ist ein Element der Schutzbedarfsfeststellung im Anwendersupport. b) Schutzziele sind irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Risikoanalyse ja, Schutzziele zentral"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

