-- Pfad: Anwendersupport/Schutzbedarfsfeststellung/Sicherheitsleitlinie Schutzbedarfsfeststellung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Dient die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport als Orientierungshilfe?', 2, '[{"text": "Ja", "correct": true, "because": "Leitfaden für Prozesse"}, {"text": "Nein", "correct": false, "because": "Zweck der Leitlinie"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport Schutzziele definieren?', 2, '[{"text": "Ja", "correct": true, "because": "Grundlage für Bewertung"}, {"text": "Nein", "correct": false, "because": "Ziele erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport ohne Risikoanalyse genutzt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Risiken essenziell"}, {"text": "Ja", "correct": false, "because": "Analyse notwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport verbindlich?', 2, '[{"text": "Nein", "correct": true, "because": "Empfehlung, kein Gesetz"}, {"text": "Ja", "correct": false, "because": "Richtlinie freiwillig"}]'),
('00000000-0000-0000-0000-000000000000', 'Berücksichtigt die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport organisatorische Aspekte?', 2, '[{"text": "Ja", "correct": true, "because": "Technisch und organisatorisch"}, {"text": "Nein", "correct": false, "because": "Umfassender Ansatz"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport?', 2, '[{"text": "Schutzbedarf bewerten", "correct": true, "because": "Kernaufgabe"}, {"text": "Kosten senken", "correct": false, "because": "Nebenaspekt"}, {"text": "Systeme warten", "correct": false, "because": "Technische Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt wird in der Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport primär betrachtet?', 3, '[{"text": "Schutzziele", "correct": true, "because": "Basis der Bewertung"}, {"text": "Hardwarestatus", "correct": false, "because": "Technischer Fokus"}, {"text": "Mitarbeiterzahl", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode empfiehlt die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport?', 2, '[{"text": "Risikoanalyse", "correct": true, "because": "Gefahren bewerten"}, {"text": "Phishing-Test", "correct": false, "because": "Spezifische Maßnahme"}, {"text": "Firewall-Check", "correct": false, "because": "Technische Prüfung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport?', 2, '[{"text": "Vorgaben geben", "correct": true, "because": "Orientierung bieten"}, {"text": "Software installieren", "correct": false, "because": "Technische Aufgabe"}, {"text": "Kunden betreuen", "correct": false, "because": "Supportaufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ergebnis liefert die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport?', 2, '[{"text": "Schutzbedarfsniveau", "correct": true, "because": "Bewertung der Risiken"}, {"text": "Kostenübersicht", "correct": false, "because": "Kein Fokus"}, {"text": "Systemupdate", "correct": false, "because": "Technische Maßnahme"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente umfasst die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport?', 3, '[{"text": "Schutzziele", "correct": true, "because": "Grundlage der Bewertung"}, {"text": "Risikoanalyse", "correct": true, "because": "Gefahren identifizieren"}, {"text": "Maßnahmenvorschläge", "correct": true, "because": "Schutzempfehlungen"}, {"text": "Marketingstrategien", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schutzziele berücksichtigt die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport?', 4, '[{"text": "Vertraulichkeit", "correct": true, "because": "Datenschutz"}, {"text": "Integrität", "correct": true, "because": "Datenintegrität"}, {"text": "Verfügbarkeit", "correct": true, "because": "Systemzugriff"}, {"text": "Benutzerfreundlichkeit", "correct": false, "because": "Kein Schutzziele"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte empfiehlt die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport?', 3, '[{"text": "Systemerfassung", "correct": true, "because": "Strukturanalyse"}, {"text": "Gefährdungsanalyse", "correct": true, "because": "Risiken bewerten"}, {"text": "Schutzbedarfsbewertung", "correct": true, "because": "Schutz definieren"}, {"text": "Kundenumfrage", "correct": false, "because": "Kein Sicherheitsaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport?', 4, '[{"text": "Klare Vorgaben", "correct": true, "because": "Strukturierte Orientierung"}, {"text": "Risikoreduktion", "correct": true, "because": "Gefahren minimieren"}, {"text": "Einheitlichkeit", "correct": true, "because": "Standardisierter Ansatz"}, {"text": "Kostenoptimierung", "correct": false, "because": "Nebenaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte werden in der Sicherheitsleitlinie Schutzbedarfsfeststellung im Anwendersupport behandelt?', 3, '[{"text": "Technische Risiken", "correct": true, "because": "Systemgefahren"}, {"text": "Organisatorische Risiken", "correct": true, "because": "Menschliche Faktoren"}, {"text": "Schutzmaßnahmen", "correct": true, "because": "Abwehrstrategien"}, {"text": "Mitarbeiterzufriedenheit", "correct": false, "because": "Kein Sicherheitsfokus"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Sicherheitsleitlinie Schutzbedarfsfeststellung hilft bei der Risikoanalyse. b) Sie ist ein gesetzlicher Standard.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Risikoanalyse ja, Empfehlung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Sicherheitsleitlinie Schutzbedarfsfeststellung definiert Schutzziele. b) Sie ersetzt technische Maßnahmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schutzziele ja, Ergänzung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Sicherheitsleitlinie Schutzbedarfsfeststellung berücksichtigt organisatorische Aspekte. b) Sie ist nur für technische Systeme gedacht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Organisatorisch ja, umfassend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Sicherheitsleitlinie Schutzbedarfsfeststellung bietet Maßnahmenvorschläge. b) Sie ist verbindlich für alle Unternehmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vorschläge ja, freiwillig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Sicherheitsleitlinie Schutzbedarfsfeststellung bewertet Schutzbedarf. b) Sie konzentriert sich nur auf Hardware.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Bewertung ja, umfassend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

