INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Planung und Anforderungsanalyse > Anforderungsanalysen > Desktops & Workstations
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind Anforderungsanalysen für Desktops und Workstations immer identisch?', 2, '[{"text": "Nein", "correct": true, "because": "Workstations haben oft höhere Leistungsanforderungen"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Nutzungszwecke"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Anforderungsanalysen für Desktops und Workstations ohne Rücksicht auf Peripheriegeräte durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Peripherie beeinflusst Nutzung"}, {"text": "Ja", "correct": false, "because": "Peripherie ist oft entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Anforderungsanalysen für Desktops und Workstations zwingend die physische Arbeitsumgebung berücksichtigen?', 2, '[{"text": "Ja", "correct": true, "because": "Umgebung beeinflusst Hardwarewahl"}, {"text": "Nein", "correct": false, "because": "Umgebung ist relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine Anforderungsanalyse für Desktops und Workstations abgeschlossen, wenn die Software festgelegt ist?', 2, '[{"text": "Nein", "correct": true, "because": "Hardware und Nutzung müssen auch geprüft werden"}, {"text": "Ja", "correct": false, "because": "Software ist nur ein Teil"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Anforderungsanalysen für Desktops und Workstations ohne Kundenbeteiligung erfolgreich sein?', 2, '[{"text": "Nein", "correct": true, "because": "Kundenbedürfnisse sind zentral"}, {"text": "Ja", "correct": false, "because": "Ohne Kunden fehlt Kontext"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt unterscheidet die Anforderungsanalyse für Workstations am meisten von Desktops?', 3, '[{"text": "Leistungsanforderungen", "correct": true, "because": "Workstations für spezialisierte Aufgaben"}, {"text": "Kostenrahmen", "correct": false, "because": "Sekundär, nicht primär"}, {"text": "Betriebssystem", "correct": false, "because": "Weniger unterscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Hardware-Komponente wird bei der Anforderungsanalyse für Workstations besonders priorisiert?', 2, '[{"text": "Grafikkarte", "correct": true, "because": "Oft für CAD oder Rendering entscheidend"}, {"text": "Netzteil", "correct": false, "because": "Unterstützend, nicht primär"}, {"text": "Monitor", "correct": false, "because": "Peripherie, nicht Kern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Anforderungsanalyse für Desktops und Workstations primär?', 2, '[{"text": "Erfüllung der Kundenanforderungen", "correct": true, "because": "Kundenzufriedenheit ist zentral"}, {"text": "Minimierung der Kosten", "correct": false, "because": "Wichtig, aber sekundär"}, {"text": "Schnelle Lieferung", "correct": false, "because": "Logistisch, nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor beeinflusst die Anforderungsanalyse für Desktops und Workstations am stärksten?', 3, '[{"text": "Nutzungsprofil", "correct": true, "because": "Definiert Hardwarebedarf"}, {"text": "Markenpräferenz", "correct": false, "because": "Sekundär"}, {"text": "Lieferzeit", "correct": false, "because": "Nachgelagert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Dokument dient als Basis für die Anforderungsanalyse von Desktops und Workstations?', 2, '[{"text": "Lastenheft", "correct": true, "because": "Enthält Kundenwünsche"}, {"text": "Pflichtenheft", "correct": false, "because": "Ergebnis der Analyse"}, {"text": "Installationsplan", "correct": false, "because": "Späterer Schritt"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente werden in der Anforderungsanalyse für Desktops und Workstations geprüft?', 4, '[{"text": "Softwarekompatibilität", "correct": true, "because": "Bestimmt Hardware"}, {"text": "Leistungsbedarf", "correct": true, "because": "Definiert Spezifikationen"}, {"text": "Arbeitsumgebung", "correct": true, "because": "Beeinflusst Auswahl"}, {"text": "Lieferantenverträge", "correct": false, "because": "Nachgelagerter Prozess"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Unterschiede zwischen Desktops und Workstations werden in der Anforderungsanalyse betrachtet?', 3, '[{"text": "Rechenleistung", "correct": true, "because": "Workstations oft leistungsstärker"}, {"text": "Grafikfähigkeit", "correct": true, "because": "Workstations für spezielle Aufgaben"}, {"text": "Erweiterbarkeit", "correct": true, "because": "Workstations flexibler"}, {"text": "Farbe des Gehäuses", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Techniken werden für die Anforderungsanalyse von Desktops und Workstations genutzt?', 3, '[{"text": "Interviews", "correct": true, "because": "Direkte Kundeninformation"}, {"text": "Fragebögen", "correct": true, "because": "Strukturierte Erhebung"}, {"text": "Beobachtung", "correct": true, "because": "Praxisnahe Einsichten"}, {"text": "Simulation", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken können die Anforderungsanalyse für Desktops und Workstations beeinträchtigen?', 4, '[{"text": "Unklare Kundenangaben", "correct": true, "because": "Fehlende Präzision"}, {"text": "Fehlende Softwareangaben", "correct": true, "because": "Hardware unklar"}, {"text": "Zeitdruck", "correct": true, "because": "Oberflächliche Analyse"}, {"text": "Hardware-Defekte", "correct": false, "because": "Späteres Problem"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Hardware-Aspekte werden bei der Anforderungsanalyse für Desktops und Workstations priorisiert?', 3, '[{"text": "Prozessor", "correct": true, "because": "Rechenleistung"}, {"text": "RAM", "correct": true, "because": "Datenverarbeitung"}, {"text": "Grafikkarte", "correct": true, "because": "Visuelle Anforderungen"}, {"text": "Tastatur", "correct": false, "because": "Peripherie, weniger kritisch"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Workstations erfordern oft stärkere Grafikkarten als Desktops. b) Die Anforderungsanalyse ignoriert die Arbeitsumgebung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Grafikkarten ja, Umgebung relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Anforderungsanalyse für Desktops und Workstations basiert auf dem Lastenheft. b) Sie ist unabhängig von der Software.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Lastenheft ja, Software entscheidend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Workstations werden oft für CAD-Software analysiert. b) Desktops und Workstations haben identische RAM-Anforderungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "CAD ja, RAM unterschiedlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Anforderungsanalyse berücksichtigt den Nutzerkontext. b) Sie wird erst nach Hardwareauswahl durchgeführt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kontext ja, vorher nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Interviews sind eine Technik der Anforderungsanalyse für Desktops und Workstations. b) Die Analyse fokussiert nur auf Kosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Interviews ja, Kosten nicht allein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

