INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Planung und Anforderungsanalyse > Anforderungsanalysen > Thin Clients
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen Anforderungsanalysen für Thin Clients zwingend lokale Hardwareleistung spezifizieren?', 2, '[{"text": "Nein", "correct": true, "because": "Thin Clients nutzen Serverleistung"}, {"text": "Ja", "correct": false, "because": "Lokale Leistung ist minimal"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Anforderungsanalysen für Thin Clients ohne Berücksichtigung der Serverinfrastruktur vollständig sein?', 2, '[{"text": "Nein", "correct": true, "because": "Server sind zentral für Thin Clients"}, {"text": "Ja", "correct": false, "because": "Serverinfrastruktur ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine Anforderungsanalyse für Thin Clients unabhängig von Netzwerkanforderungen durchführbar?', 2, '[{"text": "Nein", "correct": true, "because": "Netzwerk ist kritisch für Funktion"}, {"text": "Ja", "correct": false, "because": "Netzwerk beeinflusst Leistung"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Anforderungsanalysen für Thin Clients Sicherheitsaspekte priorisieren?', 2, '[{"text": "Ja", "correct": true, "because": "Zentrale Datenhaltung erfordert Schutz"}, {"text": "Nein", "correct": false, "because": "Sicherheit ist zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Anforderungsanalysen für Thin Clients ohne Kundenbeteiligung erstellt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Kunden definieren Nutzungsszenarien"}, {"text": "Ja", "correct": false, "because": "Kundeninput ist nötig"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt ist bei der Anforderungsanalyse für Thin Clients am kritischsten?', 3, '[{"text": "Serverkapazität", "correct": true, "because": "Bestimmt Leistungsfähigkeit"}, {"text": "Monitorauflösung", "correct": false, "because": "Sekundär"}, {"text": "Tastaturlayout", "correct": false, "because": "Peripher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wird oft in Anforderungsanalysen für Thin Clients spezifiziert?', 2, '[{"text": "RDP", "correct": true, "because": "Standard für Remote Desktop"}, {"text": "HTTP", "correct": false, "because": "Webprotokoll"}, {"text": "FTP", "correct": false, "because": "Dateitransfer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ressource wird bei Thin Clients in der Anforderungsanalyse minimiert?', 2, '[{"text": "Lokale Rechenleistung", "correct": true, "because": "Server übernimmt Arbeit"}, {"text": "Netzwerkbandbreite", "correct": false, "because": "Muss hoch sein"}, {"text": "Stromverbrauch", "correct": false, "because": "Effizienz, aber nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor wird bei der Anforderungsanalyse für Thin Clients oft übersehen?', 3, '[{"text": "Latenzzeiten", "correct": true, "because": "Beeinflusst Nutzererlebnis"}, {"text": "Betriebssystem", "correct": false, "because": "Serverseitig geregelt"}, {"text": "Speichergröße", "correct": false, "because": "Lokal minimal"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Anforderungsanalyse für Thin Clients primär?', 2, '[{"text": "Effiziente Servernutzung", "correct": true, "because": "Kern der Architektur"}, {"text": "Lokale Softwareinstallation", "correct": false, "because": "Nicht relevant"}, {"text": "Hardwarevielfalt", "correct": false, "because": "Standardisierung"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente müssen in der Anforderungsanalyse für Thin Clients berücksichtigt werden?', 4, '[{"text": "Netzwerkbandbreite", "correct": true, "because": "Für Datenübertragung"}, {"text": "Serverleistung", "correct": true, "because": "Zentrale Verarbeitung"}, {"text": "Sicherheitsprotokolle", "correct": true, "because": "Schutz der Daten"}, {"text": "Lokale Festplattengröße", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile werden in der Anforderungsanalyse für Thin Clients oft betont?', 3, '[{"text": "Kosteneffizienz", "correct": true, "because": "Weniger Hardware"}, {"text": "Zentrale Verwaltung", "correct": true, "because": "Einfache Updates"}, {"text": "Energieeinsparung", "correct": true, "because": "Geringer Verbrauch"}, {"text": "Hohe lokale Leistung", "correct": false, "because": "Serverabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken können bei der Anforderungsanalyse für Thin Clients identifiziert werden?', 3, '[{"text": "Serverausfall", "correct": true, "because": "Zentrale Abhängigkeit"}, {"text": "Netzwerkunterbrechungen", "correct": true, "because": "Verbindungsverlust"}, {"text": "Hohe Latenz", "correct": true, "because": "Verzögert Nutzung"}, {"text": "Lokale Softwarefehler", "correct": false, "because": "Wenig lokal installiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Protokolle könnten in der Anforderungsanalyse für Thin Clients spezifiziert werden?', 4, '[{"text": "RDP", "correct": true, "because": "Remote Desktop"}, {"text": "Citrix ICA", "correct": true, "because": "Virtualisierung"}, {"text": "VMware PCoIP", "correct": true, "because": "VDI-Protokoll"}, {"text": "SMTP", "correct": false, "because": "E-Mail-Protokoll"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anforderungen könnten Thin Clients in einer Analyse priorisieren?', 3, '[{"text": "Hohe Verfügbarkeit", "correct": true, "because": "Kritisch für Betrieb"}, {"text": "Schnelle Datenübertragung", "correct": true, "because": "Nutzererlebnis"}, {"text": "Zentrale Updates", "correct": true, "because": "Wartungseffizienz"}, {"text": "Lokale Speicherkapazität", "correct": false, "because": "Nicht zentral"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Anforderungsanalysen für Thin Clients fokussieren Serverleistung. b) Lokale Prozessorleistung ist entscheidend.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Server ja, lokal nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Netzwerkstabilität ist in der Analyse für Thin Clients essenziell. b) Thin Clients benötigen keine Sicherheitsprotokolle.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Netzwerk ja, Sicherheit nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Thin Clients reduzieren lokale Wartungskosten. b) Anforderungsanalysen ignorieren Serverkapazität.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wartung ja, Server relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Latenzzeiten sind in der Analyse für Thin Clients wichtig. b) Lokale Softwareinstallation ist ein Fokus.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Latenz ja, Software nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Thin Clients profitieren von zentraler Verwaltung. b) Anforderungsanalysen müssen Kundennutzung einbeziehen.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Verwaltung ja, Kunden ja"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides richtig"}]');

