-- questions.sql (Datenstrom, relevant für Datenverarbeitung und IT-Grundlagen)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Datenstrom dasselbe wie eine Datenbank?', 2, '[{"text": "Nein", "correct": true, "because": "Datenstrom ist kontinuierlich, Datenbank statisch"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Konzepte"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Datenstrom?', 3, '[{"text": "Echtzeit-Datenverarbeitung", "correct": true, "because": "Kontinuierliche Datenflüsse nutzen"}, {"text": "Hardware warten", "correct": false, "because": "Kein Hardware-Fokus"}, {"text": "Software testen", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften hat ein Datenstrom?', 5, '[{"text": "Kontinuierlich", "correct": true, "because": "Fließt ununterbrochen"}, {"text": "Zeitlich geordnet", "correct": true, "because": "Sequenzielle Reihenfolge"}, {"text": "Statisch", "correct": false, "because": "Nicht statisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Datenstrom wird fortlaufend verarbeitet. b) Er ist immer begrenzt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) oft unbegrenzt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Verarbeitung eines Datenstroms?', 4, '[{"text": "Datenrate", "correct": false, "because": "Beeinflusst Verarbeitung"}, {"text": "Sequenz", "correct": false, "because": "Reihenfolge wichtig"}, {"text": "Bildschirmdesign", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Datenstrom wahlfreien Zugriff erlaubt?', 2, '[{"text": "Nein", "correct": true, "because": "Nur sequentiell"}, {"text": "Ja", "correct": false, "because": "Nicht wie Datenbank"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik wird für Datenströme oft genutzt?', 3, '[{"text": "Streaming", "correct": true, "because": "Echtzeitübertragung"}, {"text": "Batch-Verarbeitung", "correct": false, "because": "Statische Daten"}, {"text": "SQL-Abfragen", "correct": false, "because": "Datenbankfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen nutzen Datenströme?', 5, '[{"text": "Video-Streaming", "correct": true, "because": "Kontinuierliche Übertragung"}, {"text": "Sensorüberwachung", "correct": true, "because": "Echtzeitdaten"}, {"text": "Textverarbeitung", "correct": false, "because": "Statische Daten"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Datenströme sind unbegrenzt. b) Sie sind immer statisch. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen Datenstrom?', 4, '[{"text": "Echtzeitverarbeitung", "correct": false, "because": "Kernmerkmal"}, {"text": "Datenquelle", "correct": false, "because": "Liefert Daten"}, {"text": "Küchenzeile", "correct": true, "because": "Kein Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Hat ein Datenstrom eine feste Größe?', 2, '[{"text": "Nein", "correct": true, "because": "Ende oft unklar"}, {"text": "Ja", "correct": false, "because": "Kontinuierlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Algorithmen passen zu Datenströmen?', 4, '[{"text": "One-Pass", "correct": true, "because": "Einmalige Verarbeitung"}, {"text": "Fensterbasierte", "correct": true, "because": "Segmente verarbeiten"}, {"text": "SQL-Joins", "correct": false, "because": "Datenbankfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Datenströme immer gespeichert werden. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Oft flüchtig"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Datenstrom?', 3, '[{"text": "Echtzeitfähigkeit", "correct": true, "because": "Schnelle Verarbeitung"}, {"text": "Statische Speicherung", "correct": false, "because": "Nicht primär"}, {"text": "Minimale Kosten", "correct": false, "because": "Leistung zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Datenströme sind zeitlich geordnet. b) Sie erlauben wahlfreien Zugriff.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei Datenströmen?', 5, '[{"text": "Hohe Datenrate", "correct": true, "because": "Ressourcen belastend"}, {"text": "Kontinuierlichkeit", "correct": true, "because": "Keine Pausen"}, {"text": "Statische Größe", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Datenstrom unwichtig?', 3, '[{"text": "Datenfluss", "correct": false, "because": "Kernmerkmal"}, {"text": "Verarbeitungsgeschwindigkeit", "correct": false, "because": "Entscheidend"}, {"text": "Tastaturtyp", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Datenstrom pausiert werden?', 3, '[{"text": "Nein", "correct": true, "because": "Kontinuierlich definiert"}, {"text": "Ja", "correct": false, "because": "Nicht typisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Datenströme nur für Streaming sind?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Sensoren, Logs"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Datenrate?', 4, '[{"text": "Bestimmt Verarbeitungsbedarf", "correct": true, "because": "Ressourcenanpassung"}, {"text": "Erhöht Speicher", "correct": false, "because": "Flüchtig"}, {"text": "Ändert Hardware", "correct": false, "because": "Irrelevant"}]');

