-- questions.sql (DDR - Double Data Rate RAM, z. B. für Kernkomponenten)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist DDR-RAM schneller als SDR, weil es mehr Pins hat?', 2, '[{"text": "Nein", "correct": true, "because": "Geschwindigkeit durch doppelte Datenrate"}, {"text": "Ja", "correct": false, "because": "Pin-Anzahl nicht entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaft macht DDR-RAM besonders effizient?', 3, '[{"text": "Daten auf beiden Taktflanken", "correct": true, "because": "Doppelte Übertragung pro Zyklus"}, {"text": "Größerer Cache", "correct": false, "because": "Cache ist CPU-spezifisch"}, {"text": "Höhere Spannung", "correct": false, "because": "Spannung sinkt bei neueren Versionen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Leistung von DDR-RAM?', 5, '[{"text": "Taktfrequenz", "correct": true, "because": "Bestimmt Übertragungsrate"}, {"text": "Latenzzeit", "correct": true, "because": "Beeinflusst Zugriffsgeschwindigkeit"}, {"text": "Farbe des Moduls", "correct": false, "because": "Irrelevant für Leistung"}, {"text": "Anzahl der Pins", "correct": false, "because": "Nur Kompatibilität"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) DDR4 ist abwärtskompatibel mit DDR3. b) DDR5 hat mehr Bandbreite als DDR4.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "DDR-Versionen sind nicht kompatibel"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Auswahl von DDR-RAM für einen Gaming-PC?', 4, '[{"text": "Taktfrequenz", "correct": false, "because": "Wichtig für Performance"}, {"text": "Kapazität", "correct": false, "because": "Beeinflusst Multitasking"}, {"text": "Design des Kühlers", "correct": true, "because": "Rein optisch, selten funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob DDR-RAM nur in Desktops läuft?', 2, '[{"text": "Nein", "correct": true, "because": "Auch in Laptops als SO-DIMM"}, {"text": "Ja", "correct": false, "because": "Nicht auf Desktops beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche DDR-Version ist aktuell die neueste für Standard-PCs?', 3, '[{"text": "DDR5", "correct": true, "because": "Höchste Bandbreite 2025"}, {"text": "DDR4", "correct": false, "because": "Vorgängerversion"}, {"text": "DDR3", "correct": false, "because": "Ältere Technologie"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet DDR5 gegenüber älteren Versionen?', 5, '[{"text": "Höhere Bandbreite", "correct": true, "because": "Schnellere Datenübertragung"}, {"text": "Geringerer Stromverbrauch", "correct": true, "because": "Effizientere Technik"}, {"text": "Kleinere Bauform", "correct": false, "because": "Größe bleibt gleich"}, {"text": "Bessere Kühlung", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) DDR-RAM verdoppelt die Datenrate. b) Es braucht immer Dual-Channel. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dual-Channel ist optional"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was spielt bei der RAM-Auswahl keine Rolle?', 4, '[{"text": "Kompatibilität mit Mainboard", "correct": false, "because": "Muss passen"}, {"text": "Taktfrequenz", "correct": false, "because": "Beeinflusst Leistung"}, {"text": "Markenname", "correct": true, "because": "Technische Specs zählen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist DDR3 noch zeitgemäß?', 2, '[{"text": "Nein", "correct": true, "because": "Veraltet, wenig Bandbreite"}, {"text": "Ja", "correct": false, "because": "Nur für alte Systeme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen DDR-RAM für Server wichtig?', 4, '[{"text": "Hohe Kapazität", "correct": true, "because": "Für viele Prozesse"}, {"text": "Niedrige Latenz", "correct": true, "because": "Schnelle Antwortzeiten"}, {"text": "Bunte LEDs", "correct": false, "because": "Nur Deko"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass DDR5 nur für Gamer ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Server und Workstations"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Auswahl von Arbeitsspeicher?', 3, '[{"text": "Kompatibilität", "correct": true, "because": "Muss zum System passen"}, {"text": "Preis pro GB", "correct": false, "because": "Sekundär"}, {"text": "Optik", "correct": false, "because": "Kein Leistungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) DDR-RAM ist flüchtig. b) Es speichert Daten dauerhaft.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "RAM ist temporär"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Features verbessern die Leistung eines Systems?', 5, '[{"text": "Hohe RAM-Taktfrequenz", "correct": true, "because": "Schnellere Datenverarbeitung"}, {"text": "Dual-Channel-Setup", "correct": true, "because": "Doppelte Bandbreite"}, {"text": "Hohe Spannung", "correct": false, "because": "Nur bei alten Versionen"}, {"text": "RGB-Beleuchtung", "correct": false, "because": "Rein ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem RAM-Upgrade unwichtig?', 3, '[{"text": "Mainboard-Support", "correct": false, "because": "Entscheidend für Funktion"}, {"text": "Geschwindigkeit", "correct": false, "because": "Beeinflusst Performance"}, {"text": "Verpackungsdesign", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Läuft DDR4 auf DDR5-Mainboards?', 3, '[{"text": "Nein", "correct": true, "because": "Unterschiedliche Steckplätze"}, {"text": "Ja", "correct": false, "because": "Nicht kompatibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Dual-Channel die Latenz senkt?', 2, '[{"text": "Nein", "correct": true, "because": "Erhöht Bandbreite, nicht Latenz"}, {"text": "Ja", "correct": false, "because": "Latenz bleibt gleich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature ist für DDR-RAM entscheidend?', 4, '[{"text": "Doppelte Datenrate", "correct": true, "because": "Kern der Technologie"}, {"text": "Permanente Speicherung", "correct": false, "because": "RAM ist flüchtig"}, {"text": "Hohe Pin-Anzahl", "correct": false, "because": "Nicht primär"}]');

