INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > IT-Sicherheit > Datensicherheit > Verschlüsselung
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Verschlüsselung immer notwendig, um sensible Daten während der Übertragung zu schützen?', 2, '[{"text": "Ja", "correct": true, "because": "Verschlüsselung verhindert unbefugtes Abfangen"}, {"text": "Nein", "correct": false, "because": "Ohne Verschlüsselung sind Daten gefährdet"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Verschlüsselung ohne einen Schlüssel funktionieren?', 2, '[{"text": "Nein", "correct": true, "because": "Ein Schlüssel ist für Ver- und Entschlüsselung essenziell"}, {"text": "Ja", "correct": false, "because": "Schlüssel sind zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Verschlüsselung immer symmetrisch sein?', 2, '[{"text": "Nein", "correct": true, "because": "Asymmetrische Verschlüsselung ist ebenfalls möglich"}, {"text": "Ja", "correct": false, "because": "Verschiedene Methoden existieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Können verschlüsselte Daten durch Brute-Force-Angriffe entschlüsselt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Bei schwachen Schlüsseln oder Algorithmen möglich"}, {"text": "Nein", "correct": false, "because": "Risiko besteht"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Verschlüsselung dasselbe wie die Authentifizierung?', 2, '[{"text": "Nein", "correct": true, "because": "Verschlüsselung schützt Daten, Authentifizierung prüft Identität"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Konzepte"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird am häufigsten für die Verschlüsselung von Daten im Internet verwendet?', 2, '[{"text": "TLS", "correct": true, "because": "Standard für sichere Übertragung"}, {"text": "MD5", "correct": false, "because": "Hashing, nicht Verschlüsselung"}, {"text": "SHA", "correct": false, "because": "Hashing-Algorithmus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Verschlüsselung primär?', 3, '[{"text": "Vertraulichkeit der Daten", "correct": true, "because": "Schutz vor unbefugtem Zugriff"}, {"text": "Datenintegrität", "correct": false, "because": "Sekundäres Ziel"}, {"text": "Nutzeridentifikation", "correct": false, "because": "Aufgabe der Authentifizierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Algorithmus ist ein Beispiel für symmetrische Verschlüsselung?', 2, '[{"text": "AES", "correct": true, "because": "Nutzt einen Schlüssel für Ver- und Entschlüsselung"}, {"text": "RSA", "correct": false, "because": "Asymmetrisch"}, {"text": "ECC", "correct": false, "because": "Asymmetrisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schwäche kann die Verschlüsselung haben?', 2, '[{"text": "Schwach gewählte Schlüssel", "correct": true, "because": "Einfache Schlüssel sind knackbar"}, {"text": "Hohe Geschwindigkeit", "correct": false, "because": "Kein Sicherheitsproblem"}, {"text": "Geringer Speicherbedarf", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll nutzt asymmetrische Verschlüsselung für sichere Kommunikation?', 2, '[{"text": "SSL/TLS", "correct": true, "because": "Kombiniert asymmetrische und symmetrische Verschlüsselung"}, {"text": "FTP", "correct": false, "because": "Keine Verschlüsselung"}, {"text": "SMTP", "correct": false, "because": "E-Mail, nicht primär verschlüsselt"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Arten von Verschlüsselung gibt es?', 4, '[{"text": "Symmetrisch", "correct": true, "because": "Ein Schlüssel für Ver- und Entschlüsselung"}, {"text": "Asymmetrisch", "correct": true, "because": "Öffentlicher und privater Schlüssel"}, {"text": "Hybrid", "correct": true, "because": "Kombiniert symmetrisch und asymmetrisch"}, {"text": "Statisch", "correct": false, "because": "Keine Verschlüsselungsart"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Algorithmen werden häufig für die Verschlüsselung verwendet?', 3, '[{"text": "AES", "correct": true, "because": "Symmetrischer Standard"}, {"text": "RSA", "correct": true, "because": "Asymmetrischer Algorithmus"}, {"text": "DES", "correct": true, "because": "Älterer symmetrischer Algorithmus"}, {"text": "SHA", "correct": false, "because": "Hashing, nicht Verschlüsselung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Verschlüsselung?', 4, '[{"text": "Vertraulichkeit", "correct": true, "because": "Schützt vor Abhören"}, {"text": "Datenschutz", "correct": true, "because": "Sichert sensible Daten"}, {"text": "Integrität", "correct": true, "because": "Kann Manipulation erkennen"}, {"text": "Schnelle Entwicklung", "correct": false, "because": "Kein Sicherheitsvorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bedrohungen können die Verschlüsselung gefährden?', 3, '[{"text": "Schlüsselkompromittierung", "correct": true, "because": "Gefährdet Sicherheit"}, {"text": "Brute-Force-Angriffe", "correct": true, "because": "Knacken schwache Schlüssel"}, {"text": "Schwache Algorithmen", "correct": true, "because": "Leicht zu brechen"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Sicherheitsrisiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien sollten bei der Verschlüsselung beachtet werden?', 3, '[{"text": "Starke Schlüssel", "correct": true, "because": "Erhöht Sicherheit"}, {"text": "Aktuelle Algorithmen", "correct": true, "because": "Schützt vor bekannten Schwächen"}, {"text": "Sichere Schlüsselverwaltung", "correct": true, "because": "Verhindert Kompromittierung"}, {"text": "Minimale Sicherheit", "correct": false, "because": "Kontraproduktiv"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Verschlüsselung schützt die Vertraulichkeit von Daten. b) Sie funktioniert ohne Schlüssel.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vertraulichkeit ja, Schlüssel nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Asymmetrische Verschlüsselung nutzt zwei Schlüssel. b) Sie ist immer schneller als symmetrische.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zwei Schlüssel ja, Geschwindigkeit nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) TLS schützt Daten während der Übertragung. b) Verschlüsselung ist dasselbe wie Authentifizierung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "TLS ja, Authentifizierung nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Brute-Force kann Verschlüsselung knacken. b) AES ist ein asymmetrischer Algorithmus.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Brute-Force ja, AES symmetrisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Sichere Schlüsselverwaltung ist bei Verschlüsselung essenziell. b) Verschlüsselung schützt vor physischem Datendiebstahl.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verwaltung ja, physischer Diebstahl nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

