-- # Lernfeld 5: Cyberphysische Systeme > ## Qualitätssicherung > - Entwicklung evaluieren

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann die Entwicklung einer Software ohne regelmäßige Evaluierung langfristig qualitativ hochwertig bleiben?', 2, '[{"text": "Nein", "correct": true, "because": "Fehler und Schwächen bleiben unentdeckt"}, {"text": "Ja", "correct": false, "because": "Evaluierung ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Evaluierung der Entwicklung nur zu Projektbeginn notwendig?', 2, '[{"text": "Nein", "correct": true, "because": "Fortlaufende Überprüfung ist erforderlich"}, {"text": "Ja", "correct": false, "because": "Qualität muss kontinuierlich gesichert werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Metriken wie Code-Abdeckung allein die Qualität der Entwicklung vollständig bewerten?', 2, '[{"text": "Nein", "correct": true, "because": "Metriken decken nicht alle Aspekte ab"}, {"text": "Ja", "correct": false, "because": "Qualität ist vielschichtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Evaluierung der Entwicklung unabhängig von den Projektzielen?', 2, '[{"text": "Nein", "correct": true, "because": "Ziele bestimmen Bewertungskriterien"}, {"text": "Ja", "correct": false, "because": "Evaluierung orientiert sich an Zielen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine fehlende Evaluierung der Entwicklung zu höheren Wartungskosten führen?', 2, '[{"text": "Ja", "correct": true, "because": "Unentdeckte Fehler erhöhen Aufwand"}, {"text": "Nein", "correct": false, "because": "Kostensteigerung ist wahrscheinlich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug wird häufig verwendet, um die Code-Qualität während der Entwicklung zu evaluieren?', 2, '[{"text": "Statische Code-Analyse", "correct": true, "because": "Prüft Code ohne Ausführung"}, {"text": "Texteditor", "correct": false, "because": "Kein Evaluierungswerkzeug"}, {"text": "Compiler", "correct": false, "because": "Übersetzt, bewertet nicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft am besten, den Fortschritt der Entwicklung im Vergleich zu den Zielen zu bewerten?', 3, '[{"text": "Meilensteinüberprüfung", "correct": true, "because": "Vergleicht Ist mit Soll"}, {"text": "Ad-hoc-Tests", "correct": false, "because": "Unstrukturiert"}, {"text": "Dokumentenprüfung", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Entwicklung wird durch Unit-Tests primär evaluiert?', 2, '[{"text": "Funktionalität einzelner Module", "correct": true, "because": "Unit-Tests prüfen Komponenten"}, {"text": "Systemleistung", "correct": false, "because": "Leistungstests zuständig"}, {"text": "Benutzeroberfläche", "correct": false, "because": "UI-Tests zuständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium ist entscheidend, um die Qualität der Entwicklung zu bewerten?', 2, '[{"text": "Erfüllung der Anforderungen", "correct": true, "because": "Kern der Qualität"}, {"text": "Code-Länge", "correct": false, "because": "Nicht ausschlaggebend"}, {"text": "Teamgröße", "correct": false, "because": "Indirekt relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik wird genutzt, um potenzielle Fehler früh in der Entwicklung zu erkennen?', 2, '[{"text": "Code-Reviews", "correct": true, "because": "Manuelle Prüfung durch Peers"}, {"text": "Deployment", "correct": false, "because": "Spätere Phase"}, {"text": "Datenmigration", "correct": false, "because": "Unrelated"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methoden werden zur Evaluierung der Entwicklung eingesetzt?', 4, '[{"text": "Unit-Tests", "correct": true, "because": "Prüfen einzelne Funktionen"}, {"text": "Code-Reviews", "correct": true, "because": "Manuelle Qualitätskontrolle"}, {"text": "Benutzerhandbücher", "correct": false, "because": "Dokumentation, keine Evaluierung"}, {"text": "Metrikenanalyse", "correct": true, "because": "Misst Code-Qualität"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte der Entwicklung sollten bei einer Evaluierung betrachtet werden?', 3, '[{"text": "Code-Qualität", "correct": true, "because": "Lesbarkeit und Struktur"}, {"text": "Einhaltung des Zeitplans", "correct": true, "because": "Fortschritt messen"}, {"text": "Farbauswahl der IDE", "correct": false, "because": "Irrelevant"}, {"text": "Funktionalität", "correct": true, "because": "Anforderungen erfüllen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Metriken sind für die Evaluierung der Entwicklung nützlich?', 3, '[{"text": "Code-Abdeckung", "correct": true, "because": "Zeigt Testumfang"}, {"text": "Zyklomatische Komplexität", "correct": true, "because": "Misst Komplexität"}, {"text": "Anzahl der Entwickler", "correct": false, "because": "Kein Qualitätsmaß"}, {"text": "Fehlerquote", "correct": true, "because": "Zeigt Zuverlässigkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine regelmäßige Evaluierung der Entwicklung?', 4, '[{"text": "Früherkennung von Fehlern", "correct": true, "because": "Probleme früh beheben"}, {"text": "Verbesserte Qualität", "correct": true, "because": "Kontinuierliche Optimierung"}, {"text": "Geringere Teamgröße", "correct": false, "because": "Unrelated"}, {"text": "Kostensenkung", "correct": true, "because": "Weniger Nacharbeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken entstehen ohne Evaluierung der Entwicklung?', 3, '[{"text": "Qualitätsverlust", "correct": true, "because": "Fehler unentdeckt"}, {"text": "Verzögerungen", "correct": true, "because": "Probleme spät erkannt"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Eher Verlangsamung"}, {"text": "Höhere Kosten", "correct": true, "because": "Späte Korrekturen teuer"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Evaluierung der Entwicklung ist nur in agilen Projekten nötig. b) Code-Reviews verbessern die Softwarequalität.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Evaluierung immer nötig, Reviews helfen"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Metriken wie Code-Abdeckung garantieren fehlerfreie Software. b) Meilensteinüberprüfungen messen den Projektfortschritt.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Metriken nicht absolut, Meilensteine effektiv"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Unit-Tests evaluieren die Gesamtleistung der Software. b) Eine fehlende Evaluierung erhöht die Wartungskosten.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Unit-Tests modular, Kosten steigen"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Evaluierung sollte an Projektziele gekoppelt sein. b) Statische Code-Analyse ist für kleine Projekte überflüssig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ziele entscheidend, Analyse immer nützlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine regelmäßige Evaluierung kann Fehler früh erkennen. b) Die Evaluierung der Entwicklung ist nur für große Teams relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Früherkennung hilft, Größe egal"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

