-- # Lernfeld 5: Cyberphysische Systeme > ## Projektmanagement > - Entwickleraufgaben

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Können Entwickleraufgaben in einem Projekt ohne klare Zuweisung effizient erledigt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Unklare Verantwortung führt zu Chaos"}, {"text": "Ja", "correct": false, "because": "Effizienz braucht Zuordnung"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Entwickler in agilen Projekten ausschließlich für die Programmierung zuständig?', 2, '[{"text": "Nein", "correct": true, "because": "Agile Teams übernehmen oft vielfältige Rollen"}, {"text": "Ja", "correct": false, "because": "Entwickler beteiligen sich an Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Nichtverfügbarkeit eines Entwicklers ein Projekt erheblich verzögern?', 2, '[{"text": "Ja", "correct": true, "because": "Spezialisierte Aufgaben stocken"}, {"text": "Nein", "correct": false, "because": "Abhängigkeit ist real"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Entwickleraufgaben immer detailliert dokumentiert werden, um Projekterfolg zu sichern?', 2, '[{"text": "Nein", "correct": true, "because": "Flexibilität kann wichtiger sein"}, {"text": "Ja", "correct": false, "because": "Übermäßige Dokumentation bremst"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Entwickler ohne direkte Kommunikation mit dem Projektleiter effektiv arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Abstimmung ist für Klarheit nötig"}, {"text": "Ja", "correct": false, "because": "Kommunikation vermeidet Missverständnisse"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe fällt typischerweise einem Entwickler in einem Softwareprojekt zu?', 2, '[{"text": "Implementierung von Code", "correct": true, "because": "Kernaufgabe der Entwicklung"}, {"text": "Budgetplanung", "correct": false, "because": "Projektleiteraufgabe"}, {"text": "Kundenschulung", "correct": false, "because": "Nach Projektende"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Fähigkeit ist für Entwickler in einem interdisziplinären Projekt am kritischsten?', 3, '[{"text": "Teamkommunikation", "correct": true, "because": "Koordination mit anderen Disziplinen"}, {"text": "Hardwarewartung", "correct": false, "because": "Spezifisch, nicht allgemein"}, {"text": "Projektplanung", "correct": false, "because": "Managementaufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Entwickleraufgabe hat den größten Einfluss auf die Qualität des Endprodukts?', 2, '[{"text": "Code-Reviews", "correct": true, "because": "Fehler früh erkennen"}, {"text": "Dokumentation", "correct": false, "because": "Wichtig, aber sekundär"}, {"text": "Meeting-Teilnahme", "correct": false, "because": "Indirekter Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode unterstützt Entwickler am besten bei der Aufgabenpriorisierung?', 2, '[{"text": "Sprint-Planung", "correct": true, "because": "Agile Methode für Fokus"}, {"text": "Wasserfallmodell", "correct": false, "because": "Linear, weniger flexibel"}, {"text": "Ad-hoc-Entscheidung", "correct": false, "because": "Unstrukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die größte Herausforderung für Entwickler bei unklaren Anforderungen?', 2, '[{"text": "Fehlinterpretation", "correct": true, "because": "Führt zu falschen Lösungen"}, {"text": "Zeitverlust", "correct": false, "because": "Folge, nicht Ursache"}, {"text": "Technische Umsetzung", "correct": false, "because": "Sekundär"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben übernehmen Entwickler in einem typischen Softwareprojekt?', 4, '[{"text": "Programmierung", "correct": true, "because": "Kernaufgabe"}, {"text": "Testen", "correct": true, "because": "Qualitätssicherung"}, {"text": "Marketing", "correct": false, "because": "Andere Abteilung"}, {"text": "Anforderungsanalyse", "correct": true, "because": "Mitwirkung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Effizienz von Entwickleraufgaben?', 3, '[{"text": "Klare Spezifikationen", "correct": true, "because": "Reduziert Missverständnisse"}, {"text": "Zugang zu Tools", "correct": true, "because": "Fördert Produktivität"}, {"text": "Hohe Meeting-Frequenz", "correct": false, "because": "Kann ablenken"}, {"text": "Teamzusammenarbeit", "correct": true, "because": "Synergien schaffen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen begegnen Entwicklern in agilen Projekten?', 3, '[{"text": "Häufige Anpassungen", "correct": true, "because": "Agilität erfordert Flexibilität"}, {"text": "Unklare Prioritäten", "correct": true, "because": "Sprintplanung kann schwammig sein"}, {"text": "Statische Anforderungen", "correct": false, "because": "Widerspricht Agilität"}, {"text": "Zeitdruck", "correct": true, "because": "Sprints sind begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Praktiken verbessern die Arbeit von Entwicklern in Projekten?', 4, '[{"text": "Pair Programming", "correct": true, "because": "Fördert Qualität"}, {"text": "Regelmäßige Reviews", "correct": true, "because": "Fehler früh erkennen"}, {"text": "Isolierte Entwicklung", "correct": false, "because": "Hemmende Silos"}, {"text": "Kontinuierliche Integration", "correct": true, "because": "Schnelle Rückmeldung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken entstehen durch schlecht definierte Entwickleraufgaben?', 3, '[{"text": "Verzögerungen", "correct": true, "because": "Unklarheit bremst"}, {"text": "Qualitätsmängel", "correct": true, "because": "Fehlende Ziele"}, {"text": "Geringere Kosten", "correct": false, "because": "Eher höhere Kosten"}, {"text": "Fehlende Abstimmung", "correct": true, "because": "Teamdrift möglich"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Entwickler sollten keine Rolle bei der Anforderungsanalyse spielen. b) Code-Reviews erhöhen die Produktqualität.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Entwickler mitwirken, Reviews helfen"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Entwickleraufgaben sind in agilen Projekten starr festgelegt. b) Zeitdruck kann die Qualität von Entwicklerarbeit beeinträchtigen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Agilität flexibel, Zeitdruck real"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Entwickler müssen immer alle Projektphasen durchlaufen. b) Klare Kommunikation mit dem Team ist für Entwickler essenziell.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Phasen variieren, Kommunikation kritisch"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Entwickleraufgaben umfassen oft auch das Testen von Code. b) In kleinen Teams sind Entwickler von Projektmanagement ausgeschlossen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Testen üblich, Management möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Entwickler arbeiten effizienter ohne vorgegebene Deadlines. b) Kontinuierliche Integration reduziert Entwicklungsfehler.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Deadlines fokussieren, CI hilft"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

