-- # Lernfeld 5: Cyberphysische Systeme > ## Projektmanagement > - Organisation

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann eine Projektorganisation ohne klare Rollenverteilung effizient arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Unklare Rollen führen zu Konfusion und Ineffizienz"}, {"text": "Ja", "correct": false, "because": "Rollen sind für Koordination essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine flache Hierarchie in der Projektorganisation immer vorteilhafter als eine steile Hierarchie?', 2, '[{"text": "Nein", "correct": true, "because": "Vorteile hängen von Projektgröße und Komplexität ab"}, {"text": "Ja", "correct": false, "because": "Flach nicht universell besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Können temporäre Projektteams ohne feste organisatorische Struktur langfristig erfolgreich sein?', 2, '[{"text": "Nein", "correct": true, "because": "Struktur sorgt für Stabilität und Effizienz"}, {"text": "Ja", "correct": false, "because": "Fehlende Struktur behindert Koordination"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Projektorganisation unabhängig von der Unternehmenskultur gestaltbar?', 2, '[{"text": "Nein", "correct": true, "because": "Kultur beeinflusst Zusammenarbeit und Struktur"}, {"text": "Ja", "correct": false, "because": "Kulturelle Faktoren sind relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine Matrixorganisation Konflikte zwischen Projekt- und Linienmanagement vollständig vermeiden?', 2, '[{"text": "Nein", "correct": true, "because": "Doppelte Verantwortung erzeugt Spannungen"}, {"text": "Ja", "correct": false, "because": "Konflikte sind inhärent"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Organisationsform eignet sich am besten für komplexe Projekte mit vielen Abhängigkeiten?', 2, '[{"text": "Matrixorganisation", "correct": true, "because": "Flexibel und ressourceneffizient"}, {"text": "Funktionale Organisation", "correct": false, "because": "Zu starr"}, {"text": "Reine Projektorganisation", "correct": false, "because": "Ressourcen isoliert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die Hauptaufgabe eines Projektsteuerungsgremiums in der Organisation?', 3, '[{"text": "Überwachung und Entscheidungsfindung", "correct": true, "because": "Sichert strategische Ausrichtung"}, {"text": "Operative Umsetzung", "correct": false, "because": "Teamaufgabe"}, {"text": "Ressourcenbeschaffung", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Struktur minimiert Kommunikationswege in kleinen Projekten?', 2, '[{"text": "Flache Hierarchie", "correct": true, "because": "Direkte Kommunikation"}, {"text": "Steile Hierarchie", "correct": false, "because": "Mehr Ebenen"}, {"text": "Matrixstruktur", "correct": false, "because": "Komplexer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle koordiniert typischerweise die Schnittstellen zwischen Projekt und Linienorganisation?', 2, '[{"text": "Projektleiter", "correct": true, "because": "Verantwortlich für Integration"}, {"text": "Teammitglied", "correct": false, "because": "Operative Rolle"}, {"text": "Sponsor", "correct": false, "because": "Strategische Unterstützung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die größte Herausforderung einer reinen Projektorganisation?', 2, '[{"text": "Ressourcenkonflikte nach Projektende", "correct": true, "because": "Keine feste Zuordnung"}, {"text": "Langsame Entscheidungsfindung", "correct": false, "because": "Eher schnell"}, {"text": "Mangelnde Spezialisierung", "correct": false, "because": "Teams sind fokussiert"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Organisationsformen sind in der Projektmanagement-Praxis üblich?', 4, '[{"text": "Funktionale Organisation", "correct": true, "because": "Abteilungsorientiert"}, {"text": "Matrixorganisation", "correct": true, "because": "Kombiniert Linie und Projekt"}, {"text": "Chaotische Organisation", "correct": false, "because": "Kein anerkanntes Modell"}, {"text": "Reine Projektorganisation", "correct": true, "because": "Projektzentriert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Matrixorganisation?', 3, '[{"text": "Flexibler Ressourceneinsatz", "correct": true, "because": "Teilung zwischen Projekten"}, {"text": "Klare Verantwortlichkeiten", "correct": false, "because": "Oft unklar"}, {"text": "Effiziente Nutzung von Fachwissen", "correct": true, "because": "Experten verfügbar"}, {"text": "Geringe Konfliktanfälligkeit", "correct": false, "because": "Konflikte häufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente sind für eine effektive Projektorganisation essenziell?', 3, '[{"text": "Definierte Rollen", "correct": true, "because": "Klare Aufgabenverteilung"}, {"text": "Kommunikationswege", "correct": true, "because": "Koordination ermöglicht"}, {"text": "Unabhängige Teams", "correct": false, "because": "Abhängigkeiten nötig"}, {"text": "Steuerungsinstanzen", "correct": true, "because": "Überwachung erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken birgt eine funktionale Projektorganisation?', 4, '[{"text": "Silodenken", "correct": true, "because": "Abteilungen isoliert"}, {"text": "Langsame Entscheidungen", "correct": true, "because": "Mehr Hierarchieebenen"}, {"text": "Hohe Flexibilität", "correct": false, "because": "Eher unflexibel"}, {"text": "Zielkonflikte", "correct": true, "because": "Abteilung vs. Projekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Wahl der Projektorganisation?', 3, '[{"text": "Projektgröße", "correct": true, "because": "Bestimmt Strukturaufwand"}, {"text": "Unternehmenskultur", "correct": true, "because": "Formt Zusammenarbeit"}, {"text": "Externe Partner", "correct": true, "because": "Koordination nötig"}, {"text": "Softwareauswahl", "correct": false, "because": "Sekundär"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Eine Matrixorganisation erhöht die Entscheidungsgeschwindigkeit. b) Rollenkonflikte sind in der Matrixorganisation unvermeidbar.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Entscheidungen komplexer, Konflikte typisch"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine flache Hierarchie reduziert immer die Koordinationskosten. b) Eine reine Projektorganisation isoliert Teams von der Linie.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Kosten abhängig, Isolation real"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Funktionale Organisation fördert die Projektpriorität über Abteilungsziele. b) Steuerungsgremien sind in jeder Organisationsform Pflicht.', 3, '[{"text": "Beides falsch", "correct": true, "because": "Abteilung dominiert, Gremien optional"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beides falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Eine Matrixorganisation erfordert starke Kommunikationsfähigkeiten. b) In einer flachen Hierarchie gibt es keine Führungsebenen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kommunikation zentral, Ebenen bleiben"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine reine Projektorganisation löst Ressourcenkonflikte dauerhaft. b) Die Projektorganisation muss an die Projektziele angepasst sein.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Konflikte bleiben, Anpassung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

