-- # Lernfeld 5: Cyberphysische Systeme > ## Projektmanagement > - Projekte

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann ein Projekt ohne klar definierte Ziele erfolgreich abgeschlossen werden?', 2, '[{"text": "Nein", "correct": true, "because": "Ziele geben Richtung und Erfolgskriterien"}, {"text": "Ja", "correct": false, "because": "Ohne Ziele fehlt Orientierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist jedes Vorhaben mit einem festen Enddatum automatisch ein Projekt?', 2, '[{"text": "Nein", "correct": true, "because": "Projekte erfordern Einmaligkeit und Zielsetzung"}, {"text": "Ja", "correct": false, "because": "Routineaufgaben haben auch Enddaten"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Projekte ohne Ressourcenbeschränkungen effizient durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Ressourcenlimits fördern Priorisierung"}, {"text": "Ja", "correct": false, "because": "Unbegrenzte Ressourcen führen zu Ineffizienz"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle Projekte zwingend einen Projektleiter haben, um erfolgreich zu sein?', 2, '[{"text": "Nein", "correct": true, "because": "Kleine Teams können sich selbst organisieren"}, {"text": "Ja", "correct": false, "because": "Führung kann verteilt sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist ein Projekt automatisch gescheitert, wenn es den geplanten Zeitrahmen überschreitet?', 2, '[{"text": "Nein", "correct": true, "because": "Erfolg hängt von Zielerreichung ab"}, {"text": "Ja", "correct": false, "because": "Zeitüberschreitung nicht entscheidend"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal definiert ein Projekt am präzisesten?', 2, '[{"text": "Einmaligkeit", "correct": true, "because": "Unterscheidet von Routine"}, {"text": "Unbegrenzte Dauer", "correct": false, "because": "Projekte sind zeitlich begrenzt"}, {"text": "Ständige Wiederholung", "correct": false, "because": "Routine, kein Projekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die primäre Aufgabe eines Projektleiters?', 3, '[{"text": "Koordination und Überwachung", "correct": true, "because": "Sichert Zielerreichung"}, {"text": "Technische Umsetzung", "correct": false, "because": "Aufgabe des Teams"}, {"text": "Budgeterstellung", "correct": false, "because": "Teilaufgabe, nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist für den Projekterfolg am kritischsten?', 2, '[{"text": "Klare Zieldefinition", "correct": true, "because": "Ohne Ziele kein Erfolg"}, {"text": "Großes Budget", "correct": false, "because": "Nicht allein entscheidend"}, {"text": "Viele Teammitglieder", "correct": false, "because": "Qualität über Quantität"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phase markiert den offiziellen Abschluss eines Projekts?', 2, '[{"text": "Projektabschluss", "correct": true, "because": "Formaler Abschluss mit Auswertung"}, {"text": "Planung", "correct": false, "because": "Anfangsphase"}, {"text": "Durchführung", "correct": false, "because": "Umsetzungsphase"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Risiko bedroht Projekte am häufigsten?', 2, '[{"text": "Scope Creep", "correct": true, "because": "Zielverschiebung gefährdet Plan"}, {"text": "Übermäßige Dokumentation", "correct": false, "because": "Selten kritischer Faktor"}, {"text": "Zu schnelle Umsetzung", "correct": false, "because": "Eher seltenes Problem"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale definieren ein Projekt nach allgemeiner Auffassung?', 4, '[{"text": "Zeitliche Begrenzung", "correct": true, "because": "Projekte haben ein Ende"}, {"text": "Einmaligkeit", "correct": true, "because": "Keine Routine"}, {"text": "Unbegrenztes Budget", "correct": false, "because": "Ressourcen sind limitiert"}, {"text": "Zielorientierung", "correct": true, "because": "Fokus auf Ergebnisse"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren können den Erfolg eines Projekts gefährden?', 3, '[{"text": "Unklare Anforderungen", "correct": true, "because": "Fehlende Klarheit stört"}, {"text": "Mangelnde Kommunikation", "correct": true, "because": "Koordination leidet"}, {"text": "Zu viele Ressourcen", "correct": false, "because": "Eher Vorteil"}, {"text": "Zeitdruck", "correct": true, "because": "Beeinträchtigt Qualität"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phasen umfasst ein typisches Projekt?', 3, '[{"text": "Initiierung", "correct": true, "because": "Start mit Zielsetzung"}, {"text": "Planung", "correct": true, "because": "Struktur wird festgelegt"}, {"text": "Wartung", "correct": false, "because": "Nach Projektende"}, {"text": "Durchführung", "correct": true, "because": "Umsetzung der Pläne"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zu einer effektiven Projektsteuerung?', 4, '[{"text": "Ressourcenmanagement", "correct": true, "because": "Optimale Nutzung nötig"}, {"text": "Risikobewertung", "correct": true, "because": "Probleme früh erkennen"}, {"text": "Ständige Zieländerung", "correct": false, "because": "Destabilisiert Projekt"}, {"text": "Meilensteinplanung", "correct": true, "because": "Fortschritt messbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rollen sind in einem Projektteam typischerweise vertreten?', 3, '[{"text": "Projektleiter", "correct": true, "because": "Koordiniert das Team"}, {"text": "Fach experten", "correct": true, "because": "Bringen Expertise ein"}, {"text": "Kunde", "correct": false, "because": "Extern, nicht im Team"}, {"text": "Controller", "correct": true, "because": "Überwacht Budget"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Projekte können ohne Budgetbeschränkungen erfolgreich sein. b) Jede Aufgabe mit einem Team ist ein Projekt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Budget optional, Projekte sind einmalig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Projekt hat immer einen festen Start- und Endpunkt. b) Projekte sind unabhängig von externen Stakeholdern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeitlich begrenzt, Stakeholder einflussreich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der Projektabschluss umfasst nur die Übergabe des Ergebnisses. b) Risikomanagement ist essenziell für Projekte.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Abschluss umfassender, Risiken kritisch"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Projekte können ohne Planung erfolgreich sein. b) Meilensteine dienen der Fortschrittskontrolle.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Planung nötig, Meilensteine messen"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Projekt ist abgeschlossen, wenn das Budget aufgebraucht ist. b) Kommunikation ist ein Schlüsselfaktor für Projekterfolg.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Abschluss zielt auf Ergebnisse, Kommunikation entscheidend"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

