-- Hochverfügbarkeit.sql (Clustering, Redundanz)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Redundanz immer teuer?', 2, '[{"text": "Ja", "correct": true, "because": "Zusätzliche Hardware kostet"}, {"text": "Nein", "correct": false, "because": "Selten kostenneutral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wähle ich für maximale Verfügbarkeit?', 3, '[{"text": "Clustering", "correct": true, "because": "Verteilt Last und Ausfälle"}, {"text": "Einzelserver", "correct": false, "because": "Ein Ausfall stoppt alles"}, {"text": "Manuelle Backups", "correct": false, "because": "Kein Echtzeitschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen Clustering für Datenbanken nützlich?', 5, '[{"text": "Failover", "correct": true, "because": "Automatische Umschaltung"}, {"text": "Lastverteilung", "correct": true, "because": "Gleichmäßige Abfragen"}, {"text": "Geringer Speicher", "correct": false, "because": "Mehr Ressourcen nötig"}, {"text": "Einfache Einrichtung", "correct": false, "because": "Komplex zu konfigurieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Redundanz verhindert Ausfälle. b) Clustering braucht mehrere Server.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "a) ist falsch, nur Minderung"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung von Hochverfügbarkeit?', 4, '[{"text": "Failover-Mechanismen", "correct": false, "because": "Kern der Verfügbarkeit"}, {"text": "Redundante Hardware", "correct": false, "because": "Notwendig für Schutz"}, {"text": "Optisches Design", "correct": true, "because": "Technisch irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Clustering die Kosten senkt?', 2, '[{"text": "Nein", "correct": true, "because": "Mehr Server erhöhen Kosten"}, {"text": "Ja", "correct": false, "because": "Nicht primär kostensparend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature priorisiere ich für einen Webserver?', 3, '[{"text": "Load Balancing", "correct": true, "because": "Verteilt Anfragen"}, {"text": "Hohe Latenz", "correct": false, "because": "Nicht gewünscht"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Redundanz?', 5, '[{"text": "Ausfallsicherheit", "correct": true, "because": "Backup-Systeme übernehmen"}, {"text": "Kontinuierlicher Betrieb", "correct": true, "because": "Keine Downtime"}, {"text": "Geringere Kosten", "correct": false, "because": "Teurer durch Hardware"}, {"text": "Einfachere Wartung", "correct": false, "because": "Komplexität steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Clustering erhöht die Performance. b) Redundanz ist nur für große Firmen. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, auch für kleine nützlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Hochverfügbarkeit in einem kleinen Netzwerk?', 4, '[{"text": "Redundante Netzteile", "correct": false, "because": "Schutz vor Stromausfall"}, {"text": "Failover", "correct": false, "because": "Sichert Betrieb"}, {"text": "Massive Cluster", "correct": true, "because": "Übertrieben für klein"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Redundanz ohne Clustering möglich?', 2, '[{"text": "Ja", "correct": true, "because": "Z.B. redundante Hardware allein"}, {"text": "Nein", "correct": false, "because": "Nicht zwingend verknüpft"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren sind für Clustering bei einem Mailserver wichtig?', 4, '[{"text": "Synchronisation", "correct": true, "because": "Daten konsistent halten"}, {"text": "Hohe Verfügbarkeit", "correct": true, "because": "E-Mails immer erreichbar"}, {"text": "Geringer Speicher", "correct": false, "because": "Mehr Ressourcen nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Hochverfügbarkeit ohne Kosten machbar ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Hardware und Software kosten"}, {"text": "Ja", "correct": false, "because": "Kostenfrei unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich für einen Datenbankserver?', 3, '[{"text": "Failover", "correct": true, "because": "Sichert Datenverfügbarkeit"}, {"text": "Maximale Geschwindigkeit", "correct": false, "because": "Sekundär"}, {"text": "Einfache Einrichtung", "correct": false, "because": "Verfügbarkeit zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Clustering verteilt Last. b) Redundanz erhöht Latenz.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Latenz nicht primär betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat Clustering?', 5, '[{"text": "Hohe Komplexität", "correct": true, "because": "Schwierige Verwaltung"}, {"text": "Hohe Kosten", "correct": true, "because": "Mehr Server nötig"}, {"text": "Geringere Sicherheit", "correct": false, "because": "Nicht zwangsläufig"}, {"text": "Einfache Skalierung", "correct": false, "because": "Komplexität steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Hochverfügbarkeit für einen Webshop unwichtig?', 3, '[{"text": "Redundante Server", "correct": false, "because": "Sichert Betrieb"}, {"text": "Load Balancing", "correct": false, "because": "Verteilt Last"}, {"text": "Lokale Backups", "correct": true, "because": "Echtzeit wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht Redundanz die Performance?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Verfügbarkeit, nicht Geschwindigkeit"}, {"text": "Ja", "correct": false, "because": "Performance nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Clustering auch ohne Redundanz geht?', 2, '[{"text": "Ja", "correct": true, "because": "Nur Lastverteilung möglich"}, {"text": "Nein", "correct": false, "because": "Nicht zwingend gekoppelt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wähle ich für einen kritischen Server?', 4, '[{"text": "Clustering mit Redundanz", "correct": true, "because": "Maximale Sicherheit"}, {"text": "Nur Redundanz", "correct": false, "because": "Kein Lastenausgleich"}, {"text": "Einzelserver", "correct": false, "because": "Risiko zu hoch"}]');

