-- Arbeitsrecht Berufsbildung > Rechte von Auszubildenden > Recht auf Urlaub (Bundesurlaubsgesetz)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Hat ein Fachinformatiker-Anwärter auch während der Probezeit Anspruch auf Urlaub?', 2, '[{"text": "Ja", "correct": true, "because": "Das BUrlG gilt unabhängig von der Probezeit"}, {"text": "Nein", "correct": false, "because": "Urlaubsanspruch besteht ab Vertragsbeginn"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Ausbildungsunternehmen den Urlaub eines Fachinformatikers während der IHK-Prüfungsvorbereitung verweigern?', 2, '[{"text": "Nein", "correct": false, "because": "Dringende betriebliche Gründe können eine Verweigerung rechtfertigen"}, {"text": "Ja", "correct": true, "because": "§ 5 BUrlG erlaubt Verweigerung bei betrieblichen Erfordernissen"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Fachinformatiker seinen Urlaub selbstständig beantragen?', 2, '[{"text": "Ja", "correct": true, "because": "Der Antrag ist übliche Praxis gemäß BUrlG"}, {"text": "Nein", "correct": false, "because": "Der Anspruch entsteht nicht automatisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Verfällt der Urlaub eines Fachinformatikers automatisch am Jahresende?', 2, '[{"text": "Nein", "correct": true, "because": "Übertragung bis 31. März ist nach § 7 BUrlG möglich"}, {"text": "Ja", "correct": false, "because": "Urlaub kann übertragen werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Hat ein Fachinformatiker Anspruch auf Urlaubsgeld zusätzlich zum Urlaub?', 2, '[{"text": "Nein", "correct": true, "because": "Das BUrlG sieht kein Urlaubsgeld vor"}, {"text": "Ja", "correct": false, "because": "Urlaubsgeld ist tariflich oder betrieblich geregelt"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Wie viele Urlaubstage stehen einem Fachinformatiker mindestens pro Jahr zu?', 2, '[{"text": "24 Werktage", "correct": true, "because": "§ 3 BUrlG legt dies als Mindesturlaub fest"}, {"text": "20 Werktage", "correct": false, "because": "Das ist unter dem gesetzlichen Minimum"}, {"text": "30 Werktage", "correct": false, "because": "Nur bei Tarifregelung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Wann kann ein Fachinformatiker seinen Urlaub frühestens nehmen?', 2, '[{"text": "Nach sechs Monaten im Betrieb", "correct": true, "because": "§ 4 BUrlG regelt die Wartezeit"}, {"text": "Sofort nach Vertragsbeginn", "correct": false, "because": "Wartezeit ist vorgeschrieben"}, {"text": "Nach der Probezeit", "correct": false, "because": "Probezeit ist keine Bedingung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert mit dem Urlaub eines Fachinformatikers bei Kündigung vor Jahresende?', 3, '[{"text": "Er wird anteilig ausgezahlt", "correct": true, "because": "§ 6 BUrlG regelt die Abgeltung"}, {"text": "Er verfällt komplett", "correct": false, "because": "Anspruch bleibt anteilig"}, {"text": "Er wird ins nächste Jahr übertragen", "correct": false, "because": "Übertragung ist nicht möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer bestimmt den Zeitpunkt des Urlaubs eines Fachinformatikers?', 3, '[{"text": "Der Arbeitgeber unter Berücksichtigung der Wünsche", "correct": true, "because": "§ 7 BUrlG regelt die Festlegung"}, {"text": "Der Auszubildende allein", "correct": false, "because": "Wünsche sind nicht bindend"}, {"text": "Die IHK", "correct": false, "because": "IHK hat keine Rolle dabei"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche gesetzliche Grundlage regelt den Urlaubsanspruch eines Fachinformatikers?', 2, '[{"text": "Bundesurlaubsgesetz", "correct": true, "because": "Es ist die Basis für den Mindesturlaub"}, {"text": "Berufsbildungsgesetz", "correct": false, "because": "BBiG regelt die Ausbildung, nicht Urlaub"}, {"text": "Arbeitsschutzgesetz", "correct": false, "because": "ArbSchG regelt Sicherheit"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren bestimmen die Urlaubsdauer eines Fachinformatikers?', 3, '[{"text": "Arbeitszeit pro Woche", "correct": true, "because": "§ 3 BUrlG berechnet anteilig"}, {"text": "Tarifverträge", "correct": true, "because": "Können mehr Urlaub vorsehen"}, {"text": "Programmierkenntnisse", "correct": false, "because": "Irrelevant für Urlaub"}, {"text": "Dauer der Ausbildung", "correct": false, "because": "Urlaub ist jährlich geregelt"}]'),
('00000000-0000-0000-0000-000000000000', 'In welchen Fällen kann der Urlaub eines Fachinformatikers verweigert werden?', 4, '[{"text": "Dringende betriebliche Gründe", "correct": true, "because": "§ 7 BUrlG erlaubt dies"}, {"text": "Während der Berufsschule", "correct": false, "because": "Schule ist kein Ablehnungsgrund"}, {"text": "Hohe Projektlast in der IT", "correct": true, "because": "Kann betrieblich dringend sein"}, {"text": "Persönliche Abneigung des Ausbilders", "correct": false, "because": "Nicht rechtlich zulässig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rechte hat ein Fachinformatiker bezüglich seines Urlaubs?', 3, '[{"text": "Mindestens 24 Werktage pro Jahr", "correct": true, "because": "§ 3 BUrlG garantiert dies"}, {"text": "Wünsche zum Zeitpunkt äußern", "correct": true, "because": "§ 7 BUrlG berücksichtigt Wünsche"}, {"text": "Urlaub ohne Antrag nehmen", "correct": false, "because": "Antrag ist erforderlich"}, {"text": "Urlaubsgeld verlangen", "correct": false, "because": "Nicht im BUrlG enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert mit dem Urlaub eines Fachinformatikers bei längerer Krankheit?', 4, '[{"text": "Er bleibt anteilig erhalten", "correct": true, "because": "§ 4 BUrlG schützt den Anspruch"}, {"text": "Er verfällt komplett", "correct": false, "because": "Anspruch bleibt bestehen"}, {"text": "Er kann ins nächste Jahr übertragen werden", "correct": true, "because": "§ 7 BUrlG erlaubt Übertragung"}, {"text": "Er wird automatisch ausgezahlt", "correct": false, "because": "Auszahlung nur bei Vertragsende"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Regelungen gelten für den Urlaub eines Fachinformatikers in Teilzeit?', 3, '[{"text": "Anteiliger Urlaub nach Arbeitszeit", "correct": true, "because": "§ 3 BUrlG berechnet anteilig"}, {"text": "Mindestens 24 Werktage", "correct": false, "because": "Nur bei Vollzeit"}, {"text": "Keine Übertragung möglich", "correct": false, "because": "Übertragung gilt auch hier"}, {"text": "Urlaub nach Betriebszugehörigkeit", "correct": true, "because": "Wartezeit von 6 Monaten"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ein Fachinformatiker hat Anspruch auf 4 Wochen Urlaub pro Jahr. b) Der Urlaub verfällt immer am Jahresende.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "4 Wochen sind Mindestanspruch, Übertragung möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Arbeitgeber kann den Urlaub eines Fachinformatikers während der Probezeit verweigern. b) Urlaubswünsche müssen berücksichtigt werden.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Verweigerung nur bei betrieblichen Gründen"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": true, "because": "§ 7 BUrlG verlangt Berücksichtigung"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Fachinformatiker kann seinen Urlaub frei wählen. b) Bei Kündigung wird nicht genommener Urlaub ausgezahlt.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Wahl ist eingeschränkt"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": true, "because": "§ 6 BUrlG regelt Auszahlung"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Ein Fachinformatiker hat nur Anspruch auf Urlaub nach 6 Monaten. b) Tarifverträge können mehr Urlaub gewähren.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Tarife können mehr regeln"}, {"text": "Beides stimmt", "correct": true, "because": "§ 4 BUrlG und Tarifregelungen"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der Urlaub eines Fachinformatikers kann während der Berufsschule genommen werden. b) Der Arbeitgeber muss den Urlaub genehmigen.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Berufsschule ist keine Urlaubszeit"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": true, "because": "Genehmigung ist erforderlich"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

