-- Arbeitsrecht Berufsbildung > Rechte von Auszubildenden > Recht auf angemessene Ausbildung (§ 13 BBiG)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Hat ein Fachinformatiker Anspruch auf eine Ausbildung, die den Anforderungen der IHK-Prüfung entspricht?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG fordert eine angemessene Ausbildung"}, {"text": "Nein", "correct": false, "because": "Das ist gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Ausbildungsunternehmen einen Fachinformatiker ausschließlich mit Botengängen beauftragen?', 2, '[{"text": "Nein", "correct": true, "because": "§ 13 BBiG verlangt eine fachgerechte Ausbildung"}, {"text": "Ja", "correct": false, "because": "Botengänge sind keine angemessene Ausbildung"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Fachinformatiker selbst dafür sorgen, dass seine Ausbildung angemessen ist?', 2, '[{"text": "Nein", "correct": true, "because": "Der Betrieb ist nach § 13 BBiG verantwortlich"}, {"text": "Ja", "correct": false, "because": "Die Pflicht liegt beim Ausbilder"}]'),
('00000000-0000-0000-0000-000000000000', 'Darf ein Fachinformatiker eine Beschwerde bei der IHK einreichen, wenn die Ausbildung nicht angemessen ist?', 2, '[{"text": "Ja", "correct": true, "because": "Die IHK überwacht die Einhaltung von § 13 BBiG"}, {"text": "Nein", "correct": false, "because": "Das Recht auf Beschwerde besteht"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist ein Ausbildungsbetrieb verpflichtet, einem Fachinformatiker aktuelle Programmiersprachen beizubringen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG fordert eine zeitgemäße Ausbildung"}, {"text": "Nein", "correct": false, "because": "Die Ausbildung muss den aktuellen Standards entsprechen"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche gesetzliche Grundlage sichert einem Fachinformatiker eine angemessene Ausbildung?', 2, '[{"text": "§ 13 BBiG", "correct": true, "because": "Regelt die Ausbildungsqualität"}, {"text": "§ 17 BBiG", "correct": false, "because": "Bezieht sich auf Vergütung"}, {"text": "§ 22 BBiG", "correct": false, "because": "Regelt Kündigungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was sollte ein Fachinformatiker tun, wenn er keine angemessene Ausbildung erhält?', 3, '[{"text": "Den Betrieb und die IHK informieren", "correct": true, "because": "Das ist der rechtliche Weg gemäß § 13 BBiG"}, {"text": "Sofort kündigen", "correct": false, "because": "Zu radikal ohne Klärung"}, {"text": "Es hinnehmen", "correct": false, "because": "Der Anspruch ist einklagbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt gehört zu einer angemessenen Ausbildung eines Fachinformatikers?', 3, '[{"text": "Vermittlung von Programmierkenntnissen", "correct": true, "because": "Entspricht § 13 BBiG und dem Berufsbild"}, {"text": "Nur administrative Tätigkeiten", "correct": false, "because": "Nicht fachgerecht"}, {"text": "Reine Hardware-Wartung", "correct": false, "because": "Zu einseitig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer ist verpflichtet, einem Fachinformatiker eine angemessene Ausbildung zu bieten?', 2, '[{"text": "Der Ausbildungsbetrieb", "correct": true, "because": "§ 13 BBiG legt die Pflicht fest"}, {"text": "Die Berufsschule", "correct": false, "because": "Schule ergänzt nur"}, {"text": "Die IHK", "correct": false, "because": "IHK überwacht, bildet nicht aus"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Betrieb die Ausbildung eines Fachinformatikers nicht angemessen durchführt?', 3, '[{"text": "Die IHK kann einschreiten", "correct": true, "because": "Sie überwacht § 13 BBiG"}, {"text": "Der Auszubildende verliert seinen Abschluss", "correct": false, "because": "Nicht automatisch"}, {"text": "Der Betrieb zahlt automatisch Schadensersatz", "correct": false, "because": "Nur bei Klage möglich"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Inhalte müssen laut § 13 BBiG in der Ausbildung eines Fachinformatikers vermittelt werden?', 4, '[{"text": "Fachliche Kenntnisse gemäß Ausbildungsrahmenplan", "correct": true, "because": "Das ist Kern von § 13 BBiG"}, {"text": "Persönliche Interessen des Auszubildenden", "correct": false, "because": "Nicht verpflichtend"}, {"text": "Berufs- und arbeitspädagogische Qualifikationen", "correct": true, "because": "Notwendig für die Praxis"}, {"text": "Kaffee kochen für das Team", "correct": false, "because": "Keine fachliche Ausbildung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen kann ein Fachinformatiker ergreifen, wenn die Ausbildung nicht angemessen ist?', 3, '[{"text": "Betrieb darauf hinweisen", "correct": true, "because": "Erster Schritt zur Klärung"}, {"text": "IHK informieren", "correct": true, "because": "IHK überwacht die Ausbildung"}, {"text": "Sofort kündigen", "correct": false, "because": "Nicht primäre Lösung"}, {"text": "Berufsschule bitten, die Ausbildung zu übernehmen", "correct": false, "because": "Schule ist nicht zuständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zu einer angemessenen Ausbildung eines Fachinformatikers?', 4, '[{"text": "Einblick in Softwareentwicklung", "correct": true, "because": "Teil des Berufsbildes"}, {"text": "Netzwerkadministration", "correct": true, "because": "Relevanter Ausbildungsinhalt"}, {"text": "Nur Botengänge", "correct": false, "because": "Nicht fachgerecht"}, {"text": "Schulung in aktuellen Technologien", "correct": true, "because": "Zeitgemäßigkeit ist Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen drohen einem Betrieb, der § 13 BBiG nicht einhält?', 3, '[{"text": "Verwarnung durch die IHK", "correct": true, "because": "IHK kann Maßnahmen ergreifen"}, {"text": "Schadensersatzforderungen", "correct": true, "because": "Bei Nachweis möglich"}, {"text": "Automatische Schließung", "correct": false, "because": "Nicht vorgesehen"}, {"text": "Verlust der Ausbildungsberechtigung", "correct": true, "because": "Bei schweren Verstößen möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Tätigkeiten verstoßen gegen eine angemessene Ausbildung eines Fachinformatikers?', 3, '[{"text": "Nur Akten sortieren", "correct": true, "because": "Keine fachliche Qualifikation"}, {"text": "Programmieren lernen", "correct": false, "because": "Entspricht dem Berufsbild"}, {"text": "Reinigungsarbeiten im Büro", "correct": true, "because": "Nicht ausbildungsbezogen"}, {"text": "Hardware warten", "correct": false, "because": "Teil der Ausbildung"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine angemessene Ausbildung umfasst nur praktische Tätigkeiten. b) § 13 BBiG fordert auch theoretische Inhalte.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Praxis allein reicht nicht"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": true, "because": "Theorie und Praxis sind erforderlich"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Fachinformatiker hat Anspruch auf Schulung in aktuellen Programmiersprachen. b) Der Betrieb kann beliebige Tätigkeiten anordnen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Aktualität ist Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) widerspricht § 13 BBiG"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine angemessene Ausbildung muss dem Ausbildungsrahmenplan entsprechen. b) Der Auszubildende muss selbst Inhalte vorschlagen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Rahmenplan ist bindend, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Ein Betrieb darf einen Fachinformatiker nur für Hardware-Aufgaben einsetzen. b) § 13 BBiG verlangt Vielseitigkeit.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Einseitigkeit ist unzulässig"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": true, "because": "Vielseitigkeit ist vorgeschrieben"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine angemessene Ausbildung endet mit der IHK-Prüfung. b) Der Betrieb muss die Ausbildung planen.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Ausbildung umfasst den gesamten Zeitraum"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": true, "because": "Planung ist Pflicht"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

