-- Arbeitsrecht Berufsbildung > Rechte von Auszubildenden > Teilnahme an Prüfungen (§ 14 Abs. 1 BBiG)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Hat ein Fachinformatiker Anspruch auf Freistellung für die Teilnahme an der IHK-Zwischenprüfung?', 2, '[{"text": "Ja", "correct": true, "because": "§ 14 Abs. 1 BBiG verpflichtet den Betrieb dazu"}, {"text": "Nein", "correct": false, "because": "Freistellung ist gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Ausbildungsunternehmen die Teilnahme eines Fachinformatikers an der Abschlussprüfung verbieten?', 2, '[{"text": "Nein", "correct": true, "because": "§ 14 Abs. 1 BBiG garantiert das Recht auf Teilnahme"}, {"text": "Ja", "correct": false, "because": "Das Recht ist nicht einschränkbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Fachinformatiker während der Prüfungstage weiterhin im Betrieb arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "§ 14 Abs. 1 BBiG fordert Freistellung"}, {"text": "Ja", "correct": false, "because": "Arbeit während Prüfungen ist unzulässig"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist der Ausbildungsbetrieb verpflichtet, einem Fachinformatiker die Fahrtkosten zur Prüfung zu erstatten?', 2, '[{"text": "Nein", "correct": true, "because": "§ 14 Abs. 1 BBiG regelt nur Freistellung, nicht Kosten"}, {"text": "Ja", "correct": false, "because": "Kostenerstattung ist nicht vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Hat ein Fachinformatiker Anspruch auf Freistellung für Prüfungsvorbereitungskurse?', 2, '[{"text": "Ja", "correct": true, "because": "§ 14 Abs. 1 BBiG schließt Vorbereitung mit ein"}, {"text": "Nein", "correct": false, "because": "Vorbereitung gehört zur Prüfungsteilnahme"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche gesetzliche Grundlage gibt einem Fachinformatiker das Recht auf Freistellung für Prüfungen?', 2, '[{"text": "§ 14 Abs. 1 BBiG", "correct": true, "because": "Regelt die Teilnahme an Prüfungen"}, {"text": "§ 17 BBiG", "correct": false, "because": "Bezieht sich auf Vergütung"}, {"text": "§ 22 BBiG", "correct": false, "because": "Regelt Kündigungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was muss ein Fachinformatiker tun, um an der IHK-Abschlussprüfung teilnehmen zu dürfen?', 3, '[{"text": "Den Betrieb rechtzeitig informieren", "correct": true, "because": "Koordination ist erforderlich"}, {"text": "Selbstständig kündigen", "correct": false, "because": "Kündigung ist nicht nötig"}, {"text": "Die Berufsschule abschließen", "correct": false, "because": "Nicht Bedingung für Prüfung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer trägt die Verantwortung, dass ein Fachinformatiker an der Abschlussprüfung teilnehmen kann?', 2, '[{"text": "Der Ausbildungsbetrieb", "correct": true, "because": "§ 14 Abs. 1 BBiG verpflichtet den Betrieb"}, {"text": "Die Berufsschule", "correct": false, "because": "Schule organisiert nicht die Freistellung"}, {"text": "Die IHK allein", "correct": false, "because": "IHK setzt nur Termine"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Betrieb einem Fachinformatiker die Prüfungsteilnahme verweigert?', 3, '[{"text": "Der Auszubildende kann Schadensersatz fordern", "correct": true, "because": "Verletzung von § 14 Abs. 1 BBiG"}, {"text": "Die Prüfung wird automatisch verschoben", "correct": false, "because": "IHK verschiebt nicht automatisch"}, {"text": "Der Anspruch verfällt", "correct": false, "because": "Recht bleibt bestehen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz hat es, wenn ein Fachinformatiker die Prüfung aus privaten Gründen versäumt?', 3, '[{"text": "Er muss die Prüfung selbst nachholen", "correct": true, "because": "Private Gründe entbinden nicht"}, {"text": "Der Betrieb zahlt eine Strafe", "correct": false, "because": "Betrieb ist nicht verantwortlich"}, {"text": "Die IHK stellt ein Zeugnis aus", "correct": false, "because": "Zeugnis nur bei Beendigung"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Prüfungen fallen unter den Freistellungsanspruch eines Fachinformatikers nach § 14 Abs. 1 BBiG?', 4, '[{"text": "IHK-Zwischenprüfung", "correct": true, "because": "Teil der Ausbildung"}, {"text": "IHK-Abschlussprüfung", "correct": true, "because": "Pflichtprüfung"}, {"text": "Freiwillige Zertifizierungen", "correct": false, "because": "Nicht vorgeschrieben"}, {"text": "Berufsschulprüfungen", "correct": true, "because": "Teil der Ausbildung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was muss ein Ausbildungsbetrieb einem Fachinformatiker für die Prüfungsteilnahme gewähren?', 3, '[{"text": "Freistellung von der Arbeit", "correct": true, "because": "§ 14 Abs. 1 BBiG schreibt es vor"}, {"text": "Bezahlte Überstunden", "correct": false, "because": "Nicht relevant für Prüfungen"}, {"text": "Zeit für Vorbereitung", "correct": true, "because": "Vorbereitung ist inbegriffen"}, {"text": "Kosten für Lernmaterialien", "correct": false, "because": "Nicht vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat ein Fachinformatiker bei der Prüfungsteilnahme?', 3, '[{"text": "Den Betrieb rechtzeitig informieren", "correct": true, "because": "Koordination ist nötig"}, {"text": "Die Prüfungsgebühren zahlen", "correct": false, "because": "Betrieb trägt Kosten"}, {"text": "Prüfungstermine vorschlagen", "correct": false, "because": "IHK legt Termine fest"}, {"text": "Anmeldung bei der IHK durchführen", "correct": true, "because": "Teil der Mitwirkung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen drohen einem Betrieb, der die Freistellung eines Fachinformatikers für Prüfungen verweigert?', 4, '[{"text": "Schadensersatzansprüche", "correct": true, "because": "Verletzung von § 14 Abs. 1 BBiG"}, {"text": "Verwarnung durch die IHK", "correct": true, "because": "IHK kann einschreiten"}, {"text": "Automatische Vertragsauflösung", "correct": false, "because": "Vertrag bleibt bestehen"}, {"text": "Bußgelder", "correct": false, "because": "Nicht direkt vorgesehen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Unterstützung kann ein Fachinformatiker für die Prüfungsteilnahme erwarten?', 3, '[{"text": "Freistellung für Prüfungstage", "correct": true, "because": "§ 14 Abs. 1 BBiG garantiert dies"}, {"text": "Bereitstellung von Arbeitsmitteln", "correct": false, "because": "Nicht spezifisch für Prüfungen"}, {"text": "Zeit für Vorbereitungskurse", "correct": true, "because": "Teil der Freistellung"}, {"text": "Bezahlte Reisekosten", "correct": false, "because": "Nicht vorgeschrieben"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ein Fachinformatiker muss für Prüfungen freigestellt werden. b) Die Freistellung gilt nur für bestandene Prüfungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "§ 14 Abs. 1 BBiG gilt unabhängig vom Ergebnis"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) § 14 Abs. 1 BBiG gilt auch für Zusatzprüfungen. b) Der Betrieb darf die Prüfungsteilnahme aus betrieblichen Gründen verweigern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zusatzprüfungen sind inbegriffen, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Fachinformatiker hat Anspruch auf Freistellung für die Zwischenprüfung. b) Die Freistellung ist unbezahlt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Freistellung ist bezahlt gemäß § 17 BBiG"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Teilnahme an Prüfungen ist Pflicht für den Fachinformatiker. b) Der Betrieb muss die Prüfungsgebühren übernehmen.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Teilnahme ist Recht, keine Pflicht"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": true, "because": "Gebühren trägt der Betrieb"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Fachinformatiker kann die Prüfungsteilnahme verweigern. b) § 14 Abs. 1 BBiG gilt nur für Vollzeit-Auszubildende.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Teilnahme ist freiwillig, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "Gilt auch für Teilzeit"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

