-- Projektmanagement: Erhebliche Komplexität
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist erhebliche Komplexität ein typisches Merkmal jedes Projekts?', 2, '[{"text": "Ja", "correct": true, "because": "Projekte sind oft komplex"}, {"text": "Nein", "correct": false, "because": "Komplexität kann variieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor erhöht die Komplexität eines Projekts am meisten?', 3, '[{"text": "Viele beteiligte Personen", "correct": true, "because": "Koordination wird schwieriger"}, {"text": "Einfache Aufgabe", "correct": false, "because": "Verringert Komplexität"}, {"text": "Kleine Budgets", "correct": false, "because": "Weniger Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Komplexität entsteht durch viele Abhängigkeiten. b) Komplexität ist immer vermeidbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Abhängigkeiten sind typisch, Vermeidung nicht immer möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zentral"}, {"text": "Beides falsch", "correct": false, "because": "a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte tragen zur erheblichen Komplexität bei?', 4, '[{"text": "Technische Anforderungen", "correct": true, "because": "Erhöhen den Aufwand"}, {"text": "Kleine Projektdauer", "correct": false, "because": "Weniger Einfluss"}, {"text": "Unklare Ziele", "correct": true, "because": "Erschweren Planung"}, {"text": "Einzelne Person", "correct": false, "because": "Verringert Komplexität"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Projekt ohne erhebliche Komplexität erfolgreich sein?', 2, '[{"text": "Ja", "correct": true, "because": "Einfachheit kann Vorteil sein"}, {"text": "Nein", "correct": false, "because": "Komplexität ist kein Muss"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug hilft, Komplexität zu managen?', 3, '[{"text": "Projektstrukturplan", "correct": true, "because": "Strukturiert Aufgaben"}, {"text": "Farbcodierung", "correct": false, "because": "Kein direkter Nutzen"}, {"text": "Zufällige Zuweisung", "correct": false, "because": "Erhöht Chaos"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Anzahl der Teammitglieder allein ein Indikator für Komplexität?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängigkeiten sind entscheidend"}, {"text": "Ja", "correct": false, "because": "Nicht der einzige Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt macht ein IT-Projekt komplexer?', 3, '[{"text": "Viele Schnittstellen", "correct": true, "because": "Erhöhen Abstimmungsbedarf"}, {"text": "Ein Betriebssystem", "correct": false, "because": "Vereinfacht Integration"}, {"text": "Klares Budget", "correct": false, "because": "Weniger Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Komplexität steigt mit der Projektdauer. b) Komplexität hängt nur von der Teamgröße ab.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Längere Dauer erhöht Abhängigkeiten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist zu eng"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist relevant"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren erhöhen die Komplexität in der Softwareentwicklung?', 4, '[{"text": "Viele Programmiersprachen", "correct": true, "because": "Erschweren Integration"}, {"text": "Kleine Codebasis", "correct": false, "because": "Verringert Aufwand"}, {"text": "Externe Zulieferer", "correct": true, "because": "Mehr Koordination"}, {"text": "Einzelner Entwickler", "correct": false, "because": "Weniger Abstimmung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Komplexität durch klare Kommunikation reduziert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Missverständnisse werden minimiert"}, {"text": "Nein", "correct": false, "because": "Kommunikation hilft immer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element trägt nicht zur Komplexität bei?', 3, '[{"text": "Eindeutige Anforderungen", "correct": true, "because": "Vereinfachen Planung"}, {"text": "Mehrere Standorte", "correct": false, "because": "Erhöhen Abstimmung"}, {"text": "Unklare Rollen", "correct": false, "because": "Verursachen Chaos"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist jede komplexe Aufgabe ein Projekt?', 2, '[{"text": "Nein", "correct": true, "because": "Projekte haben weitere Merkmale"}, {"text": "Ja", "correct": false, "because": "Komplexität reicht nicht aus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft bei komplexen Projekten?', 3, '[{"text": "Agiles Vorgehen", "correct": true, "because": "Flexibel und iterativ"}, {"text": "Keine Planung", "correct": false, "because": "Erhöht Chaos"}, {"text": "Feste Deadlines", "correct": false, "because": "Ignoriert Komplexität"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Komplexität erfordert mehr Planung. b) Komplexität lässt sich immer eliminieren.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Planung hilft, Elimination nicht möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zentral"}, {"text": "Beides falsch", "correct": false, "because": "a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ressourcen erhöhen die Komplexität?', 4, '[{"text": "Heterogene Teams", "correct": true, "because": "Mehr Abstimmung nötig"}, {"text": "Einheitliche Tools", "correct": false, "because": "Vereinfachen Arbeit"}, {"text": "Externe Dienstleister", "correct": true, "because": "Koordination steigt"}, {"text": "Klares Budget", "correct": false, "because": "Reduziert Unsicherheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein einfaches Projekt erhebliche Komplexität haben?', 2, '[{"text": "Ja", "correct": true, "because": "Komplexität hängt von Faktoren ab"}, {"text": "Nein", "correct": false, "because": "Einfachheit schließt es nicht aus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor mindert die Komplexität?', 3, '[{"text": "Klar definierte Prozesse", "correct": true, "because": "Struktur hilft"}, {"text": "Viele Entscheidungsträger", "correct": false, "because": "Erhöht Abstimmung"}, {"text": "Unklare Ziele", "correct": false, "because": "Verstärkt Chaos"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Komplexität immer ein Nachteil?', 2, '[{"text": "Nein", "correct": true, "because": "Kann Innovation fördern"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig negativ"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Komplexität bei der Risikobewertung?', 3, '[{"text": "Erhöht Risiken", "correct": true, "because": "Mehr Unsicherheiten"}, {"text": "Senkt Risiken", "correct": false, "because": "Widerspricht Logik"}, {"text": "Kein Einfluss", "correct": false, "because": "Komplexität wirkt sich aus"}]');

