-- # Lernfeld 5: Cyberphysische Systeme > ## Datengrundlagen > - Dateiformate

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann ein Dateiformat wie CSV gleichzeitig strukturiert und maschinenlesbar sein, ohne Metadaten zu enthalten?', 2, '[{"text": "Ja", "correct": true, "because": "CSV ist strukturiert und lesbar, Metadaten optional"}, {"text": "Nein", "correct": false, "because": "Struktur reicht aus"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind proprietäre Dateiformate immer inkompatibel mit Open-Source-Software?', 2, '[{"text": "Nein", "correct": true, "because": "Kompatibilität hängt von Reverse Engineering ab"}, {"text": "Ja", "correct": false, "because": "Einige können unterstützt werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist es möglich, dass ein komprimiertes Dateiformat wie ZIP die ursprüngliche Datenstruktur vollständig verliert?', 2, '[{"text": "Nein", "correct": true, "because": "Komprimierung bewahrt Struktur beim Entpacken"}, {"text": "Ja", "correct": false, "because": "Struktur bleibt erhalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Können binäre Dateiformate ohne spezielle Software jemals menschenlesbar sein?', 2, '[{"text": "Nein", "correct": true, "because": "Binär erfordert Decoding"}, {"text": "Ja", "correct": false, "because": "Menschen lesen keine Rohdaten"}]'),
('00000000-0000-0000-0000-000000000000', 'Garantieren offene Dateiformate wie JSON eine höhere Interoperabilität als proprietäre Formate?', 2, '[{"text": "Nein", "correct": true, "because": "Interoperabilität hängt von Implementierung ab"}, {"text": "Ja", "correct": false, "because": "Offenheit allein reicht nicht"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Dateiformat eignet sich am besten für hierarchische Daten mit flexibler Struktur?', 2, '[{"text": "JSON", "correct": true, "because": "Unterstützt verschachtelte Objekte"}, {"text": "CSV", "correct": false, "because": "Flach und tabellarisch"}, {"text": "TXT", "correct": false, "because": "Keine Struktur vorgegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Dateiformat wird primär für die verlustfreie Speicherung von Rohbilddaten verwendet?', 3, '[{"text": "RAW", "correct": true, "because": "Unverarbeitete Bilddaten"}, {"text": "JPEG", "correct": false, "because": "Verlustbehaftet"}, {"text": "PNG", "correct": false, "because": "Komprimiert, aber verarbeitet"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Dateiformat ist für die Speicherung von tabellarischen Daten mit minimalem Overhead optimiert?', 2, '[{"text": "CSV", "correct": true, "because": "Einfach und leichtgewichtig"}, {"text": "XML", "correct": false, "because": "Hoher Overhead durch Tags"}, {"text": "PDF", "correct": false, "because": "Nicht für Rohdaten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Dateiformat ist am besten geeignet, um komplexe Dokumente mit Formatierung und eingebetteten Objekten zu speichern?', 2, '[{"text": "DOCX", "correct": true, "because": "Unterstützt Formatierung und Objekte"}, {"text": "JSON", "correct": false, "because": "Nur Daten, keine Formatierung"}, {"text": "BMP", "correct": false, "because": "Nur Bilder"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Dateiformat würde bei der Übertragung großer Datenmengen die geringste Bandbreite erfordern?', 2, '[{"text": "ZIP", "correct": true, "because": "Komprimierung reduziert Größe"}, {"text": "TXT", "correct": false, "because": "Keine Komprimierung"}, {"text": "XML", "correct": false, "because": "Verbose Struktur"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften charakterisieren das XML-Dateiformat?', 4, '[{"text": "Hierarchische Struktur", "correct": true, "because": "Tags definieren Hierarchie"}, {"text": "Binäre Kodierung", "correct": false, "because": "Textbasiert"}, {"text": "Selbstbeschreibend", "correct": true, "because": "Metadaten in Tags"}, {"text": "Hohe Lesbarkeit für Maschinen", "correct": true, "because": "Struktur erleichtert Parsing"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Dateiformate sind für die Speicherung von Multimedia-Inhalten geeignet?', 3, '[{"text": "MP4", "correct": true, "because": "Video und Audio"}, {"text": "WAV", "correct": true, "because": "Verlustfreier Ton"}, {"text": "CSV", "correct": false, "because": "Nur tabellarische Daten"}, {"text": "JPEG", "correct": true, "because": "Bilder"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Dateiformate könnten irrtümlich als universell lesbar angesehen werden?', 3, '[{"text": "TXT", "correct": true, "because": "Einfach, aber ohne Struktur"}, {"text": "PDF", "correct": true, "because": "Weit verbreitet, aber proprietär"}, {"text": "DOC", "correct": false, "because": "Proprietär und softwareabhängig"}, {"text": "BIN", "correct": false, "because": "Binär, nicht direkt lesbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale machen ein Dateiformat für Datenbanken besonders geeignet?', 4, '[{"text": "Schnelle Indizierung", "correct": true, "because": "Effiziente Suche"}, {"text": "Komprimierung", "correct": true, "because": "Reduziert Speicherbedarf"}, {"text": "Lesbare Textform", "correct": false, "because": "Binär oft effizienter"}, {"text": "Strukturierte Organisation", "correct": true, "because": "Erleichtert Abfragen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile können binäre Dateiformate mit sich bringen?', 3, '[{"text": "Schwierige menschliche Lesbarkeit", "correct": true, "because": "Nicht textbasiert"}, {"text": "Kompatibilitätsprobleme", "correct": true, "because": "Spezifische Software nötig"}, {"text": "Hoher Speicherbedarf", "correct": false, "because": "Kann effizient sein"}, {"text": "Fehlende Struktur", "correct": true, "because": "Ohne Dokumentation unklar"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) JSON ist ausschließlich für hierarchische Daten geeignet. b) Binäre Formate sind immer kompakter als textbasierte Formate.', 3, '[{"text": "Beides falsch", "correct": true, "because": "JSON auch flach, Binär nicht immer kompakter"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beides falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) CSV unterstützt keine verschachtelten Datenstrukturen. b) PNG ist ein verlustbehaftetes Bildformat.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "CSV flach, PNG verlustfrei"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Offene Formate wie ODT sind immer plattformunabhängig. b) Komprimierte Formate verlieren zwangsläufig Datenintegrität.', 3, '[{"text": "Beides falsch", "correct": true, "because": "ODT nicht immer unabhängig, Komprimierung meist verlustfrei"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beides falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) XML ist effizienter als CSV für große Datenmengen. b) MP3 ist ein Beispiel für ein verlustfreies Audioformat.', 3, '[{"text": "Beides falsch", "correct": true, "because": "XML verbose, MP3 verlustbehaftet"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beides falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Dateiformate wie PDF sind für die direkte Datenbearbeitung optimiert. b) YAML ist genauso maschinenlesbar wie JSON.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "PDF nicht editierbar, YAML maschinenlesbar"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

