-- Ökonomische Prinzipien.sql (Grundlegende wirtschaftliche Konzepte)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist das Wirtschaftlichkeitsprinzip immer auf Gewinnmaximierung fokussiert?', 2, '[{"text": "Nein", "correct": true, "because": "Ziel ist optimaler Einsatz von Mitteln"}, {"text": "Ja", "correct": false, "because": "Nicht nur Gewinn zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Kernziel, wenn ich knappe Ressourcen effizient nutze?', 3, '[{"text": "Kostenminimierung", "correct": true, "because": "Optimiert Einsatz bei gleichem Nutzen"}, {"text": "Maximale Auslastung", "correct": false, "because": "Nicht immer effizient"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Zu aufwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien leiten ökonomisches Handeln?', 5, '[{"text": "Wirtschaftlichkeitsprinzip", "correct": true, "because": "Maximiert Nutzen bei Kosten"}, {"text": "Rationalitätsprinzip", "correct": true, "because": "Fördert logische Entscheidungen"}, {"text": "Zufallsprinzip", "correct": false, "because": "Keine ökonomische Basis"}, {"text": "Designprinzip", "correct": false, "because": "Nicht wirtschaftsbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Das Maximumprinzip strebt höchsten Nutzen an. b) Es ignoriert Kosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Kosten sind relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Anwendung wirtschaftlicher Prinzipien?', 4, '[{"text": "Kosten-Nutzen-Analyse", "correct": false, "because": "Kern der Entscheidung"}, {"text": "Ressourcenknappheit", "correct": false, "because": "Grundlage der Ökonomie"}, {"text": "Farbauswahl", "correct": true, "because": "Irrelevant für Wirtschaftlichkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob das Minimumprinzip immer auf geringste Kosten zielt?', 2, '[{"text": "Ja", "correct": true, "because": "Geringste Kosten bei gleichem Nutzen"}, {"text": "Nein", "correct": false, "because": "Fokus ist Kostenminimierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Konzept hilft mir, Entscheidungen logisch zu treffen?', 3, '[{"text": "Rationalitätsprinzip", "correct": true, "because": "Basiert auf Nutzenmaximierung"}, {"text": "Zufallsprinzip", "correct": false, "because": "Keine Logik"}, {"text": "Designprinzip", "correct": false, "because": "Nicht ökonomisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren berücksichtige ich bei einer Kosten-Nutzen-Analyse?', 5, '[{"text": "Direkte Kosten", "correct": true, "because": "Beeinflussen Ausgaben"}, {"text": "Nutzenpotenzial", "correct": true, "because": "Bestimmt Ertrag"}, {"text": "Bürogestaltung", "correct": false, "because": "Nicht relevant"}, {"text": "Musikwahl", "correct": false, "because": "Kein ökonomischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Skaleneffekte senken Stückkosten. b) Sie erhöhen immer die Qualität. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist nicht garantiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine wirtschaftliche Entscheidung?', 4, '[{"text": "Kostenübersicht", "correct": false, "because": "Notwendig für Analyse"}, {"text": "Nutzenbewertung", "correct": false, "because": "Bestimmt Rentabilität"}, {"text": "Social-Media-Trends", "correct": true, "because": "Sekundär für Ökonomie"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist der Gewinn dasselbe wie der Umsatz?', 2, '[{"text": "Nein", "correct": true, "because": "Gewinn ist Umsatz minus Kosten"}, {"text": "Ja", "correct": false, "because": "Kosten werden abgezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien helfen bei der Ressourcenallokation?', 4, '[{"text": "Wirtschaftlichkeitsprinzip", "correct": true, "because": "Optimiert Einsatz"}, {"text": "Opportunitätskosten", "correct": true, "because": "Berücksichtigt Alternativen"}, {"text": "Farbcodierung", "correct": false, "because": "Kein ökonomischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Fixkosten immer vermieden werden können. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Fixkosten sind oft unvermeidbar"}, {"text": "Ja", "correct": false, "because": "Nicht vollständig vermeidbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einer Investitionsentscheidung?', 3, '[{"text": "Rentabilität", "correct": true, "because": "Sichert langfristigen Nutzen"}, {"text": "Schnelle Umsetzung", "correct": false, "because": "Sekundär"}, {"text": "Minimale Planung", "correct": false, "because": "Riskant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Opportunitätskosten zeigen Verzichtskosten. b) Sie sind immer monetär.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) kann nicht-monetär sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konzepte fördern effizientes Wirtschaften?', 5, '[{"text": "Skaleneffekte", "correct": true, "because": "Senken Stückkosten"}, {"text": "Spezialisierung", "correct": true, "because": "Steigert Produktivität"}, {"text": "Zufällige Ausgaben", "correct": false, "because": "Ineffizient"}, {"text": "Maximale Lagerung", "correct": false, "because": "Kann Kosten erhöhen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer Kostenanalyse unwichtig?', 3, '[{"text": "Variable Kosten", "correct": false, "because": "Beeinflussen Gesamtkosten"}, {"text": "Fixkosten", "correct": false, "because": "Grundlage der Planung"}, {"text": "Büroausstattung", "correct": true, "because": "Nur indirekt relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob das Wirtschaftlichkeitsprinzip nur für Unternehmen gilt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Privathaushalte relevant"}, {"text": "Ja", "correct": false, "because": "Universell anwendbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind variable Kosten immer produktionsabhängig?', 3, '[{"text": "Ja", "correct": true, "because": "Steigen mit Produktionsmenge"}, {"text": "Nein", "correct": false, "because": "Definition von variablen Kosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Anwendung dieser Prinzipien?', 4, '[{"text": "Optimierung eines IT-Budgets", "correct": true, "because": "Balanciert Kosten und Nutzen"}, {"text": "Erstellung eines Logos", "correct": false, "because": "Gestalterische Aufgabe"}, {"text": "Netzwerkwartung", "correct": false, "because": "Technische Priorität"}]');

