-- NAND.sql (NAND-Flash-Speichertechnologie in der IT)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass NAND-Flash-Speicher immer schneller als herkömmliche Festplatten ist. Stimmt das?', 2, '[{"text": "Ja", "correct": true, "because": "Höhere Zugriffsgeschwindigkeit"}, {"text": "Nein", "correct": false, "because": "Generell schneller"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich NAND-Flash-Speicher für ein IT-System auswähle?', 3, '[{"text": "Speicherkapazität", "correct": true, "because": "Bestimmt Nutzung"}, {"text": "Schnellste Installation", "correct": false, "because": "Leistung zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat NAND-Flash-Speicher?', 5, '[{"text": "Nichtflüchtiger Speicher", "correct": true, "because": "Daten bleiben erhalten"}, {"text": "Hohe Schreib-/Lesegeschwindigkeit", "correct": true, "because": "Schneller als HDDs"}, {"text": "Mechanische Teile", "correct": false, "because": "Keine beweglichen Teile"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) NAND-Flash-Speicher wird in SSDs verwendet. b) Er ist immer teurer als DRAM.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Billiger als DRAM"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich NAND-Flash-Speicher für ein IT-System auswähle?', 4, '[{"text": "Schreibzyklen", "correct": false, "because": "Bestimmen Lebensdauer"}, {"text": "Datenrate", "correct": false, "because": "Beeinflusst Leistung"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob NAND-Flash-Speicher flüchtig ist?', 2, '[{"text": "Nein", "correct": true, "because": "Nichtflüchtig"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit NAND-Flash-Speicher in einem IT-System?', 3, '[{"text": "Schnelle Datenspeicherung", "correct": true, "because": "Hohe Zugriffsgeschwindigkeit"}, {"text": "Schnellste Installation", "correct": false, "because": "Leistung zählt"}, {"text": "Weniger Speicher", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind bei NAND-Flash-Speicher entscheidend?', 5, '[{"text": "Lebensdauer", "correct": true, "because": "Schreibzyklen begrenzt"}, {"text": "Datenintegrität", "correct": true, "because": "Sichert Zuverlässigkeit"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) NAND-Flash-Speicher ist nichtflüchtig. b) Er hat unbegrenzte Schreibzyklen. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zyklen begrenzt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um NAND-Flash-Speicher effektiv zu nutzen?', 4, '[{"text": "Wear-Leveling", "correct": false, "because": "Verlängert Lebensdauer"}, {"text": "Controller", "correct": false, "because": "Managed Speicher"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist NAND-Flash-Speicher immer schneller als DRAM?', 2, '[{"text": "Nein", "correct": true, "because": "DRAM schneller"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet NAND-Flash-Speicher?', 4, '[{"text": "Hohe Speicherdichte", "correct": true, "because": "Große Kapazität"}, {"text": "Geringer Stromverbrauch", "correct": true, "because": "Effizient"}, {"text": "Mechanische Robustheit", "correct": true, "because": "Keine beweglichen Teile"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass NAND-Flash-Speicher nur für SSDs verwendet wird. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch USB, Speicherkarten"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um NAND-Flash-Speicher für ein System auszuwählen?', 3, '[{"text": "Schreibzyklen", "correct": true, "because": "Bestimmen Lebensdauer"}, {"text": "Schnellste Installation", "correct": false, "because": "Leistung wichtiger"}, {"text": "Bunte Optik", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) NAND-Flash-Speicher ist günstiger als DRAM. b) Er ist flüchtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nichtflüchtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei NAND-Flash-Speicher?', 5, '[{"text": "Speicherdichte", "correct": true, "because": "Bestimmt Kapazität"}, {"text": "Lebensdauer", "correct": true, "because": "Schreibzyklen begrenzt"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich NAND-Flash-Speicher auswähle?', 3, '[{"text": "Datenrate", "correct": false, "because": "Beeinflusst Leistung"}, {"text": "Controller", "correct": false, "because": "Managed Speicher"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Hat NAND-Flash-Speicher unbegrenzte Schreibzyklen?', 3, '[{"text": "Nein", "correct": true, "because": "Begrenzte Zyklen"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob NAND-Flash-Speicher mechanische Teile hat?', 2, '[{"text": "Nein", "correct": true, "because": "Keine beweglichen Teile"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für NAND-Flash-Speicher?', 4, '[{"text": "Nichtflüchtigkeit", "correct": true, "because": "Daten bleiben erhalten"}, {"text": "Schnellste Installation", "correct": false, "because": "Leistung zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');

