-- Netzwerk.sql (Allgemeine IT-Netzwerke, wie LAN, WAN, etc.)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Netzwerk immer drahtlos sein muss. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kabelgebunden möglich"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich ein Netzwerk für eine IT-Firma plane?', 3, '[{"text": "Zuverlässigkeit", "correct": true, "because": "Sichert Betrieb"}, {"text": "Schnellste Installation", "correct": false, "because": "Qualität zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zu einem Netzwerk?', 5, '[{"text": "Router", "correct": true, "because": "Leitet Daten"}, {"text": "Switches", "correct": true, "because": "Verbindet Geräte"}, {"text": "Büromöbel", "correct": false, "because": "Kein Netzwerkfaktor"}, {"text": "Farbanalyse", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Netzwerke ermöglichen Datenübertragung. b) Sie sind immer drahtlos.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch kabelgebunden"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein Netzwerk für eine IT-Firma plane?', 4, '[{"text": "Bandbreite", "correct": false, "because": "Bestimmt Leistung"}, {"text": "Sicherheit", "correct": false, "because": "Schützt Daten"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Netzwerk nur lokale Verbindungen unterstützt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch WAN möglich"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Netzwerk?', 3, '[{"text": "Datenkommunikation", "correct": true, "because": "Ermöglicht Austausch"}, {"text": "Schnellste Einrichtung", "correct": false, "because": "Funktion zählt"}, {"text": "Weniger Verbindungen", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind bei einem Netzwerk entscheidend?', 5, '[{"text": "Zuverlässigkeit", "correct": true, "because": "Sichert Betrieb"}, {"text": "Bandbreite", "correct": true, "because": "Bestimmt Leistung"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Netzwerke nutzen Protokolle wie TCP/IP. b) Sie sind immer unsicher. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Sicherheit variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um ein Netzwerk effektiv zu betreiben?', 4, '[{"text": "Router", "correct": false, "because": "Leitet Daten"}, {"text": "Netzwerkprotokolle", "correct": false, "because": "Ermöglichen Kommunikation"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Netzwerk immer drahtlos?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kabelgebunden"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Netzwerk?', 4, '[{"text": "Ressourcenfreigabe", "correct": true, "because": "Fördert Effizienz"}, {"text": "Kommunikation", "correct": true, "because": "Ermöglicht Austausch"}, {"text": "Schnellere Installation", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Netzwerk nur für große Firmen geeignet ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Netzwerke"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um ein Netzwerk effektiv zu planen?', 3, '[{"text": "Netzwerkprotokolle", "correct": true, "because": "Ermöglichen Kommunikation"}, {"text": "Günstigste Hardware", "correct": false, "because": "Qualität wichtiger"}, {"text": "Bunte Kabel", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Netzwerk kann LAN und WAN umfassen. b) Es ist immer unsicher.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Sicherheit variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei einem Netzwerk?', 5, '[{"text": "Bandbreite", "correct": true, "because": "Bestimmt Leistung"}, {"text": "Sicherheitsmaßnahmen", "correct": true, "because": "Schützen Daten"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich ein Netzwerk plane?', 3, '[{"text": "Netzwerktopologie", "correct": false, "because": "Bestimmt Struktur"}, {"text": "Protokolle", "correct": false, "because": "Ermöglichen Kommunikation"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Netzwerk immer für große Datenmengen ausgelegt?', 3, '[{"text": "Nein", "correct": true, "because": "Abhängig von Design"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Netzwerk immer eine physische Verbindung erfordert?', 2, '[{"text": "Nein", "correct": true, "because": "Auch drahtlos möglich"}, {"text": "Ya", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für ein Netzwerk?', 4, '[{"text": "Kommunikationsprotokolle", "correct": true, "because": "Ermöglichen Austausch"}, {"text": "Schnellste Installation", "correct": false, "because": "Funktion zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');

