-- Netzwerkgeraete.sql (Physische oder virtuelle Geräte, die Netzwerke verbinden oder steuern)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass alle Netzwerkgeräte immer physische Hardware sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch virtuelle Geräte möglich"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich Netzwerkgeräte für ein IT-System auswähle?', 3, '[{"text": "Funktionalität", "correct": true, "because": "Bestimmt Rolle"}, {"text": "Schnellste Installation", "correct": false, "because": "Leistung zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beispiele gibt es für Netzwerkgeräte?', 5, '[{"text": "Router", "correct": true, "because": "Leitet Daten"}, {"text": "Switch", "correct": true, "because": "Verbindet Geräte"}, {"text": "Büromöbel", "correct": false, "because": "Kein Gerät"}, {"text": "Farbanalyse", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Router ist ein Netzwerkgerät. b) Ein Switch kann keine Daten weiterleiten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Switch leitet Daten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich Netzwerkgeräte für ein IT-System auswähle?', 4, '[{"text": "Bandbreite", "correct": false, "because": "Bestimmt Leistung"}, {"text": "Kompatibilität", "correct": false, "because": "Sichert Funktion"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Netzwerkgeräte nur für kabelgebundene Netzwerke geeignet sind?', 2, '[{"text": "Nein", "correct": true, "because": "Auch drahtlos"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Netzwerkgeräten?', 3, '[{"text": "Datenkommunikation", "correct": true, "because": "Verbindet Netzwerke"}, {"text": "Schnellste Installation", "correct": false, "because": "Funktion zählt"}, {"text": "Weniger Geräte", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind bei Netzwerkgeräten entscheidend?', 5, '[{"text": "Datenrate", "correct": true, "because": "Bestimmt Leistung"}, {"text": "Zuverlässigkeit", "correct": true, "because": "Sichert Betrieb"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Hub ist ein Netzwerkgerät. b) Alle Netzwerkgeräte sind Router. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht alle Router"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Netzwerkgeräte effektiv einzusetzen?', 4, '[{"text": "Netzwerkprotokolle", "correct": false, "because": "Ermöglichen Kommunikation"}, {"text": "Konfiguration", "correct": false, "because": "Sichert Funktion"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind alle Netzwerkgeräte Router?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Switches, Hubs"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Netzwerkgeräte?', 4, '[{"text": "Datenweiterleitung", "correct": true, "because": "Verbindet Netzwerke"}, {"text": "Effiziente Kommunikation", "correct": true, "because": "Optimiert Verkehr"}, {"text": "Schnellere Installation", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Netzwerkgeräte nur für große Netzwerke geeignet sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Netzwerke"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um Netzwerkgeräte für ein IT-System auszuwählen?', 3, '[{"text": "Bandbreitenanforderungen", "correct": true, "because": "Bestimmen Leistung"}, {"text": "Günstigster Preis", "correct": false, "because": "Funktion wichtiger"}, {"text": "Bunte Optik", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Switch verbindet Geräte im LAN. b) Ein Router ist nur für WLAN geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Router auch kabelgebunden"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei Netzwerkgeräten?', 5, '[{"text": "Übertragungsrate", "correct": true, "because": "Bestimmt Leistung"}, {"text": "Netzwerktopologie", "correct": true, "because": "Beeinflusst Einsatz"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich Netzwerkgeräte auswähle?', 3, '[{"text": "Kompatibilität", "correct": false, "because": "Sichert Funktion"}, {"text": "Datenrate", "correct": false, "because": "Bestimmt Leistung"}, {"text": "Büroausstattung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Netzwerkgeräte immer physisch?', 3, '[{"text": "Nein", "correct": true, "because": "Auch virtuell möglich"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Netzwerkgeräte nur für große Netzwerke geeignet sind?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Netzwerke"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für Netzwerkgeräte?', 4, '[{"text": "Datenweiterleitung", "correct": true, "because": "Kernfunktion"}, {"text": "Schnellste Installation", "correct": false, "because": "Leistung zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');

