-- Nicht_funktionale_Anforderungen.sql (Anforderungen an Leistung, Sicherheit, Skalierbarkeit etc.)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass nicht funktionale Anforderungen immer optional sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Oft essenziell"}, {"text": "Ja", "correct": false, "because": "Zu vereinfacht"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich nicht funktionale Anforderungen für ein IT-System definiere?', 3, '[{"text": "Leistung", "correct": true, "because": "Sichert Effizienz"}, {"text": "Schnellste Umsetzung", "correct": false, "because": "Qualität zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beispiele gibt es für nicht funktionale Anforderungen?', 5, '[{"text": "Sicherheit", "correct": true, "because": "Schützt Daten"}, {"text": "Skalierbarkeit", "correct": true, "because": "Ermöglicht Wachstum"}, {"text": "Datenbearbeitung", "correct": false, "because": "Funktional"}, {"text": "Bürodesign", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Nicht funktionale Anforderungen betreffen Leistung. b) Sie definieren immer die Hauptfunktion.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist funktional"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich nicht funktionale Anforderungen für ein IT-System plane?', 4, '[{"text": "Zuverlässigkeit", "correct": false, "because": "Sichert Betrieb"}, {"text": "Benutzbarkeit", "correct": false, "because": "Fördert Akzeptanz"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Anforderungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob nicht funktionale Anforderungen nur technische Aspekte umfassen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Benutzbarkeit"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit nicht funktionalen Anforderungen?', 3, '[{"text": "Systemqualität", "correct": true, "because": "Sichert Leistung"}, {"text": "Schnellste Entwicklung", "correct": false, "because": "Qualität zählt"}, {"text": "Weniger Funktionen", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind bei nicht funktionalen Anforderungen entscheidend?', 5, '[{"text": "Verfügbarkeit", "correct": true, "because": "Sichert Zugriff"}, {"text": "Wartbarkeit", "correct": true, "because": "Erleichtert Updates"}, {"text": "Datenbearbeitung", "correct": false, "because": "Funktional"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Nicht funktionale Anforderungen beeinflussen die Benutzererfahrung. b) Sie sind immer unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wichtig für Qualität"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um nicht funktionale Anforderungen zu definieren?', 4, '[{"text": "Leistungsmetriken", "correct": false, "because": "Messen Effizienz"}, {"text": "Sicherheitsstandards", "correct": false, "because": "Schützen System"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Anforderungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind nicht funktionale Anforderungen immer technisch?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Benutzbarkeit"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten nicht funktionale Anforderungen?', 4, '[{"text": "Systemzuverlässigkeit", "correct": true, "because": "Sichert Betrieb"}, {"text": "Benutzerzufriedenheit", "correct": true, "because": "Fördert Akzeptanz"}, {"text": "Schnellere Projekte", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass nicht funktionale Anforderungen nur für große Systeme relevant sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Systeme"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um nicht funktionale Anforderungen zu definieren?', 3, '[{"text": "Leistungskriterien", "correct": true, "because": "Sichern Effizienz"}, {"text": "Günstigste Lösung", "correct": false, "because": "Qualität wichtiger"}, {"text": "Bunte Diagramme", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Skalierbarkeit ist eine nicht funktionale Anforderung. b) Sie beschreibt die Hauptfunktion.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist funktional"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei nicht funktionalen Anforderungen?', 5, '[{"text": "Sicherheit", "correct": true, "because": "Schützt Daten"}, {"text": "Leistung", "correct": true, "because": "Sichert Effizienz"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich nicht funktionale Anforderungen definiere?', 3, '[{"text": "Verfügbarkeit", "correct": false, "because": "Sichert Zugriff"}, {"text": "Wartbarkeit", "correct": false, "because": "Erleichtert Updates"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Anforderungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind nicht funktionale Anforderungen immer optional?', 3, '[{"text": "Nein", "correct": true, "because": "Oft essenziell"}, {"text": "Ja", "correct": false, "because": "Falsche Annahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob nicht funktionale Anforderungen nur technische Aspekte betreffen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Benutzbarkeit"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für nicht funktionale Anforderungen?', 4, '[{"text": "Systemqualität", "correct": true, "because": "Sichert Leistung"}, {"text": "Schnellste Entwicklung", "correct": false, "because": "Qualität zählt"}, {"text": "Bürogestaltung", "correct": false, "because": "Irrelevant"}]');

