-- Wireframes (Sketch, Erster Entwurf, Strukturplanung).sql (Grundgerüst der UI-Planung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Wireframes detaillierte Designs mit Farben?', 2, '[{"text": "Nein", "correct": true, "because": "Sie zeigen nur die Struktur"}, {"text": "Ja", "correct": false, "because": "Details kommen in Mockups"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Wireframe?', 3, '[{"text": "Strukturplanung", "correct": true, "because": "Fokus auf Layout und Navigation"}, {"text": "Visuelle Ästhetik", "correct": false, "because": "Das ist für Mockups"}, {"text": "Funktionalität testen", "correct": false, "because": "Das macht ein Prototyp"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören typischerweise in ein Wireframe?', 5, '[{"text": "Platzhalter für Inhalte", "correct": true, "because": "Zeigt Positionen an"}, {"text": "Grundlegende Navigation", "correct": true, "because": "Definiert den Ablauf"}, {"text": "Farbschemata", "correct": false, "because": "Nicht Teil eines Wireframes"}, {"text": "Interaktive Buttons", "correct": false, "because": "Für Prototypen relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Wireframes sind erste Entwürfe. b) Sie enthalten fertigen Code.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wireframes sind skizzenhaft, kein Code"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Wireframe, wenn ich die Struktur plane?', 4, '[{"text": "Typografie", "correct": true, "because": "Kommt später im Design"}, {"text": "Anordnung der Elemente", "correct": false, "because": "Kern des Wireframes"}, {"text": "Benutzerfluss", "correct": false, "because": "Wichtig für die Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Wireframes auch für Kundenpräsentationen taugen?', 2, '[{"text": "Nein", "correct": true, "because": "Zu grob für Endkunden"}, {"text": "Ja", "correct": false, "because": "Mockups sind besser dafür"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool nutze ich für einfache Wireframes?', 3, '[{"text": "Sketch", "correct": true, "because": "Ideal für schnelle Entwürfe"}, {"text": "Figma", "correct": false, "because": "Eher für detaillierte Designs"}, {"text": "Photoshop", "correct": false, "because": "Zu komplex für Wireframes"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ansätze helfen bei der Erstellung eines Wireframes?', 5, '[{"text": "Handskizzen", "correct": true, "because": "Schnell und einfach"}, {"text": "Digitale Tools", "correct": true, "because": "Präziser und teilbar"}, {"text": "Code-Implementierung", "correct": false, "because": "Nicht Teil eines Wireframes"}, {"text": "Farbauswahl", "correct": false, "because": "Später im Prozess"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Wireframes sind grobe Skizzen. b) Sie zeigen das endgültige Design. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Enddesign kommt in Mockups"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht in einem Wireframe für eine App?', 4, '[{"text": "Navigationsstruktur", "correct": false, "because": "Kernmerkmal eines Wireframes"}, {"text": "Platzhalter für Bilder", "correct": false, "because": "Zeigt Inhaltsbereiche"}, {"text": "Animationen", "correct": true, "because": "Für Prototypen relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Wireframes nur für Designer nützlich?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Entwickler und Stakeholder"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind für ein Wireframe essenziell?', 4, '[{"text": "Grundlayout", "correct": true, "because": "Definiert die Struktur"}, {"text": "Boxen für Inhalte", "correct": true, "because": "Zeigt Platzierung"}, {"text": "Detaillierte Grafiken", "correct": false, "because": "Nicht Teil eines Wireframes"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Wireframes interaktiv sein müssen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Sie sind statisch"}, {"text": "Ja", "correct": false, "because": "Interaktivität ist für Prototypen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Wireframe für eine Website?', 3, '[{"text": "Benutzerfluss", "correct": true, "because": "Definiert die Navigation"}, {"text": "Farben", "correct": false, "because": "Später im Design"}, {"text": "Schriftarten", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Wireframes sind schnell erstellt. b) Sie enthalten visuelle Details.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Details kommen später"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Tools eignen sich für Wireframes?', 5, '[{"text": "Papier und Stift", "correct": true, "because": "Schnell und kostengünstig"}, {"text": "Balsamiq", "correct": true, "because": "Einfach und fokussiert"}, {"text": "Adobe Illustrator", "correct": false, "because": "Zu detailliert"}, {"text": "VS Code", "correct": false, "because": "Für Code, nicht Skizzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Wireframe für ein kleines Team unwichtig?', 3, '[{"text": "Klarheit der Struktur", "correct": false, "because": "Immer essenziell"}, {"text": "Lesbarkeit", "correct": false, "because": "Wichtig für Verständnis"}, {"text": "Detaillierte Beschriftung", "correct": true, "because": "Kann bei Kleinteams grob sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal mit Wireframes? Sind sie für jedes Projekt nötig?', 3, '[{"text": "Nein", "correct": true, "because": "Kleine Projekte können ohne auskommen"}, {"text": "Ja", "correct": false, "because": "Abhängig von Komplexität"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Wireframes auch Feedback einholen können?', 2, '[{"text": "Ja", "correct": true, "because": "Frühe Rückmeldung möglich"}, {"text": "Nein", "correct": false, "because": "Struktur ist diskutierbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element wähle ich für ein Wireframe, um Inhalte zu zeigen?', 4, '[{"text": "Rechtecke als Platzhalter", "correct": true, "because": "Einfach und klar"}, {"text": "Echte Bilder", "correct": false, "because": "Zu detailliert"}, {"text": "Klickbare Links", "correct": false, "because": "Nicht interaktiv"}]');

