INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > OpenData und API-Schnittstellen
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind OpenData-Daten immer frei von Nutzungsbeschränkungen?', 2, '[{"text": "Nein", "correct": true, "because": "Nutzungsbedingungen können je nach Quelle variieren"}, {"text": "Ja", "correct": false, "because": "Beschränkungen wie Lizenzen sind üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Können API-Schnittstellen verwendet werden, um OpenData automatisiert abzurufen?', 2, '[{"text": "Ja", "correct": true, "because": "APIs ermöglichen automatisierte Datenabfragen"}, {"text": "Nein", "correct": false, "because": "Automatisierung ist Hauptzweck von APIs"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen OpenData-Daten immer in Echtzeit verfügbar sein?', 2, '[{"text": "Nein", "correct": true, "because": "Verfügbarkeit hängt von der Quelle ab"}, {"text": "Ja", "correct": false, "because": "Nicht alle Daten sind live"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine API-Schlüssel-Authentifizierung bei allen OpenData-APIs erforderlich?', 2, '[{"text": "Nein", "correct": true, "because": "Manche APIs sind frei zugänglich"}, {"text": "Ja", "correct": false, "because": "Nicht immer notwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Können OpenData-Daten nur über APIs bereitgestellt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Downloads wie CSV sind üblich"}, {"text": "Ja", "correct": false, "because": "Mehrere Formate möglich"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt OpenData primär?', 2, '[{"text": "Öffentlichen Zugang zu Daten ermöglichen", "correct": true, "because": "Fördert Transparenz"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Nicht primär"}, {"text": "Daten verkaufen", "correct": false, "because": "Gegen OpenData-Prinzip"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Format wird häufig für API-Schnittstellen bei OpenData verwendet?', 3, '[{"text": "JSON", "correct": true, "because": "Maschinenlesbar und weit verbreitet"}, {"text": "PDF", "correct": false, "because": "Nicht maschinenlesbar"}, {"text": "DOCX", "correct": false, "because": "Ungeeignet für APIs"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Art von API wird oft für OpenData genutzt?', 2, '[{"text": "REST", "correct": true, "because": "Flexibel und weit verbreitet"}, {"text": "SOAP", "correct": false, "because": "Komplexer"}, {"text": "FTP", "correct": false, "because": "Kein API-Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil bietet die Nutzung von API-Schnittstellen für OpenData?', 2, '[{"text": "Automatisierter Datenzugriff", "correct": true, "because": "Ermöglicht effiziente Abfragen"}, {"text": "Höhere Sicherheit", "correct": false, "because": "Nicht primär"}, {"text": "Geringere Kosten", "correct": false, "because": "Nicht direkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einschränkung kann OpenData haben?', 2, '[{"text": "Lizenzbedingungen", "correct": true, "because": "Nutzung kann eingeschränkt sein"}, {"text": "Echtzeitverfügbarkeit", "correct": false, "because": "Nicht immer zutreffend"}, {"text": "Datenvolumen", "correct": false, "because": "Nicht primär"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Formate sind typisch für OpenData über APIs?', 4, '[{"text": "JSON", "correct": true, "because": "Maschinenlesbar"}, {"text": "XML", "correct": true, "because": "Strukturiert und verbreitet"}, {"text": "CSV", "correct": true, "because": "Einfach und kompatibel"}, {"text": "DOCX", "correct": false, "because": "Ungeeignet für APIs"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Nutzung von API-Schnittstellen für OpenData?', 3, '[{"text": "Automatisierter Zugriff", "correct": true, "because": "Effizienzsteigerung"}, {"text": "Echtzeitdaten", "correct": true, "because": "Möglich bei Live-APIs"}, {"text": "Flexibilität", "correct": true, "because": "Anpassbare Abfragen"}, {"text": "Höhere Kosten", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anforderungen muss eine OpenData-API erfüllen?', 4, '[{"text": "Maschinenlesbarkeit", "correct": true, "because": "Grundprinzip von APIs"}, {"text": "Dokumentation", "correct": true, "because": "Nutzung erleichtern"}, {"text": "Offener Zugang", "correct": true, "because": "OpenData-Prinzip"}, {"text": "Echtzeitpflicht", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einschränkungen können OpenData-APIs haben?', 3, '[{"text": "Lizenzbedingungen", "correct": true, "because": "Nutzung kann reguliert sein"}, {"text": "API-Schlüssel", "correct": true, "because": "Zugriffskontrolle möglich"}, {"text": "Datenaktualität", "correct": true, "because": "Nicht immer live"}, {"text": "Unbegrenzte Bandbreite", "correct": false, "because": "Limits üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte der Softwareplanung unterstützen OpenData-APIs?', 3, '[{"text": "API-Dokumentation lesen", "correct": true, "because": "Verständnis der Schnittstelle"}, {"text": "Datenformate unterstützen", "correct": true, "because": "Kompatibilität sicherstellen"}, {"text": "Automatisierte Abfragen", "correct": true, "because": "Effizienz erhöhen"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Nicht primär"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) OpenData-Daten können über APIs abgerufen werden. b) Sie sind immer in Echtzeit verfügbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "APIs ja, Echtzeit nicht immer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) API-Schnittstellen ermöglichen automatisierten Datenzugriff. b) OpenData ist immer frei von Lizenzen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Automatisierung ja, Lizenzen möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) JSON ist ein typisches Format für OpenData-APIs. b) APIs sind immer authentifizierungsfrei.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "JSON ja, Authentifizierung oft nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) OpenData fördert Transparenz durch APIs. b) Alle OpenData-Daten sind maschinenlesbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Transparenz ja, nicht alle maschinenlesbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) API-Dokumentation ist für OpenData-Nutzung hilfreich. b) OpenData erfordert immer Echtzeitdaten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dokumentation ja, Echtzeit nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

