-- IT-Sicherheitskonzepte.sql (Überblick über Sicherheitsanforderungen und -prinzipien, z. B. Schutz vor Bedrohungen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist IT-Sicherheit nur für große Unternehmen relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Alle Systeme sind anfällig"}, {"text": "Ja", "correct": false, "because": "Auch kleine Firmen sind Ziele"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit IT-Sicherheitskonzepten?', 3, '[{"text": "Schutz vor Bedrohungen", "correct": true, "because": "Sichert Daten und Systeme"}, {"text": "Maximale Performance", "correct": false, "because": "Sekundär"}, {"text": "Kostensenkung", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien gehören zu IT-Sicherheitskonzepten?', 5, '[{"text": "Vertraulichkeit", "correct": true, "because": "Schützt Daten vor Zugriff"}, {"text": "Integrität", "correct": true, "because": "Sichert Datenkorrektheit"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nicht sicherheitsrelevant"}, {"text": "Schnelle Installation", "correct": false, "because": "Kein Sicherheitsprinzip"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) IT-Sicherheit schützt vor unbefugtem Zugriff. b) Sie ist nur für Hardware wichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Software ist betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem IT-Sicherheitskonzept?', 4, '[{"text": "Bedrohungsanalyse", "correct": false, "because": "Kern der Planung"}, {"text": "Schutzziele", "correct": false, "because": "Definiert Anforderungen"}, {"text": "Designpräferenzen", "correct": true, "because": "Nicht sicherheitsrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob IT-Sicherheit auch physische Aspekte umfasst?', 2, '[{"text": "Ja", "correct": true, "because": "Z. B. Zugang zu Serverräumen"}, {"text": "Nein", "correct": false, "because": "Physische Sicherheit zählt dazu"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Konzept schützt Daten vor unbefugtem Zugriff?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Macht Daten unlesbar"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nur Leistung"}, {"text": "Statische IPs", "correct": false, "because": "Kein direkter Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bedrohungen berücksichtige ich in einem Sicherheitskonzept?', 5, '[{"text": "Malware", "correct": true, "because": "Schädigt Systeme"}, {"text": "Phishing", "correct": true, "because": "Zielt auf Nutzer"}, {"text": "Langsame Hardware", "correct": false, "because": "Kein Sicherheitsrisiko"}, {"text": "Unsortierte Daten", "correct": false, "because": "Kein direkter Angriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) IT-Sicherheit ist proaktiv. b) Sie reagiert nur auf Angriffe. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Prävention ist zentral"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein IT-Sicherheitskonzept?', 4, '[{"text": "Risikoanalyse", "correct": false, "because": "Identifiziert Schwachstellen"}, {"text": "Schutzmaßnahmen", "correct": false, "because": "Schützt vor Bedrohungen"}, {"text": "Farbschema", "correct": true, "because": "Irrelevant für Sicherheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist IT-Sicherheit nur technisch?', 2, '[{"text": "Nein", "correct": true, "because": "Auch organisatorisch wichtig"}, {"text": "Ja", "correct": false, "because": "Prozesse spielen mit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen gehören zu einem Sicherheitskonzept?', 4, '[{"text": "Firewall", "correct": true, "because": "Schützt Netzwerke"}, {"text": "Passwortrichtlinien", "correct": true, "because": "Sichert Zugänge"}, {"text": "Schnelle CPUs", "correct": false, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass IT-Sicherheit nur Software betrifft. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Hardware und Netzwerke auch"}, {"text": "Ja", "correct": false, "because": "Sicherheit ist ganzheitlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich in einem IT-Sicherheitskonzept?', 3, '[{"text": "Bedrohungserkennung", "correct": true, "because": "Frühwarnsystem"}, {"text": "Designoptik", "correct": false, "because": "Nicht relevant"}, {"text": "Speichergröße", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Verfügbarkeit ist ein Sicherheitsprinzip. b) Sicherheit kostet immer Leistung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Leistungseinbußen sind nicht zwingend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schutzziele sind in der IT-Sicherheit zentral?', 5, '[{"text": "Authentizität", "correct": true, "because": "Verifiziert Identitäten"}, {"text": "Nachvollziehbarkeit", "correct": true, "because": "Ermöglicht Rückverfolgung"}, {"text": "Hohe Geschwindigkeit", "correct": false, "because": "Kein Sicherheitsziel"}, {"text": "Minimaler Speicher", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung von IT-Sicherheit?', 3, '[{"text": "Potenzielle Angriffe", "correct": false, "because": "Müssen analysiert werden"}, {"text": "Sicherheitsrichtlinien", "correct": false, "because": "Leitlinien sind nötig"}, {"text": "Visuelle Gestaltung", "correct": true, "because": "Kein Sicherheitsaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal mit Sicherheit? Ist sie nur präventiv?', 3, '[{"text": "Nein", "correct": true, "because": "Auch reaktiv nötig"}, {"text": "Ja", "correct": false, "because": "Reaktion auf Angriffe zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob IT-Sicherheit auch rechtliche Aspekte hat?', 2, '[{"text": "Ja", "correct": true, "because": "Z. B. Datenschutzgesetze"}, {"text": "Nein", "correct": false, "because": "Gesetze sind relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Mittel schützt vor Datenmanipulation?', 4, '[{"text": "Hash-Funktionen", "correct": true, "because": "Sichern Integrität"}, {"text": "Schnelle Netzwerke", "correct": false, "because": "Kein Schutz"}, {"text": "Große Festplatten", "correct": false, "because": "Irrelevant"}]');

