-- Java-Datenstrukturen (ArrayList, HashMap).sql (Java-spezifische Implementierungen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist eine ArrayList in Java immer dynamisch anpassbar?', 2, '[{"text": "Ja", "correct": true, "because": "Sie wächst automatisch bei Bedarf"}, {"text": "Nein", "correct": false, "because": "Größenänderung ist immer möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode nutze ich, um ein Element in einer ArrayList zu finden?', 3, '[{"text": "indexOf()", "correct": true, "because": "Gibt den Index des Elements zurück"}, {"text": "get()", "correct": false, "because": "Nur Zugriff per Index"}, {"text": "containsKey()", "correct": false, "because": "Das ist für HashMap"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen eine HashMap in Java besonders nützlich?', 5, '[{"text": "Schneller Schlüsselzugriff", "correct": true, "because": "O(1) im Durchschnitt"}, {"text": "Erlaubt null-Schlüssel", "correct": true, "because": "Ein null-Schlüssel ist möglich"}, {"text": "Automatische Sortierung", "correct": false, "because": "HashMap sortiert nicht"}, {"text": "Feste Größe", "correct": false, "because": "Sie ist dynamisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) ArrayList erlaubt Duplikate. b) HashMap erlaubt doppelte Schlüssel.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "HashMap überschreibt bei gleichen Schlüsseln"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl zwischen ArrayList und HashMap in Java?', 4, '[{"text": "Zugriffszeit", "correct": false, "because": "Entscheidend für die Wahl"}, {"text": "Schlüssel-Wert-Paare", "correct": false, "because": "Kernmerkmal von HashMap"}, {"text": "Thread-Sicherheit", "correct": true, "because": "Beide sind standardmäßig nicht thread-sicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine ArrayList in Java schneller als ein Array ist?', 2, '[{"text": "Nein", "correct": true, "because": "ArrayList hat Overhead durch Objekte"}, {"text": "Ja", "correct": false, "because": "Array ist direkter"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Operation ist bei einer HashMap in Java am teuersten?', 3, '[{"text": "Schlüsselkollisionen auflösen", "correct": true, "because": "Kann O(n) werden"}, {"text": "put()", "correct": false, "because": "Normalerweise O(1)"}, {"text": "get()", "correct": false, "because": "Auch O(1) im Idealfall"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden nutze ich, um eine ArrayList in Java zu durchlaufen?', 5, '[{"text": "for-Schleife mit get()", "correct": true, "because": "Klassischer Indexzugriff"}, {"text": "forEach()", "correct": true, "because": "Funktionale Iteration"}, {"text": "put()", "correct": false, "because": "Das ist für HashMap"}, {"text": "keySet()", "correct": false, "because": "Für HashMap-Schlüssel"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) ArrayList hat O(1) für Hinzufügen. b) HashMap hat O(1) für Suche. Stimmt das?', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "ArrayList ist O(n) bei vollem Array"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer ArrayList in Java unwichtig, wenn ich nur lese?', 4, '[{"text": "Kapazität", "correct": true, "because": "Nur bei Schreiben relevant"}, {"text": "Elementanzahl", "correct": false, "because": "Bestimmt Schleifengrenze"}, {"text": "Indexzugriff", "correct": false, "because": "Kernmerkmal beim Lesen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Hat HashMap in Java eine feste Größe?', 2, '[{"text": "Nein", "correct": true, "because": "Sie wächst dynamisch"}, {"text": "Ja", "correct": false, "because": "Kapazität passt sich an"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Struktur in Java wähle ich für schnelle Schlüsselabfragen?', 4, '[{"text": "HashMap", "correct": true, "because": "O(1) Zugriff auf Schlüssel"}, {"text": "ArrayList", "correct": false, "because": "O(n) Suche"}, {"text": "LinkedList", "correct": false, "because": "Auch O(n)"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ArrayList in Java thread-sicher ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Standardmäßig nicht synchronisiert"}, {"text": "Ja", "correct": false, "because": "Nur mit Collections.synchronizedList()"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einer HashMap, wenn ich viele Werte speichere?', 3, '[{"text": "Lastfaktor", "correct": true, "because": "Beeinflusst Performance bei Kollisionen"}, {"text": "Sortierreihenfolge", "correct": false, "because": "HashMap sortiert nicht"}, {"text": "Indexposition", "correct": false, "because": "Irrelevant für HashMap"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) ArrayList ist gut für zufälligen Zugriff. b) HashMap ist besser für indizierte Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "HashMap nutzt Schlüssel, nicht Indizes"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Operationen sind bei einer ArrayList in Java besonders langsam?', 5, '[{"text": "Einfügen am Anfang", "correct": true, "because": "O(n) durch Verschiebung"}, {"text": "Entfernen am Anfang", "correct": true, "because": "Ebenfalls O(n)"}, {"text": "Zugriff per Index", "correct": false, "because": "O(1)"}, {"text": "Hinzufügen am Ende", "correct": false, "because": "O(1) amortisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einer HashMap, wenn ich nur lese?', 3, '[{"text": "Schreibzugriff", "correct": true, "because": "Nur für Änderungen relevant"}, {"text": "Schlüsselzugriff", "correct": false, "because": "Kernmerkmal beim Lesen"}, {"text": "Kollisionen", "correct": false, "because": "Beeinflusst Lesezeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal mit der ArrayList? Ist sie für große Datenmengen ideal?', 3, '[{"text": "Nein", "correct": true, "because": "Einfügen und Löschen sind langsam"}, {"text": "Ja", "correct": false, "because": "Nur Zugriff ist schnell"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine HashMap in Java sortierte Schlüssel braucht?', 2, '[{"text": "Nein", "correct": true, "because": "Ungeordnetes Schlüssel-Wert-Paar"}, {"text": "Ja", "correct": false, "because": "Für Sortierung gibt’s TreeMap"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Struktur wähle ich in Java für eine Liste mit häufigem Einfügen?', 4, '[{"text": "LinkedList", "correct": true, "because": "O(1) für Einfügen an bekanntem Punkt"}, {"text": "ArrayList", "correct": false, "because": "O(n) für Verschiebung"}, {"text": "HashMap", "correct": false, "because": "Keine Listenstruktur"}]');

