-- Liskov Substitution Principle (austauschbare Unterklassen ohne Probleme).sql (Schlüssel für austauschbare Unterklassen ohne Probleme, z. B. Vererbung ohne Nebenwirkungen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Gilt das Liskov Substitution Principle nur für Vererbung?', 2, '[{"text": "Ja", "correct": true, "because": "Fokus auf Unterklassen"}, {"text": "Nein", "correct": false, "because": "Primär Vererbung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit dem Liskov Substitution Principle?', 3, '[{"text": "Austauschbarkeit von Unterklassen", "correct": true, "because": "Keine unerwarteten Effekte"}, {"text": "Code kürzen", "correct": false, "because": "Nicht primär"}, {"text": "Performance steigern", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften fördert das Liskov Substitution Principle?', 5, '[{"text": "Konsistenz", "correct": true, "because": "Verhalten bleibt gleich"}, {"text": "Flexibilität", "correct": true, "because": "Unterklassen austauschbar"}, {"text": "Schnellere Ausführung", "correct": false, "because": "Kein Performance-Ziel"}, {"text": "Weniger Klassen", "correct": false, "because": "Unabhängig davon"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) LSP erlaubt Unterklassen-Austausch. b) Es ignoriert Oberklassen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Oberklassen definieren Verhalten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich beim Liskov Substitution Principle?', 4, '[{"text": "Vererbungshierarchie", "correct": false, "because": "Kern des Prinzips"}, {"text": "Verhaltenskonsistenz", "correct": false, "because": "Muss erhalten bleiben"}, {"text": "UI-Design", "correct": true, "because": "Kein Code-Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob LSP Nebenwirkungen erlaubt?', 2, '[{"text": "Nein", "correct": true, "because": "Verhalten muss konsistent sein"}, {"text": "Ja", "correct": false, "because": "Widerspricht LSP"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel verstößt gegen das Liskov Substitution Principle?', 3, '[{"text": "Unterklasse wirft neue Exceptions", "correct": true, "because": "Bricht Konsistenz"}, {"text": "Unterklasse erweitert Methode", "correct": false, "because": "Erlaubt, wenn konsistent"}, {"text": "Unterklasse nutzt Interface", "correct": false, "because": "Unterstützt LSP"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind beim Liskov Substitution Principle wichtig?', 5, '[{"text": "Verhaltensgleichheit", "correct": true, "because": "Unterklassen wie Oberklassen"}, {"text": "Vertragsdurchsetzung", "correct": true, "because": "Regeln eingehalten"}, {"text": "Hohe Geschwindigkeit", "correct": false, "because": "Kein Fokus"}, {"text": "Weniger Zeilen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) LSP sichert Austauschbarkeit. b) Es macht Vererbung überflüssig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vererbung bleibt Basis"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für das Liskov Substitution Principle?', 4, '[{"text": "Konsistentes Verhalten", "correct": false, "because": "Kern des LSP"}, {"text": "Vererbung", "correct": false, "because": "Grundlage LSP"}, {"text": "Grafische Oberfläche", "correct": true, "because": "Kein Code-Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist LSP ohne Vererbung möglich?', 2, '[{"text": "Nein", "correct": true, "because": "LSP basiert auf Vererbung"}, {"text": "Ja", "correct": false, "because": "Vererbung zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme löst das Liskov Substitution Principle?', 4, '[{"text": "Unerwartete Nebenwirkungen", "correct": true, "because": "Konsistenz gewährleistet"}, {"text": "Fehler bei Austausch", "correct": true, "because": "Unterklassen kompatibel"}, {"text": "Langsame Tests", "correct": false, "because": "Kein Testfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass LSP nur für große Hierarchien ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine profitieren"}, {"text": "Ja", "correct": false, "because": "Universell anwendbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich beim Liskov Substitution Principle?', 3, '[{"text": "Vertragstreue", "correct": true, "because": "Oberklassenregeln einhalten"}, {"text": "Schnelle Änderungen", "correct": false, "because": "Konsistenz zählt"}, {"text": "Viele Unterklassen", "correct": false, "because": "Qualität entscheidet"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) LSP verhindert Fehler bei Polymorphismus. b) Es ersetzt Interfaces.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Interfaces unterstützen LSP"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet das Liskov Substitution Principle?', 5, '[{"text": "Robuster Code", "correct": true, "because": "Keine Überraschungen"}, {"text": "Einfacher Austausch", "correct": true, "because": "Unterklassen kompatibel"}, {"text": "Geringere Kosten", "correct": false, "because": "Nicht direkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist beim Liskov Substitution Principle unwichtig?', 3, '[{"text": "Verhaltenskonsistenz", "correct": false, "because": "Kernprinzip"}, {"text": "Vererbung", "correct": false, "because": "Basis LSP"}, {"text": "Farbanimationen", "correct": true, "because": "Kein Code-Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht LSP die Komplexität?', 3, '[{"text": "Nein", "correct": true, "because": "Fördert Klarheit"}, {"text": "Ja", "correct": false, "because": "Reduziert Überraschungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob LSP Tests erleichtert?', 2, '[{"text": "Ja", "correct": true, "because": "Konsistenz prüfbar"}, {"text": "Nein", "correct": false, "because": "Testbarkeit steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip ergänzt das Liskov Substitution Principle?', 4, '[{"text": "Open Closed", "correct": true, "because": "Erweiterung unterstützt"}, {"text": "KISS", "correct": false, "because": "Allgemeiner Ansatz"}, {"text": "DRY", "correct": false, "because": "Anderer Fokus"}]');

