-- questions.sql (Anschaffungskosten: Kosten für den Erwerb von Anlagegütern)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Anschaffungskosten immer nur der Kaufpreis?', 2, '[{"text": "Nein", "correct": true, "because": "Enthalten auch Nebenkosten"}, {"text": "Ja", "correct": false, "because": "Mehr als nur Kaufpreis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit der Berechnung der Anschaffungskosten?', 3, '[{"text": "Wert des Anlageguts ermitteln", "correct": true, "because": "Grundlage für Abschreibung"}, {"text": "Umsatzsteigerung", "correct": false, "because": "Kein direkter Zweck"}, {"text": "Kostenreduktion", "correct": false, "because": "Analyse, kein Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bestandteile zählen zu den Anschaffungskosten?', 5, '[{"text": "Kaufpreis", "correct": true, "because": "Hauptbestandteil"}, {"text": "Transportkosten", "correct": true, "because": "Nebenkosten enthalten"}, {"text": "Betriebskosten", "correct": false, "because": "Nach Anschaffung"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Anschaffungskosten beinhalten Installationskosten. b) Sie umfassen Wartungskosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wartung ist Betriebskosten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Ermittlung der Anschaffungskosten?', 4, '[{"text": "Nebenkosten", "correct": false, "because": "Teil der Berechnung"}, {"text": "Rabatte", "correct": false, "because": "Reduzieren Kosten"}, {"text": "Nutzungsdauer", "correct": true, "because": "Für Abschreibung relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Anschaffungskosten Steuern enthalten?', 2, '[{"text": "Ja", "correct": true, "because": "Nicht abzugsfähige Steuern inklusive"}, {"text": "Nein", "correct": false, "because": "Steuern oft enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kostenart gehört nicht zu den Anschaffungskosten?', 3, '[{"text": "Reparaturkosten", "correct": true, "because": "Betriebskosten"}, {"text": "Lieferkosten", "correct": false, "because": "Teil der Anschaffung"}, {"text": "Zollgebühren", "correct": false, "because": "Nebenkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Berechnung der Anschaffungskosten?', 5, '[{"text": "Netto-Kaufpreis", "correct": true, "because": "Basiswert"}, {"text": "Montagekosten", "correct": true, "because": "Vorbereitungskosten"}, {"text": "Laufende Versicherung", "correct": false, "because": "Betriebskosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Anschaffungskosten sind abschreibbar. b) Sie beinhalten Nutzungskosten. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nutzungskosten separat"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Anschaffungskosten unwichtig?', 4, '[{"text": "Kaufpreis", "correct": false, "because": "Hauptbestandteil"}, {"text": "Transportkosten", "correct": false, "because": "Nebenkosten"}, {"text": "Mitarbeiterlöhne", "correct": true, "because": "Betriebskosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Rabatte bei den Anschaffungskosten abzuziehen?', 2, '[{"text": "Ja", "correct": true, "because": "Reduzieren den Wert"}, {"text": "Nein", "correct": false, "because": "Einfluss auf Gesamtkosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bringt eine genaue Ermittlung der Anschaffungskosten?', 4, '[{"text": "Korrekte Abschreibung", "correct": true, "because": "Basis für Buchhaltung"}, {"text": "Steuerliche Vorteile", "correct": true, "because": "Präzise Berechnung"}, {"text": "Schnellere Lieferung", "correct": false, "because": "Kein direkter Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Anschaffungskosten nur für neue Güter gelten. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Gebrauchtwaren"}, {"text": "Ja", "correct": false, "because": "Gilt universell"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Berechnung der Anschaffungskosten?', 3, '[{"text": "Vollständigkeit", "correct": true, "because": "Alle Kosten erfassen"}, {"text": "Schnelligkeit", "correct": false, "because": "Genauigkeit wichtiger"}, {"text": "Präsentation", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Anschaffungskosten enthalten Zoll. b) Sie beinhalten Betriebsstoffe.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Betriebsstoffe separat"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat eine falsche Berechnung der Anschaffungskosten?', 5, '[{"text": "Falsche Abschreibung", "correct": true, "because": "Verzerrte Buchhaltung"}, {"text": "Steuerprobleme", "correct": true, "because": "Ungenaue Angaben"}, {"text": "Schnellere Lieferung", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Anschaffungskosten unwichtig?', 3, '[{"text": "Nebenkosten", "correct": false, "because": "Teil der Berechnung"}, {"text": "Kaufpreis", "correct": false, "because": "Grundlage"}, {"text": "Nutzungsdauer", "correct": true, "because": "Für Abschreibung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Schulungskosten Teil der Anschaffungskosten?', 3, '[{"text": "Nein", "correct": true, "because": "Betriebskosten"}, {"text": "Ja", "correct": false, "because": "Nicht direkt zu Anschaffung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Anschaffungskosten einmalig sind?', 2, '[{"text": "Ja", "correct": true, "because": "Nur bei Erwerb"}, {"text": "Nein", "correct": false, "because": "Einmalige Kosten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Kosten wähle ich für die Berechnung der Anschaffungskosten?', 4, '[{"text": "Kaufpreis und Transport", "correct": true, "because": "Komplette Anschaffung"}, {"text": "Wartung und Reparatur", "correct": false, "because": "Betriebskosten"}, {"text": "Löhne für Nutzung", "correct": false, "because": "Nach Anschaffung"}]');

