-- questions.sql (Assessment: Bewertung oder Evaluierung von Fähigkeiten, Prozessen oder Systemen)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Assessment immer eine Prüfung von Personen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Prozesse oder Systeme"}, {"text": "Ja", "correct": false, "because": "Nicht nur Personenbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Assessment?', 3, '[{"text": "Bewertung von Fähigkeiten", "correct": true, "because": "Ermittelt Kompetenzen"}, {"text": "Kosten senken", "correct": false, "because": "Indirekt"}, {"text": "Design verbessern", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden gehören zu einem Assessment?', 5, '[{"text": "Tests", "correct": true, "because": "Bewerten Fähigkeiten"}, {"text": "Interviews", "correct": true, "because": "Persönliche Einschätzung"}, {"text": "Marketingkampagnen", "correct": false, "because": "Kein Bewertungstool"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Assessments können objektiv sein. b) Sie sind immer subjektiv.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Subjektivität nicht zwingend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei einem Assessment?', 4, '[{"text": "Bewertungskriterien", "correct": false, "because": "Grundlage der Bewertung"}, {"text": "Objektivität", "correct": false, "because": "Sichert Fairness"}, {"text": "Büroverschönerung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Assessment schriftlich sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "Auch mündlich oder praktisch"}, {"text": "Ja", "correct": false, "because": "Flexibel gestaltbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wähle ich für ein Assessment von Soft Skills?', 3, '[{"text": "Gruppenübungen", "correct": true, "because": "Zeigt Teamfähigkeit"}, {"text": "IQ-Tests", "correct": false, "because": "Kognitive Fähigkeiten"}, {"text": "Technische Prüfungen", "correct": false, "because": "Fachwissen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zu einem umfassenden Assessment?', 5, '[{"text": "Fachliche Tests", "correct": true, "because": "Bewertet Wissen"}, {"text": "Persönlichkeitsanalyse", "correct": true, "because": "Soft Skills"}, {"text": "Produktwerbung", "correct": false, "because": "Kein Bewertungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Assessments verbessern die Auswahl. b) Sie sind immer zeitaufwendig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zeitaufwand variabel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Assessment unwichtig?', 4, '[{"text": "Kriterienfestlegung", "correct": false, "because": "Grundlage"}, {"text": "Ergebnisdokumentation", "correct": false, "because": "Nachverfolgbarkeit"}, {"text": "Bürofarben", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ein Assessment standardisiert sein?', 2, '[{"text": "Nein", "correct": true, "because": "Kann individuell gestaltet sein"}, {"text": "Ja", "correct": false, "because": "Flexibel anpassbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Assessment?', 4, '[{"text": "Objektive Bewertung", "correct": true, "because": "Reduziert Bias"}, {"text": "Kompetenzfeststellung", "correct": true, "because": "Erkennt Fähigkeiten"}, {"text": "Schnellere Prozesse", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Assessments immer teuer sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten variieren"}, {"text": "Ja", "correct": false, "because": "Abhängig von Umfang"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Assessment?', 3, '[{"text": "Klarheit der Kriterien", "correct": true, "because": "Sichert Fairness"}, {"text": "Schnelligkeit", "correct": false, "because": "Qualität wichtiger"}, {"text": "Kosten", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Assessments können praktisch sein. b) Sie sind nur für Einstellungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch für Entwicklung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat ein schlechtes Assessment?', 5, '[{"text": "Ungenaue Ergebnisse", "correct": true, "because": "Fehlende Kriterien"}, {"text": "Verlust an Vertrauen", "correct": true, "because": "Unfair wahrgenommen"}, {"text": "Schnelle Durchführung", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Assessment unwichtig?', 3, '[{"text": "Bewertungsmaßstäbe", "correct": false, "because": "Grundlage"}, {"text": "Feedback", "correct": false, "because": "Fördert Verbesserung"}, {"text": "Dekoration", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Assessment online durchgeführt werden?', 3, '[{"text": "Ja", "correct": true, "because": "Digitale Tools verfügbar"}, {"text": "Nein", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Assessment Teamarbeit bewerten kann?', 2, '[{"text": "Ja", "correct": true, "because": "Gruppenaufgaben möglich"}, {"text": "Nein", "correct": false, "because": "Nicht ausgeschlossen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wähle ich für ein technisches Assessment?', 4, '[{"text": "Praktische Übungen", "correct": true, "because": "Testet Fähigkeiten"}, {"text": "Schriftliche Tests", "correct": false, "because": "Theoretisch"}, {"text": "Interviews", "correct": false, "because": "Weniger technisch"}]');

