-- Verbesserungsvorschläge erarbeiten.sql (z. B. konkrete Maßnahmen zur Code- oder Prozessoptimierung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Verbesserungsvorschläge nur für fertigen Code relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Prozesse optimierbar"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Verbesserungsvorschlägen?', 3, '[{"text": "Optimierung von Code oder Prozessen", "correct": true, "because": "Effizienz steigern"}, {"text": "Mehr Features hinzufügen", "correct": false, "because": "Nicht primär"}, {"text": "Schnellere Releases", "correct": false, "because": "Kein direkter Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen gehören zu Verbesserungsvorschlägen?', 5, '[{"text": "Refactoring", "correct": true, "because": "Verbessert Code-Qualität"}, {"text": "Automatisierung", "correct": true, "because": "Prozesse effizienter"}, {"text": "Mehr Entwickler", "correct": false, "because": "Kein direkter Vorschlag"}, {"text": "Höhere Auflösung", "correct": false, "because": "UI-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Verbesserungsvorschläge erhöhen Effizienz. b) Sie verzögern immer Projekte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verzögerung nicht zwangsläufig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei Verbesserungsvorschlägen?', 4, '[{"text": "Effizienz", "correct": false, "because": "Kernziel"}, {"text": "Konkrete Maßnahmen", "correct": false, "because": "Grundlage der Vorschläge"}, {"text": "Farbschema", "correct": true, "because": "Kein Optimierungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Verbesserungsvorschläge ohne Analyse möglich sind?', 2, '[{"text": "Nein", "correct": true, "because": "Analyse zeigt Schwächen"}, {"text": "Ja", "correct": false, "because": "Ohne Basis ineffektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft bei Verbesserungsvorschlägen?', 3, '[{"text": "Profiling", "correct": true, "because": "Zeigt Optimierungspotenzial"}, {"text": "UI-Design", "correct": false, "because": "Design-fokussiert"}, {"text": "Manuelle Tests", "correct": false, "because": "Begrenzt effektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind bei Verbesserungsvorschlägen wichtig?', 5, '[{"text": "Klarheit", "correct": true, "because": "Vorschläge verständlich"}, {"text": "Machbarkeit", "correct": true, "because": "Umsetzung realistisch"}, {"text": "Maximale Features", "correct": false, "because": "Nicht Ziel"}, {"text": "Schnelle Umsetzung", "correct": false, "because": "Qualität zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Verbesserungsvorschläge sparen Zeit langfristig. b) Sie sind immer teuer. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kosten variieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Verbesserungsvorschläge?', 4, '[{"text": "Analyse", "correct": false, "because": "Identifiziert Schwächen"}, {"text": "Konkrete Ideen", "correct": false, "because": "Grundlage der Optimierung"}, {"text": "Grafische Oberfläche", "correct": true, "because": "Kein Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Verbesserungsvorschläge ohne Team möglich?', 2, '[{"text": "Ja", "correct": true, "because": "Solo umsetzbar"}, {"text": "Nein", "correct": false, "because": "Team nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme lösen Verbesserungsvorschläge?', 4, '[{"text": "Ineffizienz", "correct": true, "because": "Optimiert Prozesse"}, {"text": "Schlechter Code", "correct": true, "because": "Verbessert Qualität"}, {"text": "Langsame Tests", "correct": false, "because": "Testfokus separat"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Verbesserungsvorschläge nur für Code sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Prozesse betreffend"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Verbesserungsvorschlägen?', 3, '[{"text": "Effektivität", "correct": true, "because": "Wirkung maximieren"}, {"text": "Schnelle Umsetzung", "correct": false, "because": "Qualität zählt"}, {"text": "Viele Vorschläge", "correct": false, "because": "Relevanz entscheidet"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Verbesserungsvorschläge fördern Qualität. b) Sie ersetzen Tests.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tests bleiben nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Verbesserungsvorschläge?', 5, '[{"text": "Höhere Effizienz", "correct": true, "because": "Optimiert Abläufe"}, {"text": "Bessere Qualität", "correct": true, "because": "Schwachstellen beheben"}, {"text": "Schnellere Releases", "correct": false, "because": "Nicht garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Verbesserungsvorschlägen unwichtig?', 3, '[{"text": "Machbarkeit", "correct": false, "because": "Muss umsetzbar sein"}, {"text": "Effektivität", "correct": false, "because": "Ziel der Optimierung"}, {"text": "UI-Layout", "correct": true, "because": "Kein direkter Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht Verbesserungsvorschläge die Komplexität?', 3, '[{"text": "Nein", "correct": true, "because": "Soll vereinfachen"}, {"text": "Ja", "correct": false, "because": "Fokus auf Effizienz"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Verbesserungsvorschläge Wartung erleichtern?', 2, '[{"text": "Ja", "correct": true, "because": "Optimierter Code einfacher"}, {"text": "Nein", "correct": false, "because": "Wartbarkeit steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug unterstützt Verbesserungsvorschläge?', 4, '[{"text": "Code-Analyzer", "correct": true, "because": "Zeigt Schwachstellen"}, {"text": "Compiler", "correct": false, "because": "Nur Übersetzung"}, {"text": "UI-Editor", "correct": false, "because": "Design-fokussiert"}]');

