-- Anycast (1-zu-Nächstem, gleiche Adresse).sql
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Anycast nur für Lastverteilung gedacht?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Nähe und Effizienz"}, {"text": "Ja", "correct": false, "because": "Nutzung ist breiter"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal definiert Anycast am besten?', 3, '[{"text": "1-zu-Nächstem", "correct": true, "because": "Routing zum nächsten Ziel"}, {"text": "1-zu-Gruppe", "correct": false, "because": "Das ist Multicast"}, {"text": "1-zu-1", "correct": false, "because": "Das ist Unicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Szenarien profitieren von Anycast?', 5, '[{"text": "DNS-Abfragen", "correct": true, "because": "Nächster Server antwortet"}, {"text": "CDN-Verteilung", "correct": true, "because": "Inhalte lokal bereitgestellt"}, {"text": "Geräteerkennung", "correct": false, "because": "Multicast-Aufgabe"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Nicht Anycast-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Anycast nutzt gleiche Adressen. b) Es ist für Broadcast gedacht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Broadcast ist anders"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei Anycast?', 4, '[{"text": "Routing-Metrik", "correct": false, "because": "Bestimmt nächstes Ziel"}, {"text": "Gemeinsame Adresse", "correct": false, "because": "Kern von Anycast"}, {"text": "Gruppenzugehörigkeit", "correct": true, "because": "Multicast-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Anycast mehrere Empfänger gleichzeitig anspricht?', 2, '[{"text": "Nein", "correct": true, "because": "Nur der nächste antwortet"}, {"text": "Ja", "correct": false, "because": "Nicht wie Multicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Adresse wähle ich für Anycast?', 3, '[{"text": "Gemeinsame IP", "correct": true, "because": "Mehrere Geräte, eine Adresse"}, {"text": "FF02::1", "correct": false, "because": "Multicast-Adresse"}, {"text": "FE80::1", "correct": false, "because": "Link-lokal Unicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften hat Anycast?', 5, '[{"text": "Nächster Empfänger", "correct": true, "because": "Routing-basiert"}, {"text": "Gleiche Adresse", "correct": true, "because": "Mehrere Ziele teilen sie"}, {"text": "Alle Geräte", "correct": false, "because": "Nicht Broadcast"}, {"text": "Gruppenkommunikation", "correct": false, "because": "Nicht Multicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Anycast verbessert Latenz. b) Es nutzt Multicast-Adressen. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist Multicast"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Anycast?', 4, '[{"text": "Routing-Protokoll", "correct": false, "because": "Bestimmt nächstes Ziel"}, {"text": "Gemeinsame Adresse", "correct": false, "because": "Kernkonzept"}, {"text": "Portnummern", "correct": true, "because": "Transportebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Anycast für Gruppenkommunikation geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Nur nächster Empfänger"}, {"text": "Ja", "correct": false, "because": "Gruppen sind Multicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie nutzt Anycast häufig?', 4, '[{"text": "DNS", "correct": true, "because": "Nächster Server antwortet"}, {"text": "DHCP", "correct": false, "because": "Unicast-basiert"}, {"text": "NDP", "correct": false, "because": "Multicast-nutzend"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Anycast nur in IPv6 funktioniert. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch in IPv4 möglich"}, {"text": "Ja", "correct": false, "because": "Protokollunabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Anycast?', 3, '[{"text": "Routing-Effizienz", "correct": true, "because": "Nächstes Ziel finden"}, {"text": "Datenmenge", "correct": false, "because": "Sekundär"}, {"text": "Gruppengröße", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Anycast nutzt BGP. b) Es sendet an alle Geräte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist Broadcast"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Anycast?', 5, '[{"text": "Geringere Latenz", "correct": true, "because": "Nächster Server"}, {"text": "Lastverteilung", "correct": true, "because": "Verteilt Anfragen"}, {"text": "Gruppenkommunikation", "correct": false, "because": "Multicast-Aufgabe"}, {"text": "Datenkompression", "correct": false, "because": "Nicht enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Anycast unwichtig?', 3, '[{"text": "Routing-Tabellen", "correct": false, "because": "Bestimmen Ziel"}, {"text": "Gemeinsame Adresse", "correct": false, "because": "Kernkonzept"}, {"text": "Multicast-Scope", "correct": true, "because": "Multicast-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Antworten bei Anycast immer mehrere Geräte?', 3, '[{"text": "Nein", "correct": true, "because": "Nur der nächste antwortet"}, {"text": "Ja", "correct": false, "because": "Nicht wie Multicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Anycast für CDN nützlich ist?', 2, '[{"text": "Ja", "correct": true, "because": "Inhalte lokal bereitgestellt"}, {"text": "Nein", "correct": false, "because": "Typische Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll unterstützt Anycast oft?', 4, '[{"text": "BGP", "correct": true, "because": "Routing zum nächsten Ziel"}, {"text": "ICMP", "correct": false, "because": "Diagnose, nicht Routing"}, {"text": "TCP", "correct": false, "because": "Transportebene"}]');

