-- # Lernfeld 5: Cyberphysische Systeme > ## Testgetriebene Entwicklung > - Tests > - Debuggen > - Fehleridentifikation

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann die Fehleridentifikation im Debugging-Prozess von TDD ohne Testfälle effektiv durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Testfälle zeigen Fehler im TDD-Zyklus"}, {"text": "Ja", "correct": false, "because": "Tests sind zentral für TDD"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Fehleridentifikation in TDD ausschließlich auf die Implementierungsphase beschränkt?', 2, '[{"text": "Nein", "correct": true, "because": "Fehler werden bereits bei Testfallerstellung erkannt"}, {"text": "Ja", "correct": false, "because": "TDD ist iterativ"}]'),
('00000000-0000-0000-0000-000000000000', 'Können fehlgeschlagene Tests in TDD direkt auf die Fehlerquelle im Code hinweisen?', 2, '[{"text": "Ja", "correct": true, "because": "Tests spezifizieren, wo etwas fehlschlägt"}, {"text": "Nein", "correct": false, "because": "Tests geben klare Hinweise"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Fehleridentifikation in TDD immer manuell erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Automatisierte Tests zeigen Fehler direkt"}, {"text": "Ja", "correct": false, "because": "Automatisierung ist üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine unzureichende Fehleridentifikation in TDD die Qualität der Software beeinträchtigen?', 2, '[{"text": "Ja", "correct": true, "because": "Unentdeckte Fehler reduzieren Qualität"}, {"text": "Nein", "correct": false, "because": "Identifikation ist entscheidend"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug ist in TDD am wichtigsten für die Fehleridentifikation beim Debuggen?', 2, '[{"text": "Test-Framework", "correct": true, "because": "Zeigt fehlschlagende Tests"}, {"text": "Texteditor", "correct": false, "because": "Nur Bearbeitung"}, {"text": "Compiler", "correct": false, "because": "Übersetzung, nicht Identifikation"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Schritt im TDD-Zyklus hilft primär bei der Fehleridentifikation?', 3, '[{"text": "Ausführung eines fehlschlagenden Tests", "correct": true, "because": "Rot-Phase zeigt Fehler"}, {"text": "Code-Implementierung", "correct": false, "because": "Folgt Identifikation"}, {"text": "Refactoring", "correct": false, "because": "Verbesserung, nicht Identifikation"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Art von Fehler wird in TDD durch die Fehleridentifikation am häufigsten entdeckt?', 2, '[{"text": "Logikfehler", "correct": true, "because": "Tests prüfen Verhalten"}, {"text": "Syntaxfehler", "correct": false, "because": "Compiler fängt ab"}, {"text": "Laufzeitfehler", "correct": false, "because": "Weniger primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip in TDD erleichtert die Fehleridentifikation?', 2, '[{"text": "Test vor Code", "correct": true, "because": "Fehler früh sichtbar"}, {"text": "Maximale Abdeckung", "correct": false, "because": "Ziel, nicht Prinzip"}, {"text": "Manuelle Prüfung", "correct": false, "because": "Automatisierung üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Fehleridentifikation beim Debuggen in TDD?', 2, '[{"text": "Lokalisierung der Fehlerursache", "correct": true, "because": "Ermöglicht gezielte Korrektur"}, {"text": "Verbesserung der Laufzeit", "correct": false, "because": "Sekundär"}, {"text": "Dokumentation der Fehler", "correct": false, "because": "Nachgelagert"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methoden unterstützen die Fehleridentifikation beim Debuggen in TDD?', 4, '[{"text": "Ausführung von Unit-Tests", "correct": true, "because": "Zeigt spezifische Fehler"}, {"text": "Logging", "correct": true, "because": "Verfolgt Ablauf"}, {"text": "Manuelle Code-Inspektion", "correct": true, "because": "Detaillierte Analyse"}, {"text": "Randomisierte Änderungen", "correct": false, "because": "Ineffizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Informationen liefern Testfälle bei der Fehleridentifikation in TDD?', 3, '[{"text": "Fehlerort", "correct": true, "because": "Test zeigt, wo es fehlschlägt"}, {"text": "Fehlerursache", "correct": true, "because": "Erwartung vs. Ist"}, {"text": "Hardwarekonfiguration", "correct": false, "because": "Nicht primär"}, {"text": "Fehlerhäufigkeit", "correct": true, "because": "Wiederholbarkeit sichtbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Arten von Fehlern können durch Debugging in TDD identifiziert werden?', 3, '[{"text": "Logikfehler", "correct": true, "because": "Tests prüfen Verhalten"}, {"text": "Integrationsfehler", "correct": true, "because": "Interaktionen getestet"}, {"text": "Syntaxfehler", "correct": false, "because": "Compiler fängt ab"}, {"text": "Spezifikationsfehler", "correct": true, "because": "Tests zeigen Abweichungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Fehleridentifikation in TDD?', 4, '[{"text": "Frühe Erkennung", "correct": true, "because": "Fehler vor Implementierung"}, {"text": "Genauere Lokalisierung", "correct": true, "because": "Tests spezifisch"}, {"text": "Höhere Entwicklungskosten", "correct": false, "because": "Kosten gesenkt"}, {"text": "Verbesserte Codequalität", "correct": true, "because": "Fehlerkorrektur sofort"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Fehleridentifikation in TDD?', 3, '[{"text": "Komplexe Testfälle", "correct": true, "because": "Können Fehler verschleiern"}, {"text": "Unklare Anforderungen", "correct": true, "because": "Tests unspezifisch"}, {"text": "Schnelle Fehlerbehebung", "correct": false, "because": "Nicht immer schnell"}, {"text": "Fehlende Testabdeckung", "correct": true, "because": "Fehler bleiben unentdeckt"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Fehleridentifikation in TDD basiert ausschließlich auf manueller Analyse. b) Fehlschlagende Tests helfen bei der Fehlerlokalisierung.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Automatisierung üblich, Tests zeigen Fehler"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Debugging in TDD erfolgt vor der Testfallerstellung. b) Fehleridentifikation verbessert die Codequalität.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Debugging nach Tests, Qualität steigt"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Fehleridentifikation in TDD ist unabhängig von Testfällen. b) Unit-Tests sind ein primäres Werkzeug zur Fehleridentifikation.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Tests nötig, Unit-Tests zentral"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Logging ist in TDD das einzige Mittel zur Fehleridentifikation. b) Fehleridentifikation erfolgt im Rot-Grün-Refaktor-Zyklus.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Logging ergänzend, Zyklus zentral"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Fehleridentifikation in TDD kann die Entwicklung verzögern. b) Eine präzise Fehleridentifikation reduziert Nacharbeiten.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "TDD beschleunigt oft, Nacharbeit sinkt"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

