-- Arbeitsrecht Berufsbildung > Pflichten von Auszubildenden > Betriebseigentum schonen (§ 13 BBiG)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Muss ein Fachinformatiker betriebliche Computer schonend behandeln?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG fordert die Schonung von Betriebseigentum"}, {"text": "Nein", "correct": false, "because": "Schonung ist eine gesetzliche Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Fachinformatiker betriebliche Hardware absichtlich beschädigen?', 2, '[{"text": "Nein", "correct": true, "because": "§ 13 BBiG verbietet die Beschädigung von Betriebseigentum"}, {"text": "Ja", "correct": false, "because": "Das wäre ein Verstoß gegen die Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist ein Fachinformatiker verpflichtet, Schäden an Betriebseigentum zu melden?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG umfasst verantwortliches Verhalten"}, {"text": "Nein", "correct": false, "because": "Meldung ist Teil der Schonungspflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Darf ein Fachinformatiker betriebliche Software für private Zwecke nutzen?', 2, '[{"text": "Nein", "correct": true, "because": "§ 13 BBiG fordert zweckmäßigen Umgang mit Betriebseigentum"}, {"text": "Ja", "correct": false, "because": "Private Nutzung ist unzulässig"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss ein Fachinformatiker Netzwerkgeräte sorgfältig anschließen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG verlangt schonenden Umgang"}, {"text": "Nein", "correct": false, "because": "Sorgfalt ist Pflicht"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche gesetzliche Grundlage verpflichtet einen Fachinformatiker, Betriebseigentum zu schonen?', 2, '[{"text": "§ 13 BBiG", "correct": true, "because": "Regelt die Pflichten des Auszubildenden"}, {"text": "§ 14 BBiG", "correct": false, "because": "Bezieht sich auf Pflichten des Betriebs"}, {"text": "§ 17 BBiG", "correct": false, "because": "Regelt die Vergütung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was sollte ein Fachinformatiker tun, wenn er versehentlich einen betrieblichen Computer beschädigt?', 3, '[{"text": "Den Schaden sofort melden", "correct": true, "because": "§ 13 BBiG fordert verantwortliches Verhalten"}, {"text": "Den Schaden verheimlichen", "correct": false, "because": "Widerspricht der Pflicht"}, {"text": "Den Computer selbst reparieren", "correct": false, "because": "Nicht primäre Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Handlung zeigt, dass ein Fachinformatiker Betriebseigentum schont?', 3, '[{"text": "Sorgfältiges Anschließen von Hardware", "correct": true, "because": "Entspricht § 13 BBiG"}, {"text": "Unachtsames Umgehen mit Geräten", "correct": false, "because": "Widerspricht der Schonung"}, {"text": "Software ohne Lizenz nutzen", "correct": false, "because": "Verstoß gegen Regeln"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer ist verantwortlich, wenn ein Fachinformatiker Betriebseigentum beschädigt?', 2, '[{"text": "Der Fachinformatiker", "correct": true, "because": "§ 13 BBiG macht ihn haftbar bei Vorsatz oder Fahrlässigkeit"}, {"text": "Die Berufsschule", "correct": false, "because": "Schule hat keine Rolle"}, {"text": "Die IHK", "correct": false, "because": "IHK überwacht nur"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert, wenn ein Fachinformatiker Betriebseigentum mutwillig beschädigt?', 3, '[{"text": "Er kann gekündigt und haftbar gemacht werden", "correct": true, "because": "Verstoß gegen § 13 BBiG hat Konsequenzen"}, {"text": "Der Betrieb übernimmt die Kosten", "correct": false, "because": "Nicht vorgesehen"}, {"text": "Nichts passiert", "correct": false, "because": "Verstoß hat Folgen"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Gegenstände zählen zum Betriebseigentum, das ein Fachinformatiker schonen muss?', 4, '[{"text": "Betriebliche Computer", "correct": true, "because": "Teil des Eigentums gemäß § 13 BBiG"}, {"text": "Softwarelizenzen", "correct": true, "because": "Immaterielles Betriebseigentum"}, {"text": "Persönliche Bücher", "correct": false, "because": "Kein Betriebseigentum"}, {"text": "Netzwerkgeräte", "correct": true, "because": "Betriebliche Ausstattung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Handlungen zeigen, dass ein Fachinformatiker Betriebseigentum schont?', 3, '[{"text": "Sorgfältige Wartung von Hardware", "correct": true, "because": "Entspricht § 13 BBiG"}, {"text": "Regelmäßige Updates von Software", "correct": true, "because": "Schützt Betriebseigentum"}, {"text": "Achtloses Umgehen mit Geräten", "correct": false, "because": "Widerspricht der Pflicht"}, {"text": "Meldung von Defekten", "correct": true, "because": "Verantwortliches Verhalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen kann ein Fachinformatiker ergreifen, um Betriebseigentum zu schonen?', 3, '[{"text": "Sorgfältiger Umgang mit Arbeitsmitteln", "correct": true, "because": "§ 13 BBiG fordert dies"}, {"text": "Schäden sofort melden", "correct": true, "because": "Teil der Pflicht"}, {"text": "Eigentum privat nutzen", "correct": false, "because": "Verstoß gegen die Pflicht"}, {"text": "Regelmäßige Reinigung von Geräten", "correct": true, "because": "Schonendes Verhalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen drohen einem Fachinformatiker, der Betriebseigentum beschädigt?', 4, '[{"text": "Abmahnung durch den Betrieb", "correct": true, "because": "Reaktion auf Pflichtverletzung"}, {"text": "Kündigung bei schwerem Verstoß", "correct": true, "because": "§ 22 BBiG erlaubt dies"}, {"text": "Schadensersatzforderungen", "correct": true, "because": "Bei Vorsatz oder Fahrlässigkeit"}, {"text": "Automatische Beförderung", "correct": false, "because": "Nicht logisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Handlungen verstoßen gegen die Pflicht, Betriebseigentum zu schonen?', 3, '[{"text": "Hardware unsachgemäß lagern", "correct": true, "because": "Widerspricht § 13 BBiG"}, {"text": "Software ohne Genehmigung kopieren", "correct": true, "because": "Verstoß gegen Nutzungsregeln"}, {"text": "Geräte regelmäßig warten", "correct": false, "because": "Entspricht der Pflicht"}, {"text": "Defekte melden", "correct": false, "because": "Zeigt Sorgfalt"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Ein Fachinformatiker muss Betriebseigentum schonend behandeln. b) Schäden müssen nicht gemeldet werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schonung ist Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Betriebseigentum umfasst Software und Hardware. b) Ein Fachinformatiker darf es privat nutzen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Eigentum ist umfassend, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Fachinformatiker muss Schäden an Betriebseigentum melden. b) Alte Geräte dürfen achtlos behandelt werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Meldung ist Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) § 13 BBiG fordert die Schonung von Betriebseigentum. b) Ein Fachinformatiker haftet nicht für Schäden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schonung ist Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Fachinformatiker muss Netzwerkgeräte sorgfältig nutzen. b) Betriebseigentum schont nur der Ausbilder.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Sorgfalt ist Pflicht, b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

