-- Ja/Nein-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Müssen Auszubildende gemäß § 13 BBiG über Betriebsgeheimnisse schweigen?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG verpflichtet zur Verschwiegenheit"}, {"text": "Nein", "correct": false, "because": "Pflicht ist gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Auszubildende Betriebsgeheimnisse an Dritte weitergeben, ohne Konsequenzen?', 2, '[{"text": "Ja", "correct": false, "because": "Weitergabe verstößt gegen § 13 BBiG"}, {"text": "Nein", "correct": true, "because": "Verstoß hat Konsequenzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Gilt die Verschwiegenheitspflicht auch nach dem Ende der Ausbildung?', 2, '[{"text": "Ja", "correct": true, "because": "Verschwiegenheit bleibt bestehen"}, {"text": "Nein", "correct": false, "because": "Pflicht endet nicht mit der Ausbildung"}]'),
('00000000-0000-0000-0000-000000000000', 'Dürfen Auszubildende Betriebsgeheimnisse mit Kollegen besprechen?', 2, '[{"text": "Ja", "correct": false, "because": "Nur bei berechtigtem Bedarf erlaubt"}, {"text": "Nein", "correct": true, "because": "Verschwiegenheit gilt allgemein"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Verschwiegenheitspflicht in § 13 BBiG gesetzlich definiert?', 2, '[{"text": "Ja", "correct": true, "because": "§ 13 BBiG regelt dies eindeutig"}, {"text": "Nein", "correct": false, "because": "Gesetzliche Grundlage vorhanden"}]');

-- Single-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz verpflichtet Auszubildende zur Verschwiegenheit über Betriebsgeheimnisse?', 2, '[{"text": "§ 13 BBiG", "correct": true, "because": "Regelt die Pflichten der Auszubildenden"}, {"text": "§ 14 BBiG", "correct": false, "because": "Regelt Arbeitgeberpflichten"}, {"text": "ArbSchG", "correct": false, "because": "Regelt Arbeitsschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was zählt als Betriebsgeheimnis?', 3, '[{"text": "Vertrauliche Informationen des Unternehmens", "correct": true, "because": "Definition von Betriebsgeheimnissen"}, {"text": "Öffentliche Produktbeschreibungen", "correct": false, "because": "Nicht vertraulich"}, {"text": "Arbeitszeiten der Kollegen", "correct": false, "because": "Kein Geheimnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz droht bei Verletzung der Verschwiegenheitspflicht?', 2, '[{"text": "Kündigung oder Schadensersatz", "correct": true, "because": "Verstoß gegen § 13 BBiG"}, {"text": "Höhere Vergütung", "correct": false, "because": "Keine Belohnung"}, {"text": "Keine Konsequenz", "correct": false, "because": "Verstoß wird sanktioniert"}]'),
('00000000-0000-0000-0000-000000000000', 'Wann dürfen Auszubildende Betriebsgeheimnisse weitergeben?', 3, '[{"text": "Nur mit Zustimmung des Arbeitgebers", "correct": true, "because": "Genehmigung erforderlich"}, {"text": "Jederzeit an Kollegen", "correct": false, "because": "Verstoß gegen Pflicht"}, {"text": "Nach Ende der Ausbildung", "correct": false, "because": "Pflicht bleibt bestehen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wer ist für die Einhaltung der Verschwiegenheit verantwortlich?', 2, '[{"text": "Die Auszubildenden", "correct": true, "because": "Pflicht gemäß § 13 BBiG"}, {"text": "Der Arbeitgeber", "correct": false, "because": "Nur Aufklärungspflicht"}, {"text": "Die Berufsschule", "correct": false, "because": "Keine Rolle"}]');

-- Multiple-Choice-Fragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Welche Informationen fallen unter die Verschwiegenheitspflicht?', 4, '[{"text": "Kundendaten", "correct": true, "because": "Vertrauliche Betriebsgeheimnisse"}, {"text": "Produktionsverfahren", "correct": true, "because": "Wettbewerbsrelevante Daten"}, {"text": "Öffentliche Werbung", "correct": false, "because": "Kein Geheimnis"}, {"text": "Finanzdaten des Unternehmens", "correct": true, "because": "Vertraulich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen kann ein Verstoß gegen die Verschwiegenheitspflicht haben?', 3, '[{"text": "Abmahnung", "correct": true, "because": "Mögliche Sanktion"}, {"text": "Kündigung", "correct": true, "because": "Bei schwerem Verstoß"}, {"text": "Belohnung", "correct": false, "because": "Keine Belohnung"}, {"text": "Schadensersatzforderung", "correct": true, "because": "Bei Schaden möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was muss ein Auszubildender tun, um die Verschwiegenheitspflicht einzuhalten?', 4, '[{"text": "Betriebsgeheimnisse nicht weitergeben", "correct": true, "because": "Kern der Pflicht"}, {"text": "Vertrauliche Daten schützen", "correct": true, "because": "Teil der Verantwortung"}, {"text": "Alles mit Freunden teilen", "correct": false, "because": "Verstoß gegen Pflicht"}, {"text": "Nur mit Zustimmung Auskunft geben", "correct": true, "because": "Ausnahme erlaubt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche gesetzlichen Grundlagen stützen die Verschwiegenheitspflicht?', 3, '[{"text": "§ 13 BBiG", "correct": true, "because": "Regelt Pflichten der Auszubildenden"}, {"text": "Datenschutz-Grundverordnung (DSGVO)", "correct": true, "because": "Ergänzt bei personenbezogenen Daten"}, {"text": "KSchG", "correct": false, "because": "Regelt Kündigungsschutz"}, {"text": "Berufsbildungsgesetz allgemein", "correct": true, "because": "Rahmenrecht"}]'),
('00000000-0000-0000-0000-000000000000', 'Wann gilt die Verschwiegenheitspflicht nicht?', 3, '[{"text": "Bei Zustimmung des Arbeitgebers", "correct": true, "because": "Genehmigung hebt Pflicht auf"}, {"text": "Bei gesetzlicher Aussagepflicht", "correct": true, "because": "Gesetzliche Ausnahme"}, {"text": "Bei Gesprächen mit Freunden", "correct": false, "because": "Pflicht bleibt"}, {"text": "Nach schriftlicher Erlaubnis", "correct": true, "because": "Ausnahme möglich"}]');

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Auszubildende müssen Betriebsgeheimnisse schützen. b) Die Pflicht endet mit der Ausbildung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) § 13 BBiG, b) falsch (dauerhaft)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Verschwiegenheit gilt für Kundendaten. b) Auszubildende dürfen Geheimnisse an Kollegen weitergeben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (nur bei Bedarf)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ein Verstoß kann zur Kündigung führen. b) Verschwiegenheit ist freiwillig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (§ 13 BBiG)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) § 13 BBiG regelt die Verschwiegenheit. b) Sie gilt nur während der Arbeitszeit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "a) richtig, b) falsch (dauerhaft)"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Weitergabe ist mit Zustimmung erlaubt. b) Verschwiegenheit schützt Betriebsgeheimnisse.', 3, '[{"text": "Nur a) stimmt", "correct": false, "because": "Beides ist richtig"}, {"text": "Beides stimmt", "correct": true, "because": "a) Ausnahme, b) Zweck der Pflicht"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides ist richtig"}]');

