-- Kumulationseffekt.sql (Kumulative Wirkung von Maßnahmen oder Ereignissen, z. B. in IT-Systemen oder Wirtschaft)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass kleine IT-Fehler immer zu großen Problemen führen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Hängt von Kontext ab"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich die Wirkung von Updates in einem IT-System prüfe?', 3, '[{"text": "Kombinierte Auswirkungen", "correct": true, "because": "Erkennt Kumulation"}, {"text": "Schnelle Installation", "correct": false, "because": "Qualität zählt"}, {"text": "Designänderungen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren verstärken die Wirkung von IT-Maßnahmen?', 5, '[{"text": "Mehrere Änderungen", "correct": true, "because": "Kumuliert Effekte"}, {"text": "Systemabhängigkeiten", "correct": true, "because": "Verstärkt Interaktionen"}, {"text": "Schnellere Hardware", "correct": false, "because": "Nicht primär"}, {"text": "Bunte Interfaces", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Kumulation kann Systemausfälle verursachen. b) Sie ist immer negativ.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kann auch positiv sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich die Auswirkungen von IT-Änderungen analysiere?', 4, '[{"text": "Interdependenzen", "correct": false, "because": "Verstärken Kumulation"}, {"text": "Zeitliche Abfolge", "correct": false, "because": "Beeinflusst Effekte"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Kumulation immer sofort sichtbar ist?', 2, '[{"text": "Nein", "correct": true, "because": "Kann sich verzögern"}, {"text": "Ja", "correct": false, "because": "Nicht immer sofort"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich, wenn ich Kumulationseffekte in einem Netzwerk prüfe?', 3, '[{"text": "Stabilität sichern", "correct": true, "because": "Vermeidet Ausfälle"}, {"text": "Schnellere Verbindung", "correct": false, "because": "Sekundär"}, {"text": "Weniger Updates", "correct": false, "because": "Kein Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte führen zu Kumulation in IT-Systemen?', 5, '[{"text": "Häufige Änderungen", "correct": true, "because": "Stapeln Effekte"}, {"text": "Verknüpfte Komponenten", "correct": true, "because": "Verstärken Wirkung"}, {"text": "Schnelle CPUs", "correct": false, "because": "Kein direkter Faktor"}, {"text": "Einzelne Updates", "correct": false, "because": "Weniger Kumulation"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Kumulation kann Effizienz steigern. b) Sie ist immer vermeidbar. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht immer vermeidbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Kumulationseffekte in einem System zu prüfen?', 4, '[{"text": "Systemüberwachung", "correct": false, "because": "Erkennt Effekte"}, {"text": "Testumgebung", "correct": false, "because": "Simuliert Kumulation"}, {"text": "Neues Branding", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Verstärkt Kumulation immer Fehler?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch positiv wirken"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Analyse von Kumulationseffekten?', 4, '[{"text": "Problemerkennung", "correct": true, "because": "Vermeidet Ausfälle"}, {"text": "Optimierte Planung", "correct": true, "because": "Berücksichtigt Effekte"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Kumulation nur in großen Systemen auftritt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Systeme betroffen"}, {"text": "Ja", "correct": false, "because": "Größe egal"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um Kumulation in einem Backup-System zu prüfen?', 3, '[{"text": "Testläufe", "correct": true, "because": "Simuliert Effekte"}, {"text": "Neue Server", "correct": false, "because": "Nicht primär"}, {"text": "Bunte Diagramme", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Kumulation entsteht durch Interaktionen. b) Sie ist immer vorhersehbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Oft schwer vorhersehbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren berücksichtige ich bei Kumulation in einem IT-Projekt?', 5, '[{"text": "Änderungshäufigkeit", "correct": true, "because": "Stapelt Effekte"}, {"text": "Systemverknüpfungen", "correct": true, "because": "Verstärkt Wirkung"}, {"text": "Bürogröße", "correct": false, "because": "Kein Einfluss"}, {"text": "Schnelle CPUs", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich Kumulationseffekte in einem Netzwerk prüfe?', 3, '[{"text": "Datenfluss", "correct": false, "because": "Beeinflusst Kumulation"}, {"text": "Änderungslog", "correct": false, "because": "Zeigt Verlauf"}, {"text": "Firmenlogo", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann Kumulation auch positive Effekte haben?', 3, '[{"text": "Ja", "correct": true, "because": "Kann Effizienz steigern"}, {"text": "Nein", "correct": false, "because": "Nicht nur negativ"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Kumulation in der IT immer kontrollierbar ist?', 2, '[{"text": "Nein", "correct": true, "because": "Oft schwer steuerbar"}, {"text": "Ja", "correct": false, "because": "Nicht immer möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend, um Kumulationseffekte zu managen?', 4, '[{"text": "Überwachungstools", "correct": true, "because": "Erkennt Kumulation früh"}, {"text": "Schnellere Server", "correct": false, "because": "Nicht primär"}, {"text": "Bunte Visuals", "correct": false, "because": "Irrelevant"}]');


