-- Planung (Anforderungen priorisieren, Iterationen festlegen).sql (Strukturierte Vorbereitung der Zyklen, z. B. Priorisierung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Plane ich hier ohne Anforderungen zu sortieren?', 2, '[{"text": "Nein", "correct": true, "because": "Priorisierung ist zentral"}, {"text": "Ja", "correct": false, "because": "Strukturierte Vorbereitung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Schritt mache ich zuerst in der Planung?', 3, '[{"text": "Anforderungen priorisieren", "correct": true, "because": "Wichtigkeit festlegen"}, {"text": "Iterationen festlegen", "correct": false, "because": "Folgt Priorisierung"}, {"text": "Zufällig starten", "correct": false, "because": "Struktur nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Planung?', 5, '[{"text": "Anforderungen priorisieren", "correct": true, "because": "Reihenfolge bestimmen"}, {"text": "Iterationen festlegen", "correct": true, "because": "Zyklen definieren"}, {"text": "Unstrukturierte Ideen", "correct": false, "because": "Ordnung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Priorisierung steuert Fokus. b) Iterationen sind unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Iterationen essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei dieser Planung?', 4, '[{"text": "Anforderungen priorisieren", "correct": false, "because": "Kern der Planung"}, {"text": "Iterationen festlegen", "correct": false, "because": "Zyklen strukturieren"}, {"text": "Zufällige Reihenfolge", "correct": true, "because": "Priorisierung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ich hier ohne Zyklen plane?', 2, '[{"text": "Nein", "correct": true, "because": "Iterationen werden festgelegt"}, {"text": "Ja", "correct": false, "because": "Iterative Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Schritt wähle ich, um Wichtigkeit festzulegen?', 3, '[{"text": "Anforderungen priorisieren", "correct": true, "because": "Reihenfolge bestimmen"}, {"text": "Iterationen festlegen", "correct": false, "because": "Zyklen planen"}, {"text": "Spontan starten", "correct": false, "because": "Struktur nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte fördern eine gute Planung?', 5, '[{"text": "Anforderungen priorisieren", "correct": true, "because": "Fokus setzen"}, {"text": "Iterationen festlegen", "correct": true, "because": "Zyklen klar definieren"}, {"text": "Ungeplante Arbeit", "correct": false, "because": "Struktur essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Priorisierung ist der Start. b) Iterationen sind Zufall. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Iterationen geplant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich hier nicht unbedingt?', 4, '[{"text": "Anforderungen priorisieren", "correct": false, "because": "Fokus setzen"}, {"text": "Iterationen festlegen", "correct": false, "because": "Zyklen strukturieren"}, {"text": "Chaotische Planung", "correct": true, "because": "Struktur nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Priorisierung hier unwichtig?', 2, '[{"text": "Nein", "correct": true, "because": "Kern der Planung"}, {"text": "Ja", "correct": false, "because": "Wichtigkeit festlegen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sorgen für klare Zyklen?', 4, '[{"text": "Iterationen festlegen", "correct": true, "because": "Zyklen definieren"}, {"text": "Anforderungen priorisieren", "correct": true, "because": "Inhalte bestimmen"}, {"text": "Spontane Arbeit", "correct": false, "because": "Struktur nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ich hier ohne Planung starte. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Planung ist Basis"}, {"text": "Ja", "correct": false, "because": "Strukturierte Vorbereitung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Planung?', 3, '[{"text": "Anforderungen priorisieren", "correct": true, "because": "Wichtigkeit klären"}, {"text": "Zufällige Aufgaben", "correct": false, "because": "Struktur nötig"}, {"text": "Iterationen überspringen", "correct": false, "because": "Zyklen planen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Iterationen werden geplant. b) Priorisierung ist Zufall.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Priorisierung strukturiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile hat diese Planung?', 5, '[{"text": "Klarer Fokus", "correct": true, "because": "Priorisierung lenkt"}, {"text": "Definierte Zyklen", "correct": true, "because": "Iterationen strukturiert"}, {"text": "Ungeplante Arbeit", "correct": false, "because": "Struktur essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist hier weniger wichtig?', 3, '[{"text": "Anforderungen priorisieren", "correct": false, "because": "Fokus setzen"}, {"text": "Iterationen festlegen", "correct": false, "because": "Zyklen planen"}, {"text": "Unstrukturierte Ansätze", "correct": true, "because": "Ordnung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Iterationen hier chaotisch?', 3, '[{"text": "Nein", "correct": true, "because": "Geplant und strukturiert"}, {"text": "Ja", "correct": false, "because": "Iterationen festgelegt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Priorisierung hier fehlt?', 2, '[{"text": "Nein", "correct": true, "because": "Kern der Planung"}, {"text": "Ja", "correct": false, "because": "Wichtigkeit wird festgelegt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Schritt wähle ich nach der Priorisierung?', 4, '[{"text": "Iterationen festlegen", "correct": true, "because": "Zyklen planen"}, {"text": "Zufällig starten", "correct": false, "because": "Struktur nötig"}, {"text": "Anforderungen ignorieren", "correct": false, "because": "Basis der Planung"}]');

