-- Lernfeld:1 > Das Unternehmen und die eigene Rolle im Betrieb beschreiben > Rechtliches > Rechte und Pflichten > Rechte und Pflichten der Beteiligten > Berufsschule
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Binärfragen (8 Stück, 40%)
('00000000-0000-0000-0000-000000000000', 'Kann die Berufsschule mich zwingen, Zusatzunterricht zu besuchen?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Pflichtunterricht bindend"}, {"text": "Ja", "correct": false, "because": "Freiwilligkeit bei Extra"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Berufsschule mir theoretisches Wissen vermitteln?', 2, '[{"text": "Ja", "correct": true, "because": "Kernaufgabe der Schule"}, {"text": "Nein", "correct": false, "because": "Pflicht im dualen System"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Berufsschule verpflichtet, meine praktischen Fähigkeiten zu prüfen?', 2, '[{"text": "Nein", "correct": true, "because": "Praxis liegt beim Betrieb"}, {"text": "Ja", "correct": false, "because": "Fokus auf Theorie"}]'),
('00000000-0000-0000-0000-000000000000', 'Könnte ich die Berufsschule überspringen und nur im Betrieb lernen?', 2, '[{"text": "Nein", "correct": true, "because": "Schule ist Pflichtteil"}, {"text": "Ja", "correct": false, "because": "Duales System erfordert beides"}]'),
('00000000-0000-0000-0000-000000000000', 'Sag mir nochmal: Muss ich den Unterricht in der Berufsschule besuchen?', 2, '[{"text": "Ja", "correct": true, "because": "Schulpflicht gilt"}, {"text": "Nein", "correct": false, "because": "Pflicht für Azubis"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Berufsschule mich bei schlechtem Verhalten ausschließen?', 2, '[{"text": "Ja", "correct": true, "because": "Disziplinarmaßnahmen möglich"}, {"text": "Nein", "correct": false, "because": "Schulrecht erlaubt es"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Berufsschule verantwortlich für meine Prüfungsvorbereitung?', 2, '[{"text": "Ja", "correct": true, "because": "Theorie für Prüfungen"}, {"text": "Nein", "correct": false, "because": "Teil ihrer Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Könnte die Berufsschule meinen Betrieb über meine Leistungen informieren?', 2, '[{"text": "Ja", "correct": true, "because": "Kooperation üblich"}, {"text": "Nein", "correct": false, "because": "Kommunikation möglich"}]'),
-- Single-Choice-Fragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Was ist die Hauptaufgabe der Berufsschule?', 2, '[{"text": "Theorieunterricht", "correct": true, "because": "Ergänzt Praxis im Betrieb"}, {"text": "Praktische Ausbildung", "correct": false, "because": "Betriebssache"}, {"text": "Vergütung zahlen", "correct": false, "because": "Nicht zuständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Meine Chefin fragt, warum ich oft in der Schule bin. Was sage ich?', 3, '[{"text": "Pflichtunterricht", "correct": true, "because": "Teil des dualen Systems"}, {"text": "Ich will mehr lernen", "correct": false, "because": "Nicht der Grund"}, {"text": "Hobbys", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Recht hat die Berufsschule gegenüber mir?', 2, '[{"text": "Unterrichtspflicht durchsetzen", "correct": true, "because": "Schulpflicht gilt"}, {"text": "Mich kündigen", "correct": false, "because": "Betriebssache"}, {"text": "Gehalt kürzen", "correct": false, "because": "Nicht zuständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Der Abteilungsleiter will wissen, was die Schule leistet. Was antworte ich?', 3, '[{"text": "Theoretisches Fachwissen", "correct": true, "because": "Kernaufgabe Schule"}, {"text": "Praktische Fertigkeiten", "correct": false, "because": "Betrieb übernimmt"}, {"text": "Urlaubsplanung", "correct": false, "because": "Kein Bezug"}]'),
-- Multiple-Choice-Fragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat die Berufsschule?', 4, '[{"text": "Theorie vermitteln", "correct": true, "because": "Hauptaufgabe"}, {"text": "Unterricht organisieren", "correct": true, "because": "Struktur nötig"}, {"text": "Lernfortschritt überwachen", "correct": true, "because": "Bewertung"}, {"text": "Praktische Übungen", "correct": false, "because": "Betriebssache"}]'),
('00000000-0000-0000-0000-000000000000', 'Was muss ich in der Berufsschule tun?', 3, '[{"text": "Regelmäßig teilnehmen", "correct": true, "because": "Schulpflicht"}, {"text": "Hausaufgaben machen", "correct": true, "because": "Lernförderung"}, {"text": "Regeln befolgen", "correct": true, "because": "Disziplin"}, {"text": "Kaffee kochen", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Wir haben Probleme mit der Schule. Welche Rechte hat die Berufsschule?', 3, '[{"text": "Leistungen bewerten", "correct": true, "because": "Notengebung"}, {"text": "Verwarnungen aussprechen", "correct": true, "because": "Disziplinmaßnahmen"}, {"text": "Betrieb informieren", "correct": true, "because": "Kooperation"}, {"text": "Mich entlassen", "correct": false, "because": "Betriebssache"}]'),
('00000000-0000-0000-0000-000000000000', 'Was bietet die Berufsschule für meine Ausbildung?', 4, '[{"text": "Fachtheorie", "correct": true, "because": "Grundlagenwissen"}, {"text": "Prüfungsvorbereitung", "correct": true, "because": "Unterstützung"}, {"text": "Berufsspezifisches Wissen", "correct": true, "because": "Spezialisierung"}, {"text": "Gehaltsverhandlung", "correct": false, "because": "Nicht zuständig"}]'),
-- Kombinationsfragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Berufsschule unterrichtet Theorie. b) Sie übernimmt meine praktische Ausbildung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Theorie ja, Praxis nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ich muss den Unterricht besuchen. b) Die Schule zahlt meine Vergütung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Besuch ja, Vergütung nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Berufsschule kann mich verwarnen. b) Sie entscheidet über meine Abschlussprüfung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verwarnung ja, Prüfung IHK"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Schule bereitet mich auf Prüfungen vor. b) Ich kann den Unterricht ignorieren.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vorbereitung ja, Besuch Pflicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

