-- Lernfeld:1 > Das Unternehmen und die eigene Rolle im Betrieb beschreiben > Rechtliches > Rechte und Pflichten > Rechte und Pflichten der Beteiligten > Betriebsrat
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Binärfragen (8 Stück, 40%)
('00000000-0000-0000-0000-000000000000', 'Kann der Betriebsrat meine Kündigung verhindern?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Anhörungsrecht, keine Entscheidung"}, {"text": "Ja", "correct": false, "because": "Einfluss, aber kein Vetorecht"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss der Betriebsrat bei meiner Einstellung gefragt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Mitbestimmung bei Einstellungen"}, {"text": "Nein", "correct": false, "because": "BetrVG schreibt es vor"}]'),
('00000000-0000-0000-0000-000000000000', 'Hat der Betriebsrat das Recht, meine Arbeitszeit zu ändern?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Mitbestimmung, keine Weisung"}, {"text": "Ja", "correct": false, "because": "Arbeitgeber entscheidet"}]'),
('00000000-0000-0000-0000-000000000000', 'Könnte ich den Betriebsrat bei Problemen mit dem Chef ansprechen?', 2, '[{"text": "Ja", "correct": true, "because": "Vertretung der Arbeitnehmer"}, {"text": "Nein", "correct": false, "because": "Unterstützung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sag mir nochmal: Muss jeder Betrieb einen Betriebsrat haben?', 2, '[{"text": "Nein", "correct": true, "because": "Freiwillig ab 5 Mitarbeitern"}, {"text": "Ja", "correct": false, "because": "Nur bei Wahl durch Mitarbeiter"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann der Betriebsrat meinen Urlaub genehmigen?', 2, '[{"text": "Nein", "correct": true, "because": "Arbeitgeber entscheidet"}, {"text": "Ja", "correct": false, "because": "Keine direkte Befugnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist der Betriebsrat verpflichtet, mich zu beraten?', 2, '[{"text": "Ja", "correct": true, "because": "Vertretungsaufgabe"}, {"text": "Nein", "correct": false, "because": "Pflicht zur Unterstützung"}]'),
('00000000-0000-0000-0000-000000000000', 'Könnte der Betriebsrat bei meiner Vergütung mitbestimmen?', 2, '[{"text": "Nein", "correct": true, "because": "Vergütung ist Vertragssache"}, {"text": "Ja", "correct": false, "because": "Nur bei Tarifbindung Einfluss"}]'),
-- Single-Choice-Fragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Was ist die Hauptaufgabe des Betriebsrats?', 2, '[{"text": "Interessen der Mitarbeiter vertreten", "correct": true, "because": "Kernaufgabe nach BetrVG"}, {"text": "Betrieb leiten", "correct": false, "because": "Arbeitgeberaufgabe"}, {"text": "Prüfungen abnehmen", "correct": false, "because": "IHK-Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Meine Chefin will Überstunden anordnen. Was kann der Betriebsrat tun?', 3, '[{"text": "Mitbestimmen", "correct": true, "because": "BetrVG gibt Mitbestimmungsrecht"}, {"text": "Überstunden verbieten", "correct": false, "because": "Keine Entscheidungsbefugnis"}, {"text": "Nichts tun", "correct": false, "because": "Einfluss möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz regelt die Rechte des Betriebsrats?', 2, '[{"text": "Betriebsverfassungsgesetz", "correct": true, "because": "Grundlage für Betriebsrat"}, {"text": "BBiG", "correct": false, "because": "Für Ausbildung"}, {"text": "BGB", "correct": false, "because": "Allgemeines Recht"}]'),
('00000000-0000-0000-0000-000000000000', 'Der Abteilungsleiter fragt, wen ich bei Konflikten anspreche. Was sage ich?', 3, '[{"text": "Betriebsrat", "correct": true, "because": "Vertretung der Mitarbeiter"}, {"text": "Kunden", "correct": false, "because": "Kein Bezug"}, {"text": "Freunde", "correct": false, "because": "Keine Autorität"}]'),
-- Multiple-Choice-Fragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Welche Rechte hat der Betriebsrat?', 4, '[{"text": "Mitbestimmung bei Arbeitszeiten", "correct": true, "because": "BetrVG §87"}, {"text": "Anhören bei Kündigungen", "correct": true, "because": "Pflicht vor Kündigung"}, {"text": "Information über Personalplanung", "correct": true, "because": "Recht auf Einsicht"}, {"text": "Gehalt festlegen", "correct": false, "because": "Arbeitgeberrecht"}]'),
('00000000-0000-0000-0000-000000000000', 'Was kann der Betriebsrat für Azubis tun?', 3, '[{"text": "Bei Konflikten helfen", "correct": true, "because": "Vertretungsrolle"}, {"text": "Ausbildungsbedingungen prüfen", "correct": true, "because": "Mitbestimmung"}, {"text": "Schulungen anbieten", "correct": true, "because": "Förderung möglich"}, {"text": "Prüfungen abnehmen", "correct": false, "because": "IHK-Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Wir haben Streit über Arbeitsbedingungen. Was darf der Betriebsrat fordern?', 3, '[{"text": "Bessere Arbeitszeiten", "correct": true, "because": "Mitbestimmungsrecht"}, {"text": "Einhaltung von Schutzvorschriften", "correct": true, "because": "Arbeitsschutz"}, {"text": "Beteiligung an Regelungen", "correct": true, "because": "BetrVG"}, {"text": "Firmenübernahme", "correct": false, "because": "Keine Befugnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat der Betriebsrat?', 4, '[{"text": "Mitarbeiterinteressen wahren", "correct": true, "because": "Kernaufgabe"}, {"text": "Vertraulichkeit einhalten", "correct": true, "because": "Pflicht nach BetrVG"}, {"text": "Mit Arbeitgeber zusammenarbeiten", "correct": true, "because": "Kooperation"}, {"text": "Urlaub genehmigen", "correct": false, "because": "Arbeitgeberaufgabe"}]'),
-- Kombinationsfragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Der Betriebsrat wird von Mitarbeitern gewählt. b) Er entscheidet über meine Vergütung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wahl ja, Vergütung nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Betriebsrat hat Mitbestimmungsrechte. b) Er kann meinen Vertrag kündigen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Mitbestimmung ja, Kündigung nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Der Betriebsrat hilft bei Konflikten. b) Er ist in jedem Betrieb Pflicht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hilfe ja, Pflicht nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Betriebsrat wird über Arbeitszeiten informiert. b) Er kann mich zwingen, Überstunden zu machen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Information ja, Zwang nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

