-- Lernfeld:1 > Das Unternehmen und die eigene Rolle im Betrieb beschreiben > Rechtliches > Rechte und Pflichten > Rechte und Pflichten der Beteiligten > Jugendvertretung
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Binärfragen (8 Stück, 40%)
('00000000-0000-0000-0000-000000000000', 'Kann die Jugendvertretung meine Kündigung verhindern?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Anhörung, keine Entscheidung"}, {"text": "Ja", "correct": false, "because": "Keine direkte Befugnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Jugendvertretung bei Problemen im Betrieb helfen?', 2, '[{"text": "Ja", "correct": true, "because": "Vertretung der Jugendlichen"}, {"text": "Nein", "correct": false, "because": "Pflicht zur Unterstützung"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Jugendvertretung im Betrieb Pflicht?', 2, '[{"text": "Nein", "correct": true, "because": "Nur bei Wahl durch Jugend"}, {"text": "Ja", "correct": false, "because": "Freiwillige Einrichtung"}]'),
('00000000-0000-0000-0000-000000000000', 'Könnte ich als Azubi die Jugendvertretung wählen?', 2, '[{"text": "Ja", "correct": true, "because": "Wahlrecht für unter 25"}, {"text": "Nein", "correct": false, "because": "Gesetzlich erlaubt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sag mir nochmal: Muss die Jugendvertretung bei meiner Einstellung angehört werden?', 2, '[{"text": "Nein", "correct": true, "because": "Nur bei Kündigung"}, {"text": "Ja", "correct": false, "because": "Anhörung nicht vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Jugendvertretung meine Arbeitszeiten ändern?', 2, '[{"text": "Nein", "correct": true, "because": "Keine direkte Befugnis"}, {"text": "Ja", "correct": false, "because": "Nur Vorschläge möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Jugendvertretung verpflichtet, mich zu beraten?', 2, '[{"text": "Ja", "correct": true, "because": "Teil ihrer Aufgabe"}, {"text": "Nein", "correct": false, "because": "Unterstützungspflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Könnte die Jugendvertretung beim Chef für mich sprechen?', 2, '[{"text": "Ja", "correct": true, "because": "Vertretung der Interessen"}, {"text": "Nein", "correct": false, "because": "Rechtlich möglich"}]'),
-- Single-Choice-Fragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Was ist die Hauptaufgabe der Jugendvertretung?', 2, '[{"text": "Interessen der Jugend vertreten", "correct": true, "because": "Kernaufgabe"}, {"text": "Prüfungen organisieren", "correct": false, "because": "IHK-Aufgabe"}, {"text": "Gehalt verhandeln", "correct": false, "because": "Tarifsache"}]'),
('00000000-0000-0000-0000-000000000000', 'Meine Chefin will mich kündigen. Was macht die Jugendvertretung?', 3, '[{"text": "Wird angehört", "correct": true, "because": "Pflicht nach BetrVG"}, {"text": "Entscheidet", "correct": false, "because": "Nur Anhörung"}, {"text": "Ignoriert das", "correct": false, "because": "Gesetzlich beteiligt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Recht hat die Jugendvertretung im Betrieb?', 2, '[{"text": "Mitbestimmung bei Jugendfragen", "correct": true, "because": "Gesetzlich geregelt"}, {"text": "Betrieb schließen", "correct": false, "because": "Keine Befugnis"}, {"text": "Urlaub festlegen", "correct": false, "because": "Betriebssache"}]'),
('00000000-0000-0000-0000-000000000000', 'Der Abteilungsleiter fragt, wen ich bei Problemen anspreche. Was sage ich?', 3, '[{"text": "Jugendvertretung", "correct": true, "because": "Vertretung für Azubis"}, {"text": "Kunden", "correct": false, "because": "Kein Bezug"}, {"text": "Freunde", "correct": false, "because": "Keine Autorität"}]'),
-- Multiple-Choice-Fragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben hat die Jugendvertretung?', 4, '[{"text": "Beratung von Azubis", "correct": true, "because": "Unterstützung"}, {"text": "Anhörung bei Kündigungen", "correct": true, "because": "Mitbestimmung"}, {"text": "Förderung der Ausbildung", "correct": true, "because": "Interessenvertretung"}, {"text": "Vergütung festlegen", "correct": false, "because": "Tarifsache"}]'),
('00000000-0000-0000-0000-000000000000', 'Was kann die Jugendvertretung bei Konflikten tun?', 3, '[{"text": "Vermitteln", "correct": true, "because": "Schlichtungsrolle"}, {"text": "Anliegen vorbringen", "correct": true, "because": "Vertretung"}, {"text": "Betrieb informieren", "correct": true, "because": "Kommunikation"}, {"text": "Chef entlassen", "correct": false, "because": "Keine Befugnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Wir haben Stress im Betrieb. Welche Rechte hat die Jugendvertretung?', 3, '[{"text": "Anhörung bei Disziplinarmaßnahmen", "correct": true, "because": "Schutzfunktion"}, {"text": "Vorschläge einbringen", "correct": true, "because": "Mitgestaltung"}, {"text": "Betriebsrat unterstützen", "correct": true, "because": "Zusammenarbeit"}, {"text": "Urlaub genehmigen", "correct": false, "because": "Betriebssache"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten hat die Jugendvertretung?', 4, '[{"text": "Jugendliche vertreten", "correct": true, "because": "Hauptaufgabe"}, {"text": "Beratung anbieten", "correct": true, "because": "Unterstützung"}, {"text": "Betrieb informieren", "correct": true, "because": "Kooperation"}, {"text": "Prüfungen abnehmen", "correct": false, "because": "IHK-Aufgabe"}]'),
-- Kombinationsfragen (4 Stück, 20%)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Jugendvertretung wird von Azubis gewählt. b) Sie entscheidet über meine Kündigung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wahl ja, Entscheidung nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Jugendvertretung hilft bei Konflikten. b) Sie ist im kleinen Betrieb Pflicht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hilfe ja, Pflicht nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Jugendvertretung wird bei Kündigungen angehört. b) Sie kann meinen Urlaub genehmigen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Anhörung ja, Urlaub nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Jugendvertretung vertritt meine Interessen. b) Sie zahlt meine Vergütung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vertretung ja, Vergütung nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

