-- Pfad: Anwendersupport/Informationssicherheit Grundlagen/Gesetze

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Müssen Unternehmen im Anwendersupport Datenschutzgesetze einhalten?', 2, '[{"text": "Ja", "correct": true, "because": "Schutz personenbezogener Daten"}, {"text": "Nein", "correct": false, "because": "Gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die DSGVO ein Gesetz, das den Anwendersupport betrifft?', 2, '[{"text": "Ja", "correct": true, "because": "Regelt Datenverarbeitung"}, {"text": "Nein", "correct": false, "because": "DSGVO ist relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Verstöße gegen Informationssicherheitsgesetze im Anwendersupport Strafen nach sich ziehen?', 2, '[{"text": "Ja", "correct": true, "because": "Gesetzliche Sanktionen"}, {"text": "Nein", "correct": false, "because": "Strafen möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist das BDSG nur für große Unternehmen im Anwendersupport relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle Datenverarbeiter"}, {"text": "Ja", "correct": false, "because": "Unabhängig von Größe"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Gesetze zur Informationssicherheit im Anwendersupport regelmäßig überprüft werden?', 2, '[{"text": "Ja", "correct": true, "because": "Änderungen möglich"}, {"text": "Nein", "correct": false, "because": "Aktualität wichtig"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz regelt den Datenschutz in der EU im Anwendersupport?', 2, '[{"text": "DSGVO", "correct": true, "because": "EU-weites Datenschutzgesetz"}, {"text": "BDSG", "correct": false, "because": "Nationales Gesetz"}, {"text": "IT-SiG", "correct": false, "because": "Sicherheitsgesetz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz ergänzt die DSGVO in Deutschland im Anwendersupport?', 3, '[{"text": "BDSG", "correct": true, "because": "Nationale Ergänzung"}, {"text": "TMG", "correct": false, "because": "Telemediengesetz"}, {"text": "UrhG", "correct": false, "because": "Urheberrecht"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die Hauptpflicht laut DSGVO im Anwendersupport?', 2, '[{"text": "Datenschutz", "correct": true, "because": "Schutz personenbezogener Daten"}, {"text": "Netzwerksicherheit", "correct": false, "because": "Anderer Fokus"}, {"text": "Softwareupdates", "correct": false, "because": "Technische Maßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz kann bei kritischen Infrastrukturen im Anwendersupport relevant sein?', 2, '[{"text": "IT-SiG", "correct": true, "because": "IT-Sicherheitsgesetz"}, {"text": "DSGVO", "correct": false, "because": "Datenschutzfokus"}, {"text": "BGB", "correct": false, "because": "Bürgerliches Recht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strafe droht bei Verstößen gegen die DSGVO im Anwendersupport?', 2, '[{"text": "Geldstrafe", "correct": true, "because": "Bis zu Millionenbeträge"}, {"text": "Warnung", "correct": false, "because": "Nur erste Maßnahme"}, {"text": "Schulung", "correct": false, "because": "Keine Strafe"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Gesetze sind im Anwendersupport relevant?', 3, '[{"text": "DSGVO", "correct": true, "because": "Datenschutz EU"}, {"text": "BDSG", "correct": true, "because": "Datenschutz DE"}, {"text": "IT-SiG", "correct": true, "because": "IT-Sicherheit"}, {"text": "HGB", "correct": false, "because": "Handelsrecht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Pflichten ergeben sich aus der DSGVO im Anwendersupport?', 4, '[{"text": "Datenminimierung", "correct": true, "because": "Nur nötige Daten"}, {"text": "Transparenz", "correct": true, "because": "Information der Nutzer"}, {"text": "Meldepflicht", "correct": true, "because": "Bei Datenpannen"}, {"text": "Softwareentwicklung", "correct": false, "because": "Kein Gesetzesziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen können Verstöße gegen Gesetze im Anwendersupport haben?', 3, '[{"text": "Geldstrafen", "correct": true, "because": "Sanktionen möglich"}, {"text": "Rufschaden", "correct": true, "because": "Vertrauensverlust"}, {"text": "Behördliche Auflagen", "correct": true, "because": "Korrekturmaßnahmen"}, {"text": "Hardwareausfall", "correct": false, "because": "Technisches Problem"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bereiche regeln Gesetze zur Informationssicherheit im Anwendersupport?', 4, '[{"text": "Datenschutz", "correct": true, "because": "Personenbezogene Daten"}, {"text": "IT-Sicherheit", "correct": true, "because": "Systemschutz"}, {"text": "Datenverarbeitung", "correct": true, "because": "Rechtliche Grundlage"}, {"text": "Marketing", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen verlangt die DSGVO im Anwendersupport?', 3, '[{"text": "Datenschutzbeauftragter", "correct": true, "because": "Bei Bedarf Pflicht"}, {"text": "Risikoanalyse", "correct": true, "because": "Schutzmaßnahmen"}, {"text": "Dokumentation", "correct": true, "because": "Nachweispflicht"}, {"text": "Telefonüberwachung", "correct": false, "because": "Kein DSGVO-Thema"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die DSGVO schützt personenbezogene Daten im Anwendersupport. b) Das IT-SiG regelt nur den Datenschutz.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DSGVO ja, IT-SiG Sicherheit"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Das BDSG ergänzt die DSGVO im Anwendersupport. b) Verstöße gegen Gesetze sind folgenlos.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "BDSG ja, Verstöße strafbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die DSGVO verlangt Transparenz im Anwendersupport. b) Gesetze zur Informationssicherheit sind optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Transparenz ja, Gesetze verpflichtend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Das IT-SiG betrifft kritische Infrastrukturen im Anwendersupport. b) Die DSGVO gilt nur für große Unternehmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "IT-SiG ja, DSGVO allgemein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),

