-- Pfad: Anwendersupport/Informationssicherheit Grundlagen/Standards

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind Standards für Informationssicherheit im Anwendersupport verbindlich?', 2, '[{"text": "Nein", "correct": true, "because": "Richtlinien, keine Gesetze"}, {"text": "Ja", "correct": false, "because": "Freiwillige Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die ISO 27001 im Anwendersupport zur Sicherheitsverbesserung beitragen?', 2, '[{"text": "Ja", "correct": true, "because": "Internationaler Standard"}, {"text": "Nein", "correct": false, "because": "Verbesserung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Standards für Informationssicherheit im Anwendersupport regelmäßig aktualisiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Anpassung an Bedrohungen"}, {"text": "Nein", "correct": false, "because": "Aktualität wichtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Standards wie der BSI-Grundschutz im Anwendersupport nur für große Unternehmen relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Für alle Größen anwendbar"}, {"text": "Ja", "correct": false, "because": "Allgemein gültig"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Standards für Informationssicherheit im Anwendersupport Risiken minimieren?', 2, '[{"text": "Ja", "correct": true, "because": "Strukturierte Vorgehensweise"}, {"text": "Nein", "correct": false, "because": "Risikoreduktion Ziel"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Standard ist international für Informationssicherheit im Anwendersupport anerkannt?', 2, '[{"text": "ISO 27001", "correct": true, "because": "Globaler Standard"}, {"text": "BSI-Grundschutz", "correct": false, "because": "Nationaler Fokus"}, {"text": "GDPR", "correct": false, "because": "Gesetz, kein Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Standard wird vom BSI für den Anwendersupport empfohlen?', 3, '[{"text": "BSI-Grundschutz", "correct": true, "because": "Deutscher Sicherheitsstandard"}, {"text": "ISO 9001", "correct": false, "because": "Qualitätsmanagement"}, {"text": "NIST", "correct": false, "because": "US-Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel von Sicherheitsstandards im Anwendersupport?', 2, '[{"text": "Schutz von Informationen", "correct": true, "because": "Kernaufgabe"}, {"text": "Kostensenkung", "correct": false, "because": "Kein Primärziel"}, {"text": "Schnellere Prozesse", "correct": false, "because": "Nebenaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Standard hilft im Anwendersupport bei der Risikobewertung?', 2, '[{"text": "ISO 27001", "correct": true, "because": "Risikomanagement enthalten"}, {"text": "ITIL", "correct": false, "because": "Service-Management"}, {"text": "COBIT", "correct": false, "because": "IT-Governance"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Zertifizierung zeigt die Einhaltung von Sicherheitsstandards im Anwendersupport?', 2, '[{"text": "ISO 27001-Zertifikat", "correct": true, "because": "Nachweis der Umsetzung"}, {"text": "BSI-Zertifikat", "correct": false, "because": "Spezifisch, weniger global"}, {"text": "DSGVO-Bescheinigung", "correct": false, "because": "Kein Standard"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Standards sind im Anwendersupport relevant?', 3, '[{"text": "ISO 27001", "correct": true, "because": "International anerkannt"}, {"text": "BSI-Grundschutz", "correct": true, "because": "Deutscher Standard"}, {"text": "NIST", "correct": true, "because": "US-Sicherheitsstandard"}, {"text": "ISO 9001", "correct": false, "because": "Qualitätsmanagement"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten Standards für Informationssicherheit im Anwendersupport?', 4, '[{"text": "Risikominimierung", "correct": true, "because": "Gefahren reduzieren"}, {"text": "Einheitliche Prozesse", "correct": true, "because": "Standardisierung"}, {"text": "Vertrauensaufbau", "correct": true, "because": "Nachweis Sicherheit"}, {"text": "Kundengewinnung", "correct": false, "because": "Marketingaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente enthält die ISO 27001 im Anwendersupport?', 3, '[{"text": "Risikobewertung", "correct": true, "because": "Gefahrenanalyse"}, {"text": "Sicherheitsmaßnahmen", "correct": true, "because": "Schutzvorgaben"}, {"text": "Kontinuierliche Verbesserung", "correct": true, "because": "Anpassung"}, {"text": "Hardwarewartung", "correct": false, "because": "Technische Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben unterstützen Standards im Anwendersupport?', 4, '[{"text": "Sicherheitsplanung", "correct": true, "because": "Strukturierte Vorgehensweise"}, {"text": "Vorfallmanagement", "correct": true, "because": "Reaktion auf Probleme"}, {"text": "Schulungsplanung", "correct": true, "because": "Sensibilisierung"}, {"text": "Kundensupport", "correct": false, "because": "Operative Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Standards fördern die Informationssicherheit im Anwendersupport?', 3, '[{"text": "BSI-Grundschutz", "correct": true, "because": "Deutscher Ansatz"}, {"text": "ISO 27001", "correct": true, "because": "Globaler Rahmen"}, {"text": "PCI DSS", "correct": true, "because": "Zahlungsdaten-Schutz"}, {"text": "ITIL", "correct": false, "because": "Service-Management"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die ISO 27001 ist ein Standard für Informationssicherheit im Anwendersupport. b) Standards sind gesetzlich vorgeschrieben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "ISO ja, Standards freiwillig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) BSI-Grundschutz hilft bei der Risikobewertung im Anwendersupport. b) Standards ersetzen gesetzliche Vorgaben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "BSI ja, Ergänzung zu Gesetzen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Standards wie ISO 27001 fördern einheitliche Sicherheitsprozesse. b) Standards sind nur für technische Teams relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Einheitlich ja, alle betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Standards müssen im Anwendersupport regelmäßig überprüft werden. b) ISO 27001 ist ein deutscher Standard.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Überprüfung ja, ISO international"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Standards helfen bei der Zertifizierung im Anwendersupport. b) BSI-Grundschutz ist für kleine Unternehmen ungeeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zertifizierung ja, BSI für alle"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

