-- Pflichtenheft.sql (Dokumentation von Anforderungen für IT-Projekte)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Pflichtenheft immer bindend für ein Projekt?', 2, '[{"text": "Ja", "correct": true, "because": "Definiert verbindliche Anforderungen"}, {"text": "Nein", "correct": false, "because": "Änderungen möglich, aber selten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel eines solchen Dokuments?', 3, '[{"text": "Klare Anforderungen festlegen", "correct": true, "because": "Sichert Projektziele"}, {"text": "Maximale Flexibilität", "correct": false, "because": "Gegenteil von Klarheit"}, {"text": "Manuelle Umsetzung", "correct": false, "because": "Fokus auf Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Inhalte gehören typischerweise in ein Pflichtenheft?', 5, '[{"text": "Funktionale Anforderungen", "correct": true, "because": "Beschreiben Systemverhalten"}, {"text": "Nicht-funktionale Anforderungen", "correct": true, "because": "Definieren Qualität"}, {"text": "Marketingstrategien", "correct": false, "because": "Nicht projektbezogen"}, {"text": "Mitarbeiterprofile", "correct": false, "because": "Irrelevant für Projekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Pflichtenheft beschreibt Soll-Zustände. b) Es enthält die technische Umsetzung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist im Lastenheft"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Erstellung eines Pflichtenhefts?', 4, '[{"text": "Stakeholder-Anforderungen", "correct": false, "because": "Grundlage des Dokuments"}, {"text": "Abnahmekriterien", "correct": false, "because": "Definieren Erfolg"}, {"text": "Farbschemata", "correct": true, "because": "Nicht funktionsrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Pflichtenheft nur für Softwareprojekte genutzt wird?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für andere Projekte geeignet"}, {"text": "Ja", "correct": false, "because": "Universell einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist für ein Pflichtenheft entscheidend?', 3, '[{"text": "Präzise Formulierungen", "correct": true, "because": "Vermeiden Missverständnisse"}, {"text": "Vage Beschreibungen", "correct": false, "because": "Führen zu Fehlern"}, {"text": "Manuelle Zeichnungen", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein gut erstelltes Pflichtenheft?', 5, '[{"text": "Klarheit für Entwickler", "correct": true, "because": "Definiert Anforderungen"}, {"text": "Reduzierte Missverständnisse", "correct": true, "because": "Vermeidet Fehlinterpretation"}, {"text": "Hohe Flexibilität", "correct": false, "because": "Eher bindend"}, {"text": "Einmalige Nutzung", "correct": false, "because": "Langfristige Referenz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Pflichtenheft dient der Abnahme. b) Es ist nur für Kunden. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) auch für Entwickler"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Pflichtenheft?', 4, '[{"text": "Anforderungen", "correct": false, "because": "Kern des Dokuments"}, {"text": "Abnahmekriterien", "correct": false, "because": "Bestimmen Erfolg"}, {"text": "Musikwiedergabe", "correct": true, "because": "Irrelevant für Projekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Pflichtenheft dasselbe wie ein Lastenheft?', 2, '[{"text": "Nein", "correct": true, "because": "Lastenheft beschreibt Lösung"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Dokumente"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind in einem Pflichtenheft wichtig?', 4, '[{"text": "Leistungsanforderungen", "correct": true, "because": "Definieren Systemleistung"}, {"text": "Sicherheitsanforderungen", "correct": true, "because": "Schützen System"}, {"text": "Teamfotos", "correct": false, "because": "Nicht projektrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Pflichtenheft immer unveränderlich ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Änderungen mit Zustimmung möglich"}, {"text": "Ja", "correct": false, "because": "Flexibilität erlaubt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Erstellung eines Pflichtenhefts?', 3, '[{"text": "Klarheit", "correct": true, "because": "Vermeidet Missverständnisse"}, {"text": "Maximale Details", "correct": false, "because": "Kann überladen"}, {"text": "Manuelle Erstellung", "correct": false, "because": "Vorlagen effizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Pflichtenheft enthält Abnahmekriterien. b) Es ersetzt die Programmierung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist keine Umsetzung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente verbessern ein Pflichtenheft?', 5, '[{"text": "Präzise Anforderungen", "correct": true, "because": "Sichern Verständnis"}, {"text": "Nachvollziehbare Kriterien", "correct": true, "because": "Erleichen Abnahme"}, {"text": "Vage Formulierungen", "correct": false, "because": "Führen zu Fehlern"}, {"text": "Grafische Designs", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Pflichtenheft unwichtig?', 3, '[{"text": "Funktionsbeschreibungen", "correct": false, "because": "Kern des Dokuments"}, {"text": "Qualitätsanforderungen", "correct": false, "because": "Sichern Leistung"}, {"text": "Bildbearbeitung", "correct": true, "because": "Kein Projektfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Pflichtenheft für agile Projekte geeignet ist?', 2, '[{"text": "Ja", "correct": true, "because": "Mit Anpassungen nutzbar"}, {"text": "Nein", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Definiert ein Pflichtenheft die technische Umsetzung?', 3, '[{"text": "Nein", "correct": true, "because": "Fokus auf Anforderungen"}, {"text": "Ja", "correct": false, "because": "Umsetzung im Lastenheft"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Nutzung eines Pflichtenhefts?', 4, '[{"text": "Entwicklung einer Unternehmenssoftware", "correct": true, "because": "Klärt Anforderungen"}, {"text": "Erstellung eines Logos", "correct": false, "because": "Kreative Aufgabe"}, {"text": "Hardwarewartung", "correct": false, "because": "Technische Aufgabe"}]');

