-- Phasen des Softwareentwicklungsprozesses.sql (Strukturierte Schritte zur Softwareerstellung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Planungsphase immer die erste im Softwareentwicklungsprozess?', 2, '[{"text": "Ja", "correct": true, "because": "Legt Anforderungen und Ziele fest"}, {"text": "Nein", "correct": false, "because": "Planung startet Prozess"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Analysephase?', 3, '[{"text": "Anforderungen definieren", "correct": true, "because": "Identifiziert Systembedürfnisse"}, {"text": "Code schreiben", "correct": false, "because": "Erst in Implementierung"}, {"text": "Manuelle Tests", "correct": false, "because": "Testphase"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phasen gehören typischerweise zum Entwicklungsprozess?', 5, '[{"text": "Design", "correct": true, "because": "Plant Architektur"}, {"text": "Testen", "correct": true, "because": "Sichert Qualität"}, {"text": "Marketing", "correct": false, "because": "Nicht entwicklungsspezifisch"}, {"text": "Hardwarewartung", "correct": false, "because": "Andere Domäne"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Implementierung folgt dem Design. b) Wartung ist optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist oft erforderlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich in der Testphase?', 4, '[{"text": "Fehlerprotokolle", "correct": false, "because": "Identifizieren Probleme"}, {"text": "Testfälle", "correct": false, "because": "Sichern Abdeckung"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Tests"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Designphase vor der Analyse kommt?', 2, '[{"text": "Nein", "correct": true, "because": "Analyse definiert Anforderungen zuerst"}, {"text": "Ja", "correct": false, "because": "Design folgt Analyse"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Implementierungsphase?', 3, '[{"text": "Code schreiben", "correct": true, "because": "Setzt Design um"}, {"text": "Anforderungen erheben", "correct": false, "because": "Analysephase"}, {"text": "Manuelle Optimierung", "correct": false, "because": "Automatisierung üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aktivitäten sind in der Wartungsphase wichtig?', 5, '[{"text": "Fehlerbehebung", "correct": true, "because": "Löst Probleme nach Release"}, {"text": "Updates", "correct": true, "because": "Verbessern Funktionalität"}, {"text": "Erstanforderungen", "correct": false, "because": "Analysephase"}, {"text": "Bildbearbeitung", "correct": false, "because": "Nicht entwicklungsspezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Testen findet vor der Implementierung statt. b) Design definiert Architektur. Stimmt das?', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "a) folgt Implementierung"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht in der Analysephase?', 4, '[{"text": "Stakeholder-Input", "correct": false, "because": "Definiert Anforderungen"}, {"text": "Anforderungsdokument", "correct": false, "because": "Ergebnis der Phase"}, {"text": "3D-Modellierung", "correct": true, "because": "Irrelevant für Analyse"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Wartungsphase immer die letzte?', 2, '[{"text": "Nein", "correct": true, "because": "Läuft nach Release weiter"}, {"text": "Ja", "correct": false, "because": "Langfristige Phase"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phasen beeinflussen die Softwarequalität direkt?', 4, '[{"text": "Testen", "correct": true, "because": "Findet Fehler"}, {"text": "Design", "correct": true, "because": "Legt Architektur fest"}, {"text": "Marketing", "correct": false, "because": "Nicht entwicklungsspezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass die Analysephase immer kurz ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Dauer hängt von Projekt ab"}, {"text": "Ja", "correct": false, "because": "Kann umfangreich sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich in der Designphase?', 3, '[{"text": "Klare Architektur", "correct": true, "because": "Sichert Umsetzbarkeit"}, {"text": "Schnelle Codierung", "correct": false, "because": "Implementierungsphase"}, {"text": "Manuelle Tests", "correct": false, "because": "Testphase"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Testen validiert Anforderungen. b) Design ist nur für Programmierer.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) betrifft auch Stakeholder"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine strukturierte Testphase?', 5, '[{"text": "Fehlerreduktion", "correct": true, "because": "Findet Probleme früh"}, {"text": "Qualitätssicherung", "correct": true, "because": "Bestätigt Anforderungen"}, {"text": "Schnelle Markteinführung", "correct": false, "because": "Qualität hat Vorrang"}, {"text": "Manuelle Planung", "correct": false, "because": "Automatisierte Tests besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist in der Implementierungsphase unwichtig?', 3, '[{"text": "Codequalität", "correct": false, "because": "Sichert Wartbarkeit"}, {"text": "Versionierung", "correct": false, "because": "Verfolgt Änderungen"}, {"text": "Musikwiedergabe", "correct": true, "because": "Kein Entwicklungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann die Wartungsphase neue Funktionen einführen?', 3, '[{"text": "Ja", "correct": true, "because": "Updates können Features hinzufügen"}, {"text": "Nein", "correct": false, "because": "Nicht nur Fehlerbehebung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Analysephase für agile Projekte relevant ist?', 2, '[{"text": "Ja", "correct": true, "because": "Auch iterativ genutzt"}, {"text": "Nein", "correct": false, "because": "Anforderungen immer nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zum Entwicklungsprozess?', 4, '[{"text": "Erstellung einer Web-App", "correct": true, "because": "Folgt Phasen wie Design, Test"}, {"text": "Logoerstellung", "correct": false, "because": "Kreative Aufgabe"}, {"text": "Netzwerkwartung", "correct": false, "because": "Technische Aufgabe"}]');

