-- Privacy by Design.sql (Konzept zur Integration von Datenschutz in Systementwicklung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Privacy by Design nur für Softwareentwicklung relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle datenverarbeitenden Systeme"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel von Privacy by Design?', 3, '[{"text": "Datenschutz von Anfang an", "correct": true, "because": "Integriert Schutz in Design"}, {"text": "Maximale Datenverarbeitung", "correct": false, "because": "Gegenteil des Ziels"}, {"text": "Manuelle Konfiguration", "correct": false, "because": "Automatisiert bevorzugt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien gehören zu Privacy by Design?', 5, '[{"text": "Datenminimierung", "correct": true, "because": "Nur nötige Daten erheben"}, {"text": "Transparenz", "correct": true, "because": "Nutzer informieren"}, {"text": "Maximale Datenspeicherung", "correct": false, "because": "Gegenteil von Minimierung"}, {"text": "Öffentliche Freigabe", "correct": false, "because": "Verletzt Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Privacy by Design ist in der DSGVO verankert. b) Es ist nur für Großunternehmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) gilt für alle Unternehmen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Umsetzung von Privacy by Design?', 4, '[{"text": "Datensparsamkeit", "correct": false, "because": "Kernprinzip"}, {"text": "Nutzerkontrolle", "correct": false, "because": "Fördert Vertrauen"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Privacy by Design nur technische Maßnahmen umfasst?', 2, '[{"text": "Nein", "correct": true, "because": "Auch organisatorische Maßnahmen"}, {"text": "Ja", "correct": false, "because": "Umfassender Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip ist zentral für Privacy by Design?', 3, '[{"text": "Proaktiver Schutz", "correct": true, "because": "Verhindert Datenschutzverstöße"}, {"text": "Maximale Speicherung", "correct": false, "because": "Gegenteil von Minimierung"}, {"text": "Manuelle Überwachung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen unterstützen Privacy by Design?', 5, '[{"text": "Pseudonymisierung", "correct": true, "because": "Schützt Identität"}, {"text": "Standardmäßiger Datenschutz", "correct": true, "because": "Privacy by Default"}, {"text": "Hohe Datenmenge", "correct": false, "because": "Widerspricht Minimierung"}, {"text": "Öffentliche Freigabe", "correct": false, "because": "Verletzt Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Privacy by Design fördert Nutzerrechte. b) Es erhöht immer Kosten. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) nicht zwangsläufig teuer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Privacy by Design?', 4, '[{"text": "Datenschutzrichtlinien", "correct": false, "because": "Leiten Umsetzung"}, {"text": "Sicherheitsmaßnahmen", "correct": false, "because": "Schützen Daten"}, {"text": "Grafische Animationen", "correct": true, "because": "Irrelevant für Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Privacy by Design nur für neue Systeme?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für bestehende Systeme"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind bei Privacy by Design wichtig?', 4, '[{"text": "End-to-End-Schutz", "correct": true, "because": "Sichert gesamten Lebenszyklus"}, {"text": "Nutzerfreundlichkeit", "correct": true, "because": "Fördert Akzeptanz"}, {"text": "Hohe Datenmenge", "correct": false, "because": "Widerspricht Minimierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Privacy by Design immer komplex ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kann einfach integriert werden"}, {"text": "Ja", "correct": false, "because": "Komplexität abhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Privacy by Design?', 3, '[{"text": "Datenminimierung", "correct": true, "because": "Reduziert Risiken"}, {"text": "Maximale Datenerfassung", "correct": false, "because": "Gegenteil des Ziels"}, {"text": "Manuelle Einstellungen", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Privacy by Design schützt proaktiv. b) Es ignoriert Nutzerrechte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) fördert Nutzerrechte"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Privacy by Design?', 5, '[{"text": "Vertrauensaufbau", "correct": true, "because": "Nutzer fühlen sich geschützt"}, {"text": "Rechtskonformität", "correct": true, "because": "Erfüllt DSGVO"}, {"text": "Hohe Datenmenge", "correct": false, "because": "Gegenteil von Minimierung"}, {"text": "Manuelle Kontrollen", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Privacy by Design unwichtig?', 3, '[{"text": "Transparenz", "correct": false, "because": "Fördert Vertrauen"}, {"text": "Datensicherheit", "correct": false, "because": "Kernprinzip"}, {"text": "Musikwiedergabe", "correct": true, "because": "Kein Datenschutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Privacy by Design für IoT-Geräte relevant ist?', 2, '[{"text": "Ja", "correct": true, "because": "Schützt vernetzte Geräte"}, {"text": "Nein", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erfordert Privacy by Design immer Verschlüsselung?', 3, '[{"text": "Nein", "correct": true, "because": "Maßnahme abhängig vom System"}, {"text": "Ja", "correct": false, "because": "Flexibel umsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu Privacy by Design?', 4, '[{"text": "Entwicklung einer sicheren App", "correct": true, "because": "Datenschutz integriert"}, {"text": "Musikwiedergabe", "correct": false, "because": "Kein Datenschutzfokus"}, {"text": "Netzwerkwartung", "correct": false, "because": "Technische Aufgabe"}]');

