-- Projektdurchführung.sql (Umsetzung von Projekten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Projektdurchführung immer strikt an den Plan gebunden?', 2, '[{"text": "Nein", "correct": true, "because": "Anpassungen bei Änderungen möglich"}, {"text": "Ja", "correct": false, "because": "Flexibilität nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Projektdurchführung?', 3, '[{"text": "Erreichung der Projektziele", "correct": true, "because": "Setzt Plan in Ergebnisse um"}, {"text": "Maximale Kosten", "correct": false, "because": "Kostenminimierung oft Ziel"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Systematik bevorzugt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aktivitäten gehören zur Projektdurchführung?', 5, '[{"text": "Aufgabenkoordination", "correct": true, "because": "Synchronisiert Team"}, {"text": "Fortschrittskontrolle", "correct": true, "because": "Überwacht Zeitplan"}, {"text": "Bildbearbeitung", "correct": false, "because": "Nicht projektbezogen"}, {"text": "Musikwiedergabe", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Projektdurchführung benötigt Kommunikation. b) Sie ignoriert Ressourcen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) berücksichtigt Ressourcen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Projektdurchführung?', 4, '[{"text": "Zeitmanagement", "correct": false, "because": "Sichert Termine"}, {"text": "Risikomanagement", "correct": false, "because": "Minimiert Probleme"}, {"text": "Bürogestaltung", "correct": true, "because": "Irrelevant für Ablauf"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Projektdurchführung nur technische Aufgaben umfasst?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Management und Kommunikation"}, {"text": "Ja", "correct": false, "because": "Umfassender Prozess"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt der Projektleiter in der Durchführung?', 3, '[{"text": "Koordination", "correct": true, "because": "Lenkt Team und Ressourcen"}, {"text": "Nur Berichtswesen", "correct": false, "because": "Breitere Aufgaben"}, {"text": "Manuelle Arbeit", "correct": false, "because": "Führung im Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Werkzeuge unterstützen die Projektdurchführung?', 5, '[{"text": "Projektmanagementsoftware", "correct": true, "because": "Wie Jira oder MS Project"}, {"text": "Kommunikationstools", "correct": true, "because": "Wie Slack oder Teams"}, {"text": "Musikwiedergabe", "correct": false, "because": "Nicht projektbezogen"}, {"text": "Grafikdesign", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Projektdurchführung umfasst Monitoring. b) Sie benötigt keine Planung. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) basiert auf Planung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Projektdurchführung?', 4, '[{"text": "Teamkommunikation", "correct": false, "because": "Fördert Zusammenarbeit"}, {"text": "Ressourcenplanung", "correct": false, "because": "Sichert Einsatz"}, {"text": "3D-Modellierung", "correct": true, "because": "Nicht projektbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Projektdurchführung dasselbe wie die Planung?', 2, '[{"text": "Nein", "correct": true, "because": "Durchführung setzt Plan um"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Phasen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Projektdurchführung?', 4, '[{"text": "Zeitdruck", "correct": true, "because": "Beeinflusst Termine"}, {"text": "Ressourcenknappheit", "correct": true, "because": "Begrenzt Kapazitäten"}, {"text": "Hohe Auflösung", "correct": false, "because": "Kein Projektproblem"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Projektdurchführung immer reibungslos läuft. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Herausforderungen üblich"}, {"text": "Ja", "correct": false, "because": "Probleme möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Projektdurchführung?', 3, '[{"text": "Kommunikation", "correct": true, "because": "Sichert Zusammenarbeit"}, {"text": "Minimale Kontrolle", "correct": false, "because": "Überwachung nötig"}, {"text": "Manuelle Aufgaben", "correct": false, "because": "Systematik besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Projektdurchführung benötigt Monitoring. b) Sie ignoriert Risiken.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) berücksichtigt Risiken"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren verbessern die Projektdurchführung?', 5, '[{"text": "Klare Rollen", "correct": true, "because": "Vermeiden Verwirrung"}, {"text": "Regelmäßige Updates", "correct": true, "because": "Halten Team informiert"}, {"text": "Hohe Komplexität", "correct": false, "because": "Eher Nachteil"}, {"text": "Einmalige Planung", "correct": false, "because": "Fortlaufende Anpassung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Projektdurchführung unwichtig?', 3, '[{"text": "Fortschrittskontrolle", "correct": false, "because": "Sichert Zeitplan"}, {"text": "Kommunikation", "correct": false, "because": "Fördert Zusammenarbeit"}, {"text": "Musikwiedergabe", "correct": true, "because": "Kein Projektfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Projektdurchführung für agile Projekte geeignet ist?', 2, '[{"text": "Ja", "correct": true, "because": "Flexibel und iterativ"}, {"text": "Nein", "correct": false, "because": "Agile nutzt Durchführung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Umfasst die Projektdurchführung nur technische Aufgaben?', 3, '[{"text": "Nein", "correct": true, "because": "Auch Management und Kommunikation"}, {"text": "Ja", "correct": false, "because": "Breiter Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Projektdurchführung?', 4, '[{"text": "Umsetzung einer Softwareentwicklung", "correct": true, "because": "Koordiniert Team und Aufgaben"}, {"text": "Musikwiedergabe", "correct": false, "because": "Keine Projektarbeit"}, {"text": "Bildbearbeitung", "correct": false, "because": "Kreative Aufgabe"}]');

