-- Projektplanung.sql (Strukturierte Vorbereitung eines Projekts)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Projektplanung immer nur für den Projektstart relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Beeinflusst gesamten Projektverlauf"}, {"text": "Ja", "correct": false, "because": "Kontinuierliche Anpassung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Projektplanung?', 3, '[{"text": "Projektziele definieren", "correct": true, "because": "Legt Grundlage für Erfolg"}, {"text": "Maximale Dokumentation", "correct": false, "because": "Nur Teilaspekt"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Strukturierte Methoden besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Projektplanung?', 5, '[{"text": "Zeitplan", "correct": true, "because": "Definiert Meilensteine"}, {"text": "Ressourcenplanung", "correct": true, "because": "Sichert Verfügbarkeit"}, {"text": "Musikwiedergabe", "correct": false, "because": "Irrelevant"}, {"text": "Bildbearbeitung", "correct": false, "because": "Nicht planungsbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Projektplanung berücksichtigt Risiken. b) Sie ersetzt die Durchführung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist andere Phase"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Projektplanung?', 4, '[{"text": "Stakeholder-Anforderungen", "correct": false, "because": "Bestimmen Ziele"}, {"text": "Kostenplanung", "correct": false, "because": "Sichert Budget"}, {"text": "Bürogestaltung", "correct": true, "because": "Irrelevant für Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Projektplanung nur für IT-Projekte geeignet ist?', 2, '[{"text": "Nein", "correct": true, "because": "Für alle Projektarten anwendbar"}, {"text": "Ja", "correct": false, "because": "Universell einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug ist typisch für die Projektplanung?', 3, '[{"text": "Gantt-Diagramm", "correct": true, "because": "Visualisiert Zeitplan"}, {"text": "Texteditor", "correct": false, "because": "Ungeeignet für Planung"}, {"text": "Manuelle Skizzen", "correct": false, "because": "Software effizienter"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gute Projektplanung?', 5, '[{"text": "Klare Zielsetzung", "correct": true, "because": "Definiert Erfolg"}, {"text": "Effiziente Ressourcennutzung", "correct": true, "because": "Optimiert Einsatz"}, {"text": "Hohe Komplexität", "correct": false, "because": "Eher Nachteil"}, {"text": "Einmalige Nutzung", "correct": false, "because": "Kontinuierlich angepasst"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Projektplanung reduziert Risiken. b) Sie garantiert Erfolg. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) hängt von Umsetzung ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Projektplanung?', 4, '[{"text": "Meilensteine", "correct": false, "because": "Strukturieren Ablauf"}, {"text": "Ressourcen", "correct": false, "because": "Sichern Umsetzung"}, {"text": "Musikwiedergabe", "correct": true, "because": "Irrelevant für Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Projektplanung nur für den Projektleiter relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Betrifft Team und Stakeholder"}, {"text": "Ja", "correct": false, "because": "Ganzes Team involviert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Projektplanung?', 4, '[{"text": "Projektumfang", "correct": true, "because": "Definiert Aufgaben"}, {"text": "Ressourcenverfügbarkeit", "correct": true, "because": "Beeinflusst Zeitplan"}, {"text": "Grafikdesign", "correct": false, "because": "Nicht planungsrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass die Projektplanung immer starr ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Flexibel anpassbar"}, {"text": "Ja", "correct": false, "because": "Anpassung üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Projektplanung?', 3, '[{"text": "Klare Ziele", "correct": true, "because": "Leiten Ablauf"}, {"text": "Maximale Details", "correct": false, "because": "Klarheit wichtiger"}, {"text": "Manuelle Eingaben", "correct": false, "because": "Tools effizienter"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Projektplanung definiert Meilensteine. b) Sie ignoriert Kosten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) berücksichtigt Kosten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Tools unterstützen die Projektplanung?', 5, '[{"text": "MS Project", "correct": true, "because": "Erstellt Zeitpläne"}, {"text": "Trello", "correct": true, "because": "Verwaltet Aufgaben"}, {"text": "Musikwiedergabe", "correct": false, "because": "Kein Planungstool"}, {"text": "Texteditor", "correct": false, "because": "Ungeeignet für Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Projektplanung unwichtig?', 3, '[{"text": "Zeitplanung", "correct": false, "because": "Sichert Termine"}, {"text": "Risikoanalyse", "correct": false, "because": "Minimiert Probleme"}, {"text": "Bildschirmauflösung", "correct": true, "because": "Kein Planungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Projektplanung für agile Projekte geeignet ist?', 2, '[{"text": "Ja", "correct": true, "because": "Flexibel für Iterationen"}, {"text": "Nein", "correct": false, "because": "Anpassbar für Agile"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Berücksichtigt die Projektplanung immer alle Details?', 3, '[{"text": "Nein", "correct": true, "because": "Fokussiert auf Wesentliches"}, {"text": "Ja", "correct": false, "because": "Ausgewogenheit zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Projektplanung?', 4, '[{"text": "Vorbereitung einer Softwareentwicklung", "correct": true, "because": "Definiert Ziele und Ablauf"}, {"text": "Musikwiedergabe", "correct": false, "because": "Keine Planungsaufgabe"}, {"text": "Bildbearbeitung", "correct": false, "because": "Kreative Aufgabe"}]');

