-- Projektinstanzen.sql (Organisatorische Einheiten und Rollen im Projektmanagement)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Projektinstanzen immer feste Teams?', 2, '[{"text": "Nein", "correct": true, "because": "Können auch temporäre Rollen sein"}, {"text": "Ja", "correct": false, "because": "Flexibel je nach Projekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel von Projektinstanzen?', 3, '[{"text": "Projektsteuerung", "correct": true, "because": "Sichern Ablauf und Entscheidungen"}, {"text": "Maximale Dokumentation", "correct": false, "because": "Nur Teilaufgabe"}, {"text": "Manuelle Arbeit", "correct": false, "because": "Koordination zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Projektinstanzen gibt es typischerweise?', 5, '[{"text": "Lenkungsausschuss", "correct": true, "because": "Entscheidet strategisch"}, {"text": "Projektteam", "correct": true, "because": "Setzt Aufgaben um"}, {"text": "Designabteilung", "correct": false, "because": "Kein Standard"}, {"text": "Musikteam", "correct": false, "because": "Irrelevant für Projekte"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Der Projektleiter gehört zu den Projektinstanzen. b) Jeder Mitarbeiter ist eine Instanz.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) nur definierte Rollen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Definition von Projektinstanzen?', 4, '[{"text": "Rollenklarheit", "correct": false, "because": "Vermeidet Konflikte"}, {"text": "Verantwortlichkeiten", "correct": false, "because": "Bestimmen Aufgaben"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob der Lenkungsausschuss operative Aufgaben übernimmt?', 2, '[{"text": "Nein", "correct": true, "because": "Fokussiert auf strategische Entscheidungen"}, {"text": "Ja", "correct": false, "because": "Operative Aufgaben beim Team"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle hat der Projektleiter in den Projektinstanzen?', 3, '[{"text": "Koordination", "correct": true, "because": "Steuert Team und Fortschritt"}, {"text": "Nur Dokumentation", "correct": false, "because": "Breitere Verantwortung"}, {"text": "Manuelle Umsetzung", "correct": false, "because": "Team übernimmt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben übernehmen Projektinstanzen?', 5, '[{"text": "Entscheidungsfindung", "correct": true, "because": "Lenkungsausschuss entscheidet"}, {"text": "Umsetzung", "correct": true, "because": "Team führt Aufgaben aus"}, {"text": "Grafikdesign", "correct": false, "because": "Projektabhängig"}, {"text": "Musikwiedergabe", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Projektinstanzen definieren Verantwortlichkeiten. b) Sie sind immer extern. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) meist intern"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Projektinstanzen?', 4, '[{"text": "Rollenzuweisung", "correct": false, "because": "Definiert Verantwortung"}, {"text": "Kommunikationswege", "correct": false, "because": "Sichern Koordination"}, {"text": "Bildbearbeitung", "correct": true, "because": "Irrelevant für Instanzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist der Lenkungsausschuss Teil jeder Projektinstanz?', 2, '[{"text": "Nein", "correct": true, "because": "Nur in größeren Projekten"}, {"text": "Ja", "correct": false, "because": "Abhängig von Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Instanzen unterstützen die Entscheidungsfindung?', 4, '[{"text": "Lenkungsausschuss", "correct": true, "because": "Trifft strategische Entscheidungen"}, {"text": "Projektleiter", "correct": true, "because": "Koordiniert und entscheidet operativ"}, {"text": "Marketingteam", "correct": false, "because": "Nicht Standardinstanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Projektinstanzen immer groß sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Größe abhängig vom Projekt"}, {"text": "Ja", "correct": false, "because": "Auch kleine Teams möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Definition von Projektinstanzen?', 3, '[{"text": "Klare Verantwortlichkeiten", "correct": true, "because": "Vermeidet Konflikte"}, {"text": "Maximale Mitglieder", "correct": false, "because": "Effizienz wichtiger"}, {"text": "Manuelle Zuweisung", "correct": false, "because": "Struktur zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Projektinstanzen fördern Kommunikation. b) Sie sind nur für externe Partner.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) meist intern"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten klar definierte Projektinstanzen?', 5, '[{"text": "Effiziente Koordination", "correct": true, "because": "Rollen sind klar"}, {"text": "Konfliktvermeidung", "correct": true, "because": "Verantwortung definiert"}, {"text": "Hohe Komplexität", "correct": false, "because": "Eher Nachteil"}, {"text": "Unabhängige Teams", "correct": false, "because": "Koordination zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Projektinstanzen unwichtig?', 3, '[{"text": "Kommunikationsstruktur", "correct": false, "because": "Sichert Zusammenarbeit"}, {"text": "Rollenzuweisung", "correct": false, "because": "Definiert Aufgaben"}, {"text": "Musikwiedergabe", "correct": true, "because": "Kein Projektfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Projektteam Teil der Projektinstanzen ist?', 2, '[{"text": "Ja", "correct": true, "because": "Setzt Aufgaben um"}, {"text": "Nein", "correct": false, "because": "Kerninstanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Entscheidet der Projektleiter allein über alles?', 3, '[{"text": "Nein", "correct": true, "because": "Lenkungsausschuss oft involviert"}, {"text": "Ja", "correct": false, "because": "Koordination mit Instanzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu Projektinstanzen?', 4, '[{"text": "Aufbau eines IT-Projekts", "correct": true, "because": "Rollen wie Leiter, Team nötig"}, {"text": "Musikwiedergabe", "correct": false, "because": "Kein Projektkontext"}, {"text": "Bildbearbeitung", "correct": false, "because": "Kreative Aufgabe"}]');

