-- Projektteam.sql (Gruppe von Personen zur Durchführung eines Projekts)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Projektteam immer dauerhaft zusammengesetzt?', 2, '[{"text": "Nein", "correct": true, "because": "Oft temporär für Projektlaufzeit"}, {"text": "Ja", "correct": false, "because": "Flexibel je nach Projekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel eines Projektteams?', 3, '[{"text": "Projektziele erreichen", "correct": true, "because": "Setzt Aufgaben gemeinsam um"}, {"text": "Maximale Dokumentation", "correct": false, "because": "Nur Teilaufgabe"}, {"text": "Manuelle Arbeit", "correct": false, "because": "Koordination zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rollen gehören typischerweise zu einem Projektteam?', 5, '[{"text": "Projektleiter", "correct": true, "because": "Steuert das Team"}, {"text": "Fachmitarbeiter", "correct": true, "because": "Bringen Expertise ein"}, {"text": "Grafikdesigner", "correct": false, "because": "Projektabhängig"}, {"text": "Musikproduzent", "correct": false, "because": "Nicht standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Projektteam arbeitet kollaborativ. b) Es benötigt keine Kommunikation.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Kommunikation essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Zusammenstellung eines Projektteams?', 4, '[{"text": "Kompetenzen", "correct": false, "because": "Bestimmen Erfolg"}, {"text": "Kommunikationsfähigkeit", "correct": false, "because": "Fördert Zusammenarbeit"}, {"text": "Bürogestaltung", "correct": true, "because": "Irrelevant für Team"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Projektteam nur aus internen Mitarbeitern besteht?', 2, '[{"text": "Nein", "correct": true, "because": "Externe Experten möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Projektteam?', 3, '[{"text": "Umsetzung von Arbeitspaketen", "correct": true, "because": "Setzt Projektziele um"}, {"text": "Nur Berichtswesen", "correct": false, "because": "Breitere Verantwortung"}, {"text": "Manuelle Planung", "correct": false, "because": "Koordination wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren fördern ein effektives Projektteam?', 5, '[{"text": "Klare Rollen", "correct": true, "because": "Vermeiden Konflikte"}, {"text": "Gute Kommunikation", "correct": true, "because": "Sichert Zusammenarbeit"}, {"text": "Einheitliche Kleidung", "correct": false, "because": "Irrelevant"}, {"text": "Musikwiedergabe", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Projektteam benötigt einen Leiter. b) Alle Mitglieder sind gleichberechtigt. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) Rollen sind unterschiedlich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Projektteam?', 4, '[{"text": "Kompetenzen", "correct": false, "because": "Treiben Erfolg"}, {"text": "Zielvorgaben", "correct": false, "because": "Leiten Arbeit"}, {"text": "3D-Modellierung", "correct": true, "because": "Projektabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Arbeitet ein Projektteam isoliert?', 2, '[{"text": "Nein", "correct": true, "because": "Interagiert mit Stakeholdern"}, {"text": "Ja", "correct": false, "because": "Zusammenarbeit nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es in einem Projektteam?', 4, '[{"text": "Kommunikationsprobleme", "correct": true, "because": "Beeinträchtigen Koordination"}, {"text": "Rollenkonflikte", "correct": true, "because": "Verursachen Spannungen"}, {"text": "Bürofläche", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Projektteam immer groß sein muss. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Größe abhängig vom Projekt"}, {"text": "Ja", "correct": false, "because": "Kleine Teams möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Bildung eines Projektteams?', 3, '[{"text": "Passende Kompetenzen", "correct": true, "because": "Sichern Erfolg"}, {"text": "Maximale Mitglieder", "correct": false, "because": "Effizienz wichtiger"}, {"text": "Manuelle Auswahl", "correct": false, "because": "Strukturierte Auswahl besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Projektteam benötigt klare Ziele. b) Es arbeitet ohne Leitung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) braucht Führung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Tools unterstützen ein Projektteam?', 5, '[{"text": "Kommunikationstools", "correct": true, "because": "Wie Slack fördern Austausch"}, {"text": "Projektmanagementsoftware", "correct": true, "because": "Wie Jira für Aufgaben"}, {"text": "Musikwiedergabe", "correct": false, "because": "Kein Teamtool"}, {"text": "Bildbearbeitung", "correct": false, "because": "Projektabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist für ein Projektteam unwichtig?', 3, '[{"text": "Kommunikation", "correct": false, "because": "Fördert Zusammenarbeit"}, {"text": "Rollenverteilung", "correct": false, "because": "Sichert Klarheit"}, {"text": "Bildschirmauflösung", "correct": true, "because": "Kein Teamfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Projektteam externe Berater einbeziehen kann?', 2, '[{"text": "Ja", "correct": true, "because": "Erweitert Expertise"}, {"text": "Nein", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Projektteam ohne Projektleiter möglich?', 3, '[{"text": "Nein", "correct": true, "because": "Leitung koordiniert"}, {"text": "Ja", "correct": false, "because": "Führung meist nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einem Projektteam?', 4, '[{"text": "Entwicklung einer Software", "correct": true, "because": "Team setzt Aufgaben um"}, {"text": "Musikwiedergabe", "correct": false, "because": "Keine Teamaufgabe"}, {"text": "Netzwerkwartung", "correct": false, "because": "Technische Aufgabe"}]');

