-- Projektmanagement.sql (Methoden und Prozesse zur Steuerung von Projekten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Projektmanagement nur für große Projekte notwendig?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte profitieren"}, {"text": "Ja", "correct": false, "because": "Universell einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel von Projektmanagement?', 3, '[{"text": "Erfolgreiche Projektumsetzung", "correct": true, "because": "Ziele innerhalb Zeit und Budget erreichen"}, {"text": "Maximale Dokumentation", "correct": false, "because": "Nur ein Teilaspekt"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Strukturierte Methoden besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phasen umfasst Projektmanagement typischerweise?', 5, '[{"text": "Planung", "correct": true, "because": "Definiert Ablauf"}, {"text": "Durchführung", "correct": true, "because": "Setzt Plan um"}, {"text": "Musikwiedergabe", "correct": false, "because": "Irrelevant"}, {"text": "Bildbearbeitung", "correct": false, "because": "Nicht projektbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Projektmanagement nutzt Meilensteine. b) Es ersetzt Teamarbeit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) unterstützt Teamarbeit"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Anwendung von Projektmanagement?', 4, '[{"text": "Zeitplanung", "correct": false, "because": "Bestimmt Ablauf"}, {"text": "Ressourcenmanagement", "correct": false, "because": "Sichert Verfügbarkeit"}, {"text": "Bürogestaltung", "correct": true, "because": "Irrelevant für Steuerung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Projektmanagement nur für IT-Projekte geeignet ist?', 2, '[{"text": "Nein", "correct": true, "because": "Für alle Projektarten anwendbar"}, {"text": "Ja", "correct": false, "because": "Universell einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug ist für Projektmanagement typisch?', 3, '[{"text": "Gantt-Diagramm", "correct": true, "because": "Visualisiert Zeitplan"}, {"text": "Texteditor", "correct": false, "because": "Ungeeignet für Planung"}, {"text": "Manuelle Notizen", "correct": false, "because": "Software effizienter"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet effektives Projektmanagement?', 5, '[{"text": "Termintreue", "correct": true, "because": "Hält Zeitplan ein"}, {"text": "Kostenkontrolle", "correct": true, "because": "Verhindert Budgetüberschreitung"}, {"text": "Hohe Komplexität", "correct": false, "because": "Eher Nachteil"}, {"text": "Einmalige Nutzung", "correct": false, "because": "Kontinuierlich angewendet"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Projektmanagement steigert Effizienz. b) Es vermeidet Teamkommunikation. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) fördert Kommunikation"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Projektmanagement?', 4, '[{"text": "Projektziele", "correct": false, "because": "Definieren Erfolg"}, {"text": "Ressourcenplanung", "correct": false, "because": "Sichert Umsetzung"}, {"text": "Musikwiedergabe", "correct": true, "because": "Irrelevant für Management"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist agiles Projektmanagement dasselbe wie klassisches?', 2, '[{"text": "Nein", "correct": true, "because": "Agil ist flexibler"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Ansätze"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden gehören zum Projektmanagement?', 4, '[{"text": "Scrum", "correct": true, "because": "Agile Methode"}, {"text": "Wasserfall", "correct": true, "because": "Klassische Methode"}, {"text": "Bildbearbeitung", "correct": false, "because": "Keine Managementmethode"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Projektmanagement immer teuer ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten abhängig von Projekt"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig teuer"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich im Projektmanagement?', 3, '[{"text": "Klare Kommunikation", "correct": true, "because": "Verhindert Missverständnisse"}, {"text": "Maximale Dokumentation", "correct": false, "because": "Ausgewogen wichtiger"}, {"text": "Manuelle Kontrolle", "correct": false, "because": "Systeme effizienter"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Projektmanagement steuert Risiken. b) Es ignoriert Teamdynamik.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) berücksichtigt Team"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Tools unterstützen Projektmanagement?', 5, '[{"text": "Jira", "correct": true, "because": "Verwaltet Aufgaben"}, {"text": "Trello", "correct": true, "because": "Visualisiert Fortschritt"}, {"text": "Musikwiedergabe", "correct": false, "because": "Kein Managementtool"}, {"text": "Texteditor", "correct": false, "because": "Ungeeignet für Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist im Projektmanagement unwichtig?', 3, '[{"text": "Zeitplanung", "correct": false, "because": "Sichert Termintreue"}, {"text": "Risikomanagement", "correct": false, "because": "Minimiert Probleme"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Managementfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Projektmanagement für Einzelpersonen geeignet ist?', 2, '[{"text": "Ja", "correct": true, "because": "Auch für Solo-Projekte nützlich"}, {"text": "Nein", "correct": false, "because": "Skalierbar für alle"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzt Projektmanagement die Teamarbeit?', 3, '[{"text": "Nein", "correct": true, "because": "Unterstützt Teamarbeit"}, {"text": "Ja", "correct": false, "because": "Teamarbeit essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu Projektmanagement?', 4, '[{"text": "Koordination einer Softwareentwicklung", "correct": true, "because": "Steuert Zeit, Ressourcen"}, {"text": "Musikwiedergabe", "correct": false, "because": "Keine Projektarbeit"}, {"text": "Bildbearbeitung", "correct": false, "because": "Kreative Aufgabe"}]');

