-- Pseudonymisierung.sql (Datenschutztechnik zur Anonymisierung von Daten, relevant für Fachinformatiker im Kontext von IT-Sicherheit und DSGVO)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Pseudonymisierung dasselbe wie Anonymisierung?', 2, '[{"text": "Nein", "correct": true, "because": "Pseudonymisierte Daten sind rückführbar"}, {"text": "Ja", "correct": false, "because": "Anonymisierte Daten nicht rückführbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Pseudonymisierung?', 3, '[{"text": "Datenschutz erhöhen", "correct": true, "because": "Vermindert Identifizierbarkeit"}, {"text": "Daten löschen", "correct": false, "because": "Daten bleiben nutzbar"}, {"text": "Manuelle Verarbeitung", "correct": false, "because": "Automatisiert besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat die Pseudonymisierung?', 5, '[{"text": "Ersetzung von Identifikatoren", "correct": true, "because": "Z. B. durch Pseudonyme"}, {"text": "Rückführbarkeit mit Zusatzinformationen", "correct": true, "because": "Unterschied zu Anonymisierung"}, {"text": "Vollständige Anonymität", "correct": false, "because": "Rückführbar möglich"}, {"text": "Musikwiedergabe", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Pseudonymisierung ist in der DSGVO definiert. b) Sie macht Daten immer anonym.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) Daten bleiben rückführbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Pseudonymisierung?', 4, '[{"text": "Sicherheit der Zusatzinformationen", "correct": false, "because": "Schützt Rückführbarkeit"}, {"text": "Datenschutzvorgaben", "correct": false, "because": "DSGVO-konform sein"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Pseudonymisierung personenbezogene Daten löscht?', 2, '[{"text": "Nein", "correct": true, "because": "Daten bleiben nutzbar"}, {"text": "Ja", "correct": false, "because": "Nur Identifikatoren ersetzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird für Pseudonymisierung genutzt?', 3, '[{"text": "Ersetzen von Namen durch Codes", "correct": true, "because": "Verhindert direkte Identifikation"}, {"text": "Datenlöschung", "correct": false, "because": "Nicht Pseudonymisierung"}, {"text": "Manuelle Verschlüsselung", "correct": false, "because": "Automatisierung üblich"}]'),
('0000000a0-0000-0000-0000-000000000000', 'Welche Vorteile bietet Pseudonymisierung?', 5, '[{"text": "Datenschutz", "correct": true, "because": "Reduziert Identifizierbarkeit"}, {"text": "Datenverwendbarkeit", "correct": true, "because": "Für Analysen nutzbar"}, {"text": "Vollständige Anonymität", "correct": false, "because": "Rückführbar möglich"}, {"text": "Hohe Komplexität", "correct": false, "because": "Eher vereinfacht"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Pseudonymisierung schützt Daten. b) Sie ist immer reversibel. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) abhängig von Zusatzinformationen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht immer korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Pseudonymisierung?', 4, '[{"text": "Pseudonyme", "correct": false, "because": "Ersetzen Identifikatoren"}, {"text": "Sichere Speicherung", "correct": false, "because": "Schützt Zusatzdaten"}, {"text": "Musikwiedergabe", "correct": true, "because": "Irrelevant für Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Pseudonymisierung in der DSGVO vorgeschrieben?', 2, '[{"text": "Nein", "correct": true, "because": "Empfohlen, nicht vorgeschrieben"}, {"text": "Ja", "correct": false, "because": "Freiwillige Maßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Techniken werden für Pseudonymisierung verwendet?', 4, '[{"text": "Hashing", "correct": true, "because": "Ersetzt Identifikatoren"}, {"text": "Tokenisierung", "correct": true, "because": "Verknüpft Pseudonyme"}, {"text": "Grafische Darstellung", "correct": false, "because": "Kein Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Pseudonymisierung keine Sicherheitsmaßnahme ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Reduziert Identifizierungsrisiko"}, {"text": "Ja", "correct": false, "because": "Teil der Datensicherheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Pseudonymisierung?', 3, '[{"text": "Sicherheit der Zusatzdaten", "correct": true, "because": "Verhindert Rückführung"}, {"text": "Maximale Datenmenge", "correct": false, "because": "Datensparsamkeit zählt"}, {"text": "Manuelle Zuweisung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Pseudonymisierung ist DSGVO-konform. b) Sie ersetzt Verschlüsselung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist andere Technik"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen profitieren von Pseudonymisierung?', 5, '[{"text": "Datenanalysen", "correct": true, "because": "Schützen Identität"}, {"text": "Medizinische Forschung", "correct": true, "because": "Datenschutz bei Studien"}, {"text": "Öffentliche Freigabe", "correct": false, "because": "Nicht anonym genug"}, {"text": "Musikwiedergabe", "correct": false, "because": "Kein Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Pseudonymisierung unwichtig?', 3, '[{"text": "Datensicherheit", "correct": false, "because": "Schützt Rückführung"}, {"text": "Pseudonyme", "correct": false, "because": "Kern der Methode"}, {"text": "Bildschirmauflösung", "correct": true, "because": "Kein Datenschutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Pseudonymisierung für alle Daten gilt?', 2, '[{"text": "Nein", "correct": true, "because": "Nur personenbezogene Daten"}, {"text": "Ja", "correct": false, "because": "Spezifisch für Datenschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzt Pseudonymisierung die Daten vollständig?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Identifikatoren ersetzt"}, {"text": "Ja", "correct": false, "because": "Daten bleiben nutzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Pseudonymisierung?', 4, '[{"text": "Analyse von Patientendaten", "correct": true, "because": "Schützt Identität"}, {"text": "Musikwiedergabe", "correct": false, "because": "Kein Datenschutz"}, {"text": "Netzwerkkonfiguration", "correct": false, "because": "Technische Aufgabe"}]');

