-- Punkt-zu-Punkt.sql (Direkte Netzwerkverbindungen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist eine Punkt-zu-Punkt-Verbindung immer physisch direkt?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch virtuell über Netzwerke sein"}, {"text": "Ja", "correct": false, "because": "Nicht immer physisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel einer Punkt-zu-Punkt-Verbindung?', 3, '[{"text": "Direkte Kommunikation", "correct": true, "because": "Verbindet zwei Punkte ohne Zwischenschaltung"}, {"text": "Datenverteilung", "correct": false, "because": "Eher Broadcast"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Automatisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien nutzen Punkt-zu-Punkt-Verbindungen?', 5, '[{"text": "VPN", "correct": true, "because": "Sichere direkte Verbindungen"}, {"text": "Leitungsvermittlung", "correct": true, "because": "Z. B. Telefonleitungen"}, {"text": "Cloud-Speicher", "correct": false, "because": "Nicht direkt"}, {"text": "Musikwiedergabe", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Punkt-zu-Punkt ist bidirektional. b) Sie unterstützt immer mehrere Endpunkte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist für Multipoint"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Einrichtung einer Punkt-zu-Punkt-Verbindung?', 4, '[{"text": "Bandbreite", "correct": false, "because": "Beeinflusst Leistung"}, {"text": "Sicherheitsprotokolle", "correct": false, "because": "Schützen Daten"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Verbindung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Punkt-zu-Punkt-Verbindung für Broadcast geeignet ist?', 2, '[{"text": "Nein", "correct": true, "because": "Nur zwei Endpunkte"}, {"text": "Ja", "correct": false, "because": "Broadcast ist Multipoint"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wird oft für Punkt-zu-Punkt-Verbindungen genutzt?', 3, '[{"text": "PPP", "correct": true, "because": "Point-to-Point Protocol"}, {"text": "HTTP", "correct": false, "because": "Webprotokoll"}, {"text": "Manuelles Routing", "correct": false, "because": "Automatisiert besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Punkt-zu-Punkt-Verbindung?', 5, '[{"text": "Hohe Sicherheit", "correct": true, "because": "Direkte Verbindung"}, {"text": "Einfache Konfiguration", "correct": true, "because": "Nur zwei Punkte"}, {"text": "Hohe Latenz", "correct": false, "because": "Eher niedrig"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Automatisierung üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Punkt-zu-Punkt ist sicherer als Multipoint. b) Es ist immer drahtlos. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) kann auch kabelgebunden"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine Punkt-zu-Punkt-Verbindung?', 4, '[{"text": "Endgeräte", "correct": false, "because": "Zwei Punkte nötig"}, {"text": "Protokoll", "correct": false, "because": "Regelt Kommunikation"}, {"text": "3D-Modellierung", "correct": true, "because": "Irrelevant für Netzwerk"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Punkt-zu-Punkt dasselbe wie Multipoint?', 2, '[{"text": "Nein", "correct": true, "because": "Multipoint hat mehrere Endpunkte"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Topologien"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei Punkt-zu-Punkt-Verbindungen?', 4, '[{"text": "Bandbreitenbegrenzung", "correct": true, "because": "Abhängig von Leitung"}, {"text": "Sicherheitskonfiguration", "correct": true, "because": "Schutz nötig"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Problem"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Punkt-zu-Punkt immer teurer ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten abhängig von Technologie"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig teuer"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einer Punkt-zu-Punkt-Verbindung?', 3, '[{"text": "Sicherheit", "correct": true, "because": "Schützt Daten"}, {"text": "Maximale Endpunkte", "correct": false, "because": "Nur zwei Punkte"}, {"text": "Manuelle Konfiguration", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Punkt-zu-Punkt nutzt oft PPP. b) Es ist für Broadcast geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist Multipoint"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen nutzen Punkt-zu-Punkt-Verbindungen?', 5, '[{"text": "WAN-Verbindungen", "correct": true, "because": "Z. B. Standortvernetzung"}, {"text": "VPN-Tunnel", "correct": true, "because": "Sichere Verbindungen"}, {"text": "Cloud-Speicher", "correct": false, "because": "Mehrere Endpunkte"}, {"text": "Musikwiedergabe", "correct": false, "because": "Nicht netzwerkbezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Punkt-zu-Punkt-Verbindungen unwichtig?', 3, '[{"text": "Latenz", "correct": false, "because": "Beeinflusst Leistung"}, {"text": "Sicherheit", "correct": false, "because": "Schützt Daten"}, {"text": "Bildschirmauflösung", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Punkt-zu-Punkt-Verbindungen skalierbar sind?', 2, '[{"text": "Nein", "correct": true, "because": "Begrenzt auf zwei Punkte"}, {"text": "Ja", "correct": false, "because": "Skalierbarkeit eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann Punkt-zu-Punkt drahtlos sein?', 3, '[{"text": "Ja", "correct": true, "because": "Z. B. Funkverbindungen"}, {"text": "Nein", "correct": false, "because": "Kabel nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einer Punkt-zu-Punkt-Verbindung?', 4, '[{"text": "VPN zwischen zwei Büros", "correct": true, "because": "Direkte sichere Verbindung"}, {"text": "Musikwiedergabe", "correct": false, "because": "Keine Netzwerkaufgabe"}, {"text": "Broadcast-Streaming", "correct": false, "because": "Multipoint"}]');

