-- Projekt Organisation: Fehlermanagement - Verwalten von Supportanfragen
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist das Verwalten von Supportanfragen ein wichtiger Teil des Fehlermanagements?', 2, '[{"text": "Ja", "correct": true, "because": "Behandelt Fehler und Anfragen"}, {"text": "Nein", "correct": false, "because": "Es ist relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt das Verwalten von Supportanfragen?', 3, '[{"text": "Schnelle und effiziente Problemlösung", "correct": true, "because": "Sichert Zufriedenheit"}, {"text": "Projektziele neu definieren", "correct": false, "because": "Initiierungsschritt"}, {"text": "Kosten direkt senken", "correct": false, "because": "Nebenaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Supportanfragen werden priorisiert. b) Sie werden nur im Abschluss bearbeitet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, fortlaufend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte gehören zum Verwalten von Supportanfragen?', 4, '[{"text": "Anfragen erfassen", "correct": true, "because": "Erster Schritt"}, {"text": "Unklare Antworten", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Anfragen zuweisen", "correct": true, "because": "Fördert Bearbeitung"}, {"text": "Lösung dokumentieren", "correct": true, "because": "Sichert Nachweis"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Projekt ohne Verwaltung von Supportanfragen erfolgreich sein?', 2, '[{"text": "Nein", "correct": true, "because": "Probleme bleiben ungelöst"}, {"text": "Ja", "correct": false, "because": "Unzufriedenheit droht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt das Verwalten von Supportanfragen?', 3, '[{"text": "Unterstützung der Projektqualität", "correct": true, "because": "Behebt Probleme"}, {"text": "Team neu einteilen", "correct": false, "because": "Projektleiteraufgabe"}, {"text": "Projekt finanzieren", "correct": false, "because": "Auftraggeberaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist das Verwalten von Supportanfragen nur für IT-Projekte relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle Projekte"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe gehört zum Verwalten von Supportanfragen?', 3, '[{"text": "Anfragen systematisch bearbeiten", "correct": true, "because": "Fördert Effizienz"}, {"text": "Zeitplan neu erstellen", "correct": false, "because": "Planungsaufgabe"}, {"text": "Kosten neu kalkulieren", "correct": false, "because": "Controlling-Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Supportanfragen erfordern Koordination. b) Sie sind immer unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, oft kritisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Verwaltung von Supportanfragen?', 3, '[{"text": "Unzufriedenheit bei Stakeholdern", "correct": true, "because": "Probleme ungelöst"}, {"text": "Projekt wird schneller", "correct": false, "because": "Eher Verzögerung"}, {"text": "Qualität steigt", "correct": false, "because": "Probleme bleiben"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Verwaltung von Supportanfragen ohne System erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Struktur nötig"}, {"text": "Ja", "correct": false, "because": "Unsystematisch unpraktisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt die Verwaltung von Supportanfragen?', 3, '[{"text": "Ticket für Bug zuweisen", "correct": true, "because": "Konkret und real"}, {"text": "Irgendwas bearbeiten", "correct": false, "because": "Zu vage"}, {"text": "Team soll Anfragen ignorieren", "correct": false, "because": "Keine Verwaltung"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Verwaltung von Supportanfragen nur für den Projektleiter relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Team bearbeitet Anfragen"}, {"text": "Ja", "correct": false, "because": "Projektweite Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente sind bei der Verwaltung von Supportanfragen wichtig?', 4, '[{"text": "Erfassung der Anfrage", "correct": true, "because": "Definiert Problem"}, {"text": "Unklare Priorität", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Zuweisung an Verantwortliche", "correct": true, "because": "Fördert Lösung"}, {"text": "Statusverfolgung", "correct": true, "because": "Sichert Fortschritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Verwaltung von Supportanfragen dokumentiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Nachvollziehbarkeit wichtig"}, {"text": "Nein", "correct": false, "because": "Dokumentation hilft"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug unterstützt die Verwaltung von Supportanfragen?', 3, '[{"text": "Support-Ticketsystem", "correct": true, "because": "Verwaltet Anfragen"}, {"text": "Keine Struktur", "correct": false, "because": "Fehlt Übersicht"}, {"text": "Zufällige Notizen", "correct": false, "because": "Unsystematisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Verwaltung von Supportanfragen ohne Priorisierung erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Dringlichkeit unklar"}, {"text": "Ja", "correct": false, "because": "Unpraktisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor erschwert die Verwaltung von Supportanfragen?', 3, '[{"text": "Fehlende Kommunikation", "correct": true, "because": "Verhindert Koordination"}, {"text": "Klarer Prozess", "correct": false, "because": "Fördert Verwaltung"}, {"text": "Gute Dokumentation", "correct": false, "because": "Unterstützt Prozess"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Verwaltung von Supportanfragen steigert Effizienz. b) Sie ist nur für technische Probleme.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, breit anwendbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen der Verwaltung von Supportanfragen?', 3, '[{"text": "Schnelle Problemlösung", "correct": true, "because": "Fördert Fortschritt"}, {"text": "Maximale Unklarheit", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Bearbeitung", "correct": false, "because": "Fördert Lösung"}]');

