-- MulticastNutzung (Netzwerkübersicht, Debugging).sql
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Multicast nur für Netzwerkübersicht gedacht?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Streaming und Debugging"}, {"text": "Ja", "correct": false, "because": "Nutzung ist breiter"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt Multicast beim Debugging?', 3, '[{"text": "Geräteerkennung", "correct": true, "because": "Testet Gruppenantwort"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Nicht Multicast-Aufgabe"}, {"text": "Bandbreitensteuerung", "correct": false, "because": "Netzwerkabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben unterstützt Multicast im Netzwerk?', 5, '[{"text": "Netzwerkübersicht", "correct": true, "because": "Zeigt aktive Knoten"}, {"text": "Debugging", "correct": true, "because": "Testet Erreichbarkeit"}, {"text": "Einzelverbindungen", "correct": false, "because": "Unicast-Aufgabe"}, {"text": "Paketkompression", "correct": false, "because": "Nicht Multicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Multicast hilft bei der Netzwerkübersicht. b) Es ersetzt Ping.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ping bleibt eigenständig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Multicast-Nutzung?', 4, '[{"text": "Gruppenadressen", "correct": false, "because": "Definiert Empfänger"}, {"text": "Scope", "correct": false, "because": "Begrenzt Reichweite"}, {"text": "Einzel-IPs", "correct": true, "because": "Multicast ist gruppenbasiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Multicast beim Debugging Latenz misst?', 2, '[{"text": "Nein", "correct": true, "because": "Ping misst Latenz"}, {"text": "Ja", "correct": false, "because": "Fokus auf Erreichbarkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Adresse nutze ich für eine Netzwerkübersicht?', 3, '[{"text": "FF02::1", "correct": true, "because": "Alle Knoten im Segment"}, {"text": "FE80::1", "correct": false, "because": "Unicast-Adresse"}, {"text": "2001:db8::1", "correct": false, "because": "Globale Unicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Multicast beim Debugging?', 5, '[{"text": "Gruppenantwort", "correct": true, "because": "Testet mehrere Geräte"}, {"text": "Netzwerkerkennung", "correct": true, "because": "Zeigt aktive Knoten"}, {"text": "Datenflusssteuerung", "correct": false, "because": "TCP-Aufgabe"}, {"text": "Hohe Sicherheit", "correct": false, "because": "Keine Verschlüsselung"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Multicast zeigt Netzwerkübersicht. b) Es ist nur für große Netze. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch kleine Netze profitieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Multicast beim Debugging?', 4, '[{"text": "Gruppenadresse", "correct": false, "because": "Definiert Zielgruppe"}, {"text": "ICMPv6", "correct": false, "because": "Protokollbasis"}, {"text": "DNS-Server", "correct": true, "because": "Nicht Multicast-relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Nutzt Multicast beim Debugging Unicast?', 2, '[{"text": "Nein", "correct": true, "because": "Multicast ist gruppenbasiert"}, {"text": "Ja", "correct": false, "because": "Verwechselt mit Antwort"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Adresse hilft mir, alle Geräte zu debuggen?', 4, '[{"text": "FF02::1%interface", "correct": true, "because": "Alle Knoten link-lokal"}, {"text": "FF02::2", "correct": false, "because": "Nur Router"}, {"text": "FE80::1", "correct": false, "because": "Unicast"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Multicast beim Debugging ineffizient ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Effizient für Gruppen"}, {"text": "Ja", "correct": false, "because": "Reduziert Paketflut"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Multicast für Netzwerkübersicht?', 3, '[{"text": "Richtige Gruppenadresse", "correct": true, "because": "Erreicht Zielgruppe"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Netzwerkabhängig"}, {"text": "Schnelle Antwortzeit", "correct": false, "because": "Diagnoseabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Multicast testet Netzwerkgeräte. b) Es ersetzt Traceroute.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Traceroute ist eigenständig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen Multicast für Netzwerkübersicht nützlich?', 5, '[{"text": "Effiziente Gruppenabfrage", "correct": true, "because": "Weniger Pakete"}, {"text": "Link-Local-Scope", "correct": true, "because": "Lokale Reichweite"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Nicht enthalten"}, {"text": "Routing-Optimierung", "correct": false, "because": "Router-Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Multicast für Debugging unwichtig?', 3, '[{"text": "Gruppenadresse", "correct": false, "because": "Definiert Empfänger"}, {"text": "Scope", "correct": false, "because": "Begrenzt Reichweite"}, {"text": "Portnummern", "correct": true, "because": "Transportebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann Multicast globale Netzwerke debuggen?', 3, '[{"text": "Nein", "correct": true, "because": "Link-lokal beschränkt"}, {"text": "Ja", "correct": false, "because": "Scope-abhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Multicast beim Debugging Router testet?', 2, '[{"text": "Ja", "correct": true, "because": "FF02::2 für Router"}, {"text": "Nein", "correct": false, "because": "Router sind erreichbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Adresse wähle ich, um Router im Netzwerk zu debuggen?', 4, '[{"text": "FF02::2%interface", "correct": true, "because": "Alle Router link-lokal"}, {"text": "FF02::1", "correct": false, "because": "Alle Knoten"}, {"text": "FE80::1", "correct": false, "because": "Unicast"}]');

