-- # Lernfeld 5: Cyberphysische Systeme > ## IT-Sicherheit > - Datensicherung > - + Wiederherstellung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann eine Wiederherstellung aus einem Backup immer den exakten Zustand vor einem Datenverlust garantieren?', 2, '[{"text": "Nein", "correct": true, "because": "Änderungen seit letztem Backup fehlen"}, {"text": "Ja", "correct": false, "because": "Aktualität nicht gewährleistet"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Wiederherstellung aus einem Backup ohne vorherige Integritätsprüfung sicher durchführbar?', 2, '[{"text": "Nein", "correct": true, "because": "Korrupte Daten könnten wiederhergestellt werden"}, {"text": "Ja", "correct": false, "because": "Integrität muss geprüft werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Können verschlüsselte Backups ohne den passenden Schlüssel erfolgreich wiederhergestellt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Schlüssel ist für Entschlüsselung essenziell"}, {"text": "Ja", "correct": false, "because": "Ohne Schlüssel unlesbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine Wiederherstellung auf einem anderen System als dem ursprünglichen immer problemlos möglich?', 2, '[{"text": "Nein", "correct": true, "because": "Kompatibilitätsprobleme können auftreten"}, {"text": "Ja", "correct": false, "because": "Systemunterschiede sind relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine schnelle Wiederherstellung ohne vorherigen Test die Datensicherheit gefährden?', 2, '[{"text": "Ja", "correct": true, "because": "Fehlerhafte Backups könnten unbemerkt bleiben"}, {"text": "Nein", "correct": false, "because": "Tests sind essenziell"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor ist bei der Wiederherstellung aus einem Backup am kritischsten?', 2, '[{"text": "Integrität des Backups", "correct": true, "because": "Korrupte Daten sind nutzlos"}, {"text": "Speichergröße", "correct": false, "because": "Sekundär"}, {"text": "Übertragungsgeschwindigkeit", "correct": false, "because": "Wichtig, aber nicht kritisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird typischerweise verwendet, um die Wiederherstellbarkeit eines Backups zu testen?', 3, '[{"text": "Testwiederherstellung", "correct": true, "because": "Simuliert realen Einsatz"}, {"text": "Dateikomprimierung", "correct": false, "because": "Irrelevant für Test"}, {"text": "Netzwerkscan", "correct": false, "because": "Keine Testmethode"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist die größte Herausforderung bei der Wiederherstellung eines inkrementellen Backups?', 2, '[{"text": "Abhängigkeit von vorherigen Backups", "correct": true, "because": "Kette muss intakt sein"}, {"text": "Hoher Speicherbedarf", "correct": false, "because": "Eher gering"}, {"text": "Langsame Entschlüsselung", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Art von Backup ermöglicht die schnellste Wiederherstellung?', 2, '[{"text": "Vollbackup", "correct": true, "because": "Alle Daten sofort verfügbar"}, {"text": "Differenzielles Backup", "correct": false, "because": "Abhängig von Vollbackup"}, {"text": "Inkrementelles Backup", "correct": false, "because": "Mehrere Schritte nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme ist entscheidend, um die Wiederherstellung aus einem Cloud-Backup zu sichern?', 2, '[{"text": "Verfügbarkeit des Zugriffsschlüssels", "correct": true, "because": "Ohne Schlüssel keine Daten"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Hilfreich, nicht entscheidend"}, {"text": "Lokale Kopie", "correct": false, "because": "Nicht zwingend"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind für eine erfolgreiche Wiederherstellung essenziell?', 4, '[{"text": "Intaktes Backup", "correct": true, "because": "Korruption verhindert Erfolg"}, {"text": "Kompatibles System", "correct": true, "because": "Unterschiede blockieren"}, {"text": "Schnelle Hardware", "correct": false, "because": "Hilfreich, nicht essenziell"}, {"text": "Zugriff auf Schlüssel", "correct": true, "because": "Verschlüsselte Daten unlesbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können die Wiederherstellung verzögern oder verhindern?', 3, '[{"text": "Fehlende Backup-Dokumentation", "correct": true, "because": "Prozess unklar"}, {"text": "Korrupte Daten", "correct": true, "because": "Wiederherstellung unmöglich"}, {"text": "Geringe Speicherkapazität", "correct": true, "because": "Platzmangel blockiert"}, {"text": "Hohe Netzwerklatenz", "correct": false, "because": "Verzögert, verhindert nicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sollten vor einer Wiederherstellung durchgeführt werden?', 3, '[{"text": "Integritätsprüfung", "correct": true, "because": "Stellt Nutzbarkeit sicher"}, {"text": "Testwiederherstellung", "correct": true, "because": "Verifiziert Prozess"}, {"text": "Datenkomprimierung", "correct": false, "because": "Irrelevant"}, {"text": "Schlüsselverifizierung", "correct": true, "because": "Entschlüsselung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Wiederherstellung aus einem Offline-Backup?', 4, '[{"text": "Schutz vor Cyberangriffen", "correct": true, "because": "Getrennt vom Netzwerk"}, {"text": "Schnelle Verfügbarkeit", "correct": false, "because": "Physischer Zugriff nötig"}, {"text": "Unabhängigkeit von Internet", "correct": true, "because": "Keine Verbindung nötig"}, {"text": "Hohe Sicherheit", "correct": true, "because": "Weniger Angriffsfläche"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren erhöhen die Komplexität einer Wiederherstellung?', 3, '[{"text": "Heterogene Systeme", "correct": true, "because": "Kompatibilität schwierig"}, {"text": "Inkrementelle Backups", "correct": true, "because": "Mehrere Schritte nötig"}, {"text": "Kleine Datenmenge", "correct": false, "because": "Vereinfacht"}, {"text": "Verschlüsselung", "correct": true, "because": "Schlüsselmanagement nötig"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Eine Wiederherstellung ist nur mit einem Vollbackup möglich. b) Testwiederherstellungen sind gesetzlich vorgeschrieben.', 3, '[{"text": "Beides falsch", "correct": true, "because": "Andere Backup-Typen möglich, Tests nicht vorgeschrieben"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Beides stimmt", "correct": false, "because": "Beides falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Wiederherstellung aus einem Cloud-Backup erfordert eine Internetverbindung. b) Differenzielle Backups sind schneller wiederherzustellen als inkrementelle.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Cloud braucht Netz, Differenziell weniger Schritte"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine Wiederherstellung kann fehlschlagen, wenn das Backup beschädigt ist. b) Verschlüsselte Backups sind ohne Schlüssel nutzlos.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Beschädigung blockiert, Schlüssel essenziell"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Wiederherstellung auf ein anderes System ist immer mit Datenverlust verbunden. b) Ein Test der Wiederherstellung erhöht die Zuverlässigkeit.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Datenverlust nicht zwingend, Tests verbessern"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine Wiederherstellung ist ohne vorherigen Backup-Plan unmöglich. b) Offline-Backups erhöhen die Wiederherstellungssicherheit.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Plan hilfreich, nicht zwingend; Offline sicherer"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

