INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Datenschutz > Grundsätze (Art. 5) > Integrität
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Fordert der Grundsatz der Integrität gemäß Art. 5 DSGVO, dass personenbezogene Daten vor unbefugter Veränderung geschützt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Art. 5 Abs. 1f verlangt Schutz vor unbefugter Veränderung"}, {"text": "Nein", "correct": false, "because": "Integrität ist zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Integrität personenbezogener Daten ohne technische Schutzmaßnahmen gewährleistet werden?', 2, '[{"text": "Nein", "correct": true, "because": "Technische und organisatorische Maßnahmen sind erforderlich"}, {"text": "Ja", "correct": false, "because": "Ohne Schutzmaßnahmen ist Integrität gefährdet"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Integrität gemäß Art. 5 DSGVO auch die Vertraulichkeit der Daten umfassen?', 2, '[{"text": "Ja", "correct": true, "because": "Integrität und Vertraulichkeit sind eng verknüpft"}, {"text": "Nein", "correct": false, "because": "Beide Aspekte gehören zusammen"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Verstöße gegen den Grundsatz der Integrität zu rechtlichen Konsequenzen führen?', 2, '[{"text": "Ja", "correct": true, "because": "Verstöße gegen Art. 5 können sanktioniert werden"}, {"text": "Nein", "correct": false, "because": "Bußgelder sind möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Integrität nach Art. 5 DSGVO nur für digitale Daten relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Sie gilt für alle personenbezogenen Daten"}, {"text": "Ja", "correct": false, "because": "Auch papierbasierte Daten betroffen"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Was bedeutet der Grundsatz der Integrität gemäß Art. 5 DSGVO?', 2, '[{"text": "Schutz vor unbefugter oder unrechtmäßiger Veränderung", "correct": true, "because": "Art. 5 Abs. 1f definiert dies"}, {"text": "Maximierung der Datenspeicherung", "correct": false, "because": "Widerspricht DSGVO"}, {"text": "Schnelle Datenverarbeitung", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme stellt die Integrität personenbezogener Daten am effektivsten sicher?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Schützt vor unbefugter Veränderung"}, {"text": "Maximale Datenerhebung", "correct": false, "because": "Widerspricht Minimierung"}, {"text": "Manuelle Überprüfung", "correct": false, "because": "Weniger effizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt der Grundsatz der Integrität nach Art. 5 DSGVO?', 2, '[{"text": "Sicherstellung der Datenunversehrtheit", "correct": true, "because": "Schutz vor Veränderung und Verlust"}, {"text": "Erhöhung der Datenmenge", "correct": false, "because": "Kein Ziel"}, {"text": "Beschleunigung der Verarbeitung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie wird häufig genutzt, um die Integrität von Daten zu gewährleisten?', 2, '[{"text": "Hash-Funktionen", "correct": true, "because": "Erkennen Veränderungen an Daten"}, {"text": "Texteditor", "correct": false, "because": "Kein Sicherheitswerkzeug"}, {"text": "Router", "correct": false, "because": "Netzwerkgerät"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz droht bei Verstoß gegen den Grundsatz der Integrität?', 2, '[{"text": "Bußgelder", "correct": true, "because": "Verstoß gegen Art. 5 strafbar"}, {"text": "Systemausfall", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Geringere Nutzerfreundlichkeit", "correct": false, "because": "Nicht relevant"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte umfasst der Grundsatz der Integrität nach Art. 5 DSGVO?', 4, '[{"text": "Schutz vor unbefugter Veränderung", "correct": true, "because": "Kern der Integrität"}, {"text": "Vertraulichkeit", "correct": true, "because": "Schutz vor unbefugtem Zugriff"}, {"text": "Sicherstellung der Datenunversehrtheit", "correct": true, "because": "Daten bleiben unverändert"}, {"text": "Maximale Datenerhebung", "correct": false, "because": "Widerspricht Minimierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen unterstützen die Integrität gemäß Art. 5 DSGVO?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Schützt vor Manipulation"}, {"text": "Zugriffskontrollen", "correct": true, "because": "Verhindert unbefugten Zugriff"}, {"text": "Hashing", "correct": true, "because": "Erkennt Veränderungen"}, {"text": "Unbeschränkte Datenspeicherung", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bedrohungen können die Integrität personenbezogener Daten gefährden?', 4, '[{"text": "Unbefugte Veränderung", "correct": true, "because": "Direkte Manipulation"}, {"text": "Datenverlust", "correct": true, "because": "Beeinträchtigt Unversehrtheit"}, {"text": "Hackerangriffe", "correct": true, "because": "Können Daten manipulieren"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Keine Bedrohung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folgen kann ein Verstoß gegen den Grundsatz der Integrität haben?', 3, '[{"text": "Bußgelder", "correct": true, "because": "Verstoß gegen Art. 5 strafbar"}, {"text": "Schadensersatzansprüche", "correct": true, "because": "Betroffene können klagen"}, {"text": "Vertrauensverlust", "correct": true, "because": "Kunden verlieren Vertrauen"}, {"text": "Verbesserte Performance", "correct": false, "because": "Keine Folge"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien helfen, die Integrität personenbezogener Daten zu sichern?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Schützt vor Veränderung"}, {"text": "Digitale Signaturen", "correct": true, "because": "Bestätigt Unversehrtheit"}, {"text": "Zugriffsberechtigungen", "correct": true, "because": "Beschränkt Änderungen"}, {"text": "Textverarbeitung", "correct": false, "because": "Kein Sicherheitswerkzeug"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Integrität schützt Daten vor unbefugter Veränderung. b) Sie ist ohne technische Maßnahmen möglich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schutz ja, Maßnahmen nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Integrität umfasst auch Vertraulichkeit. b) Verstöße führen nie zu Bußgeldern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vertraulichkeit ja, Bußgelder möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Verschlüsselung unterstützt die Integrität. b) Integrität gilt nur für digitale Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verschlüsselung ja, alle Daten betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Hash-Funktionen helfen, die Integrität zu prüfen. b) Datenverlust ist kein Integritätsproblem.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hashing ja, Verlust betrifft Integrität"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Zugriffskontrollen schützen die Integrität. b) Integrität ist ohne Vertraulichkeit nutzlos.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kontrollen ja, Vertraulichkeit ergänzend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

