INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Datenschutz > Grundsätze (Art. 5) > Rechenschaftspflicht
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Fordert der Grundsatz der Rechenschaftspflicht gemäß Art. 5 DSGVO, dass Unternehmen die Einhaltung der Datenschutzvorschriften nachweisen können?', 2, '[{"text": "Ja", "correct": true, "because": "Art. 5 Abs. 2 verlangt Nachweisbarkeit"}, {"text": "Nein", "correct": false, "because": "Rechenschaftspflicht ist zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Rechenschaftspflicht ohne Dokumentation erfüllt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Dokumentation ist ein Kernbestandteil der Nachweispflicht"}, {"text": "Ja", "correct": false, "because": "Ohne Dokumentation fehlt der Nachweis"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Rechenschaftspflicht gemäß Art. 5 DSGVO auch technische Maßnahmen umfassen?', 2, '[{"text": "Ja", "correct": true, "because": "Technische und organisatorische Maßnahmen sind Teil davon"}, {"text": "Nein", "correct": false, "because": "Umfassender Schutz erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Verstöße gegen die Rechenschaftspflicht zu Bußgeldern führen?', 2, '[{"text": "Ja", "correct": true, "because": "Verstöße gegen Art. 5 können sanktioniert werden"}, {"text": "Nein", "correct": false, "because": "Sanktionen sind möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Rechenschaftspflicht nach Art. 5 DSGVO nur für große Unternehmen relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle Verantwortlichen unabhängig von Größe"}, {"text": "Ja", "correct": false, "because": "Anwendung ist allgemein"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Was bedeutet der Grundsatz der Rechenschaftspflicht gemäß Art. 5 DSGVO?', 2, '[{"text": "Nachweis der Einhaltung von Datenschutzvorschriften", "correct": true, "because": "Art. 5 Abs. 2 verlangt Verantwortlichkeit"}, {"text": "Maximale Datenerhebung", "correct": false, "because": "Widerspricht DSGVO"}, {"text": "Schnelle Datenverarbeitung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme ist zentral, um die Rechenschaftspflicht nach Art. 5 DSGVO zu erfüllen?', 3, '[{"text": "Dokumentation der Verarbeitungstätigkeiten", "correct": true, "because": "Nachweis durch Verzeichnis erforderlich"}, {"text": "Regelmäßige Backups", "correct": false, "because": "Schutz, nicht Nachweis"}, {"text": "Datensparsamkeit", "correct": false, "because": "Anderer Grundsatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt der Grundsatz der Rechenschaftspflicht?', 2, '[{"text": "Sicherstellung der Einhaltung der DSGVO", "correct": true, "because": "Verantwortliche müssen Compliance beweisen"}, {"text": "Erhöhung der Datenmenge", "correct": false, "because": "Kein Ziel"}, {"text": "Beschleunigung der Verarbeitung", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz droht bei Verstoß gegen die Rechenschaftspflicht?', 2, '[{"text": "Bußgelder", "correct": true, "because": "Verstoß gegen Art. 5 strafbar"}, {"text": "Systemausfall", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Geringere Nutzerfreundlichkeit", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Dokument ist für die Rechenschaftspflicht nach Art. 5 DSGVO am wichtigsten?', 2, '[{"text": "Verzeichnis der Verarbeitungstätigkeiten", "correct": true, "because": "Pflicht nach Art. 30 DSGVO"}, {"text": "Softwarehandbuch", "correct": false, "because": "Kein Datenschutzfokus"}, {"text": "Marketingplan", "correct": false, "because": "Irrelevant"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Anforderungen stellt der Grundsatz der Rechenschaftspflicht nach Art. 5 DSGVO?', 4, '[{"text": "Nachweisbarkeit", "correct": true, "because": "Einhaltung muss belegt werden"}, {"text": "Dokumentation", "correct": true, "because": "Verarbeitung muss aufgezeichnet werden"}, {"text": "Technische Maßnahmen", "correct": true, "because": "Schutz muss nachweisbar sein"}, {"text": "Maximale Datenerhebung", "correct": false, "because": "Widerspricht Minimierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen unterstützen die Rechenschaftspflicht?', 3, '[{"text": "Verzeichnis der Verarbeitungstätigkeiten", "correct": true, "because": "Pflichtdokumentation"}, {"text": "Datenschutz-Folgenabschätzung", "correct": true, "because": "Risiken dokumentieren"}, {"text": "Regelmäßige Überprüfung", "correct": true, "because": "Stellt Compliance sicher"}, {"text": "Unbegrenzte Speicherung", "correct": false, "because": "Verboten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente müssen gemäß Art. 5 DSGVO dokumentiert werden, um die Rechenschaftspflicht zu erfüllen?', 4, '[{"text": "Verarbeitungszwecke", "correct": true, "because": "Teil des Verzeichnisses"}, {"text": "Kategorien personenbezogener Daten", "correct": true, "because": "Pflichtangabe"}, {"text": "Technische Schutzmaßnahmen", "correct": true, "because": "Nachweis erforderlich"}, {"text": "Softwareentwicklungszeit", "correct": false, "because": "Kein Datenschutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folgen kann ein Verstoß gegen die Rechenschaftspflicht haben?', 3, '[{"text": "Bußgelder", "correct": true, "because": "Bis zu 20 Mio. Euro möglich"}, {"text": "Schadensersatzansprüche", "correct": true, "because": "Betroffene können klagen"}, {"text": "Verarbeitungsverbot", "correct": true, "because": "Schwere Fälle"}, {"text": "Schnellere Verarbeitung", "correct": false, "because": "Keine Folge"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte der Rechenschaftspflicht sind bei der Softwareplanung zu berücksichtigen?', 3, '[{"text": "Dokumentation der Verarbeitung", "correct": true, "because": "Nachweis erforderlich"}, {"text": "Technische Schutzmaßnahmen", "correct": true, "because": "Sicherheit nachweisen"}, {"text": "Datenschutz-Folgenabschätzung", "correct": true, "because": "Risiken belegen"}, {"text": "Maximale Datenspeicherung", "correct": false, "because": "Widerspricht Speicherbegrenzung"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Rechenschaftspflicht verlangt Nachweisbarkeit der DSGVO-Einhaltung. b) Sie kann ohne Dokumentation erfüllt werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nachweisbarkeit ja, Dokumentation nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Dokumentation der Verarbeitungstätigkeiten ist Teil der Rechenschaftspflicht. b) Sie gilt nur für große Unternehmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dokumentation ja, alle betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Verstöße gegen die Rechenschaftspflicht können Bußgelder nach sich ziehen. b) Technische Maßnahmen sind irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Bußgelder ja, Maßnahmen nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Datenschutz-Folgenabschätzung unterstützt die Rechenschaftspflicht. b) Sie ist nur für digitale Daten relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Folgenabschätzung ja, alle Daten betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Rechenschaftspflicht umfasst die Nachweisbarkeit technischer Maßnahmen. b) Sie erfordert keine organisatorischen Maßnahmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Technisch ja, organisatorisch auch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

