INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Datenschutz > Grundsätze (Art. 5) > Rechtmäßigkeit
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Rechtmäßigkeit gemäß Art. 5 DSGVO eine Voraussetzung für die Verarbeitung personenbezogener Daten?', 2, '[{"text": "Ja", "correct": true, "because": "Art. 5 fordert rechtmäßige, faire und transparente Verarbeitung"}, {"text": "Nein", "correct": false, "because": "Rechtmäßigkeit ist zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Verarbeitung personenbezogener Daten ohne Rechtsgrundlage rechtmäßig sein?', 2, '[{"text": "Nein", "correct": true, "because": "Eine Rechtsgrundlage nach Art. 6 DSGVO ist erforderlich"}, {"text": "Ja", "correct": false, "because": "Ohne Grundlage ist sie unrechtmäßig"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Rechtmäßigkeit der Datenverarbeitung immer durch eine Einwilligung der Betroffenen gewährleistet sein?', 2, '[{"text": "Nein", "correct": true, "because": "Andere Rechtsgrundlagen wie Vertragserfüllung sind möglich"}, {"text": "Ja", "correct": false, "because": "Einwilligung ist nur eine Option"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Verstöße gegen den Grundsatz der Rechtmäßigkeit zu Bußgeldern führen?', 2, '[{"text": "Ja", "correct": true, "because": "DSGVO sieht Sanktionen für Verstöße vor"}, {"text": "Nein", "correct": false, "because": "Bußgelder sind möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Rechtmäßigkeit nach Art. 5 DSGVO unabhängig von nationalen Datenschutzgesetzen?', 2, '[{"text": "Nein", "correct": true, "because": "Nationale Gesetze wie das BDSG ergänzen die DSGVO"}, {"text": "Ja", "correct": false, "because": "Verknüpfung besteht"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Grundsatz gemäß Art. 5 DSGVO fordert, dass die Verarbeitung rechtmäßig sein muss?', 2, '[{"text": "Rechtmäßigkeit, Fairness, Transparenz", "correct": true, "because": "Art. 5 Abs. 1a nennt diese Prinzipien"}, {"text": "Zweckbindung", "correct": false, "because": "Anderer Grundsatz"}, {"text": "Datenminimierung", "correct": false, "because": "Anderer Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rechtsgrundlage nach Art. 6 DSGVO ist am häufigsten für die rechtmäßige Verarbeitung relevant?', 3, '[{"text": "Einwilligung", "correct": true, "because": "Häufig genutzt und klar geregelt"}, {"text": "Vertragserfüllung", "correct": false, "because": "Auch wichtig, aber situational"}, {"text": "Berechtigtes Interesse", "correct": false, "because": "Abwägung erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme stellt die Rechtmäßigkeit der Datenverarbeitung sicher?', 2, '[{"text": "Dokumentation der Rechtsgrundlage", "correct": true, "because": "Nachweis der Rechtmäßigkeit"}, {"text": "Schnelle Datenverarbeitung", "correct": false, "because": "Irrelevant"}, {"text": "Hohe Serverleistung", "correct": false, "because": "Kein Datenschutzaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz droht bei fehlender Rechtmäßigkeit der Datenverarbeitung?', 2, '[{"text": "Bußgelder", "correct": true, "because": "Verstöße können sanktioniert werden"}, {"text": "Langsamere Systeme", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Geringere Nutzerfreundlichkeit", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip der Rechtmäßigkeit nach Art. 5 DSGVO wird oft missverstanden?', 2, '[{"text": "Transparenz", "correct": true, "because": "Kunden müssen über Verarbeitung informiert werden"}, {"text": "Fairness", "correct": false, "because": "Weniger missverstanden"}, {"text": "Datenintegrität", "correct": false, "because": "Anderer Grundsatz"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Rechtsgrundlagen nach Art. 6 DSGVO machen die Verarbeitung rechtmäßig?', 4, '[{"text": "Einwilligung", "correct": true, "because": "Freiwillige Zustimmung"}, {"text": "Vertragserfüllung", "correct": true, "because": "Notwendig für Verträge"}, {"text": "Gesetzliche Verpflichtung", "correct": true, "because": "Pflichten wie Steuerrecht"}, {"text": "Maximale Datenmenge", "correct": false, "because": "Kein Rechtsgrund"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anforderungen stellt Art. 5 DSGVO an die rechtmäßige Verarbeitung?', 3, '[{"text": "Rechtmäßigkeit", "correct": true, "because": "Muss gesetzeskonform sein"}, {"text": "Fairness", "correct": true, "because": "Darf Betroffene nicht täuschen"}, {"text": "Transparenz", "correct": true, "because": "Verständliche Information"}, {"text": "Hohe Geschwindigkeit", "correct": false, "because": "Kein Datenschutzkriterium"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen unterstützen die Rechtmäßigkeit nach Art. 5 DSGVO?', 4, '[{"text": "Einholung der Einwilligung", "correct": true, "because": "Rechtsgrundlage schaffen"}, {"text": "Datenschutzerklärung", "correct": true, "because": "Sorgt für Transparenz"}, {"text": "Dokumentation", "correct": true, "because": "Nachweis der Rechtmäßigkeit"}, {"text": "Software-Optimierung", "correct": false, "because": "Kein Datenschutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folgen kann ein Verstoß gegen die Rechtmäßigkeit nach Art. 5 DSGVO haben?', 3, '[{"text": "Bußgelder", "correct": true, "because": "Bis zu 20 Mio. Euro möglich"}, {"text": "Schadensersatzforderungen", "correct": true, "because": "Betroffene können klagen"}, {"text": "Verwarnungen", "correct": true, "because": "Von Aufsichtsbehörden"}, {"text": "Schnellere Verarbeitung", "correct": false, "because": "Keine Folge"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte der Rechtmäßigkeit sollten bei der Softwareplanung beachtet werden?', 3, '[{"text": "Rechtsgrundlage definieren", "correct": true, "because": "Basis für Verarbeitung"}, {"text": "Transparenz sicherstellen", "correct": true, "because": "Nutzer informieren"}, {"text": "Einwilligungsmanagement", "correct": true, "because": "Wenn nötig umsetzen"}, {"text": "Maximale Datenmenge", "correct": false, "because": "Widerspricht Datenminimierung"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Rechtmäßigkeit ist ein Grundsatz nach Art. 5 DSGVO. b) Sie erfordert immer eine Einwilligung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Rechtmäßigkeit ja, Einwilligung optional"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Transparenz ist Teil der Rechtmäßigkeit nach Art. 5. b) Verstöße führen nie zu Bußgeldern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Transparenz ja, Bußgelder möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Vertragserfüllung ist eine Rechtsgrundlage für Rechtmäßigkeit. b) Rechtmäßigkeit ist unabhängig von nationalen Gesetzen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vertrag ja, nationale Gesetze relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Dokumentation unterstützt die Rechtmäßigkeit nach Art. 5. b) Fairness ist kein Teil der Rechtmäßigkeit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dokumentation ja, Fairness Teil davon"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Einwilligung ist eine Option für rechtmäßige Verarbeitung. b) Rechtmäßigkeit erfordert keine Transparenz.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Einwilligung ja, Transparenz nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

