INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > Datenschutz > Grundsätze (Art. 5) > Richtigkeit
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Fordert der Grundsatz der Richtigkeit gemäß Art. 5 DSGVO, dass personenbezogene Daten sachlich korrekt sein müssen?', 2, '[{"text": "Ja", "correct": true, "because": "Art. 5 Abs. 1d verlangt sachliche Richtigkeit"}, {"text": "Nein", "correct": false, "because": "Richtigkeit ist zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Verarbeitung unrichtiger personenbezogener Daten rechtmäßig sein?', 2, '[{"text": "Nein", "correct": true, "because": "Unrichtige Daten verstoßen gegen Art. 5"}, {"text": "Ja", "correct": false, "because": "Richtigkeit ist Voraussetzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen Unternehmen laut Art. 5 DSGVO unrichtige Daten automatisch korrigieren?', 2, '[{"text": "Ja", "correct": true, "because": "Korrektur oder Löschung ist vorgeschrieben"}, {"text": "Nein", "correct": false, "because": "Pflicht zur Korrektur besteht"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Betroffene aufgrund des Grundsatzes der Richtigkeit die Korrektur ihrer Daten verlangen?', 2, '[{"text": "Ja", "correct": true, "because": "Art. 16 DSGVO gewährt das Berichtigungsrecht"}, {"text": "Nein", "correct": false, "because": "Recht ist gesetzlich verankert"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Richtigkeit nach Art. 5 DSGVO nur für personenbezogene Daten relevant?', 2, '[{"text": "Ja", "correct": true, "because": "Art. 5 gilt für personenbezogene Daten"}, {"text": "Nein", "correct": false, "because": "Kein Bezug zu anderen Daten"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Was bedeutet der Grundsatz der Richtigkeit gemäß Art. 5 DSGVO?', 2, '[{"text": "Daten müssen sachlich korrekt und aktuell sein", "correct": true, "because": "Art. 5 Abs. 1d definiert dies"}, {"text": "Daten dürfen beliebig sein", "correct": false, "because": "Widerspricht DSGVO"}, {"text": "Daten müssen maximal gesammelt werden", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme stellt die Richtigkeit personenbezogener Daten am effektivsten sicher?', 3, '[{"text": "Regelmäßige Aktualisierung", "correct": true, "because": "Hält Daten auf dem neuesten Stand"}, {"text": "Maximale Datenerhebung", "correct": false, "because": "Widerspricht Minimierung"}, {"text": "Automatische Speicherung", "correct": false, "because": "Kein Fokus auf Richtigkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Recht unterstützt den Grundsatz der Richtigkeit?', 2, '[{"text": "Recht auf Berichtigung", "correct": true, "because": "Art. 16 DSGVO erlaubt Korrektur"}, {"text": "Recht auf Auskunft", "correct": false, "because": "Anderer Zweck"}, {"text": "Recht auf Datenportabilität", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenz droht bei Verstoß gegen den Grundsatz der Richtigkeit?', 2, '[{"text": "Bußgelder", "correct": true, "because": "Verstoß gegen Art. 5 strafbar"}, {"text": "Systemausfall", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Geringere Nutzerfreundlichkeit", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Richtigkeit ist für die Softwareplanung am relevantesten?', 2, '[{"text": "Datenaktualität sicherstellen", "correct": true, "because": "Gewährleistet korrekte Verarbeitung"}, {"text": "Hohe Datenmenge", "correct": false, "because": "Widerspricht Minimierung"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Irrelevant"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Anforderungen stellt der Grundsatz der Richtigkeit nach Art. 5 DSGVO?', 4, '[{"text": "Sachliche Korrektheit", "correct": true, "because": "Daten müssen richtig sein"}, {"text": "Aktualität", "correct": true, "because": "Daten müssen auf dem neuesten Stand sein"}, {"text": "Korrekturmöglichkeit", "correct": true, "because": "Unrichtige Daten müssen berichtigt werden"}, {"text": "Maximale Speicherung", "correct": false, "because": "Widerspricht Speicherbegrenzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen unterstützen die Einhaltung des Grundsatzes der Richtigkeit?', 3, '[{"text": "Regelmäßige Datenprüfung", "correct": true, "because": "Stellt Korrektheit sicher"}, {"text": "Betroffenenrechte umsetzen", "correct": true, "because": "Ermöglicht Korrektur"}, {"text": "Datenaktualisierung", "correct": true, "because": "Hält Daten aktuell"}, {"text": "Unkontrollierte Datensammlung", "correct": false, "because": "Verstoß gegen Minimierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Beispiele zeigen einen Verstoß gegen den Grundsatz der Richtigkeit?', 4, '[{"text": "Speicherung veralteter Adressen", "correct": true, "because": "Nicht aktuell"}, {"text": "Falsche Namensangaben", "correct": true, "because": "Sachlich unrichtig"}, {"text": "Ignorieren von Korrekturanfragen", "correct": true, "because": "Verletzt Betroffenenrechte"}, {"text": "Aktuelle Vertragsdaten", "correct": false, "because": "Richtig und aktuell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Folgen kann ein Verstoß gegen den Grundsatz der Richtigkeit haben?', 3, '[{"text": "Bußgelder", "correct": true, "because": "Verstoß gegen Art. 5 strafbar"}, {"text": "Schadensersatzansprüche", "correct": true, "because": "Betroffene können klagen"}, {"text": "Reputationsverlust", "correct": true, "because": "Vertrauen schwindet"}, {"text": "Schnellere Datenverarbeitung", "correct": false, "because": "Keine Folge"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte der Richtigkeit sollten bei der Softwareplanung berücksichtigt werden?', 3, '[{"text": "Datenvalidierung", "correct": true, "because": "Sichert Korrektheit"}, {"text": "Aktualisierungsmechanismen", "correct": true, "because": "Hält Daten aktuell"}, {"text": "Betroffenenrechte umsetzen", "correct": true, "because": "Korrektur ermöglichen"}, {"text": "Maximale Datenerhebung", "correct": false, "because": "Widerspricht Minimierung"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Richtigkeit nach Art. 5 DSGVO verlangt aktuelle Daten. b) Unrichtige Daten sind immer rechtmäßig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Aktualität ja, Unrichtigkeit nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Betroffene können laut DSGVO die Korrektur ihrer Daten verlangen. b) Unternehmen müssen unrichtige Daten nicht korrigieren.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Korrekturrecht ja, Korrekturpflicht nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Datenvalidierung unterstützt die Richtigkeit nach Art. 5. b) Richtigkeit gilt nur für digitale Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Validierung ja, alle Daten betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Ein Verstoß gegen die Richtigkeit kann Bußgelder nach sich ziehen. b) Richtigkeit ist für nicht-personenbezogene Daten relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Bußgelder ja, nur personenbezogene Daten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Regelmäßige Datenprüfung fördert die Richtigkeit. b) Unrichtige Daten müssen automatisch gelöscht werden.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Prüfung ja, Korrektur oder Löschung möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

