INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann E-Mail im Anwendersupport für die Dokumentation von Problemen genutzt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Schriftlich und nachvollziehbar"}, {"text": "Nein", "correct": false, "because": "E-Mail ist dafür geeignet"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Chat im Anwendersupport schneller als E-Mail für einfache Rückfragen?', 2, '[{"text": "Ja", "correct": true, "because": "Echtzeitkommunikation"}, {"text": "Nein", "correct": false, "because": "Chat ist direkter"}]'),
('00000000-0000-0000-0000-000000000000', 'Erfordert Telefon im Anwendersupport eine Internetverbindung?', 2, '[{"text": "Nein", "correct": true, "because": "Funktioniert über Telefonleitung"}, {"text": "Ja", "correct": false, "because": "Internet nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann E-Mail im Anwendersupport Anhänge wie Screenshots enthalten?', 2, '[{"text": "Ja", "correct": true, "because": "Anhänge sind möglich"}, {"text": "Nein", "correct": false, "because": "E-Mail unterstützt das"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Telefon im Anwendersupport für komplexe Problembeschreibungen weniger geeignet?', 2, '[{"text": "Ja", "correct": true, "because": "Schriftlich oft klarer"}, {"text": "Nein", "correct": false, "because": "Komplexität kann schwierig sein"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Kommunikationsmittel im Anwendersupport ist am besten für schriftliche Nachverfolgbarkeit?', 2, '[{"text": "E-Mail", "correct": true, "because": "Dokumentation möglich"}, {"text": "Chat", "correct": false, "because": "Weniger formell"}, {"text": "Telefon", "correct": false, "because": "Nicht schriftlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Mittel der digitalen Kommunikation ermöglicht die schnellste Rückmeldung?', 3, '[{"text": "Chat", "correct": true, "because": "Echtzeit-Antwort"}, {"text": "E-Mail", "correct": false, "because": "Verzögerung möglich"}, {"text": "Telefon", "correct": false, "because": "Wartezeit möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kommunikationsmittel im Anwendersupport eignet sich am besten für mündliche Erklärungen?', 2, '[{"text": "Telefon", "correct": true, "because": "Direkte Sprachkommunikation"}, {"text": "E-Mail", "correct": false, "because": "Schriftlich"}, {"text": "Chat", "correct": false, "because": "Textbasiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einschränkung hat E-Mail im Anwendersupport?', 2, '[{"text": "Verzögerte Antwort", "correct": true, "because": "Keine Echtzeit"}, {"text": "Keine Anhänge", "correct": false, "because": "Anhänge möglich"}, {"text": "Kein Ton", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kommunikationsmittel im Anwendersupport wird für dringende Anliegen bevorzugt?', 2, '[{"text": "Telefon", "correct": true, "because": "Sofortiger Kontakt"}, {"text": "E-Mail", "correct": false, "because": "Langsamer"}, {"text": "Chat", "correct": false, "because": "Abhängig von Verfügbarkeit"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Kommunikationsmittel werden im Anwendersupport genutzt?', 3, '[{"text": "E-Mail", "correct": true, "because": "Schriftliche Kommunikation"}, {"text": "Chat", "correct": true, "because": "Echtzeit-Text"}, {"text": "Telefon", "correct": true, "because": "Mündliche Kommunikation"}, {"text": "Fernwartung", "correct": false, "because": "Support-Tool"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet E-Mail im Anwendersupport?', 4, '[{"text": "Dokumentation", "correct": true, "because": "Nachverfolgbarkeit"}, {"text": "Anhänge möglich", "correct": true, "because": "Zusatzinformationen"}, {"text": "Asynchrone Kommunikation", "correct": true, "because": "Zeitunabhängig"}, {"text": "Sofortige Antwort", "correct": false, "because": "Verzögerung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen Chat im Anwendersupport nützlich?', 3, '[{"text": "Schnelle Antwort", "correct": true, "because": "Echtzeit"}, {"text": "Textbasiert", "correct": true, "because": "Schriftlich"}, {"text": "Multitasking möglich", "correct": true, "because": "Mehrere Chats"}, {"text": "Mündliche Erklärung", "correct": false, "because": "Nicht möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile haben Telefonate im Anwendersupport?', 4, '[{"text": "Keine Dokumentation", "correct": true, "because": "Nicht automatisch schriftlich"}, {"text": "Wartezeiten möglich", "correct": true, "because": "Abhängig von Verfügbarkeit"}, {"text": "Missverständnisse", "correct": true, "because": "Mündlich schwieriger"}, {"text": "Keine Internetverbindung", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungsfälle gibt es für digitale Kommunikation im Anwendersupport?', 3, '[{"text": "Problemberichte per E-Mail", "correct": true, "because": "Detaillierte Beschreibung"}, {"text": "Schnelle Rückfragen per Chat", "correct": true, "because": "Echtzeit"}, {"text": "Dringende Anliegen per Telefon", "correct": true, "because": "Direkter Kontakt"}, {"text": "Hardware-Reparatur", "correct": false, "because": "Physische Aufgabe"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) E-Mail ist für komplexe Problembeschreibungen geeignet. b) Chat ist immer langsamer als Telefon.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "E-Mail ja, Chat oft schneller"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Telefon ermöglicht direkte Kommunikation. b) E-Mail ist für dringende Anliegen die beste Wahl.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Telefon ja, E-Mail langsamer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Chat ist ein textbasiertes Kommunikationsmittel. b) Telefon bietet automatische Dokumentation.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Chat ja, Telefon nicht automatisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) E-Mail unterstützt Dateianhänge. b) Chat ist für langfristige Kommunikation gedacht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Anhänge ja, Chat kurzfristig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Telefon ist für dringende Fälle geeignet. b) E-Mail ist schneller als Chat für einfache Fragen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Telefon ja, Chat schneller"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

