-- Ransomware.sql (Malware zur Datenverschlüsselung und Erpressung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass ein verschlüsseltes System immer durch Zahlung wiederhergestellt wird?', 2, '[{"text": "Nein", "correct": true, "because": "Keine Garantie für Entschlüsselung"}, {"text": "Ja", "correct": false, "because": "Angreifer können Schlüssel vorenthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode ist primär, um ein Netzwerk vor Erpressungssoftware zu schützen?', 3, '[{"text": "Regelmäßige Backups", "correct": true, "because": "Ermöglicht Wiederherstellung ohne Zahlung"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Schnelle CPUs", "correct": false, "because": "Irrelevant für Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen helfen, einen Angriff zu verhindern?', 5, '[{"text": "Patch-Management", "correct": true, "because": "Schließt Sicherheitslücken"}, {"text": "Mitarbeiterschulung", "correct": true, "because": "Reduziert Phishing-Risiko"}, {"text": "Farbcodierte Kabel", "correct": false, "because": "Kein Sicherheitsvorteil"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Kein Schutzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Phishing ist ein häufiger Einstieg für Erpressungssoftware. b) Alle Angriffe nutzen Zero-Day-Lücken.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, bekannte Lücken oft genutzt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht universell"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Abwehr von Datenverschlüsselungsangriffen?', 4, '[{"text": "Antivirus-Software", "correct": false, "because": "Erkennt viele Bedrohungen"}, {"text": "Netzwerksegmentierung", "correct": false, "because": "Begrenzt Verbreitung"}, {"text": "Betriebssystemfarbe", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Angriff immer Daten löscht?', 2, '[{"text": "Nein", "correct": true, "because": "Ziel ist Verschlüsselung, nicht Löschung"}, {"text": "Ja", "correct": false, "because": "Löschung ist selten das Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Verfahren erkennt verdächtige Aktivitäten frühzeitig?', 4, '[{"text": "Verhaltensanalyse", "correct": true, "because": "Erkennt Anomalien im System"}, {"text": "Manuelle Log-Prüfung", "correct": false, "because": "Zu langsam"}, {"text": "Höhere Bandbreite", "correct": false, "because": "Kein Erkennungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Backups allein vor Erpressung schützen. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Kombination mit anderen Maßnahmen nötig"}, {"text": "Ja", "correct": false, "because": "Backups lösen nicht alle Risiken"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist jede Antivirensoftware gegen solche Angriffe wirksam?', 2, '[{"text": "Nein", "correct": true, "because": "Neue Varianten oft unerkannt"}, {"text": "Ja", "correct": false, "because": "Begrenzte Wirksamkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren erhöhen das Risiko eines Angriffs?', 5, '[{"text": "Ungepatchte Systeme", "correct": true, "because": "Bieten Einfallstore"}, {"text": "Schwache Passwörter", "correct": true, "because": "Erleichtern Zugriff"}, {"text": "Schnelle Internetverbindung", "correct": false, "because": "Kein Risikofaktor"}, {"text": "Hoher Speicherplatz", "correct": false, "because": "Irrelevant für Angriffe"}]'),
('00000000-0000-0000-0000-000000000000', 'Was würdest du bei der Reaktion auf einen Angriff priorisieren?', 4, '[{"text": "Systemisolierung", "correct": true, "because": "Begrenzt Schadensausbreitung"}, {"text": "Sofortige Zahlung", "correct": false, "because": "Keine Garantie für Wiederherstellung"}, {"text": "Neustart aller Geräte", "correct": false, "because": "Kann Datenverlust erhöhen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) RaaS ermöglicht Angriffe durch Amateure. b) Alle Angriffe stehlen Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, nicht immer Datenexfiltration"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht universell"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um ein System vor Erpressung zu schützen?', 3, '[{"text": "Firewalls", "correct": false, "because": "Blockieren unerlaubten Zugriff"}, {"text": "MFA", "correct": false, "because": "Erschwert unbefugten Zugang"}, {"text": "Bildschirmhintergrund", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich bei einem Angriff vorgehen würde?', 4, '[{"text": "Infizierte Systeme isolieren", "correct": true, "because": "Verhindert weitere Verbreitung"}, {"text": "Alle Passwörter ändern", "correct": false, "because": "Riskant während des Angriffs"}, {"text": "Zahlung vorbereiten", "correct": false, "because": "Nicht primäre Maßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Angriff nur über E-Mails erfolgt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch andere Vektoren wie Schwachstellen"}, {"text": "Ja", "correct": false, "because": "E-Mails nur ein Weg"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip hilft, die Auswirkungen eines Angriffs zu minimieren?', 3, '[{"text": "Least Privilege", "correct": true, "because": "Beschränkt Zugriffsrechte"}, {"text": "Maximale Offenheit", "correct": false, "because": "Erhöht Risiken"}, {"text": "Hohe Komplexität", "correct": false, "because": "Keine Schutzmaßnahme"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht die Zahlung eines Lösegeldes die Sicherheit?', 2, '[{"text": "Nein", "correct": true, "because": "Kann weitere Angriffe fördern"}, {"text": "Ja", "correct": false, "because": "Keine Garantie für Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien helfen, einen Angriff zu erkennen?', 5, '[{"text": "IDS/IPS", "correct": true, "because": "Erkennt und blockiert Bedrohungen"}, {"text": "SIEM-Systeme", "correct": true, "because": "Analysiert Sicherheitsereignisse"}, {"text": "Grafikkarten", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Cloud-Speicher", "correct": false, "because": "Nur für Datenhaltung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Planung einer Abwehrstrategie unwichtig?', 3, '[{"text": "Regelmäßige Updates", "correct": false, "because": "Schließen Sicherheitslücken"}, {"text": "Notfallwiederherstellung", "correct": false, "because": "Sichert Betriebsfähigkeit"}, {"text": "Betriebssystemsprache", "correct": true, "because": "Kein Einfluss auf Sicherheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ein System kompromittiert wurde?', 4, '[{"text": "Backups wiederherstellen", "correct": true, "because": "Stellt Daten ohne Zahlung zurück"}, {"text": "Alle Geräte neu starten", "correct": false, "because": "Kann Datenverlust erhöhen"}, {"text": "Angreifer kontaktieren", "correct": false, "because": "Keine empfohlene Maßnahme"}]');

