-- Rechtsformen.sql (Unternehmensstrukturen mit rechtlichen und steuerlichen Folgen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass ich als Einzelunternehmer immer persönlich hafte?', 2, '[{"text": "Ja", "correct": true, "because": "Unbeschränkte Haftung mit Privatvermögen"}, {"text": "Nein", "correct": false, "because": "Persönliche Haftung ist Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Unternehmensform eignet sich für ein kleines Start-up ohne hohes Kapital?', 3, '[{"text": "UG", "correct": true, "because": "Geringe Kapitalanforderung"}, {"text": "AG", "correct": false, "because": "Hoher Kapitalbedarf"}, {"text": "OHG", "correct": false, "because": "Persönliche Haftung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale machen eine GmbH attraktiv?', 5, '[{"text": "Haftungsbeschränkung", "correct": true, "because": "Schützt Privatvermögen"}, {"text": "Flexibles Stammkapital", "correct": true, "because": "Anpassbar an Bedarf"}, {"text": "Unbeschränkte Haftung", "correct": false, "because": "Gegenteil ist wahr"}, {"text": "Keine Buchführung", "correct": false, "because": "Buchführungspflicht besteht"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine GbR braucht keinen Gesellschaftsvertrag. b) Sie hat eine eigene Rechtspersönlichkeit.', 3, '[{"text": "Beides falsch", "correct": true, "because": "GbR braucht Vertrag, keine Rechtspersönlichkeit"}, {"text": "Beides stimmt", "correct": false, "because": "Beide sind falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl einer Unternehmensform für ein Ein-Personen-Projekt?', 4, '[{"text": "Haftungsrisiken", "correct": false, "because": "Entscheidend für Schutz"}, {"text": "Steuerliche Auswirkungen", "correct": false, "because": "Beeinflusst Gewinn"}, {"text": "Anzahl der Gesellschafter", "correct": true, "because": "Irrelevant bei Einzelprojekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine AG immer börsennotiert sein muss?', 2, '[{"text": "Nein", "correct": true, "because": "Börsennotierung ist optional"}, {"text": "Ja", "correct": false, "because": "AG kann privat sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Struktur ist für ein Unternehmen mit vielen Investoren geeignet?', 4, '[{"text": "AG", "correct": true, "because": "Ermöglicht Aktienausgabe"}, {"text": "Einzelunternehmen", "correct": false, "because": "Keine Investorenstruktur"}, {"text": "GbR", "correct": false, "because": "Eingeschränkte Skalierbarkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine OHG keine Buchführungspflicht hat. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "OHG ist buchführungspflichtig"}, {"text": "Ja", "correct": false, "because": "Gesetzliche Pflicht besteht"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist eine UG nur für Start-ups gedacht?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für andere Zwecke geeignet"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren erhöhen die Haftung in einem Unternehmen?', 5, '[{"text": "Persönliche Bürgschaften", "correct": true, "because": "Privatvermögen gefährdet"}, {"text": "Gesellschafterstatus", "correct": true, "because": "In Personengesellschaften"}, {"text": "Hoher Umsatz", "correct": false, "because": "Kein Haftungsfaktor"}, {"text": "Firmenstandort", "correct": false, "because": "Irrelevant für Haftung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was würdest du bei der Gründung eines kleinen IT-Dienstleisters priorisieren?', 4, '[{"text": "Haftungsbeschränkung", "correct": true, "because": "Schützt vor Risiken"}, {"text": "Schnelle Gründung", "correct": false, "because": "Rechtssicherheit wichtiger"}, {"text": "Hohes Stammkapital", "correct": false, "because": "Oft nicht nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine GmbH hat eine Mindestkapitalanforderung. b) Sie ist steuerlich wie eine GbR behandelt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, eigene Besteuerung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Wahl einer Unternehmensform?', 3, '[{"text": "Haftungsregeln", "correct": false, "because": "Kern der Entscheidung"}, {"text": "Steuerliche Folgen", "correct": false, "because": "Beeinflusst Gewinn"}, {"text": "Firmenlogo", "correct": true, "because": "Kein rechtlicher Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich eine GbR gründe?', 4, '[{"text": "Gesellschaftsvertrag abschließen", "correct": true, "because": "Legt Regeln fest"}, {"text": "Mindestkapital einzahlen", "correct": false, "because": "Nicht erforderlich"}, {"text": "Vorstand wählen", "correct": false, "because": "Nicht nötig bei GbR"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine GmbH immer teuer zu gründen ist. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "UG als Alternative günstiger"}, {"text": "Ja", "correct": false, "because": "Kosten variieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip hilft, Haftungsrisiken zu minimieren?', 4, '[{"text": "Kapitalgesellschaft wählen", "correct": true, "because": "Beschränkt Haftung"}, {"text": "Hohe Verschuldung", "correct": false, "because": "Erhöht Risiken"}, {"text": "Einzelentscheidungen", "correct": false, "because": "Kein Haftungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss eine OHG ins Handelsregister?', 2, '[{"text": "Ja", "correct": true, "because": "Pflicht für Kaufleute"}, {"text": "Nein", "correct": false, "because": "Eintragung gesetzlich vorgeschrieben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine UG für Gründer?', 5, '[{"text": "Geringes Stammkapital", "correct": true, "because": "Ermöglicht einfache Gründung"}, {"text": "Haftungsbeschränkung", "correct": true, "because": "Schützt Privatvermögen"}, {"text": "Keine Buchführung", "correct": false, "because": "Buchführungspflicht besteht"}, {"text": "Börsennotierung", "correct": false, "because": "Nicht für UG relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Unternehmenswahl unwichtig?', 3, '[{"text": "Gründungskosten", "correct": false, "because": "Beeinflusst Budget"}, {"text": "Haftungsstruktur", "correct": false, "because": "Schützt Vermögen"}, {"text": "Firmenfarben", "correct": true, "because": "Kein rechtlicher Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich mit Partnern ein Unternehmen gründe?', 4, '[{"text": "KG wählen für flexible Haftung", "correct": true, "because": "Kombiniert Haftungsarten"}, {"text": "Einzelunternehmen gründen", "correct": false, "because": "Keine Partnerstruktur"}, {"text": "Keine Verträge schließen", "correct": false, "because": "Vertrag ist nötig"}]');

