-- Referenzielle Integrität.sql (Sicherstellung konsistenter Beziehungen in Datenbanken)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass eine Datenbank ohne Fremdschlüssel immer konsistent ist?', 2, '[{"text": "Nein", "correct": true, "because": "Fremdschlüssel sichern Beziehungen"}, {"text": "Ja", "correct": false, "because": "Ohne Kontrolle drohen Inkonsistenzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Mittel nutze ich, um Beziehungen zwischen Tabellen zu sichern?', 3, '[{"text": "Fremdschlüssel", "correct": true, "because": "Verknüpft Tabellen konsistent"}, {"text": "Index", "correct": false, "because": "Nur für Suchleistung"}, {"text": "Trigger", "correct": false, "because": "Für Aktionen, nicht Beziehungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Mechanismen helfen, Datenkonsistenz zu wahren?', 5, '[{"text": "Fremdschlüssel-Constraints", "correct": true, "because": "Sichern referenzielle Beziehungen"}, {"text": "Kaskadierende Löschungen", "correct": true, "because": "Vermeiden verwaiste Einträge"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Kein Konsistenzfaktor"}, {"text": "Schnelle CPU", "correct": false, "because": "Kein Einfluss auf Beziehungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Fremdschlüssel verhindern ungültige Verweise. b) Sie erhöhen immer die Abfragegeschwindigkeit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, kann Leistung beeinträchtigen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Gestaltung einer konsistenten Datenbank?', 4, '[{"text": "Fremdschlüssel-Definitionen", "correct": false, "because": "Zentral für Konsistenz"}, {"text": "Referenzielle Constraints", "correct": false, "because": "Sichern Beziehungen"}, {"text": "Tabellenfarben", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Fremdschlüssel immer einen Primärschlüssel referenzieren muss?', 2, '[{"text": "Ja", "correct": true, "because": "Sichert eindeutige Verweise"}, {"text": "Nein", "correct": false, "because": "Primär- oder Unique-Schlüssel nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aktion verhindert verwaiste Datensätze beim Löschen?', 4, '[{"text": "ON DELETE CASCADE", "correct": true, "because": "Löscht abhängige Einträge"}, {"text": "ON DELETE IGNORE", "correct": false, "because": "Gibt’s nicht"}, {"text": "ON DELETE NULLIFY", "correct": false, "because": "Kein Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Constraints die Datenbank immer verlangsamen. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Konsistenz wichtiger, Leistung optimierbar"}, {"text": "Ja", "correct": false, "because": "Abhängig von Design"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Fremdschlüssel auch ein Primärschlüssel?', 2, '[{"text": "Nein", "correct": true, "because": "Fremdschlüssel verweist, Primärschlüssel identifiziert"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Funktionen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Optionen sichern die Konsistenz bei Datenänderungen?', 5, '[{"text": "ON UPDATE CASCADE", "correct": true, "because": "Passt abhängige Einträge an"}, {"text": "ON DELETE RESTRICT", "correct": true, "because": "Verhindert ungültige Löschungen"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Kein Konsistenzfaktor"}, {"text": "Manuelle Prüfung", "correct": false, "because": "Fehleranfällig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Gestaltung einer relationalen Datenbank?', 4, '[{"text": "Konsistente Beziehungen", "correct": true, "because": "Sichert Datenintegrität"}, {"text": "Maximale Tabellengröße", "correct": false, "because": "Sekundär"}, {"text": "Schnelle Erstellung", "correct": false, "because": "Qualität wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) ON DELETE SET NULL setzt Fremdschlüssel auf NULL. b) Es entfernt die gesamte Zeile.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Zeile bleibt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Datenkonsistenz zu sichern?', 3, '[{"text": "Fremdschlüssel", "correct": false, "because": "Kern der Konsistenz"}, {"text": "Constraints", "correct": false, "because": "Erzwingen Regeln"}, {"text": "Datenbankfarben", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich verwaiste Datensätze verhindere?', 4, '[{"text": "Kaskadierende Constraints nutzen", "correct": true, "because": "Automatische Anpassung"}, {"text": "Manuelle Prüfung", "correct": false, "because": "Fehleranfällig"}, {"text": "Keine Fremdschlüssel", "correct": false, "because": "Erhöht Risiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Fremdschlüssel nur für relationale Datenbanken gelten. Stimmt das?', 2, '[{"text": "Ja", "correct": true, "because": "Typisch für relationale Modelle"}, {"text": "Nein", "correct": false, "because": "Selten in NoSQL"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Verfahren hilft, ungültige Datenänderungen zu blockieren?', 3, '[{"text": "ON UPDATE RESTRICT", "correct": true, "because": "Verhindert ungültige Updates"}, {"text": "ON UPDATE IGNORE", "correct": false, "because": "Gibt’s nicht"}, {"text": "ON UPDATE DELETE", "correct": false, "because": "Kein Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ich Fremdschlüssel ohne Constraints definieren?', 2, '[{"text": "Nein", "correct": true, "because": "Constraints erzwingen Regeln"}, {"text": "Ja", "correct": false, "because": "Ohne Constraints wirkungslos"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind für konsistente Datenbanken wichtig?', 5, '[{"text": "Primärschlüssel", "correct": true, "because": "Eindeutige Identifikation"}, {"text": "Fremdschlüssel", "correct": true, "because": "Sichern Beziehungen"}, {"text": "Tabellenlayout", "correct": false, "because": "Nur visuelle Ordnung"}, {"text": "Datenbankgröße", "correct": false, "because": "Kein Konsistenzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Datenbankwartung unwichtig?', 3, '[{"text": "Constraint-Überprüfung", "correct": false, "because": "Sichert Konsistenz"}, {"text": "Backup-Strategie", "correct": false, "because": "Schützt Daten"}, {"text": "Benutzeroberfläche", "correct": true, "because": "Kein Konsistenzfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ich eine Tabelle ohne verwaiste Einträge löschen will?', 4, '[{"text": "ON DELETE CASCADE einrichten", "correct": true, "because": "Löscht abhängige Daten"}, {"text": "Manuell prüfen", "correct": false, "because": "Fehleranfällig"}, {"text": "Constraints deaktivieren", "correct": false, "because": "Risiko für Inkonsistenz"}]');

