-- Repeater.sql (Gerät zur Erweiterung der WLAN-Reichweite durch Signalweiterleitung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist es wahr, dass ein Gerät zur Signalverstärkung die Bandbreite immer halbiert?', 2, '[{"text": "Nein", "correct": true, "because": "Dual-Band-Modelle verhindern das"}, {"text": "Ja", "correct": false, "because": "Nicht bei allen Geräten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion erfüllt ein WLAN-Verstärker primär?', 3, '[{"text": "Signalreichweite erweitern", "correct": true, "because": "Verstärkt und verteilt Signal"}, {"text": "Datenrate erhöhen", "correct": false, "because": "Nicht primär"}, {"text": "Firewall einrichten", "correct": false, "because": "Keine Sicherheitsfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen ein Gerät effektiv?', 5, '[{"text": "Dual-Band-Unterstützung", "correct": true, "because": "Nutzt zwei Frequenzen"}, {"text": "WPS-Funktion", "correct": true, "because": "Vereinfacht Einrichtung"}, {"text": "Hohe Farbtiefe", "correct": false, "because": "Irrelevant für Netzwerk"}, {"text": "Großer Speicher", "correct": false, "because": "Nicht primär nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Verstärker kann Mesh-Netzwerke unterstützen. b) Er verdoppelt immer die Bandbreite.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Bandbreite oft halbiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Platzierung eines Signalverstärkers?', 4, '[{"text": "Signalstärke des Routers", "correct": false, "because": "Entscheidend für Reichweite"}, {"text": "Wandmaterial", "correct": false, "because": "Beeinflusst Signal"}, {"text": "Gerätefarbe", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Verstärker immer eine Kabelverbindung braucht?', 2, '[{"text": "Nein", "correct": true, "because": "Verbindet drahtlos"}, {"text": "Ja", "correct": false, "because": "Kabellos möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Einstellung vereinfacht die Einrichtung eines Verstärkers?', 3, '[{"text": "WPS", "correct": true, "because": "Automatische Verbindung"}, {"text": "Manuelle IP", "correct": false, "because": "Komplexer"}, {"text": "Bluetooth", "correct": false, "because": "Nicht für WLAN"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Signalverstärker immer die Geschwindigkeit halbiert. Stimmt das?', 3, '[{"text": "Nein", "correct": true, "because": "Dual-Band oder Mesh verhindern das"}, {"text": "Ja", "correct": false, "because": "Abhängig von Modell"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Verstärker dasselbe wie ein Access Point?', 2, '[{"text": "Nein", "correct": true, "because": "Access Point nutzt Kabel"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Technik"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Leistung eines Verstärkers?', 5, '[{"text": "Platzierung", "correct": true, "because": "Signalstärke entscheidend"}, {"text": "Frequenzband", "correct": true, "because": "2.4/5 GHz beeinflusst Reichweite"}, {"text": "Gehäusefarbe", "correct": false, "because": "Keine Funktion"}, {"text": "Betriebssystem", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was würdest du bei der Einrichtung eines Signalverstärkers priorisieren?', 4, '[{"text": "Optimale Position", "correct": true, "because": "Maximiert Reichweite"}, {"text": "Schnelle Installation", "correct": false, "because": "Position wichtiger"}, {"text": "Design", "correct": false, "because": "Funktion zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Verstärker unterstützt WPA3. b) Er braucht immer ein eigenes Netzwerk.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, nutzt oft Router-Netzwerk"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für die Installation eines Verstärkers?', 3, '[{"text": "Router-Signal", "correct": false, "because": "Notwendig für Verbindung"}, {"text": "Stromquelle", "correct": false, "because": "Gerät braucht Strom"}, {"text": "Firmenlogo", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, wie ich die Reichweite eines Verstärkers maximiere?', 4, '[{"text": "Zwischen Router und Ziel platzieren", "correct": true, "because": "Optimale Signalstärke"}, {"text": "Neben Router stellen", "correct": false, "because": "Zu nah, kein Effekt"}, {"text": "In Keller setzen", "correct": false, "because": "Schwächt Signal"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Verstärker immer mit jedem Router kompatibel sind. Stimmt das?', 2, '[{"text": "Ja", "correct": true, "because": "Meist universell kompatibel"}, {"text": "Nein", "correct": false, "because": "Standards wie 802.11 sichern Kompatibilität"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll nutzt ein Verstärker typischerweise?', 3, '[{"text": "802.11", "correct": true, "because": "WLAN-Standard"}, {"text": "FTP", "correct": false, "because": "Dateiübertragung"}, {"text": "HTTP", "correct": false, "because": "Webprotokoll"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht ein Verstärker die Datenrate?', 2, '[{"text": "Nein", "correct": true, "because": "Erweitert Reichweite, nicht Geschwindigkeit"}, {"text": "Ja", "correct": false, "because": "Geschwindigkeit bleibt gleich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Dual-Band-Verstärker?', 5, '[{"text": "Bessere Geschwindigkeit", "correct": true, "because": "Nutzt 2.4 und 5 GHz"}, {"text": "Weniger Interferenz", "correct": true, "because": "Frequenzwechsel möglich"}, {"text": "Kleinere Größe", "correct": false, "because": "Nicht relevant"}, {"text": "Bessere Optik", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Wahl eines Verstärkers unwichtig?', 3, '[{"text": "WLAN-Standard", "correct": false, "because": "Beeinflusst Kompatibilität"}, {"text": "Reichweite", "correct": false, "because": "Entscheidend für Nutzen"}, {"text": "Verpackungsdesign", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie gehe ich vor, wenn ein Verstärker keine Verbindung herstellt?', 4, '[{"text": "WPS neu starten oder manuell konfigurieren", "correct": true, "because": "Löst Verbindungsprobleme"}, {"text": "Router ausschalten", "correct": false, "because": "Unnötig"}, {"text": "Farbe ändern", "correct": false, "because": "Irrelevant"}]');

