-- Wiederherstellung.sql
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist eine Wiederherstellung immer vollständig möglich?', 2, '[{"text": "Nein", "correct": true, "because": "Hängt von Backup-Qualität ab"}, {"text": "Ja", "correct": false, "because": "Nicht garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Wiederherstellung?', 3, '[{"text": "Datenintegrität", "correct": true, "because": "Sichert Nutzbarkeit"}, {"text": "Schnelligkeit", "correct": false, "because": "Qualität wichtiger"}, {"text": "Minimale Kosten", "correct": false, "because": "Zuverlässigkeit zählt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sind für eine erfolgreiche Wiederherstellung nötig?', 5, '[{"text": "Aktuelle Backups", "correct": true, "because": "Minimieren Datenverlust"}, {"text": "Testläufe", "correct": true, "because": "Sichern Prozess"}, {"text": "Schnelle Hardware", "correct": false, "because": "Sekundär"}, {"text": "Manuelle Eingriffe", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Wiederherstellung braucht Backups. b) Sie funktioniert ohne Tests.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tests sind essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wiederherstellung?', 4, '[{"text": "Backup-Integrität", "correct": false, "because": "Sichert Erfolg"}, {"text": "Wiederherstellungsplan", "correct": false, "because": "Strukturiert Vorgehen"}, {"text": "Oberflächen-Design", "correct": true, "because": "Kein funktionaler Nutzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Wiederherstellung auch teilweise sein kann?', 2, '[{"text": "Ja", "correct": true, "because": "Point-in-Time möglich"}, {"text": "Nein", "correct": false, "because": "Nicht nur vollständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wähle ich für eine schnelle Wiederherstellung?', 3, '[{"text": "Inkrementelles Backup", "correct": true, "because": "Weniger Daten zu laden"}, {"text": "Manuelle Kopie", "correct": false, "because": "Zeitaufwendig"}, {"text": "Cloud-Upload", "correct": false, "because": "Netzwerkabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen eine Wiederherstellung zuverlässig?', 5, '[{"text": "Regelmäßige Tests", "correct": true, "because": "Sichern Funktion"}, {"text": "Redundante Backups", "correct": true, "because": "Mehrere Optionen"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nur Geschwindigkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Wiederherstellung braucht Planung. b) Sie ist immer sofort möglich. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vorbereitung nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine Wiederherstellung?', 4, '[{"text": "Backup-Dateien", "correct": false, "because": "Grundlage"}, {"text": "Testprotokolle", "correct": false, "because": "Sichern Erfolg"}, {"text": "Spiele-Software", "correct": true, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Wiederherstellung ohne Backup möglich?', 2, '[{"text": "Nein", "correct": true, "because": "Datenbasis fehlt"}, {"text": "Ja", "correct": false, "because": "Unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Optionen verbessern die Wiederherstellung?', 4, '[{"text": "Offsite-Speicher", "correct": true, "because": "Schützt vor lokalem Ausfall"}, {"text": "Automatisierte Tests", "correct": true, "because": "Sichern Prozess"}, {"text": "Schnelle CPU", "correct": false, "because": "Hardwareaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Wiederherstellung nur für große Datenbanken ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Systeme brauchen es"}, {"text": "Ja", "correct": false, "because": "Größe egal"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Wiederherstellung unwichtig?', 3, '[{"text": "Backup-Frequenz", "correct": false, "because": "Beeinflusst Datenverlust"}, {"text": "Testläufe", "correct": false, "because": "Sichern Erfolg"}, {"text": "Farbcodierung", "correct": true, "because": "Kein technischer Nutzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Wiederherstellung schützt Daten. b) Sie braucht keine Dokumentation.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Dokumentation hilft"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Strategie wähle ich für minimale Ausfallzeiten?', 5, '[{"text": "Point-in-Time Recovery", "correct": true, "because": "Präzise Wiederherstellung"}, {"text": "Manuelle Kopien", "correct": false, "because": "Zu langsam"}, {"text": "Einmalige Sicherung", "correct": false, "because": "Zu riskant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ich ohne Tests wiederherstellen?', 3, '[{"text": "Nein", "correct": true, "because": "Tests sichern Erfolg"}, {"text": "Ja", "correct": false, "because": "Risiko steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Wiederherstellung auch für einzelne Tabellen geht?', 2, '[{"text": "Ja", "correct": true, "because": "Granulare Wiederherstellung möglich"}, {"text": "Nein", "correct": false, "because": "Nicht nur komplett"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool hilft mir bei der Wiederherstellung?', 4, '[{"text": "RMAN", "correct": true, "because": "Oracle-Wiederherstellungstool"}, {"text": "Notepad", "correct": false, "because": "Kein Backup-Tool"}, {"text": "Browser", "correct": false, "because": "Nicht datenbankspezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gute Wiederherstellung?', 5, '[{"text": "Minimierter Datenverlust", "correct": true, "because": "Aktuelle Backups"}, {"text": "Schnelle Verfügbarkeit", "correct": true, "because": "Reduziert Downtime"}, {"text": "Bessere Grafik", "correct": false, "because": "Kein Bezug"}]');

