-- questions.sql (IP Multimedia Subsystem, z. B. Netzwerkarchitektur, SIP, Telekommunikation)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein System für Multimedia immer auf IP basiert?', 2, '[{"text": "Ja", "correct": true, "because": "IMS ist ein All-IP-System"}, {"text": "Nein", "correct": false, "because": "IMS nutzt IP"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll steuert die Kommunikation in einem Multimedia-System?', 3, '[{"text": "SIP", "correct": true, "because": "Session Initiation Protocol ist zentral"}, {"text": "HTTP", "correct": false, "because": "Für Web, nicht IMS"}, {"text": "FTP", "correct": false, "because": "Für Dateien"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben hat ein System für IP-Multimedia?', 5, '[{"text": "Sprachdienste", "correct": true, "because": "z. B. VoIP"}, {"text": "Netzwerksteuerung", "correct": true, "because": "Verbindet Netze"}, {"text": "Dateispeicherung", "correct": false, "because": "Nicht primär"}, {"text": "Webhosting", "correct": false, "because": "Andere Technologie"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Es verbindet Mobilfunk mit IP-Netzen. b) Es nutzt nur Wi-Fi.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "IMS ist netzübergreifend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein Multimedia-System einrichte?', 4, '[{"text": "SIP-Steuerung", "correct": false, "because": "Kernfunktion"}, {"text": "QoS", "correct": false, "because": "Qualitätssicherung nötig"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass es nur für Mobilfunk gedacht ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Festnetz unterstützt"}, {"text": "Ja", "correct": false, "because": "Breiter Einsatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponente verbindet IMS mit klassischen Netzen?', 3, '[{"text": "Media Gateway", "correct": true, "because": "Konvertiert Signale"}, {"text": "Router", "correct": false, "because": "Nur Netzwerk"}, {"text": "Firewall", "correct": false, "because": "Sicherheit, nicht Konvertierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein IP-basiertes System?', 5, '[{"text": "Flexibilität", "correct": true, "because": "Netzübergreifend"}, {"text": "Dienstintegration", "correct": true, "because": "Sprache und Daten"}, {"text": "Hohe Latenz", "correct": false, "because": "Nicht erwünscht"}, {"text": "Komplexität", "correct": false, "because": "Ziel ist Vereinfachung"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) SIP das Hauptprotokoll ist und b) IMS nur 5G nutzt. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "IMS ist netzagnostisch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein Multimedia-System?', 4, '[{"text": "HSS", "correct": false, "because": "Benutzerdatenbank"}, {"text": "CSCF", "correct": false, "because": "Anrufsteuerung"}, {"text": "Monitorgröße", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist IMS nur für Sprache gedacht?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Video und Daten"}, {"text": "Ja", "correct": false, "because": "Multimedial"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktionen hat die CSCF-Komponente?', 4, '[{"text": "Anrufsteuerung", "correct": true, "because": "Managed Sessions"}, {"text": "Routing", "correct": true, "because": "Leitet Anfragen"}, {"text": "Datenkompression", "correct": false, "because": "Nicht ihre Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass es keine QoS unterstützt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "QoS ist zentral"}, {"text": "Ja", "correct": false, "because": "Qualität gesichert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem IP-Multimedia-System?', 3, '[{"text": "Dienstintegration", "correct": true, "because": "Vereint Sprache und Daten"}, {"text": "Hardwareersatz", "correct": false, "because": "Softwarefokus"}, {"text": "Kostensteigerung", "correct": false, "because": "Effizienz ist Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Es nutzt 3GPP-Standards. b) Es ist nur für Festnetz.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Mobilfunk"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt das HSS?', 4, '[{"text": "Benutzerdatenbank", "correct": true, "because": "Speichert Profile"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Nicht primär"}, {"text": "Routing", "correct": false, "because": "Andere Komponente"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob IMS nur für LTE ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch GSM, WLAN"}, {"text": "Ja", "correct": false, "because": "Netzübergreifend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen ein Multimedia-System nützlich?', 5, '[{"text": "Netzwerkanbindung", "correct": true, "because": "Verbindet verschiedene Netze"}, {"text": "Dienstbereitstellung", "correct": true, "because": "Multimedia-Dienste"}, {"text": "Hohe Latenz", "correct": false, "because": "Nicht erwünscht"}, {"text": "Komplexität", "correct": false, "because": "Ziel ist Einfachheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Nutzt IMS TCP für Signalisierung?', 3, '[{"text": "Nein", "correct": true, "because": "SIP über UDP oder TCP"}, {"text": "Ja", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einem IP-Multimedia-System?', 4, '[{"text": "VoLTE-Anruf", "correct": true, "because": "Sprache über LTE"}, {"text": "Dateiübertragung", "correct": false, "because": "Anderes Protokoll"}, {"text": "Webhosting", "correct": false, "because": "HTTP-basierend"}]');

