-- questions.sql (Schutz von Daten, IT-Sicherheitsmaßnahmen, Bedrohungen in IT)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Passwort allein immer genug Schutz bietet?', 2, '[{"text": "Nein", "correct": true, "because": "Mehrfaktor erhöht Sicherheit"}, {"text": "Ja", "correct": false, "because": "Kann geknackt werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme hilft mir, Daten vor unbefugtem Zugriff zu schützen?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Macht Daten unlesbar"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nur Geschwindigkeit"}, {"text": "Schnelle Hardware", "correct": false, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden sichern ein IT-System?', 5, '[{"text": "Firewall", "correct": true, "because": "Blockt Angriffe"}, {"text": "Antivirus", "correct": true, "because": "Erkennt Malware"}, {"text": "Regelmäßige Updates", "correct": true, "because": "Schließt Lücken"}, {"text": "Großer Monitor", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Phishing zielt auf Nutzerdaten. b) Updates sind optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Updates sind essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein Netzwerk absichere?', 4, '[{"text": "Verschlüsselung", "correct": false, "because": "Schützt Daten"}, {"text": "Zugriffskontrollen", "correct": false, "because": "Begrenzt Zugang"}, {"text": "Router-Design", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Firewall alles abwehrt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Teil des Schutzes"}, {"text": "Ja", "correct": false, "because": "Begrenzt wirksam"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool erkennt verdächtige Aktivitäten im Netzwerk?', 3, '[{"text": "IDS", "correct": true, "because": "Intrusion Detection System"}, {"text": "Router", "correct": false, "because": "Nur Weiterleitung"}, {"text": "Texteditor", "correct": false, "because": "Kein Sicherheitswerkzeug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen ein System sicher?', 5, '[{"text": "Starke Passwörter", "correct": true, "because": "Erschweren Zugriff"}, {"text": "Backups", "correct": true, "because": "Schützen Datenverlust"}, {"text": "Verschlüsselung", "correct": true, "because": "Sichert Übertragung"}, {"text": "Hohe Auflösung", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) 2FA die Sicherheit erhöht und b) offene WLANs sicher sind. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Offene WLANs unsicher"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Daten vor Verlust zu schützen?', 4, '[{"text": "Regelmäßige Backups", "correct": false, "because": "Wiederherstellung"}, {"text": "Verschlüsselung", "correct": false, "because": "Schützt Vertraulichkeit"}, {"text": "Schnelle Festplatte", "correct": true, "because": "Nur Leistung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein VPN immer sicher?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Konfiguration"}, {"text": "Ja", "correct": false, "because": "Schwachstellen möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen schützen vor Social Engineering?', 4, '[{"text": "Schulungen", "correct": true, "because": "Sensibilisieren Nutzer"}, {"text": "Richtlinien", "correct": true, "because": "Definieren Verhalten"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Sicherheitslücken selten sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Häufig und gefährlich"}, {"text": "Ja", "correct": false, "because": "Regelmäßige Updates nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer Firewall?', 3, '[{"text": "Unbefugten Zugriff blocken", "correct": true, "because": "Filtert Verkehr"}, {"text": "Daten komprimieren", "correct": false, "because": "Nicht ihre Aufgabe"}, {"text": "Netzwerk beschleunigen", "correct": false, "because": "Kein Leistungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Backups schützen vor Ransomware. b) Antivirus stoppt alle Bedrohungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Antivirus nicht 100%"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik wähle ich, um Daten bei Übertragung zu sichern?', 4, '[{"text": "TLS", "correct": true, "because": "Verschlüsselt Kommunikation"}, {"text": "FTP", "correct": false, "because": "Unsicher"}, {"text": "HTTP", "correct": false, "because": "Klartext"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein starkes Passwort immer ausreicht?', 2, '[{"text": "Nein", "correct": true, "because": "Kombination mit 2FA besser"}, {"text": "Ja", "correct": false, "because": "Kann geknackt werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein IDS?', 5, '[{"text": "Bedrohungserkennung", "correct": true, "because": "Warnt bei Angriffen"}, {"text": "Protokollierung", "correct": true, "because": "Dokumentiert Ereignisse"}, {"text": "Datenkompression", "correct": false, "because": "Nicht enthalten"}, {"text": "Schnelle Hardware", "correct": false, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt ein Backup vor allen Bedrohungen?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Datenverlust"}, {"text": "Ja", "correct": false, "because": "Kein Echtzeitschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario zeigt einen typischen Angriff?', 4, '[{"text": "Phishing-Mail", "correct": true, "because": "Zielt auf Nutzer"}, {"text": "Software-Update", "correct": false, "because": "Kein Angriff"}, {"text": "Netzwerkscan", "correct": false, "because": "Nur Prüfung"}]');

