-- questions.sql (Datenintegrität, Systemintegrität in IT, z. B. Schutz vor Manipulation, Konsistenz)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Daten immer unverändert bleiben müssen?', 2, '[{"text": "Ja", "correct": true, "because": "Schutz vor Manipulation"}, {"text": "Nein", "correct": false, "because": "Kernmerkmal"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft mir, sicherzustellen, dass Daten nicht verändert wurden?', 3, '[{"text": "Hashing", "correct": true, "because": "Erzeugt Prüfsumme"}, {"text": "Komprimierung", "correct": false, "because": "Nur Größe"}, {"text": "Verschlüsselung", "correct": false, "because": "Schützt, prüft nicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sichern die Datenkonsistenz?', 5, '[{"text": "Transaktionen", "correct": true, "because": "Garantieren Vollständigkeit"}, {"text": "Prüfsummen", "correct": true, "because": "Erkennen Änderungen"}, {"text": "Backups", "correct": true, "because": "Wiederherstellung"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Hash-Werte prüfen Datenänderungen. b) Verschlüsselung reicht allein aus.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) prüft nicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich Daten vor Änderungen schützen will?', 4, '[{"text": "Prüfsummen", "correct": false, "because": "Erkennen Manipulation"}, {"text": "Zugriffskontrollen", "correct": false, "because": "Begrenzen Zugriff"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein System ohne Prüfung sicher ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Prüfung nötig"}, {"text": "Ja", "correct": false, "because": "Risiko bleibt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug hilft, Datenkonsistenz in Datenbanken zu sichern?', 3, '[{"text": "Constraints", "correct": true, "because": "Zwingen Regeln durch"}, {"text": "Browser", "correct": false, "because": "Kein Datenbanktool"}, {"text": "Texteditor", "correct": false, "because": "Keine Datenbankfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Sicherstellung von Datenkonsistenz?', 5, '[{"text": "Verlässlichkeit", "correct": true, "because": "Daten korrekt"}, {"text": "Nachvollziehbarkeit", "correct": true, "because": "Änderungen prüfbar"}, {"text": "Schutz vor Manipulation", "correct": true, "because": "Erkennt Fehler"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) Transaktionen Konsistenz sichern und b) Backups allein ausreichen. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Backups prüfen nicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um Daten vor Manipulation zu schützen?', 4, '[{"text": "Hash-Funktion", "correct": false, "because": "Erkennt Änderungen"}, {"text": "Zugriffskontrollen", "correct": false, "because": "Begrenzen Zugriff"}, {"text": "Monitorgröße", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist eine Prüfsumme immer notwendig?', 2, '[{"text": "Nein", "correct": true, "because": "Andere Methoden möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Techniken sichern die Datenkonsistenz?', 4, '[{"text": "Transaktionslog", "correct": true, "because": "Dokumentiert Änderungen"}, {"text": "Foreign Keys", "correct": true, "because": "Beziehungen prüfen"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Verschlüsselung allein Manipulation verhindert. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Vertraulichkeit"}, {"text": "Ja", "correct": false, "because": "Prüfung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich, wenn ich Datenkonsistenz sichere?', 3, '[{"text": "Verlässliche Daten", "correct": true, "because": "Schutz vor Fehlern"}, {"text": "Schnellere Verarbeitung", "correct": false, "because": "Indirekt"}, {"text": "Designverbesserung", "correct": false, "because": "Kein Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Prüfsummen erkennen Änderungen. b) Hashing verschlüsselt Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Hashing prüft, nicht verschlüsselt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt ein Hash bei der Datenprüfung?', 4, '[{"text": "Änderungserkennung", "correct": true, "because": "Vergleicht Prüfsumme"}, {"text": "Datenkompression", "correct": false, "because": "Nicht Zweck"}, {"text": "Schnellere Verarbeitung", "correct": false, "because": "Indirekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein System ohne Zugriffskontrollen sicher ist?', 2, '[{"text": "Nein", "correct": true, "because": "Schutz nötig"}, {"text": "Ja", "correct": false, "because": "Risiko bleibt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Sicherstellung von Datenkonsistenz?', 5, '[{"text": "Genauigkeit", "correct": true, "because": "Daten korrekt"}, {"text": "Vertrauen", "correct": true, "because": "Nutzer verlassen sich drauf"}, {"text": "Nachvollziehbarkeit", "correct": true, "because": "Änderungen prüfbar"}, {"text": "Hohe Latenz", "correct": false, "because": "Nicht erwünscht"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützt ein Backup vor Datenmanipulation?', 3, '[{"text": "Nein", "correct": true, "because": "Nur Wiederherstellung"}, {"text": "Ja", "correct": false, "because": "Kein Echtzeitschutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario zeigt einen Verlust von Datenkonsistenz?', 4, '[{"text": "Unbemerkte Änderung", "correct": true, "because": "Manipulation nicht erkannt"}, {"text": "Regelmäßige Updates", "correct": false, "because": "Kein Verlust"}, {"text": "Datenbank-Backup", "correct": false, "because": "Schutzmaßnahme"}]');

