-- questions.sql (Erfassung des Ist-Zustands von IT-Systemen, Netzwerken, Prozessen in IT)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Bestandsaufnahme immer automatisch erfolgt?', 2, '[{"text": "Nein", "correct": true, "because": "Manuelle Methoden möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel umsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft dir, den aktuellen Zustand eines Netzwerks zu erfassen?', 3, '[{"text": "Netzwerkscan", "correct": true, "because": "Erkennt Geräte"}, {"text": "Programmierung", "correct": false, "because": "Anderer Zweck"}, {"text": "Designanpassung", "correct": false, "because": "Kein Erfassungstool"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte prüfst du bei einer Systemanalyse?', 5, '[{"text": "Hardware", "correct": true, "because": "Physische Komponenten"}, {"text": "Software", "correct": true, "because": "Installierte Programme"}, {"text": "Netzwerk", "correct": true, "because": "Verbindungen"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Bestandsaufnahme erfasst Geräte. b) Sie ist nur für Software nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Hardware betroffen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich den Zustand eines Systems erhebe?', 4, '[{"text": "Netzwerkkonfiguration", "correct": false, "because": "Wichtig für Analyse"}, {"text": "Softwareversionen", "correct": false, "because": "Relevante Details"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Bestandsaufnahme immer Tools braucht. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch manuell möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel umsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool kannst du nutzen, um Geräte im Netzwerk zu finden?', 3, '[{"text": "Nmap", "correct": true, "because": "Netzwerkscanner"}, {"text": "Notepad", "correct": false, "because": "Nur Text"}, {"text": "Browser", "correct": false, "because": "Kein Scan-Tool"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gründliche Systemerfassung?', 5, '[{"text": "Übersicht", "correct": true, "because": "Klarheit über Systeme"}, {"text": "Planungsgrundlage", "correct": true, "because": "Basis für Verbesserung"}, {"text": "Fehlererkennung", "correct": true, "because": "Probleme sichtbar"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) eine Bestandsaufnahme Hardware erfasst und b) sie nur für neue Systeme ist. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch bestehende Systeme"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um den Zustand eines Systems zu dokumentieren?', 4, '[{"text": "Inventarliste", "correct": false, "because": "Erfasst Komponenten"}, {"text": "Netzwerkscan", "correct": false, "because": "Zeigt Verbindungen"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist eine Systemerfassung immer automatisiert?', 2, '[{"text": "Nein", "correct": true, "because": "Manuelle Methoden möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden helfen bei der Erfassung eines Netzwerks?', 4, '[{"text": "Interviews", "correct": true, "because": "Erfahrungen sammeln"}, {"text": "Scans", "correct": true, "because": "Geräte erkennen"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass eine Bestandsaufnahme nur Hardware betrifft. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Software"}, {"text": "Ja", "correct": false, "because": "Umfassend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einer Bestandsaufnahme?', 3, '[{"text": "Aktuellen Zustand kennen", "correct": true, "because": "Grundlage schaffen"}, {"text": "Design verbessern", "correct": false, "because": "Sekundär"}, {"text": "Daten komprimieren", "correct": false, "because": "Anderer Zweck"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Netzwerkscans zeigen Geräte. b) Eine Erfassung ist nur für große Firmen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch kleine Netze"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt eine Inventarliste?', 4, '[{"text": "Dokumentiert Komponenten", "correct": true, "because": "Übersicht schaffen"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Anderer Zweck"}, {"text": "Design anpassen", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Bestandsaufnahme immer Softwaretools braucht?', 2, '[{"text": "Nein", "correct": true, "because": "Auch manuell möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen eine Systemerfassung nützlich?', 5, '[{"text": "Genauigkeit", "correct": true, "because": "Detaillierte Daten"}, {"text": "Vollständigkeit", "correct": true, "because": "Alle Komponenten"}, {"text": "Planungsgrundlage", "correct": true, "because": "Für Verbesserungen"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erfasst eine Bestandsaufnahme nur neue Systeme?', 3, '[{"text": "Nein", "correct": true, "because": "Auch bestehende"}, {"text": "Ja", "correct": false, "because": "Umfassend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Erfassung eines Systems?', 4, '[{"text": "Netzwerk vor Optimierung prüfen", "correct": true, "because": "Ist-Zustand"}, {"text": "Webseitenlayout erstellen", "correct": false, "because": "Anderer Zweck"}, {"text": "Daten komprimieren", "correct": false, "because": "Sekundär"}]');

