-- questions.sql (Rolle und Aufgaben in der IT-Sicherheit, z. B. Schutz, Richtlinien, Audits)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob jemand im Unternehmen immer für die Datensicherheit verantwortlich ist?', 2, '[{"text": "Nein", "correct": true, "because": "Nur bei Bedarf bestellt"}, {"text": "Ja", "correct": false, "because": "Keine Pflicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat jemand, der die IT-Sicherheit überwacht?', 3, '[{"text": "Risiken bewerten", "correct": true, "because": "Identifiziert Schwachstellen"}, {"text": "Webseiten designen", "correct": false, "because": "Kein Sicherheitsaspekt"}, {"text": "Hardware kaufen", "correct": false, "because": "Andere Rolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Tätigkeiten gehören zur Sicherstellung von Datenschutz?', 5, '[{"text": "Richtlinien erstellen", "correct": true, "because": "Definiert Standards"}, {"text": "Audits durchführen", "correct": true, "because": "Prüft Einhaltung"}, {"text": "Mitarbeiter schulen", "correct": true, "because": "Sensibilisiert"}, {"text": "Marketingpläne", "correct": false, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Jemand muss ISO 27001 kennen. b) Es gibt eine gesetzliche Pflicht zur Bestellung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Keine allgemeine Pflicht"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich die Sicherheit eines Systems plane?', 4, '[{"text": "Risikoanalyse", "correct": false, "because": "Schwachstellen finden"}, {"text": "Schulungen", "correct": false, "because": "Bewusstsein schaffen"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass jemand für IT-Sicherheit immer ein Programmierer sein muss. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Fachwissen reicht"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt jemand bei einem Sicherheitsvorfall?', 3, '[{"text": "Koordination", "correct": true, "because": "Leitet Maßnahmen"}, {"text": "Marketing", "correct": false, "because": "Kein Sicherheitsaspekt"}, {"text": "Hardware-Reparatur", "correct": false, "because": "Andere Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Fähigkeiten braucht jemand für die IT-Sicherheit?', 5, '[{"text": "Risikomanagement", "correct": true, "because": "Bewertet Gefahren"}, {"text": "Kommunikation", "correct": true, "because": "Koordiniert Teams"}, {"text": "Technisches Wissen", "correct": true, "because": "Versteht Systeme"}, {"text": "Grafikdesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) jemand die Geschäftsführung berät und b) nur technische Aufgaben hat. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist zu eng"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um die IT-Sicherheit zu überwachen?', 4, '[{"text": "Audits", "correct": false, "because": "Prüft Maßnahmen"}, {"text": "Richtlinien", "correct": false, "because": "Setzt Standards"}, {"text": "Dekoration", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss jemand immer intern sein?', 2, '[{"text": "Nein", "correct": true, "because": "Extern möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel wählbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet jemand extern für die Sicherheit?', 4, '[{"text": "Objektivität", "correct": true, "because": "Unabhängige Sicht"}, {"text": "Spezialwissen", "correct": true, "because": "Expertenexpertise"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass jemand nur für große Firmen nötig ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch KMUs profitieren"}, {"text": "Ja", "correct": false, "because": "Größe egal"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Sicherheitsrichtlinien?', 3, '[{"text": "Daten schützen", "correct": true, "because": "Vertraulichkeit sichern"}, {"text": "Design verbessern", "correct": false, "because": "Kein Ziel"}, {"text": "Kosten erhöhen", "correct": false, "because": "Effizienz ist Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Jemand schult Mitarbeiter. b) Jemand ist gesetzlich vorgeschrieben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) nur bei KRITIS"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat jemand bei einem Audit?', 4, '[{"text": "Überwachung", "correct": true, "because": "Prüft Einhaltung"}, {"text": "Webentwicklung", "correct": false, "because": "Andere Rolle"}, {"text": "Hardwarekauf", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob jemand Datenschutz übernimmt?', 2, '[{"text": "Nein", "correct": true, "because": "DSB zuständig"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Rollen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen jemanden effektiv?', 5, '[{"text": "Technisches Wissen", "correct": true, "because": "Versteht Systeme"}, {"text": "Kommunikation", "correct": true, "because": "Koordiniert Maßnahmen"}, {"text": "Analytisches Denken", "correct": true, "because": "Bewertet Risiken"}, {"text": "Grafikdesign", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist jemand für KRITIS Pflicht?', 3, '[{"text": "Ja", "correct": true, "because": "IT-Sicherheitsgesetz"}, {"text": "Nein", "correct": false, "because": "Gesetzlich geregelt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu jemandem im Unternehmen?', 4, '[{"text": "Risikoanalyse nach Cyberangriff", "correct": true, "because": "Bewertet Schwachstellen"}, {"text": "Webseitenlayout", "correct": false, "because": "Andere Aufgabe"}, {"text": "Hardwaremontage", "correct": false, "because": "Technische Rolle"}]');

