-- questions.sql (Informations- und Telekommunikationsbranche, z. B. Trends, Berufe, Technologien in IT)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob diese Branche nur aus Programmierern besteht?', 2, '[{"text": "Nein", "correct": true, "because": "Viele Rollen vorhanden"}, {"text": "Ja", "correct": false, "because": "Vielfalt an Berufen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Trend prägt die Entwicklung in dieser Branche stark?', 3, '[{"text": "Digitalisierung", "correct": true, "because": "Treibt Innovation"}, {"text": "Hardware-Design", "correct": false, "because": "Nur ein Teil"}, {"text": "Büroverschönerung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bereiche gehören zu dieser Branche?', 5, '[{"text": "IT-Dienstleistungen", "correct": true, "because": "Software und Support"}, {"text": "Telekommunikation", "correct": true, "because": "Netzwerke und Dienste"}, {"text": "Cloud Computing", "correct": true, "because": "Moderne Technologie"}, {"text": "Inneneinrichtung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) 5G ist ein Thema dieser Branche. b) Sie beschäftigt nur Ingenieure.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Vielfalt an Berufen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich die Branche analysiere?', 4, '[{"text": "Technologietrends", "correct": false, "because": "Treiben Entwicklung"}, {"text": "Berufsfelder", "correct": false, "because": "Definieren Tätigkeiten"}, {"text": "Büroverschönerung", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass diese Branche nur Telekommunikation umfasst. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch IT-Dienste"}, {"text": "Ja", "correct": false, "because": "Breiter gefächert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Beruf ist typisch für diese Branche?', 3, '[{"text": "Fachinformatiker", "correct": true, "because": "Kernrolle in IT"}, {"text": "Innenarchitekt", "correct": false, "because": "Anderer Bereich"}, {"text": "Grafikdesigner", "correct": false, "because": "Spezifische Nische"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien prägen diese Branche?', 5, '[{"text": "KI", "correct": true, "because": "Automatisierung"}, {"text": "IoT", "correct": true, "because": "Vernetzung"}, {"text": "5G", "correct": true, "because": "Schnelle Kommunikation"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass a) Cloud Computing ein Trend ist und b) die Branche nur Hardware verkauft. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Dienstleistungen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um in dieser Branche zu arbeiten?', 4, '[{"text": "IT-Kenntnisse", "correct": false, "because": "Grundvoraussetzung"}, {"text": "Netzwerkverständnis", "correct": false, "because": "Wichtig für TK"}, {"text": "Innenarchitektur", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Umfasst die Branche nur Softwareentwicklung?', 2, '[{"text": "Nein", "correct": true, "because": "Auch TK-Dienste"}, {"text": "Ja", "correct": false, "because": "Breiter gefächert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Trends beeinflussen die Branche?', 4, '[{"text": "Cybersecurity", "correct": true, "because": "Schutz wichtig"}, {"text": "Digitalisierung", "correct": true, "because": "Prozesse optimieren"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass die Branche keine Hardware umfasst. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Netzwerkgeräte"}, {"text": "Ja", "correct": false, "because": "Umfassend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt diese Branche?', 3, '[{"text": "Vernetzung ermöglichen", "correct": true, "because": "IT und TK verbinden"}, {"text": "Datenkompression", "correct": false, "because": "Sekundär"}, {"text": "Designverbesserung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) KI ist ein Wachstumsfeld. b) Die Branche schrumpft.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Branche wächst"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt 5G in dieser Branche?', 4, '[{"text": "Schnellere Kommunikation", "correct": true, "because": "Verbessert Netzwerke"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Anderer Zweck"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die Branche nur in Deutschland aktiv ist?', 2, '[{"text": "Nein", "correct": true, "because": "Global tätig"}, {"text": "Ja", "correct": false, "because": "International"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen diese Branche zukunftssicher?', 5, '[{"text": "Technologische Innovation", "correct": true, "because": "Treibt Fortschritt"}, {"text": "Wachsende Nachfrage", "correct": true, "because": "Digitalisierung"}, {"text": "Vielfalt an Berufen", "correct": true, "because": "Breite Einsatzmöglichkeiten"}, {"text": "Farbanpassung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Branche nur für Hardware?', 3, '[{"text": "Nein", "correct": true, "because": "Auch Software und Dienste"}, {"text": "Ja", "correct": false, "because": "Umfassend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Branche?', 4, '[{"text": "Netzwerk für ein Unternehmen einrichten", "correct": true, "because": "Typische Aufgabe"}, {"text": "Inneneinrichtung planen", "correct": false, "because": "Anderer Bereich"}, {"text": "Datenkompression entwickeln", "correct": false, "because": "Spezifische Nische"}]');

