-- Initiierung: Abklären wirtschaftlicher Aspekte
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist das Abklären wirtschaftlicher Aspekte Teil der Initiierung?', 2, '[{"text": "Ja", "correct": true, "because": "Wirtschaftlichkeit prüft Machbarkeit"}, {"text": "Nein", "correct": false, "because": "Es gehört zur Initiierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel hat das Abklären wirtschaftlicher Aspekte?', 3, '[{"text": "Kosten-Nutzen-Verhältnis prüfen", "correct": true, "because": "Bewertet Rentabilität"}, {"text": "Teamgröße festlegen", "correct": false, "because": "Anderer Fokus"}, {"text": "Technische Details klären", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Wirtschaftliche Aspekte beeinflussen die Projektfreigabe. b) Sie werden erst in der Durchführung geklärt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Initiierung ist entscheidend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte werden bei der wirtschaftlichen Abklärung untersucht?', 4, '[{"text": "Anschaffungskosten", "correct": true, "because": "Teil der Kalkulation"}, {"text": "Teamzufriedenheit", "correct": false, "because": "Kein wirtschaftlicher Faktor"}, {"text": "Betriebskosten", "correct": true, "because": "Langfristige Kosten"}, {"text": "Nutzen für Unternehmen", "correct": true, "because": "Bewertet Ertrag"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Projekt ohne wirtschaftliche Abklärung starten?', 2, '[{"text": "Nein", "correct": true, "because": "Risiko von Verlusten"}, {"text": "Ja", "correct": false, "because": "Wirtschaftlichkeit ist Grundlage"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft beim Abklären wirtschaftlicher Aspekte?', 3, '[{"text": "Kosten-Nutzen-Analyse", "correct": true, "because": "Bewertet Wirtschaftlichkeit"}, {"text": "Keine Planung", "correct": false, "because": "Fehlt Struktur"}, {"text": "Zufällige Schätzung", "correct": false, "because": "Ungenau"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die wirtschaftliche Abklärung nur für große Projekte relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kleine Projekte brauchen sie"}, {"text": "Ja", "correct": false, "because": "Gilt für alle Projekte"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor gehört zur wirtschaftlichen Abklärung?', 3, '[{"text": "Return on Investment (ROI)", "correct": true, "because": "Misst Rentabilität"}, {"text": "Teamdynamik", "correct": false, "because": "Kein wirtschaftlicher Aspekt"}, {"text": "Technische Machbarkeit", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Wirtschaftliche Aspekte prüfen die Machbarkeit. b) Sie sind unwichtig für IT-Projekte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, auch IT braucht sie"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Abklärung wirtschaftlicher Aspekte?', 3, '[{"text": "Unrentable Projekte starten", "correct": true, "because": "Kosten unklar"}, {"text": "Projekt wird schneller", "correct": false, "because": "Eher Verzögerung"}, {"text": "Team wird effizienter", "correct": false, "because": "Kein Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Können wirtschaftliche Aspekte in der Initiierung ignoriert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Entscheidend für Freigabe"}, {"text": "Ja", "correct": false, "because": "Risiko von Verlusten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine wirtschaftliche Abklärung?', 3, '[{"text": "Kosten von 10.000 € vs. Nutzen von 15.000 €", "correct": true, "because": "Klarer Vergleich"}, {"text": "Irgendwas wird schon passen", "correct": false, "because": "Zu ungenau"}, {"text": "Team soll Spaß haben", "correct": false, "because": "Kein wirtschaftlicher Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die wirtschaftliche Abklärung nur für den Kunden wichtig?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Unternehmen relevant"}, {"text": "Ja", "correct": false, "because": "Beide Seiten profitieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur wirtschaftlichen Abklärung?', 4, '[{"text": "Investitionskosten", "correct": true, "because": "Grundlage der Kalkulation"}, {"text": "Unklare Schätzungen", "correct": false, "because": "Fehlt Präzision"}, {"text": "Erwarteter Nutzen", "correct": true, "because": "Misst Ertrag"}, {"text": "Amortisationszeit", "correct": true, "because": "Zeigt Rentabilität"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die wirtschaftliche Abklärung dokumentiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Nachvollziehbarkeit nötig"}, {"text": "Nein", "correct": false, "because": "Dokumentation hilft"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die wirtschaftliche Abklärung?', 3, '[{"text": "Entscheidungsgrundlage schaffen", "correct": true, "because": "Prüft Sinnhaftigkeit"}, {"text": "Technische Details klären", "correct": false, "because": "Anderer Bereich"}, {"text": "Team motivieren", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die wirtschaftliche Abklärung ohne Daten erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Daten sind Basis"}, {"text": "Ja", "correct": false, "because": "Ungenauigkeit droht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor erschwert die wirtschaftliche Abklärung?', 3, '[{"text": "Unklare Kosten", "correct": true, "because": "Verhindert Kalkulation"}, {"text": "Klarer Nutzen", "correct": false, "because": "Fördert Klarheit"}, {"text": "Gute Datenbasis", "correct": false, "because": "Unterstützt Analyse"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Wirtschaftliche Abklärung prüft Rentabilität. b) Sie erfolgt erst nach Projektstart.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, vor Start nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Ziel der wirtschaftlichen Abklärung?', 3, '[{"text": "Sicherung der Rentabilität", "correct": true, "because": "Bewertet Erfolg"}, {"text": "Zeit verlängern", "correct": false, "because": "Kein Ziel"}, {"text": "Technische Lösung finden", "correct": false, "because": "Anderer Fokus"}]');

