-- Initiierung: Analyse des Ausgangsproblems
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Gehört die Analyse des Ausgangsproblems zur Projektinitiierung?', 2, '[{"text": "Ja", "correct": true, "because": "Legt Grundlage für Ziele"}, {"text": "Nein", "correct": false, "because": "Sie ist zentral dafür"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Analyse des Ausgangsproblems?', 3, '[{"text": "Problem genau definieren", "correct": true, "because": "Schafft Klarheit"}, {"text": "Team sofort einteilen", "correct": false, "because": "Späterer Schritt"}, {"text": "Kosten reduzieren", "correct": false, "because": "Kein primäres Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Analyse identifiziert Schwachstellen. b) Sie wird erst in der Planung gemacht.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, gehört zur Initiierung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Punkte umfasst die Analyse des Ausgangsproblems?', 4, '[{"text": "Aktuelle Situation", "correct": true, "because": "Beschreibt Ist-Zustand"}, {"text": "Zufällige Ideen", "correct": false, "because": "Nicht strukturiert"}, {"text": "Problemursachen", "correct": true, "because": "Erklären Schwierigkeiten"}, {"text": "Zielvorstellung", "correct": true, "because": "Definiert Soll-Zustand"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Analyse des Ausgangsproblems für den Projektstart notwendig?', 2, '[{"text": "Ja", "correct": true, "because": "Ohne fehlt Orientierung"}, {"text": "Nein", "correct": false, "because": "Risiko von Missverständnissen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technik unterstützt die Analyse des Ausgangsproblems?', 3, '[{"text": "Ishikawa-Diagramm", "correct": true, "because": "Findet Ursachen"}, {"text": "Keine Struktur", "correct": false, "because": "Fehlt Systematik"}, {"text": "Spontane Meinungen", "correct": false, "because": "Ungenau"}]'),
('00000000-0000-0000-0000-000000000000', 'Gilt die Analyse des Ausgangsproblems nur für technische Probleme?', 2, '[{"text": "Nein", "correct": true, "because": "Auch organisatorische Aspekte"}, {"text": "Ja", "correct": false, "because": "Breitere Relevanz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt ist bei der Analyse des Ausgangsproblems zentral?', 3, '[{"text": "Detaillierte Problembeschreibung", "correct": true, "because": "Schafft Verständnis"}, {"text": "Kostenplanung", "correct": false, "because": "Späterer Schritt"}, {"text": "Teamzusammensetzung", "correct": false, "because": "Anderer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Analyse zeigt Verbesserungspotenzial. b) Sie ist nur für große Projekte nötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, auch kleine Projekte"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist eine Folge, wenn die Analyse des Ausgangsproblems fehlt?', 3, '[{"text": "Ziele werden unklar", "correct": true, "because": "Problem unklar"}, {"text": "Projekt wird schneller", "correct": false, "because": "Eher Verzögerung"}, {"text": "Team arbeitet besser", "correct": false, "because": "Fehlende Basis"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Analyse des Ausgangsproblems oberflächlich bleiben?', 2, '[{"text": "Nein", "correct": true, "because": "Tiefe nötig für Lösung"}, {"text": "Ja", "correct": false, "because": "Risiko von Fehlern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine gute Analyse des Ausgangsproblems?', 3, '[{"text": "Lange Ladezeiten durch Serverlast", "correct": true, "because": "Spezifisch und klar"}, {"text": "Irgendwas läuft schlecht", "correct": false, "because": "Zu vage"}, {"text": "Team ist langsam", "correct": false, "because": "Nicht detailliert"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Analyse des Ausgangsproblems nur für den Projektleiter relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Team braucht Verständnis"}, {"text": "Ja", "correct": false, "because": "Projektweite Bedeutung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Fragen klärt die Analyse des Ausgangsproblems?', 4, '[{"text": "Was ist das Problem?", "correct": true, "because": "Definiert Schwierigkeit"}, {"text": "Wie hoch sind Kosten?", "correct": false, "because": "Späterer Schritt"}, {"text": "Warum tritt es auf?", "correct": true, "because": "Findet Ursachen"}, {"text": "Was ist das Ziel?", "correct": true, "because": "Leitet Lösung ab"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Analyse des Ausgangsproblems schriftlich festgehalten werden?', 2, '[{"text": "Ja", "correct": true, "because": "Fördert Nachvollziehbarkeit"}, {"text": "Nein", "correct": false, "because": "Dokumentation hilft"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Analyse des Ausgangsproblems?', 3, '[{"text": "Basis für Projektziele", "correct": true, "because": "Definiert Richtung"}, {"text": "Budget festlegen", "correct": false, "because": "Späterer Schritt"}, {"text": "Team motivieren", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Analyse ohne Stakeholder-Input erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Perspektiven wichtig"}, {"text": "Ja", "correct": false, "because": "Input verbessert Analyse"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor kompliziert die Analyse des Ausgangsproblems?', 3, '[{"text": "Mangelnde Daten", "correct": true, "because": "Erschwert Verständnis"}, {"text": "Klarer Zeitplan", "correct": false, "because": "Fördert Struktur"}, {"text": "Gute Kommunikation", "correct": false, "because": "Unterstützt Analyse"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Analyse hilft bei der Priorisierung. b) Sie ist nur für technische Projekte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, breit anwendbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen der Analyse des Ausgangsproblems?', 3, '[{"text": "Klare Problemgrundlage", "correct": true, "because": "Fördert Lösung"}, {"text": "Zeitverlängerung", "correct": false, "because": "Kein Ziel"}, {"text": "Kostensteigerung", "correct": false, "because": "Unabhängig davon"}]');

