-- Initiierung: Berücksichtigen von Datensicherheit
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist das Berücksichtigen von Datensicherheit Teil der Initiierung?', 2, '[{"text": "Ja", "correct": true, "because": "Schützt Daten von Anfang an"}, {"text": "Nein", "correct": false, "because": "Es gehört zur Initiierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel hat das Berücksichtigen von Datensicherheit?', 3, '[{"text": "Schutz sensibler Daten", "correct": true, "because": "Vermeidet Verstöße"}, {"text": "Teamgröße festlegen", "correct": false, "because": "Anderer Fokus"}, {"text": "Kosten sofort senken", "correct": false, "because": "Kein primäres Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Datensicherheit beeinflusst die Projektplanung. b) Sie wird erst in der Durchführung berücksichtigt.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, früh nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte werden bei der Datensicherheit berücksichtigt?', 4, '[{"text": "Datenschutzgesetze", "correct": true, "because": "Regeln Handhabung"}, {"text": "Teamdynamik", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Verschlüsselung", "correct": true, "because": "Schützt Daten"}, {"text": "Zugriffskontrollen", "correct": true, "because": "Begrenzen Zugriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Projekt ohne Berücksichtigung der Datensicherheit starten?', 2, '[{"text": "Nein", "correct": true, "because": "Risiko von Datenlecks"}, {"text": "Ja", "correct": false, "because": "Rechtliche Folgen drohen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft bei der Datensicherheitsanalyse?', 3, '[{"text": "Risikobewertung", "correct": true, "because": "Identifiziert Gefahren"}, {"text": "Keine Planung", "correct": false, "because": "Fehlt Struktur"}, {"text": "Zufällige Annahmen", "correct": false, "because": "Riskant"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Datensicherheit nur für IT-Projekte relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Gilt für alle sensiblen Daten"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor der Datensicherheit ist in der Initiierung entscheidend?', 3, '[{"text": "Einhaltung der DSGVO", "correct": true, "because": "Rechtliche Vorschrift"}, {"text": "Teamverfügbarkeit", "correct": false, "because": "Kein Sicherheitsaspekt"}, {"text": "Kostenübersicht", "correct": false, "because": "Wirtschaftlicher Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Datensicherheit schützt vor Verstößen. b) Sie ist für kleine Projekte unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, immer relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Berücksichtigung der Datensicherheit?', 3, '[{"text": "Datenverlust droht", "correct": true, "because": "Schutz fehlt"}, {"text": "Projekt wird schneller", "correct": false, "because": "Eher Verzögerung"}, {"text": "Kosten sinken", "correct": false, "because": "Strafen möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Datensicherheit in der Initiierung ignoriert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Früher Schutz nötig"}, {"text": "Ja", "correct": false, "because": "Risiko von Verstößen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt Berücksichtigung von Datensicherheit?', 3, '[{"text": "Verschlüsselung für Kundendaten", "correct": true, "because": "Konkret und relevant"}, {"text": "Irgendwas wird sicher sein", "correct": false, "because": "Zu ungenau"}, {"text": "Team soll vorsichtig sein", "correct": false, "because": "Nicht spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Datensicherheit nur für den Kunden wichtig?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Unternehmen betroffen"}, {"text": "Ja", "correct": false, "because": "Beide Seiten profitieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente gehören zur Datensicherheitsplanung?', 4, '[{"text": "Backups", "correct": true, "because": "Schützen Daten"}, {"text": "Unklare Regeln", "correct": false, "because": "Fehlt Struktur"}, {"text": "Zugriffsrechte", "correct": true, "because": "Begrenzen Zugriff"}, {"text": "Sicherheitsrichtlinien", "correct": true, "because": "Definieren Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss Datensicherheit in der Initiierung dokumentiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Nachweis nötig"}, {"text": "Nein", "correct": false, "because": "Dokumentation schützt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt Datensicherheit in der Initiierung?', 3, '[{"text": "Risiken minimieren", "correct": true, "because": "Schützt Projekt"}, {"text": "Kosten senken", "correct": false, "because": "Kann Kosten erhöhen"}, {"text": "Team motivieren", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Datensicherheit ohne rechtliche Prüfung geplant werden?', 2, '[{"text": "Nein", "correct": true, "because": "Gesetze wie DSGVO nötig"}, {"text": "Ja", "correct": false, "because": "Rechtliche Basis fehlt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor erschwert die Datensicherheitsplanung?', 3, '[{"text": "Unklare Anforderungen", "correct": true, "because": "Verhindert Schutz"}, {"text": "Klarer Zeitplan", "correct": false, "because": "Fördert Planung"}, {"text": "Gute Technik", "correct": false, "because": "Unterstützt Sicherheit"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Datensicherheit prüft Risiken. b) Sie ist nur für technische Projekte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, breit relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Ziel der Datensicherheitsplanung?', 3, '[{"text": "Vertraulichkeit gewährleisten", "correct": true, "because": "Schützt Daten"}, {"text": "Zeit verlängern", "correct": false, "because": "Kein Ziel"}, {"text": "Team vergrößern", "correct": false, "because": "Anderer Fokus"}]');

