INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Nutzt SLAAC Router-Advertisement-Nachrichten zur IPv6-Adresszuweisung?', 2, '[{"text": "Ja", "correct": true, "because": "SLAAC verwendet RA-Nachrichten vom Router"}, {"text": "Nein", "correct": false, "because": "RA ist zentral für SLAAC"}]'),
('00000000-0000-0000-0000-000000000000', 'Erfordert DHCPv6 einen Server zur Adresszuweisung?', 2, '[{"text": "Ja", "correct": true, "because": "DHCPv6 benötigt einen DHCPv6-Server"}, {"text": "Nein", "correct": false, "because": "Ein Server ist notwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann SLAAC auch DNS-Server-Informationen bereitstellen?', 2, '[{"text": "Nein", "correct": true, "because": "SLAAC liefert keine DNS-Informationen"}, {"text": "Ja", "correct": false, "because": "DNS erfordert DHCPv6 oder manuelle Konfiguration"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist DHCPv6 statusbehaftet (stateful)?', 2, '[{"text": "Ja", "correct": true, "because": "DHCPv6 speichert Zuweisungen zentral"}, {"text": "Nein", "correct": false, "because": "DHCPv6 ist stateful, im Gegensatz zu SLAAC"}]'),
('00000000-0000-0000-0000-000000000000', 'Funktioniert SLAAC ohne einen Router im Netzwerk?', 2, '[{"text": "Nein", "correct": true, "because": "SLAAC benötigt Router für Präfix-Informationen"}, {"text": "Ja", "correct": false, "because": "Ein Router ist essenziell"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methode verwendet keine zentrale Adressverwaltung?', 2, '[{"text": "SLAAC", "correct": true, "because": "SLAAC ist stateless, keine Serververwaltung"}, {"text": "DHCPv6", "correct": false, "because": "DHCPv6 ist stateful"}, {"text": "Manuelle Zuweisung", "correct": false, "because": "Nicht automatisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was benötigt ein Client von einem Router, um SLAAC zu nutzen?', 3, '[{"text": "Netzwerkpräfix", "correct": true, "because": "SLAAC kombiniert Präfix mit Interface-ID"}, {"text": "Komplette IP-Adresse", "correct": false, "because": "Client generiert die ID selbst"}, {"text": "DNS-Adresse", "correct": false, "because": "SLAAC liefert kein DNS"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Autokonfigurationsmethode kann zusätzlich DNS- und NTP-Serverinformationen liefern?', 2, '[{"text": "DHCPv6", "correct": true, "because": "DHCPv6 kann zusätzliche Parameter verteilen"}, {"text": "SLAAC", "correct": false, "because": "SLAAC beschränkt sich auf Adressen"}, {"text": "APIPA", "correct": false, "because": "Gilt nur für IPv4"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponente generiert bei SLAAC die Interface-ID?', 2, '[{"text": "Der Client", "correct": true, "because": "SLAAC nutzt z. B. die MAC-Adresse des Clients"}, {"text": "Der Router", "correct": false, "because": "Router liefert nur das Präfix"}, {"text": "Ein DHCPv6-Server", "correct": false, "because": "Nicht bei SLAAC"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode ist für komplexe Netzwerke mit zentraler Kontrolle besser geeignet?', 2, '[{"text": "DHCPv6", "correct": true, "because": "Bietet zentrale Verwaltung und Kontrolle"}, {"text": "SLAAC", "correct": false, "because": "SLAAC ist dezentral"}, {"text": "Statische Zuweisung", "correct": false, "because": "Zu aufwendig"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Aussagen treffen auf SLAAC zu?', 4, '[{"text": "Stateless-Methode", "correct": true, "because": "Keine zentrale Verwaltung"}, {"text": "Benötigt Router-Advertisements", "correct": true, "because": "RA liefert das Präfix"}, {"text": "Liefert DNS-Informationen", "correct": false, "because": "DNS fehlt bei SLAAC"}, {"text": "Client generiert Interface-ID", "correct": true, "because": "Z. B. aus MAC-Adresse"}]'),
('00000000-0000-0000-0000-000000000000', 'Was kann DHCPv6 einem Client bereitstellen?', 3, '[{"text": "IPv6-Adresse", "correct": true, "because": "Hauptfunktion von DHCPv6"}, {"text": "DNS-Server-Adresse", "correct": true, "because": "Zusätzliche Parameter möglich"}, {"text": "Netzwerkpräfix", "correct": true, "because": "Wird mitgeliefert"}, {"text": "MAC-Adresse", "correct": false, "because": "Client-seitig vorhanden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Unterschiede gibt es zwischen SLAAC und DHCPv6?', 4, '[{"text": "SLAAC ist stateless, DHCPv6 stateful", "correct": true, "because": "Kernunterschied"}, {"text": "DHCPv6 benötigt einen Server, SLAAC nicht", "correct": true, "because": "SLAAC nutzt Router"}, {"text": "SLAAC liefert DNS, DHCPv6 nicht", "correct": false, "because": "Umgekehrt"}, {"text": "DHCPv6 bietet mehr Konfigurationsoptionen", "correct": true, "because": "Z. B. DNS, NTP"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet SLAAC?', 3, '[{"text": "Einfache Einrichtung", "correct": true, "because": "Keine Serververwaltung nötig"}, {"text": "Keine zentrale Instanz nötig", "correct": true, "because": "Nur Router erforderlich"}, {"text": "Hohe Kontrolle über Adressen", "correct": false, "because": "Wenig Kontrolle"}, {"text": "Schnelle Autokonfiguration", "correct": true, "because": "Direkt über RA"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind für DHCPv6 notwendig?', 3, '[{"text": "DHCPv6-Server", "correct": true, "because": "Verteilt Adressen"}, {"text": "Router", "correct": true, "because": "Leitet DHCPv6-Anfragen weiter"}, {"text": "Client mit DHCPv6-Unterstützung", "correct": true, "because": "Empfängt die Konfiguration"}, {"text": "Switch ohne DHCP-Funktion", "correct": false, "because": "Nicht zwingend"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) SLAAC ist stateless. b) DHCPv6 ist stateless.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SLAAC ist stateless, DHCPv6 stateful"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) SLAAC benötigt Router-Advertisements. b) DHCPv6 funktioniert ohne Server.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SLAAC nutzt RA, DHCPv6 braucht einen Server"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) DHCPv6 kann DNS-Server zuweisen. b) SLAAC liefert ebenfalls DNS-Informationen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DHCPv6 ja, SLAAC nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) SLAAC generiert Adressen aus Präfix und Interface-ID. b) DHCPv6 ist einfacher als SLAAC.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SLAAC ja, DHCPv6 komplexer durch Server"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) DHCPv6 bietet zentrale Verwaltung. b) SLAAC erfordert einen DHCP-Server.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DHCPv6 ja, SLAAC nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');