-- questions.sql (CMYK-Farbmodell, relevant für Drucktechnik und Farbmanagement)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist das CMYK-Modell nur für den Druck geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Auch in Software nutzbar"}, {"text": "Ja", "correct": false, "because": "Nicht auf Druck beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Farbe fehlt mir, wenn ich nur Cyan, Magenta und Gelb habe?', 3, '[{"text": "Schwarz", "correct": true, "because": "Key ergänzt Tiefe"}, {"text": "Weiß", "correct": false, "because": "Kein Bestandteil"}, {"text": "Grau", "correct": false, "because": "Ergebnis, kein Grundton"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zum CMYK-Modell?', 4, '[{"text": "Cyan", "correct": true, "because": "Grundfarbe"}, {"text": "Magenta", "correct": true, "because": "Grundfarbe"}, {"text": "Rot", "correct": false, "because": "RGB-spezifisch"}, {"text": "Grün", "correct": false, "because": "Nicht enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) CMYK ist subtraktiv. b) Es ersetzt RGB vollständig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "RGB bleibt für Bildschirme"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Arbeit mit diesem Farbsystem?', 4, '[{"text": "Farbmischung", "correct": false, "because": "Kern des Systems"}, {"text": "Schwarzanteil", "correct": false, "because": "Wichtig für Tiefe"}, {"text": "Lichtintensität", "correct": true, "because": "RGB-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Schwarz im Modell immer nötig ist?', 2, '[{"text": "Nein", "correct": true, "because": "CMY kann theoretisch reichen"}, {"text": "Ja", "correct": false, "because": "Praktisch, aber nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Zweck hat die vierte Komponente in diesem System?', 3, '[{"text": "Tiefe hinzufügen", "correct": true, "because": "Schwarz verstärkt Kontrast"}, {"text": "Helligkeit erhöhen", "correct": false, "because": "Subtraktiv, nicht additiv"}, {"text": "Farbgenauigkeit verringern", "correct": false, "because": "Verbessert Präzision"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen dieses Farbsystem nützlich?', 5, '[{"text": "Subtraktive Mischung", "correct": true, "because": "Für Druck essenziell"}, {"text": "Breiter Farbraum", "correct": true, "because": "Vielseitige Farben"}, {"text": "Hohe Helligkeit", "correct": false, "because": "Nicht lichtbasiert"}, {"text": "Pixelgenauigkeit", "correct": false, "because": "Nicht digital"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Das Modell ist für Drucker. b) Es funktioniert auch für Bildschirme. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Bildschirme nutzen RGB"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht direkt für dieses Modell?', 4, '[{"text": "Cyan", "correct": false, "because": "Grundbestandteil"}, {"text": "Schwarz", "correct": false, "because": "Ergänzt Tiefe"}, {"text": "Rot", "correct": true, "because": "RGB-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist das System additiv?', 2, '[{"text": "Nein", "correct": true, "because": "Subtraktiv für Druck"}, {"text": "Ja", "correct": false, "because": "Additiv ist RGB"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Farben mische ich für ein sattes Schwarz?', 5, '[{"text": "Cyan", "correct": true, "because": "Grundfarbe"}, {"text": "Magenta", "correct": true, "because": "Grundfarbe"}, {"text": "Gelb", "correct": true, "because": "Grundfarbe"}, {"text": "Grün", "correct": false, "because": "Nicht enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass das Modell ohne Schwarz unvollständig ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "CMY kann allein funktionieren"}, {"text": "Ja", "correct": false, "because": "Schwarz ist Zusatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Farbauswahl für einen Druck?', 3, '[{"text": "Farbtreue", "correct": true, "because": "Wichtig für Qualität"}, {"text": "Schnelligkeit", "correct": false, "because": "Sekundär"}, {"text": "Helligkeit", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Das System ist für physische Medien. b) Es hat mehr Farben als RGB.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "RGB hat breiteren Gamut"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet dieses Farbsystem?', 4, '[{"text": "Druckgenauigkeit", "correct": true, "because": "Optimiert für Papier"}, {"text": "Kosteneffizienz", "correct": true, "because": "Schwarz spart Tinte"}, {"text": "Hohe Helligkeit", "correct": false, "because": "Nicht lichtbasiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Arbeit mit Farben unwichtig?', 3, '[{"text": "Mischverhältnis", "correct": false, "because": "Entscheidend für Ergebnis"}, {"text": "Papierqualität", "correct": false, "because": "Beeinflusst Druck"}, {"text": "Bildschirmkalibrierung", "correct": true, "because": "Nur für RGB"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erzeugt das System auch Weiß?', 3, '[{"text": "Nein", "correct": true, "because": "Weiß ist Papierfarbe"}, {"text": "Ja", "correct": false, "because": "Subtraktiv, kein Licht"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob dieses Modell für digitale Medien passt?', 2, '[{"text": "Nein", "correct": true, "because": "RGB ist Standard"}, {"text": "Ja", "correct": false, "because": "Nicht lichtbasiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die vierte Farbe im Druck?', 4, '[{"text": "Kontrast verstärken", "correct": true, "because": "Schwarz für Tiefe"}, {"text": "Farbvielfalt erhöhen", "correct": false, "because": "CMY deckt Farben ab"}, {"text": "Helligkeit steigern", "correct": false, "because": "Nicht additiv"}]');

