-- questions.sql (Compiler, relevant für Programmierung und Softwareentwicklung)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Compiler dasselbe wie ein Interpreter?', 2, '[{"text": "Nein", "correct": true, "because": "Compiler übersetzt komplett, Interpreter zeilenweise"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Ausführung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe übernimmt dieses Tool primär?', 3, '[{"text": "Quellcode in Maschinencode umwandeln", "correct": true, "because": "Kernfunktion"}, {"text": "Code ausführen", "correct": false, "because": "Nicht direkt"}, {"text": "Syntax prüfen", "correct": false, "because": "Nur ein Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phasen gehören zur Arbeit eines Compilers?', 5, '[{"text": "Lexikalische Analyse", "correct": true, "because": "Tokenisierung"}, {"text": "Codegenerierung", "correct": true, "because": "Maschinencode erstellen"}, {"text": "Programmausführung", "correct": false, "because": "Nicht seine Aufgabe"}, {"text": "Debugging", "correct": false, "because": "IDE-Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Compiler optimiert den Code. b) Er übersetzt nur Hochsprachen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Assembler möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl eines Compilers?', 4, '[{"text": "Zielsprache", "correct": false, "because": "Entscheidend für Ausgabe"}, {"text": "Optimierungsoptionen", "correct": false, "because": "Wichtig für Performance"}, {"text": "Farbschema", "correct": true, "because": "Irrelevant für Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Compiler Fehler im Code behebt?', 2, '[{"text": "Nein", "correct": true, "because": "Nur Erkennung, keine Korrektur"}, {"text": "Ja", "correct": false, "because": "Programmiereraufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Schritt führt ein Compiler als Erstes aus?', 3, '[{"text": "Lexikalische Analyse", "correct": true, "because": "Zerlegt Quellcode in Token"}, {"text": "Code-Optimierung", "correct": false, "because": "Späterer Schritt"}, {"text": "Linken", "correct": false, "because": "Nach Kompilierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bringt mir ein Compiler?', 5, '[{"text": "Schnellere Ausführung", "correct": true, "because": "Maschinencode ist effizient"}, {"text": "Fehlererkennung", "correct": true, "because": "Vor Ausführung"}, {"text": "Plattformunabhängigkeit", "correct": false, "because": "Zielsystem-spezifisch"}, {"text": "Live-Debugging", "correct": false, "because": "Nicht seine Rolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Compiler erzeugt ausführbare Dateien. b) Er arbeitet zeilenweise. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist Interpreter"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht direkt vom Compiler?', 4, '[{"text": "Objektcode", "correct": false, "because": "Zwischenschritt"}, {"text": "Fehlermeldungen", "correct": false, "because": "Hilft bei Korrektur"}, {"text": "Benutzeroberfläche", "correct": true, "because": "IDE-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist ein Compiler plattformunabhängig?', 2, '[{"text": "Nein", "correct": true, "because": "Zielsystem-spezifisch"}, {"text": "Ja", "correct": false, "because": "Abhängig von Architektur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben übernimmt dieses Tool?', 4, '[{"text": "Syntaxprüfung", "correct": true, "because": "Teil des Prozesses"}, {"text": "Semantische Analyse", "correct": true, "because": "Logik überprüfen"}, {"text": "Programmausführung", "correct": false, "because": "Nicht seine Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Compiler immer optimiert. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Einstellungen"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Tool-Auswahl?', 3, '[{"text": "Kompatibilität", "correct": true, "because": "Muss zur Sprache passen"}, {"text": "Schnellste Übersetzung", "correct": false, "because": "Qualität zählt mehr"}, {"text": "Kostenlosigkeit", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Er erzeugt Maschinencode. b) Er debuggt den Code.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Debugging nicht enthalten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sind für die Übersetzung essenziell?', 5, '[{"text": "Parsing", "correct": true, "because": "Struktur analysieren"}, {"text": "Codegenerierung", "correct": true, "because": "Ausgabe erstellen"}, {"text": "Live-Ausführung", "correct": false, "because": "Nicht seine Rolle"}, {"text": "UI-Design", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Arbeit damit unwichtig?', 3, '[{"text": "Zielarchitektur", "correct": false, "because": "Entscheidend für Ausgabe"}, {"text": "Fehlerberichte", "correct": false, "because": "Hilft bei Korrektur"}, {"text": "Schriftart", "correct": true, "because": "Kein technischer Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Übersetzt ein Compiler auch während der Laufzeit?', 3, '[{"text": "Nein", "correct": true, "because": "Vorab-Übersetzung"}, {"text": "Ja", "correct": false, "because": "Das macht ein JIT"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Compiler für Skriptsprachen nötig ist?', 2, '[{"text": "Nein", "correct": true, "because": "Meist interpretiert"}, {"text": "Ja", "correct": false, "because": "Skriptsprachen sind dynamisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ergebnis liefere ich mit diesem Tool?', 4, '[{"text": "Ausführbare Datei", "correct": true, "because": "Endprodukt"}, {"text": "Zwischencode", "correct": false, "because": "Nur ein Schritt"}, {"text": "Laufzeitumgebung", "correct": false, "because": "Nicht enthalten"}]');

