-- questions.sql (CRM, relevant für Software und Kundenmanagement)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein CRM-System nur für große Unternehmen geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Auch KMUs profitieren"}, {"text": "Ja", "correct": false, "because": "Skalierbar für alle Größen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem CRM?', 3, '[{"text": "Kundenbeziehungen verbessern", "correct": true, "because": "Zentralisiert Daten"}, {"text": "Hardware optimieren", "correct": false, "because": "Kein technischer Fokus"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Sicherheit ist sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktionen bietet ein CRM-System?', 5, '[{"text": "Kontaktverwaltung", "correct": true, "because": "Speichert Kundendaten"}, {"text": "Verkaufsprognosen", "correct": true, "because": "Unterstützt Planung"}, {"text": "Netzwerkkonfiguration", "correct": false, "because": "Kein IT-Fokus"}, {"text": "Grafikdesign", "correct": false, "because": "Nicht enthalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) CRM hilft beim Verkauf. b) Es ersetzt E-Mail komplett.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "E-Mail bleibt eigenständig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Auswahl eines CRM?', 4, '[{"text": "Integration", "correct": false, "because": "Wichtig für Systeme"}, {"text": "Benutzerfreundlichkeit", "correct": false, "because": "Fördert Akzeptanz"}, {"text": "Farbschema", "correct": true, "because": "Sekundär zur Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein CRM immer Cloud-basiert ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch On-Premise möglich"}, {"text": "Ja", "correct": false, "because": "Flexible Bereitstellung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Abteilung profitiert am meisten davon?', 3, '[{"text": "Vertrieb", "correct": true, "because": "Optimiert Kundenansprache"}, {"text": "IT", "correct": false, "because": "Weniger direkter Nutzen"}, {"text": "Produktion", "correct": false, "because": "Kein direkter Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bringt ein CRM?', 5, '[{"text": "Kundenzufriedenheit", "correct": true, "because": "Bessere Betreuung"}, {"text": "Effizienzsteigerung", "correct": true, "because": "Automatisiert Prozesse"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein Hardware-Fokus"}, {"text": "Grafikverbesserung", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) CRM zentralisiert Daten. b) Es ist nur für Marketing. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Vertrieb nutzt es"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein CRM?', 4, '[{"text": "Datenbank", "correct": false, "because": "Speichert Kundeninfo"}, {"text": "Schnittstellen", "correct": false, "because": "Verbindet Systeme"}, {"text": "3D-Drucker", "correct": true, "because": "Kein Zusammenhang"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist CRM nur für große Datenmengen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für kleine Firmen"}, {"text": "Ja", "correct": false, "because": "Skalierbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Daten speichere ich typischerweise?', 4, '[{"text": "Kundenkontakte", "correct": true, "because": "Basis des Systems"}, {"text": "Verkaufshistorie", "correct": true, "because": "Für Prognosen"}, {"text": "Serverlogs", "correct": false, "because": "IT-spezifisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass CRM keine Analysen bietet. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Bietet Berichte und Prognosen"}, {"text": "Ja", "correct": false, "because": "Analyse ist Kernfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Einführung?', 3, '[{"text": "Schulung", "correct": true, "because": "Sichert Akzeptanz"}, {"text": "Schnelle Installation", "correct": false, "because": "Qualität zählt"}, {"text": "Minimale Kosten", "correct": false, "because": "Nutzen wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) CRM automatisiert Prozesse. b) Es funktioniert ohne Internet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Cloud braucht Internet"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bereiche unterstützt ein CRM?', 5, '[{"text": "Marketing", "correct": true, "because": "Kampagnenmanagement"}, {"text": "Kundenservice", "correct": true, "because": "Support verbessern"}, {"text": "Hardwarewartung", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Nutzung unwichtig?', 3, '[{"text": "Datenqualität", "correct": false, "because": "Entscheidend für Erfolg"}, {"text": "Zugriffskontrolle", "correct": false, "because": "Schützt Daten"}, {"text": "Bildschirmdiagonale", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzt CRM den persönlichen Kontakt?', 3, '[{"text": "Nein", "correct": true, "because": "Unterstützt, nicht ersetzt"}, {"text": "Ja", "correct": false, "because": "Ergänzt Interaktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob CRM für Einzelnutzer geeignet ist?', 2, '[{"text": "Ja", "correct": true, "because": "Auch für Einzelpersonen"}, {"text": "Nein", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature ist entscheidend?', 4, '[{"text": "Kundenverfolgung", "correct": true, "because": "Zentralisiert Interaktionen"}, {"text": "Maximale Bandbreite", "correct": false, "because": "Netzwerkfaktor"}, {"text": "Grafikleistung", "correct": false, "because": "Irrelevant"}]');

