-- # Lernfeld 5: Cyberphysische Systeme > ## Testgetriebene Entwicklung > - Grundprinzipien > - Iterative Entwicklung

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die iterative Entwicklung ein zentrales Prinzip der testgetriebenen Entwicklung (TDD)?', 2, '[{"text": "Ja", "correct": true, "because": "TDD basiert auf kleinen, wiederholten Zyklen"}, {"text": "Nein", "correct": false, "because": "Iteration ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann TDD ohne iterative Entwicklung effektiv funktionieren?', 2, '[{"text": "Nein", "correct": true, "because": "Iterative Zyklen sind Kern von TDD"}, {"text": "Ja", "correct": false, "because": "Einmalige Durchläufe untypisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Erfordert die iterative Entwicklung in TDD, dass Tests vor jedem Iterationsschritt angepasst werden?', 2, '[{"text": "Nein", "correct": true, "because": "Tests wachsen mit neuen Anforderungen"}, {"text": "Ja", "correct": false, "because": "Nur bei Änderungen nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Können iterative Entwicklungsschritte in TDD die Softwarequalität kontinuierlich verbessern?', 2, '[{"text": "Ja", "correct": true, "because": "Jeder Zyklus optimiert Code"}, {"text": "Nein", "correct": false, "because": "Qualität steigt iterativ"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die iterative Entwicklung in TDD unabhängig von den Anforderungen?', 2, '[{"text": "Nein", "correct": true, "because": "Iterationen basieren auf Anforderungen"}, {"text": "Ja", "correct": false, "because": "Anforderungen leiten Zyklen"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die iterative Entwicklung in TDD?', 2, '[{"text": "Kontinuierliche Verbesserung des Codes", "correct": true, "because": "Jede Iteration optimiert"}, {"text": "Einmalige Fertigstellung", "correct": false, "because": "Nicht iterativ"}, {"text": "Reduzierung der Tests", "correct": false, "because": "Tests wachsen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der iterativen Entwicklung ist in TDD entscheidend?', 3, '[{"text": "Schrittweise Verfeinerung", "correct": true, "because": "Kleine Zyklen verbessern Code"}, {"text": "Langfristige Planung", "correct": false, "because": "Weniger TDD-Fokus"}, {"text": "Einmalige Testdurchführung", "correct": false, "because": "Kontinuierlich nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phase des TDD-Zyklus zeigt die iterative Natur am deutlichsten?', 2, '[{"text": "Red-Green-Refactor", "correct": true, "because": "Wiederholter Zyklus"}, {"text": "Nur Rot-Phase", "correct": false, "because": "Einzelner Schritt"}, {"text": "Nur Grün-Phase", "correct": false, "because": "Teil des Zyklus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug unterstützt die iterative Entwicklung in TDD am besten?', 2, '[{"text": "Test-Framework", "correct": true, "because": "Ermöglicht schnelle Zyklen"}, {"text": "Debugger", "correct": false, "because": "Fehleranalyse, nicht Iteration"}, {"text": "Texteditor", "correct": false, "because": "Nur Bearbeitung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Vorteil der iterativen Entwicklung in TDD ist am bedeutendsten?', 2, '[{"text": "Schnelle Anpassungsfähigkeit", "correct": true, "because": "Flexibilität bei Änderungen"}, {"text": "Einmalige Fertigstellung", "correct": false, "because": "Nicht iterativ"}, {"text": "Reduzierte Testanzahl", "correct": false, "because": "Tests wachsen"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale charakterisieren die iterative Entwicklung in TDD?', 4, '[{"text": "Kleine Entwicklungsschritte", "correct": true, "because": "Inkrementelle Verbesserung"}, {"text": "Kontinuierliche Tests", "correct": true, "because": "Jeder Schritt getestet"}, {"text": "Langfristige Planung", "correct": false, "because": "Kurzfristiger Fokus"}, {"text": "Feedback-Schleifen", "correct": true, "because": "Tests geben Rückmeldung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die iterative Entwicklung in TDD?', 3, '[{"text": "Schnelle Fehlererkennung", "correct": true, "because": "Tests in jedem Zyklus"}, {"text": "Flexibilität bei Änderungen", "correct": true, "because": "Iterative Anpassung"}, {"text": "Einmalige Durchführung", "correct": false, "because": "Nicht iterativ"}, {"text": "Verbesserte Qualität", "correct": true, "because": "Kontinuierliche Optimierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente der iterativen Entwicklung sind in TDD entscheidend?', 3, '[{"text": "Testgetriebene Zyklen", "correct": true, "because": "Red-Green-Refactor"}, {"text": "Inkrementelle Fortschritte", "correct": true, "because": "Schrittweise Verbesserung"}, {"text": "Statische Planung", "correct": false, "because": "Nicht TDD-typisch"}, {"text": "Kontinuierliche Validierung", "correct": true, "because": "Tests prüfen ständig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen kann die iterative Entwicklung in TDD mit sich bringen?', 4, '[{"text": "Hoher Testaufwand", "correct": true, "because": "Tests wachsen mit Iterationen"}, {"text": "Unklare Anforderungen", "correct": true, "because": "Schwierig ohne Klarheit"}, {"text": "Einmalige Fertigstellung", "correct": false, "because": "Nicht iterativ"}, {"text": "Kontinuierliche Anpassung", "correct": true, "because": "Flexibilität erfordert Mühe"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien unterstützen die iterative Entwicklung in TDD?', 3, '[{"text": "Schrittweise Verfeinerung", "correct": true, "because": "Inkrementelle Verbesserung"}, {"text": "Test vor Code", "correct": true, "because": "Leitet Iterationen"}, {"text": "Langfristige Planung", "correct": false, "because": "Kurzfristiger Fokus"}, {"text": "Kontinuierliches Feedback", "correct": true, "because": "Tests geben Rückmeldung"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Iterative Entwicklung in TDD basiert auf wiederholten Zyklen. b) TDD erfordert keine iterativen Schritte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zyklen zentral, Iteration essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Iterative Entwicklung in TDD verbessert die Qualität schrittweise. b) Jede Iteration erfordert neue Tests für bestehenden Code.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Qualität steigt, Tests nur bei Änderung"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Iterative Entwicklung in TDD ist unabhängig von Tests. b) Der Red-Green-Refactor-Zyklus ist iterativ.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Tests zentral, Zyklus wiederholt"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Iterative Entwicklung in TDD ermöglicht schnelle Anpassungen. b) TDD ohne Iterationen ist effektiver.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Anpassungen möglich, Iteration nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Iterative Entwicklung in TDD erhöht den Testaufwand. b) Kontinuierliches Feedback ist ein Vorteil der Iteration.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "Tests wachsen, Feedback zentral"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist auch richtig"}, {"text": "Beides falsch", "correct": false, "because": "Beides richtig"}]');

