INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist eine Analyse bestehender Software immer notwendig, bevor neue Funktionen implementiert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig vom Projektumfang, manchmal ausreichend dokumentiert"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend, wenn Anforderungen klar sind"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Analyse bestehender Software ohne Zugriff auf den Quellcode vollständig sein?', 2, '[{"text": "Nein", "correct": true, "because": "Ohne Quellcode fehlen interne Details"}, {"text": "Ja", "correct": false, "because": "Externe Tests liefern nur Teilinformationen"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen bei der Analyse bestehender Software alle Funktionen auf ihre Effizienz geprüft werden?', 2, '[{"text": "Nein", "correct": true, "because": "Fokus liegt auf Relevanz für das Projekt"}, {"text": "Ja", "correct": false, "because": "Effizienzprüfung ist oft optional"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Analyse bestehender Software ausschließlich darauf ausgerichtet, Fehler zu finden?', 2, '[{"text": "Nein", "correct": true, "because": "Ziel ist Verständnis von Struktur und Funktion"}, {"text": "Ja", "correct": false, "because": "Fehlerfindung ist nur ein Teilaspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine Analyse bestehender Software die Notwendigkeit einer Neuentwicklung überflüssig machen?', 2, '[{"text": "Nein", "correct": true, "because": "Analyse liefert Einsichten, ersetzt aber keine Entscheidung"}, {"text": "Ja", "correct": false, "because": "Neuentwicklung hängt von weiteren Faktoren ab"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt ist bei der Analyse bestehender Software am wichtigsten, um Kompatibilität mit neuen Anforderungen zu prüfen?', 3, '[{"text": "Schnittstellen und Datenformate", "correct": true, "because": "Definiert Integration und Interaktion"}, {"text": "Visuelle Gestaltung", "correct": false, "because": "Sekundär für Kompatibilität"}, {"text": "Entwicklungszeit der Software", "correct": false, "because": "Historie ist irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug ist am besten geeignet, um die Struktur bestehender Software zu verstehen?', 2, '[{"text": "Statische Code-Analyse-Tools", "correct": true, "because": "Zeigen Abhängigkeiten und Architektur"}, {"text": "Texteditor", "correct": false, "because": "Fehlt Übersicht und Analysefunktion"}, {"text": "Leistungsüberwachung", "correct": false, "because": "Fokussiert Laufzeit, nicht Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Analyse bestehender Software primär bei einer Systemerweiterung?', 3, '[{"text": "Identifikation von Wiederverwendbarkeit", "correct": true, "because": "Vermeidet doppelte Arbeit"}, {"text": "Maximierung der Benutzerfreundlichkeit", "correct": false, "because": "Sekundär in dieser Phase"}, {"text": "Reduktion der Wartungskosten", "correct": false, "because": "Folge, nicht Hauptziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor erschwert die Analyse bestehender Software am meisten?', 3, '[{"text": "Fehlende Dokumentation", "correct": true, "because": "Macht Verständnis zeitaufwändig"}, {"text": "Hohe Anzahl an Funktionen", "correct": false, "because": "Komplexität ist überwindbar"}, {"text": "Bekannte Programmiersprache", "correct": false, "because": "Erleichtert eher"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft am effektivsten, versteckte Abhängigkeiten in bestehender Software zu erkennen?', 2, '[{"text": "Dynamische Laufzeitanalyse", "correct": true, "because": "Zeigt Interaktionen im Betrieb"}, {"text": "Manuelle Codeinspektion", "correct": false, "because": "Zeitaufwändig und fehleranfällig"}, {"text": "Nutzerbefragung", "correct": false, "because": "Liefert keine technischen Details"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente sollten bei der Analyse bestehender Software untersucht werden?', 4, '[{"text": "Code-Struktur", "correct": true, "because": "Zeigt Architektur und Modularität"}, {"text": "Datenfluss", "correct": true, "because": "Klärt Verarbeitung und Speicherung"}, {"text": "Farbschema der GUI", "correct": false, "because": "Irrelevant für Funktionalität"}, {"text": "Schnittstellen", "correct": true, "because": "Definiert Integration"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden sind für die Analyse bestehender Software geeignet?', 3, '[{"text": "Reverse Engineering", "correct": true, "because": "Rekonstruiert Struktur ohne Dokumentation"}, {"text": "Leistungstests", "correct": true, "because": "Prüft Effizienz und Schwachstellen"}, {"text": "Kosten-Nutzen-Analyse", "correct": false, "because": "Wirtschaftlich, nicht technisch"}, {"text": "Code-Reviews", "correct": true, "because": "Liefert detaillierte Einsichten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können bei der Analyse bestehender Software auftreten?', 4, '[{"text": "Veraltete Technologien", "correct": true, "because": "Erschwert Verständnis und Integration"}, {"text": "Unklare Abhängigkeiten", "correct": true, "because": "Verbirgt Interaktionen"}, {"text": "Schnelle Analysezeit", "correct": false, "because": "Zeit ist kein Problem"}, {"text": "Mangelnde Testbarkeit", "correct": true, "because": "Kompliziert Validierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Informationen liefert die Analyse bestehender Software für ein Projekt?', 3, '[{"text": "Technische Einschränkungen", "correct": true, "because": "Zeigt Grenzen der Erweiterung"}, {"text": "Wiederverwendbare Komponenten", "correct": true, "because": "Fördert Effizienz"}, {"text": "Zukünftige Markttrends", "correct": false, "because": "Nicht Teil der Analyse"}, {"text": "Bestehende Fehler", "correct": true, "because": "Wichtig für Verbesserungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen können bei der Analyse bestehender Software ohne Quellcode entstehen?', 3, '[{"text": "Eingeschränkte Sicht auf Logik", "correct": true, "because": "Interna bleiben verborgen"}, {"text": "Fehlende Performance-Daten", "correct": false, "because": "Laufzeit kann getestet werden"}, {"text": "Schwierigkeiten bei Funktionsprüfung", "correct": true, "because": "Verhalten schwer nachvollziehbar"}, {"text": "Unklarer Entwicklungsaufwand", "correct": true, "because": "Abschätzung wird kompliziert"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Analyse bestehender Software dient nur der Fehlerbehebung. b) Sie kann die Basis für eine Modernisierung bilden.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Fehler sind ein Aspekt, Modernisierung ein Hauptzweck"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist zu eng gefasst"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Eine Analyse bestehender Software erfordert immer Zugriff auf den Quellcode. b) Sie kann Schwachstellen in der Architektur aufdecken.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Quellcode hilft, ist aber nicht zwingend; Schwachstellen werden sichtbar"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Analyse bestehender Software ist nur bei Neuentwicklungen relevant. b) Sie hilft, Integrationspunkte zu identifizieren.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Relevanz ist breiter, Integration ist ein Ziel"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Eine Analyse bestehender Software kann ohne Tests durchgeführt werden. b) Sie sollte die Dokumentation der Software ersetzen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tests sind optional, Dokumentation wird ergänzt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Analyse bestehender Software kann die Wiederverwendbarkeit von Modulen fördern. b) Sie ist immer schneller als eine Neuentwicklung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Wiederverwendung wird unterstützt, Zeit hängt vom Umfang ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht garantiert"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

