INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Einhaltung der ISO 9241 zwingend erforderlich, um ein ergonomisches Softwaredesign zu gewährleisten?', 2, '[{"text": "Nein", "correct": true, "because": "ISO 9241 bietet Richtlinien, ist aber nicht gesetzlich bindend"}, {"text": "Ja", "correct": false, "because": "Ergonomie kann auch ohne Norm erreicht werden"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle WCAG-Richtlinien erfüllt werden, um ein System als barrierefrei zu bezeichnen?', 2, '[{"text": "Nein", "correct": true, "because": "Stufen (A, AA, AAA) erlauben unterschiedliche Konformitätsgrade"}, {"text": "Ja", "correct": false, "because": "Teilweise Erfüllung ist möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die ISO 9241 auch auf Hardware-Komponenten angewendet werden?', 2, '[{"text": "Ja", "correct": true, "because": "Sie umfasst ergonomische Aspekte von Eingabegeräten"}, {"text": "Nein", "correct": false, "because": "Anwendung ist nicht auf Software beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Garantieren die WCAG-Richtlinien automatisch eine hohe Benutzerfreundlichkeit?', 2, '[{"text": "Nein", "correct": true, "because": "Barrierefreiheit und Usability sind nicht identisch"}, {"text": "Ja", "correct": false, "because": "WCAG fokussiert Zugänglichkeit, nicht Komfort"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die ISO 9241 ausschließlich für die Gestaltung grafischer Benutzeroberflächen relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Sie umfasst auch Arbeitsumgebung und Prozesse"}, {"text": "Ja", "correct": false, "because": "Anwendungsbereich ist breiter"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip der WCAG zielt primär darauf ab, Inhalte für verschiedene Sinne zugänglich zu machen?', 3, '[{"text": "Wahrnehmbarkeit", "correct": true, "because": "Es fordert Alternativen wie Text für Bilder"}, {"text": "Robustheit", "correct": false, "because": "Robustheit zielt auf technische Kompatibilität"}, {"text": "Bedienbarkeit", "correct": false, "because": "Fokus liegt auf Navigation"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der ISO 9241 ist entscheidend für die Bewertung der Effizienz einer Benutzeroberfläche?', 2, '[{"text": "Zielerreichung mit minimalem Aufwand", "correct": true, "because": "Effizienz misst Aufwand im Verhältnis zum Ergebnis"}, {"text": "Maximale Anzahl an Funktionen", "correct": false, "because": "Quantität ist nicht maßgeblich"}, {"text": "Visuelle Ästhetik", "correct": false, "because": "Ästhetik ist sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche WCAG-Stufe wird häufig als Mindestanforderung für öffentliche Webseiten empfohlen?', 3, '[{"text": "AA", "correct": true, "because": "AA bietet ein gutes Gleichgewicht zwischen Aufwand und Zugänglichkeit"}, {"text": "A", "correct": false, "because": "A ist minimal, oft unzureichend"}, {"text": "AAA", "correct": false, "because": "AAA ist maximal, aber selten umgesetzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die ISO 9241 primär bei der Softwareentwicklung?', 2, '[{"text": "Verbesserung der Nutzerzufriedenheit", "correct": true, "because": "Fokus liegt auf Ergonomie und Usability"}, {"text": "Erhöhung der Entwicklungsgeschwindigkeit", "correct": false, "because": "Zeit ist kein Hauptziel"}, {"text": "Reduktion der Hardwarekosten", "correct": false, "because": "Kosten sind nicht zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anforderung der WCAG ist am schwierigsten bei dynamischen Inhalten zu erfüllen?', 3, '[{"text": "Bedienbarkeit durch Tastatur", "correct": true, "because": "Dynamische Elemente erfordern oft komplexe Interaktionen"}, {"text": "Textalternativen für Bilder", "correct": false, "because": "Statische Inhalte sind simpler"}, {"text": "Farbkontrast", "correct": false, "because": "Kontrast ist unabhängig von Dynamik"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien gehören zu den WCAG-Richtlinien?', 4, '[{"text": "Wahrnehmbarkeit", "correct": true, "because": "Inhalte müssen zugänglich sein"}, {"text": "Bedienbarkeit", "correct": true, "because": "Interaktion muss möglich sein"}, {"text": "Maximale Performance", "correct": false, "because": "Performance ist nicht Teil der WCAG"}, {"text": "Verständlichkeit", "correct": true, "because": "Inhalte müssen klar sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte der ISO 9241 sind für die Ergonomie einer Benutzeroberfläche relevant?', 3, '[{"text": "Effektivität", "correct": true, "because": "Misst Zielerreichung"}, {"text": "Effizienz", "correct": true, "because": "Misst Aufwand"}, {"text": "Anzahl der Funktionen", "correct": false, "because": "Quantität ist nicht entscheidend"}, {"text": "Zufriedenheit", "correct": true, "because": "Nutzerkomfort ist zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anforderungen der WCAG unterstützen Sehbehinderte Nutzer?', 4, '[{"text": "Textalternativen für Nicht-Text-Inhalte", "correct": true, "because": "Ermöglicht Screenreader-Nutzung"}, {"text": "Ausreichender Farbkontrast", "correct": true, "because": "Verbessert Sichtbarkeit"}, {"text": "Schnelle Ladezeiten", "correct": false, "because": "Performance ist nicht WCAG-Fokus"}, {"text": "Tastaturnavigation", "correct": true, "because": "Unterstützt blinde Nutzer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente der ISO 9241 können bei der Gestaltung eines Arbeitsplatzes berücksichtigt werden?', 3, '[{"text": "Bildschirmgestaltung", "correct": true, "because": "Teil der ergonomischen Anforderungen"}, {"text": "Beleuchtungsverhältnisse", "correct": true, "because": "Beeinflusst Nutzerkomfort"}, {"text": "Softwarelizenzierung", "correct": false, "because": "Nicht ergonomisch relevant"}, {"text": "Eingabegeräte", "correct": true, "because": "Ergonomie von Hardware wird behandelt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen können bei der Umsetzung der WCAG auftreten?', 3, '[{"text": "Hoher Entwicklungsaufwand", "correct": true, "because": "Anpassungen erfordern Zeit"}, {"text": "Kompatibilität mit älteren Systemen", "correct": true, "because": "Technische Einschränkungen möglich"}, {"text": "Automatische Codegenerierung", "correct": false, "because": "Nicht zentrales Problem"}, {"text": "Kollision mit Designwünschen", "correct": true, "because": "Ästhetik kann Konflikte erzeugen"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die ISO 9241 definiert verbindliche gesetzliche Vorgaben. b) Die WCAG ist speziell für Webinhalte entwickelt worden.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "ISO 9241 sind Richtlinien, WCAG ist webfokussiert"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die WCAG-Stufe AAA ist für die meisten Projekte realistisch umsetzbar. b) Die ISO 9241 betrachtet die Zufriedenheit der Nutzer als Messgröße.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "AAA ist oft zu aufwändig, Zufriedenheit ist ISO-Fokus"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die WCAG fordert, dass alle Inhalte ausschließlich per Maus bedienbar sind. b) Die ISO 9241 kann bei der Gestaltung von Dialogsystemen helfen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "WCAG fordert Tastaturzugang, ISO 9241 ist anwendbar"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die ISO 9241 legt Mindestanforderungen für Farbkontraste fest. b) Die WCAG unterstützt die Entwicklung inklusiver Software.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "ISO 9241 ist allgemeiner, WCAG fördert Inklusion"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die WCAG gilt auch für native Mobile-Apps ohne Anpassung. b) Die ISO 9241 behandelt ergonomische Anforderungen an Arbeitsumgebungen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "WCAG ist webfokussiert, ISO 9241 umfasst Umgebung"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

