INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Abklärung rechtlicher Rahmenbedingungen immer erforderlich, bevor ein IT-Projekt gestartet wird?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig vom Projektumfang, nicht immer zwingend"}, {"text": "Ja", "correct": false, "because": "Erforderlichkeit variiert je nach Kontext"}]'),
('00000000-0000-0000-0000-000000000000', 'Können rechtliche Rahmenbedingungen die Wahl der Technologie in einem Projekt vollständig bestimmen?', 2, '[{"text": "Nein", "correct": true, "because": "Technologie wird auch von anderen Faktoren beeinflusst"}, {"text": "Ja", "correct": false, "because": "Rechtliche Vorgaben sind nur ein Aspekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen rechtliche Rahmenbedingungen nur für öffentliche Projekte abgeklärt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Auch private Projekte unterliegen Gesetzen"}, {"text": "Ja", "correct": false, "because": "Rechtliche Vorgaben gelten allgemein"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Abklärung rechtlicher Rahmenbedingungen ohne juristische Expertise unmöglich?', 2, '[{"text": "Nein", "correct": true, "because": "Grundkenntnisse können ausreichen, Expertise ist aber hilfreich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Nichtbeachtung rechtlicher Rahmenbedingungen die Projektkosten unwesentlich beeinflussen?', 2, '[{"text": "Nein", "correct": true, "because": "Rechtsverstöße können hohe Strafen verursachen"}, {"text": "Ja", "correct": false, "because": "Kostenwirkung ist oft signifikant"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher rechtliche Aspekt muss bei einem IT-Projekt mit personenbezogenen Daten primär abgeklärt werden?', 3, '[{"text": "Datenschutz (z. B. DSGVO)", "correct": true, "because": "Regelt Umgang mit personenbezogenen Daten"}, {"text": "Urheberrecht", "correct": false, "because": "Sekundär bei Datenprojekten"}, {"text": "Vertragsrecht", "correct": false, "because": "Wichtig, aber nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz ist am relevantesten für die Barrierefreiheit öffentlicher Webseiten in Deutschland?', 2, '[{"text": "Behindertengleichstellungsgesetz (BGG)", "correct": true, "because": "Fordert Barrierefreiheit öffentlicher Stellen"}, {"text": "Telemediengesetz (TMG)", "correct": false, "because": "Regelt andere Aspekte"}, {"text": "Bürgerliches Gesetzbuch (BGB)", "correct": false, "because": "Allgemeines Zivilrecht"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor erschwert die Abklärung rechtlicher Rahmenbedingungen am meisten?', 3, '[{"text": "Unterschiedliche nationale Gesetze", "correct": true, "because": "Internationale Projekte sind komplex"}, {"text": "Zu schnelle Gesetzesänderungen", "correct": false, "because": "Änderungen sind überschaubar"}, {"text": "Fehlende technische Dokumentation", "correct": false, "because": "Nicht primär rechtlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode ist am effektivsten, um rechtliche Rahmenbedingungen frühzeitig abzuklären?', 2, '[{"text": "Konsultation eines Rechtsberaters", "correct": true, "because": "Bietet präzise Expertise"}, {"text": "Analyse von Projektzielen", "correct": false, "because": "Liefert keinen rechtlichen Input"}, {"text": "Vergleich mit früheren Projekten", "correct": false, "because": "Kontextabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Risiko entsteht durch eine unzureichende Abklärung rechtlicher Rahmenbedingungen?', 3, '[{"text": "Rechtliche Sanktionen", "correct": true, "because": " Verstöße können Strafen nach sich ziehen"}, {"text": "Schnellere Projektumsetzung", "correct": false, "because": "Gegenteil ist der Fall"}, {"text": "Geringere Entwicklungskosten", "correct": false, "because": "Kosten können steigen"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche rechtlichen Bereiche sollten bei einem IT-Projekt abgeklärt werden?', 4, '[{"text": "Datenschutzrecht", "correct": true, "because": "Schützt personenbezogene Daten"}, {"text": "Urheberrecht", "correct": true, "because": "Regelt Nutzung von Inhalten"}, {"text": "Verkehrsrecht", "correct": false, "because": "Irrelevant für IT-Projekte"}, {"text": "Vertragsrecht", "correct": true, "because": "Definiert Kundenbeziehungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konsequenzen kann eine fehlende Abklärung rechtlicher Rahmenbedingungen haben?', 3, '[{"text": "Bußgelder", "correct": true, "because": "Verstöße werden sanktioniert"}, {"text": "Projektverzögerungen", "correct": true, "because": "Nachtragungen kosten Zeit"}, {"text": "Schnellere Markteinführung", "correct": false, "because": "Gegenteil ist wahrscheinlich"}, {"text": "Rechtliche Streitigkeiten", "correct": true, "because": "Unklarheiten führen zu Konflikten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Quellen helfen bei der Abklärung rechtlicher Rahmenbedingungen?', 4, '[{"text": "Gesetzestexte", "correct": true, "because": "Primärquelle für Vorgaben"}, {"text": "Branchenspezifische Richtlinien", "correct": true, "because": "Ergänzen gesetzliche Regeln"}, {"text": "Technische Dokumentation", "correct": false, "because": "Nicht rechtlich relevant"}, {"text": "Rechtsberatung", "correct": true, "because": "Bietet Interpretation"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte der DSGVO müssen bei einem IT-Projekt abgeklärt werden?', 3, '[{"text": "Datenverarbeitungszwecke", "correct": true, "because": "Müssen rechtmäßig sein"}, {"text": "Nutzerrechte (z. B. Löschung)", "correct": true, "because": "Pflichten des Verantwortlichen"}, {"text": "Maximale Serverkapazität", "correct": false, "because": "Technisch, nicht rechtlich"}, {"text": "Einwilligung der Nutzer", "correct": true, "because": "Basis für Datenverarbeitung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gründliche Abklärung rechtlicher Rahmenbedingungen?', 3, '[{"text": "Rechtssicherheit", "correct": true, "because": "Minimiert Verstöße"}, {"text": "Klarheit für Planung", "correct": true, "because": "Definiert Grenzen"}, {"text": "Automatische Kostensenkung", "correct": false, "because": "Kosten hängen von Umsetzung ab"}, {"text": "Vertrauen der Stakeholder", "correct": true, "because": "Zeigt Professionalität"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Rechtliche Rahmenbedingungen betreffen nur internationale Projekte. b) Sie können die Projektplanung beeinflussen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Alle Projekte sind betroffen, Planung wird angepasst"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Abklärung rechtlicher Rahmenbedingungen kann die Wahl der Programmiersprache bestimmen. b) Sie ist nur für Projekte mit personenbezogenen Daten relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Recht kann Technik beeinflussen, Relevanz ist breiter"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Rechtliche Rahmenbedingungen sollten erst nach Projektstart geklärt werden. b) Sie können Haftungsrisiken minimieren.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Klärung sollte früh sein, Haftung wird reduziert"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Abklärung rechtlicher Rahmenbedingungen ist eine rein technische Aufgabe. b) Sie erfordert oft die Analyse von Gesetzen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Nicht technisch, Gesetze sind zentral"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Rechtliche Rahmenbedingungen können die Projektziele verändern. b) Sie sind nur für den Kunden relevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ziele können angepasst werden, Relevanz ist allgemein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

