INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Dokumentation von Erwartungen ohne direkten Kundenkontakt immer unzureichend?', 2, '[{"text": "Nein", "correct": true, "because": "Vorhandene Dokumente oder Vorgaben können ausreichen"}, {"text": "Ja", "correct": false, "because": "Kontakt ist hilfreich, aber nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle Erwartungen eines Kunden zwingend schriftlich dokumentiert werden, um verbindlich zu sein?', 2, '[{"text": "Nein", "correct": true, "because": "Mündliche Absprachen können ebenfalls bindend sein"}, {"text": "Ja", "correct": false, "because": "Schriftlichkeit ist ideal, aber nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Dokumentation von Erwartungen ohne technische Details vollständig sein?', 2, '[{"text": "Ja", "correct": true, "because": "Fokus liegt auf Zielen, Details folgen später"}, {"text": "Nein", "correct": false, "because": "Technische Details sind oft sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Dokumentation von Erwartungen nur dann nützlich, wenn sie alle Eventualitäten abdeckt?', 2, '[{"text": "Nein", "correct": true, "because": "Kernanforderungen reichen für Verständnis"}, {"text": "Ja", "correct": false, "because": "Vollständigkeit ist unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Können unklare Erwartungen in der Dokumentation spätere Missverständnisse vollständig vermeiden?', 2, '[{"text": "Nein", "correct": true, "because": "Unklarheit führt zu Interpretationsproblemen"}, {"text": "Ja", "correct": false, "because": "Klarheit ist essenziell"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Element ist bei der Dokumentation von Erwartungen am wichtigsten, um Missverständnisse zu vermeiden?', 3, '[{"text": "Klarheit der Formulierungen", "correct": true, "because": "Präzision schafft einheitliches Verständnis"}, {"text": "Maximale Detailtiefe", "correct": false, "because": "Überladung kann verwirren"}, {"text": "Technische Spezifikationen", "correct": false, "because": "Sekundär in dieser Phase"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode hilft am besten, die Erwartungen eines Kunden zu dokumentieren?', 2, '[{"text": "Strukturierte Interviews", "correct": true, "because": "Fördert direkte Abstimmung"}, {"text": "Automatische Protokollierung", "correct": false, "because": "Fehlt Kontext"}, {"text": "Vorgefertigte Vorlagen", "correct": false, "because": "Weniger individuell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Erwartungsdokumentation ist entscheidend, um die Projektziele abzusichern?', 3, '[{"text": "Abgestimmte Prioritäten", "correct": true, "because": "Klärt Fokus und Reihenfolge"}, {"text": "Detaillierte Zeitpläne", "correct": false, "because": "Folgt der Dokumentation"}, {"text": "Teamzuweisungen", "correct": false, "because": "Interne Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Fehler kann die Dokumentation von Erwartungen am stärksten beeinträchtigen?', 3, '[{"text": "Unklare Begriffe", "correct": true, "because": "Führt zu unterschiedlichen Interpretationen"}, {"text": "Zu viele technische Details", "correct": false, "because": "Stört nicht primär"}, {"text": "Kurze Beschreibungen", "correct": false, "because": "Kürze kann Vorteil sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Dokumentation von Erwartungen?', 2, '[{"text": "Einheitliches Verständnis schaffen", "correct": true, "because": "Basis für Zusammenarbeit"}, {"text": "Technische Umsetzung festlegen", "correct": false, "because": "Folgt später"}, {"text": "Kosten sofort kalkulieren", "correct": false, "because": "Sekundäres Ziel"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Elemente sollten in der Dokumentation von Erwartungen enthalten sein?', 4, '[{"text": "Projektziele", "correct": true, "because": "Definiert den Zweck"}, {"text": "Akzeptanzkriterien", "correct": true, "because": "Macht Erfolg messbar"}, {"text": "Detaillierte Codebeispiele", "correct": false, "because": "Zu früh für Technik"}, {"text": "Prioritäten der Anforderungen", "correct": true, "because": "Leitet Umsetzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methoden unterstützen die Dokumentation von Erwartungen effektiv?', 3, '[{"text": "Workshops mit Stakeholdern", "correct": true, "because": "Fördert Diskussion"}, {"text": "Fragebögen", "correct": true, "because": "Erfasst gezielte Antworten"}, {"text": "Analyse von Markttrends", "correct": false, "because": "Extern und nicht kundenbezogen"}, {"text": "Protokollierung von Meetings", "correct": true, "because": "Sichert Absprachen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken entstehen durch eine unzureichende Dokumentation von Erwartungen?', 4, '[{"text": "Missverständnisse zwischen Kunde und Team", "correct": true, "because": "Fehlende Klarheit stört"}, {"text": "Verzögerungen im Projektverlauf", "correct": true, "because": "Unklare Ziele bremsen"}, {"text": "Schnellere Umsetzung", "correct": false, "because": "Gegenteil ist der Fall"}, {"text": "Abweichung vom Kundenwunsch", "correct": true, "because": "Fehlende Basis führt zu Fehlern"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gut dokumentierte Erwartungshaltung?', 3, '[{"text": "Klarheit über Projektumfang", "correct": true, "because": "Definiert Grenzen"}, {"text": "Grundlage für Planung", "correct": true, "because": "Ermöglicht Struktur"}, {"text": "Automatische Kostenreduktion", "correct": false, "because": "Kosten hängen von Umsetzung ab"}, {"text": "Verbesserte Kommunikation", "correct": true, "because": "Einheitliches Verständnis"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen können bei der Dokumentation von Erwartungen auftreten?', 3, '[{"text": "Unklare Kundenangaben", "correct": true, "because": "Erschwert Präzision"}, {"text": "Widersprüchliche Anforderungen", "correct": true, "because": "Müssen geklärt werden"}, {"text": "Schnelle Fertigstellung", "correct": false, "because": "Geschwindigkeit ist kein Problem"}, {"text": "Mangelnde Stakeholder-Einbindung", "correct": true, "because": "Fehlende Perspektiven"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Die Dokumentation von Erwartungen dient nur der internen Planung. b) Sie sollte mit dem Kunden abgestimmt werden.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Nicht nur intern, Abstimmung ist zentral"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Erwartungen müssen immer technisch detailliert dokumentiert werden. b) Eine klare Dokumentation reduziert Konflikte.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Technische Details sind optional, Klarheit hilft"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Dokumentation von Erwartungen kann ohne Priorisierung auskommen. b) Sie bildet die Grundlage für Akzeptanztests.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Priorisierung ist hilfreich, Tests basieren darauf"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist nicht ideal"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Eine gute Dokumentation von Erwartungen verhindert alle Änderungen im Projekt. b) Sie sollte verständlich für alle Stakeholder sein.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Änderungen sind möglich, Verständlichkeit ist Ziel"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Dokumentation von Erwartungen ist nur für den Kunden relevant. b) Sie kann als Referenz für den Projektfortschritt dienen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Nicht nur für Kunden, Fortschritt wird gemessen"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]');

