INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist die Risikobewertung immer eine rein quantitative Analyse?', 2, '[{"text": "Nein", "correct": true, "because": "Qualitative Ansätze sind ebenfalls üblich"}, {"text": "Ja", "correct": false, "because": "Bewertung kann subjektiv sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine Risikobewertung ohne vorherige Risikoidentifikation durchgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Ohne Identifikation fehlt die Grundlage"}, {"text": "Ja", "correct": false, "because": "Bewertung braucht definierte Risiken"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen alle Risiken in einer Risikobewertung gleich gewichtet werden?', 2, '[{"text": "Nein", "correct": true, "because": "Gewichtung hängt von Auswirkung und Wahrscheinlichkeit ab"}, {"text": "Ja", "correct": false, "because": "Ungleichheit ist Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist eine Risikobewertung nur dann sinnvoll, wenn alle Risiken vollständig bekannt sind?', 2, '[{"text": "No", "correct": true, "because": "Auch bei Unsicherheit nützlich"}, {"text": "Ja", "correct": false, "because": "Teilwissen reicht für Priorisierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Risiken in einer Risikobewertung ohne Maßnahmenplanung priorisiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Priorisierung ist unabhängig von Maßnahmen"}, {"text": "Nein", "correct": false, "because": "Maßnahmen folgen der Bewertung"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium ist entscheidend, um die Priorität eines Risikos in einer Risikobewertung festzulegen?', 3, '[{"text": "Produkt aus Wahrscheinlichkeit und Auswirkung", "correct": true, "because": "Kombiniert Eintritt und Schaden"}, {"text": "Kosten der Vermeidung", "correct": false, "because": "Sekundär zur Bewertung"}, {"text": "Zeitpunkt des Auftretens", "correct": false, "because": "Weniger maßgeblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird am häufigsten für eine qualitative Risikobewertung verwendet?', 2, '[{"text": "Risikomatrix", "correct": true, "because": "Visualisiert Risiken einfach"}, {"text": "Monte-Carlo-Simulation", "correct": false, "because": "Quantitativ und komplex"}, {"text": "Break-Even-Analyse", "correct": false, "because": "Wirtschaftlich, nicht risikobezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Aspekt der Risikobewertung wird oft unterschätzt?', 3, '[{"text": "Subjektive Einschätzungen", "correct": true, "because": "Beeinflussen Ergebnisse stark"}, {"text": "Technische Dokumentation", "correct": false, "because": "Nicht primär relevant"}, {"text": "Kostenabschätzung", "correct": false, "because": "Folgt der Bewertung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Fehler kann eine Risikobewertung am stärksten verfälschen?', 2, '[{"text": "Fehlende Objektivität", "correct": true, "because": "Subjektivität verzerrt Prioritäten"}, {"text": "Zu viele Risiken", "correct": false, "because": "Quantität ist kein Fehler"}, {"text": "Schnelle Durchführung", "correct": false, "because": "Geschwindigkeit ist sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist das Hauptziel der Risikobewertung in einem Projekt?', 3, '[{"text": "Priorisierung der Risiken", "correct": true, "because": "Ermöglicht gezielte Maßnahmen"}, {"text": "Eliminierung aller Risiken", "correct": false, "because": "Unrealistisch"}, {"text": "Kostenreduktion", "correct": false, "because": "Folge, nicht Ziel"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren sollten in einer Risikobewertung berücksichtigt werden?', 4, '[{"text": "Eintrittswahrscheinlichkeit", "correct": true, "because": "Bestimmt Häufigkeit"}, {"text": "Schwere der Auswirkungen", "correct": true, "because": "Misst Schaden"}, {"text": "Anzahl der Teammitglieder", "correct": false, "because": "Kein Risikofaktor"}, {"text": "Erkennbarkeit des Risikos", "correct": true, "because": "Beeinflusst Prävention"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Ansätze können für eine Risikobewertung genutzt werden?', 3, '[{"text": "Qualitative Bewertung", "correct": true, "because": "Nutzt Skalen wie hoch/mittel/niedrig"}, {"text": "Quantitative Bewertung", "correct": true, "because": "Basiert auf Zahlen"}, {"text": "Maximierung der Funktionen", "correct": false, "because": "Kein Bewertungsansatz"}, {"text": "Risikomatrix", "correct": true, "because": "Kombiniert Wahrscheinlichkeit und Auswirkung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen können bei der Risikobewertung auftreten?', 4, '[{"text": "Mangelnde Datenbasis", "correct": true, "because": "Erschwert Prognosen"}, {"text": "Subjektive Einschätzungen", "correct": true, "because": "Verzerren Ergebnisse"}, {"text": "Schnelle Berechnung", "correct": false, "because": "Kein Hindernis"}, {"text": "Unklare Kriterien", "correct": true, "because": "Führt zu Inkonsistenz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gründliche Risikobewertung?', 3, '[{"text": "Klare Priorisierung", "correct": true, "because": "Fokussiert auf kritische Risiken"}, {"text": "Reduzierte Unsicherheit", "correct": true, "because": "Schafft Übersicht"}, {"text": "Automatische Problemlösung", "correct": false, "because": "Lösung folgt separat"}, {"text": "Bessere Entscheidungsgrundlage", "correct": true, "because": "Unterstützt Planung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente beeinflussen die Genauigkeit einer Risikobewertung?', 3, '[{"text": "Qualität der Informationen", "correct": true, "because": "Ungenaue Daten verfälschen"}, {"text": "Expertise der Beteiligten", "correct": true, "because": "Erfahrung verbessert Einschätzung"}, {"text": "Projektlaufzeit", "correct": false, "because": "Indirekter Einfluss"}, {"text": "Konsistenz der Methode", "correct": true, "because": "Sichert Vergleichbarkeit"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Eine Risikobewertung muss immer numerische Werte enthalten. b) Sie hilft, Ressourcen effizient einzusetzen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Numerik ist optional, Effizienz wird gesteigert"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die Risikobewertung kann ohne Stakeholder-Beteiligung objektiv sein. b) Sie sollte regelmäßig überprüft werden.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Stakeholder erhöhen Objektivität, Aktualität ist wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist nicht ideal"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine Risikobewertung garantiert die Vermeidung aller Probleme. b) Sie kann qualitative und quantitative Methoden kombinieren.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Vermeidung ist nicht garantiert, Kombination ist möglich"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Die Risikobewertung ist nur für technische Risiken relevant. b) Sie unterstützt die Priorisierung von Maßnahmen.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Risiken sind vielfältig, Maßnahmen werden fokussiert"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine Risikobewertung kann durch unklare Kriterien ungenau werden. b) Sie ist nur in der Planungsphase nützlich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Klarheit ist essenziell, Nutzen ist fortlaufend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

