-- Technik: Netzwerk - Netzwerkprotokolle - Ethernet
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Ethernet ein weit verbreitetes Netzwerkprotokoll?', 2, '[{"text": "Ja", "correct": true, "because": "Standard in LANs"}, {"text": "Nein", "correct": false, "because": "Es ist zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt Ethernet?', 3, '[{"text": "Datenübertragung in lokalen Netzwerken", "correct": true, "because": "Verbinden Geräte"}, {"text": "Daten dauerhaft speichern", "correct": false, "because": "Festplattenaufgabe"}, {"text": "Grafik darstellen", "correct": false, "because": "GPU-Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ethernet nutzt kabelgebundene Verbindungen. b) Es ist ausschließlich drahtlos.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, kabelbasiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten sind für Ethernet typisch?', 4, '[{"text": "Netzwerkkabel", "correct": true, "because": "Verbindung"}, {"text": "Unklare Protokolle", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Switches", "correct": true, "because": "Verbinden Geräte"}, {"text": "Router", "correct": true, "because": "Leiten Daten"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Netzwerk ohne Ethernet funktionieren?', 2, '[{"text": "Ja", "correct": true, "because": "Andere Protokolle möglich"}, {"text": "Nein", "correct": false, "because": "Flexibilität gegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt Ethernet im Netzwerk?', 3, '[{"text": "Datenübertragung zwischen Geräten", "correct": true, "because": "Verbindet LAN"}, {"text": "Nur Internetzugang", "correct": false, "because": "Routeraufgabe"}, {"text": "Datenverarbeitung", "correct": false, "because": "CPU-Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Ethernet nur für Unternehmensnetzwerke geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Auch privat genutzt"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Ethernet-Switch?', 3, '[{"text": "Datenpakete zwischen Geräten leiten", "correct": true, "because": "Verbindet Netzwerk"}, {"text": "Daten speichern", "correct": false, "because": "Festplattenaufgabe"}, {"text": "Grafik rendern", "correct": false, "because": "GPU-Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ethernet nutzt MAC-Adressen. b) Es ist ein drahtloses Protokoll.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, kabelgebunden"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Ethernet in einem LAN?', 3, '[{"text": "Keine kabelgebundene Verbindung", "correct": true, "because": "Andere Protokolle nötig"}, {"text": "Netzwerk wird schneller", "correct": false, "because": "Eher Einschränkung"}, {"text": "Datenverlust", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Ethernet ohne Netzwerkkabel funktionieren?', 2, '[{"text": "Nein", "correct": true, "because": "Kabelgebunden"}, {"text": "Ja", "correct": false, "because": "Wi-Fi ist anderes Protokoll"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine Ethernet-Komponente?', 3, '[{"text": "RJ45-Stecker", "correct": true, "because": "Konkret und real"}, {"text": "USB-Stick", "correct": false, "because": "Keine Netzwerkkomponente"}, {"text": "Monitor", "correct": false, "because": "Ausgabegerät"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Ethernet nur für schnelle Netzwerke geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Verschiedene Geschwindigkeiten"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat Ethernet?', 4, '[{"text": "Kabelgebundene Verbindung", "correct": true, "because": "Typisch Ethernet"}, {"text": "Unklare Adressen", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "MAC-Adressen", "correct": true, "because": "Identifizieren Geräte"}, {"text": "Datenpaketübertragung", "correct": true, "because": "Grundfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss Ethernet immer mit Switches arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Auch direkt möglich"}, {"text": "Ja", "correct": false, "because": "Flexibilität gegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Geschwindigkeit ist typisch für modernes Ethernet?', 3, '[{"text": "1 Gbit/s", "correct": true, "because": "Standardgeschwindigkeit"}, {"text": "1 Mbit/s", "correct": false, "because": "Zu langsam"}, {"text": "1 Kbit/s", "correct": false, "because": "Veraltet"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Ethernet mit WLAN koexistieren?', 2, '[{"text": "Ja", "correct": true, "because": "Hybridnetzwerke möglich"}, {"text": "Nein", "correct": false, "because": "Kompatibel nutzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor beeinflusst die Ethernet-Leistung?', 3, '[{"text": "Kabellänge", "correct": true, "because": "Beeinflusst Signal"}, {"text": "Monitorgröße", "correct": false, "because": "Kein Einfluss"}, {"text": "Tastaturlayout", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Ethernet ist standardisiert (IEEE 802.3). b) Es nutzt keine Kabel.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, kabelgebunden"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen von Ethernet?', 3, '[{"text": "Zuverlässige Datenübertragung", "correct": true, "because": "Fördert Stabilität"}, {"text": "Maximale Mobilität", "correct": false, "because": "WLAN-Merkmal"}, {"text": "Keine Verbindung", "correct": false, "because": "Widerspricht Zweck"}]');

