-- questions.sql (Backup: Sicherung von Daten zur Wiederherstellung im Notfall)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was versteht man unter einem Backup im IT-Kontext?', 2, '[{"text": "Datensicherung zur Wiederherstellung", "correct": true, "because": "Schützt vor Datenverlust"}, {"text": "Datenverschlüsselung", "correct": false, "because": "Anderer Prozess"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich als Fachinformatiker mit einem Backup?', 3, '[{"text": "Datenverlust verhindern", "correct": true, "because": "Wiederherstellung möglich"}, {"text": "Systemgeschwindigkeit erhöhen", "correct": false, "because": "Kein direkter Effekt"}, {"text": "Kosten senken", "correct": false, "because": "Indirekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Arten von Backups gibt es?', 5, '[{"text": "Vollbackup", "correct": true, "because": "Komplette Daten"}, {"text": "Inkrementelles Backup", "correct": true, "because": "Nur Änderungen"}, {"text": "Hardwarebackup", "correct": false, "because": "Kein Backup-Typ"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Vollbackup sichert alle Daten. b) Es ist immer das schnellste Backup.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Langsamer als inkrementell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung eines Backups?', 4, '[{"text": "Backup-Häufigkeit", "correct": false, "because": "Entscheidend für Aktualität"}, {"text": "Speicherort", "correct": false, "because": "Wichtig für Sicherheit"}, {"text": "Büroverschönerung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein inkrementelles Backup schneller als ein Vollbackup ist?', 2, '[{"text": "Ja", "correct": true, "because": "Nur Änderungen gesichert"}, {"text": "Nein", "correct": false, "because": "Effizienter"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Backup-Strategie ist für einen Fachinformatiker am sichersten?', 3, '[{"text": "3-2-1-Regel", "correct": true, "because": "3 Kopien, 2 Medien, 1 extern"}, {"text": "Einmaliges Backup", "correct": false, "because": "Wenig Schutz"}, {"text": "Tägliches Überschreiben", "correct": false, "because": "Keine Historie"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Backup-Planung?', 5, '[{"text": "Backup-Zeitplan", "correct": true, "because": "Regelmäßigkeit"}, {"text": "Speicherort", "correct": true, "because": "Sicherheitsfaktor"}, {"text": "Bürogestaltung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Ein Differential-Backup sichert Änderungen seit dem letzten Vollbackup. b) Es ist dasselbe wie ein inkrementelles Backup. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Inkrementell nur seit letztem Backup"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem Backup unwichtig?', 4, '[{"text": "Speicherkapazität", "correct": false, "because": "Entscheidend für Umfang"}, {"text": "Wiederherstellbarkeit", "correct": false, "because": "Hauptziel"}, {"text": "Farbe der Speichermedien", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss ein Backup extern gespeichert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Empfohlen, aber nicht Pflicht"}, {"text": "Ja", "correct": false, "because": "Flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein regelmäßiges Backup?', 4, '[{"text": "Datenwiederherstellung", "correct": true, "because": "Schutz vor Verlust"}, {"text": "Aktuelle Daten", "correct": true, "because": "Minimiert Verluste"}, {"text": "Schnellere Systeme", "correct": false, "because": "Kein direkter Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Backup immer lokal gespeichert werden sollte. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Externer Speicher sicherer"}, {"text": "Ja", "correct": false, "because": "Risiko bei lokalem Ausfall"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem Backup?', 3, '[{"text": "Wiederherstellbarkeit", "correct": true, "because": "Hauptzweck"}, {"text": "Kosten", "correct": false, "because": "Sekundär"}, {"text": "Ästhetik", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Backup schützt vor Hardwarefehlern. b) Es schützt vor Viren.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Viren erfordern separate Maßnahmen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat ein unzureichendes Backup?', 5, '[{"text": "Datenverlust", "correct": true, "because": "Keine Wiederherstellung"}, {"text": "Hohe Wiederherstellungszeit", "correct": true, "because": "Unvollständig"}, {"text": "Schnelle Wiederherstellung", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Fachinformatiker bei Backups?', 3, '[{"text": "Backup-Strategie planen", "correct": true, "because": "Sichert Daten"}, {"text": "Büro reinigen", "correct": false, "because": "Kein Bezug"}, {"text": "Marketing betreiben", "correct": false, "because": "Andere Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Backup automatisiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Skripte oder Tools"}, {"text": "Nein", "correct": false, "because": "Häufig automatisiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool könnte ein Fachinformatiker für Backups nutzen?', 4, '[{"text": "Veeam", "correct": true, "because": "Backup-Software"}, {"text": "Photoshop", "correct": false, "because": "Grafiktool"}, {"text": "Excel", "correct": false, "because": "Tabellenkalkulation"}]');

