-- questions.sql (Block-Storage: Speicherung von Daten in festen Blöcken)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was versteht ein Fachinformatiker unter Block-Storage?', 2, '[{"text": "Speicherung in festen Datenblöcken", "correct": true, "because": "Blockweise Zugriff"}, {"text": "Dateisystem für Textdaten", "correct": false, "because": "Anderes Konzept"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit Block-Storage?', 3, '[{"text": "Effizienter Datenzugriff", "correct": true, "because": "Direkter Blockzugriff"}, {"text": "Kosten senken", "correct": false, "because": "Indirekt"}, {"text": "Design verbessern", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften hat Block-Storage?', 5, '[{"text": "Feste Blockgröße", "correct": true, "because": "Einheitliche Blöcke"}, {"text": "Direkter Zugriff", "correct": true, "because": "Keine Dateistruktur"}, {"text": "Textformatierung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Block-Storage wird in SAN verwendet. b) Es ist nur für lokale Festplatten geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Cloud, nicht nur lokal"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei Block-Storage?', 4, '[{"text": "Blockgröße", "correct": false, "because": "Definiert Struktur"}, {"text": "Zugriffsprotokoll", "correct": false, "because": "z.B. iSCSI"}, {"text": "Büroverschönerung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Block-Storage direkt auf Blockspeicher zugreift?', 2, '[{"text": "Ja", "correct": true, "because": "Blockweise Zugriff"}, {"text": "Nein", "correct": false, "because": "Kernprinzip"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wird oft für Block-Storage verwendet?', 3, '[{"text": "iSCSI", "correct": true, "because": "Netzwerkzugriff"}, {"text": "HTTP", "correct": false, "because": "Webprotokoll"}, {"text": "FTP", "correct": false, "because": "Dateiübertragung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Nutzung von Block-Storage?', 5, '[{"text": "Blockadressierung", "correct": true, "because": "Direkter Zugriff"}, {"text": "Speicherverwaltung", "correct": true, "because": "Effiziente Nutzung"}, {"text": "Textformatierung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Block-Storage ist schneller als Dateispeicher. b) Es ist nur für kleine Datenmengen geeignet. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch große Datenmengen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Block-Storage unwichtig?', 4, '[{"text": "Blockgröße", "correct": false, "because": "Definiert Struktur"}, {"text": "Zugriffsprotokoll", "correct": false, "because": "z.B. iSCSI"}, {"text": "Farbe der Speichergeräte", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Muss Block-Storage ein Dateisystem haben?', 2, '[{"text": "Nein", "correct": true, "because": "Rohdatenblöcke"}, {"text": "Ja", "correct": false, "because": "Kein Dateisystem nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Block-Storage für Fachinformatiker?', 4, '[{"text": "Hohe Leistung", "correct": true, "because": "Direkter Zugriff"}, {"text": "Flexibilität", "correct": true, "because": "Vielfältige Nutzung"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Block-Storage nur in der Cloud genutzt wird. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch lokal"}, {"text": "Ja", "correct": false, "because": "Vielseitig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Block-Storage?', 3, '[{"text": "Zugriffsgeschwindigkeit", "correct": true, "because": "Leistung"}, {"text": "Kosten", "correct": false, "because": "Sekundär"}, {"text": "Ästhetik", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Block-Storage ist für Datenbanken geeignet. b) Es ist langsamer als Dateispeicher.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schneller, nicht langsamer"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat Block-Storage?', 5, '[{"text": "Komplexere Verwaltung", "correct": true, "because": "Kein Dateisystem"}, {"text": "Höherer Ressourcenbedarf", "correct": true, "because": "Leistungsintensiv"}, {"text": "Schnellere Entwicklung", "correct": false, "because": "Kein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Fachinformatiker bei Block-Storage?', 3, '[{"text": "Konfiguration und Verwaltung", "correct": true, "because": "Speicheroptimierung"}, {"text": "Büro reinigen", "correct": false, "because": "Kein Bezug"}, {"text": "Marketing betreiben", "correct": false, "because": "Andere Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Block-Storage virtualisiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "z.B. Cloud"}, {"text": "Nein", "correct": false, "because": "Möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches System nutzt Block-Storage?', 4, '[{"text": "SAN", "correct": true, "because": "Storage Area Network"}, {"text": "NAS", "correct": false, "because": "Dateibasiert"}, {"text": "FTP", "correct": false, "because": "Übertragung"}]');

