-- questions.sql (Bundesbeauftragte für Datenschutz und Informationsfreiheit: IT-Sicherheit und Datenschutz)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Was versteht ein Fachinformatiker unter der Bundesbeauftragten für den Datenschutz und die Informationsfreiheit (BfDI)?', 2, '[{"text": "Behörde für Datenschutz und Informationsfreiheit", "correct": true, "because": "Überwacht Datenschutz"}, {"text": "Behörde für Netzwerksicherheit", "correct": false, "because": "Andere Zuständigkeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die BfDI?', 3, '[{"text": "Schutz von Daten und Informationsfreiheit", "correct": true, "because": "Datenschutzgesetze"}, {"text": "Hardwareoptimierung", "correct": false, "because": "Kein technisches Ziel"}, {"text": "Kosten senken", "correct": false, "because": "Indirekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben hat die BfDI?', 5, '[{"text": "Überwachung des Datenschutzes", "correct": true, "because": "Bundesbehörden"}, {"text": "Förderung der Informationsfreiheit", "correct": true, "because": "Informationszugang"}, {"text": "Netzwerkadministration", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Die BfDI überwacht den Datenschutz bei Bundesbehörden. b) Sie ist nur für private Unternehmen zuständig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Telekom/Post"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Arbeit der BfDI?', 4, '[{"text": "Datenschutzgesetze", "correct": false, "because": "Grundlage"}, {"text": "Informationsfreiheitsgesetz", "correct": false, "because": "Pflicht"}, {"text": "Büroverschönerung", "correct": true, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob die BfDI den Datenschutz bei Telekommunikationsunternehmen überwacht?', 2, '[{"text": "Ja", "correct": true, "because": "§ 9 BDSG"}, {"text": "Nein", "correct": false, "because": "Korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Gesetz regelt die Arbeit der BfDI?', 3, '[{"text": "Bundesdatenschutzgesetz (BDSG)", "correct": true, "because": "Rechtsgrundlage"}, {"text": "Arbeitszeitgesetz", "correct": false, "because": "Kein Bezug"}, {"text": "Mindestlohngesetz", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Was gehört zur Arbeit der BfDI?', 5, '[{"text": "Datenschutzüberprüfung", "correct": true, "because": "Kernaufgabe"}, {"text": "Informationsfreiheit fördern", "correct": true, "because": "Zusatzaufgabe"}, {"text": "Hardwarewartung", "correct": false, "because": "Kein Bezug"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Die BfDI ist unabhängig. b) Sie ist nur für lokale Behörden zuständig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Bundesbehörden"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat ein Fachinformatiker in Bezug auf die BfDI?', 3, '[{"text": "Datenschutzvorgaben umsetzen", "correct": true, "because": "IT-Sicherheit"}, {"text": "Büro reinigen", "correct": false, "because": "Kein Bezug"}, {"text": "Marketing betreiben", "correct": false, "because": "Andere Aufgabe"}]');

