-- Arbeitsspeicher.sql (Kapazität, Typ, Geschwindigkeit)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist höhere Geschwindigkeit immer besser für den RAM?', 2, '[{"text": "Nein", "correct": true, "because": "Kompatibilität und Kosten zählen"}, {"text": "Ja", "correct": false, "because": "Nicht universell vorteilhaft"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal ist für eine Datenbank entscheidend?', 3, '[{"text": "Große Kapazität", "correct": true, "because": "Mehr Daten im RAM halten"}, {"text": "Hohe Geschwindigkeit", "correct": false, "because": "Wichtig, aber sekundär"}, {"text": "ECC-Unterstützung", "correct": false, "because": "Nur bei Fehlertoleranz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen RAM für Virtualisierung geeignet?', 5, '[{"text": "Hohe Kapazität", "correct": true, "because": "Mehr VMs unterstützen"}, {"text": "Schnelle Zugriffszeiten", "correct": true, "because": "Effiziente Datenverarbeitung"}, {"text": "Niedriger Preis", "correct": false, "because": "Leistung zählt mehr"}, {"text": "Integrierte Grafik", "correct": false, "because": "Irrelevant für RAM"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) DDR5 ist immer schneller als DDR4. b) Mehr RAM verbessert Multitasking.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "a) hängt von Konfiguration ab"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist nicht absolut"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der RAM-Auswahl für einen Gaming-PC?', 4, '[{"text": "Kapazität", "correct": false, "because": "Wichtig für große Spiele"}, {"text": "Geschwindigkeit", "correct": false, "because": "Beeinflusst FPS"}, {"text": "Farbliche Beleuchtung", "correct": true, "because": "Nur Ästhetik"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob 16 GB immer besser sind als 8 GB?', 2, '[{"text": "Nein", "correct": true, "because": "Hängt von der Anwendung ab"}, {"text": "Ja", "correct": false, "because": "Nicht immer nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature priorisiere ich für einen Videoschnitt-PC?', 3, '[{"text": "Hohe Kapazität", "correct": true, "because": "Große Dateien im RAM halten"}, {"text": "Maximale Geschwindigkeit", "correct": false, "because": "Weniger entscheidend"}, {"text": "Low Latency", "correct": false, "because": "Hilfreich, aber sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet schneller RAM?', 5, '[{"text": "Schnellere Datenübertragung", "correct": true, "because": "Höhere Bandbreite"}, {"text": "Bessere CPU-Nutzung", "correct": true, "because": "Weniger Wartezeiten"}, {"text": "Geringerer Stromverbrauch", "correct": false, "because": "Nicht zwangsläufig"}, {"text": "Einfachere Installation", "correct": false, "because": "Unabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) ECC-RAM ist für Server Pflicht. b) Geschwindigkeit ist bei ECC irrelevant. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Geschwindigkeit zählt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist oft wahr"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen Office-PC?', 4, '[{"text": "Hohe Kapazität", "correct": false, "because": "Für Multitasking nötig"}, {"text": "Moderate Geschwindigkeit", "correct": false, "because": "Für Basisaufgaben wichtig"}, {"text": "Extreme Übertaktung", "correct": true, "because": "Überflüssig für Standardnutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist DDR4 mit DDR5 kompatibel?', 2, '[{"text": "Nein", "correct": true, "because": "Unterschiedliche Steckplätze"}, {"text": "Ja", "correct": false, "because": "Physisch inkompatibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind für einen Server-RAM entscheidend?', 4, '[{"text": "ECC-Unterstützung", "correct": true, "because": "Fehlerkorrektur nötig"}, {"text": "Hohe Kapazität", "correct": true, "because": "Viele Prozesse gleichzeitig"}, {"text": "RGB-Beleuchtung", "correct": false, "because": "Nur optisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass mehr RAM immer die Leistung steigert. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Nur bis zur Nutzungsgrenze"}, {"text": "Ja", "correct": false, "because": "Überkapazität nutzlos"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich für einen Thin Client?', 3, '[{"text": "Ausreichende Kapazität", "correct": true, "because": "Basisaufgaben abdecken"}, {"text": "Höchste Geschwindigkeit", "correct": false, "because": "Nicht primär nötig"}, {"text": "Overclocking", "correct": false, "because": "Überflüssig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) RAM-Geschwindigkeit beeinflusst die CPU. b) Typ ist egal, Hauptsache Kapazität.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Typ ist wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist wahr"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ECC-RAM?', 5, '[{"text": "Fehlerkorrektur", "correct": true, "because": "Datenintegrität gesichert"}, {"text": "Stabilität bei Last", "correct": true, "because": "Weniger Abstürze"}, {"text": "Höhere Geschwindigkeit", "correct": false, "because": "Nicht primär"}, {"text": "Geringere Kosten", "correct": false, "because": "Teurer als Non-ECC"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei RAM für einen Webserver unwichtig?', 3, '[{"text": "Kapazität", "correct": false, "because": "Für viele Anfragen nötig"}, {"text": "Geschwindigkeit", "correct": false, "because": "Beeinflusst Antwortzeit"}, {"text": "Overclocking-Fähigkeit", "correct": true, "because": "Stabilität wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Beeinflusst RAM-Typ die Kompatibilität?', 3, '[{"text": "Ja", "correct": true, "because": "Muss zu Mainboard passen"}, {"text": "Nein", "correct": false, "because": "Typ ist entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob 32 GB für Gaming immer nötig sind?', 2, '[{"text": "Nein", "correct": true, "because": "16 GB oft ausreichend"}, {"text": "Ja", "correct": false, "because": "Hängt vom Spiel ab"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche RAM-Eigenschaft wähle ich für einen Render-PC?', 4, '[{"text": "Hohe Kapazität", "correct": true, "because": "Große Projekte laden"}, {"text": "Extreme Geschwindigkeit", "correct": false, "because": "Weniger kritisch"}, {"text": "Minimaler Preis", "correct": false, "because": "Leistung zählt"}]');

