-- Netzwerkkomponenten.sql (Netzwerkkarten, Bandbreite, Schnittstellen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist eine hohe Bandbreite immer entscheidend für eine Netzwerkkarte?', 2, '[{"text": "Nein", "correct": true, "because": "Latenz und Anwendung zählen mit"}, {"text": "Ja", "correct": false, "because": "Nicht allein ausschlaggebend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature priorisiere ich für einen Gaming-PC?', 3, '[{"text": "Niedrige Latenz", "correct": true, "because": "Reaktionszeit ist entscheidend"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Sekundär bei kleinen Paketen"}, {"text": "Viele Schnittstellen", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen eine Netzwerkkarte für einen Server geeignet?', 5, '[{"text": "Hohe Bandbreite", "correct": true, "because": "Viel Datenverkehr"}, {"text": "Redundante Schnittstellen", "correct": true, "because": "Ausfallsicherheit"}, {"text": "Geringer Stromverbrauch", "correct": false, "because": "Leistung zählt mehr"}, {"text": "Integrierte GPU", "correct": false, "because": "Irrelevant für Netzwerk"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Bandbreite bestimmt die Datenrate. b) Schnittstellen beeinflussen die Kompatibilität.', 3, '[{"text": "Beides stimmt", "correct": true, "because": "a) definiert Durchsatz, b) Hardware-Passung"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist auch richtig"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "Beide sind richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl einer Netzwerkkarte für einen Desktop?', 4, '[{"text": "Bandbreite", "correct": false, "because": "Wichtig für Datenfluss"}, {"text": "Schnittstellentyp", "correct": false, "because": "Muss zum Mainboard passen"}, {"text": "Farbliches Design", "correct": true, "because": "Technisch irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine 1-Gbit/s-Karte für 4K-Streaming reicht?', 2, '[{"text": "Ja", "correct": true, "because": "Ausreichend für typische Streams"}, {"text": "Nein", "correct": false, "because": "Bandbreite ist mehr als genug"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schnittstelle wähle ich für maximale Geschwindigkeit?', 3, '[{"text": "PCIe", "correct": true, "because": "Hohe Datenrate und Bandbreite"}, {"text": "USB", "correct": false, "because": "Langsamer als PCIe"}, {"text": "SATA", "correct": false, "because": "Für Speicher, nicht Netzwerk"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren sind für eine Netzwerkkarte bei Virtualisierung entscheidend?', 5, '[{"text": "Hohe Bandbreite", "correct": true, "because": "Viele VMs, viel Traffic"}, {"text": "SR-IOV-Unterstützung", "correct": true, "because": "Direkte VM-Zugriffe"}, {"text": "Niedrige Latenz", "correct": false, "because": "Wichtig, aber sekundär"}, {"text": "Bluetooth", "correct": false, "because": "Nicht netzwerkrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Mehr Bandbreite löst alle Netzwerkprobleme. b) Schnittstellen sind austauschbar. Stimmt das?', 3, '[{"text": "Beides falsch", "correct": true, "because": "a) ignoriert Latenz, b) ignoriert Kompatibilität"}, {"text": "Beides stimmt", "correct": false, "because": "Beides zu pauschal"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist falsch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine Netzwerkkarte in einem Thin Client?', 4, '[{"text": "Hohe Bandbreite", "correct": false, "because": "Für Remote-Zugriff nötig"}, {"text": "Kompatible Schnittstelle", "correct": false, "because": "Muss passen"}, {"text": "10-Gbit/s-Unterstützung", "correct": true, "because": "Überdimensioniert für einfache Tasks"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist eine Netzwerkkarte mit 100 Mbit/s für moderne Büros ausreichend?', 2, '[{"text": "Nein", "correct": true, "because": "Zu wenig für heutige Anforderungen"}, {"text": "Ja", "correct": false, "because": "Gigabit ist Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Karte mit mehreren Schnittstellen?', 4, '[{"text": "Redundanz", "correct": true, "because": "Ausfallsicherheit erhöhen"}, {"text": "Lastverteilung", "correct": true, "because": "Traffic aufteilen"}, {"text": "Höhere Latenz", "correct": false, "because": "Kein Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Bandbreite und Geschwindigkeit dasselbe sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Bandbreite ist Kapazität, Geschwindigkeit ist Latenz"}, {"text": "Ja", "correct": false, "because": "Technisch unterschiedlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich für einen Dateiserver?', 3, '[{"text": "Hohe Bandbreite", "correct": true, "because": "Große Datenmengen übertragen"}, {"text": "Niedrige Latenz", "correct": false, "because": "Sekundär bei großen Files"}, {"text": "Kleine Bauform", "correct": false, "because": "Technisch irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) PCIe ist schneller als USB für Netzwerkkarten. b) Bandbreite ist unwichtig bei kleinen Netzwerken.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Bandbreite bleibt relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen eine Netzwerkkarte für Streaming ideal?', 5, '[{"text": "Hohe Bandbreite", "correct": true, "because": "Stabile Datenrate"}, {"text": "Niedrige Latenz", "correct": true, "because": "Weniger Buffering"}, {"text": "Viele Ports", "correct": false, "because": "Nicht primär nötig"}, {"text": "Bluetooth", "correct": false, "because": "Nicht für Streaming"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer Netzwerkkarte für einen Laptop unwichtig?', 3, '[{"text": "Bandbreite", "correct": false, "because": "Für Downloads relevant"}, {"text": "Schnittstellentyp", "correct": false, "because": "Muss kompatibel sein"}, {"text": "Server-Clustering", "correct": true, "because": "Nicht laptoprelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht eine bessere Netzwerkkarte die Internetgeschwindigkeit?', 3, '[{"text": "Nein", "correct": true, "because": "Limitiert durch ISP"}, {"text": "Ja", "correct": false, "because": "Nur lokale Performance"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Karte mit 10 Gbit/s für ein kleines Büro sinnvoll ist?', 2, '[{"text": "Nein", "correct": true, "because": "Oft überdimensioniert"}, {"text": "Ja", "correct": false, "because": "Nur bei hohen Anforderungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bandbreite wähle ich für einen Webserver?', 4, '[{"text": "Mindestens 1 Gbit/s", "correct": true, "because": "Viele Anfragen gleichzeitig"}, {"text": "100 Mbit/s", "correct": false, "because": "Zu wenig für Last"}, {"text": "10 Mbit/s", "correct": false, "because": "Völlig unzureichend"}]');

