INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Prüfung 1: Planen eines Softwareprodukts > IT-Sicherheit > Bedrohungsszenarien > Datendiebstahl
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann Datendiebstahl ohne unbefugten Zugriff auf ein System erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Unbefugter Zugriff ist Voraussetzung für Datendiebstahl"}, {"text": "Ja", "correct": false, "because": "Zugriff ist notwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist Datendiebstahl immer mit finanziellen Motiven verbunden?', 2, '[{"text": "Nein", "correct": true, "because": "Motive können auch Spionage oder Sabotage sein"}, {"text": "Ja", "correct": false, "because": "Motive sind vielfältig"}]'),
('00000000-0000-0000-0000-000000000000', 'Können verschlüsselte Daten bei einem Datendiebstahl dennoch kompromittiert werden?', 2, '[{"text": "Ja", "correct": true, "because": "Wenn der Schlüssel gestohlen wird, sind Daten lesbar"}, {"text": "Nein", "correct": false, "because": "Risiko besteht bei Schlüsselkompromittierung"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss Datendiebstahl immer durch externe Angreifer erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Interne Mitarbeiter können ebenfalls Daten stehlen"}, {"text": "Ja", "correct": false, "because": "Interne Bedrohungen existieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Datendiebstahl durch Social Engineering verursacht werden?', 2, '[{"text": "Ja", "correct": true, "because": "Social Engineering täuscht Nutzer zur Datenpreisgabe"}, {"text": "Nein", "correct": false, "because": "Methode ist gängig"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methode wird am häufigsten für Datendiebstahl genutzt?', 2, '[{"text": "Phishing", "correct": true, "because": "Weit verbreitet und effektiv"}, {"text": "SQL-Injection", "correct": false, "because": "Spezifischer Angriff"}, {"text": "Brute-Force", "correct": false, "because": "Weniger häufig für Diebstahl"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt Datendiebstahl primär?', 3, '[{"text": "Unbefugtes Erlangen sensibler Informationen", "correct": true, "because": "Kernziel ist Datenentwendung"}, {"text": "Systemstörung", "correct": false, "because": "Sekundäres Ziel"}, {"text": "Benutzeridentifikation", "correct": false, "because": "Anderer Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahme schützt am effektivsten vor Datendiebstahl?', 2, '[{"text": "Verschlüsselung", "correct": true, "because": "Macht gestohlene Daten unlesbar"}, {"text": "Firewall", "correct": false, "because": "Schützt Netzwerk, nicht direkt Daten"}, {"text": "Antivirus", "correct": false, "because": "Fokussiert Malware"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schwäche macht Systeme anfällig für Datendiebstahl?', 2, '[{"text": "Schwache Authentifizierung", "correct": true, "because": "Erleichtert unbefugten Zugriff"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein Sicherheitsproblem"}, {"text": "Geringer Speicher", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug wird oft verwendet, um Datendiebstahl durch Schwachstellen in Webanwendungen zu verhindern?', 2, '[{"text": "Web Application Firewall (WAF)", "correct": true, "because": "Schützt vor SQL-Injection und XSS"}, {"text": "Router", "correct": false, "because": "Netzwerkgerät"}, {"text": "Texteditor", "correct": false, "because": "Kein Sicherheitswerkzeug"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Methoden werden häufig für Datendiebstahl eingesetzt?', 4, '[{"text": "Phishing", "correct": true, "because": "Täuscht Nutzer zur Preisgabe"}, {"text": "Malware", "correct": true, "because": "Sammelt Daten heimlich"}, {"text": "SQL-Injection", "correct": true, "because": "Nutz Schwachstellen in Datenbanken"}, {"text": "Manuelle Dateneingabe", "correct": false, "because": "Keine Diebstahlmethode"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen können Datendiebstahl verhindern?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Schützt Daten bei Diebstahl"}, {"text": "Starke Authentifizierung", "correct": true, "because": "Verhindert unbefugten Zugriff"}, {"text": "Regelmäßige Updates", "correct": true, "because": "Schließt Sicherheitslücken"}, {"text": "Langsame Netzwerke", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Daten sind typische Ziele von Datendiebstahl?', 4, '[{"text": "Personenbezogene Daten", "correct": true, "because": "Hochwertig für Identitätsdiebstahl"}, {"text": "Finanzdaten", "correct": true, "because": "Für finanziellen Gewinn"}, {"text": "Geschäftsgeheimnisse", "correct": true, "because": "Wettbewerbsvorteil"}, {"text": "Öffentliche Dokumente", "correct": false, "because": "Weniger sensibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Bedrohungen führen zu Datendiebstahl?', 3, '[{"text": "Social Engineering", "correct": true, "because": "Täuscht Nutzer"}, {"text": "Schwachstellen-Exploits", "correct": true, "because": "Nutzt technische Lücken"}, {"text": "Insider-Bedrohungen", "correct": true, "because": "Interne Akteure"}, {"text": "Langsame Server", "correct": false, "because": "Kein Sicherheitsrisiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologien helfen, Datendiebstahl zu erkennen oder zu verhindern?', 3, '[{"text": "Intrusion Detection System (IDS)", "correct": true, "because": "Erkennt unbefugten Zugriff"}, {"text": "Data Loss Prevention (DLP)", "correct": true, "because": "Überwacht Datenbewegungen"}, {"text": "Verschlüsselung", "correct": true, "because": "Schützt Daten"}, {"text": "Textverarbeitung", "correct": false, "because": "Kein Sicherheitswerkzeug"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Datendiebstahl erfordert unbefugten Zugriff. b) Er ist immer finanziell motiviert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Zugriff ja, Motive vielfältig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Verschlüsselung schützt vor Datendiebstahl. b) Interne Bedrohungen sind unmöglich.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Verschlüsselung ja, interne Bedrohungen möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Phishing ist eine häufige Methode für Datendiebstahl. b) Verschlüsselte Daten sind immer sicher.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Phishing ja, Schlüssel können kompromittiert werden"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Social Engineering kann Datendiebstahl ermöglichen. b) Externe Angreifer sind die einzige Bedrohung.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Social Engineering ja, interne Bedrohungen auch"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) DLP-Tools helfen, Datendiebstahl zu verhindern. b) Schwache Authentifizierung schützt vor Datendiebstahl.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "DLP ja, schwache Authentifizierung nein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

