-- Grenzwerte prüfen.sql (z. B. Tests an den Randbereichen von Eingabewerten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind Grenzwerte nur bei numerischen Eingaben relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Strings oder Arrays betroffen"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit dem Prüfen von Grenzwerten?', 3, '[{"text": "Robustheit testen", "correct": true, "because": "Verhalten an Randbereichen prüfen"}, {"text": "Schnellere Tests", "correct": false, "because": "Nicht primär"}, {"text": "Mehr Features", "correct": false, "because": "Kein Fokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Werte prüfe ich bei Grenzwerttests?', 5, '[{"text": "Minimalwert", "correct": true, "because": "Unterer Rand"}, {"text": "Maximalwert", "correct": true, "because": "Oberer Rand"}, {"text": "Zufällige Werte", "correct": false, "because": "Kein Grenzfokus"}, {"text": "Durchschnittswerte", "correct": false, "because": "Mittlerer Bereich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Grenzwerte finden Fehler an Rändern. b) Sie ersetzen normale Tests.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Ergänzen, nicht ersetzen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich beim Prüfen von Grenzwerten?', 4, '[{"text": "Randbereiche", "correct": false, "because": "Kern der Tests"}, {"text": "Fehleranfälligkeit", "correct": false, "because": "Ziel der Prüfung"}, {"text": "Farbschema", "correct": true, "because": "Kein Testfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Grenzwerte ohne Tests prüfbar sind?', 2, '[{"text": "Nein", "correct": true, "because": "Tests nötig für Verhalten"}, {"text": "Ja", "correct": false, "because": "Analyse allein ungenau"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt Grenzwertprüfung?', 3, '[{"text": "Test mit 0 und 100", "correct": true, "because": "Randwerte prüfen"}, {"text": "Test mit 50", "correct": false, "because": "Mittlerer Wert"}, {"text": "Test ohne Eingabe", "correct": false, "because": "Kein Grenzfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet das Prüfen von Grenzwerten?', 5, '[{"text": "Fehlererkennung", "correct": true, "because": "Ränder oft fehleranfällig"}, {"text": "Robustheit", "correct": true, "because": "Sichert Extremfälle"}, {"text": "Schnellere Tests", "correct": false, "because": "Nicht garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Grenzwerte testen Extremfälle. b) Sie sind immer einfach zu finden. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Definition nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für Grenzwerttests?', 4, '[{"text": "Randwerte", "correct": false, "because": "Kern der Prüfung"}, {"text": "Testfälle", "correct": false, "because": "Definieren Szenarien"}, {"text": "UI-Animationen", "correct": true, "because": "Kein Testfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Grenzwerte ohne Spezifikation prüfbar?', 2, '[{"text": "Nein", "correct": true, "because": "Grenzen müssen definiert sein"}, {"text": "Ja", "correct": false, "because": "Unklar ohne Spezifikation"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme löst Grenzwertprüfung?', 4, '[{"text": "Fehler an Rändern", "correct": true, "because": "Typische Schwachstellen"}, {"text": "Unrobustes Verhalten", "correct": true, "because": "Extremfälle abdecken"}, {"text": "Langsame Tests", "correct": false, "because": "Kein Testfokus"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Grenzwerte nur für Unit-Tests sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Integrationstests"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei Grenzwerttests?', 3, '[{"text": "Randbereiche", "correct": true, "because": "Kern der Prüfung"}, {"text": "Schnelle Durchführung", "correct": false, "because": "Gründlichkeit zählt"}, {"text": "Viele Testfälle", "correct": false, "because": "Relevanz entscheidet"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Grenzwerte erhöhen Zuverlässigkeit. b) Sie garantieren fehlerfreien Code.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Fehlerfreiheit nicht garantiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Nachteile hat Grenzwertprüfung?', 5, '[{"text": "Mehr Testfälle", "correct": true, "because": "Ränder abdecken"}, {"text": "Zeitaufwand", "correct": true, "because": "Gründlichkeit braucht Zeit"}, {"text": "Langsamere Ausführung", "correct": false, "because": "Kein Performance-Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Grenzwerttests unwichtig?', 3, '[{"text": "Extremwerte", "correct": false, "because": "Kern der Prüfung"}, {"text": "Fehlererkennung", "correct": false, "because": "Hauptziel"}, {"text": "Schriftart", "correct": true, "because": "Kein Testfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erhöht Grenzwertprüfung den Testaufwand?', 3, '[{"text": "Ja", "correct": true, "because": "Mehr Szenarien prüfen"}, {"text": "Nein", "correct": false, "because": "Aufwand steigt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Grenzwerte Robustheit verbessern?', 2, '[{"text": "Ja", "correct": true, "because": "Extremfälle abgesichert"}, {"text": "Nein", "correct": false, "because": "Klarer Nutzen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug hilft bei Grenzwerttests?', 4, '[{"text": "Test-Frameworks", "correct": true, "because": "Automatisieren Randtests"}, {"text": "UI-Designer", "correct": false, "because": "Design-Fokus"}, {"text": "Compiler", "correct": false, "because": "Nur Syntax"}]');

