-- Keylogging.sql (Erfassen von Tastatureingaben, z. B. als Sicherheitsrisiko oder Überwachungstool)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Tastatureingaben immer unbemerkt aufgezeichnet werden können. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Antivirus kann Keylogger erkennen"}, {"text": "Ja", "correct": false, "because": "Erkennung ist möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, um ein System vor unbefugtem Mitschneiden zu schützen?', 3, '[{"text": "Regelmäßige Scans", "correct": true, "because": "Entdeckt verdächtige Software"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein Schutzfaktor"}, {"text": "Mehr Speicher", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen schützen ein Netzwerk vor Eingabeaufzeichnungen?', 5, '[{"text": "Endpoint-Sicherheit", "correct": true, "because": "Überwacht Geräte"}, {"text": "Aktualisierte Software", "correct": true, "because": "Schließt Schwachstellen"}, {"text": "Höhere Bandbreite", "correct": false, "because": "Kein Sicherheitsvorteil"}, {"text": "Bunte Tastaturen", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Keylogger können Hardware-basiert sein. b) Sie sind immer leicht zu erkennen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Erkennung ist oft schwierig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich einen PC auf Sicherheitsrisiken prüfe?', 4, '[{"text": "Unbekannte Prozesse", "correct": false, "because": "Können Keylogger sein"}, {"text": "Netzwerkverkehr", "correct": false, "because": "Datenabfluss möglich"}, {"text": "Bildschirmdesign", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Keylogger immer eine Internetverbindung braucht?', 2, '[{"text": "Nein", "correct": true, "because": "Kann lokal speichern"}, {"text": "Ja", "correct": false, "because": "Offline möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool hilft mir, verdächtige Eingabeaufzeichnungen zu erkennen?', 3, '[{"text": "Antimalware-Software", "correct": true, "because": "Erkennt Keylogger"}, {"text": "Texteditor", "correct": false, "because": "Kein Sicherheitswerkzeug"}, {"text": "Browser", "correct": false, "because": "Nicht relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren erhöhen das Risiko für unbemerkte Eingabeaufzeichnungen?', 5, '[{"text": "Veraltete Software", "correct": true, "because": "Schwachstellen ausnutzbar"}, {"text": "Unsichere Downloads", "correct": true, "because": "Können Keylogger enthalten"}, {"text": "Schnelle CPU", "correct": false, "because": "Kein Risikofaktor"}, {"text": "Großer Monitor", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Keylogger speichern oft Passwörter. b) Sie sind immer legal. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Legalität hängt vom Einsatz ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um ein System vor Keyloggern zu schützen?', 4, '[{"text": "Firewall", "correct": false, "because": "Blockiert verdächtige Verbindungen"}, {"text": "Regelmäßige Updates", "correct": false, "because": "Schließt Schwachstellen"}, {"text": "Neuer Schreibtisch", "correct": true, "because": "Kein Sicherheitsvorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Keylogger nur Software?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Hardware möglich"}, {"text": "Ja", "correct": false, "because": "Hardware-Keylogger existieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode schützt Passwörter vor unbefugtem Mitschneiden?', 4, '[{"text": "Zwei-Faktor-Authentifizierung", "correct": true, "because": "Ergänzt Passwörter"}, {"text": "Schnellere Internetleitung", "correct": false, "because": "Kein Schutz"}, {"text": "Bunter Bildschirm", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ein Keylogger immer sichtbare Prozesse hat. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kann im Hintergrund laufen"}, {"text": "Ja", "correct": false, "because": "Oft versteckt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich einen Arbeits-PC auf Sicherheit prüfe?', 3, '[{"text": "Unbekannte Software", "correct": true, "because": "Kann Keylogger enthalten"}, {"text": "Hohe Taktfrequenz", "correct": false, "because": "Kein Sicherheitsfaktor"}, {"text": "Großer Cache", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Keylogger können per E-Mail verschickt werden. b) Sie funktionieren nur unter Windows.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Plattformübergreifend möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine virtuelle Tastatur gegen Keylogger?', 5, '[{"text": "Umgeht Hardware-Keylogger", "correct": true, "because": "Keine physische Eingabe"}, {"text": "Schützt vor Software-Keylogger", "correct": true, "because": "Erschwert Mitschnitt"}, {"text": "Erhöht CPU-Leistung", "correct": false, "because": "Kein Zusammenhang"}, {"text": "Verbessert Netzwerk", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich einen PC gegen Keylogger sichere?', 3, '[{"text": "Benutzerrechte", "correct": false, "because": "Eingeschränkte Rechte schützen"}, {"text": "Antivirus", "correct": false, "because": "Erkennt Bedrohungen"}, {"text": "Tastaturfarbe", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Zeichnen Keylogger auch Mausklicks auf?', 3, '[{"text": "Nein", "correct": true, "because": "Fokus auf Tastatureingaben"}, {"text": "Ja", "correct": false, "because": "Nicht typisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Keylogger durch Verschlüsselung gestoppt wird?', 2, '[{"text": "Nein", "correct": true, "because": "Schützt nur Übertragung"}, {"text": "Ja", "correct": false, "because": "Keylogger fängt vor Verschlüsselung ab"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Verhalten schützt vor Keyloggern?', 4, '[{"text": "Vermeiden unsicherer Downloads", "correct": true, "because": "Reduziert Infektionsrisiko"}, {"text": "Schnelleres Tippen", "correct": false, "because": "Kein Schutz"}, {"text": "Mehr Bildschirme", "correct": false, "because": "Irrelevant"}]');

