-- Ablauf (Anforderungen Festlegen, System entwerfen, Module entwickeln, testen jeder Ebene, System abnehmen).sql (Strukturierter Ablauf mit Testphasen, z. B. für sicherheitskritische Systeme)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Beginne ich hier ohne Anforderungen?', 2, '[{"text": "Nein", "correct": true, "because": "Anforderungen festlegen ist erster Schritt"}, {"text": "Ja", "correct": false, "because": "Strukturierter Ablauf"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Schritt mache ich zuerst in diesem Prozess?', 3, '[{"text": "Anforderungen festlegen", "correct": true, "because": "Basis des Projekts definieren"}, {"text": "System entwerfen", "correct": false, "because": "Folgt Anforderungen"}, {"text": "Testen jeder Ebene", "correct": false, "because": "Später im Ablauf"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phasen gehören zu diesem Ablauf?', 5, '[{"text": "Module entwickeln", "correct": true, "because": "Systemkomponenten erstellen"}, {"text": "System abnehmen", "correct": true, "because": "Abschluss des Projekts"}, {"text": "Iterative Entwicklung", "correct": false, "because": "Linear strukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Testen erfolgt auf jeder Ebene. b) Systementwurf ist optional.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Systementwurf essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich in diesem Ablauf?', 4, '[{"text": "Anforderungen festlegen", "correct": false, "because": "Grundlage des Prozesses"}, {"text": "Testen jeder Ebene", "correct": false, "because": "Qualität sichern"}, {"text": "Flexible Anpassung", "correct": true, "because": "Strukturierter Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ich hier ohne Tests arbeite?', 2, '[{"text": "Nein", "correct": true, "because": "Testen jeder Ebene ist Kern"}, {"text": "Ja", "correct": false, "because": "Qualitätssicherung zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phase wähle ich, um die Architektur zu definieren?', 3, '[{"text": "System entwerfen", "correct": true, "because": "Gesamtsystem planen"}, {"text": "Module entwickeln", "correct": false, "because": "Einzelkomponenten"}, {"text": "System abnehmen", "correct": false, "because": "Abschluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schritte sichern die Qualität?', 5, '[{"text": "Testen jeder Ebene", "correct": true, "because": "Fehler früh erkennen"}, {"text": "System abnehmen", "correct": true, "because": "Endgültige Validierung"}, {"text": "Ungeprüfte Entwicklung", "correct": false, "because": "Tests essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Anforderungen sind die Basis. b) Tests sind unwichtig. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Tests sind zentral"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich hier nicht unbedingt?', 4, '[{"text": "System entwerfen", "correct": false, "because": "Architektur definieren"}, {"text": "Testen jeder Ebene", "correct": false, "because": "Qualität sichern"}, {"text": "Iterative Anpassung", "correct": true, "because": "Linearer Ablauf"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Entwickle ich hier ohne Entwurf?', 2, '[{"text": "Nein", "correct": true, "because": "System entwerfen ist Schritt"}, {"text": "Ja", "correct": false, "because": "Strukturierter Prozess"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phasen unterstützen die Entwicklung?', 4, '[{"text": "Anforderungen festlegen", "correct": true, "because": "Basis schaffen"}, {"text": "Module entwickeln", "correct": true, "because": "Komponenten umsetzen"}, {"text": "Zufällige Tests", "correct": false, "because": "Geplante Tests"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass ich hier ohne Abnahme fertig bin. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "System abnehmen ist Schritt"}, {"text": "Ja", "correct": false, "because": "Abnahme zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich nach den Anforderungen?', 3, '[{"text": "System entwerfen", "correct": true, "because": "Architektur planen"}, {"text": "Testen jeder Ebene", "correct": false, "because": "Später im Ablauf"}, {"text": "System abnehmen", "correct": false, "because": "Abschluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Module werden entwickelt. b) Entwurf ist unwichtig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Entwurf essenziell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile hat dieser Ablauf?', 5, '[{"text": "Qualitätssicherung", "correct": true, "because": "Testen jeder Ebene"}, {"text": "Strukturierte Entwicklung", "correct": true, "because": "Klarer Ablauf"}, {"text": "Flexible Änderungen", "correct": false, "because": "Linearer Ansatz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist hier weniger wichtig?', 3, '[{"text": "Anforderungen festlegen", "correct": false, "because": "Basis des Projekts"}, {"text": "Module entwickeln", "correct": false, "because": "Umsetzung zentral"}, {"text": "Iterative Zyklen", "correct": true, "because": "Linear strukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist die Abnahme hier unwichtig?', 3, '[{"text": "Nein", "correct": true, "because": "System abnehmen abschließend"}, {"text": "Ja", "correct": false, "because": "Validierung nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ich hier ohne Tests arbeite?', 2, '[{"text": "Nein", "correct": true, "because": "Testen jeder Ebene ist Kern"}, {"text": "Ja", "correct": false, "because": "Qualitätssicherung zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welchen Schritt wähle ich nach der Entwicklung?', 4, '[{"text": "Testen jeder Ebene", "correct": true, "because": "Qualität prüfen"}, {"text": "Anforderungen festlegen", "correct": false, "because": "Erster Schritt"}, {"text": "System entwerfen", "correct": false, "because": "Vor Entwicklung"}]');

