-- Netzwerk: OSI-Modell - Bitübertragungsschicht
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Bitübertragungsschicht eine Ebene des OSI-Modells?', 2, '[{"text": "Ja", "correct": true, "because": "Schicht 1"}, {"text": "Nein", "correct": false, "because": "Sie ist grundlegend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt die Bitübertragungsschicht?', 3, '[{"text": "Physische Übertragung von Bits", "correct": true, "because": "Grundlage der Kommunikation"}, {"text": "Daten formatieren", "correct": false, "because": "Schicht 6 Aufgabe"}, {"text": "Datenpakete routen", "correct": false, "because": "Schicht 3 Aufgabe"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Bitübertragungsschicht ist Schicht 1. b) Sie steuert die Sitzungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Schicht 5"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponenten gehören zur Bitübertragungsschicht?', 4, '[{"text": "Netzwerkkabel", "correct": true, "because": "Physische Verbindung"}, {"text": "Unklare Protokolle", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Netzwerkkarten", "correct": true, "because": "Übertragen Signale"}, {"text": "Switches", "correct": true, "because": "Verbinden Geräte"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Netzwerk ohne Bitübertragungsschicht funktionieren?', 2, '[{"text": "Nein", "correct": true, "because": "Physische Übertragung fehlt"}, {"text": "Ja", "correct": false, "because": "Unmöglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Bitübertragungsschicht?', 3, '[{"text": "Physische Datenübertragung ermöglichen", "correct": true, "because": "Grundlage Netzwerk"}, {"text": "Daten formatieren", "correct": false, "because": "Schicht 6"}, {"text": "Sitzungen verwalten", "correct": false, "because": "Schicht 5"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Bitübertragungsschicht nur für kabelgebundene Netzwerke relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch WLAN"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat die Bitübertragungsschicht?', 3, '[{"text": "Bits über physische Medien senden", "correct": true, "because": "Grundfunktion"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Schicht 6"}, {"text": "Netzwerkadressen zuweisen", "correct": false, "because": "Schicht 3"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Bitübertragungsschicht definiert Kabelstandards. b) Sie ist für Datenflusssteuerung zuständig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Schicht 4"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Bitübertragungsschicht?', 3, '[{"text": "Keine physische Datenübertragung", "correct": true, "because": "Grundlage fehlt"}, {"text": "Datenübertragung schneller", "correct": false, "because": "Unsinn"}, {"text": "Sitzungen unstrukturiert", "correct": false, "because": "Schicht 5"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Bitübertragungsschicht ohne Netzwerkkabel arbeiten?', 2, '[{"text": "Ja", "correct": true, "because": "WLAN möglich"}, {"text": "Nein", "correct": false, "because": "Flexibilität gegeben"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine Funktion der Bitübertragungsschicht?', 3, '[{"text": "Signalübertragung über Kabel", "correct": true, "because": "Konkret und real"}, {"text": "Datenpaket-Routing", "correct": false, "because": "Schicht 3"}, {"text": "Sitzung starten", "correct": false, "because": "Schicht 5"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Bitübertragungsschicht nur für lokale Netzwerke relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch WAN"}, {"text": "Ja", "correct": false, "because": "Breite Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat die Bitübertragungsschicht?', 4, '[{"text": "Physische Verbindung", "correct": true, "because": "Kabel oder Funk"}, {"text": "Unklare Signale", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Bitübertragung", "correct": true, "because": "Grundfunktion"}, {"text": "Hardwarestandards", "correct": true, "because": "Definiert Medien"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Bitübertragungsschicht Daten formatieren?', 2, '[{"text": "Nein", "correct": true, "because": "Schicht 6 Aufgabe"}, {"text": "Ja", "correct": false, "because": "Nicht ihre Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Netzwerkkarte auf der Bitübertragungsschicht?', 3, '[{"text": "Bits physisch übertragen", "correct": true, "because": "Signalübertragung"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Schicht 6"}, {"text": "IP-Adressen zuweisen", "correct": false, "because": "Schicht 3"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Bitübertragungsschicht ohne Hardware arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Physische Medien nötig"}, {"text": "Ja", "correct": false, "because": "Unmöglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor beeinflusst die Bitübertragungsschicht?', 3, '[{"text": "Kabelqualität", "correct": true, "because": "Signalstärke"}, {"text": "Sitzungssteuerung", "correct": false, "because": "Schicht 5"}, {"text": "Monitorauflösung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Bitübertragungsschicht definiert Signalübertragung. b) Sie ist für Datenflusssteuerung zuständig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Schicht 4"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen der Bitübertragungsschicht?', 3, '[{"text": "Physische Grundlage für Netzwerke", "correct": true, "because": "Fördert Kommunikation"}, {"text": "Maximale Unklarheit", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Übertragung", "correct": false, "because": "Fördert Verbindung"}]');

