-- Netzwerk: OSI-Modell - Sicherungsschicht
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Sicherungsschicht eine Ebene des OSI-Modells?', 2, '[{"text": "Ja", "correct": true, "because": "Schicht 2"}, {"text": "Nein", "correct": false, "because": "Sie ist zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt die Sicherungsschicht?', 3, '[{"text": "Datenübertragung zwischen benachbarten Geräten", "correct": true, "because": "Lokale Verbindung"}, {"text": "Daten physisch übertragen", "correct": false, "because": "Schicht 1"}, {"text": "Netzwerkweites Routing", "correct": false, "because": "Schicht 3"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Sicherungsschicht ist Schicht 2. b) Sie verschlüsselt Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Schicht 6"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgaben gehören zur Sicherungsschicht?', 4, '[{"text": "Fehlererkennung", "correct": true, "because": "Prüft Datenintegrität"}, {"text": "Unklare Daten", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "MAC-Adressierung", "correct": true, "because": "Identifiziert Geräte"}, {"text": "Zugriffskontrolle", "correct": true, "because": "Regelt Netzwerkzugriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann ein Netzwerk ohne Sicherungsschicht funktionieren?', 2, '[{"text": "Nein", "correct": true, "because": "Lokale Verbindung fehlt"}, {"text": "Ja", "correct": false, "because": "Schicht 2 essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Sicherungsschicht?', 3, '[{"text": "Datenrahmen zwischen Geräten übertragen", "correct": true, "because": "Lokale Kommunikation"}, {"text": "Daten global routen", "correct": false, "because": "Schicht 3"}, {"text": "Anwendungsdienste bereitstellen", "correct": false, "because": "Schicht 7"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Sicherungsschicht nur für kabelgebundene Netzwerke relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch WLAN"}, {"text": "Ja", "correct": false, "because": "Breite Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Funktion hat die MAC-Adresse auf der Sicherungsschicht?', 3, '[{"text": "Geräte im lokalen Netz identifizieren", "correct": true, "because": "Eindeutige Kennung"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Schicht 6"}, {"text": "Globale Adressierung", "correct": false, "because": "Schicht 3"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Sicherungsschicht erkennt Übertragungsfehler. b) Sie stellt Anwendungsdienste bereit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Schicht 7"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Sicherungsschicht?', 3, '[{"text": "Keine lokale Datenübertragung", "correct": true, "because": "Schicht 2 fehlt"}, {"text": "Datenübertragung schneller", "correct": false, "because": "Unsinn"}, {"text": "Netzwerk bleibt global", "correct": false, "because": "Schicht 3 betroffen"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Sicherungsschicht ohne Bitübertragungsschicht arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig von Schicht 1"}, {"text": "Ja", "correct": false, "because": "Schichten verbunden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine Sicherungsschicht-Funktion?', 3, '[{"text": "Ethernet-Rahmen übertragen", "correct": true, "because": "Konkret und real"}, {"text": "IP-Adresse zuweisen", "correct": false, "because": "Schicht 3"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Schicht 6"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Sicherungsschicht nur für Switches relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Bridges, WLAN"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Protokolle arbeiten auf der Sicherungsschicht?', 4, '[{"text": "Ethernet", "correct": true, "because": "Kabelgebundene Übertragung"}, {"text": "Unklare Protokolle", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Wi-Fi (802.11)", "correct": true, "because": "Drahtlose Übertragung"}, {"text": "PPP", "correct": true, "because": "Point-to-Point"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Sicherungsschicht Daten verschlüsseln?', 2, '[{"text": "Nein", "correct": true, "because": "Schicht 6 Aufgabe"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Fehlererkennung?', 3, '[{"text": "Übertragungsfehler identifizieren", "correct": true, "because": "Sichert Daten"}, {"text": "Daten global routen", "correct": false, "because": "Schicht 3"}, {"text": "Anwendungsdienste", "correct": false, "because": "Schicht 7"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Sicherungsschicht ohne Netzwerkschicht arbeiten?', 2, '[{"text": "Ja", "correct": true, "because": "Lokale Verbindung möglich"}, {"text": "Nein", "correct": false, "because": "Unabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor beeinflusst die Sicherungsschicht?', 3, '[{"text": "Netzwerktechnologie", "correct": true, "because": "Bestimmt Protokoll"}, {"text": "Monitorauflösung", "correct": false, "because": "Irrelevant"}, {"text": "Tastaturlayout", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Sicherungsschicht verwendet MAC-Adressen. b) Sie stellt Anwendungsdienste bereit.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Schicht 7"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen der Sicherungsschicht?', 3, '[{"text": "Fehlerfreie lokale Übertragung", "correct": true, "because": "Sichert Daten"}, {"text": "Maximale Fehler", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Verbindung", "correct": false, "because": "Fördert Kommunikation"}]');

