-- Netzwerk: OSI-Modell - Transportschicht
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Transportschicht eine zentrale Schicht im OSI-Modell?', 2, '[{"text": "Ja", "correct": true, "because": "Schicht 4, steuert Datenfluss"}, {"text": "Nein", "correct": false, "because": "Sie ist essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt die Transportschicht?', 3, '[{"text": "Zuverlässige Datenübertragung sicherstellen", "correct": true, "because": "Verbindet Anwendungen"}, {"text": "Daten dauerhaft speichern", "correct": false, "because": "Festplattenaufgabe"}, {"text": "Netzwerkadressierung", "correct": false, "because": "Netzwerkschicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Die Transportschicht verwendet Ports. b) Sie ist für physikalische Verbindungen zuständig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Schicht 1"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Protokolle gehören zur Transportschicht?', 4, '[{"text": "TCP", "correct": true, "because": "Zuverlässig"}, {"text": "Unklare Protokolle", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "UDP", "correct": true, "because": "Schnell"}, {"text": "IP", "correct": false, "because": "Netzwerkschicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Transportschicht ohne Netzwerkschicht arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Schicht 3 nötig"}, {"text": "Ja", "correct": false, "because": "Abhängigkeit vorhanden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt die Transportschicht im Netzwerk?', 3, '[{"text": "Datenfluss zwischen Anwendungen steuern", "correct": true, "because": "Verbindet Endpunkte"}, {"text": "Physikalische Verbindung", "correct": false, "because": "Schicht 1"}, {"text": "Datenpaketadressierung", "correct": false, "because": "Schicht 3"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Transportschicht nur für Internetkommunikation relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch lokale Netzwerke"}, {"text": "Ja", "correct": false, "because": "Breitere Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat TCP auf der Transportschicht?', 3, '[{"text": "Verbindungsorientierte Übertragung", "correct": true, "because": "Sichert Daten"}, {"text": "Datenpaket-Routing", "correct": false, "because": "IP-Aufgabe"}, {"text": "Physikalische Verbindung", "correct": false, "because": "Schicht 1"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) UDP ist verbindungslos. b) TCP ist schneller als UDP.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, UDP schneller"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne Transportschicht?', 3, '[{"text": "Keine zuverlässige Datenübertragung", "correct": true, "because": "Datenfluss fehlt"}, {"text": "Netzwerk wird schneller", "correct": false, "because": "Unsinn"}, {"text": "Daten werden automatisch gesichert", "correct": false, "because": "Andere Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Transportschicht ohne Ports arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Ports identifizieren Anwendungen"}, {"text": "Ja", "correct": false, "because": "Unpraktisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine Transportschicht-Funktion?', 3, '[{"text": "TCP-Port 80 für HTTP", "correct": true, "because": "Konkret und real"}, {"text": "IP-Adresse zuweisen", "correct": false, "because": "Schicht 3"}, {"text": "Kabel verbinden", "correct": false, "because": "Schicht 1"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Transportschicht nur für TCP relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch UDP"}, {"text": "Ja", "correct": false, "because": "Mehrere Protokolle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat die Transportschicht?', 4, '[{"text": "Portnummern", "correct": true, "because": "Identifizieren Anwendungen"}, {"text": "Unklare Daten", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Verbindungssteuerung", "correct": true, "because": "TCP-Funktion"}, {"text": "Datenflusskontrolle", "correct": true, "because": "Sichert Übertragung"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss die Transportschicht Daten verschlüsseln?', 2, '[{"text": "Nein", "correct": true, "because": "Optionale Schicht 5-7"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt UDP auf der Transportschicht?', 3, '[{"text": "Schnelle, verbindungslose Übertragung", "correct": true, "because": "Effizient"}, {"text": "Datenpaket-Routing", "correct": false, "because": "IP-Aufgabe"}, {"text": "Physikalische Verbindung", "correct": false, "because": "Schicht 1"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann die Transportschicht ohne Anwendungsschicht arbeiten?', 2, '[{"text": "Ja", "correct": true, "because": "Grundfunktion möglich"}, {"text": "Nein", "correct": false, "because": "Anwendungen nutzen sie"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor beeinflusst die Transportschicht?', 3, '[{"text": "Anwendungsanforderungen", "correct": true, "because": "Bestimmen Protokoll"}, {"text": "Monitorauflösung", "correct": false, "because": "Irrelevant"}, {"text": "Tastaturlayout", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Transportschicht sorgt für Fehlerkorrektur. b) Sie adressiert Geräte.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, Schicht 3"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen der Transportschicht?', 3, '[{"text": "Zuverlässige Datenlieferung", "correct": true, "because": "Fördert Kommunikation"}, {"text": "Maximale Unzuverlässigkeit", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Datensteuerung", "correct": false, "because": "Fördert Kontrolle"}]');

