-- Netzwerk: OSI-Modell - OSI-Modell generell
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist das OSI-Modell ein Standard für Netzwerkkommunikation?', 2, '[{"text": "Ja", "correct": true, "because": "Referenzmodell"}, {"text": "Nein", "correct": false, "because": "Es ist weit akzeptiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Hauptziel verfolgt das OSI-Modell?', 3, '[{"text": "Netzwerkkommunikation standardisieren", "correct": true, "because": "Fördert Verständnis"}, {"text": "Hardware direkt steuern", "correct": false, "because": "Abstraktes Modell"}, {"text": "Software entwickeln", "correct": false, "because": "Kein Entwicklungsmodell"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Das OSI-Modell hat 7 Schichten. b) Es ist ein physisches Gerät.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, abstrakt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schichten gehören zum OSI-Modell?', 4, '[{"text": "Bitübertragungsschicht", "correct": true, "because": "Schicht 1"}, {"text": "Unklare Schicht", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Netzwerkschicht", "correct": true, "because": "Schicht 3"}, {"text": "Anwendungsschicht", "correct": true, "because": "Schicht 7"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann Netzwerkkommunikation ohne das OSI-Modell funktionieren?', 2, '[{"text": "Ja", "correct": true, "because": "Modell ist theoretisch"}, {"text": "Nein", "correct": false, "because": "Praktische Umsetzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Rolle spielt das OSI-Modell?', 3, '[{"text": "Struktur für Netzwerkprotokolle bieten", "correct": true, "because": "Fördert Standardisierung"}, {"text": "Daten physisch speichern", "correct": false, "because": "Hardwareaufgabe"}, {"text": "Anwendungen entwickeln", "correct": false, "because": "Kein Entwicklungsmodell"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist das OSI-Modell nur für lokale Netzwerke relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch globale Netze"}, {"text": "Ja", "correct": false, "because": "Universelle Anwendung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aufgabe hat das OSI-Modell?', 3, '[{"text": "Netzwerkkommunikation in Schichten aufteilen", "correct": true, "because": "Modularität"}, {"text": "Daten verschlüsseln", "correct": false, "because": "Schicht 6"}, {"text": "Physische Verbindung herstellen", "correct": false, "because": "Schicht 1"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Das OSI-Modell ist ein Referenzmodell. b) Es ist ein Protokoll.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, kein Protokoll"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was passiert ohne das OSI-Modell?', 3, '[{"text": "Kommunikation bleibt möglich", "correct": true, "because": "Modell ist theoretisch"}, {"text": "Netzwerke funktionieren nicht", "correct": false, "because": "Praktische Umsetzung"}, {"text": "Daten werden schneller", "correct": false, "because": "Unsinn"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann eine Schicht ohne die darunterliegende arbeiten?', 2, '[{"text": "Nein", "correct": true, "because": "Schichten sind abhängig"}, {"text": "Ja", "correct": false, "because": "Unrealistisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Beispiel zeigt eine OSI-Schicht?', 3, '[{"text": "Transportschicht", "correct": true, "because": "Schicht 4"}, {"text": "Irgendwas", "correct": false, "because": "Zu vage"}, {"text": "Netzwerkkabel", "correct": false, "because": "Hardware"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist das OSI-Modell nur für Hardwareentwicklung relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Protokolle"}, {"text": "Ja", "correct": false, "because": "Breitere Nutzung"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale hat das OSI-Modell?', 4, '[{"text": "7 Schichten", "correct": true, "because": "Komplette Struktur"}, {"text": "Unklare Ebenen", "correct": false, "because": "Widerspricht Klarheit"}, {"text": "Modularität", "correct": true, "because": "Unabhängige Funktionen"}, {"text": "Abstraktion", "correct": true, "because": "Theoretisches Modell"}]'),
('00000000-0000-0000-0000-000000000000', 'Muss das OSI-Modell physisch implementiert werden?', 2, '[{"text": "Nein", "correct": true, "because": "Referenzmodell"}, {"text": "Ja", "correct": false, "because": "Abstrakt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schicht ist für die physische Übertragung zuständig?', 3, '[{"text": "Bitübertragungsschicht", "correct": true, "because": "Schicht 1"}, {"text": "Sitzungsschicht", "correct": false, "because": "Schicht 5"}, {"text": "Anwendungsschicht", "correct": false, "because": "Schicht 7"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann das OSI-Modell ohne Transportschicht funktionieren?', 2, '[{"text": "Nein", "correct": true, "because": "Datenfluss fehlt"}, {"text": "Ja", "correct": false, "because": "Schichten verbunden"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor beeinflusst das OSI-Modell?', 3, '[{"text": "Kommunikationsanforderungen", "correct": true, "because": "Bestimmen Schichten"}, {"text": "Monitorgröße", "correct": false, "because": "Irrelevant"}, {"text": "Tastaturlayout", "correct": false, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Das OSI-Modell hilft bei der Fehlersuche. b) Es ist ein Betriebssystem.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist falsch, kein OS"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht korrekt"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist zutreffend"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Nutzen des OSI-Modells?', 3, '[{"text": "Klare Struktur für Netzwerkdesign", "correct": true, "because": "Fördert Verständnis"}, {"text": "Maximale Unklarheit", "correct": false, "because": "Widerspricht Zweck"}, {"text": "Keine Standardisierung", "correct": false, "because": "Fördert Einheitlichkeit"}]');

