-- questions.sql (DDoS - Distributed Denial of Service, z. B. für IT-Sicherheit)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein DDoS-Angriff immer auf eine einzelne IP gerichtet?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch Netzwerke oder Dienste treffen"}, {"text": "Ja", "correct": false, "because": "Ziel kann variieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Methode nutzen Angreifer oft, um einen Server lahmzulegen?', 3, '[{"text": "SYN-Flood", "correct": true, "because": "Überlastet TCP-Verbindungen"}, {"text": "Ping-Request", "correct": false, "because": "Weniger effektiv"}, {"text": "SQL-Injection", "correct": false, "because": "Datenbankangriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen helfen gegen solche Angriffe?', 5, '[{"text": "Rate-Limiting", "correct": true, "because": "Begrenzt Anfragen"}, {"text": "Load-Balancing", "correct": true, "because": "Verteilt Last"}, {"text": "Höhere Bandbreite", "correct": false, "because": "Hilft nur begrenzt"}, {"text": "Statische IPs", "correct": false, "because": "Keine Abwehr"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein DDoS zielt auf Verfügbarkeit ab. b) Er stiehlt Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Datenklau ist nicht Ziel"}, {"text": "Beides stimmt "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Abwehr eines solchen Angriffs?', 4, '[{"text": "Traffic-Analyse", "correct": false, "because": "Erkennt Anomalien"}, {"text": "Firewall-Regeln", "correct": false, "because": "Filtert Schadtraffic"}, {"text": "Neuer Router", "correct": true, "because": "Hardware allein reicht nicht"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein Botnet immer dahintersteckt?', 2, '[{"text": "Nein", "correct": true, "because": "Auch andere Quellen möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Protokoll wird oft für solche Angriffe missbraucht?', 3, '[{"text": "UDP", "correct": true, "because": "Ermöglicht Amplification"}, {"text": "TCP", "correct": false, "because": "Weniger effektiv"}, {"text": "FTP", "correct": false, "because": "Dateitransfer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen eine Abwehr effektiv?', 5, '[{"text": "Früherkennung", "correct": true, "because": "Stoppt Eskalation"}, {"text": "Traffic-Filterung", "correct": true, "because": "Reduziert Schadlast"}, {"text": "Schnelle CPU", "correct": false, "because": "Nicht primär"}, {"text": "Mehr RAM", "correct": false, "because": "Hilft nur bedingt"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) DDoS nutzt verteilte Systeme. b) Es ist leicht zu blocken. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Blocken ist komplex"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um einen Angriff abzuwehren?', 4, '[{"text": "IDS", "correct": false, "because": "Erkennt Bedrohungen"}, {"text": "WAF", "correct": false, "because": "Schützt Webanwendungen"}, {"text": "Neue Festplatte", "correct": true, "because": "Irrelevant für Abwehr"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind solche Angriffe immer illegal?', 2, '[{"text": "Ja", "correct": true, "because": "Verstoß gegen IT-Sicherheitsgesetze"}, {"text": "Nein", "correct": false, "because": "Kaum legale Szenarien"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Dienste sind oft Ziele?', 4, '[{"text": "Webserver", "correct": true, "because": "Öffentlich erreichbar"}, {"text": "DNS-Server", "correct": true, "because": "Kritisch für Netzwerk"}, {"text": "Lokale Drucker", "correct": false, "because": "Weniger relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass mehr Bandbreite den Angriff stoppt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Angreifer skalieren mit"}, {"text": "Ja", "correct": false, "because": "Nur temporäre Linderung"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Abwehr?', 3, '[{"text": "Traffic-Mustererkennung", "correct": true, "because": "Identifiziert Angriff"}, {"text": "Manuelle Überprüfung", "correct": false, "because": "Zu langsam"}, {"text": "Neustart", "correct": false, "because": "Ineffektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein CDN hilft bei der Abwehr. b) Ein VPN verhindert den Angriff.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "VPN schützt nicht direkt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Schutzsystem?', 5, '[{"text": "Lastverteilung", "correct": true, "because": "Mindert Überlastung"}, {"text": "Anomalieerkennung", "correct": true, "because": "Frühwarnsystem"}, {"text": "Schnellere Festplatte", "correct": false, "because": "Irrelevant"}, {"text": "Mehr User", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Abwehr unwichtig?', 3, '[{"text": "Echtzeitüberwachung", "correct": false, "because": "Erkennt Angriffe"}, {"text": "Traffic-Filter", "correct": false, "because": "Reduziert Last"}, {"text": "Grafikkarte", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Kann ein Angriff auch von innen kommen?', 3, '[{"text": "Ja", "correct": true, "because": "Interne Botnets möglich"}, {"text": "Nein", "correct": false, "because": "Nicht ausschließlich extern"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein einzelner PC einen Angriff starten kann?', 2, '[{"text": "Nein", "correct": true, "because": "Verteilt erforderlich"}, {"text": "Ja", "correct": false, "because": "Zu wenig Impact"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool hilft bei der Analyse eines Angriffs?', 4, '[{"text": "Wireshark", "correct": true, "because": "Zeigt Traffic-Muster"}, {"text": "Photoshop", "correct": false, "because": "Bildbearbeitung"}, {"text": "Excel", "correct": false, "because": "Nur Datenverarbeitung"}]');


