-- questions.sql (Drive-by-Exploits - Cyberangriffe, z. B. für IT-Sicherheit)

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Drive-by-Exploit ein aktiver Angriff?', 2, '[{"text": "Nein", "correct": true, "because": "Passiv, Nutzeraktion nicht nötig"}, {"text": "Ja", "correct": false, "because": "Keine direkte Interaktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie wird ein Drive-by-Exploit typischerweise ausgeführt?', 3, '[{"text": "Über bösartige Webseiten", "correct": true, "because": "Schadcode im Browser"}, {"text": "Per E-Mail-Anhang", "correct": false, "because": "Andere Methode"}, {"text": "Durch Hardwarezugriff", "correct": false, "because": "Softwareangriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schwachstellen nutzen Drive-by-Exploits?', 5, '[{"text": "Veraltete Browser", "correct": true, "because": "Sicherheitslücken"}, {"text": "Plugins", "correct": true, "because": "Z. B. Flash"}, {"text": "Physische Ports", "correct": false, "because": "Softwareebene"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Drive-by-Exploits laden Schadcode automatisch. b) Sie erfordern Nutzerinteraktion.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Keine Interaktion nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich beim Schutz vor Drive-by-Exploits?', 4, '[{"text": "Software-Updates", "correct": false, "because": "Lücken schließen"}, {"text": "Antivirus", "correct": false, "because": "Erkennung wichtig"}, {"text": "Monitorauflösung", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Drive-by-Exploits physischen Zugriff benötigen?', 2, '[{"text": "Nein", "correct": true, "because": "Über Netzwerk ausgeführt"}, {"text": "Ja", "correct": false, "because": "Remote-Angriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Technologie wird oft für Drive-by-Exploits missbraucht?', 3, '[{"text": "JavaScript", "correct": true, "because": "Schadcode im Browser"}, {"text": "USB", "correct": false, "because": "Andere Methode"}, {"text": "Bluetooth", "correct": false, "because": "Kein Webzugriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Schutzmaßnahmen helfen gegen Drive-by-Exploits?', 5, '[{"text": "Aktuelle Software", "correct": true, "because": "Lücken schließen"}, {"text": "Ad-Blocker", "correct": true, "because": "Bösartige Werbung stoppen"}, {"text": "Schnellere CPU", "correct": false, "because": "Kein Schutz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Drive-by-Exploits nutzen Browser-Schwächen. b) Sie sind immer sichtbar. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Unsichtbar ausgeführt"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um mich vor Drive-by-Exploits zu schützen?', 4, '[{"text": "Firewall", "correct": false, "because": "Schützt Netzwerk"}, {"text": "Browser-Updates", "correct": false, "because": "Sicherheitslücken schließen"}, {"text": "Neuer Monitor", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Drive-by-Exploits immer zielgerichtet?', 2, '[{"text": "Nein", "correct": true, "because": "Oft breit gestreut"}, {"text": "Ja", "correct": false, "because": "Nicht immer gezielt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Software ist oft Ziel von Drive-by-Exploits?', 4, '[{"text": "Webbrowser", "correct": true, "because": "Haupteintrittspunkt"}, {"text": "Plugins", "correct": true, "because": "Z. B. Java"}, {"text": "Festplatten-Manager", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Drive-by-Exploits nur auf PCs laufen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Mobilgeräte"}, {"text": "Ja", "correct": false, "because": "Geräteübergreifend"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich beim Schutz vor Drive-by-Exploits?', 3, '[{"text": "Software-Updates", "correct": true, "because": "Lücken schließen"}, {"text": "Schneller Prozessor", "correct": false, "because": "Kein Schutz"}, {"text": "Neuer Router", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Drive-by-Exploits nutzen Exploit-Kits. b) Sie erfordern Downloads.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Automatisch ohne Download"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Angriffsvektoren nutzen Drive-by-Exploits?', 5, '[{"text": "Bösartige Webseiten", "correct": true, "because": "Schadcode einbetten"}, {"text": "Werbung", "correct": true, "because": "Malvertising"}, {"text": "Physische Medien", "correct": false, "because": "Kein Webzugriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei Drive-by-Exploits unwichtig?', 3, '[{"text": "Browser-Sicherheit", "correct": false, "because": "Kernschutz"}, {"text": "Antivirus", "correct": false, "because": "Erkennung"}, {"text": "Bildschirmgröße", "correct": true, "because": "Kein Einfluss"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Können Drive-by-Exploits ohne Internetzugang ausgeführt werden?', 3, '[{"text": "Nein", "correct": true, "because": "Webzugriff nötig"}, {"text": "Ja", "correct": false, "because": "Internet erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Drive-by-Exploits immer Malware installieren?', 2, '[{"text": "Ja", "correct": true, "because": "Hauptziel"}, {"text": "Nein", "correct": false, "because": "Meist Malware"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature macht Drive-by-Exploits gefährlich?', 4, '[{"text": "Automatische Ausführung", "correct": true, "because": "Ohne Nutzeraktion"}, {"text": "Sichtbare Warnungen", "correct": false, "because": "Unsichtbar"}, {"text": "Langsame Ausführung", "correct": false, "because": "Schnell"}]');

