-- Man_in_the_Middle_Angriffe.sql (Angriffe, bei denen Kommunikation abgefangen wird)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Man-in-the-Middle-Angriffe immer bemerkt werden. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Oft unbemerkt"}, {"text": "Ja", "correct": false, "because": "Schwer erkennbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, um ein IT-System gegen Man-in-the-Middle-Angriffe zu schützen?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Sichert Kommunikation"}, {"text": "Schnellere Server", "correct": false, "because": "Sekundär"}, {"text": "Bunte Oberfläche", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Techniken nutzen Man-in-the-Middle-Angriffe?', 5, '[{"text": "ARP-Spoofing", "correct": true, "because": "Täuscht Netzwerk"}, {"text": "DNS-Spoofing", "correct": true, "because": "Leitet Anfragen um"}, {"text": "Software-Updates", "correct": false, "because": "Kein Angriff"}, {"text": "Firewall", "correct": false, "because": "Schutz, kein Angriff"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Man-in-the-Middle-Angriffe können Daten abfangen. b) Sie sind immer leicht zu verhindern.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schwer zu verhindern"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein IT-System gegen Man-in-the-Middle-Angriffe schütze?', 4, '[{"text": "SSL/TLS", "correct": false, "because": "Sichert Kommunikation"}, {"text": "Netzwerksicherheit", "correct": false, "because": "Verhindert Zugriff"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Man-in-the-Middle-Angriffe nur in WLANs möglich sind?', 2, '[{"text": "Nein", "correct": true, "because": "Auch in LANs möglich"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich, wenn ich ein IT-System gegen Man-in-the-Middle-Angriffe sichere?', 3, '[{"text": "Vertraulichkeit", "correct": true, "because": "Schützt Daten"}, {"text": "Schnellere Verbindung", "correct": false, "because": "Sekundär"}, {"text": "Weniger Sicherheit", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen schützen vor Man-in-the-Middle-Angriffen?', 5, '[{"text": "HTTPS", "correct": true, "because": "Verschlüsselt Daten"}, {"text": "VPN", "correct": true, "because": "Sichert Verbindung"}, {"text": "Schnellere Server", "correct": false, "because": "Kein Schutz"}, {"text": "Bunte Kabel", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Man-in-the-Middle-Angriffe können Passwörter abfangen. b) Sie sind immer physisch durchgeführt. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch digital möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um ein IT-System gegen Man-in-the-Middle-Angriffe zu schützen?', 4, '[{"text": "Zertifikate", "correct": false, "because": "Sichern Authentizität"}, {"text": "Verschlüsselung", "correct": false, "because": "Schützt Daten"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Man-in-the-Middle-Angriffe nur in öffentlichen Netzwerken möglich?', 2, '[{"text": "Nein", "correct": true, "because": "Auch private Netzwerke betroffen"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet Schutz vor Man-in-the-Middle-Angriffen?', 4, '[{"text": "Datensicherheit", "correct": true, "because": "Verhindert Abfangen"}, {"text": "Vertrauenswürdige Kommunikation", "correct": true, "because": "Sichert Integrität"}, {"text": "Schnellere Server", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Man-in-the-Middle-Angriffe nur Daten stehlen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch manipulierbar"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um Man-in-the-Middle-Angriffe in einem Netzwerk zu erkennen?', 3, '[{"text": "Netzwerküberwachung", "correct": true, "because": "Zeigt Anomalien"}, {"text": "Schnellere Router", "correct": false, "because": "Kein Erkennungstool"}, {"text": "Bunte Diagramme", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Man-in-the-Middle-Angriffe können durch Verschlüsselung verhindert werden. b) Sie sind immer leicht erkennbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Schwer erkennbar"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich, um Man-in-the-Middle-Angriffe zu verhindern?', 5, '[{"text": "SSL/TLS", "correct": true, "because": "Verschlüsselt Daten"}, {"text": "Authentifizierung", "correct": true, "because": "Sichert Identität"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich ein IT-System gegen Man-in-the-Middle-Angriffe schütze?', 3, '[{"text": "Zertifikatsprüfung", "correct": false, "because": "Sichert Authentizität"}, {"text": "VPN", "correct": false, "because": "Sichert Verbindung"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Sicherheitsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Können Man-in-the-Middle-Angriffe durch HTTPS komplett verhindert werden?', 3, '[{"text": "Nein", "correct": true, "because": "Angriffe weiter möglich"}, {"text": "Ja", "correct": false, "because": "Nicht absolut sicher"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Man-in-the-Middle-Angriffe nur Daten abfangen?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Manipulation möglich"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend, um Man-in-the-Middle-Angriffe zu verhindern?', 4, '[{"text": "End-to-End-Verschlüsselung", "correct": true, "because": "Sichert Kommunikation"}, {"text": "Schnellere Server", "correct": false, "because": "Irrelevant"}, {"text": "Bunte Kabel", "correct": false, "because": "Ästhetisch"}]');

