-- Marktgaengige_IT-Systeme.sql (Gängige IT-Systeme auf dem Markt im IT-Kontext)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass marktgängige IT-Systeme immer teuer sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten variieren je nach System"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich marktgängige IT-Systeme für eine Firma auswähle?', 3, '[{"text": "Funktionalität", "correct": true, "because": "Erfüllt Anforderungen"}, {"text": "Schnellste Installation", "correct": false, "because": "Qualität zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Typen von marktgängigen IT-Systemen gibt es?', 5, '[{"text": "ERP-Systeme", "correct": true, "because": "Für Unternehmensprozesse"}, {"text": "CRM-Systeme", "correct": true, "because": "Für Kundenmanagement"}, {"text": "Büromöbel", "correct": false, "because": "Kein IT-System"}, {"text": "Farbanalyse", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Marktgängige IT-Systeme unterstützen Geschäftsprozesse. b) Sie sind immer cloudbasiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch lokal möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich marktgängige IT-Systeme für eine Firma bewerte?', 4, '[{"text": "Skalierbarkeit", "correct": false, "because": "Wichtig für Wachstum"}, {"text": "Kosten", "correct": false, "because": "Bestimmen Wirtschaftlichkeit"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Systemfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob marktgängige IT-Systeme immer proprietär sind?', 2, '[{"text": "Nein", "correct": true, "because": "Auch Open Source möglich"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich, wenn ich marktgängige IT-Systeme auswähle?', 3, '[{"text": "Prozesseffizienz", "correct": true, "because": "Optimiert Abläufe"}, {"text": "Schnellste Installation", "correct": false, "because": "Funktion wichtiger"}, {"text": "Weniger Funktionen", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale sind bei marktgängigen IT-Systemen entscheidend?', 5, '[{"text": "Zuverlässigkeit", "correct": true, "because": "Sichert Betrieb"}, {"text": "Benutzerfreundlichkeit", "correct": true, "because": "Fördert Akzeptanz"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Marktgängige IT-Systeme sind oft modular. b) Sie sind immer für Großfirmen gedacht. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch für KMU"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um marktgängige IT-Systeme zu bewerten?', 4, '[{"text": "Leistungsfähigkeit", "correct": false, "because": "Wichtiges Kriterium"}, {"text": "Wirtschaftlichkeit", "correct": false, "because": "Bestimmt Kosten"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Systemfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind marktgängige IT-Systeme immer cloudbasiert?', 2, '[{"text": "Nein", "correct": true, "because": "Auch lokal möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten marktgängige IT-Systeme?', 4, '[{"text": "Prozessautomatisierung", "correct": true, "because": "Steigert Effizienz"}, {"text": "Breite Unterstützung", "correct": true, "because": "Viele Anbieter"}, {"text": "Schnellere Hardware", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass marktgängige IT-Systeme nur für Unternehmen sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Privatnutzer"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um marktgängige IT-Systeme zu beurteilen?', 3, '[{"text": "Funktionsumfang", "correct": true, "because": "Erfüllt Bedarf"}, {"text": "Günstigster Preis", "correct": false, "because": "Qualität wichtiger"}, {"text": "Bunte Oberfläche", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Marktgängige IT-Systeme sind skalierbar. b) Sie sind immer proprietär.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Auch Open Source"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei marktgängigen IT-Systemen?', 5, '[{"text": "Kosten", "correct": true, "because": "Bestimmen Budget"}, {"text": "Support", "correct": true, "because": "Sichert Betrieb"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich marktgängige IT-Systeme auswähle?', 3, '[{"text": "Benutzerfreundlichkeit", "correct": false, "because": "Fördert Akzeptanz"}, {"text": "Kompatibilität", "correct": false, "because": "Sichert Integration"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Systemfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind marktgängige IT-Systeme immer für Großunternehmen?', 3, '[{"text": "Nein", "correct": true, "because": "Auch für KMU"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob marktgängige IT-Systeme immer komplex sind?', 2, '[{"text": "Nein", "correct": true, "because": "Auch einfache Systeme"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für marktgängige IT-Systeme?', 4, '[{"text": "Funktionalität", "correct": true, "because": "Erfüllt Bedarf"}, {"text": "Schnellste Installation", "correct": false, "

