-- Medienzugriffsverfahren.sql (Methoden zur Steuerung des Zugriffs auf ein Übertragungsmedium in Netzwerken)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Medienzugriffsverfahren immer Kollisionen verhindern. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Nicht alle vermeiden Kollisionen"}, {"text": "Ja", "correct": false, "because": "Abhängig vom Verfahren"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich ein Medienzugriffsverfahren für ein Netzwerk auswähle?', 3, '[{"text": "Effizienz", "correct": true, "because": "Optimiert Datenfluss"}, {"text": "Schnellste Installation", "correct": false, "because": "Effektivität zählt"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Medienzugriffsverfahren werden in Netzwerken genutzt?', 5, '[{"text": "CSMA/CD", "correct": true, "because": "Kollisionserkennung"}, {"text": "Token Passing", "correct": true, "because": "Kollisionsfrei"}, {"text": "Büroplanung", "correct": false, "because": "Kein Verfahren"}, {"text": "Farbanalyse", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) CSMA/CD erkennt Kollisionen. b) Alle Medienzugriffsverfahren sind kollisionsfrei.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Nicht alle kollisionsfrei"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich ein Medienzugriffsverfahren für ein Netzwerk auswähle?', 4, '[{"text": "Netzwerkauslastung", "correct": false, "because": "Beeinflusst Effizienz"}, {"text": "Übertragungsmedium", "correct": false, "because": "Bestimmt Verfahren"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Medienzugriffsverfahren nur für WLAN gelten?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für LAN"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolge ich mit einem Medienzugriffsverfahren?', 3, '[{"text": "Kollisionsvermeidung", "correct": true, "because": "Sichert Datenfluss"}, {"text": "Schnellste Installation", "correct": false, "because": "Effizienz wichtiger"}, {"text": "Weniger Daten", "correct": false, "because": "Nicht Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften sind bei Medienzugriffsverfahren entscheidend?', 5, '[{"text": "Effizienz", "correct": true, "because": "Optimiert Übertragung"}, {"text": "Kollisionsmanagement", "correct": true, "because": "Verhindert Datenverlust"}, {"text": "Farbschema", "correct": false, "because": "Irrelevant"}, {"text": "Bürogröße", "correct": false, "because": "Kein Faktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Token Passing vermeidet Kollisionen. b) Alle Medienzugriffsverfahren sind gleich schnell. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Geschwindigkeit variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht, um ein Medienzugriffsverfahren auszuwählen?', 4, '[{"text": "Netzwerktyp", "correct": false, "because": "Bestimmt Verfahren"}, {"text": "Datenverkehr", "correct": false, "because": "Beeinflusst Effizienz"}, {"text": "Büroausstattung", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Medienzugriffsverfahren nur für drahtlose Netzwerke relevant?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kabelgebunden"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein Medienzugriffsverfahren?', 4, '[{"text": "Stabile Übertragung", "correct": true, "because": "Verhindert Kollisionen"}, {"text": "Effiziente Nutzung", "correct": true, "because": "Optimiert Medium"}, {"text": "Schnellere Projekte", "correct": false, "because": "Kein direkter Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Medienzugriffsverfahren immer CSMA/CD nutzen. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Andere Verfahren möglich"}, {"text": "Ja", "correct": false, "because": "Zu eingeschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was wähle ich, um ein Medienzugriffsverfahren für ein Netzwerk auszuwählen?', 3, '[{"text": "Netzwerkanforderungen", "correct": true, "because": "Bestimmen Verfahren"}, {"text": "Schnellste Installation", "correct": false, "because": "Effizienz wichtiger"}, {"text": "Bunte Kabel", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) CSMA/CA wird in WLAN genutzt. b) Alle Verfahren sind gleich effizient.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Effizienz variiert"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte berücksichtige ich bei Medienzugriffsverfahren?', 5, '[{"text": "Netzwerkgröße", "correct": true, "because": "Beeinflusst Auswahl"}, {"text": "Datenverkehrsmenge", "correct": true, "because": "Bestimmt Effizienz"}, {"text": "Bürogröße", "correct": false, "because": "Irrelevant"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist unwichtig, wenn ich ein Medienzugriffsverfahren auswähle?', 3, '[{"text": "Übertragungsmedium", "correct": false, "because": "Bestimmt Verfahren"}, {"text": "Kollisionsrate", "correct": false, "because": "Beeinflusst Effizienz"}, {"text": "Büromöbel", "correct": true, "because": "Kein Netzwerkfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Medienzugriffsverfahren nur für Ethernet-Netzwerke relevant?', 3, '[{"text": "Nein", "correct": true, "because": "Auch andere Netzwerke"}, {"text": "Ja", "correct": false, "because": "Zu begrenzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Medienzugriffsverfahren immer kollisionsfrei sind?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig vom Verfahren"}, {"text": "Ja", "correct": false, "because": "Nicht immer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Element ist entscheidend für Medienzugriffsverfahren?', 4, '[{"text": "Effizientes Management", "correct": true, "because": "Sichert Datenfluss"}, {"text": "Schnellste Installation", "correct": false, "because": "Effizienz zählt"}, {"text": "Büroausstattung", "correct": false, "because": "Irrelevant"}]');

