INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Speichert eine Objektdatenbank nur primitive Datentypen?', 2, '[{"text": "Nein", "correct": true, "because": "Sie speichert komplexe Objekte mit Beziehungen"}, {"text": "Ja", "correct": false, "because": "Nicht auf primitive Typen beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptvorteil, wenn ich Objekte direkt speichere?', 3, '[{"text": "Vermeidung von Objekt-Relationalem Mapping", "correct": true, "because": "Reduziert Komplexität"}, {"text": "Höhere Schreibgeschwindigkeit", "correct": false, "because": "Nicht primär entscheidend"}, {"text": "Kleinere Datenbankgröße", "correct": false, "because": "Kein direkter Effekt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften unterstützt eine solche Datenbank?', 5, '[{"text": "Vererbung", "correct": true, "because": "Objektorientierte Prinzipien"}, {"text": "Polymorphismus", "correct": true, "because": "Unterstützt flexible Typen"}, {"text": "SQL-Standard", "correct": false, "because": "Eher relationale Datenbanken"}, {"text": "Tabellenstruktur", "correct": false, "because": "Objekte statt Tabellen"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Objektdatenbanken nutzen Klassen. b) Sie ersetzen immer relationale Modelle.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist kontextabhängig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht immer wahr"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Wahl einer Objektdatenbank?', 4, '[{"text": "Abfrageperformance", "correct": false, "because": "Wichtig für Effizienz"}, {"text": "Objektkomplexität", "correct": false, "because": "Kern der Speicherung"}, {"text": "Tabellenlayout", "correct": true, "because": "Relevant für relationale Systeme"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Objektdatenbank SQL benötigt?', 2, '[{"text": "Nein", "correct": true, "because": "Eigene Abfragesprachen möglich"}, {"text": "Ja", "correct": false, "because": "SQL nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature ist entscheidend für die Arbeit mit Objekten?', 3, '[{"text": "Objektidentität", "correct": true, "because": "Eindeutige Referenzierung"}, {"text": "Primärschlüssel", "correct": false, "because": "Relationale Konzepte"}, {"text": "Indizierung", "correct": false, "because": "Sekundär relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind bei der Verwaltung von Objekten wichtig?', 5, '[{"text": "Beziehungshandling", "correct": true, "because": "Verknüpfung von Objekten"}, {"text": "Kapselung", "correct": true, "because": "Schützt Objektintegrität"}, {"text": "Festes Schema", "correct": false, "because": "Weniger flexibel"}, {"text": "Hohe Kompression", "correct": false, "because": "Kein primäres Ziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Objektdatenbanken sind für Multimedia ideal. b) Sie sind immer langsamer als relationale. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) hängt von Anwendung ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht universell"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine Objektdatenbank?', 4, '[{"text": "Objektserialisierung", "correct": false, "because": "Wichtig für Persistenz"}, {"text": "Referenzintegrität", "correct": false, "because": "Schützt Beziehungen"}, {"text": "Normierte Tabellen", "correct": true, "because": "Relationale Struktur"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Objektdatenbanken nur für kleine Projekte?', 2, '[{"text": "Nein", "correct": true, "because": "Skalierbar für komplexe Anwendungen"}, {"text": "Ja", "correct": false, "because": "Breite Einsatzmöglichkeiten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Daten speichert so eine Datenbank effektiv?', 4, '[{"text": "Hierarchische Objekte", "correct": true, "because": "Unterstützt Baumstrukturen"}, {"text": "Multimedia-Inhalte", "correct": true, "because": "Komplexe Datentypen"}, {"text": "Einfache Tabellen", "correct": false, "because": "Relationale Stärke"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Objektdatenbanken keine Joins brauchen. Stimmt das?', 2, '[{"text": "Ja", "correct": true, "because": "Beziehungen sind direkt modelliert"}, {"text": "Nein", "correct": false, "because": "Joins oft überflüssig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Arbeit mit einer Objektdatenbank?', 3, '[{"text": "Modellierung von Beziehungen", "correct": true, "because": "Fördert Konsistenz"}, {"text": "Schnelle Installation", "correct": false, "because": "Sekundär"}, {"text": "Minimale Speichergröße", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Objektdatenbanken sind objektorientiert. b) Sie benötigen immer ODBC.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "ODBC nicht zwingend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine Objektdatenbank?', 5, '[{"text": "Direkte Objektspeicherung", "correct": true, "because": "Vereinfacht Entwicklung"}, {"text": "Flexible Strukturen", "correct": true, "because": "Passt sich komplexen Daten an"}, {"text": "Hohe Kompression", "correct": false, "because": "Kein Fokus"}, {"text": "Tabellenoptimierung", "correct": false, "because": "Relationale Systeme"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einer Objektdatenbank unwichtig?', 3, '[{"text": "Objektbeziehungen", "correct": false, "because": "Kern der Funktionalität"}, {"text": "Skalierbarkeit", "correct": false, "because": "Wichtig für große Daten"}, {"text": "Feste Schemata", "correct": true, "because": "Flexibilität steht im Vordergrund"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzt eine Objektdatenbank NoSQL?', 3, '[{"text": "Nein", "correct": true, "because": "Unterschiedliche Ansätze"}, {"text": "Ja", "correct": false, "because": "NoSQL ist breiter gefasst"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob eine Objektdatenbank für Echtzeitanwendungen geeignet ist?', 2, '[{"text": "Ja", "correct": true, "because": "Effiziente Objektabfragen"}, {"text": "Nein", "correct": false, "because": "Abhängig von Design, aber möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Nutzung einer Objektdatenbank?', 4, '[{"text": "Verwaltung komplexer CAD-Modelle", "correct": true, "because": "Unterstützt hierarchische Daten"}, {"text": "Einfache CSV-Importe", "correct": false, "because": "Relationale Systeme effizienter"}, {"text": "Statische Webseiten", "correct": false, "because": "Kein komplexer Bedarf"}]');


