-- Objektorientiertes Programmierparadigma.sql (Prinzipien und Konzepte der objektorientierten Programmierung)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist Vererbung immer notwendig für objektorientierte Programmierung?', 2, '[{"text": "Nein", "correct": true, "because": "Kapselung und Polymorphismus reichen oft"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Prinzip wende ich an, wenn ich Daten und Methoden bündle?', 3, '[{"text": "Kapselung", "correct": true, "because": "Schützt Daten durch Zugriffskontrolle"}, {"text": "Polymorphismus", "correct": false, "because": "Bezieht sich auf flexible Typen"}, {"text": "Abstraktion", "correct": false, "because": "Vereinfacht Modelle"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale machen ein Programm objektorientiert?', 5, '[{"text": "Kapselung", "correct": true, "because": "Bündelt Daten und Logik"}, {"text": "Vererbung", "correct": true, "because": "Fördert Wiederverwendung"}, {"text": "Statische Typisierung", "correct": false, "because": "Nicht spezifisch"}, {"text": "Prozedurale Abläufe", "correct": false, "because": "Anderes Paradigma"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Polymorphismus erlaubt flexible Methodenaufrufe. b) Kapselung erzwingt öffentliche Attribute.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kapselung schützt Attribute"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich eine Klasse entwerfe?', 4, '[{"text": "Attribute", "correct": false, "because": "Definiert Zustand"}, {"text": "Methoden", "correct": false, "because": "Definiert Verhalten"}, {"text": "Farbschema", "correct": true, "because": "Irrelevant für Funktionalität"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Abstraktion dasselbe wie Kapselung ist?', 2, '[{"text": "Nein", "correct": true, "because": "Abstraktion vereinfacht, Kapselung schützt"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Konzepte"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Konzept nutze ich, um Code in einer Superklasse wiederzuverwenden?', 3, '[{"text": "Vererbung", "correct": true, "because": "Ermöglicht Wiederverwendung"}, {"text": "Polymorphismus", "correct": false, "because": "Bezieht sich auf Typflexibilität"}, {"text": "Kapselung", "correct": false, "because": "Schützt Daten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet mir objektorientierte Programmierung?', 5, '[{"text": "Wiederverwendbarkeit", "correct": true, "because": "Durch Vererbung und Module"}, {"text": "Wartbarkeit", "correct": true, "because": "Klar strukturierter Code"}, {"text": "Maximale Performance", "correct": false, "because": "Nicht primär"}, {"text": "Einfache Syntax", "correct": false, "because": "Nicht zwangsläufig"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Kapselung verhindert Zugriff. b) Polymorphismus benötigt immer Vererbung. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Polymorphismus auch über Interfaces"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für ein objektorientiertes Design?', 4, '[{"text": "Klassen", "correct": false, "because": "Grundbausteine"}, {"text": "Objekte", "correct": false, "because": "Instanzen von Klassen"}, {"text": "Globale Variablen", "correct": true, "because": "Gegen Kapselung"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist objektorientierte Programmierung nur für große Projekte?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für kleine Projekte nützlich"}, {"text": "Ja", "correct": false, "because": "Skalierbar für alle Größen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prinzipien wende ich in einem objektorientierten Programm an?', 4, '[{"text": "Abstraktion", "correct": true, "because": "Vereinfacht Modelle"}, {"text": "Polymorphismus", "correct": true, "because": "Erlaubt Flexibilität"}, {"text": "Prozedurale Schleifen", "correct": false, "because": "Anderes Paradigma"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Vererbung immer die beste Lösung ist. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Komposition oft flexibler"}, {"text": "Ja", "correct": false, "because": "Kontextabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einem objektorientierten Entwurf?', 3, '[{"text": "Klare Struktur", "correct": true, "because": "Fördert Wartbarkeit"}, {"text": "Maximale Geschwindigkeit", "correct": false, "because": "Sekundär"}, {"text": "Minimale Zeilen", "correct": false, "because": "Lesbarkeit wichtiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Objekte repräsentieren Instanzen. b) Klassen sind nur für Daten.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Klassen definieren Verhalten"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Konzepte fördern Wiederverwendbarkeit?', 5, '[{"text": "Vererbung", "correct": true, "because": "Erlaubt Code-Sharing"}, {"text": "Komposition", "correct": true, "because": "Flexibles Design"}, {"text": "Globale Funktionen", "correct": false, "because": "Weniger strukturiert"}, {"text": "Statische Methoden", "correct": false, "because": "Begrenzt flexibel"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem objektorientierten Programm unwichtig?', 3, '[{"text": "Kapselung", "correct": false, "because": "Schützt Daten"}, {"text": "Abstraktion", "correct": false, "because": "Vereinfacht Modelle"}, {"text": "Bildschirmauflösung", "correct": true, "because": "Kein Programmierfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ersetzt Polymorphismus die Vererbung?', 3, '[{"text": "Nein", "correct": true, "because": "Ergänzt, aber ersetzt nicht"}, {"text": "Ja", "correct": false, "because": "Unterschiedliche Zwecke"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Kapselung die Performance steigert?', 2, '[{"text": "Nein", "correct": true, "because": "Fokus auf Sicherheit, nicht Geschwindigkeit"}, {"text": "Ja", "correct": false, "because": "Kein direkter Performance-Vorteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was mache ich, wenn ich eine Klasse für mehrere Typen wiederverwendbar machen will?', 4, '[{"text": "Interfaces nutzen", "correct": true, "because": "Fördert Polymorphismus"}, {"text": "Statische Methoden", "correct": false, "because": "Begrenzt Flexibilität"}, {"text": "Private Attribute", "correct": false, "because": "Nur Kapselung"}]');


