-- Off-Premises Backup.sql (Datensicherung außerhalb des eigenen Standorts)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Off-Premises Backup immer cloudbasiert?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch physische Medien umfassen"}, {"text": "Ja", "correct": false, "because": "Cloud ist nur eine Option"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist entscheidend, wenn ich meine Daten extern sichere?', 3, '[{"text": "Verschlüsselung", "correct": true, "because": "Schützt Daten während Übertragung"}, {"text": "Hohe lokale Speicherkapazität", "correct": false, "because": "Weniger relevant"}, {"text": "Manuelle Übertragung", "correct": false, "because": "Zu aufwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Merkmale machen eine externe Datensicherung effektiv?', 5, '[{"text": "Redundanz", "correct": true, "because": "Verhindert Datenverlust"}, {"text": "Automatisierung", "correct": true, "because": "Spart Zeit und Fehler"}, {"text": "Hohe Downloadgeschwindigkeit", "correct": false, "because": "Sekundär"}, {"text": "Lokale Installation", "correct": false, "because": "Nicht erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Off-Premises Backups schützen vor physischen Schäden. b) Sie sind immer teurer als lokale Backups.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) hängt von Anbieter ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht immer wahr"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung einer externen Datensicherung?', 4, '[{"text": "Wiederherstellungszeit", "correct": false, "because": "Entscheidend für Ausfallzeiten"}, {"text": "Datensicherheit", "correct": false, "because": "Schützt Vertraulichkeit"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Backups"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob externe Backups immer Internet benötigen?', 2, '[{"text": "Nein", "correct": true, "because": "Physische Medien möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium ist bei einer externen Sicherung entscheidend?', 3, '[{"text": "Datenintegrität", "correct": true, "because": "Sichert korrekte Wiederherstellung"}, {"text": "Lokale Speichergröße", "correct": false, "because": "Weniger relevant"}, {"text": "Manuelle Prüfung", "correct": false, "because": "Automatisierung bevorzugt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen erhöhen die Sicherheit bei externen Backups?', 5, '[{"text": "Ende-zu-Ende-Verschlüsselung", "correct": true, "because": "Schützt Daten"}, {"text": "Regelmäßige Tests", "correct": true, "because": "Sichert Wiederherstellbarkeit"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Nur für Geschwindigkeit"}, {"text": "Lokale Kopien", "correct": false, "because": "Kein Off-Premises"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass externe Backups immer langsamer sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Hängt von Infrastruktur ab"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig langsamer"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei einer Datensicherung außerhalb?', 4, '[{"text": "Zuverlässigkeit des Anbieters", "correct": true, "because": "Verhindert Ausfälle"}, {"text": "Minimale Kosten", "correct": false, "because": "Qualität wichtiger"}, {"text": "Manuelle Übertragung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Externe Backups sind standortresilient. b) Sie ersetzen lokale Backups.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist nicht universell"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature finde ich bei einer externen Sicherung entscheidend?', 4, '[{"text": "Automatische Planung", "correct": true, "because": "Reduziert menschliche Fehler"}, {"text": "Hohe lokale Rechenleistung", "correct": false, "because": "Weniger relevant"}, {"text": "Manuelle Validierung", "correct": false, "because": "Zu aufwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass externe Backups immer öffentlich sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Privatsphäre durch Verschlüsselung"}, {"text": "Ja", "correct": false, "because": "Sicherheit gewährleistet"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine externe Datensicherung?', 3, '[{"text": "Zugriffskontrollen", "correct": false, "because": "Schützt unbefugten Zugriff"}, {"text": "Vertragsbedingungen", "correct": false, "because": "Regeln Nutzung"}, {"text": "Lokale Festplatten", "correct": true, "because": "Off-Premises extern"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind Off-Premises Backups immer teurer?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten variieren je nach Anbieter"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig teurer"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine externe Datensicherung?', 4, '[{"text": "Katastrophenschutz", "correct": true, "because": "Schützt vor lokalen Schäden"}, {"text": "Geografische Trennung", "correct": true, "because": "Erhöht Sicherheit"}, {"text": "Echtzeitverarbeitung", "correct": false, "because": "Nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob externe Backups immer automatisch sind?', 2, '[{"text": "Nein", "correct": true, "because": "Manuelle Optionen existieren"}, {"text": "Ja", "correct": false, "because": "Automatisierung optional"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Wiederherstellung aus einem externen Backup wichtig?', 3, '[{"text": "Schnelle Zugriffszeit", "correct": true, "because": "Minimiert Ausfallzeiten"}, {"text": "Lokale Speichergröße", "correct": false, "because": "Weniger relevant"}, {"text": "Manuelle Prüfung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Schützen externe Backups vor Ransomware?', 3, '[{"text": "Ja", "correct": true, "because": "Isolierte Kopien sind sicher"}, {"text": "Nein", "correct": false, "because": "Schutz ist effektiv"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einer externen Datensicherung?', 4, '[{"text": "Sicherung kritischer Unternehmensdaten", "correct": true, "because": "Schützt vor Verlust"}, {"text": "Echtzeit-Datenbankverarbeitung", "correct": false, "because": "Andere Technologie"}, {"text": "Lokale Testumgebung", "correct": false, "because": "Nicht Off-Premises"}]');

