-- Output-Stream.sql (Datenfluss für die Ausgabe in Programmierung und IT-Systemen)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist ein Ausgabefluss immer an eine Datei gebunden?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch Konsole oder Netzwerk sein"}, {"text": "Ja", "correct": false, "because": "Nicht auf Dateien beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptziel, wenn ich einen Datenfluss für die Ausgabe nutze?', 3, '[{"text": "Effiziente Datenübertragung", "correct": true, "because": "Sichert schnelle Ausgabe"}, {"text": "Maximale Speicherung", "correct": false, "because": "Nicht primär"}, {"text": "Manuelle Formatierung", "correct": false, "because": "Zu aufwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Eigenschaften machen einen solchen Datenfluss nützlich?', 5, '[{"text": "Pufferung", "correct": true, "because": "Optimiert Schreibvorgänge"}, {"text": "Flexibilität", "correct": true, "because": "Unterstützt verschiedene Ziele"}, {"text": "Hohe Latenz", "correct": false, "because": "Eher ein Nachteil"}, {"text": "Feste Struktur", "correct": false, "because": "Einschränkt Anpassung"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein Ausgabefluss kann Daten serialisieren. b) Er liest immer Eingaben.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) ist für Eingabeflüsse"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich, wenn ich einen Datenfluss für die Ausgabe implementiere?', 4, '[{"text": "Fehlerbehandlung", "correct": false, "because": "Sichert Robustheit"}, {"text": "Zielmedium", "correct": false, "because": "Bestimmt Ausgabe"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Funktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob ein solcher Fluss immer textbasiert ist?', 2, '[{"text": "Nein", "correct": true, "because": "Kann auch binär sein"}, {"text": "Ja", "correct": false, "because": "Nicht auf Text beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Merkmal ist für die Performance entscheidend?', 3, '[{"text": "Puffergröße", "correct": true, "because": "Reduziert Schreibzugriffe"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Sekundär"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Anwendungen nutzen solche Datenflüsse?', 5, '[{"text": "Dateischreiben", "correct": true, "because": "Speichert Daten"}, {"text": "Netzwerkkommunikation", "correct": true, "because": "Sendet Daten"}, {"text": "Eingabeverarbeitung", "correct": false, "because": "Anderer Fluss"}, {"text": "Hardwaresteuerung", "correct": false, "because": "Spezialisierte Schnittstellen"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Solche Flüsse unterstützen Pufferung. b) Sie sind immer langsam. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) hängt von Implementierung ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für einen solchen Datenfluss?', 4, '[{"text": "Ausgabeziel", "correct": false, "because": "Definiert Zielmedium"}, {"text": "Fehlerbehandlung", "correct": false, "because": "Sichert Stabilität"}, {"text": "3D-Rendering", "correct": true, "because": "Kein Ausgabefaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind solche Flüsse nur für Dateien geeignet?', 2, '[{"text": "Nein", "correct": true, "because": "Auch für Konsole oder Netzwerk"}, {"text": "Ja", "correct": false, "because": "Vielseitig einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei solchen Datenflüssen?', 4, '[{"text": "Ressourcenmanagement", "correct": true, "because": "Puffer kann überlaufen"}, {"text": "Datenverlust", "correct": true, "because": "Bei schlechter Handhabung"}, {"text": "Hohe Auflösung", "correct": false, "because": "Kein Flussproblem"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass solche Flüsse immer synchron sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Können asynchron sein"}, {"text": "Ja", "correct": false, "because": "Asynchrone Optionen existieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Implementierung eines solchen Flusses?', 3, '[{"text": "Effizienz", "correct": true, "because": "Reduziert Verzögerungen"}, {"text": "Maximale Speicherung", "correct": false, "because": "Nicht primär"}, {"text": "Manuelle Pufferung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Ein solcher Fluss kann formatiert ausgeben. b) Er speichert immer Daten dauerhaft.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) hängt vom Ziel ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet ein solcher Datenfluss?', 5, '[{"text": "Flexibles Ziel", "correct": true, "because": "Unterstützt Dateien oder Netzwerk"}, {"text": "Optimierte Ausgabe", "correct": true, "because": "Pufferung reduziert Zugriffe"}, {"text": "Eingabeverarbeitung", "correct": false, "because": "Anderer Fluss"}, {"text": "Hohe Komplexität", "correct": false, "because": "Eher ein Nachteil"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei einem solchen Datenfluss unwichtig?', 3, '[{"text": "Datenintegrität", "correct": false, "because": "Sichert korrekte Ausgabe"}, {"text": "Schließmechanismen", "correct": false, "because": "Vermeiden Ressourcenlecks"}, {"text": "Musikwiedergabe", "correct": true, "because": "Kein Flussmerkmal"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erfordern solche Flüsse immer eine Netzwerkverbindung?', 3, '[{"text": "Nein", "correct": true, "because": "Können lokal ausgeben"}, {"text": "Ja", "correct": false, "because": "Netzwerk optional"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob solche Flüsse für Echtzeitdaten geeignet sind?', 2, '[{"text": "Ja", "correct": true, "because": "Mit richtiger Implementierung"}, {"text": "Nein", "correct": false, "because": "Echtzeit möglich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zu einem solchen Datenfluss?', 4, '[{"text": "Logdateien schreiben", "correct": true, "because": "Typische Ausgabeanwendung"}, {"text": "Datenbankabfragen", "correct": false, "because": "Eher Eingabefluss"}, {"text": "Hardwaresteuerung", "correct": false, "because": "Spezialisierte Schnittstellen"}]');


