-- Outsourcing.sql (Auslagerung von IT-Diensten oder Prozessen an Dritte)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Ist die Auslagerung von Diensten immer kostensparend?', 2, '[{"text": "Nein", "correct": true, "because": "Kosten hängen von Anbieter und Umfang ab"}, {"text": "Ja", "correct": false, "because": "Nicht garantiert günstiger"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptziel, wenn ich IT-Prozesse auslagere?', 3, '[{"text": "Konzentration auf Kernkompetenzen", "correct": true, "because": "Ermöglicht Fokus auf Hauptgeschäft"}, {"text": "Maximale Kontrolle", "correct": false, "because": "Kontrolle nimmt ab"}, {"text": "Manuelle Verwaltung", "correct": false, "because": "Zu aufwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet die Auslagerung von IT-Diensten?', 5, '[{"text": "Zugriff auf Expertise", "correct": true, "because": "Spezialisten verbessern Qualität"}, {"text": "Kosteneffizienz", "correct": true, "because": "Skaleneffekte möglich"}, {"text": "Volle Kontrolle", "correct": false, "because": "Kontrolle reduziert"}, {"text": "Lokale Hardware", "correct": false, "because": "Nicht notwendig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Auslagerung reduziert internen Aufwand. b) Sie eliminiert alle Risiken.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) führt zu neuen Risiken"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Planung einer Auslagerung?', 4, '[{"text": "Vertragsdetails", "correct": false, "because": "Regeln Zusammenarbeit"}, {"text": "Servicequalität", "correct": false, "because": "Sichert Leistung"}, {"text": "Büroausstattung", "correct": true, "because": "Irrelevant für Auslagerung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Auslagerung immer externe Anbieter bedeutet?', 2, '[{"text": "Ja", "correct": true, "because": "Dritte übernehmen Aufgaben"}, {"text": "Nein", "correct": false, "because": "Externe Partner üblich"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium ist entscheidend für die Auswahl eines Partners?', 3, '[{"text": "Zuverlässigkeit", "correct": true, "because": "Sichert stabile Leistung"}, {"text": "Lokale Präsenz", "correct": false, "because": "Nicht immer nötig"}, {"text": "Manuelle Steuerung", "correct": false, "because": "Automatisierung bevorzugt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Risiken gibt es bei der Auslagerung?', 5, '[{"text": "Datenlecks", "correct": true, "because": "Externe Zugriffe möglich"}, {"text": "Abhängigkeit", "correct": true, "because": "Vertrauen in Anbieter nötig"}, {"text": "Hohe lokale Bandbreite", "correct": false, "because": "Nicht risikorelevant"}, {"text": "Eigene Expertise", "correct": false, "because": "Kein Risiko"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört: a) Auslagerung verbessert Skalierbarkeit. b) Sie ist immer offshore. Stimmt das?', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) kann lokal sein"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für eine erfolgreiche Auslagerung?', 4, '[{"text": "Vertragsmanagement", "correct": false, "because": "Regelt Zusammenarbeit"}, {"text": "Sicherheitsstandards", "correct": false, "because": "Schützen Daten"}, {"text": "Lokale Server", "correct": true, "because": "Externe Anbieter genutzt"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Ist Auslagerung nur für IT-Dienste?', 2, '[{"text": "Nein", "correct": true, "because": "Auch HR oder Logistik möglich"}, {"text": "Ja", "correct": false, "because": "Vielseitig einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Prozesse eignen sich für eine Auslagerung?', 4, '[{"text": "Support-Dienste", "correct": true, "because": "Skalierbar und standardisiert"}, {"text": "Cloud-Hosting", "correct": true, "because": "Externe Expertise nutzbar"}, {"text": "Strategische Planung", "correct": false, "because": "Kernkompetenz"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass Auslagerung die Qualität senkt. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Qualität hängt von Anbieter ab"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig niedriger"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich bei der Auslagerung von IT-Diensten?', 3, '[{"text": "Service-Level-Agreements", "correct": true, "because": "Definieren Leistung"}, {"text": "Lokale Teams", "correct": false, "because": "Nicht primär"}, {"text": "Manuelle Überwachung", "correct": false, "because": "Automatisierung besser"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Auslagerung spart Zeit. b) Sie erhöht interne Kompetenzen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) kann Kompetenzen reduzieren"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen eine Auslagerung erfolgreich?', 5, '[{"text": "Klare Verträge", "correct": true, "because": "Sichern Erwartungen"}, {"text": "Kommunikation", "correct": true, "because": "Fördert Zusammenarbeit"}, {"text": "Lokale Hardware", "correct": false, "because": "Nicht erforderlich"}, {"text": "Minimale Planung", "correct": false, "because": "Planung essenziell"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Auslagerung unwichtig?', 3, '[{"text": "Datenschutz", "correct": false, "because": "Schützt sensible Daten"}, {"text": "Anbieterzuverlässigkeit", "correct": false, "because": "Sichert Leistung"}, {"text": "Bürogestaltung", "correct": true, "because": "Kein Auslagerungsfaktor"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob Auslagerung immer langfristig ist?', 2, '[{"text": "Nein", "correct": true, "because": "Auch kurzfristig möglich"}, {"text": "Ja", "correct": false, "because": "Flexibel einsetzbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erfordert Auslagerung immer einen internationalen Anbieter?', 3, '[{"text": "Nein", "correct": true, "because": "Lokale Anbieter möglich"}, {"text": "Ja", "correct": false, "because": "Nicht zwangsläufig international"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Szenario passt zur Auslagerung?', 4, '[{"text": "Betreuung eines IT-Helpdesks", "correct": true, "because": "Standardisierbar und skalierbar"}, {"text": "Entwicklung der Unternehmensstrategie", "correct": false, "because": "Kernkompetenz"}, {"text": "Lokale Netzwerkwartung", "correct": false, "because": "Oft intern besser"}]');

