-- Öffentliche Daten.sql (Umgang mit frei zugänglichen Daten)
INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
('00000000-0000-0000-0000-000000000000', 'Sind öffentliche Daten immer frei von Lizenzbeschränkungen?', 2, '[{"text": "Nein", "correct": true, "because": "Oft gelten Nutzungsbedingungen"}, {"text": "Ja", "correct": false, "because": "Lizenzen wie CC können gelten"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist entscheidend, wenn ich frei zugängliche Daten nutze?', 3, '[{"text": "Lizenzprüfung", "correct": true, "because": "Sichert rechtliche Nutzung"}, {"text": "Maximale Datengröße", "correct": false, "because": "Nicht primär relevant"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte sind bei der Nutzung solcher Daten wichtig?', 5, '[{"text": "Datenqualität", "correct": true, "because": "Beeinflusst Analyseergebnisse"}, {"text": "Quellenangabe", "correct": true, "because": "Fördert Transparenz"}, {"text": "Hohe Kompression", "correct": false, "because": "Nicht entscheidend"}, {"text": "Echtzeitverarbeitung", "correct": false, "because": "Kontextabhängig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Öffentliche Daten sind immer aktuell. b) Sie dürfen kommerziell genutzt werden.', 3, '[{"text": "Beides falsch", "correct": true, "because": "Aktualität variiert, Nutzung oft eingeschränkt"}, {"text": "Beides stimmt", "correct": false, "because": "Beide sind kontextabhängig"}, {"text": "Nur a) stimmt", "correct": false, "because": "a) ist oft falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "b) ist nicht universell"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ignoriere ich bei der Verarbeitung frei zugänglicher Daten?', 4, '[{"text": "Datenherkunft", "correct": false, "because": "Wichtig für Vertrauen"}, {"text": "Formatierung", "correct": false, "because": "Erleichtert Verarbeitung"}, {"text": "Farbcodierung", "correct": true, "because": "Irrelevant für Analyse"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob öffentliche Daten immer anonymisiert sind?', 2, '[{"text": "Nein", "correct": true, "because": "Können personenbezogene Daten enthalten"}, {"text": "Ja", "correct": false, "because": "Nicht garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium ist bei der Auswahl solcher Daten entscheidend?', 3, '[{"text": "Vertrauenswürdigkeit der Quelle", "correct": true, "because": "Sichert Zuverlässigkeit"}, {"text": "Dateigröße", "correct": false, "because": "Sekundär"}, {"text": "Verfügbare Bandbreite", "correct": false, "because": "Nur für Download relevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Maßnahmen sichern den korrekten Umgang mit solchen Daten?', 5, '[{"text": "Lizenzkonformität", "correct": true, "because": "Vermeidet Rechtsverstöße"}, {"text": "Datenvalidierung", "correct": true, "because": "Stellt Qualität sicher"}, {"text": "Hohe Speicherkapazität", "correct": false, "because": "Nicht primär"}, {"text": "Automatische Übersetzung", "correct": false, "because": "Irrelevant"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass öffentliche Daten immer sicher sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Können Fehler oder Manipulationen enthalten"}, {"text": "Ja", "correct": false, "because": "Sicherheit nicht garantiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Was priorisiere ich, wenn ich frei zugängliche Daten analysiere?', 4, '[{"text": "Datenintegrität", "correct": true, "because": "Sichert korrekte Ergebnisse"}, {"text": "Schnelle Verarbeitung", "correct": false, "because": "Sekundär zur Qualität"}, {"text": "Minimale Speichernutzung", "correct": false, "because": "Weniger wichtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Öffentliche Daten brauchen Quellenangaben. b) Sie sind immer maschinenlesbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "b) hängt vom Format ab"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist nicht immer wahr"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist korrekt"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Format wähle ich für die Verarbeitung solcher Daten?', 4, '[{"text": "JSON oder CSV", "correct": true, "because": "Weit verbreitet und flexibel"}, {"text": "Proprietäres Format", "correct": false, "because": "Eingeschränkte Kompatibilität"}, {"text": "Bilddateien", "correct": false, "because": "Schwer analysierbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Habe gehört, dass solche Daten immer kostenlos sind. Stimmt das?', 2, '[{"text": "Nein", "correct": true, "because": "Manche erfordern Gebühren"}, {"text": "Ja", "correct": false, "because": "Kosten variieren"}]'),
('00000000-0000-0000-0000-000000000000', 'Was brauche ich nicht für den Umgang mit öffentlichen Daten?', 3, '[{"text": "Datenprüfung", "correct": false, "because": "Sichert Qualität"}, {"text": "Metadaten", "correct": false, "because": "Liefert Kontext"}, {"text": "Grafische Oberfläche", "correct": true, "because": "Nicht zwingend"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Sind öffentliche Daten immer global verfügbar?', 2, '[{"text": "Nein", "correct": true, "because": "Regionale Einschränkungen möglich"}, {"text": "Ja", "correct": false, "because": "Zugang kann limitiert sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen gibt es bei der Nutzung solcher Daten?', 4, '[{"text": "Inkonsistente Formate", "correct": true, "because": "Erschwert Verarbeitung"}, {"text": "Fehlende Metadaten", "correct": true, "because": "Reduziert Verständnis"}, {"text": "Hohe Bandbreite", "correct": false, "because": "Kein primäres Problem"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist bei der Veröffentlichung eigener Daten zu beachten?', 3, '[{"text": "Datenschutz", "correct": true, "because": "Schützt sensible Informationen"}, {"text": "Maximale Dateigröße", "correct": false, "because": "Sekundär"}, {"text": "Schnelle Uploads", "correct": false, "because": "Nicht entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Kannst du dich erinnern, ob öffentliche Daten immer maschinenlesbar sind?', 2, '[{"text": "Nein", "correct": true, "because": "Formate wie PDF sind problematisch"}, {"text": "Ja", "correct": false, "because": "Nicht immer strukturiert"}]'),
('00000000-0000-0000-0000-000000000000', 'Wie war das nochmal? Erfordern solche Daten immer eine Registrierung?', 3, '[{"text": "Nein", "correct": true, "because": "Oft frei zugänglich"}, {"text": "Ja", "correct": false, "because": "Nicht immer nötig"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Tool hilft mir, öffentliche Daten effizient zu analysieren?', 4, '[{"text": "Datenanalyse-Frameworks", "correct": true, "because": "Wie Pandas oder SQL"}, {"text": "Texteditor", "correct": false, "because": "Zu eingeschränkt"}, {"text": "Bildbearbeitung", "correct": false, "because": "Nicht relevant"}]');


