-- # Lernfeld 5: Cyberphysische Systeme > ## Testgetriebene Entwicklung > - Werkzeuge > - Test-Frameworks > - JUnit

INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Ist JUnit ein Test-Framework, das speziell für die testgetriebene Entwicklung (TDD) in Java entwickelt wurde?', 2, '[{"text": "Ja", "correct": true, "because": "JUnit unterstützt TDD in Java"}, {"text": "Nein", "correct": false, "because": "Hauptzweck ist TDD-Unterstützung"}]'),
('00000000-0000-0000-0000-000000000000', 'Kann JUnit ohne Integration in eine Entwicklungsumgebung wie Eclipse verwendet werden?', 2, '[{"text": "Ja", "correct": true, "because": "JUnit ist eigenständig nutzbar"}, {"text": "Nein", "correct": false, "because": "Keine zwingende IDE erforderlich"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen mit JUnit erstellte Tests immer manuell ausgeführt werden?', 2, '[{"text": "Nein", "correct": true, "because": "JUnit unterstützt automatisierte Ausführung"}, {"text": "Ja", "correct": false, "because": "Automatisierung ist Standard"}]'),
('00000000-0000-0000-0000-000000000000', 'Können JUnit-Tests in TDD auch Integrationstests abdecken?', 2, '[{"text": "Ja", "correct": true, "because": "JUnit ist flexibel einsetzbar"}, {"text": "Nein", "correct": false, "because": "Nicht auf Unit-Tests beschränkt"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist JUnit ausschließlich für Java-Projekte in TDD geeignet?', 2, '[{"text": "Ja", "correct": true, "because": "JUnit ist Java-spezifisch"}, {"text": "Nein", "correct": false, "because": "Primär für Java entwickelt"}]'),

-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Funktion erfüllt JUnit in der testgetriebenen Entwicklung?', 2, '[{"text": "Automatisierung von Unit-Tests", "correct": true, "because": "Hauptzweck von JUnit"}, {"text": "Erstellung von Dokumentation", "correct": false, "because": "Nicht primär"}, {"text": "Code-Optimierung", "correct": false, "because": "Keine Optimierungsfunktion"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Annotation wird in JUnit verwendet, um einen Testfall zu kennzeichnen?', 3, '[{"text": "@Test", "correct": true, "because": "Markiert Testmethoden"}, {"text": "@Before", "correct": false, "because": "Vorbereitung, kein Test"}, {"text": "@After", "correct": false, "because": "Nachbereitung, kein Test"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Phase des TDD-Zyklus wird durch JUnit direkt unterstützt?', 2, '[{"text": "Rot-Phase", "correct": true, "because": "Tests schlagen zunächst fehl"}, {"text": "Grün-Phase", "correct": false, "because": "Nach Korrektur"}, {"text": "Refactor-Phase", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Feature von JUnit hilft, Testfälle zu organisieren?', 2, '[{"text": "Test-Suiten", "correct": true, "because": "Gruppierung von Tests"}, {"text": "Assertions", "correct": false, "because": "Prüft Bedingungen"}, {"text": "Timeouts", "correct": false, "because": "Begrenzt Laufzeit"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aussage beschreibt JUnit am besten in Bezug auf TDD?', 2, '[{"text": "Es ermöglicht schnelle Testausführung", "correct": true, "because": "Unterstützt TDD-Zyklus"}, {"text": "Es ersetzt manuelle Tests vollständig", "correct": false, "because": "Ergänzung möglich"}, {"text": "Es optimiert die Laufzeit des Codes", "correct": false, "because": "Kein Optimierungstool"}]'),

-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Funktionen bietet JUnit für TDD?', 4, '[{"text": "Automatisierte Testausführung", "correct": true, "because": "Kernfunktion"}, {"text": "Assertion-Methoden", "correct": true, "because": "Prüft Ergebnisse"}, {"text": "Code-Generierung", "correct": false, "because": "Nicht Aufgabe von JUnit"}, {"text": "Test-Suiten", "correct": true, "because": "Organisiert Tests"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bringt JUnit in TDD?', 3, '[{"text": "Schnelle Rückmeldung", "correct": true, "because": "Tests sofort ausführbar"}, {"text": "Einfache Testfallerstellung", "correct": true, "because": "Annotations erleichtern"}, {"text": "Langsamere Entwicklung", "correct": false, "because": "Beschleunigt Prozess"}, {"text": "Verbesserte Fehlererkennung", "correct": true, "because": "Fehlschläge sichtbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Annotations sind in JUnit für TDD wichtig?', 3, '[{"text": "@Test", "correct": true, "because": "Markiert Testmethoden"}, {"text": "@Before", "correct": true, "because": "Vorbereitung vor Tests"}, {"text": "@Compile", "correct": false, "because": "Keine JUnit-Annotation"}, {"text": "@After", "correct": true, "because": "Aufräumen nach Tests"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Herausforderungen können bei der Nutzung von JUnit in TDD auftreten?', 4, '[{"text": "Lernkurve für Anfänger", "correct": true, "because": "Annotations erfordern Wissen"}, {"text": "Wartung der Test-Suite", "correct": true, "because": "Änderungen nötig"}, {"text": "Keine Integration möglich", "correct": false, "because": "Gut integrierbar"}, {"text": "Komplexität bei großen Projekten", "correct": true, "because": "Viele Tests zu verwalten"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Aspekte machen JUnit zu einem geeigneten Werkzeug für TDD?', 3, '[{"text": "Schnelle Testausführung", "correct": true, "because": "Fördert Iterationen"}, {"text": "Unterstützung für Assertions", "correct": true, "because": "Prüft Erwartungen"}, {"text": "Hohe Laufzeitkosten", "correct": false, "because": "Effizient"}, {"text": "Flexibilität bei Testarten", "correct": true, "because": "Unit- und mehr"}]'),

-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) JUnit ist ein Kernwerkzeug für TDD in Java. b) JUnit kann keine Integrationstests unterstützen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "JUnit zentral, Integration möglich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) JUnit erfordert manuelle Testausführung. b) JUnit unterstützt den Rot-Grün-Refaktor-Zyklus.', 3, '[{"text": "Nur b) stimmt", "correct": true, "because": "Automatisierung Standard, Zyklus unterstützt"}, {"text": "Beides stimmt", "correct": false, "because": "a) ist falsch"}, {"text": "Nur a) stimmt", "correct": false, "because": "b) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "b) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) JUnit-Tests beschleunigen die Fehlererkennung in TDD. b) JUnit ist nur für kleine Projekte geeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Fehler schnell sichtbar, Größe flexibel"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) JUnit kann Test-Suiten organisieren. b) JUnit ersetzt die Notwendigkeit von Debugging.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Suiten möglich, Debugging ergänzend"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) JUnit unterstützt Assertions zur Überprüfung. b) JUnit ist für TDD in Python optimiert.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Assertions zentral, JUnit für Java"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

