INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Software > Auswahl > Marktgängige IT-Systeme & Lösungen
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Können marktgängige IT-Systeme unabhängig von den Unternehmensanforderungen ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Systeme müssen an Bedürfnisse angepasst sein"}, {"text": "Ja", "correct": false, "because": "Ohne Anpassung ineffizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen bei der Auswahl marktgängiger IT-Systeme immer die Kosten berücksichtigt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Budget beeinflusst Entscheidung"}, {"text": "Nein", "correct": false, "because": "Kosten sind zentral"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Kompatibilität mit bestehender Hardware bei der Auswahl marktgängiger IT-Systeme irrelevant?', 2, '[{"text": "Nein", "correct": true, "because": "Kompatibilität sichert Funktion"}, {"text": "Ja", "correct": false, "because": "Integration ist entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Können marktgängige IT-Systeme ohne Rücksicht auf die Benutzerfreundlichkeit ausgewählt werden?', 2, '[{"text": "Nein", "correct": true, "because": "Benutzerfreundlichkeit beeinflusst Akzeptanz"}, {"text": "Ja", "correct": false, "because": "Nutzung muss effizient sein"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind marktgängige IT-Systeme immer Open-Source-Lösungen?', 2, '[{"text": "Nein", "correct": true, "because": "Viele sind proprietär"}, {"text": "Ja", "correct": false, "because": "Nicht ausschließlich Open Source"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor ist bei der Auswahl marktgängiger IT-Systeme am wichtigsten?', 3, '[{"text": "Unternehmensanforderungen", "correct": true, "because": "Bestimmen Funktion und Nutzen"}, {"text": "Markenbekanntheit", "correct": false, "because": "Sekundär"}, {"text": "Design", "correct": false, "because": "Ästhetisch, nicht primär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches marktgängige IT-System wird häufig für Textverarbeitung eingesetzt?', 2, '[{"text": "Microsoft Word", "correct": true, "because": "Weit verbreitet und funktional"}, {"text": "Adobe Photoshop", "correct": false, "because": "Für Bildbearbeitung"}, {"text": "AutoCAD", "correct": false, "because": "Für technische Zeichnungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Kriterium beeinflusst die Wahl eines IT-Systems stark?', 2, '[{"text": "Skalierbarkeit", "correct": true, "because": "Ermöglicht Wachstum"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}, {"text": "Installationszeit", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches marktgängige IT-System ist für Unternehmensressourcenplanung typisch?', 3, '[{"text": "SAP", "correct": true, "because": "Führend in ERP"}, {"text": "Linux", "correct": false, "because": "Betriebssystem"}, {"text": "Zoom", "correct": false, "because": "Kommunikation"}]'),
('00000000-0000-0000-0000-000000000000', 'Was ist ein Hauptvorteil marktgängiger IT-Systeme?', 2, '[{"text": "Breite Unterstützung", "correct": true, "because": "Viele Nutzer und Ressourcen"}, {"text": "Geringste Kosten", "correct": false, "because": "Nicht immer günstig"}, {"text": "Minimale Funktionen", "correct": false, "because": "Umfassend ausgestattet"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Kriterien beeinflussen die Auswahl marktgängiger IT-Systeme?', 4, '[{"text": "Kompatibilität", "correct": true, "because": "Sichert Integration"}, {"text": "Kosten", "correct": true, "because": "Budget ist entscheidend"}, {"text": "Benutzerfreundlichkeit", "correct": true, "because": "Erleichtert Nutzung"}, {"text": "Farbe der Oberfläche", "correct": false, "because": "Ästhetisch, nicht funktional"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche marktgängigen IT-Systeme sind für Büroanwendungen typisch?', 3, '[{"text": "Microsoft Office", "correct": true, "because": "Text und Tabellen"}, {"text": "Google Workspace", "correct": true, "because": "Cloud-basierte Lösung"}, {"text": "LibreOffice", "correct": true, "because": "Open-Source-Alternative"}, {"text": "AutoCAD", "correct": false, "because": "Technische Zeichnungen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bieten marktgängige IT-Systeme?', 3, '[{"text": "Gute Support-Struktur", "correct": true, "because": "Herstellerunterstützung"}, {"text": "Breite Verfügbarkeit", "correct": true, "because": "Leicht zugänglich"}, {"text": "Regelmäßige Updates", "correct": true, "because": "Sicherheit und Funktionen"}, {"text": "Minimale Anpassbarkeit", "correct": false, "because": "Oft anpassbar"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können bei der Auswahl marktgängiger IT-Systeme auftreten?', 4, '[{"text": "Hohe Lizenzkosten", "correct": true, "because": "Proprietäre Lösungen teuer"}, {"text": "Kompatibilitätsprobleme", "correct": true, "because": "Mit bestehender Hardware"}, {"text": "Komplexität", "correct": true, "because": "Schulung erforderlich"}, {"text": "Geringe Verfügbarkeit", "correct": false, "because": "Weit verbreitet"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren machen marktgängige IT-Systeme attraktiv?', 3, '[{"text": "Skalierbarkeit", "correct": true, "because": "Passt sich Wachstum an"}, {"text": "Benutzerunterstützung", "correct": true, "because": "Hilft bei Problemen"}, {"text": "Bewährte Zuverlässigkeit", "correct": true, "because": "Getestete Lösungen"}, {"text": "Minimaler Funktionsumfang", "correct": false, "because": "Umfassend ausgestattet"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Marktgängige IT-Systeme müssen mit bestehender Hardware kompatibel sein. b) Sie sind immer kostenfrei verfügbar.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kompatibilität ja, nicht kostenfrei"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Microsoft Office ist ein marktgängiges IT-System für Büroanwendungen. b) Skalierbarkeit ist bei der Auswahl irrelevant.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Office ja, Skalierbarkeit wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Marktgängige IT-Systeme bieten oft gute Unterstützung. b) Sie sind ausschließlich Open-Source-Lösungen.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Unterstützung ja, nicht nur Open Source"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Kosten sind ein entscheidender Faktor bei der Auswahl marktgängiger IT-Systeme. b) Benutzerfreundlichkeit spielt keine Rolle.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Kosten ja, Benutzerfreundlichkeit wichtig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) SAP ist ein marktgängiges ERP-System. b) Marktgängige IT-Systeme sind immer für kleine Unternehmen ungeeignet.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "SAP ja, auch für kleine Firmen"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

