INSERT INTO temporary_questions (essence_fk, text, points, options) VALUES
-- Lernfeld 1 > Software > Konfiguration und Inbetriebnahme > Software-Konfiguration
-- Ja/Nein-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Kann die Software-Konfiguration unabhängig von den Benutzeranforderungen erfolgen?', 2, '[{"text": "Nein", "correct": true, "because": "Anforderungen bestimmen Einstellungen"}, {"text": "Ja", "correct": false, "because": "Ohne Anpassung ineffizient"}]'),
('00000000-0000-0000-0000-000000000000', 'Müssen bei der Software-Konfiguration immer die Systemvoraussetzungen geprüft werden?', 2, '[{"text": "Ja", "correct": true, "because": "Sichert Funktion auf der Hardware"}, {"text": "Nein", "correct": false, "because": "Voraussetzungen sind entscheidend"}]'),
('00000000-0000-0000-0000-000000000000', 'Ist die Software-Konfiguration abgeschlossen, sobald die Software installiert ist?', 2, '[{"text": "Nein", "correct": true, "because": "Einstellungen und Tests folgen"}, {"text": "Ja", "correct": false, "because": "Konfiguration geht weiter"}]'),
('00000000-0000-0000-0000-000000000000', 'Können Software-Konfigurationen ohne Dokumentation durchgeführt werden?', 2, '[{"text": "Ja", "correct": true, "because": "Technisch möglich, aber nicht empfohlen"}, {"text": "Nein", "correct": false, "because": "Dokumentation ist Best Practice"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind Software-Konfigurationen immer plattformunabhängig?', 2, '[{"text": "Nein", "correct": true, "because": "Abhängig vom Betriebssystem"}, {"text": "Ja", "correct": false, "because": "Plattform beeinflusst Einstellungen"}]'),
-- Single-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welcher Schritt ist bei der Software-Konfiguration am wichtigsten?', 3, '[{"text": "Anforderungsanalyse", "correct": true, "because": "Basis für passende Einstellungen"}, {"text": "Installation", "correct": false, "because": "Voraussetzung, nicht Kern"}, {"text": "Update", "correct": false, "because": "Späterer Schritt"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Werkzeug wird oft für die Software-Konfiguration verwendet?', 2, '[{"text": "Konfigurationsassistent", "correct": true, "because": "Führt durch Einstellungen"}, {"text": "Textverarbeitung", "correct": false, "because": "Nicht technisch"}, {"text": "Hardware-Diagnose", "correct": false, "because": "Für Hardware"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Komponente beeinflusst die Software-Konfiguration maßgeblich?', 2, '[{"text": "Betriebssystem", "correct": true, "because": "Definiert Umgebung"}, {"text": "Monitor", "correct": false, "because": "Peripheriegerät"}, {"text": "Tastatur", "correct": false, "because": "Eingabegerät"}]'),
('00000000-0000-0000-0000-000000000000', 'Welches Ziel verfolgt die Software-Konfiguration primär?', 3, '[{"text": "Optimale Funktionalität", "correct": true, "because": "Erfüllt Nutzerbedürfnisse"}, {"text": "Minimale Kosten", "correct": false, "because": "Sekundär"}, {"text": "Schnelle Installation", "correct": false, "because": "Nicht Hauptziel"}]'),
('00000000-0000-0000-0000-000000000000', 'Welcher Faktor kann die Software-Konfiguration erschweren?', 2, '[{"text": "Inkompatibilität", "correct": true, "because": "Einschränkt Einstellungen"}, {"text": "Farbschema", "correct": false, "because": "Ästhetisch"}, {"text": "Lieferzeit", "correct": false, "because": "Logistisch"}]'),
-- Multiple-Choice-Fragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Welche Schritte gehören zur Software-Konfiguration?', 4, '[{"text": "Installation", "correct": true, "because": "Erster Schritt"}, {"text": "Einstellungen anpassen", "correct": true, "because": "Kern der Konfiguration"}, {"text": "Testen", "correct": true, "because": "Sichert Funktion"}, {"text": "Hardware austauschen", "correct": false, "because": "Nicht softwarebezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Faktoren beeinflussen die Software-Konfiguration?', 3, '[{"text": "Benutzeranforderungen", "correct": true, "because": "Bestimmen Einstellungen"}, {"text": "Systemvoraussetzungen", "correct": true, "because": "Hardwareabhängig"}, {"text": "Netzwerkumgebung", "correct": true, "because": "Beeinflusst Zugriff"}, {"text": "Farbe der Oberfläche", "correct": false, "because": "Ästhetisch"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Probleme können bei der Software-Konfiguration auftreten?', 3, '[{"text": "Inkompatibilität", "correct": true, "because": "Verhindert Funktion"}, {"text": "Fehlende Dokumentation", "correct": true, "because": "Erschwert Anpassung"}, {"text": "Falsche Einstellungen", "correct": true, "because": "Beeinträchtigt Nutzung"}, {"text": "Langsame Hardware", "correct": false, "because": "Sekundär"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Elemente werden bei der Software-Konfiguration angepasst?', 4, '[{"text": "Benutzerrechte", "correct": true, "because": "Definiert Zugriff"}, {"text": "Netzwerkeinstellungen", "correct": true, "because": "Sichert Verbindung"}, {"text": "Spezifische Parameter", "correct": true, "because": "Passt an Bedürfnisse an"}, {"text": "Hardwarefarbe", "correct": false, "because": "Nicht softwarebezogen"}]'),
('00000000-0000-0000-0000-000000000000', 'Welche Vorteile bietet eine gute Software-Konfiguration?', 3, '[{"text": "Erhöhte Effizienz", "correct": true, "because": "Optimiert Nutzung"}, {"text": "Bessere Sicherheit", "correct": true, "because": "Schützt Daten"}, {"text": "Anpassungsfähigkeit", "correct": true, "because": "Passt an Veränderungen"}, {"text": "Geringere Kosten", "correct": false, "because": "Nicht primär"}]'),
-- Richtig/Falsch-Kombinationsfragen (5 Stück)
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen richtig? a) Software-Konfiguration berücksichtigt Benutzeranforderungen. b) Sie ist unabhängig vom Betriebssystem.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Anforderungen ja, OS relevant"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen korrekt? a) Systemvoraussetzungen müssen vor der Konfiguration geprüft werden. b) Konfiguration endet mit der Installation.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Prüfung ja, Konfiguration weiter"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Konfigurationsassistenten erleichtern die Software-Konfiguration. b) Dokumentation ist bei der Konfiguration unnötig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Assistenten ja, Dokumentation hilfreich"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind folgende Aussagen korrekt? a) Netzwerkeinstellungen sind Teil der Software-Konfiguration. b) Software-Konfiguration ist immer plattformunabhängig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Netzwerk ja, Plattformabhängig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]'),
('00000000-0000-0000-0000-000000000000', 'Sind diese Aussagen richtig? a) Eine gute Software-Konfiguration steigert die Effizienz. b) Tests sind nach der Konfiguration überflüssig.', 3, '[{"text": "Nur a) stimmt", "correct": true, "because": "Effizienz ja, Tests nötig"}, {"text": "Beides stimmt", "correct": false, "because": "b) ist falsch"}, {"text": "Nur b) stimmt", "correct": false, "because": "a) ist richtig"}, {"text": "Beides falsch", "correct": false, "because": "a) ist richtig"}]');

